### ISSUE TITLE
https redirect error

### ISSUE THREAD

**Issue by xxrlzzz** [yhirose/cpp-httplib#1003]
hey guys, I'm using this library to do little project, and with a problem. 

### Problem Description:

When I want send http request with `Client`,  it may fail to get response when the server require redirect from http request to https request. 

### My way to resolve

I found I need to call `set_ca_cert_path`, but it lost during redirect, `copy_settings` don't copy ca cert path, and I found `client_cert_path_` and `client_key_path_`, but no else place was using this.   
`SSLClient` actually using `ca_cert_file_path_` and `ca_cert_dir_path_`. I don't know relation between them.  
Currently I'm setting `ca_cert_file_path_` and `ca_cert_dir_path_` in `copy_settings`. It works for me. It may be a bug or just my wrong usage. looking for your reply.

**Comment by yhirose** [comment]
@xxrlzzz, thanks for the feedback. It sounds like a bug. Could you send a pull request with your fix and a unit test if possible? Then, I'll review it soon. Thanks!

**Comment by yhirose** [comment]
Resolved by #1004.
