### ISSUE TITLE
library crashed with GCC < 4.9

### ISSUE THREAD

**Issue by folibis** [yhirose/cpp-httplib#1005]
The library that was compiled with gcc < 4.9 crashed with error:
`terminate called after throwing an instance of 'std::regex_error'`
It looks that regex support was fixed in gcc 4.9, for earlier versions there is some bug(s) that does not allow you to work with the library. The problem that most of embedded systems (where you actually need some embedded web server like this) use old compilers.

**Comment by yhirose** [comment]
https://github.com/yhirose/cpp-httplib/search?q=regex_error&type=issues

**Comment by yhirose** [comment]
https://github.com/yhirose/cpp-httplib#g
