### ISSUE TITLE
Is it possible to flush() the DataSink within a chunked response?

### ISSUE THREAD

**Issue by blaubart69** [yhirose/cpp-httplib#1009]
Something like sink.flush() with is not available.
To push the bytes to the browser.

Thank you very much for you help!

~~~
{
    httplib::Server svr;

    svr.Get("/chunked", [&](const Request& req, Response& res) {
      
      res.set_chunked_content_provider(
        "text/plain",
        [](size_t offset, httplib::DataSink &sink) {
            for (int i=0;i<10;++i) {
                sink.write("123",3);
                // FLUSH
                // sink.flush() ???
                std::this_thread::sleep_for( std::chrono::milliseconds(1000) );
            }

          sink.done(); // No more data
          return true; // return 'false' if you want to cancel the process.
        }
      );
    });

    svr.listen("0.0.0.0", 8080);

    return 0;
}
~~~

**Comment by PixlRainbow** [comment]
as far as I can tell, we do not have any internal stream buffer within httplib; calling `write` immediately writes to the socket stream.  

However, if you want the system-level socket stream itself to always flush to peer when `write` is called, you can do `svr.set_tcp_nodelay(true)`. Note that this only affects connections that have been established after the setting is changed, and this setting is server-wide (affects all request handlers).

**Comment by yhirose** [comment]
Hope this helps.
https://stackoverflow.com/questions/914286/what-does-it-mean-to-flush-a-socket

**Comment by blaubart69** [comment]
Thank you all for your answers!!
I'll integrate httplib in my "real-world-app" and see if it work's. :-)
btw: httplib is the 3rd lib/framework I'm trying. hopefully the last one! :-)

The real-world app (http-server-part) is sending JPEG images captured from a camera in an infinite loop to the browser.
One image is around 15kB in size.

Pseudo code:
~~~
... cut ...
set("ContentType", "multipart/x-mixed-replace;boundary=Ba4oTvQMY8ew04N8dcnM");
for (;;) {
  write("--Ba4oTvQMY8ew04N8dcnM\r\nContent-Type: image/jpeg\r\n\r\n");  //boundary
  write(bytesOfTheJPEGImage);
  write("\r\n");
}
... cut ...
~~~

**Comment by blaubart69** [comment]
Now it's working!
--> https://github.com/hfrebort/traktor/blob/6edc332312bb73013f6ad1a4c5fbf10c682664a4/src/webserver.cpp#L24

Thanks for writing cpp-httplib! :-)
