### ISSUE TITLE
Stuck at trying to show html page

### ISSUE THREAD

**Issue by mptyy** [yhirose/cpp-httplib#1014]
Hello! As title says, I'm stuck at trying to show .html page in browser. In page I've connected some stuff like jQuery, bootstrap etc... I haven't found any examples on how to do it so that's why i opened this issue, sorry in advance.
Here's my code how i tried to do it:

std::string page;

std::string line;
std::ifstream in("index.html");

while (std::getline(in, line))
{
        page += "\n";
        page += line;
}

svr.Get("/", [](const Request& req, Response& res) {
      res.set_header("Access-Control-Allow-Origin", "*");
      const char* webPage = page.c_str();
      char buf[BUFSIZ];
      snprintf(buf, sizeof(buf), webPage, res.status);
      res.set_content(buf, "text/html");
      });

Of course I need to say that's I'm pretty "new" to c++, at least I wasn't doing "web stuff" before. Thanks in advance!

**Comment by yhirose** [comment]
You can find some server examples in [`example`](https://github.com/yhirose/cpp-httplib/tree/master/example) folder.
Hope it helps!

**Comment by mptyy** [comment]
@yhirose  sorry, but I haven't found there what I'm looking for.

**Comment by mptyy** [comment]
SORRY! I've made a mistake, everything works now! Ty!
