### ISSUE TITLE
Parameters with GET.

### ISSUE THREAD

**Issue by callingpizza** [yhirose/cpp-httplib#1016]
I was wondering how I can add parameters with GET requests? It's not in the documentation.

**Comment by PixlRainbow** [comment]
You can use any of these method calls, if you are referring to Get requests on the Client
https://github.com/yhirose/cpp-httplib/blob/887074efd2ebb9c7c6513082f12fe23971d19f43/httplib.h#L7513-L7528
Alternatively, you may call `httplib::detail::append_query_params` and append the parameters as a query string onto the end of your path string, then pass the complete string to the Client as a Get path.
https://github.com/yhirose/cpp-httplib/blob/887074efd2ebb9c7c6513082f12fe23971d19f43/httplib.h#L3504-L3510

**Comment by yhirose** [comment]
Here is another way to do it.
https://github.com/yhirose/cpp-httplib/blob/887074efd2ebb9c7c6513082f12fe23971d19f43/test/test.cc#L2980

**Comment by callingpizza** [comment]
Thank you all!
