### ISSUE TITLE
Feature Request: Bind to multiple interfaces (not just 127.0.0.1 or localhost)

### ISSUE THREAD

**Issue by sinfloodmusic** [yhirose/cpp-httplib#102]
Hi!  Great library!  Noticed I have provide an specific ip or 'localhost' to listen when starting the server can't specify an '*' or pass an empty string to listen to any ip address on my machine.  Makes it tricky in a DHCP environment when I want another system to talk to my app as things move around.  Or maybe I'm just missing something and not seeing it.

I think binding with INADDR_ANY is what's needed.  <https://stackoverflow.com/questions/12709771/how-to-bind-a-socket-to-multiple-interfaces> Perhaps if the hostname/ip passed to the Listen() method '*' or empty you bind on all interfaces?

Thanks again for making this library!

**Comment by yhirose** [comment]
@sinfloodmusic, can you try '0.0.0.0'?

**Comment by sinfloodmusic** [comment]
Ugh - I could have sworn I tried that and it didn't work!  But just tried again, and yes, thank you, that worked.  Might be good to have in the examples just to know you've got that use case taken care of.  Thanks!!!

**Comment by yhirose** [comment]
Thank you! I updated README to mention this.

**Comment by ifplusor** [comment]
How to bind any ip both IPv4 and IPv6?
