### ISSUE TITLE
The content length in the client is smaller than the one sent by the server

### ISSUE THREAD

**Issue by henriquenunez** [yhirose/cpp-httplib#1022]
Hi, amazing library.

I'm trying to build an application that sends a raw image, and a client that receives it.

The problem I'm having is that I'm expecting to receive 1536000 byes, but the client only receives 4096. Testing on cURL, I get a good response, with the correct length, so i suppose the problem is not with the server.

The client code is the following:
```cpp
httplib::Result res = httpClients[i] -> Get("/data",
  [ & ](const char * rec_data, size_t rec_data_length) {
    rec_last_data_size = rec_data_length;
    printf("Content length: %zu == %zu ? %d\n", rec_data_length, my_data_size, rec_data_length == my_data_size);
    if (rec_data_length != my_data_size) {
      printf("TOO BAD!\n");
      std::cin.get();
      return true;
    }
    memcpy(data, rec_data, rec_data_length);
    return true;
  });
```

The server code:
```cpp
    svr.Get("/data", [](const httplib::Request&, httplib::Response& res) {
        printf("Size: %zu\n", my_data_size);
        res.set_content(my_data, my_data_size, "application/octet-stream");
    });
```

It's also worth mentioning that I'm on Windows, using visual studio 2019.

I'm using Qt for my application, and there's no `#include<Windows.h>`, so I'm just including httplib. Could this be the issue?

Thank you

**Comment by PixlRainbow** [comment]
you appear to be using the streaming content receiver callback on your client. Your callback will be called multiple times as incoming data is received. The data length parameter is not the length of the whole received body, it is the length of a fragment.

**Comment by yhirose** [comment]
I guess in your case, just the simple regular interface is enough.

```cpp
auto res = cli.get("/data");
auto p = res.body.data();
auto l = res.body.size();
```
