### ISSUE TITLE
Please add to README how to run tests

### ISSUE THREAD

**Issue by yurivict** [yhirose/cpp-httplib#1027]
Is there a make target?

There doesn't seem to be a cmake option that enables tests.

**Comment by yhirose** [comment]
The unit test is not integrated into CMake. What you need to do is `cd test; make`. Hope it helps.

**Comment by yhirose** [comment]
@sum01, do you have anything else to add to my comment, because it's a question about cmake? Thanks!

**Comment by sum01** [comment]
Not really. As you said, I never bothered adding test support into Cmake.
I suppose I could, but it would be a bit of work, and I don't have tons of time to keep up with all the additional tests that get added by people.
