### ISSUE TITLE
3 tests fail on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [yhirose/cpp-httplib#1028]
```
[ RUN      ] CancelTest.WithCancelLargePayload_Online
test.cc:631: Failure
Value of: !res
  Actual: false
Expected: true
[  FAILED  ] CancelTest.WithCancelLargePayload_Online (1090 ms)
[----------] 3 tests from CancelTest (3042 ms total)

[----------] 1 test from BaseAuthTest
[ RUN      ] BaseAuthTest.FromHTTPWatch_Online
test.cc:674: Failure
Expected equality of these values:
  401
  res->status
    Which is: 502
[  FAILED  ] BaseAuthTest.FromHTTPWatch_Online (5435 ms)
[----------] 1 test from BaseAuthTest (5435 ms total)
[...]
[ RUN      ] ServerTest.SlowPostFail
test.cc:2656: Failure
Value of: !res
  Actual: false
Expected: true
[  FAILED  ] ServerTest.SlowPostFail (2751 ms)
```

FreeBSD 13

**Comment by yhirose** [comment]
@yurivict, thanks for the feedbak. Honestly, I have never used FreeBSD in the past. So could you take a look at these problems a bit more deeper to figure out what are causing them? (At least as for BaseAUthTest.FromHTTPWatch_Online, it seems it's not a bug in cpp-httplib, but your network environment since it returns 502. Are you directly connect to httplib.org? If you are connecting it via proxy, could you turn is off?)
Thanks a lot!

**Comment by yhirose** [comment]
@yurivict, I have just tried to install FreeBSD 13 on Vagrant in my iMac. I built the unit test exe with a minor changes for brotli include and library paths in Makefile. And I was able to run all the unit test successfully.

![image](https://user-images.githubusercontent.com/357397/130715276-8153aa74-d142-401a-ab55-07664948ea79.png)

Please let me know if I am missing something to reproduce the problem that you experienced. Thanks!

**Comment by yurivict** [comment]
I don't know why did you close it, because ```cd /usr/ports/www/cpp-httplib && make deinstall clean test``` fails intermittently - 1-3 cases fail. Sometimes all of them pass.

(Current ports tree /usr/ports is required because tests were only added today to the port.)

**Comment by PixlRainbow** [comment]
the tests that failed depend on test servers hosted by third parties. Depending on your network setup, and depending on the load being experienced by the third parties, tests may sometimes fail.
