### ISSUE TITLE
Sending POST json request

### ISSUE THREAD

**Issue by freakovision** [yhirose/cpp-httplib#1029]
Hello, I'm trying to send POST json request to my discord webhook, but it returns the "400 Bad request" error. How do I make it work? 

Here's my code:
```
using namespace httplib;

int main(void) {
	Client cli("discordapp.com");
	
	if (auto res = cli.Post("discordapp.com/api/webhooks/mywebhook", "{ \"username\":\"freakovision\", \"content\": \"dude\" }", "application/json"))
	{
		std::cout << res->status << std::endl;
		std::cout << res->get_header_value("Content-Type") << std::endl;
		std::cout << res->body << std::endl;
	} 
	else 
		std::cout << res.error() << std::endl;
	
	std::cin.get();
	return 0;
}
```

Sorry for such a noob question. I'm bad at coding.

**Comment by sum01** [comment]
The first arg to `Client::Post` should be your endpoint, not the full path.
See https://github.com/yhirose/cpp-httplib#post

Sidenote: HTTPS is really easy to use, you probably want to use it (if you compiled with OpenSSL).
Compression is also similarly easy (if the API supports it & you compiled with ZLIB).

**Comment by freakovision** [comment]
Thanks for the quick answer. When I change full path to just endpoint I get Error 301.

**Comment by sum01** [comment]
I'm not familiar with Discord's API, but are you sure your path & endpoint are correct?

I just created a webhook to look at it and it has this form: `https://discord.com/api/webhooks/longstringofnumbershere/evenlongerstringofnumscharsandlettershere`

**Comment by freakovision** [comment]
Yes, I'm sure it's correct, because I used it with other libraries.

**Comment by braindigitalis** [comment]
```Client cli("discordapp.com");```

should be:

```Client cli("https://discordapp.com");```

it's trying to redirect you to the https version of the API endpoint.

**Comment by freakovision** [comment]
I have no idea how to use HTTPS. Downloaded libssl.a and libcrypto.a and trying to include it in cmakelists, but nothing works. 
Is there a way to specify it to use HTTP instead of HTTPS?

**Comment by braindigitalis** [comment]
Yes you have to set a #define value before you include the header, and OpenSSL has to be available.
The define variable is ```#define CPPHTTPLIB_OPENSSL_SUPPORT```
see here for an example of using this lib to access discord, as I made a C++ discord lib that makes use of it:

https://github.com/brainboxdotcc/DPP/blob/master/src/dpp/queues.cpp

**Comment by freakovision** [comment]
Where do I get the openssl lib and include files?

**Comment by sum01** [comment]
https://github.com/yhirose/cpp-httplib/issues/1029#issuecomment-904967886
If you're already using Cmake, it might be easy enough to just use the Cmake integration cpp-httplib already has, instead of manually building it yourself, either by using `find_package(httplib REQUIRED)` if you installed httplib, or using `add_subdirectory` along with a git submodule.

It'll (try to) find OpenSSL for you, which you can check via the `HTTPLIB_IS_USING_OPENSSL` bool after running `find_package`. Something like this is what I do...
```cmake
find_package(httplib REQUIRED)
if(NOT HTTPLIB_IS_USING_OPENSSL)
  message(FATAL_ERROR "OpenSSL support is missing in cpp-httplib")
endif()
target_link_libraries(yourexe httplib::httplib)
```

If this is on Windows, there's a couple places you can grab OpenSSL binaries. If it's Linux you should already have it most likely.

**Comment by yhirose** [comment]
@freakovision, since this isn't an issue in cpp-httplib, I'll close it. Hope the above comments help you!

**Comment by PixlRainbow** [comment]
> Is there a way to specify it to use HTTP instead of HTTPS?

For security reasons, Discord does not permit the use of insecure connections. All attempts to connect to Discord API using unencrypted HTTP will be rejected by Discord's servers.
