### ISSUE TITLE
Support OpenSSL 3.0

### ISSUE THREAD

**Issue by GreyHak** [yhirose/cpp-httplib#1030]
The routines MD5_Init, MD5_Update, MD5_Final, SHA256_Init, SHA256_Update, SHA256_Final, SHA512_Init, SHA512_Update, and  SHA512_Final have been deprecated.  The MD5, SHA_256, and SHA_512 calls can be replaced by:

```
inline std::string message_digest(const std::string& s, const EVP_MD* evp_md,
    size_t digest_length) {
    using namespace std;

    std::vector<unsigned char> md(digest_length, 0);
    EVP_MD_CTX* ctx = EVP_MD_CTX_create();
    EVP_MD_CTX_init(ctx);
    EVP_DigestInit_ex(ctx, evp_md, NULL);
    EVP_DigestUpdate(ctx, s.data(), s.size());
    EVP_DigestFinal_ex(ctx, md.data(), NULL);
    EVP_MD_CTX_destroy(ctx);

    stringstream ss;
    for (auto c : md) {
        ss << setfill('0') << setw(2) << hex << (unsigned int)c;
    }
    return ss.str();
}

inline std::string MD5(const std::string& s) {
    return message_digest(s, EVP_md5(), MD5_DIGEST_LENGTH);
}

inline std::string SHA_256(const std::string& s) {
    return message_digest(s, EVP_sha256(), SHA256_DIGEST_LENGTH);
}

inline std::string SHA_512(const std::string& s) {
    return message_digest(s, EVP_sha512(), SHA512_DIGEST_LENGTH);
}
```

**Comment by yhirose** [comment]
@GreyHak, thank you for the report. I took a look at https://www.openssl.org/docs/man1.1.1/man3/MD5_Init.html, but I don't find any description that `MD5_Init` is deprecated. Could you show me the reference in the official OpenSSL?
Thanks!

**Comment by yhirose** [comment]
It seems like they will be deprecated since 3.0 (still beta 2) and valid on 1.1.1.
https://www.openssl.org/
https://www.openssl.org/docs/manmaster/man3/MD5_Init.html
But it sounds good to prepare for it since 3.0 is coming soon.

**Comment by GreyHak** [comment]
@yhirose Thank you for finding the references.  I was building with the latest GitHub master branch:
https://github.com/openssl/openssl/blob/master/include/openssl/md5.h#L49
https://github.com/openssl/openssl/blob/master/include/openssl/sha.h#L73
https://github.com/openssl/openssl/blob/master/include/openssl/sha.h#L123

**Comment by yhirose** [comment]
3.0 is out. I'll wait a while until the major package managers support the version.

**Comment by Tachi107** [comment]
Also, `OPENSSL_VERSION_NUMBER` has been deprecated (see https://www.openssl.org/docs/man3.0/man3/OPENSSL_VERSION_NUMBER.html)

**Comment by Dorbmon** [comment]
Yes. I got a log of warnings too.

**Comment by Tachi107** [comment]
> Also, `OPENSSL_VERSION_NUMBER` has been deprecated (see https://www.openssl.org/docs/man3.0/man3/OPENSSL_VERSION_NUMBER.html)

The macro has been undeprecated, see https://github.com/openssl/openssl/commit/42659159f4d4a8c16a0e9b089d40a5831b60cbb6

**Comment by yhirose** [comment]
I no longer get any deprecated warning.
