### ISSUE TITLE
No public way of adding both query parameters and body to some client methods?

### ISSUE THREAD

**Issue by ZizhengTai** [yhirose/cpp-httplib#1031]
I was looking at how to send a `PUT` request with both query parameters and a body, and found that none of the `Client::Put` overloads take them both. It seems I have to use the internal API `httplib::detail::append_query_params` to achieve this:
```c++
httplib::Params params{{"foo", "bar"}};
std::string path = httplib::detail::append_query_params("/foo", params);
std::string body("...");

auto res = client.Put(path.c_str(), httplib::Headers(), body, "application/json");
```

Is there an alternative way of doing this that doesn't use stuff from `httplib::detail`? What's the _intended_ way of doing this?

**Comment by yhirose** [comment]
Could you try the latest httplib.h on the master branch? I made the method public.

**Comment by Quleaf** [comment]
it reset to private again...

**Comment by Tigole** [comment]
Hello,

Why is there no Post/Put metho with both Params and body (seems easier for user in my mind) ?

```c++
client.Post("/path/:param", {{"param", "value"}}, "my_body", "content-type");
```
