### ISSUE TITLE
Reconnect with different url

### ISSUE THREAD

**Issue by denprog** [yhirose/cpp-httplib#1032]
How can I reconnect with the same or different url? I see there is stop() function, but there is no connect() function.

**Comment by yhirose** [comment]
Nope

**Comment by PixlRainbow** [comment]
I am assuming you are referring to client side connection. The stop function is for the server. If you want to request a different path on the same host, just call the GET or POST or whatever function again on the old client object with the new path. If you want to connect to a different host, you will have to destroy and reconstruct a new client object.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the clear explanation.
@denprog, hope @PixlRainbow comment helps you. If you are talking about client side connection and requests to the same host, the same TCP connection will be used as long as possible. If the connection is closed and make another request on the same client object, it will reconnect to the same host.

**Comment by denprog** [comment]
@PixlRainbow thank you, I'm using a new object for a new url.
