### ISSUE TITLE
Digest auth causes std::out_of_range

### ISSUE THREAD

**Issue by ProtoByter** [yhirose/cpp-httplib#1037]
I've got this code
```
httplib::Client client(ip,port);
client.set_digest_auth("AAAA","CCCC");
auto res = client.Get("/digest/getConfig");
printf("%s",res->body.c_str());
```

and when I run it I get this error:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
```

It appears to originate here:
https://github.com/yhirose/cpp-httplib/blob/415edc237c3ea84b0bf77d85aa5a917570302fec/httplib.h#L4047

Is this the fault of my code?

**Comment by ProtoByter** [comment]
On further inspection the map does appear to not contain a `qop` key
![Screenshot_18](https://user-images.githubusercontent.com/20995169/132197124-98cb135d-fa58-4992-804c-bf135419a568.png)

**Comment by yhirose** [comment]
@ProtoByter, it seems like your server doesn't provide 'qop' parameter that the digest auth requires. Could you make sure that your server is ok?

![image](https://user-images.githubusercontent.com/357397/132216467-6b0e66ce-cdb2-48a3-93f8-b09a02889600.png)

I'll try to fix the crash problem by returning an error when any required parameter is missing.
Thanks!

**Comment by ProtoByter** [comment]
That's weird, my server is using kotlin's ktor module so it should work, given that the code I'm using is pretty close to the documentation's example of how to use it
Also as a test I connected via Firefox and that connected successfully to the server and got data which was guarded by the digest Auth (ie Firefox asked me for a user/password combo, then connected and got the data)

**Comment by ProtoByter** [comment]
https://github.com/ProtoByter/SDSServer[https://github.com/ProtoByter/SDSServer](https://github.com/ProtoByter/SDSServer)

**Comment by ProtoByter** [comment]
This is where the code for digest authentication starts:
https://github.com/ProtoByter/SDSServer/blob/78cab46fc24be1c98548e4046932535b4adb5f0d/src/main/kotlin/me/protobyte/sdsserver/plugins/Security.kt#L67
And this is what the docs say to do:
https://ktor.io/docs/digest.html#flow

**Comment by ProtoByter** [comment]
When I get the chance to I'll take a look at the requests and responses from my server and I'll also check the ktor sample which should have a version that works - I'll make an issue if both show no qop parameter being sent

**Comment by yhirose** [comment]
@ProtoByter, could you try the following code for lines 4047-4052 to see if your problem can be fixed? It uses 'auth' as a default value if 'qop' is not specified in a WWW-Authenticate response from a server.

```cpp
  std::string qop = "auth";
  if (auth.find("qop") != std::string::npos) {
    qop = auth.at("qop");
  }
```

If the behavior is common, I am ok to commit the change. I'll also check more carefully the HTTP Digest Access Auth spec in the RFC when you have time this coming weekend.

**Comment by ProtoByter** [comment]
I will test that, annoyingly the only sample that mentions digest for ktor doesn't do anything, it just creates a map of 1 username to a password and then doesn't do anything else with it, so this might be quite hard to test on the ktor side - I will test the snippet of code when I get back on my pc, which I will be soon

**Comment by ProtoByter** [comment]
That code didn't work for me but this did:
``` cpp
  std::string qop = "auth";
  if (auth.find("qop") != auth.end()) {
      qop = auth.at("qop");
  }
```

**Comment by yhirose** [comment]
@ProtoByter, yes, you are right!. Anyway, please don't use the code in production, because it's just a experimental code. Sorry for your patience.

**Comment by yhirose** [comment]
@ProtoByter, when I took a look at RFC7616, it turned out that I misread the spec. 'qop' could be optional:

![image](https://user-images.githubusercontent.com/357397/132268616-7bdfcff4-699d-4ecc-8fde-4a05b91f51a2.png)

The following articles also mention that it's optional:
https://en.wikipedia.org/wiki/Digest_access_authentication
https://blog.wildix.com/basic-digest-authentication/

I'll try to implement the digest auth accordingly this weekend.

**Comment by ProtoByter** [comment]
When I try the latest commit it fails with a 401 error, whilst when using the experimental patch it worked fine and running v0.9.4 it fails with the qop issue

**Comment by ProtoByter** [comment]
`Authorization: Digest username="a", realm="Access to the '/digest' path", nonce="...", uri="/digest/needReload", algorithm=MD5, response="..."` this is what firefox sends, let me see what httplib sends

**Comment by ProtoByter** [comment]
`Digest username="a", realm="Access to the '/digest' path", nonce="...", uri="/digest/needReload", algorithm=MD5, qop=, nc="00000005", cnonce="...", response="..."`
this is what httplib sends (captured from wireshark)

**Comment by ProtoByter** [comment]
I'll move this to another issue
