### ISSUE TITLE
httplib::Client crash inside docker container

### ISSUE THREAD

**Issue by pyrotechnics-io** [yhirose/cpp-httplib#1038]
I've noticed some weirdly perplexing behavior inside docker. 

If I launch a client app inside a docker container and call an external https endpoint, the Post seems to end up with a SEGV. The same thing doesn't happen if I launch the binary directly. 

The docker container and the bare metal host run the same OS : Ubuntu 20.04
Most of the binary dependencies are static linked except OpenSSL (but its the same version inside and outside)

**Comment by yhirose** [comment]
@pyrotechnics-io, thanks for the feedback. Could you give me more detailed information where the SEGV takes place and what kind of HTTP server are you using? Also could you give me the smallest possible client code, so that I could reproduce it on my iMac? Thanks!

**Comment by pyrotechnics-io** [comment]
Let me try and get something. Getting a call stack from inside a docker container will take some doing..

**Comment by yhirose** [comment]
Any response please?

**Comment by yhirose** [comment]
Close this issue for now.
