### ISSUE TITLE
HTTP/2 (SPDY)

### ISSUE THREAD

**Issue by danesh-d** [yhirose/cpp-httplib#104]
Hi all,

Wanted to ask if there is any plan to implement HTTP/2 (SPDY)? Specially header compression will be an important improvement.

Regards,

Danesh Daroui

**Comment by yhirose** [comment]
@danesh-d, thanks for the request. But I don't have any plan to implement HTTP/2 since it's not a easy task. (I have actually made a HTTP/2 server with libuv + nghttp2 in my work which cannot be opensouce. The combination of libraries is really good.)
