### ISSUE TITLE
split.py could split Client and Server code in different files

### ISSUE THREAD

**Issue by dmenendez-gruposantander** [yhirose/cpp-httplib#1040]
Would you consider improving split.py so that Client and Server functionality are separated in different files?

I only need Client side code for my app, and I don't want to "pay" to compile all the server side code.

**Comment by yhirose** [comment]
@dmenendez-gruposantander, thanks for the feedback. Honestly, I only use the single header file only, and never used the split version. If you work on it and send a pull request, I'll merge it.

@jrosdahl, what do you think of this idea?

**Comment by jrosdahl** [comment]
Sounds like a good idea to me if it's not too hard. I'm also only interested in the client part.

**Comment by yhirose** [comment]
@dmenendez-gruposantander, I don't mind including the feature in split.py, but I am not interested in implement it since I am not going to be a user for it. Could you implement it, and send a pull request? I am glad to take it in the master branch. Thanks!

**Comment by yhirose** [comment]
@dmenendez-gruposantander, you can send a pull request anytime. Thanks!
