### ISSUE TITLE
PUT --data-binary

### ISSUE THREAD

**Issue by ThePiso** [yhirose/cpp-httplib#1042]
Hi Yhirose,

Is there currently support for sending files through the PUT?

like this:
curl --location --request PUT 'https://blablabla' --header  'Content-Type: application/octet-stream'  --data-binary '@/Users/web01/Desktop/dunplab-manifest-48607.json'

**Comment by yhirose** [comment]
@ThePiso, yes, you can get the information from the followings as well as some examples in `test/test.cc`.

https://github.com/yhirose/cpp-httplib#send-content-with-a-content-provider
https://github.com/yhirose/cpp-httplib/blob/415edc237c3ea84b0bf77d85aa5a917570302fec/httplib.h#L906-L914
