### ISSUE TITLE
Run-Time Check Failure

### ISSUE THREAD

**Issue by josemaGruposantander** [yhirose/cpp-httplib#1043]
Hi,

It seems to be a problem with the stack when httplib is used with openssl in .h and .cc version
This cmakeLists code:

```
set( HTTPLIB_COMPILE ON)
add_subdirectory(${THIRDPARTYLIBS}/httplib/0.9.4 ${CMAKE_BINARY_DIR}/httplib)
target_compile_definitions(httplib PRIVATE CPPHTTPLIB_OPENSSL_SUPPORT)
target_include_directories(httplib PRIVATE $<BUILD_INTERFACE:${CMAKE_BINARY_DIR}/openssl/include>)
target_link_libraries(httplib PRIVATE $<BUILD_INTERFACE:crypto> $<BUILD_INTERFACE:ssl>)

set( E_SRC testExe.cpp )
add_executable(TestExe ${E_SRC})
target_link_libraries(TestExe PRIVATE httplib)
```

and this simple code:

```
#include "httplib.h"

int main(int argc, char* argv[])
{
    httplib::Client cliSts1("");
}
```

Produces the error in debug mode: "**Run-Time Check Failure #2- Stack around the variable "cliSts1" was corrupted"**

![Excpeptionhttplib](https://user-images.githubusercontent.com/90444945/132819769-9fb3d320-c378-4fc8-bb74-df4bc017b698.PNG)

This only happens with the .h and .cc version not with the header only version. Without openssl this problem disappear.

Regards

**Comment by josemaGruposantander** [comment]
Issue solved. The right way to call httplib cmake is the following

```
set( HTTPLIB_COMPILE ON)
add_subdirectory(${THIRDPARTYLIBS}/httplib/0.9.4 ${CMAKE_BINARY_DIR}/httplib)
target_compile_definitions(httplib **PUBLIC** CPPHTTPLIB_OPENSSL_SUPPORT)
target_include_directories(httplib **PUBLIC** $<BUILD_INTERFACE:${CMAKE_BINARY_DIR}/openssl/include>)
target_link_libraries(httplib PRIVATE $<BUILD_INTERFACE:crypto> $<BUILD_INTERFACE:ssl>)

```

In PRIVATE mode httplib.cc is compiled with CPPHTTPLIB_OPENSSL_SUPPORT activated but the testExe.cpp code is compiled with CPPHTTPLIB_OPENSSL_SUPPORT disabled. This situation corrupts the stack

**Comment by sum01** [comment]
See https://github.com/yhirose/cpp-httplib/issues/1034#issuecomment-912224075 for a better way to use the Cmake integration. It lets both system-installed & in-tree to be used.
You shouldn't need to manually set compile defs or include dirs.

Also, you probably want to `set(HTTPLIB_REQUIRE_OPENSSL ON)` before all of it since you seem to want that on.

**Comment by yhirose** [comment]
I think @sum01's comment can close this issue.
