### ISSUE TITLE
Latest commit doesn't correctly authenticate with digests

### ISSUE THREAD

**Issue by ProtoByter** [yhirose/cpp-httplib#1045]
My endpoint works in firefox and this is what firefox sends:
`Authorization: Digest username="a", realm="Access to the '/digest' path", nonce="...", uri="/digest/needReload", algorithm=MD5, response="..."`

whilst httplib sends:
`Digest username="a", realm="Access to the '/digest' path", nonce="...", uri="/digest/needReload", algorithm=MD5, qop=, nc="00000005", cnonce="...", response="..."`
and ends up with a 401 Unauthorized return status

**Comment by yhirose** [comment]
Oops... The problem is that the correct behavior isn't described clearly in RFC 7616...
I'll check the Wikipedia article more carefully, and try to fix it. Thanks for your report!
https://en.wikipedia.org/wiki/Digest_access_authentication

**Comment by yhirose** [comment]
@yhirose, could you test the latest? If it works, then I'll bump the version.

**Comment by ProtoByter** [comment]
I will when I can get on my pc

**Comment by ProtoByter** [comment]
I will when I can get on my pc

**Comment by ProtoByter** [comment]
It works, thanks!
