### ISSUE TITLE
Getting URL client got redirected to

### ISSUE THREAD

**Issue by Narase33** [yhirose/cpp-httplib#1048]
Hello, I found this old issue: https://github.com/yhirose/cpp-httplib/issues/765, unfortunately the solution doesnt work in my case.

The URL is: https://en.cppreference.com/mwiki/index.php?title=Special%3ASearch&search=std%3Achrono%3Aduration

which redirects you to: https://en.cppreference.com/w/cpp/chrono/duration

When looking at the result, Response::location is empty

also setting set_follow_redirection for the first adress returns with error "Read"

**Comment by yhirose** [comment]
@Narase33, thanks for the feedback. I think you forget setting some necessary HTTP headers to get 302 response from the server. I get the same problem even with curl with `curl -L https://en.cppreference.com/mwiki/index.php?title=Special%3ASearch&search=std%3Achrono%3Aduration` which returns 200.
