### ISSUE TITLE
Crash on long URLs

### ISSUE THREAD

**Issue by juggernauten** [yhirose/cpp-httplib#105]
Love the library, I've used it tons and it's great; 

HOWEVER, I found a game-changer;
The server crashes when presented with long requests.
ex, I'm hosting on localhost:8080/blah
and someone makes a request localhost:8080/blah?something=AHUGEAMOUNTOFTEXT, it will make a segfault. 

Tried on W10 - Visual studio 2017, Archlinux (latest kernel) and Ubuntu 18.04 both with their latest version of GCC.

**Comment by yhirose** [comment]
@juggernauten, thanks for the bug report! I'll try to reproduce it on my MacBook. Could you give me the length of the AHUGEAMOUNTOFTEST string in your case?

**Comment by juggernauten** [comment]
I tried with different lengths, but I never found a threshold. I know that it at least crashes on 25k characters.

**Comment by yhirose** [comment]
@juggernauten, I tried to reproduce it, but could get success. Here is my test code at https://github.com/yhirose/cpp-httplib/commit/76ea8dd560cddb079c560bd6766b5657c1f143b6:

```cpp
const string LONG_QUERY_VALUE = string(25000, '@');
const string LONG_QUERY_URL = "/long-query-value?key=" + LONG_QUERY_VALUE;
```

```cpp
// On Client
auto res = cli.Get(LONG_QUERY_URL.c_str());
```

```cpp
// On Server
svr.Get("/long-query-value", [&](const Request& req, Response& /*res*/) {
    EXPECT_EQ(LONG_QUERY_URL, req.target);
    EXPECT_EQ(LONG_QUERY_VALUE, req.get_param_value("key"));
})
```

What characters does your AHUGEAMOUNTOFTEST string include?
Thanks!

**Comment by juggernauten** [comment]
A bas64 encoded string.

**Comment by yhirose** [comment]
@juggernauten, do you still experience this problem?
By the way, we have to be careful to use Base64 encoding string in the HTTP query text. You can find the information at https://stackoverflow.com/questions/1374753/passing-base64-encoded-strings-in-url.

**Comment by juggernauten** [comment]
Sorry, I have been quite busy juggling Work and School; And since I reworked my application from using HTTP to TCP to send the data I haven't been having the issue, but I will see if I can re-create it.

**Comment by juggernauten** [comment]
Looking at it now I don't seem to be able to replicate it. Quite strange.

**Comment by yhirose** [comment]
@juggernauten, thank you for the report and testing this issue again! The direct use of TCP is a good and faster choice. 👍
Please let me know when you have the same problem again.
