### ISSUE TITLE
Add move constructor for Client

### ISSUE THREAD

**Issue by ZizhengTai** [yhirose/cpp-httplib#1050]
Since `Client` already uses the PIMPL pattern, it seems reasonably to provide a default move constructor for it. This enables classes that have a `Client` member variable to be movable.

If using C++11 or later, we only need to add
```c++
Client(Client &&) = default;
```
unless we want to support older standards.

**Comment by yhirose** [comment]
@ZizhengTai, that's a reasonable request even if I don't need it. Could you send me a pull request and a unit test for it? I'll take a look at and merge it right away. Thanks!

**Comment by ZizhengTai** [comment]
@yhirose In the test, I can either use `static_assert` to fail the test build at compile time if `Client` is not move-constructible, or use `EXPECT_TRUE` to fail the test only at test runtime. Which approach do you prefer? The former fails sooner while the latter outputs the failure together with the rest of the test, which might be desired.

**Comment by ZizhengTai** [comment]
Submitted a PR that uses `EXPECT_*`. Let me know if you prefer the other approach.
