### ISSUE TITLE
build error on vs2013 community

### ISSUE THREAD

**Issue by qingfengshiran** [yhirose/cpp-httplib#1055]
2	error C2610: 'httplib::Response::Response(httplib::Response &&)' : is not a special member function which can be defaulted	d:\mcpas\mcpas-v2\caffe_caffe\caffe_caffe\httplib.h	423	1	
3	error C2610: 'httplib::Response &httplib::Response::operator =(httplib::Response &&)' : is not a special member function which can be defaulted	d:\mcpas\mcpas-v2\caffe_caffe\caffe_caffe\httplib.h	424	1	caffe_caffe
16 IntelliSense: invalid type for defaulted constructor	d:\mcpas\mcpas-v2\caffe_caffe\caffe_caffe\httplib.h	423	5	caffe_caffe
17	IntelliSense: invalid type for defaulted assignment operator	d:\mcpas\mcpas-v2\caffe_caffe\caffe_caffe\httplib.h	424	15	caffe_caffe
 source code :
    Response(Response&&) = default;
    Response& operator=(Response&&) = default;

**Comment by yhirose** [comment]
@qingfengshiran, thank you for the report, but I no longer use vs2013. I'll mention in README that httplib.h does officially support only the latest visual studio. Sorry for the inconvenience...

**Comment by yhirose** [comment]
@qingfengshiran, FYI: https://github.com/yhirose/cpp-httplib/commit/623ab4a96e2ced02e212ef779a50afe802cee6e6
