### ISSUE TITLE
std::invalid_argument: 'https' scheme is not supported

### ISSUE THREAD

**Issue by marller2013** [yhirose/cpp-httplib#1059]
Hello,I used cpp-httplib in my project.When I send a "http" request,it works OK.But when I send a "https",it works failed,and thrown an exception:terminating with uncaught exception of type std::invalid_argument: 'https' scheme is not supported.
I had  browsed all Issues about this exception.What puzzles me is that I still don't know how to deal with this exception.

I had defined CPPHTTPLIB_BROTLI_SUPPORT before including httplib.h,and I had tried httplib::SSLClient. Unfortunately,It compiled failed:

undefined reference to `httplib::SSLClient::SSLClient(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
 undefined reference to `httplib::SSLClient::~SSLClient()'
 undefined reference to `httplib::SSLClient::~SSLClient()'

Can I get some advice or help here

**Comment by yhirose** [comment]
Hope [this](https://github.com/yhirose/cpp-httplib#ssl-support) helps.

**Comment by PixlRainbow** [comment]
when compiling httplib.cc separately, you have to define `CPPHTTPLIB_OPENSSL_SUPPORT` for both cc files. If you only define in your main.cc, httplib.o will not contain the code for SSLClient, which is why it is saying it is an undefined reference -- the compiler has detected that you have "declared" SSL class in httplib.h but did not define the implementation for it in httplib.cc

**Comment by marller2013** [comment]
@PixlRainbow Thanks for your reply, and it is great.I'll try your plan later.

**Comment by Riz-ve** [comment]
> I had fixed this error.By the way,it caused by the httplib.cc and httplib.h.I split the httplib.h by split.py. When I used httplib.cc and httplib.h,the error occurred. So I used httplib.h in the httplib project folder default,and my invoking works OK. @yhirose If you get the reason, could you reply here?

Thank you so much for telling me it was the problem with the files being split up. After hours of debugging its finally fixed when i used just the header file.
