### ISSUE TITLE
Asynchronoush server push

### ISSUE THREAD

**Issue by danesh-d** [yhirose/cpp-httplib#106]
Hi,

This is rather question/feature request to whether the library supports this feature or not. I would like to know whether it is possible to push asynchronous data to the client from a HTTP server implemented using cpp-httplib? Of course by push I do not mean the push that is defined in HTTP/2 which is about pushing resources to the client in advance, but I mean pushing notification/data to the client when the client has not sent any request to the server.

A quick and naive solution in my mind would be to implement a tiny HTTP server at the client side as well, so the server can send data asynchronously using another library like curl through a PUT method to the client but I am not sure if this is an efficient solution since both server and client should have limited implementations of both server and client embedded.

Regards,

Danesh

**Comment by yhirose** [comment]
@danesh-d, sorry for the late reply. A short answer is that cpp-httplib doesn't support 'server push'.

But if we implement SSE (Server-Sent Events) support in cpp-httlib, it will be possible to push data to client. Please see [this blog article](https://medium.com/conectric-networks/a-look-at-server-sent-events-54a77f8d6ff7).

I am not planning to implement it for now. But I'll keep this in mind. Thanks for your feedback!

**Comment by yhirose** [comment]
See #45

**Comment by yhirose** [comment]
Since there is already an issue about SSE (#45), I'll close it.
