### ISSUE TITLE
losing tail of the data when posting big data

### ISSUE THREAD

**Issue by wenjunlong** [yhirose/cpp-httplib#1062]
**I turn an image into base64 string and have it Url encoded , and try to post it to a server which was written in java.

I print the post data to make sure I post the right data, I  also print the raw data recieved by the server.

the problem is that the result is sometimes right and sometime wrong.  if the result is right, the data printed by the server is the same with that printed by the client side.  if the result is wrong, the date printed by the server shows that the tail of the data has been changed into serial of "\u0000".

below is the code on the client side:**

`void Engine::feature() {
    std::string* imageBase64 = ImageUtil::image_to_base64("/path/to/image.jpg");
    std::string dataJson = "{\"reqId\": \"aaaaaaa\",\"withQuality\": 1,\"imageBase64\": \""+ *imageBase64+"\"}";
    std::cout << dataJson << std::endl;
    std::string url = "http://127.0.0.1:8080";
    std::string uri = "/engine/image/feature";
    sendRequest(dataJson, url, uri);
   delete imageBase64;
}

void Engine::sendRequest(const std::string& data, const std::string& url, const std::string& uri) {
    httplib::Client cli(url.c_str()); // scheme + host
    cli.set_connection_timeout(0, 6000000); // 300 milliseconds
    cli.set_read_timeout(5, 0); // 5 seconds
    cli.set_write_timeout(5, 0); // 5 seconds
    httplib::Headers headers = {
            {"accept", "application/json"}
    };
    httplib::Result res = cli.Post(uri.c_str(), headers, data, "application/json; charset=UTF-8");
    std::cout << res->body << std::endl;
}`

and the result of     `std::cout << dataJson << std::endl;`  is like 

_{"reqId": "aaaaaaa","withQuality": 1,"imageBase64": "%2F9j%2F4RTiRXhpZgAATU0AKgAAAAgACwEOAAIAAAAgAAAC6gEPAAIAAAAgAAADCgEQAAIAAAAgAAADKgESAAMAAAABAAEAAAEaAAUAAAABAAADSgEbAAUAAAABAAADUgEoAAMAAAABAAIAAAExAAIAAAAgAAADWgEyAAIAAAAUAAADeodpAAQAAAABAAAAkoglAAQAAAABAAACMAAAAqgAIoKaAAUAAAABAAADjoKdAAUAAAABAAADlogiAAMAAAABAAIAAIgnAAMAAAABBUYAAJAAAAcAAAAEMDIyMZADAAIAAAAUAAADnpAEAAIAAAAUAAADspEBAAcAAAAEAQIDAJECAAUAAAABAAADxpIBAAoAAAABAAADzpICAAUAAAABAAAD1pIEAAoAAAABAAAD3pIFAAUAAAABAAAD5pIHAAMAAAABAAEdv51AziK2BztI6g0X5Z5uUX5sksvv71CRJkqGxjnkdaAKkcpa53ZzkjLjmti5xHa7gQoA5xx9KqQWBHzNhmPJ9qr3ckwTaGOCc5VucdulAENxOHIO%2FJ7gDNV5blo15faCcYx2p0EcuMnnnn1qC5XEi7S2P5f1oAZDH8xIcn028fnRKzRyg7to9z1q1FHnAIAOMAjpioJ4DmnSL0BGPaoQMMBnnrg0AOPy8DgnnH9Khkn6g5HXpUo3bCQSzds1Ucsd2BjBzQAhkCjgkD0NQysMY756nmlIzkH5ifT1pjqWQ9h1oAjbLPkkEDpjvUbMNuQp%2FnzSuvTPTNMbIz6HmgCGZ%2BBgZyaiLrnPH41KUOM9Rnp6VDKpwOx9DQBEzEE5Izn8BUDYVgRnJ6809wVwGyD1z1qORsYAAA9%2B9ADXk%2BbnioJCA2eOetPJLYPSq8oKKQABjtQA3J7k5HUVXdlAYEYOc1IxYjOBz0OarSnK8k5x0FAFeeXAdeuefxrMvJ%2BCBzxzxV64b5SG%2BUY61i6lOFDbuc%2Fw%2BtAGNq18FG3dghcsfQCuKmm8x8nknp71o6xcluEYHI6rx3rKJO49enWgABbOM%2FpR6kUDJOeAKcB0HqKAAsF7%2FTNAGO%2FFKBkEdaTG3g9fagAwV9ck5pVJAOOvvSEeopwJ60AAbnlfxpR15%2FCkODkZP4UuACe9ACjkjijqe1IAen8utOA4Oce9ADcg49fU0uBnAb2pSMf4Ug4yT2H60Af%2F9k%3D"}_

I have shorten the content of imageBase64 largely,  for the result of  `dataJson .size()` is actually 190639.

if I  get the wrong result from the server side like  :
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: unclosed str; nested exception is com.alibaba.fastjson.JSONException: unclosed str   

 the raw content received by the server as I print down is like: (I  have also shorten the content by deleting from the middle side)

_{"Context":["{\"reqId\": \"aaaaaaa\",\"withQuality\": 1,\"imageBase64\": \"%2F9j%2F4RTiRXhpZgAATU0AKgAAAAgACwEOAAIAAAAgAAAC6gEPAAIAAAAgAAADCgEQAAIAAAAgAAADKgESAAMAAAABAAEAAAEaAAUAAAABAAADSgEbAAUAAAABAAADUgEoAAMAAAABAAIAAAExAAIAAAAgAAADWgEyAAIAAAAUAAADeodpAAQAAAABAAAAkoglAAQAAAABAAACMAAAAqgAIoKaAAUAAAABAAADjoKdAAUAAAABAAADlogiAAMAAAABAAIAAIgnAAMAAAABBUYAAJAAAAcAAAAEMDIyMZADAAIAAAAUAAADnpAEAAIAAAAUAAADspEBAAcAAAAEAQIDAJECAAUAAAABAAADxpIBAAoAAAABAAADzpICAAUAAAABAAAD1pIEAAoAAAABAAAD3pIFAAUAAAABAAAD5pIHAAMAAAABAAEAAJIIAAMAAAABAAEAAJIJAAMAAAABAAAAAJIKAAUAAAABAAAD7qABAAMAAAABAAEAAKACAAQAAAABAAAFAKADAAQAAAABAAAC0KAFAAQAAAABAAACiqIXAAMAAAABAAIAAKMAAAcAAAABAwAAAKMBAAcAAAABAQAAAKQu0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"],"headers":[{"content-length":"190639","host":"127.0.0.1:8080","connection":"keep-alive","content-type":"application/json; charset=UTF-8","accept":"application/json","user-agent":"cpp-httplib/0.7"}],"Method":"POST","Protocol":"HTTP/1.1","parameters":[{}],"URL":"http://127.0.0.1:8080/engine/image/feature"}_

as it shows , it seems the server  know the size of content it need to receive, but got less than what it expected, so it append \u0000 to the content it receive to fullfil the length.

what confuse me most is that this problem do not always happen ,  about 50% the chance.

sorry for the poor english, hope the information can help, and it will be gratefull receiving you answer.

**Comment by yhirose** [comment]
> if I get the wrong result from the server side like :
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: unclosed str; nested exception is com.alibaba.fastjson.JSONException: unclosed str

It seems like `dataJson` isn't a valid JSON string. Could you make sure the `dataJson` is correct with any available JSON validator?

**Comment by PixlRainbow** [comment]
the reason that dataJson sometimes is not a valid JSON string is because httplib stops sending data halfway through the base64 string and never manages to send the rest of the JSON.

**Comment by wenjunlong** [comment]
> > if I get the wrong result from the server side like :
> > org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: unclosed str; nested exception is com.alibaba.fastjson.JSONException: unclosed str
> 
> It seems like `dataJson` isn't a valid JSON string. Could you make sure the `dataJson` is correct with any available JSON validator?

Yes.  I was posting **the same data** repeatedly, and about 50% the chance the server side receive the correct data, and the JSON string was parsed correclty.
 The point is , I did'n changed the  data through out the whole testing, with **the same data** posted, sometimes the server receive the data correctly, and the parse goes well , sometimes not.   Each time things went wrong, the  tail of the data was replace with serials of "\u0000" compared to what was printed in the client  side.

I also printed the data downing  in the client side before posting, So I can be sure that  all the time the data posted was the same.

**Comment by wenjunlong** [comment]
> the reason that dataJson sometimes is not a valid JSON string is because httplib stops sending data halfway through the base64 string and doesn't manage to send the rest of the JSON.

agreed, The most confusing part is, with the same data posted, sometimes things go right and sometime wrong.

**Comment by yhirose** [comment]
@wenjunlong, @PixlRainbow, thanks for the replies. Honestly, I have no clue why this symptom happens because `test/test/cc` has already unit test cases to deal with 100B huge data, and I have never seen these test fails.
https://github.com/yhirose/cpp-httplib/blob/d87d0672a8e0f3695f168ff1f55028f6fbe4aedf/test/test.cc#L2793-L2820

Could you investigate more why this problem is happening on your machine? If you especially send the same exact request from curl, does the same problem happen?

If I can reproduce the problem with the smallest possible code on my machine, I'll try to debug it. Thanks for your help and patience!

**Comment by wenjunlong** [comment]
I think I finally figure it out, It turns out to be  the server's problem, not the client.  Someone changed  some of the  default implementations of  the Java Servlet for some purpose, I change them back, then everything returns to normal. 

 I turned to some other client both written in c++ and python to make sure that the problem is really made by the server. It's likely that the server stopped after accepting the first 8192 byte of the data, but I not very sure. 

It still confuse me why the java http client restTemplate always worked, before an after I fix the problem in the serve side, which make me believed that the client cause the problem in the first place.  Is it because  there is some way to force the server to received all the data in one time?

Sorry for all the trouble, and thank you for your patience!
