### ISSUE TITLE
patch note for the default behave of select

### ISSUE THREAD

**Issue by wangningito** [yhirose/cpp-httplib#1063]
recently I introduce this lib into my project, but the connection keeps failing in some of processes.
I found the failed process is that the process is holding too much fd(s), over 1024. It changes the behave of "select" in many of operating systems. Also, "select" is use by cpp-httplib by default, without specifying "CPPHTTPLIB_USE_POLL".
would you mind patching some notes for this? I guess there are some people like me, just want to get the ability to send Get or Post request, but not quite familiar with underlying things. Thanks.

**Comment by yhirose** [comment]
@wangningito, thanks for the feedback. What do you mean by `patch note`? Are you asking for making README change or putting a comment in httplib.h?

**Comment by wangningito** [comment]
@yhirose thanks for replying, 
This case is easily to be reproduce in case of holding 1024 fd(s) with the default settings of cpp-httplib, Maybe there could be some FAQ or Troubleshooting doc?
I'm very new to network things, it takes me some time to troubleshooting this problem, maybe some doc can help the another one who happened to met this problem to fix the problem in very soon.  How do you think about it?
