### ISSUE TITLE
Basic SSL Client-Server example fails to make request

### ISSUE THREAD

**Issue by lexika979** [yhirose/cpp-httplib#1068]
Hello, i have been trying to run the example code in the repository, but came across wierd/incorrect behaviour (Probbaly caused by me).
I have followed the basic examples to get a SSLServer running, which seems to be working fine - I have generated a certificate and a private key using OpenSSL, and made the server use them.

Commands used:
```
openssl genrsa -des3 –out priv.pem -passout pass:myPassword 1024
openssl req -x509 -new -key priv.pem -passin pass:myPassword -days 3650 -out cert.cer
```

I have slightly altered the example code, but both the example code and my code behaves the same:
Server: 

```
int main( ) {
    httplib::SSLServer svr( "cert.cer", "priv.pem" );

    svr.Get( "/hi", [ ]( const httplib::Request&, httplib::Response& res ) {
        res.body = "Hello world";
        res.status = 200;
    } );

    svr.listen( "localhost", 8080 );
}
```

Client: 

```
int main( ) {
    httplib::SSLClient cli("https://localhost", 8080);

    auto res = cli.Get("/hi");
    std::cout << res->status << "\n";
    std::cout << res->body;
    while(1);
}
```

The issue:
Once I start the server and the client, the client promptly crashes, because the request failed and `res->status` is nullptr.
I don't understand why the request failed, but it has something to do with SSL. If I change the code to use HTTP instead of HTTPS, it works as expected.
HTTP Server: 

```
int main( ) {
    httplib::Server svr;

    svr.Get( "/hi", [ ]( const httplib::Request&, httplib::Response& res ) {
        res.body = "Hello world";
        res.status = 200;
    } );

    svr.listen( "localhost", 8080 );
}
```

HTTP Client: 

```
int main( ) {
    httplib::Client cli("http://localhost", 8080);

    auto res = cli.Get("/hi");
    std::cout << res->status << "\n";
    std::cout << res->body;
    while(1);
}
```

So this probably means I generated my cert/private key wrong, but since I am new to certificates and this kind of stuff, I sadly have no idea what's going on.
There are no issues on the GitHub that match the problem I have, and the documentation does not provide a solution in this scenario.

I would appreciate any help and thank you for taking your time to read this.

**Comment by lexika979** [comment]
Thank you for the fast answer, but unoftunately the issue still persists with both solution applied:
```
int main( ) {
	httplib::SSLClient cli( "https://localhost", 8080 );
	cli.set_ca_cert_path( "cert.cer" );
	cli.enable_server_certificate_verification( false );

	auto res = cli.Get( "/hi" );
	std::cout << res->status << "\n";
	std::cout << res->body;
	while ( 1 );
}
```

res is still nullptr.

**Comment by PixlRainbow** [comment]
remove the "https://" from the hostname in SSLClient constructor, SSLClient always attempts https by default

**Comment by PixlRainbow** [comment]
that is strange, have you tried visiting the server from web browser or using CURL?

**Comment by lexika979** [comment]
Making a request thru postman works
![hZP8jSO](https://user-images.githubusercontent.com/83946527/136653683-9e8ca3ba-4c88-4923-b11a-9fe5f8502432.png)
t

**Comment by lexika979** [comment]
I'm very confused, this
![9mpsA7G](https://user-images.githubusercontent.com/83946527/136654008-64890bca-683b-41f6-a2a2-87e551363933.png)
just started working all of a sudden
![WYEAzoo](https://user-images.githubusercontent.com/83946527/136654024-09a0971c-babf-41b1-bda4-4c15c4919646.png)
?

**Comment by lexika979** [comment]
I'll close this for now, if i figure out what happaned i will let you know
