### ISSUE TITLE
Posible improvement when HTTPLIB_COMPILE ON

### ISSUE THREAD

**Issue by josemaGruposantander** [yhirose/cpp-httplib#1071]
Hi,

Right now httplib.h is splitted into httplib.cc and httplib.h every time target views are generated. This situation implies that httplib.cc and httplib.h are recompiled every time target views are generated even if the original httplib doesn't change.

I propose to used **add_custom_command** insted of **execute_process**

That means replace this code:

`execute_process(COMMAND ${Python3_EXECUTABLE} "${CMAKE_CURRENT_BINARY_DIR}/split.py"
WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
ERROR_VARIABLE _httplib_split_error
)
if(_httplib_split_error)
message(FATAL_ERROR "Failed when trying to split Cpp-httplib with the Python script.\n${_httplib_split_error}")
endif()`

by

`add_custom_command(
OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/out/httplib.cc" "${CMAKE_CURRENT_BINARY_DIR}/out/httplib.h"
COMMAND ${Python3_EXECUTABLE} "${CMAKE_CURRENT_BINARY_DIR}/split.py"
WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
MAIN_DEPENDENCY "${CMAKE_CURRENT_BINARY_DIR}/httplib.h"
COMMENT "splitting"
    )`

**add_custom_command** is only executed during build process. it will be executed only if **"${CMAKE_CURRENT_BINARY_DIR}/httplib.h"** has changed. With this situation we avoid recreating and recompiling **${CMAKE_CURRENT_BINARY_DIR}/out/httplib.h** and **${CMAKE_CURRENT_BINARY_DIR}/out/httplib.cc** when it is not needed.

Tell mi what you think

**Comment by sum01** [comment]
I see what you mean, but it doesn't happen for me.

`split.py` [has these lines](https://github.com/yhirose/cpp-httplib/blob/master/split.py#L35-L38) that are preventing it from happening already. All it does is output the message `out/httplib.h and out/httplib.cc are up to date` and it stops it from doing anything else.

If you think it's necessary then I'm not against a PR, I just don't have the issue personally.

**Comment by josemaGruposantander** [comment]
My version was older and it doesn't have these lines.
I will update it. Anyway another solution is what i proposed. In this solution it is not needed to do specific code in the python script to check if the file has changed
