### ISSUE TITLE
Does the GET request of the http protocol do not need params?

### ISSUE THREAD

**Issue by hctym1995** [yhirose/cpp-httplib#1081]
as the title, I did not find a constructor similar to “Result Get(const char *path, const Headers &headers);” in the source code,
so i added "Result Get(const char *path, const Params &params);" and other related code in my source code and it worked.

Is this a useful change?

**Comment by yhirose** [comment]
@hctym1995, I took a look at #1082, but it's not a production quality code, and could break existing users' code... So I rejected it. I understand what you need. When I have time, I'll come up with a better way to do i. Thank you for your understanding!

**Comment by hctym1995** [comment]
It's ok， thank u too
