### ISSUE TITLE
Get with request format required

### ISSUE THREAD

**Issue by xkaraman** [yhirose/cpp-httplib#1083]
I am trying to use the library in order to connect with an 3rd party server API. That API requires that REST API requests need to be sent as "Content Type: application/json". 
As a i understand this can be accomplished by
```
httplib::Headers headers ={
        {"Accept","application/json"}
    };
    auto res = cli.Get("/public/[some-url]");

```
But it also requires that Request have a a specific format with json components that are required, otherwise it denies the request. 

How can i accomplish this with the library? Any hints?

Thanks a lot for the easy to use library.

**Comment by yhirose** [comment]
@xkaraman, thanks for the feedback, but I don't think it's not a question for cpp-httplib, but a question for the 3rd party server to figure out what JSON format is required. I think the easiest way to find it is to go to the documentation of the server, or try with curl. Hope it helps!

**Comment by xkaraman** [comment]
I know the json format that is required, but how can i send it with a GET request?

**Comment by PixlRainbow** [comment]
use an external library to format object-oriented data into a binary string (either `char*` or `std::string`) then send that as a request body/request content.

Note that in HTTP standards, the `Accept` header is for defining what meta types client is capable of *receiving* as a response from the server. To define that the client request body is `application/json`, use the third parameter of the [Post](https://github.com/yhirose/cpp-httplib#post) or [Put](https://github.com/yhirose/cpp-httplib#put) functions. Note that GET requests, by standard, cannot have request bodies.
