### ISSUE TITLE
fatal error: 'arpa/inet.h' file not found

### ISSUE THREAD

**Issue by nidhaloff** [yhirose/cpp-httplib#1086]
I'm using ubuntu 20.04 and I'm trying to include this lib in my project, however, I can't build with cmake because of this error. 

```
httplib.h:162:10: fatal error: 'arpa/inet.h' file not found
#include <arpa/inet.h>
```

This is my cmake file. To use the lib, I just copy pasted the content under include/httplib.h (that's why I included the folder with include_directories)

```
cmake_minimum_required(VERSION 3.16)
project(proj VERSION 1.0.0)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/include)
add_executable(proj main.cpp)
```

It's actually pretty basic/simple. I know that maybe this error has nothing to do with the lib. I'm just asking if anyone faced this issue before. That would be great. 

I checked whether I have the arpa/inet.h in my file system and Indeed I have it under `/usr/include/arpa/` so everything should be fine. Why can't Cmake find this? or what am I doing wrong to use the library? I appreciate any help

**Comment by shugela123** [comment]
Hello, I have also encountered this issue, but there is no<arpa/inet. h>in my environment. May I know where to download this thing
