### ISSUE TITLE
Httpclient calls with OpenSSL 1.1.1l 24 Aug 2021 Crash

### ISSUE THREAD

**Issue by zhuge20100104** [yhirose/cpp-httplib#1097]
@yhirose OpenSSL 1.1.1l 24 Aug 2021 This version's client still crash on latest fedora platform for multi thread.

Segmentation fault (thread 139884551083584, pid 1437)
Stack trace:
[root@07882a6dc489 build]# [__memcmp_avx2_movbe]
:?
[std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const]
/lib64/libstdc++.so.6:0x14803e
[bool std::operator==<char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*)]
/usr/include/c++/11/bits/basic_string.h:6249
[httplib::detail::if2ip(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)]
http/httplib.h:2605 (discriminator 1)
[httplib::detail::create_client_socket(char const*, char const*, int, int, bool, std::function<void (int)>, long, long, long, long, long, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, httplib::Error&)::{lambda(int, addrinfo&)#1}::operator()(int, addrinfo&) const]
http/httplib.h:2633 (discriminator 1)
[int httplib::detail::create_socket<httplib::detail::create_client_socket(char const*, char const*, int, int, bool, std::function<void (int)>, long, long, long, long, long, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, httplib::Error&)::{lambda(int, addrinfo&)#1}>(char const*, char const*, int, int, int, bool, std::function<void (int)>, httplib::detail::create_client_socket(char const*, char const*, int, int, bool, std::function<void (int)>, long, long, long, long, long, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, httplib::Error&)::{lambda(int, addrinfo&)#1})]
http/httplib.h:2541
[httplib::detail::create_client_socket(char const*, char const*, int, int, bool, std::function<void (int)>, long, long, long, long, long, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, httplib::Error&)]
http/httplib.h:2627
[httplib::ClientImpl::create_client_socket(httplib::Error&) const]
http/httplib.h:5616
[httplib::ClientImpl::create_and_connect_socket(httplib::ClientImpl::Socket&, httplib::Error&)]
http/httplib.h:5637
[httplib::SSLClient::create_and_connect_socket(httplib::ClientImpl::Socket&, httplib::Error&)]
http/httplib.h:7262 (discriminator 1)
[httplib::ClientImpl::send(httplib::Request&, httplib::Response&, httplib::Error&)]
http/httplib.h:5732
[httplib::ClientImpl::send_(httplib::Request&&)]
http/httplib.h:5803
[httplib::ClientImpl::Get(char const*, std::multimap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, httplib::detail::ci, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::function<bool (unsigned long, unsigned long)>)]
http/httplib.h:6290
[httplib::ClientImpl::Get(char const*, std::multimap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, httplib::detail::ci, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)]
http/httplib.h:6279
[HttpUtil::get_str(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)]
http/impl/http_util.cpp:129
[Req::make_a_async_api_query_and_get_report_url(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)]
utils/req.cpp:84 (discriminator 3)

**Comment by zhuge20100104** [comment]
If you have time, pls help to resolve it.
I am a Automation QA using boost::asio::thread_pool to create new thread and then met this error.

Thanks you very much.

**Comment by yhirose** [comment]
@zhuge20100104, thanks for the report, but I can't give you any help at this point since I am not able to reproduce it on my machine. Could you look into it deeper and try to provide the smallest possible code to reproduce the problem? Thanks.

**Comment by zhuge20100104** [comment]
OK, I will try to give you a demo.

**Comment by zhuge20100104** [comment]
@yhirose I'm sorry.  I find the error cause by myself finally. Cuz in my CMakeLists.txt file, I didn't use find_package to find the OpenSSL lib, then the cmake build system find the system's ssl library for me, it's below a specific version. After I add find_package to my CMakeLists.txt, it didn't crash now. I'm sorry. Pls close this issue. Thanks.
