### ISSUE TITLE
Params posted to PHP lose characters

### ISSUE THREAD

**Issue by ASBaj** [yhirose/cpp-httplib#110]
Hi,

I'm doing some interop with a PHP server I don't fully control. In order for my request to be accepted, I need to post a json string with a parameter named data, which I know I can do like this:

httplib::Params params;
params.emplace("data", jsonString);

However, on the PHP side, when the server gets the $_REQUEST["data"] property, 6 characters from the string get cut off.

I'm unsure of the cause of this issue. Do you know what it might be?

Thanks!

**Comment by yhirose** [comment]
@ASBaj, thanks for the feedback. But I guess this is out of scope of what cpp-httplib should do. Does the following post help you instead?
https://github.com/github/fetch/issues/263

**Comment by ASBaj** [comment]
@yhirose Hi, actually, I have found the source of the issue. In the method write_request, in this paragraph:

    // Body
    if (!req.body.empty()) {
        if (req.get_header_value("Content-Type") == "application/x-www-form-urlencoded") {
            auto str = detail::encode_url(req.body); //This is the problem
            bstrm.write(str.c_str(), str.size());
			std::cout << str << std::endl;
        } else {
            bstrm.write(req.body.c_str(), req.body.size());
        }
    }

When the json object is encoded and posted to the PHP server, characters get lost and the JSON becomes malformed.

**Comment by yhirose** [comment]
@ASBaj, Good find! I am thinking to get red of the code if the change doesn't break unit tests. I'll let you know if the new version becomes available.

**Comment by ASBaj** [comment]
No worries, happy to help! For the moment, I've edited my own copy of the library and duplicated all the required methods for posting using a slightly different name, with the only real change that write_request doesn't encode the url, so I have a workaround for now. In the meantime,  I'll be looking forward to a new version!

**Comment by yhirose** [comment]
@ASBaj, the new version is available now. I removed the line of URL encoding. Hope you can go with this version. Thanks for your great contribution!
