### ISSUE TITLE
Compile failing with exceptions disabled

### ISSUE THREAD

**Issue by sgraham** [yhirose/cpp-httplib#1100]
I'm trying to update from a quite-old version and am getting errors of this form from clang or similar from VS:

```
../../third_party/cpp-httplib/cpp-httplib/httplib.h:3598:70: error: cannot use 'try' with exceptions disabled
inline bool parse_range_header(const std::string &s, Ranges &ranges) try {
                                                                     ^
../../third_party/cpp-httplib/cpp-httplib/httplib.h:5492:3: error: cannot use 'try' with exceptions disabled
  try {
  ^
../../third_party/cpp-httplib/cpp-httplib/httplib.h:7557:7: error: cannot use 'throw' with exceptions disabled
      throw std::invalid_argument(msg);
      ^
```

(https://bugs.chromium.org/p/crashpad/issues/detail?id=378)

I think the exception handling was added around January for #845. Would it be reasonable to have a compile time define that excludes the exception handler?

**Comment by yhirose** [comment]
@sgraham, thank you for the report. These exception handlings have been added for #705, #714 and #845 to protect cpp-httplib from crashes reported by users. I don't mind adding the compile-time option such as `CPPHTTPLIB_NO_EXCEPTION_HANDLING` to disable these, but it will compromise stability a bit.
Please let me know your thought. Thanks!

**Comment by sgraham** [comment]
Thank you for looking. That seems reasonable to me, though I'm not sure how invasive it will be.

I guess the call to std::stoll, and handling an unsupported scheme could be written slightly differently to avoid relying on C++ exceptions, but I guess #845 would have to be just excluded based on the define.

**Comment by yhirose** [comment]
@sgraham, I added `CPPHTTPLIB_NO_EXCEPTIONS` to disable C++ exception handling, and release v0.9.8. Hope it resolve the issue in your project.

**Comment by sgraham** [comment]
Thank you so much! I will try it out.
