### ISSUE TITLE
How to use this lib download big files?

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [yhirose/cpp-httplib#1101]
the example has download big files?

**Comment by yhirose** [comment]
Hope this helps: https://github.com/yhirose/cpp-httplib#receive-content-with-a-content-receiver-1

**Comment by wangwenqiangGitHub** [comment]
Has a specific application example?

**Comment by PixlRainbow** [comment]
if you want to immediately save the big file to a file on disk, just replace `std::string body` with `std::ofstream file("big_file.mp4", std::ofstream::binary)` and replace `body.append(data, data_length)` with `file.write(data, data_length)` from the linked example.

**Comment by wangwenqiangGitHub** [comment]
> if you want to immediately save the big file to a file on disk, just replace `std::string body` with `std::ofstream file("big_file.mp4", std::ofstream::binary)` and replace `body.append(data, data_length)` with `file.write(data, data_length)` from the linked example.

very thanks!

**Comment by wangwenqiangGitHub** [comment]
> Hope this helps: https://github.com/yhirose/cpp-httplib#receive-content-with-a-content-receiver-1

how to set  low speed time and low speed limit like curl?

**Comment by PixlRainbow** [comment]
just use a C++ standard library sleep e.g. https://stackoverflow.com/a/10613664 and add it after you write the file but before you return true to force the function to wait between receiver calls. You can also manipulate the size of the stream buffer by setting `#define CPPHTTPLIB_RECV_BUFSIZ size_t(4096u)` (replacing `4096` with a smaller value) to force httplib to read less data from the network stream per call.

Note that if your network is already slow, these methods will make the download even slower -- they are not "smart" or "adaptive" methods that dynamically adjust sleep time to maintain a set speed. You will have to figure out how to calculate the amount of delay yourself.
