### ISSUE TITLE
Transmitting large data streams in 32-bit applications.

### ISSUE THREAD

**Issue by vlad-mal** [yhirose/cpp-httplib#1106]
Hello.
It seems useful that the type of parameter **in_length** in methods like 
```
inline void Response::set_content_provider(
    size_t in_length, const char *content_type, ContentProvider provider,
    ContentProviderResourceReleaser resource_releaser)

```
would not be **size_t**, but, for example, **uintmax_t**. 

Thus, for example, it would be possible to transfer files larger than 4GB.

Best regards, Vladimir Malinovsky.

**Comment by yhirose** [comment]
@vlad-mal, thank you for the suggestion, but I am ok with the current limitation, since just changing `size_t length` parameter isn't enough to support files larger than 4GB. So I would rather recommend users to switch to the 64 bit environment. :)

**Comment by vlad-mal** [comment]
OK. :)
