### ISSUE TITLE
About threads

### ISSUE THREAD

**Issue by okman334** [yhirose/cpp-httplib#1107]
I saw httplib source code create N threads, the N is equal std::thread::hardware_concurrency(). if I create more than std::thread::hardware_concurrency(), the performance will improve? sometimes, in callback function, may be will block a while, such as use httpclient or db operation in callback function. so I think, if create a bit more threads, the performance will better?

**Comment by yhirose** [comment]
@okman334, this is actually not a question for the cpp-httplib, but a general question regarding thread pooling and the answer varies depending on environments... You don't have to use the default CPPHTTPLIB_THREAD_POOL_COUNT value as it is, but you can find the best possible count that fits your environment with measuring your OS system activities, and set CPPHTTPLIB_THREAD_POOL_COUNT to the value. Hope it helps!

```
#ifndef CPPHTTPLIB_THREAD_POOL_COUNT
#define CPPHTTPLIB_THREAD_POOL_COUNT                                           \
  ((std::max)(8u, std::thread::hardware_concurrency() > 0                      \
                      ? std::thread::hardware_concurrency() - 1                \
                      : 0))
#endif
```
