### ISSUE TITLE
Trying to connect to Ethereum node through JSON RPC

### ISSUE THREAD

**Issue by jjohnson5253** [yhirose/cpp-httplib#1111]
Hi there! Wondering if anyone can help me out. I want to use the `eth_blockNumber` method through a JSON RPC call. I believe the url I want to send to is: `https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161` and I believe the JSON I want to send is `{\"id\":0,\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[]}`

Is this how I would go about doing it?

```cpp
std::string url = "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161";
std::string request = "{\"id\":0,\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[]}";
httplib::Client cli(url);

auto result = cli.Post("/jsonrpc", request, "application/json");
```

When I try this, `result` becomes `{err_:Connection}`

Does anyone have any advice? Thanks!

**Comment by PixlRainbow** [comment]
the first parameter in a client constructor is not actually the URL. The first parameter is the domain/hostname/IP address (whichever you prefer). The first parameter of the Post method is the path that follows the domain in an URL.

For example, if the full request URL is `https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161/jsonrpc` then you'd construct the client object like `cli(mainnet.infura.io)` and the first parameter of the Post method would be `/v3/9aa3d95b3bc440fa88ea12eaa4456161/jsonrpc`

**Comment by jjohnson5253** [comment]
Awesome thank you!

For anyone in future curious, here is what I did

```cpp
#include <iostream>
#include <string>
#define CPPHTTPLIB_OPENSSL_SUPPORT
#include "httplib.h"

using namespace std;

int main()
{
     // use endpoint from my infura account "https://mainnet.infura.io/v3/baf0fa2609d64e349473280a3d994200"
    string domain = "https://mainnet.infura.io";
    char endpoint[] = "/v3/baf0fa2609d64e349473280a3d994200"; // Post() requires C-style string as parameter
    
    // create request (would normally use json-rpc-cxx eventually to compile this)
    string request = "{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[]}";
    
    httplib::Client cli(domain);

    // get result after Posting
    auto result = cli.Post(endpoint, 
        request, 
        "application/json");

    cout << result->body << endl;
}
```

To compile on Linux:
```sh
g++ main.cpp -lcrypto -lssl
```
Note that you need the openssl dependency installed:
```sh
sudo apt-get install libssl-dev
```
