### ISSUE TITLE
loading url with query string

### ISSUE THREAD

**Issue by toutant** [yhirose/cpp-httplib#1117]
How would you implement file retrieval of local file that has url query string attached...
for example http://localhost:8100/file.htm&something=1

currently I get file not found ... I need the query string as part of the url but it is currently trying to load file as if the query string is part of the filename

**Comment by PixlRainbow** [comment]
query strings begin with `?` not `&`. Ampersand is used only to join multiple query parameters.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the replay!
