### ISSUE TITLE
Cannot respond to requests concurrently

### ISSUE THREAD

**Issue by swapcontext** [yhirose/cpp-httplib#1123]
> server.Get("/api",[](const Request& req,Response& res){
	system("ping /n 15 www.google.com");//This will block new request
	res.set_content("200", "text/plain");
});

**Comment by yhirose** [comment]
@swapcontext, I don't know how your client sends requests though, it should happen if you send them in a same socket connection with HTTP Keep Alive. So you shouldn't include any long blocking call in a handler. Hope it helps!
