### ISSUE TITLE
19 threads by default?

### ISSUE THREAD

**Issue by mcordova1967** [yhirose/cpp-httplib#1124]
Hello, I am testing a microservice with httplib, working very nice so far, I used Apache jMeter with a load of 1000 threads with 100 requests each one to the same microservice (access db, returns json), the service is very fast, but I observed than only 19 threads were used to manage the load at peak times, I know this because I used a single database connection for each thread using thread_local and the PostgreSQL system view that retrieves active connections always returned the same 19 connections from my microservice app.

I have a machine with 10 cores, and I think there is a default of 8 threads in httplib (am I right?), so I wonder how the number of 19 threads is decided at runtime?

Thank you,
Martin

**Comment by yhirose** [comment]
Here is the default thread count for the default thread pool in cpp-httplib:
https://github.com/yhirose/cpp-httplib/blob/084c643973b43fe796f56bf9c124c5a7ce4c0efc/httplib.h#L83-L87

If it does't satisfy your needs, you can change the value declared by `CPPHTTPLIB_THREAD_POOL_COUNT`. If you even think the default thread pool implementation in cpp-httplib isn't enough, you can make your own `TaskQueue` and provide it when making a server.  Please see [here](https://github.com/yhirose/cpp-httplib#default-thread-pool-support) in README.

Hope it helps.
