### ISSUE TITLE
HTTPU/UDP Support

### ISSUE THREAD

**Issue by whyman** [yhirose/cpp-httplib#1125]
Hey, great project, thanks for brining it to the world.

What would be needed to make this project be usable as a HTTPU server?

A brief look shows that STREAM flag is hardcoded for the socket, but everything else (socket flags/opts) is available to configure.

Thanks!

**Comment by whyman** [comment]
Note, I am _not_ talking about the newfangled HTTP3 UDP transports, simply binding to a UDP socket, instead.

**Comment by yhirose** [comment]
@whyman, thanks for the feedback. Honestly, I have never thought about HTTP UDP, and don't have any necessity to support it in my projects. If you can support it with minimal changes, please send me a pull request. I'll take a look at it. Thanks!
