### ISSUE TITLE
Callback Function, may be will block a while

### ISSUE THREAD

**Issue by wangtingbo** [yhirose/cpp-httplib#1126]
Hi, it's a great library, I am testing a microservice with httplib, working very nice so far, 
I used Apache jMeter with a load of 100 threads with 100 requests each one to the same microservice (access db, returns json), the service is very fast,
but I observed in callback function, may be will block a while ,How to improve performance? 
Thankyou。

**Comment by yhirose** [comment]
@wangtingbo, no way to improve performance unless you get a server who has more cores so that you can spawn more threads running on the cores. Hope it helps!
