### ISSUE TITLE
SSLClient upload file fail

### ISSUE THREAD

**Issue by valenhuang** [yhirose/cpp-httplib#1127]
use sslclient send content with a content provider， if buffer is large, such as 512k, SSL_write will error.

my code:
httplib::Client cli("https://xxx.com");
char* buffer = new char[512 * 1024];
auto res = cli.Post( "/stream", body.size(),
  [&](size_t offset, size_t length, DataSink &sink) {
    sink.write(buffer , 512 * 1024);
    return true;
  },"application/octet-stream");

but if I use not sslclient, It's ok.

**Comment by yhirose** [comment]
It's an incorrect usage. Please read [here](https://github.com/yhirose/cpp-httplib#send-content-with-a-content-provider) in README carefully. Also you can get more examples in `test/test/cc`. Hope it helps!
