### ISSUE TITLE
digest Authentication error 

### ISSUE THREAD

**Issue by LightYears88** [yhirose/cpp-httplib#1128]
in parse_www_authenticate function make auth map , val  should erase the Double quotation mark
for example: website response the  WWW-Authenticate: Digest qop="auth", realm="IP Camera(E5294)", nonce="59574d334e5751784e6d5536596a51304d54466c4e57453d", stale="FALSE"
the realm value is IP Camera(E5294) instead of  \"IP Camera(E5294)\"
so i add this before the value push the map:
val.erase(remove(val.begin(), val.end(), '\"'), val.end());

**Comment by yhirose** [comment]
@LightYears88, thanks for the report, but I didn't find any bug in httplib.h. I guess your test data isn't correct. To validate, I added a unit test for parse_www_authenticate function [here](https://github.com/yhirose/cpp-httplib/commit/f1334602ce1b5710e8b04fe2d1f4e59bfeaba1e9), and the test passed successfully.

**Comment by LightYears88** [comment]
yes,I run correct in VS,but not ok in Ubuntu 14.04, g++ version is 4.9.4
I print the value use cout, the val is "IP Camera(E5294)"

std::cout << "val ==" << val << std::endl;
auth[key] = val;

I got this bellow:
val =="auth"
val =="IP Camera(E5294)"
val =="4f475a6d4f5446685a575936596d51354d7a466b5a544d3d"
val =="FALSE"
