### ISSUE TITLE
API to set listen() backlog size

### ISSUE THREAD

**Issue by witaly-iwanow** [yhirose/cpp-httplib#1131]
It's currently [hard-coded to 5](https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L5110) which is not a lot imo, it would be nice to have one more API define like `CPPHTTPLIB_LISTEN_BACKLOG` which you can use to increase the number. I'd create a PR, but I guess I'll spend much more time forking and such than you just adding it to main/master whenever possible. TY

**Comment by witaly-iwanow** [comment]
The reason I'd like to have that is because I see a lot of SSL errors when load testing with `ab -c 6`, and all the errors go away with `-c 5` or when I bump the backlog size manually in `httplib.h`. I see this behavior on macOS (M1 Air), while on Ubuntu it has no problems whatsoever even with `-c 100` - I suspect the backlog parameter might actually be ignored on Linux

**Comment by yhirose** [comment]
@witaly-iwanow, I added it!
