### ISSUE TITLE
Error descriptions

### ISSUE THREAD

**Issue by josemaGruposantander** [yhirose/cpp-httplib#1133]
Hi,

When i try to do a post and it fails:

`httplib::Client cliSts(std::string(protocol)+ "://" + stsServer + ":" + boost::lexical_cast<std::string>(port));
const auto resSts = cliSts.Post(stsTarget, headersSts, httplib::Params{});`

Then the object resSts has te attribute err_ defined with one of the following elements:

`enum class Error {
  Success = 0,
  Unknown,
  Connection,
  BindIPAddress,
  Read,
  Write,
  ExceedRedirectCount,
  Canceled,
  SSLConnection,
  SSLLoadingCerts,
  SSLServerVerification,
  UnsupportedMultipartBoundaryChars,
  Compression,
};`

But i don´t have any description about the error. i can't see the statusCode (200. 404...) because the object is null when it fails.
Is there a wey to see the error message when the post action fail?

**Comment by PixlRainbow** [comment]
if there is no status code or the object is null, that means httplib was completely unable to find or connect to the server at all or could not get any response from the server.  
httplib currently does not provide human-readable error descriptions, only error codes to indicate the rough category of error.

**Comment by josemaGruposantander** [comment]
That is what i see. The only information you can have is the error category but no any precise information, I opened this post to know if there was a way to have more information

**Comment by yhirose** [comment]
@josemaGruposantander, sorry for the inconvenience. As @PixlRainbow, mentioned, cpp-httplib gives only error codes to indicate the rough category of error, and I am planning to enhance it.
