### ISSUE TITLE
POSTing large Text

### ISSUE THREAD

**Issue by npritchard** [yhirose/cpp-httplib#1134]
Hi thanks for the fantastic library - a lot of effort is greatly appreciated.

I'm posting large volumes of data to a cpp-httplib server and getting error 413 in response. It's returned as a result of this section around line 5004 in the latest version:

```
      const auto& content_type = req.get_header_value("Content-Type");
      if (!content_type.find("application/x-www-form-urlencoded")) {
        if (req.body.size() > CPPHTTPLIB_REQUEST_URI_MAX_LENGTH) {
          res.status = 413; // NOTE: should be 414?
          return false;
        }
        detail::parse_query_text(req.body, req.params);
      }
```

So what I understand is that, unless there's a Content-Type header 'application/x-www-form-urlencoded', this makes sure that the body of the data cannot be larger than CPPHTTPLIB_REQUEST_URI_MAX_LENGTH. 

Is this the correct logic?

Even so, I'm not sure what this line is doing:

`      if (!content_type.find("application/x-www-form-urlencoded")) {`

Should that not be:
`      if (content_type.find("application/x-www-form-urlencoded") == std::string::npos) {`

Thanks

**Comment by yhirose** [comment]
That's opposite. If there's a Content-Type header 'application/x-www-form-urlencoded', then do the CPPHTTPLIB_REQUEST_URI_MAX_LENGTH check. If the test succeeds, then parse the form text and construct req.params.
Hope the explanation helps!
