### ISSUE TITLE
I can't build https client after successful build of https server

### ISSUE THREAD

**Issue by mcordova1967** [yhirose/cpp-httplib#1136]
I just built an https server with openssl 1.1, so far so good. after that I came to write a simple https client, but I can't build it, these are the errors:

g++ -L"C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0" -L"C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\opt\lib" -L"C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\lib\gcc\x86_64-w64-mingw32\lib" -o "HttpClient"  ./src/HttpClient.o   -lcrypto -lssl -lws2_32
./src/HttpClient.o:HttpClient.cpp:(.text$_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv[_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv]+0x73): undefined reference to `__imp_CertOpenSystemStoreW'
./src/HttpClient.o:HttpClient.cpp:(.text$_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv[_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv]+0x82): undefined reference to `__imp_CertEnumCertificatesInStore'
./src/HttpClient.o:HttpClient.cpp:(.text$_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv[_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv]+0x126): undefined reference to `__imp_CertFreeCertificateContext'
./src/HttpClient.o:HttpClient.cpp:(.text$_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv[_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv]+0x131): undefined reference to `__imp_CertCloseStore'
./src/HttpClient.o:HttpClient.cpp:(.text$_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENKUlvE0_clEv[_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENKUlvE0_clEv]+0x73): undefined reference to `__imp_CertOpenSystemStoreW'
./src/HttpClient.o:HttpClient.cpp:(.text$_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENKUlvE0_clEv[_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENKUlvE0_clEv]+0x82): undefined reference to `__imp_CertEnumCertificatesInStore'
./src/HttpClient.o:HttpClient.cpp:(.text$_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENKUlvE0_clEv[_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENKUlvE0_clEv]+0x126): undefined reference to `__imp_CertFreeCertificateContext'
./src/HttpClient.o:HttpClient.cpp:(.text$_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENKUlvE0_clEv[_ZZSt9call_onceIZN7httplib9SSLClient10load_certsEvEUlvE_JEEvRSt9once_flagOT_DpOT0_ENKUlvE0_clEv]+0x131): undefined reference to `__imp_CertCloseStore'

My code: (it compiles OK)

#define CPPHTTPLIB_OPENSSL_SUPPORT
#define WIN32_LEAN_AND_MEAN 1

#include <windows.h>
#include <httplib.h>
#include <string>
#include <chrono>

using namespace std;

int main() {

	httplib::Client cli("https://localhost/gasto");
	cli.set_ca_cert_path("C:/certs/certificate.crt");
	cli.enable_server_certificate_verification(false);
	auto res = cli.Get("/gasto");
	res->status;
	res->body;
	return 0;

}

I really tried to search for a clue before posting here, but I could not find a page about these specific link problems which seem related to OPENSSL certificate API, looks like I am missing a static library?

Thank you,
Martin

**Comment by PixlRainbow** [comment]
> I just built an https server with openssl 1.1

when you say you used OpenSSL 1.1, do you mean **1.1.1** or **1.1.0**? Only 1.1.1 and above is supported.

**Comment by mcordova1967** [comment]
I used OpenSSL 1.1.1:

C:\Users\marti>openssl version
OpenSSL 1.1.1m  14 Dec 2021

I found the problem, I had to add library libcrypt32.a -L crypt32 this was the one missing, containing the Windows certificate store functions, or so it seems to me. Also required is -L wsa_32. In any case, now it runs but the client is doing nothing, no error messages shown in console and the server is not receiving the request, it has a log that prints all requests and I know it is working because I can hit it with a browser.

Regards,
Martin

**Comment by PixlRainbow** [comment]
Based on the code shown in your first message, there may be several possible issues:
```cpp
httplib::Client cli("https://localhost/gasto");
```
The constructor only allows hostname (e.g. "localhost") or scheme+hostname (e.g. "https://localhost"), it does not allow path. Including the path "/gasto" in the constructor will make request fail as it will attempt to resolve as if "/gasto" was part of the hostname, which is not valid.

This library does not automatically throw exceptions or print error messages. You have to check for yourself if an error has occurred by checking if res is null and the value of `res.error()`

**Comment by mcordova1967** [comment]
Thank you PixlRainbow, my mistake for not doing a good reading of the basic examples of http client.  Regards.
