### ISSUE TITLE
Reverse proxy support

### ISSUE THREAD

**Issue by avdbg** [yhirose/cpp-httplib#114]

**Comment by yhirose** [comment]
@avdbg, thanks for the feedback. But your request is beyond the scope of this library. I would like to keep cpp-httplib simple (and keep my life simple as well 😄). Sorry about that.

**Comment by avdbg** [comment]
I found an easy way to do this, just like this:
```
svr.Get(".*", [](const httplib::Request& req, httplib::Response& res) {
		httplib::Client cli("blog.51cto.com", 80);
		auto req2 = req;
		cli.send(req2, res);
	});
```
Although it has some problems, it can meet my current needs by some small modify.
And thanks for your works.

**Comment by yhirose** [comment]
@avdbg, glad to hear that you found the solution!
