### ISSUE TITLE
Support mbedtls instead of OpenSSL

### ISSUE THREAD

**Issue by mrexodia** [yhirose/cpp-httplib#1142]
OpenSSL is a very heavy dependency and mbedtls is fast to compile and easy to embed in your application.

I looked at the code a year ago or so, but it doesn’t seem like the SSL parts are designed to be replaced easily unfortunately…

A similar idea would be to support the OS’ native SSL implementation so that you can do HTTPS without any dependencies. This should be possible at least on Windows but I’m pretty sure on Mac too.

Also: do you have GitHub sponsors?

**Comment by yhirose** [comment]
@mrexodia, thanks for the feedback. It's a good idea, but I simply don't have time to work on it. Of course, a pull request is always welcome!

**Comment by mrexodia** [comment]
That looks very promising, I will definitely give it a try!

**Comment by lifw555** [comment]
Has there been any progress?
thx
