### ISSUE TITLE
gcc4.8.5 编译错误

### ISSUE THREAD

**Issue by robinfoxnan** [yhirose/cpp-httplib#1143]
主要是在find_content_type()中使用字面量的运算符重载，
在编译时候告错，
起始，个人认为这样的处理方式效率并不高，不如直接设置静态变量 std::map<string, string> {};

直接搜索字符串，因为，map是红黑树，
switch case 是线性比较，速度不如map快，

**Comment by yhirose** [comment]
@robinfoxnan, thanks for the feedback, but I can't read Chinese. :)

**Comment by PixlRainbow** [comment]
they say that your function `find_content_type()` has a very long switch clause and it might be more efficient to make use of a map, which has index lookup implemented using red-black tree

**Comment by yhirose** [comment]
@PixlRainbow, thank you for the translation.
@robinfoxnan, I am not a compiler expert though, I think we don't have to worry about the performance of the switch statement. Here is a good reference from stackoverflow: https://stackoverflow.com/questions/1028437/why-switch-case-and-not-if-else-if#answer-1028463

**Comment by robinfoxnan** [comment]
it doesn't matter to use witch case, the diffrence of performance is not so big,
i change it to using map, only because  gcc4.8.5 can't compile that operator "" _t(  )
