### ISSUE TITLE
How to restrict only one process listening on the given port?

### ISSUE THREAD

**Issue by mcordova1967** [yhirose/cpp-httplib#1144]
Hello, I observed that multiple copies of my program can attach to port 443, only one will receive requests, but the svr.listen() method is always returning true.

If I use the socket option flag svr.listen("0.0.0.0", 443, SO_EXCLUSIVEADDRUSE) the listen() always returns false and no process can listen to the port, not even the first one.

Is there a portable (windows/linux) way of setting a flag so that only one program listens to the given port at the same time?

Thank you,
Martin

**Comment by yhirose** [comment]
@mcordova1967, the current cpp-httplib behavior is based on the following code.

https://github.com/yhirose/cpp-httplib/blob/b324921c1aeff2976544128e4bb2a0979a4aa595/httplib.h#L1531-L1547

You can completely change the socket option setting with the `set_socket_options `.
https://github.com/yhirose/cpp-httplib/blob/b324921c1aeff2976544128e4bb2a0979a4aa595/httplib.h#L652

As you may know the actual effect of each option isn't consistent among operating systems unfortunately. So I am not in good position to answer your questions...

Hope is helps.
