### ISSUE TITLE
decode_url() not working for international spanish characters (2 byte sequences)

### ISSUE THREAD

**Issue by mcordova1967** [yhirose/cpp-httplib#1145]
This value of parameter descrip:
descrip=Gastos%20%C3%A1%C3%A9%C3%AD%C3%B3%C3%BA%C3%B1%C3%91%206

should decode to this:
descrip=Gastos áéíóúñÑ 6

But it is returning something else. I could not fix it in the original library code, but I found a code that works and returns the expected result, taken from: https://stackoverflow.com/questions/154536/encode-decode-urls-in-c

The code...

const char HEX2DEC[55] =
{
     0, 1, 2, 3,  4, 5, 6, 7,  8, 9,-1,-1, -1,-1,-1,-1,
    -1,10,11,12, 13,14,15,-1, -1,-1,-1,-1, -1,-1,-1,-1,
    -1,-1,-1,-1, -1,-1,-1,-1, -1,-1,-1,-1, -1,-1,-1,-1,
    -1,10,11,12, 13,14,15
};

#define __x2d__(s) HEX2DEC[*(s)-48]
#define __x2d2__(s) __x2d__(s) << 4 | __x2d__(s+1)

std::string decodeURI(const char * s) {
    unsigned char b;
    std::string ws;
    while (*s) {
        if (*s == '%')
            if ((b = __x2d2__(s + 1)) >= 0x80) {
                if (b >= 0xE0) { // three byte codepoint
                    ws += ((b & 0b00001111) << 12) | ((__x2d2__(s + 4) & 0b00111111) << 6) | (__x2d2__(s + 7) & 0b00111111);
                    s += 9;
                }
                else { // two byte codepoint
                    ws += (__x2d2__(s + 4) & 0b00111111) | (b & 0b00000011) << 6;
                    s += 6;
                }
            }
            else { // one byte codepoints
                ws += b;
                s += 3;
            }
        else { // no %
            ws += *s;
            s++;
        }
    }
    return ws;
}

I replaced the body of decode_url() with this code and it worked, the URL param values with international characters are being correctly decoded and inserted into a database with the expected value. I don't understand either code, but I wonder if the above can give a clue about how to fix the problem in the original function code.

In the meantime I modified httplib.h so I can use it to receive international characters in parameter values, here is the code:

const char HEX2DEC[55] =
{
     0, 1, 2, 3,  4, 5, 6, 7,  8, 9,-1,-1, -1,-1,-1,-1,
    -1,10,11,12, 13,14,15,-1, -1,-1,-1,-1, -1,-1,-1,-1,
    -1,-1,-1,-1, -1,-1,-1,-1, -1,-1,-1,-1, -1,-1,-1,-1,
    -1,10,11,12, 13,14,15
};

#define __x2d__(s) HEX2DEC[*(s)-48]
#define __x2d2__(s) __x2d__(s) << 4 | __x2d__(s+1)

inline std::string decode_url(const std::string &ss,
                              bool convert_plus_to_space) {

  const char * s = ss.c_str();
  unsigned char b;
  std::string ws;
  while (*s) {
      if (*s == '%')
          if ((b = __x2d2__(s + 1)) >= 0x80) {
              if (b >= 0xE0) { // three byte codepoint
                  ws += ((b & 0b00001111) << 12) | ((__x2d2__(s + 4) & 0b00111111) << 6) | (__x2d2__(s + 7) & 0b00111111);
                  s += 9;
              }
              else { // two byte codepoint
                  ws += (__x2d2__(s + 4) & 0b00111111) | (b & 0b00000011) << 6;
                  s += 6;
              }
          }
          else { // one byte codepoints
              ws += b;
              s += 3;
          }
      else { // no %
          ws += *s;
          s++;
      }
  }
  return ws;
}

**Comment by yhirose** [comment]
@mcordova1967, I added a test case with your sample string in `test/test.cc`, but I couldn't reproduce the problem...
https://github.com/yhirose/cpp-httplib/commit/865b0e4c03a90823d39d133949ce259ffcf7916c

**Comment by mcordova1967** [comment]
Thank you for the prompt reply @yhirose. I reproduced the problem with an isolated test case, the output of the program:

input -> descrip=Gastos%20%C3%A1%C3%A9%C3%AD%C3%B3%C3%BA%C3%B1%C3%91%206
httplib -> descrip=Gastos Ã¡Ã©Ã­Ã³ÃºÃ±Ã‘ 6
stackoverflow -> descrip=Gastos áéíóúñÑ 6

Code:

`#include <iostream>
#include <string>
#include <filesystem>
#include <iostream>
#include <fstream>
#include <string>
#include <unordered_map>
#include <vector>
#include <regex>

const char HEX2DEC[55] =
{
     0, 1, 2, 3,  4, 5, 6, 7,  8, 9,-1,-1, -1,-1,-1,-1,
    -1,10,11,12, 13,14,15,-1, -1,-1,-1,-1, -1,-1,-1,-1,
    -1,-1,-1,-1, -1,-1,-1,-1, -1,-1,-1,-1, -1,-1,-1,-1,
    -1,10,11,12, 13,14,15
};

#define __x2d__(s) HEX2DEC[*(s)-48]
#define __x2d2__(s) __x2d__(s) << 4 | __x2d__(s+1)

//https://stackoverflow.com/questions/154536/encode-decode-urls-in-c
std::string decodeURI(const char * s) {
    unsigned char b;
    std::string ws;
    while (*s) {
        if (*s == '%')
            if ((b = __x2d2__(s + 1)) >= 0x80) {
                if (b >= 0xE0) { // three byte codepoint
                    ws += ((b & 0b00001111) << 12) | ((__x2d2__(s + 4) & 0b00111111) << 6) | (__x2d2__(s + 7) & 0b00111111);
                    s += 9;
                }
                else { // two byte codepoint
                    ws += (__x2d2__(s + 4) & 0b00111111) | (b & 0b00000011) << 6;
                    s += 6;
                }
            }
            else { // one byte codepoints
                ws += b;
                s += 3;
            }
        else { // no %
            ws += *s;
            s++;
        }
    }
    return ws;
}

inline bool is_hex(char c, int &v) {
  if (0x20 <= c && isdigit(c)) {
    v = c - '0';
    return true;
  } else if ('A' <= c && c <= 'F') {
    v = c - 'A' + 10;
    return true;
  } else if ('a' <= c && c <= 'f') {
    v = c - 'a' + 10;
    return true;
  }
  return false;
}

bool from_hex_to_i(const std::string &s, size_t i, size_t cnt,
                          int &val) {
  if (i >= s.size()) { return false; }

  val = 0;
  for (; cnt; i++, cnt--) {
    if (!s[i]) { return false; }
    int v = 0;
    if (is_hex(s[i], v)) {
      val = val * 16 + v;
    } else {
      return false;
    }
  }
  return true;
}

size_t to_utf8(int code, char *buff) {
  if (code < 0x0080) {
    buff[0] = (code & 0x7F);
    return 1;
  } else if (code < 0x0800) {
    buff[0] = static_cast<char>(0xC0 | ((code >> 6) & 0x1F));
    buff[1] = static_cast<char>(0x80 | (code & 0x3F));
    return 2;
  } else if (code < 0xD800) {
    buff[0] = static_cast<char>(0xE0 | ((code >> 12) & 0xF));
    buff[1] = static_cast<char>(0x80 | ((code >> 6) & 0x3F));
    buff[2] = static_cast<char>(0x80 | (code & 0x3F));
    return 3;
  } else if (code < 0xE000) { // D800 - DFFF is invalid...
    return 0;
  } else if (code < 0x10000) {
    buff[0] = static_cast<char>(0xE0 | ((code >> 12) & 0xF));
    buff[1] = static_cast<char>(0x80 | ((code >> 6) & 0x3F));
    buff[2] = static_cast<char>(0x80 | (code & 0x3F));
    return 3;
  } else if (code < 0x110000) {
    buff[0] = static_cast<char>(0xF0 | ((code >> 18) & 0x7));
    buff[1] = static_cast<char>(0x80 | ((code >> 12) & 0x3F));
    buff[2] = static_cast<char>(0x80 | ((code >> 6) & 0x3F));
    buff[3] = static_cast<char>(0x80 | (code & 0x3F));
    return 4;
  }
}

std::string decode_url(const std::string &s, bool convert_plus_to_space) {
  std::string result;

  for (size_t i = 0; i < s.size(); i++) {
    if (s[i] == '%' && i + 1 < s.size()) {
      if (s[i + 1] == 'u') {
        int val = 0;
        if (from_hex_to_i(s, i + 2, 4, val)) {
          // 4 digits Unicode codes
          char buff[4];
          size_t len = to_utf8(val, buff);
          if (len > 0) { result.append(buff, len); }
          i += 5; // 'u0000'
        } else {
          result += s[i];
        }
      } else {
        int val = 0;
        if (from_hex_to_i(s, i + 1, 2, val)) {
          // 2 digits hex codes
          result += static_cast<char>(val);
          i += 2; // '00'
        } else {
          result += s[i];
        }
      }
    } else if (convert_plus_to_space && s[i] == '+') {
      result += ' ';
    } else {
      result += s[i];
    }
  }

  return result;
}

int main()
{

	std::string uri = "descrip=Gastos%20%C3%A1%C3%A9%C3%AD%C3%B3%C3%BA%C3%B1%C3%91%206";
	//expected result = "descrip=Gastos áéíóúñÑ 6"
	std::cout << "input -> " << uri <<  std::endl;
	std::cout << "httplib -> " << decode_url(uri, false) <<  std::endl;
	std::cout << "stackoverflow -> " << decodeURI(uri.c_str()) <<  std::endl;

}

`

**Comment by yhirose** [comment]
@mcordova1967 could you try `cd test && make test && ./test --gtest_filter="DecodeURL*.*"` in your terminal?

The result is supposed to be as below.
![image](https://user-images.githubusercontent.com/357397/147411219-d5981c54-964c-4c86-94a1-169e3a69c131.png)

**Comment by mcordova1967** [comment]
Hello, I can't make test on Windows (using msys2), but anyway, I did run my small test case on Linux and httplib works as expected on Linux, the other code (stackoverflow) does not, it's the opposite of running on Windows, so I wonder if there is a platform encoding issue here.

root@ubuntuserver:/opt/helloworld# ./helloworld
input -> descrip=Gastos%20%C3%A1%C3%A9%C3%AD%C3%B3%C3%BA%C3%B1%C3%91%206
httplib -> descrip=Gastos áéíóúñÑ 6
stackoverflow -> descrip=Gastos ▒▒▒▒▒▒▒ 6
root@ubuntuserver:/opt/helloworld#

BTW, this is the error when running "make test"

#c_rehash .
process_begin: CreateProcess(NULL, #c_rehash ., ...) failed.
make (e=2): The system cannot find the file specified.
Makefile:61: recipe for target 'cert.pem' failed
make: *** [cert.pem] Error 2

cert.pem exists in the /test folder, my installation folder is: C:\cpp-httplib-master

Regards,
Martin

**Comment by mcordova1967** [comment]
I managed to solve the issue using the PostgreSQL unicode driver and setting iso-8859-1 in the content-type header of my requests that serve JSON, that combination works on Windows and allows me to use httptlib parameter decoding without problems. Thank you for your support and patience. Regards, Martin
