### ISSUE TITLE
BoringSSL support on Windows

### ISSUE THREAD

**Issue by vitaly-castLabs** [yhirose/cpp-httplib#1146]
I wonder if it's possible to merge [this change](https://github.com/witaly-iwanow/cpp-httplib/commit/384e953df3d841b1e8b6106621936640fd8a220a) in?
I'm working on a project which links webrtc statically and have to use BoringSSL for that reason. API-wise BoringSSL is almost identical to OpenSSL 1.1, and everything works out of the box on Linux and macOS. The problem is on Windows due to some defines in wincrypt.h which happen to be named the same as some structures in BoringSSL headers, very much NOMINMAX-like mess

**Comment by yhirose** [comment]
@vitaly-castLabs, could you send a pull request?

**Comment by yhirose** [comment]
Resolved by #1148
