### ISSUE TITLE
Testing found that static file service files exceeding 4GB caused exceptions 

### ISSUE THREAD

**Issue by cool2528** [yhirose/cpp-httplib#1150]
The test found that the static file service file exceeded 4GB and caused an exception.
 detail::read_file does not close the file handle after reading the file.

**Comment by yhirose** [comment]
@cool2528, thanks for the feedback. Could you provide more detailed information, and the smallest possible code example from your test code that can reproduce the problem?

**Comment by cool2528** [comment]
`//
//  sample.cc
//
//  Copyright (c) 2019 Yuji Hirose. All rights reserved.
//  MIT License
//

#include <chrono>
#include <cstdio>
#include <httplib.h>

#define SERVER_CERT_FILE "./cert.pem"
#define SERVER_PRIVATE_KEY_FILE "./key.pem"

using namespace httplib;

std::string dump_headers(const Headers &headers) {
  std::string s;
  char buf[BUFSIZ];

  for (auto it = headers.begin(); it != headers.end(); ++it) {
    const auto &x = *it;
    snprintf(buf, sizeof(buf), "%s: %s\n", x.first.c_str(), x.second.c_str());
    s += buf;
  }

  return s;
}

std::string log(const Request &req, const Response &res) {
  std::string s;
  char buf[BUFSIZ];

  s += "================================\n";

  snprintf(buf, sizeof(buf), "%s %s %s", req.method.c_str(),
           req.version.c_str(), req.path.c_str());
  s += buf;

  std::string query;
  for (auto it = req.params.begin(); it != req.params.end(); ++it) {
    const auto &x = *it;
    snprintf(buf, sizeof(buf), "%c%s=%s",
             (it == req.params.begin()) ? '?' : '&', x.first.c_str(),
             x.second.c_str());
    query += buf;
  }
  snprintf(buf, sizeof(buf), "%s\n", query.c_str());
  s += buf;

  s += dump_headers(req.headers);

  s += "--------------------------------\n";

  snprintf(buf, sizeof(buf), "%d %s\n", res.status, res.version.c_str());
  s += buf;
  s += dump_headers(res.headers);
  s += "\n";

  //if (!res.body.empty()) { s += res.body; }

  s += "\n";

  return s;
}
int main(void) {
#ifdef CPPHTTPLIB_OPENSSL_SUPPORT
  SSLServer svr(SERVER_CERT_FILE, SERVER_PRIVATE_KEY_FILE);
#else
  Server svr;
#endif

  if (!svr.is_valid()) {
    printf("server has an error...\n");
    return -1;
  }
  svr.set_mount_point("/", R"(E:\test_media_files\22)");
  svr.Get("/666.mp4", [=](const Request & req, Response &res) {
    std::string path = R"(E:\test_media_files\22\666.mp4)";
      detail::read_file(path, res.body);
      res.set_header("Content-Type", "video/mp4");
  });
  svr.Post("/", [=](const Request & req, Response &res) {
    res.set_redirect("/hi");
  });
  svr.Get("/hi", [](const Request & req, Response &res) {
    res.set_content("Hello World!\n", "text/plain");
  });

  svr.Get("/slow", [](const Request & /*req*/, Response &res) {
    std::this_thread::sleep_for(std::chrono::seconds(2));
    res.set_content("Slow...\n", "text/plain");
  });

  svr.Get("/dump", [](const Request &req, Response &res) {
    res.set_content(dump_headers(req.headers), "text/plain");
  });

  svr.Get("/stop",
          [&](const Request & /*req*/, Response & /*res*/) { svr.stop(); });

  svr.set_error_handler([](const Request & /*req*/, Response &res) {
    const char *fmt = "<p>Error Status: <span style='color:red;'>%d</span></p>";
    char buf[BUFSIZ];
    snprintf(buf, sizeof(buf), fmt, res.status);
    res.set_content(buf, "text/html");
  });

  svr.set_logger([](const Request &req, const Response &res) {
    printf("%s", log(req, res).c_str());
  });
  svr.listen("0.0.0.0", 8080);

  return 0;
}
`
I used your official example and simply added a static file service mapping directory when I accessed
If the `666.mp4` file is smaller than 5GB, it seems to be fine, but when the file is larger than 5GB, it will trigger an exception. And after I locate it, it should be caused by reading the file too large when reading_file. But I see that your code requires that res.body must be read as a complete file, and then you modify the file content of res.body by offset when you apply_ranges.
![image](https://user-images.githubusercontent.com/42990446/147722601-2016deb0-1393-46c2-854c-f590eb90c6ef.png)
![image](https://user-images.githubusercontent.com/42990446/147722625-7184ffc4-d70c-49a6-8dc8-e835393c1f20.png)
I think your intention is to put together response headers, but I personally suggest that developers have a reason to write these headers themselves, whereas your forward thinking may cause inconvenience to users.
This is the size of the file used for testing
![image](https://user-images.githubusercontent.com/42990446/147722753-a75bba4f-59c9-4d91-a78d-d8f0b65638a5.png)

**Comment by yhirose** [comment]
@cool2528, thanks for the information. First of all, your following code isn't correct.

```cpp
svr.set_mount_point("/", R"(E:\test_media_files\22)");
svr.Get("/666.mp4", [=](const Request & req, Response &res) {
std::string path = R"(E:\test_media_files\22\666.mp4)";
detail::read_file(path, res.body);
res.set_header("Content-Type", "video/mp4");
});
```

You don't have to make the Get handler for files at all since `Server::handle_file_request` will handle your request properly for you. You can simply do this and should remove the Get handler:

```cpp
svr.set_mount_point("/", R"(E:\test_media_files\22)");
```

You can see how `Server::handle_file_request` works here:

https://github.com/yhirose/cpp-httplib/blob/37fd4eb643f8d4f6261560ead150864827938d57/httplib.h#L5126-L5154

Another thing is that you have to compile with 64bit mode, otherwise `std::string Response::body` member variable can't hold content which is larger than 4GB.

As for serving such huge files, the static file server feature compiled with 32bit doesn't work properly. You can use [the content receiver](https://github.com/yhirose/cpp-httplib#receive-content-with-a-content-receiver), but I know it's a bit inconvenient than the static file server way though.

So please first make sure to compile with 64bit, and remove the Get handler from your example. Then, please let me know what will happen. Thanks.

**Comment by cool2528** [comment]
Yes, I forgot to mention that I used a Windows x86 build and not a Windows x64 build of the above code. I guess it could be due to x86 memory limitations. I just found this problem because I used x86.
