### ISSUE TITLE
The is_file function cannot determine large files using the system stat API.

### ISSUE THREAD

**Issue by cool2528** [yhirose/cpp-httplib#1151]
A new problem was found with is_file, which uses stat to determine that a file exists but returns false, resulting in the following code not executing properly
![image](https://user-images.githubusercontent.com/42990446/147724684-f044932e-fd7e-44c3-a702-fa559e249b07.png)
![image](https://user-images.githubusercontent.com/42990446/147724722-2aaa06cf-20f4-4051-8be9-6002e762f776.png)
``` svr.set_mount_point("/", R"(E:\test_media_files\22)");```
In the E:\test_media_files\22 folder, there is a file 666.mp4, which is a little over 5GB in size.
I first see for myself what causes the cause of the problem if found I will come here to explain the cause of the problem

**Comment by cool2528** [comment]
The x64 also triggers an exception when reading a file, as if multiple threads have entered read_file at the same time.  We suggest you to test a file of 5GB or more

**Comment by PixlRainbow** [comment]
MSVC compiler in particular does not support large files through the C standard `stat` API.

@yhirose we may need to add conditional compilation to use [`GetFileSizeEx`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfilesizeex?redirectedfrom=MSDN) instead of `stat` when MSVC being used. `stat` otherwise works normally on other compilers, including mingw on Windows.

**Comment by cool2528** [comment]
Read in large video files segmentation can be written in the following format This current mainstream browsers support the way of course the client needs to determine their own response protocol header Unfortunately, the software I have tested ffmpeg and potplay are not applicable to the following code 
Most likely, these software are not written to follow the HTTP protocol very well 

```
 if (req.path == "/666.mp4") { 
          std::string path = R"(E:\test_media_files\22\666.mp4)";
        if (!req.ranges.empty()) {
           
          std::ifstream fs(path, std::ios_base::binary);
          fs.seekg(0, std::ios_base::end);
          auto size = fs.tellg();
          auto offsets = detail::get_range_offset_and_length(req, size, 0);
          auto offset = offsets.first;
          auto length = offsets.second;
          if (length > 8192 * 10) { 
              length = 8192 * 10;
          }
          fs.seekg(offset);
          res.body.resize(static_cast<size_t>(length));
          fs.read(&res.body[0], static_cast<std::streamsize>(length));
          fs.close();
          res.status = 206;
          auto content_range =
              detail::make_content_range_header_field(offset, length, size);
          res.set_header("Content-Range", content_range);
          res.set_header("Accept-Ranges", "bytes");
          res.set_header("Content-Length", std::to_string(res.body.size()));
          res.set_header("Content-Type", "video/mp4");
          printf("%s", log(req, res).c_str());
        } else {
          //detail::read_file(path, res.body);
        //  std::ifstream fs(path, std::ios_base::binary);
        /*  fs.seekg(0, std::ios_base::end);
          auto size = fs.tellg();
          fs.close();*/
          // Content-Type:
       /*   res.set_header("Content-Type", "video/mp4");
          res.set_header("Accept-Ranges", "bytes");
          res.set_header("Content-Length", std::to_string(res.body.size()));
          res.status = 200;
          printf("%s", log(req, res).c_str());*/
          std::ifstream fs(path, std::ios_base::binary);
          fs.seekg(0, std::ios_base::end);
          auto size = fs.tellg();
          auto offsets = std::make_pair(0,8192);
          auto offset = offsets.first;
          auto length = offsets.second;
          fs.seekg(offset);
          res.body.resize(static_cast<size_t>(length));
          fs.read(&res.body[0], static_cast<std::streamsize>(length));
          fs.close();
          res.status = 206;
          auto content_range =
              detail::make_content_range_header_field(offset, length, size);
          res.set_header("Content-Range", content_range);
          res.set_header("Accept-Ranges", "bytes");
          res.set_header("Content-Length", std::to_string(res.body.size()));
          res.set_header("Content-Type", "video/mp4");
        }
```
This 666.mp4 is a 5 GB mp4 file and it plays very well now 
![image](https://user-images.githubusercontent.com/42990446/147741564-142d9321-1082-4ac3-99f8-db849f7a39c0.png)

is_file I changed it like this and it works fine

```
inline void read_file(const std::string &path, std::string &out) {
  std::ifstream fs(path, std::ios_base::binary);
  fs.seekg(0, std::ios_base::end);
  auto size = fs.tellg();
  fs.seekg(0);
  out.resize(static_cast<size_t>(size));
  fs.read(&out[0], static_cast<std::streamsize>(size));
  fs.close();
}
```

**Comment by yhirose** [comment]
@cool2528, please see this commit. https://github.com/yhirose/cpp-httplib/pull/1153/commits/301a54a2287136ef6368bcf098a7dc9c2608c67c
