### ISSUE TITLE
Listen failed when there are some connections left 

### ISSUE THREAD

**Issue by donglintao** [yhirose/cpp-httplib#1157]
Without setting SO_REUSEADDR, a socket may listen failed when there are some connections left in TIME_WAITTING status. 
So why not set SO_REUSEADDR for listening?

**Comment by yhirose** [comment]
It does actually.
https://github.com/yhirose/cpp-httplib/blob/65a8f4cf44195d6d042c9ed0a174c9c8ea0a1b05/httplib.h#L1540-L1556

**Comment by donglintao** [comment]
But it sets SO_REUSEADDR only when SO_REUSEPORT is not defined.

I do not think SO_REUSEPORT is equal to SO_REUSEADDR.

**Comment by donglintao** [comment]
And i am working in linux  environment.

**Comment by yhirose** [comment]
Please see https://github.com/yhirose/cpp-httplib/issues/506#issuecomment-637863292.

**Comment by donglintao** [comment]
> Please see [#506 (comment)](https://github.com/yhirose/cpp-httplib/issues/506#issuecomment-637863292).

Thank you very much for your reply.

Compared with SO_ REUSEADDR，SO_ REUSEPORT has more restrictions.  
   Only sockets with SO_ REUSEPORT opened can be reused.
   Only sockets with same user id can be reused.


Yes, SO_ REUSEPORT seems safer.
