### ISSUE TITLE
Getting a vector from a POST/GET request

### ISSUE THREAD

**Issue by ngoncalves** [yhirose/cpp-httplib#116]
Hello,

In my application, I have an array as part of the input arguments for a POST call. The array is being sent (I am using Python's requests) as: http://my_url?array=value1&array=value2&array=value3 

Thus the same name is mapped to different values. This does not pose an immediate problem for httplib, because it is using a multimap for storing the POST arguments. However the library does not seem to have a function/method for retrieving array arguments. The method Request::get_param_value() returns the first value that maps to the given argument name.

So, am I missing how to retrieve array arguments or is this not supported in httplib ? 

Thanks,

 Nelson Gonçalves

**Comment by yhirose** [comment]
@ngoncalves, thanks for the feedback. cpp-httplib was actually missing a method to retrieve array arguments.

I have just added it. (I added a parameter `size_t id` in `get_param_value` method to get a desired value.) Also I added `get_param_value_count` to get the count of values in array.

```cpp
    std::string get_param_value(const char* key, size_t id = 0) const;
    size_t get_param_value_count(const char* key) const;
```

Please let me know if the above methods solve your problem.
Thanks!

**Comment by ngoncalves** [comment]
Thanks @yhirose, I updated my code and it worked perfectly.
