### ISSUE TITLE
Compiler errors when i include cpp-httplib

### ISSUE THREAD

**Issue by VladislavAlpatov** [yhirose/cpp-httplib#1160]
When I link the library to my project, what happens is, I have no idea how to fix it
![devenv_kQVcMzH3p3](https://user-images.githubusercontent.com/59374393/148557814-91ca6257-7604-4a03-8101-08072d91528c.png)

**Comment by yhirose** [comment]
You can see what to do in Makefiles (Linux or macOS) or *vcxproj files in test and examples folders. Hope it helps.
