### ISSUE TITLE
Send content with the content provider without content-length: example wrong or outdated?

### ISSUE THREAD

**Issue by ArnaudBienner** [yhirose/cpp-httplib#1161]
The example on README.md uses a lambda function that takes 3 arguments:
`(size_t offset, size_t length, DataSink &sink)`

However, this fails to compile in the current version, because there is two `set_content_provider` functions, and the one without length specified takes a `ContentProviderWithoutLength` function as parameter, which signature is `(size_t offset, DataSink &sink)`

Is this simply a mistake on the example?

Or was this supported at some point? Or is there a desire to support this?

I can see the value about having this, in case of range requests: one doesn't know yet the content-length of the response (depends on range the user asked for) so cannot use `void set_content_provider(size_t length, const char *content_type, ContentProvider provider, ...)` but would still be interested in using a `ContentProvider` instead of a `ContentProviderWithoutLength` so it knows the length/range user requested. Thus can read only the portion of a file that user is interested in.

I think this usecase can be implemented today, by computing the content-length prior to calling `set_content_provider` by checking for `req.ranges` but IMHO it would be nicer if the library supports this more natively. What do you think?

**Comment by yhirose** [comment]
@ArnaudBienner, thanks for the feedback. Could you take a look at examples in `test/test.cc` using those methods? I don't have any problem to compile the file on both my iMac and GitHub Actions CI.

**Comment by ArnaudBienner** [comment]
`test/test.cc` looks different from the example: `NoContentLengthStreaming` https://github.com/yhirose/cpp-httplib/blob/master/test/test.cc#L3655

The lambda signature is `(size_t offset, DataSink &sink)` unlike the example, which is `(size_t offset, size_t length, DataSink &sink)`

**Comment by yhirose** [comment]
These 3 unit test cases use `ContentProvider`.
https://github.com/yhirose/cpp-httplib/blob/412ab5f0634a1e1db43ccff57c82797f9469497c/test/test.cc#L1560-L1599

**Comment by ArnaudBienner** [comment]
Thank you.
I saw those tests.

I've opened #1163 to fix the example. Hopefully that would be clearer.

Regarding the second part of my initial comment, forget about it: I realized that `Content-Length` value is adjusted automatically in case of byte-range requests, so it definitely looks like the library works as I would have expected, and there was simply just an small error in the example.

**Comment by yhirose** [comment]
@ArnaudBienner, I now understand what you reported. Yes, the README example isn't correct... Thanks for the pull request. I'll merge it soon.

**Comment by yhirose** [comment]
I just merged it. Thanks for your fine contribution!

**Comment by ArnaudBienner** [comment]
>  I now understand what you reported.

A patch is probably more explanatory than a long comment ;)

Thanks for taking the time to review my PR and merge it.

And thank you very much for this awesome library! :)
