### ISSUE TITLE
Is it really multithreaded?

### ISSUE THREAD

**Issue by smith111707** [yhirose/cpp-httplib#1164]
Hi
Is the lib really multithreaded and thread safe implemented?
It works just fine if I use it from a single thread.
However I get issues when trying to run it from 2 threads (1 http instance and 1 https instance) in parallel.
Any ideas, please?

**Comment by smith111707** [comment]
@yhirose , I really need a suggestion or work around for that. I don't like to switch to another library. I like this one. Good job.
But I need to do something with the issue. And it's pretty urgent for me. So could you help with that, please?

**Comment by yhirose** [comment]
@smith111707, as you can see the past issues, I tried to make this library thread-safe as much as possible, but there could be always bugs since we are all imperfect. :)

Unless you give me the smallest possible reproducible code and I can confirm the bug on my machine, then I can't do anything like debugging. So please provide more detailed information. Thanks!

**Comment by yhirose** [comment]
any response?

**Comment by 52617365** [comment]
> any response?

Hey, would you be willing to provide a link to an explanation or give me an explanation on how the default thread pool within the library works? My goal is to queue tasks to different threads, run them parallel and then re-use those threads after they have completed their task.

**Comment by PixlRainbow** [comment]
Are you using the client or the server? Note that the client does not use the thread pool at all. It is single threaded, and not intended to handle multiple concurrent requests. Only the server is multi threaded.

**Comment by yhirose** [comment]
Hope the following links help you.
https://github.com/yhirose/cpp-httplib#default-thread-pool-support
https://github.com/yhirose/cpp-httplib#override-the-default-thread-pool-with-yours

**Comment by smith111707** [comment]
> any response?

I've originally provided you with all details I had. I think you can easily recreate the issue with the info provided if you make a try.

**Comment by PixlRainbow** [comment]
> I've originally provided you with all details I had

You still haven't answered whether you are trying to use two servers, two clients, or other combinations when you say "1 http instance and 1 https instance"

**Comment by smith111707** [comment]
> You still haven't answered whether you are trying to use two servers, two clients, or other combinations when you say "1 http instance and 1 https instance"

You are right, sorry about that. I should had originally mentioned that it's all about clients - I have 2 clients.
