### ISSUE TITLE
SSL Update without restart

### ISSUE THREAD

**Issue by ozanselte** [yhirose/cpp-httplib#1165]
Hello,

I want to develop a new application with cpp-httplib library and I need regular updates of SSL certificate and key. How can I do this without restarting my application every time?

**Comment by PixlRainbow** [comment]
tear down the client or server object and re-construct it. This should force all data including SSL certs to be reloaded.

**Comment by yhirose** [comment]
Hope @PixlRainbow's comment helps you.
