### ISSUE TITLE
"opaque" is missing.

### ISSUE THREAD

**Issue by DennisHan** [yhirose/cpp-httplib#1166]
when processing digest authentication, you must respond to "opaque" field otherwise authorization fails.

i modified the code like this.

```
auto opaque = (auth.find("opaque") != auth.end()) ? auth.at("opaque"):"";

auto field =
        "Digest username=\"" + username + "\", realm=\"" + auth.at("realm") +
        "\", nonce=\"" + auth.at("nonce") + "\", uri=\"" + req.path +
        "\", algorithm=" + algo +                
        (qop.empty() ? ", response=\""
                     : ", qop=" + qop + ", nc=" + nc + ", cnonce=\"" +
                       cnonce + "\", response=\"") +
        response + "\"" + (opaque.empty() ? "":", opaque=\"" + opaque + "\"")
        ;
```

and i removed quotation marks for nc field.

thanks for great library.

**Comment by yhirose** [comment]
@DennisHan, thanks for the report! Could you send me a pull request including at leas one unit test in `test/test.cc`?

**Comment by DennisHan** [comment]
@yhirose well, I don't know if it's possible in the test.cc using httpbin.org. 
because The responds of a server has to contain an "opaque" field and when requested.

but, you can simply find out that a client must respond with the same value. 
plz refer to following doc. https://datatracker.ietf.org/doc/html/rfc2617

> opaque
     A string of data, specified by the server, which should be returned
     by the client unchanged in the Authorization header of subsequent
     requests with URIs in the same protection space. It is recommended
     that this string be base64 or hexadecimal data.

FYI, I found it while testing digest authentication with various ip cameras.
and without my edited code, always failed authentication.

**Comment by yhirose** [comment]
@DennisHan, I merged your suggestion. Thanks for the detailed information and fine contribution!
