### ISSUE TITLE
Can't link files to the project

### ISSUE THREAD

**Issue by Amazingkenneth** [yhirose/cpp-httplib#1167]
[NOTE from README](https://www.openssl.org/source/openssl-1.1.1m.tar.gz)
The compilation always terminates with the missing files error when `CPPHTTPLIB_OPENSSL_SUPPORT` is being defined.

Windows Powershell's Log
```
PS C:\Users\amazi\Desktop\Program> g++ a.cpp -o a -LC:\openssl\
In file included from a.cpp:2:
httplib.h:220:10: fatal error: openssl/err.h: No such file or directory
 #include <openssl/err.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
```
a.cpp , _extremely simple_
```
#define CPPHTTPLIB_OPENSSL_SUPPORT
#include "httplib.h"
using namespace std;
int main() {

  return 0;
}
```
C:\openssl is downloaded from [here](https://www.openssl.org/source/openssl-1.1.1m.tar.gz).

Likely, the problem is that `#include <openssl/err.h>` is quoted in angle brackets, so the compiler won't check files except for the environment's path(which places STL). I've tried to add -l or -L to solve this, but it didn't work.

**Comment by Amazingkenneth** [comment]
It didn't work either when I add `-llibssl -llibcrypto`

**Comment by yhirose** [comment]
@Amazingkenneth, I think you just downloaded the OpenSSL source package, instead of Windows binary package. Could you make sure that your 'include' and 'lib' directories really contain header files and Windows binaries respectively? Hope it helps!

**Comment by Amazingkenneth** [comment]
@yhirose 
However, when I downloaded the binary files from [here](https://slproweb.com/download/Win64OpenSSL_Light-1_1_1m.msi), and added opensslconf.h from [somebody's respository](https://github.com/rwinlib/openssl/blob/master/include/openssl/opensslconf.h), the compilation terminated with the following strange errors:
```
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail10ssl_deleteERSt5mutexP6ssl_stb[_ZN7httplib6detail10ssl_deleteERSt5mutexP6ssl_stb]+0x2a): undefined reference to `SSL_shutdown'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail10ssl_deleteERSt5mutexP6ssl_stb[_ZN7httplib6detail10ssl_deleteERSt5mutexP6ssl_stb]+0x46): undefined reference to `SSL_free'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail7SSLInitC1Ev[_ZN7httplib6detail7SSLInitC1Ev]+0x17): undefined reference to `OPENSSL_init_ssl'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail15SSLSocketStreamC1EyP6ssl_stxxxx[_ZN7httplib6detail15SSLSocketStreamC1EyP6ssl_stxxxx]+0x99): undefined reference to `SSL_ctrl'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail15SSLSocketStream4readEPcy[_ZN7httplib6detail15SSLSocketStream4readEPcy]+0x20): undefined reference to `SSL_pending'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail15SSLSocketStream4readEPcy[_ZN7httplib6detail15SSLSocketStream4readEPcy]+0x46): undefined reference to `SSL_read'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail15SSLSocketStream4readEPcy[_ZN7httplib6detail15SSLSocketStream4readEPcy]+0x86): undefined reference to `SSL_read'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail15SSLSocketStream4readEPcy[_ZN7httplib6detail15SSLSocketStream4readEPcy]+0xa6): undefined reference to `SSL_get_error'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail15SSLSocketStream4readEPcy[_ZN7httplib6detail15SSLSocketStream4readEPcy]+0xfa): undefined reference to `SSL_pending'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail15SSLSocketStream4readEPcy[_ZN7httplib6detail15SSLSocketStream4readEPcy]+0x120): undefined reference to `SSL_read'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail15SSLSocketStream4readEPcy[_ZN7httplib6detail15SSLSocketStream4readEPcy]+0x17f): undefined reference to `SSL_read'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail15SSLSocketStream4readEPcy[_ZN7httplib6detail15SSLSocketStream4readEPcy]+0x1a2): undefined reference to `SSL_get_error'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail15SSLSocketStream5writeEPKcy[_ZN7httplib6detail15SSLSocketStream5writeEPKcy]+0x49): undefined reference to `SSL_write'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail15SSLSocketStream5writeEPKcy[_ZN7httplib6detail15SSLSocketStream5writeEPKcy]+0x69): undefined reference to `SSL_get_error'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail15SSLSocketStream5writeEPKcy[_ZN7httplib6detail15SSLSocketStream5writeEPKcy]+0x105): undefined reference to `SSL_write'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail15SSLSocketStream5writeEPKcy[_ZN7httplib6detail15SSLSocketStream5writeEPKcy]+0x128): undefined reference to `SSL_get_error'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib9SSLServerD1Ev[_ZN7httplib9SSLServerD1Ev]+0x39): undefined reference to `SSL_CTX_free'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib9SSLClientD1Ev[_ZN7httplib9SSLClientD1Ev]+0x39): undefined reference to `SSL_CTX_free'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail33ssl_connect_or_accept_nonblockingIPFiP6ssl_stEEEbyS3_T_xx[_ZN7httplib6detail33ssl_connect_or_accept_nonblockingIPFiP6ssl_stEEEbyS3_T_xx]+0x45): undefined reference to `SSL_get_error'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail7ssl_newIZNS_9SSLServer24process_and_close_socketEyEUlP6ssl_stE_ZNS2_24process_and_close_socketEyEUlS4_E0_EES4_yP10ssl_ctx_stRSt5mutexT_T0_[_ZN7httplib6detail7ssl_newIZNS_9SSLServer24process_and_close_socketEyEUlP6ssl_stE_ZNS2_24process_and_close_socketEyEUlS4_E0_EES4_yP10ssl_ctx_stRSt5mutexT_T0_]+0x4c): undefined reference to `SSL_new'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail7ssl_newIZNS_9SSLServer24process_and_close_socketEyEUlP6ssl_stE_ZNS2_24process_and_close_socketEyEUlS4_E0_EES4_yP10ssl_ctx_stRSt5mutexT_T0_[_ZN7httplib6detail7ssl_newIZNS_9SSLServer24process_and_close_socketEyEUlP6ssl_stE_ZNS2_24process_and_close_socketEyEUlS4_E0_EES4_yP10ssl_ctx_stRSt5mutexT_T0_]+0x85): undefined reference to `BIO_new_socket'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail7ssl_newIZNS_9SSLServer24process_and_close_socketEyEUlP6ssl_stE_ZNS2_24process_and_close_socketEyEUlS4_E0_EES4_yP10ssl_ctx_stRSt5mutexT_T0_[_ZN7httplib6detail7ssl_newIZNS_9SSLServer24process_and_close_socketEyEUlP6ssl_stE_ZNS2_24process_and_close_socketEyEUlS4_E0_EES4_yP10ssl_ctx_stRSt5mutexT_T0_]+0xa6): undefined reference to `BIO_ctrl'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail7ssl_newIZNS_9SSLServer24process_and_close_socketEyEUlP6ssl_stE_ZNS2_24process_and_close_socketEyEUlS4_E0_EES4_yP10ssl_ctx_stRSt5mutexT_T0_[_ZN7httplib6detail7ssl_newIZNS_9SSLServer24process_and_close_socketEyEUlP6ssl_stE_ZNS2_24process_and_close_socketEyEUlS4_E0_EES4_yP10ssl_ctx_stRSt5mutexT_T0_]+0xbd): undefined reference to `SSL_set_bio'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail7ssl_newIZNS_9SSLServer24process_and_close_socketEyEUlP6ssl_stE_ZNS2_24process_and_close_socketEyEUlS4_E0_EES4_yP10ssl_ctx_stRSt5mutexT_T0_[_ZN7httplib6detail7ssl_newIZNS_9SSLServer24process_and_close_socketEyEUlP6ssl_stE_ZNS2_24process_and_close_socketEyEUlS4_E0_EES4_yP10ssl_ctx_stRSt5mutexT_T0_]+0x107): undefined reference to `SSL_shutdown'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail7ssl_newIZNS_9SSLServer24process_and_close_socketEyEUlP6ssl_stE_ZNS2_24process_and_close_socketEyEUlS4_E0_EES4_yP10ssl_ctx_stRSt5mutexT_T0_[_ZN7httplib6detail7ssl_newIZNS_9SSLServer24process_and_close_socketEyEUlP6ssl_stE_ZNS2_24process_and_close_socketEyEUlS4_E0_EES4_yP10ssl_ctx_stRSt5mutexT_T0_]+0x123): undefined reference to `SSL_free'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.text$_ZN7httplib6detail7ssl_newIZNS_9SSLServer24process_and_close_socketEyEUlP6ssl_stE_ZNS2_24process_and_close_socketEyEUlS4_E0_EES4_yP10ssl_ctx_stRSt5mutexT_T0_[_ZN7httplib6detail7ssl_newIZNS_9SSLServer24process_and_close_socketEyEUlP6ssl_stE_ZNS2_24process_and_close_socketEyEUlS4_E0_EES4_yP10ssl_ctx_stRSt5mutexT_T0_]+0x161): undefined reference to `BIO_ctrl'
C:\Users\amazi\AppData\Local\Temp\ccwndiyb.o:a.cpp:(.rdata$.refptr.SSL_accept[.refptr.SSL_accept]+0x0): undefined reference to `SSL_accept'
collect2.exe: error: ld returned 1 exit status`
```
How can I solve it? By adding files? Thanks for helping.

**Comment by PixlRainbow** [comment]
Windows does not follow standard methods of installing system global libraries, so the linker must specify exact filenames to binaries or paths to header include directories.
Note that the header directory you must reference is NOT the whole openssl project folder. It is the "/include" folder inside the openssl project folder.
Also note that the binaries you have downloaded are for a different minor version (1.1.1k vs 1.1.1m) though they may still be compatible as they are within the same major version.

The original copy of the openssl source code you downloaded comes with an automatic compilation script to build an openssl binary, so you also had the option of building your own openssl binary if you wanted to.

**Comment by Amazingkenneth** [comment]
Thanks a lot. I've solved the problem.

But I still have some questions about the openssl library. 
Seems every header in `./include/openssl` can be found in the whole openssl project folder, so does dragging the whole folder to the compiler's directory directly have the same effect as making a copy of `./include/openssl` to it? What is the purpose of having nested folders the same name?

It didn't work when I add the `OpenSSL-Win64\bin` to the environment variables, instead, as I copied the `libcrypto-1_1-x64.dll` and `libssl-1_1-x64.dll` to `C:\Windows\System32`, the runtime-error of "`dll`s not found" disappeared. 

Doesn't the program look up the value in the environment variable?

**Comment by PixlRainbow** [comment]
Unfortunately, Windows linkers do not check PATH environment variables for system global binaries. The only valid location for global binaries is System32, but that is not a recommended place to install third-party binaries to. In fact, Microsoft recommends that nobody uses global binaries at all unless they are using a feature built into Microsoft Windows.

This makes management of dependencies much more difficult on Windows than on POSIX/Unix-like systems unless a third-party package manager like vcpkg, nuget or chocolatey is used. Even if a third-party package manager is used, you will still be forced to either manually reference the package manager directory, or use another program like cmake or make to generate scripts that reference the directory.

**Comment by PixlRainbow** [comment]
> Seems every header in ./include/openssl can be found in the whole openssl project folder

This doesn't seem correct. I am looking at the folder, and I do not see duplicate copies. The files in the /include folder are headers, which are files that provide the function signatures but do not define their actual bodies. The files in the rest of the project are C source files, which provide the code implementation for the functions.

**Comment by Amazingkenneth** [comment]
I mean, C headers (.H file) in `./include/openssl` is seemingly duplicate to the 106 .H files in the whole openssl project folder. They both provide the same signatures.

**Comment by Amazingkenneth** [comment]
Besides, thanks for your answer. @PixlRainbow

**Comment by PixlRainbow** [comment]
The way C and C++ work is that you must still define the function signatures even if you intend to use a pre compiled binary. But using the C source files directly when you already link a binary will cause the function bodies to be compiled unnecessarily. The binary already includes the bodies.
