### ISSUE TITLE
POSTing Large Text Data Fails

### ISSUE THREAD

**Issue by zeyad-mansour** [yhirose/cpp-httplib#1169]
Is there any documentation on under what circumstances the `Error::Write` error gets returned?

I am trying to post large textual data (approx. 1 MB), however, the result is a "Write" error every time.

I do not encounter this error with smaller sized texts.
```
auto res = cli.Post("/portal/upload", text, "text/plain");

if (res.httplib::Result::error() == httplib::Error::Success) {
    cout << res->body << endl;
}
else {
    cout << res.error() << endl;
}
```

**Comment by yhirose** [comment]
@zeyad-mansour, thank you for the report. I added a unit test to post (posting 100MB text), and the unit test successfully passed. Could you try 'cd test; make', to see what happens on your machine?

As for 'Error::Write', it can happen with  various reasons. If you grep 'Error::Write' in httplib.h, you will see where the error is set.

**Comment by yhirose** [comment]
any response?

**Comment by yhirose** [comment]
I close it for now until I receive more information.

**Comment by zeyad-mansour** [comment]
> I close it for now until I receive more information.

Sorry about the lateness.

 I resolved the issue. It seems that the issue stemmed from the way that I was using OpenSSL 3.0 while not properly addressing the depreciation errors (`#pragma warning(disable : 4996)`). Now, I properly updated the inline functions that were depreciated.

I didn't look into why this error was happening, so I'm still not sure why exclusively posting large text was failing.
