### ISSUE TITLE
read_headers regex not working

### ISSUE THREAD

**Issue by tkozybski** [yhirose/cpp-httplib#117]
Hello.
I'm attaching screenshoot of the problem. The read_headers function fails to match the regex. I've added some printfs for clarification. Suprisingly it works if i move the regex outside of the function like in the second screenshot.

https://i.imgur.com/c6mXv7A.png
https://i.imgur.com/sVzCWIA.png

Compiler is MSVC 15.9.4.

**Comment by yhirose** [comment]
@tkozybski, thanks for the information. It's really interesting.

It seems like a compiler bug in VC 15.9.4. Do you think if the compiler error is caused due to the reason described in the stackoverflow post?
https://stackoverflow.com/questions/53823991/c-lambda-as-static-member-in-crtp-class-fails-to-compile-in-visual-studio-15

**Comment by tkozybski** [comment]
It may be related but the example code from stackoverflow won't compile while this regex compiles, but doesn't work. The latter is even worse because it wasn't obvious to catch.

**Comment by yhirose** [comment]
@tkozybski, I have just updated VC to 15.9.4. But I am able to build without any compile error, and all unit tests passed. (I tried with all the combinations of 'Relelase/Debug' and 'Win32/x64'.

The following shows some of my compiler settings:

 * `General/Platform Toolset`: `Visual Studio 2017 (v141)`
 * `C/C++/Language`: (Nothing)

Please let me know whatever things that you think cause the build error. Thanks!

**Comment by tkozybski** [comment]
i'm using /std:c++latest. I'll probably investigate this further after holidays

**Comment by yhirose** [comment]
Please let me know if you still experience the build problem.
