### ISSUE TITLE
Add checking robots.txt to the features

### ISSUE THREAD

**Issue by Amazingkenneth** [yhirose/cpp-httplib#1170]
I am working on a crawler project right now, and it may be necessary to check the website's robots.txt before crawling to it.

Can you add a check for the robots.txt if the URL has been written with "Disallow"? If the URL is forbidden, warnings will occur.

**Comment by PixlRainbow** [comment]
Note that cpp-httplib is only intended to handle the HTTP/HTTPS spec. Some extensions beyond that may be reasonable, but any features that are too specific to a particular use case/application (e.g. building a web crawler) are not our responsibility and should be built on top of the library by a downstream developer.

If you want to read and parse the content of robots.txt, you can just use httplib to make a normal Get request to `/robots.txt` of the website. Then either implement text parsing yourself with standard C++ utilities, or pass the retrieved content string to [google's robotstxt parser library](https://github.com/google/robotstxt)
[Example](https://github.com/google/robotstxt/blob/02bc6cdfa32db50d42563180c42aeb47042b4f0c/robots_main.cc#L95-L98)

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the helpful information.
@Amazingkenneth, hope the @PixlRainbow's comment helps.

**Comment by Amazingkenneth** [comment]
Thanks for the helpful information and the awesome library.
