### ISSUE TITLE
Client struggling to send request when server closes connection

### ISSUE THREAD

**Issue by Rockybilly** [yhirose/cpp-httplib#1179]
In my use case, some client objects may not receive a request directive for some time. By my observation, it seems like this causes the target server to close the connection (client->set_connection_timeout is high enough). This makes my Post requests to fail with Write error. And the next time the client tries to Post, it succeeds, and then fails again.

It happens like this

Client:

Post (OK) -> Post (Error:Write) -> Post (OK) -> Post (Error:Write)

There are varying time intervals with these requests, but it seems like, when the request fails, it manages to reopen the connection, but doesn't use it, and return an error. Next time, it uses the opened connection, after that server closes the connection again.

Shouldn't the client be able to reopen the connection before sending a request, instead of returning an error ? Or is there a way to make this happen ?

**Comment by yhirose** [comment]
@Rockybilly, thank you for the report. Could you explain more about the following statement?

> In my use case, some client objects may not receive a request directive for some time. By my observation, it seems like this causes the target server to close the connection (client->set_connection_timeout is high enough).

**Comment by Rockybilly** [comment]
Hey, first of all, let me answer your question. To allow parallel requests, I create multiple Client instances, and distribute them to different threads using a queue (e.g. Free List). It's a really simple structure, I know there are no issue here. I might even humbly suggest you to implement a similar class to this project also. Really helps with the bottleneck of a single client when many threads share the same one.

Second, I looked around a little, It seems the issue I was talking about, was the issue you resolved some time ago (is_socket_alive). What's interesting is, in my case, it resolved the issue %95 of the time, but sometimes it still gets an error similar to before, but this time, it is Error::Read instead of Error::Write (it makes sense, given the is_socket_alive fix you applied).

It's hard for me to recreate the issue in a basic code, but I can try if you want to.

**Comment by yhirose** [comment]
@Rockybilly, thanks for the detailed information. It's a more complex situation that I thought. :)
Is it possible to make the smallest possible code to reproduce it easily, so that I could try to debug it on my machine? That helps me a lot. Thanks!

**Comment by Rockybilly** [comment]
I couldn't recreate the behavior using httplib::Server, probably the server I am sending requests to is nginx or apache (Probably handling the sockets differently). Unfortunately, the server I am experiencing this issue is not a public IP. The only thing I can say is the request fails with Error::Read (in the latest version). Sorry I couldn't supply more information.

**Comment by yhirose** [comment]
@Rockybilly, does it means that the problem resides on the other end such as nginx or apache, rather than httplib::Client? In any case, I can't do anything for this issue unless I am able to reproduce it on my machine. Thank you for your understanding.
