### ISSUE TITLE
example crash on gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 

### ISSUE THREAD

**Issue by SillyFlame** [yhirose/cpp-httplib#118]
crash when run with demo.

**Comment by yhirose** [comment]
@SillyFlame, thanks for the report. Could you give me more detailed information to fix the problem?

 * Which demo caused the crash?
 * What does 'Ubuntu 4.8.4-2ubuntu1~14.04.3' mean?
 * Is there any other helpful information such as the call stack dump?

Thanks for your help.

**Comment by SillyFlame** [comment]
System info:
 Ubuntu 14.04.5 LTS \n \l

Gcc info:
 Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
......
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)

Step:
1. modify clang++ to g++, c++14 flag to c++11
2. compile example
3.  ./hello
4. visit 127.0.0.1:8080/hi in chromium
5. core with info: 
  terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)
[example.zip](https://github.com/yhirose/cpp-httplib/files/2734896/example.zip)

more informatin in attachs.

**Comment by SillyFlame** [comment]
[example.zip](https://github.com/yhirose/cpp-httplib/files/2734907/example.zip)

**Comment by yhirose** [comment]
@SillyFlame, thanks so much for the information! I'll prepared the OS environment on VirtualBox and reproduce the problem sometime this week.

**Comment by yhirose** [comment]
@SillyFlame, I setup Ubuntu 14.04.5, and reproduced this problem successfully. After I spent sometime to look into the problem, I found the following stackoverflow post.

https://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions

According to the answer, <regex> is broken before gcc 4.9.0 So it seems there is nothing to do on my side because cpp-httb heavily depends on <regex> for routing. Is it possible for you to switch to gcc 4.9 or later?

Sorry about that...

**Comment by SillyFlame** [comment]
> @SillyFlame, I setup Ubuntu 14.04.5, and reproduced this problem successfully. But after I spent sometime to look into the problem, I found the following stackoverflow post.
> 
> https://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions
> 
> According to the answer, `regex` is broken before gcc 4.9.0 So it seems there is nothing to do on my side because cpp-httb heavily depends on `regex` for routing. Is it possible for you to switch to gcc 4.9 or later?
> 
> Sorry about that...

Thanks a lot.
I will try updating my gcc.

**Comment by yhirose** [comment]
@SillyFlame, you may want to consider [Crow C++ micro web framework](https://github.com/ipkn/crow). It suports g++4.8 and is a header-only library as well.
