### ISSUE TITLE
Bad performance  when using post

### ISSUE THREAD

**Issue by huangyinghui01** [yhirose/cpp-httplib#1180]
recently I use cpp-httplib with SSL support,  send a post  to a remote server and get response, it takes 30ms ;
while python do the same work  only takes 15ms ;
finally I locate the problem is the pos functon, it takes 26ms ;
inline Result ClientImpl::Post(const char *path, const Headers &headers, const std::string &body, const char *content_type)

**Comment by yhirose** [comment]
@huangyinghui01, thanks for the report. Could you explain more about it for debugging?

**Comment by huangyinghui01** [comment]
simplified case code:
-----------------------

std::shared_ptr<httplib::SSLClient> m_sslClient;
...
std::string strBody = "symbol=BTCUSDT&side=BUY&positionSide=BOTH&type=LIMIT&quantity=0.001";
httplib::Headers headers;
headers.insert(std::make_pair("X-MBX-APIKEY", "21548s5f25daergre52s4r"));

//send an order
m_logger->info("UserAPI_Impl::http_proc, before Post");
httplib::Result res = m_sslClient->Post(exchange_url, headers, strBody, "application/x-www-form-urlencoded");
m_logger->info("UserAPI_Impl::http_proc, after Post");


output log in us:
---------------------
2022-01-28 17:57:59.794751|220827||info: UserAPI_Impl::http_proc, before Post
2022-01-28 17:57:59.821544|220827||info: UserAPI_Impl::http_proc, after Post

Post() costs = 821544 - 794751 = 26793(us)

as shown above, the Post latency is around 26ms, while on the same machine, 
my partener use python do the same work, takes around 15ms in average


line 6604 in httplib.h:
--------------------------

inline Result ClientImpl::Post(const char *path, const Headers &headers,
                               const std::string &body,
                               const char *content_type) {
  return send_with_content_provider("POST", path, headers, body.data(),
                                    body.size(), nullptr, nullptr,
                                    content_type);
}

**Comment by huangyinghui01** [comment]
running env is :  centos 8.4 with gcc 10.2

**Comment by yhirose** [comment]
@huangyinghui01, thanks for the info. Could you also profile your project to identify which exact line causes the performance issue in httplib.h on your machine? It helps me very much for debugging. Thanks a lot!

**Comment by huangyinghui01** [comment]
@yhirose I profile my program, and found out two lines that caused big latency:
1. initialize_ssl(),  it was called every time I send a  http Post ,  it takes  ~6ms
2. process_socket(), this function spent most of the time, it takes ~15ms

code:
inline bool ClientImpl::send(Request &req, Response &res, Error &error) 
{
  ...
  if (!scli.initialize_ssl(socket_, error)) { return false; }  // ==> initialize_ssl() takes ~15ms in first call, and takes ~6ms  subsequent
  ... 
  auto close_connection = !keep_alive_;
  auto ret = process_socket(socket_, [&](Stream &strm) {  // ==>  takes  ~15ms
      return handle_request(strm, req, res, close_connection, error);});  
}

**Comment by huangyinghui01** [comment]
Is it possible to call initialize_ssl only once ?

**Comment by yhirose** [comment]
Thank you for the helpful information. As you can see below, `initialize_ssl` won't be called again as long as the socket connection is alive.

![image](https://user-images.githubusercontent.com/357397/151665228-0c3943d6-f48e-4251-92f4-3b79764dfb2f.png)

So in the following example, only the first `cli.Post` will call `initialize_ssl`.

```cpp
Client cli("https://...");
cli.Post("...");  // initialize_ssl gets called
cli.Post("...");
cli.Post("...");
```

What does your code look like?

**Comment by huangyinghui01** [comment]
in my case,  the Post is called according to market status,
SSLClient cli("https://...");
cli.Post();
wait a few seconds or minutes
cli.Post();

**Comment by huangyinghui01** [comment]
I just do a test:

**Comment by huangyinghui01** [comment]
I sent two orders continuously:
Post();
Post();

output log:
initialize_ssl : 5803 us
Post total: 27368 us
initialize_ssl : 5776 us
Post total: 25395 us

as shown above, it seems that isalive does not work,  initialize_ssl  still takes 5776 us

**Comment by huangyinghui01** [comment]
in fcuntion: initialize_ssl() ,  select_read() is called,  which takes ~4000us

**Comment by yhirose** [comment]
@huangyinghui01, thank you for the detailed info! I'll try to reproduce it on my machine when I have time.

**Comment by yhirose** [comment]
@huangyinghui01, I tried to measure the performance on my machine (M1 MacBook Pro) with the following code though, I don't see any performance problem... The very first call took about 5ms, but rest of them are under 1ms except a few calls... Could you run the following code on your machine to see if any difference? Thanks!

```cpp
#include <chrono>
#include <httplib.h>
using namespace httplib;
using namespace std;
using namespace chrono;

void post_message(Client &cli) {
  auto before = steady_clock::now();
  auto res = cli.Post("/echo", "message", "text/plain");
  auto after = steady_clock::now();
  auto usec = duration_cast<microseconds>(after - before);
  cout << usec.count() << " us" << endl;
}

int main(void) {
  Server svr;

  svr.Post("/echo", [](const Request &req, Response &res) {
    res.set_content(req.body, "text/plain");
  });

  auto t = thread([&]() { svr.listen("localhost", 8080); });
  this_thread::sleep_for(milliseconds(1));

  for (size_t i = 0; i < 3; i++) {
    std::cout << "*** " << i << " ***" << std::endl;
    Client cli("localhost", 8080);
    for (size_t j = 0; j < 10; j++) {
      post_message(cli);
    }
  }

  svr.stop();
  t.join();
}
```

```
> make 1180 && ./1180
c++ -o 1180 -g -std=c++11 -I.. -Wall -Wextra -pthread 1180.cc -DCPPHTTPLIB_OPENSSL_SUPPORT -I/opt/homebrew/opt/openssl@1.1/include -L/opt/homebrew/opt/openssl@1.1/lib -lssl -lcrypto -DCPPHTTPLIB_ZLIB_SUPPORT -lz -DCPPHTTPLIB_BROTLI_SUPPORT -I/opt/homebrew/opt/brotli/include -L/opt/homebrew/opt/brotli/lib -lbrotlicommon -lbrotlienc -lbrotlidec
*** 0 ***
5490 us
910 us
590 us
573 us
553 us
663 us
638 us
532 us
489 us
470 us
*** 1 ***
469 us
465 us
542 us
614 us
598 us
603 us
672 us
663 us
3430 us
1357 us
*** 2 ***
558 us
862 us
535 us
707 us
719 us
1130 us
588 us
639 us
625 us
573 us
```

**Comment by yhirose** [comment]
@huangyinghui01, I tried to reproduce the performance problem, but I couldn't so far. Here is my benchmark code. As you can see my result, I don't find any performance problem. The very first POST call took 4ms and rest of them only took less than 1ms. Could you run this example on your machine? Thanks!

```cpp
// 1180.cc
#include <chrono>
#include <httplib.h>
using namespace httplib;
using namespace std;
using namespace chrono;

#define SERVER_CERT_FILE "./cert.pem"
#define SERVER_PRIVATE_KEY_FILE "./key.pem"

void post_message(Client &cli) {
  auto before = steady_clock::now();
  auto res = cli.Post("/echo", "message", "text/plain");
  auto after = steady_clock::now();
  auto usec = duration_cast<microseconds>(after - before);
  cout << usec.count() << " us" << endl;
}

int main(void) {
  SSLServer svr(SERVER_CERT_FILE, SERVER_PRIVATE_KEY_FILE);

  svr.Post("/echo", [](const Request &req, Response &res) {
    res.set_content(req.body, "text/plain");
  });

  auto t = thread([&]() { svr.listen("localhost", 8080); });
  this_thread::sleep_for(milliseconds(1));

  for (size_t i = 0; i < 3; i++) {
    std::cout << "*** " << i << " ***" << std::endl;
    Client cli("localhost", 8080);
    for (size_t j = 0; j < 10; j++) {
      post_message(cli);
    }
  }

  svr.stop();
  t.join();
}
```

```
[master] ~/cpp-httplib/example$ make 1180 && ./1180
c++ -o 1180 -g -std=c++11 -I.. -Wall -Wextra -pthread 1180.cc -DCPPHTTPLIB_OPENSSL_SUPPORT -I/opt/homebrew/opt/openssl@1.1/include -L/opt/homebrew/opt/openssl@1.1/lib -lssl -lcrypto -DCPPHTTPLIB_ZLIB_SUPPORT -lz -DCPPHTTPLIB_BROTLI_SUPPORT -I/opt/homebrew/opt/brotli/include -L/opt/homebrew/opt/brotli/lib -lbrotlicommon -lbrotlienc -lbrotlidec
*** 0 ***
4207 us
565 us
431 us
477 us
823 us
576 us
559 us
551 us
*** 1 ***
670 us
364 us
303 us
410 us
361 us
363 us
306 us
324 us
*** 2 ***
284 us
375 us
300 us
453 us
428 us
394 us
356 us
408 us
```

**Comment by yhirose** [comment]
I'll close it for now until I receive more evidence.
