### ISSUE TITLE
Signal Handling

### ISSUE THREAD

**Issue by ozanselte** [yhirose/cpp-httplib#1188]
Hello, I want to close my program without any issues but when SIGINT(CTRL+C) occurs, it fails because of accept. How can I solve this without adding a signal handler?

![image](https://user-images.githubusercontent.com/4232230/152808984-e6d6c9ea-aeec-46ce-829f-c824637d8901.png)

**Comment by yhirose** [comment]
cpp-httplib itself doesn't do anything for SIGINT, since it's totally an application's decision regarding how to handle the received signal. I usually provide a signal handler. Sorry that I can't directly answer your question.

**Comment by PixlRainbow** [comment]
Those are not errors. GDB is simply warning that you do not have the source files for posix socket api installed so it will not be able to debug beyond that point
