### ISSUE TITLE
How Can I import these *Header* files in Visual Studio?

### ISSUE THREAD

**Issue by josephlee518** [yhirose/cpp-httplib#119]
I've Used G++ to Compile it on Linux (Ubuntu)

But when I compile on windows, I have some errors related about `linker`

How can I fix it?

**Comment by yhirose** [comment]
@josephlee518, thanks for the report.

Could you open `example/example.sh` with your Visual Studio and try to build? It will tell you what you need to do. (This solution/project files are for Visual Studio 2015, but Visual Studio 2017 can also accept them.)

Hope it helps.

**Comment by josephlee518** [comment]
![https://i.gifer.com/NGO.gif]

Thank You for help.

- You gave me a hint on `example.sln`, So I've Look Very Closely (like kissing with monitor)

- And I've got a hints and Fixed it. AND **COMPILED VERY SMOOTHLY!** 

1. <AdditionalIncludeDirectories>..</AdditionalIncludeDirectories> -> The Two Dots are Included.

2. And `Ws2_32.lib` Library file located in <AdditionalDependencies>Ws2_32.lib;%(AdditionalDependencies)</AdditionalDependencies> -> So I've Fixed It.

Thank You and Happy New Year!
