### ISSUE TITLE
Initial receive buffer size always 4096 bytes

### ISSUE THREAD

**Issue by mqnc** [yhirose/cpp-httplib#1191]
https://github.com/yhirose/cpp-httplib/blob/bb00a23116f5c9f64f1e257ecf5b97a49d0be44e/httplib.h#L2410
Should this not be
`static const size_t read_buff_size_ = CPPHTTPLIB_RECV_BUFSIZ;`
?

**Comment by yhirose** [comment]
@mqnc, thanks for the feedback. `CPPHTTPLIB_RECV_BUFSIZ` is used for HTTP level buffer. `read_buff_size_` is used for lower level socket stream. We can introduce another define symbol like `CPPHTTPLIB_SOCKET_STREAM_BUFSIZ`. I'll ponder over it. Thanks!

**Comment by mqnc** [comment]
I was using the chunked transfer and I noticed that no matter how high I set `CPPHTTPLIB_RECV_BUFSIZ`, the first chunk I read is always 4090 bytes. And I traced it back to this number.

**Comment by mqnc** [comment]
```cpp
#include <iostream>
#include <string>
#define CPPHTTPLIB_RECV_BUFSIZ size_t(10000)
#include <httplib.h>

using namespace std;
using namespace httplib;

void serve() {
	httplib::Server svr;

	string data(20000, '.');

	svr.Get("/chunked", [&](const Request& req, Response& res) {
		res.set_chunked_content_provider(
			"text/plain",
			[&data](size_t offset, DataSink& sink) {
				std::cout << "sent " << data.size() << " bytes\n";
				sink.write(data.c_str(), data.size());
				sink.done();
				return true;
			}
		);
		});

	svr.listen("0.0.0.0", 8080);
}

void request() {
	httplib::Client cli("localhost", 8080);

	auto res = cli.Get("/chunked",
		[&](const char* data, size_t data_length) {
			std::cout << "received " << data_length << " bytes\n";
			return true;
		});
}

int main() {
	std::thread server(serve);
	request();
	server.join();
	return 0;
}
```

produces

```
sent 20000 bytes
received 4090 bytes
received 10000 bytes
received 5910 bytes
```

**Comment by yhirose** [comment]
@mqnc, thanks for the report!

**Comment by yhirose** [comment]
@mqnc, after I carefully consider this situation, I concluded that it's not a bug.

> I was using the chunked transfer and I noticed that no matter how high I set CPPHTTPLIB_RECV_BUFSIZ, the first chunk I read is always 4090 bytes. And I traced it back to this define.

According to the MDN documentation (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding#chunked_encoding), **a chunk** doesn't mean a meaningful unit for a recipient.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/357397/157169440-153f5aa8-0323-43cc-a929-7d0d86f2a5b7.png">

Chunks are supposed to be concatenated to form a message body. So basically, we have to do as below:

```cpp
std::string body;
auto res = cli.Get("/chunked",
[&](const char* data, size_t data_length) {
    body.append(data, data_length);
    return true;
  });
```
