### ISSUE TITLE
Request body being cut off

### ISSUE THREAD

**Issue by adamaa5** [yhirose/cpp-httplib#1193]
Hello,

I have a PUT method with a content receiver using the following code:
`std::string request_body;

    content_reader([&](const char *data, size_t data_length) {
        request_body.append(data);
        return true;
    });

// parse json from request_body`

However, the request body keeps getting cut off. (Content length is specified correctly too - not as chunks or -1)

I have checked whether the error is on the request-making end by writing a quick http server in go to replicate the PUT request and all the content gets read so, the problem lies with my code above.

Is this a bug with the httplib library or am I not reading properly?

Thanks!

**Comment by yhirose** [comment]
Here is a unit test showing a correct way to use the content reader. Your codes is not using `data_length`.
Could you also run the unit test on your machine with `cd test; make`, so that you can tell if the bug is from httplib or not?

https://github.com/yhirose/cpp-httplib/blob/bb00a23116f5c9f64f1e257ecf5b97a49d0be44e/test/test.cc#L1787-L1797

**Comment by WarShoe** [comment]
I don't know is it related or not, but I cannot get back "application/json" or "text/plain"  with Server.Post() call. The http response body (seen in a browser) is always null. In the code fragment below Get() works, but Post() does not.

```    
svr.Get("/get", [](const Request & req, Response &res) {
        res.set_content("{\"a\":1,\"b\":\"c\"}", "application/json");
        res.set_header("Access-Control-Allow-Origin","*");
    });

svr.Post("/post", [](const Request & req, Response &res) {
        res.set_content("{\"a\":1,\"b\":\"c\"}", "application/json");
    });
```

Post() response in browser:
```
Response { type: "opaque", url: "", redirected: false, status: 0, ok: false, statusText: "", headers: Headers, body: null, bodyUsed: false }
```

**Comment by yhirose** [comment]
Could you just run the unit tests with `cd test; make` to verify your environment is correct? Then, could you submit another issue with more detailed information? Thanks a lot!

**Comment by PixlRainbow** [comment]
> ```Response { type: "opaque", url: "", redirected: false, status: 0, ok: false, statusText: "", headers: Headers, body: null, bodyUsed: false }```

Hi, it appears you are attempting to make a cross-origin ajax request. For security reasons, web browsers will block access to the response of a server with a different port or domain from the current page by default. In order to disable this behavior, the browser must see "cors headers" in the server response and the request must be made with cors mode enabled

**Comment by WarShoe** [comment]
OK, Thank you! I got it working!

Apparently, if:
- In the javascript fetch request I set header 'Content-Type': 'application/json'
OR
- I don't set header 'Access-Control-Allow-Origin:*' in the server response

the client-server communication will not work (I cannot exchange JSON data between client<==>server )

The following setup works for me now. 
Javascript:
```
    async function send () {
        const request = {
            method: 'post',
            body: JSON.stringify({
                name: 'myName',
                password: 'myPassword'
            })
        };
        const res = await fetch('http://localhost:8080/hi',request);
        const data = await res.json();
        console.log('data:',data);
    }
```
C++
```
    Server svr;
    svr.Post("/hi", [&](const Request &req, Response &res) {
        res.set_content("{\"a\":1,\"b\":\"c\"}", "application/json");
        res.set_header("Access-Control-Allow-Origin","*");
    });
```
