### ISSUE TITLE
device or resource busy

### ISSUE THREAD

**Issue by peguine** [yhirose/cpp-httplib#1195]
```
std::shared_ptr<httplib::Client> web_cli_;
web_cli_.reset(new Client("https://"+ uri.getHost() + ":" + to_string(uri.getPort())));
auto res = web_cli_->Post(path.c_str(),reqheaders,body,"application/x-www-form-urlencoded");
```
Exception at Post:
device or resource busy
why?

**Comment by PixlRainbow** [comment]
that is an operating system message that indicates that your system is temporarily unable to create network connections. It may be due to multiple possible reasons including domain resolution misconfigured, network driver problem or too many network connections, or other reasons.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the answer.
@peguine, hope @PixlRainbow's comment helps.
