### ISSUE TITLE
Add new interfaces for const std::string& path

### ISSUE THREAD

**Issue by ylz-at** [yhirose/cpp-httplib#1196]
Current Http Methods exposed are using const char* path, and `Client to the lib` have to use `path.c_str()` before invoking.

```
Result Client::Get(const char *path) { return cli_->Get(path); }
```

New interfaces such as,
```
Result Client::Get(const std::string &path) { return cli_->Get(path); }
```

or even std::string_view for C17,
```
Result Client::Get(std::string_view path) { return cli_->Get(path); }
```

should be added.

**Comment by yhirose** [comment]
@ylz-at, thank you for your suggestion! I may think about it in the future.
