### ISSUE TITLE
content reciever and content provider consistency check

### ISSUE THREAD

**Issue by HandleTlsData** [yhirose/cpp-httplib#1197]
is there any way we can communicate between server content provider and client content reciever for adding extra consistency check?
like to do hashing of chunk or something like this

**Comment by yhirose** [comment]
@HandleTlsData, you could do it with sending a checksum. This technique has nothing to do with cpp-httplib or HTTP though. Hope it helps.
https://en.wikipedia.org/wiki/Checksum
