### ISSUE TITLE
Flaky tests on multiple architectures

### ISSUE THREAD

**Issue by Tachi107** [yhirose/cpp-httplib#1199]
The `ClientProblemDetectionTest.ContentProvider` test is failing in Debian's build network on the [armel](https://buildd.debian.org/status/fetch.php?pkg=cpp-httplib&arch=armel&ver=0.10.2%2Bds-1&stamp=1644965279&raw=0), [armhf](https://buildd.debian.org/status/fetch.php?pkg=cpp-httplib&arch=armhf&ver=0.10.2%2Bds-1&stamp=1644965111&raw=0), [ppc64el](https://buildd.debian.org/status/fetch.php?pkg=cpp-httplib&arch=ppc64el&ver=0.10.2%2Bds-1&stamp=1644964830&raw=0) and [sparc64](https://buildd.debian.org/status/fetch.php?pkg=cpp-httplib&arch=sparc64&ver=0.10.2%2Bds-1&stamp=1644965985&raw=0) architectures.

Tests also often fail on other architectures, so they are a bit flaky in general.

To see all the logs of the current release (0.10.2), you can go here: https://buildd.debian.org/status/logs.php?pkg=cpp-httplib&ver=0.10.2%2Bds-1 - you'll need to click on "Maybe-Failed" to go to the build log.

**Comment by yhirose** [comment]
@Tachi107, since I don't have any access to such architecture machines, there is not way for me to debug this issue. Are you able to figure out what's happening on the architectures and hopefully fix it? Thanks!

**Comment by Tachi107** [comment]
Unfortunately I don't have those machines either. Debian offers access to "porter boxes" (i.e. machines that run on all the supported architectures) to official Debian Developers, but since I've been maintaining packages for only a few months I still don't have access to them.

I think I'll be able to get access to one of those soon, and I'll be then able to debug the failures. But until then I think we should leave this open, so that if somebody who owns a machine running on one of the affected architectures sees this issue they could help us debug it

**Comment by yhirose** [comment]
@Tachi107, could you simply remove cpp-httplib support from architectures except amd64, arm64 and i386, since I don't have time to support them and I am not interested in other architectures anyway? Thanks!

**Comment by Tachi107** [comment]
I could simply disable flaky tests for those architectures, so that users who want to use cpp-httplib on less common architectures don't have to install it from source. Not having those architectures in Debian won't top users from using the library :)

**Comment by yuzibo** [comment]
Hi @Tachi107 , please add failed test cases as flaky on riscv64 arch also, thank you:)
if need me to do more tests on riscv64, please let me know.

**Comment by Tachi107** [comment]
I've just pushed a commit on the Debian packaging branch that disables the flaky tests: https://salsa.debian.org/debian/cpp-httplib/-/commit/2a08f65de8a605e8a72a269e4e1f1bec66919227

To summarize, here's what's currently broken on the various architectures:

- `PutLargeFileWithGzip`, `PutLargeFileWithGzip2` broken on riscv64, mipsel
- `ClientProblemDetectionTest` broken on armel, armhf, sparc64

The real cause of the failure hasn't been fixed though, so if somebody is able to investigate the failures it would be nice :)

Closing for now.
