### ISSUE TITLE
How to invoke multi-params interface

### ISSUE THREAD

**Issue by JingnanJia** [yhirose/cpp-httplib#1206]

**Comment by yhirose** [comment]
https://github.com/yhirose/cpp-httplib#post-with-parameters

**Comment by JingnanJia** [comment]
@yhirose #post-with-parameters：they only support string? For example, I have two-parameters interface , which are file and string. What should I do? thanks.

**Comment by PixlRainbow** [comment]
[C/C++ does not distinguish between human-readable text and binary data. They are both stored using string.](https://github.com/yhirose/cpp-httplib/issues/824#issuecomment-755097175)
