### ISSUE TITLE
How to test POST request

### ISSUE THREAD

**Issue by dwarfovich** [yhirose/cpp-httplib#1208]
I'm trying to test your lib with the following code for url `https://httpbin.org/post`:
```    
    httplib::Client client("https://httpbin.org/");
    auto res = client.Post("post", "My data", nullptr);
    if (res) {
        cout << res->status << endl;
    } else {
        cout << res.error() << endl;
    }
```
and it's always results in `Connection (2)` error. I've tried my work URL and httpbin, both with different parameters of path, body and content_type. It works with WinApi and another, curl-based, library, but not with cpp-httplib. Could you please explain, what I'm doing wrong.

**Comment by PixlRainbow** [comment]
the slash should be part of the path, not the hostname
so `"https://httpbin.org"` and `"/post"`
instead of `"https://httpbin.org/"` and `"post"`

**Comment by dwarfovich** [comment]
```
httplib::Client client("https://httpbin.org");
auto res = client.Post("/post", "My data", nullptr);
```
throws exeption:
> Unhandled exception at 0x00007FFEA32B4F69 in HttpTest.exe: Microsoft C++ exception: std::invalid_argument at memory location 0x000000220490F838.
P.S.: I use Win10 and MSVS2022

**Comment by PixlRainbow** [comment]
The "s" in https means "secure". It means http with encrypted connection.

Httplib makes use of openssl to decode and encode the encryption, so unless openssl is enabled and linked, you will be unable to connect to https servers.

**Comment by dwarfovich** [comment]
Yeah, sorry. I missed that. I'm just added openssl and it works.
