### ISSUE TITLE
Large files Write error 0x5 - Error::Unknown (Multipart-formdata)

### ISSUE THREAD

**Issue by Werew1942** [yhirose/cpp-httplib#1211]
**OS**: Windows
**httplib version**: vcpkg x64-windows-static

Code snippet:
```cpp
bool Telegram::sendDocument(const std::string& buffer, const std::string& fileName)
{
	std::stringstream path;
	path << "/bot" << token << "/sendDocument";

	httplib::MultipartFormDataItems items {
		{ "document", buffer, fileName, "application/octet-stream" },
		{ "chat_id", "xxx", "", "" },
	};
	auto res = cli.Post(path.str().data(), items);
	if (res && res->status == 200)
	{
		return true;
	}
...
```

This works with small files like hello world txt file. Fails with 2MB files also.

![image](https://user-images.githubusercontent.com/32010211/156881893-53859599-580d-4105-ad95-1f5a1e6e6112.png)

I traced the error somewhere around process_socket.

Thanks in advance

**Comment by yhirose** [comment]
@Werew1942, thanks for the feedback, but it's too little information for debugging. Could you please provide the smallest possible code which can reproduce the problem, so that I can debug it on my machine? Thanks!

**Comment by Werew1942** [comment]
Sure.

I'm using telegram API for this, you can change it to someother api idk which public api has form-data support.

Just add bot token, ur chat id and path of file. Hope its not too much work. Lemme know any api so i can make it easier to reproduce.

https://github.com/Werew1942/cpp-httplib-large-files/blob/main/httplib-large-files/main.cpp#L11

this uses vcpkg

![image](https://user-images.githubusercontent.com/32010211/156890645-521d4cba-4a54-4a79-af08-409df5605190.png)

Thanks in advance

**Comment by Werew1942** [comment]
@yhirose Any updates?

**Comment by yhirose** [comment]
@Werew1942, sorry for the late reply. When I have time, I'll try to reproduce this problem on my machine first with simulating your situation with httplib::Server and httplib::Client, then start debugging it. Hopefully I will be available to work on this sometime this month. Thanks for your patience.

**Comment by yhirose** [comment]
@Werew1942, I tried to reproduce it with a httplib::SSLServer, but I don't see any problem. The server that you send requests to seems to have a problem. Could you build and run the following code to see what will happen? Thanks!

```cpp
#include <chrono>
#include <httplib.h>

using namespace httplib;

#define SERVER_CERT_FILE "./cert.pem"
#define SERVER_PRIVATE_KEY_FILE "./key.pem"

template <typename T> void run_server(T callback) {
  SSLServer svr(SERVER_CERT_FILE, SERVER_PRIVATE_KEY_FILE);

  svr.Post("/post", [&](const Request &req, Response & /*res*/,
                        const ContentReader &content_reader) {
    if (req.is_multipart_form_data()) {
      MultipartFormDataItems files;
      content_reader(
          [&](const MultipartFormData &file) {
            files.push_back(file);
            return true;
          },
          [&](const char *data, size_t data_length) {
            files.back().content.append(data, data_length);
            return true;
          });
      for (auto &file : files) {
        std::cout << file.name << ": " << file.content.size()
                  << " bytes, filename: '" << file.filename << "'" << std::endl;
      }
    } else {
      std::string body;
      content_reader([&](const char *data, size_t data_length) {
        body.append(data, data_length);
        return true;
      });
    }
  });

  auto t = std::thread([&]() { svr.listen("localhost", 8080); });
  while (!svr.is_running()) {
    std::this_thread::sleep_for(std::chrono::milliseconds(1));
  }
  std::this_thread::sleep_for(std::chrono::seconds(1));

  callback();

  svr.stop();
  t.join();
}

int main(void) {
  run_server([]() {
    std::string data(1024 * 1024 * 2, '.');
    std::stringstream buffer;
    buffer << data << std::endl;

    Client cli("https://localhost:8080");
    cli.enable_server_certificate_verification(false);

    MultipartFormDataItems items{
        {"document", buffer.str(), "2MB_data", "application/octet-stream"},
        {"hello", "world", "", ""},
    };

    auto res = cli.Post("/post", items);

    if (res) {
      if (res->status == 200) {
        std::cout << "Success!" << std::endl;
      } else {
        std::cout << "Error Status: " << res->status << std::endl;
      }
    } else {
      std::cout << "Error..." << std::endl;
    }
  });
}
```

```bash
> ./test
document: 2097153 bytes, filename: '2MB_data'
hello: 5 bytes, filename: ''
Success!
```

**Comment by yhirose** [comment]
I'll close it for now until I receive more evidence.

**Comment by Werew1942** [comment]
I think its telegram's problem. I made my own https client using wininet and there also same issue, somehow it started working again when tinkering with the multipart form data body.

Thanks in advance. You can close this
