### ISSUE TITLE
upload unicode file name bug

### ISSUE THREAD

**Issue by eurake** [yhirose/cpp-httplib#1212]
# problem
If you upload using a Unicode file name, you cannot get the correct file name and file content
# code 
```
svr.Post("/uploadFile", [&](const auto& req, auto& res) {
    std::string path = boost::dll::program_location().parent_path().string();
    auto imgFile = req.get_file_value("imgFile");

    // log  
    BOOST_LOG_TRIVIAL(fatal) << "file.filename: " << imgFile.filename;
    BOOST_LOG_TRIVIAL(fatal) << "file.content_type: " << imgFile.content_type;
    BOOST_LOG_TRIVIAL(fatal) << "file.name: " << imgFile.name;
    BOOST_LOG_TRIVIAL(fatal) << "file.content: " << imgFile.content.length();

    // generate file name
    boost::uuids::uuid uid = boost::uuids::random_generator()();
    std::string tmpUid = boost::uuids::to_string(uid);
    boost::filesystem::path imgPath(path + "\\upload\\" + tmpUid + ".jpg");

    // write to file 
    std::ofstream  fStream(imgPath.string(), std::ios::binary);
    fStream << imgFile.content;
    fStream.close();

    // return json 
    nlohmann::json jRes;
    jRes["id"] = 1;
    jRes["msg"] = "客户测试1112";
    res.set_content(jRes.dump(), "application/json");
}
```
# used postman to request 
http://127.0.0.1:12345/api/v1/uploadFile
use body => form data => key="imgFile" and Value="1test.jpg"
Can get the picture correctly in http server side

use body => form data => key="imgFile" and Value="测试test.jpg"  
Can‘t get the picture correctly  in http server side
[results are as follows]

# log 
```
[2022-03-15 08:45:50.726725][fatal]:  file.filename: 
[2022-03-15 08:45:50.726725][fatal]:  file.content_type: 
[2022-03-15 08:45:50.726725][fatal]:  file.name: 
[2022-03-15 08:45:50.726725][fatal]:  file.content: 0
```
# analysis
in cpp-httplib.h file line: 3794 
std::regex_match(header, m, re_content_disposition)
can get correctly name and filename 
```
          static const std::string header_name = "content-type:";
          const auto header = buf_head(pos);
          if (start_with_case_ignore(header, header_name)) {
            file_.content_type = trim_copy(header.substr(header_name.size()));
          } else {
            std::smatch m;
            if (std::regex_match(header, m, re_content_disposition)) {
              file_.name = m[1];
              file_.filename = m[2];
            }
          }
```

**Comment by yhirose** [comment]
@eurake, could you provide the smallest possible example with `http::Client` and `http::Server` in a `int main(void)` function, so that I can compile and debug easily on my machine? Thanks for your help.

**Comment by eurake** [comment]
@yhirose  Thank you for your reply

Now I create a solution for repetition,  you can find here https://github.com/eurake/Testcpphttplib.git
I tested a lot more cases than we did before.

* 1 Test in python client use unicode filename  is OK 
* 2 Test in curl  use unicode filename is OK 
* 3 Test in PostMan use Unicode filename is Error 
   postman you can download 

debug get msg cpp-httplib.h file line: 3788 
the header param is different
*  postman request in cpp-http
```
Content-Disposition: form-data; name="imgFile"; filename="中国.jpg"; filename*=UTF-8''%E4%B8%AD%E5%9B%BD.jpg
```
* curl request in cpp-http
```
Content-Disposition: form-data; name="imgFile"; filename="����.jpg"
```
I think it's a "filename“ parameter problem that causes the regular expression to not work properly

**Comment by eurake** [comment]
In https://github.com/eurake/Testcpphttplib.git repository
* 1 Now add  The official sample server2, Can get the correct picture data. throw webrequest ,  but file name is garbled, need to  change std::wstring is ok!
* 2 Add golang http server use postman request, Can get the correct picture data. and file name. 

I think it's possible that Postman is requesting an interface that doesn't meet the HTTP standard (I haven't read the standard carefully).
This problem is not completely solved, but I want to avoid it because my application is a Web page.
Thank you for your attention!

**Comment by yhirose** [comment]
@eurake, thank you for the very helpful detail. It turns out that this problem is caused with `filename*` which is 'ext-parameter' described in [RFC5987](https://datatracker.ietf.org/doc/html/rfc5987). I'll take a look at it when I am available.

**Comment by yhirose** [comment]
What does this mean? Did you make a change in httplib.h to fix the problem from postman?
> need to change std::wstring is ok!

**Comment by yhirose** [comment]
@eurake, could you try the latest httplib.h on master? This change isn't  a perfect solution, but at least the regular expression doesn't fail when 'filename*' is present in the Content-Disposition header. Hope the fix works for you.

**Comment by eurake** [comment]
@yhirose  When I use it in web application, I can get garbled Chinese correctly through web page, and can get files correctly through std::wstring conversion, which does not solve the problem in Postman test. 

Now I read the golang HTTP [code](https://github.com/golang/go/blob/master/src/mime/mediatype.go)  for parsing MultipartForm
I noticed that instead of using regular expressions, golang uses string sequential splitting to get the correct values, which I think is a pretty big job for c++, but I'm sure the problem can be solved need more time.

**Comment by eurake** [comment]
Solving the problem Thank you very much
