### ISSUE TITLE
URL match problem

### ISSUE THREAD

**Issue by WaN3DDK** [yhirose/cpp-httplib#1214]
URL: `http://127.0.0.1:8080/login#token_type=Bearer&access_token=xxxxx&expires_in=604800&scope=identify+guilds+rpc`
It is different from other URLs. Use # as a delimiter.I use the following code:
`svr.Get("/login", [](const httplib::Request& req, httplib::Response& res) `
Could not match this URL. what should I do?
thanks.

**Comment by yhirose** [comment]
@WaN3DDK, thanks for the report. It's a bug. The sever needs to ignore the fragment part.

**Comment by WaN3DDK** [comment]
> @WaN3DDK, thanks for the report. It's a bug. The sever needs to ignore the fragment part.

![image](https://user-images.githubusercontent.com/31143076/158632703-df14b8bc-da5f-4ec6-a51b-a68370cc461e.png)
