### ISSUE TITLE
Questions about delete image on the static server

### ISSUE THREAD

**Issue by DUNDUN-ww** [yhirose/cpp-httplib#1216]
I just started to learn how to use httplib. I have little knowledge about using httplib, so I want to ask for your help.

I have set the mount point by 
```
set_mount_point("/",` "./test");
```
And I could get the image by sending "```client.GET("/2.jpg")```" to view the image "2.jpg" stored on the “test" file folder.
But now I want to delete the image stored on the "test" file folder. I send request "```client.Delete("/2.jpg")```" to delete the image on the "test" file folder, but it didn't work. 
I want to know if my request was sent incorrectly, or for any other reason. Or, how could I delete the image on the static server？
I hope to get your help. Thank you all :).

**Comment by yhirose** [comment]
@DUNDUN-ww, it's a read-only feature to serve static files from a directory via GET and HEAD. (I think other simple Web frameworks like Python Flask also provides only read-only static file serving feature.)

<img width="549" alt="image" src="https://user-images.githubusercontent.com/357397/158805201-7662b4b6-3e44-45cb-9515-3474ebbd6285.png">

If you want to have more control, you can do with `set_pre_routing_handler` to intercept any incoming request and do whatever you want.

Hope it helps!
