### ISSUE TITLE
Request oauth2 authentication. Return error 11001

### ISSUE THREAD

**Issue by WaN3DDK** [yhirose/cpp-httplib#1217]
### code
```
httplib::Client cli("https://discord.com/api/v8")
auto res = cli.Get("/oauth2/token");
if (res)
{
std::cout << res->status;
}
else
{
auto err = res.error();
}
```
res.error() returns code 11001. what does it mean?
![image](https://user-images.githubusercontent.com/31143076/158800882-102e7d57-3cfa-4b2b-a852-c0c16e1c1e49.png)

![image](https://user-images.githubusercontent.com/31143076/158800766-0e63fdf2-2476-44cf-9b17-5dc904852f25.png)

If I use a browser it will return the following result
![image](https://user-images.githubusercontent.com/31143076/158800655-66d55d6c-298c-450f-876f-0f686de96e16.png)

I don't know how to deal with this problem

**Comment by yhirose** [comment]
`httplib::Client cli("https://discord.com/api/v8")` is incorrect. It should take 'scheme' + 'hostname'. Please check with README.
