### ISSUE TITLE
Blocking processes when errors occur

### ISSUE THREAD

**Issue by BestAnHongjun** [yhirose/cpp-httplib#1219]
if (auto res = cli.Post(url.c_str(), req.c_str(), "application/json")) {
    std::cout << res->status << " " << res->body << std::endl;
} else {
    //auto err = res.error();
    std::cout << "Unknow Error!!" << std::endl;
}
------------
If there is an error in the sending process, the process will be blocked. How can I solve this problem?

**Comment by yhirose** [comment]
@BestAnHongjun, thanks for the feedback, but I don't understand what you are mentioning. Could you explain more about it?

**Comment by yhirose** [comment]
Close it until more detail.
