### ISSUE TITLE
Make Https POST request with ignoring the SSL certification verification

### ISSUE THREAD

**Issue by Anil8753** [yhirose/cpp-httplib#122]
I want to make an HTTPS POST login request to my server. Here I do not want to attach any certificate, hence want to disable the SSL certificate verification.
I did not find the example to do so.

**Comment by yhirose** [comment]
@Anil8753, thanks for the feedback. What you want to do is like `curl -k`?

**Comment by yhirose** [comment]
cpp-httplib client doesn't implement the certificate verification yet. That means it's disabled.
