### ISSUE TITLE
Does HTTPS still works with this library

### ISSUE THREAD

**Issue by buckdan** [yhirose/cpp-httplib#1220]
I am trying to request some data from my api with HTTPS but the console print out this error
![image](https://user-images.githubusercontent.com/88769526/159111394-0205f6b4-1119-4bfe-b915-f11b9d827435.png)
So does https still work with this library? If so why do this error pops up

**Comment by yhirose** [comment]
Hope this helps. https://github.com/yhirose/cpp-httplib#ssl-support
