### ISSUE TITLE
Client::Post() returns error SSLServerVerification

### ISSUE THREAD

**Issue by dthnh175** [yhirose/cpp-httplib#1222]
As the title suggests, I'm getting error SSLServerVerification (error code 10) while trying to post a document to Telegram channel using Telegram's API. When developing on my own machine (Visual Studio 2019, windows 10 10.0.18363) it runs completely normal, but when I test on Windows 10 Pro 10.0.19041 it returns error code 10. As I researched it might relate to TLS.
Can you suggest me a solution for this?
my code:

```
httplib::Client cli("https://api.telegram.org");

sprintf(uri, "/bot%s/sendDocument", TELEGRAM_TOKEN);
httplib::MultipartFormDataItems items = {
	{ "chat_id", CHAT_ID, "", "" },
	{ "document", (CHAR*)data, file_name_utf8, "text/plain" }
};
if (auto res = cli.Post(uri, items)) {
	printf("%d\n", res->status);
}
else {
	auto err = res.error();
	printf("error: %d\n", err);
}
```
I installed cpp-httplib and openssl from vcpkg.

EDIT 220321:1650
After some debugging I found the problem lies in the call to openssl's SSL_get_verify_result() function.
![image](https://user-images.githubusercontent.com/41712808/159241265-ed1a838b-f727-431b-bd84-39667a2d43a5.png)

Here the returned result is 19 which means some certification is not verified. What should I do now?

**Comment by mcordova1967** [comment]
If it is acceptable for your case you can disable certificate validation:

	cli.enable_server_certificate_verification(false);

Regards.

**Comment by yhirose** [comment]
@mcordova1967, thanks for the answer!
