### ISSUE TITLE
Does this library have a timer module?

### ISSUE THREAD

**Issue by okman334** [yhirose/cpp-httplib#1226]
as the title, I want to know this lib has a timer or not?

**Comment by Yimura** [comment]
Are you talking about timeouts?

Because the README has a section about this:
![image](https://user-images.githubusercontent.com/24669514/159672328-56ab7baf-fc36-4dcb-98eb-7ed50efcb17e.png)
[README#timeout](https://github.com/yhirose/cpp-httplib#timeout)

**Comment by yhirose** [comment]
@Yimura, thanks for answering the question!

**Comment by okman334** [comment]
Maybe I didn't describe it clearly enough.  I want to ask to set a timer, when the time is up, call back a callback function. 
such as: CNetModule::getSingleton().SetTimer(IDI_CONNECT_CENTER, 2000, this, false); When time has elapsed 2000 milliseconds, will backup a function like:on_timer (int timer_id){}

**Comment by Yimura** [comment]
And why would a http lib have a standalone timer?

**Comment by okman334** [comment]
> And why would a http lib have a standalone timer?

😂. I'm just asking. Usually the server will have this feature.
