### ISSUE TITLE
Garbled characters when outputting some text using cout

### ISSUE THREAD

**Issue by ifloppy** [yhirose/cpp-httplib#1227]
Some special symbols, Chinese will become unexpected text, I think this is an encoding problem, but I can't seem to find a solution on other people's blogs. Please help me with a solution, thanks!

Compiler:TDM-GCC
OpenSSL was compiled with MinGW32 in MSYS

Console:
![image](https://user-images.githubusercontent.com/68799904/159934477-7e40e475-379d-4035-9032-d96786faa054.png)

CodeBlocks:
![image](https://user-images.githubusercontent.com/68799904/159934847-08be69a4-4485-471a-ab7c-ba973c99ef38.png)

**Comment by yhirose** [comment]
@ifloppy, this issue is out of the scope of this library. You are responsible to appropriately convert the text in the response to fit your environment. Sorry that I can't give you any more help.
