### ISSUE TITLE
in line 99 if CPPHTTPLIB_SEND_FLAGS is 0, when servier is closed, request will cause broken pipe crash and can not catch

### ISSUE THREAD

**Issue by tonyonce2017** [yhirose/cpp-httplib#1231]
![image](https://user-images.githubusercontent.com/34465929/160573229-9d1f7bb3-414f-431b-a023-e042fffde39e.png)

**Comment by tonyonce2017** [comment]
i set CPPHTTPLIB_SEND_FLAGS MSG_NOSIGNAL, it looks like fine

**Comment by yhirose** [comment]
It's already described in #77 and #848.
