### ISSUE TITLE
HTTPS Server crash

### ISSUE THREAD

**Issue by rtojagic** [yhirose/cpp-httplib#1232]
Hey, 
I am trying to run HTTPS server, and I've followed your example, but the server just stops without log / errors or anything. I managed to trace where it exits:
![image](https://user-images.githubusercontent.com/8715031/160583021-9c7b1793-39ce-42db-97f4-a340a554560b.png)

How can I get more detailed error message, and what should I do about it? Thanks in advance!

**Comment by rtojagic** [comment]
UPDATE: It seems that it didn't recognize cert paths correctly from Visual Studio, when I run it directly from the Debug/ it worked. It would be useful to at least have some information on why the server crashed.

**Comment by yhirose** [comment]
Thanks for the information.
