### ISSUE TITLE
Couldn't post chinese text

### ISSUE THREAD

**Issue by XingShuyu** [yhirose/cpp-httplib#1234]
when i tried to post a chinese text "你好" ("hello") to a client ,it post ���
code:
`class msgAPI`
`{`
`    public:`
`        void privateMsg(string QQnum, string msg);`
`        void groupMsg(string group_id,string msg);`
`        void sendMsg(string msgType, string id, string msg);//发送消息到收到消息的地方`
`};`
`void msgAPI::privateMsg(string QQnum, string msg)`
`{`
`    string http = "/send_private_msg?user_id=" + QQnum + "&message=" + msg;`
`    const char* path = http.c_str();`
`    httplib::Client cli("127.0.0.1:5700");`
`    auto res = cli.Get(path);`
`}`
`msgsend.privateMsg("778599906", "你好");`
output:
![image](https://user-images.githubusercontent.com/82715884/161876294-abcb3c83-d31f-4f7b-a783-6d4d50ab1734.png)

"77859906"is ID of the user's social account

what can i do to solve this problem?

**Comment by yhirose** [comment]
Your question has nothing to do with cpp-httplib, but it's just a regular HTTP question.
What you have to do is to properly set 'charset' in 'Content-Type' HTTP header.
https://www.w3.org/International/articles/http-charset/index
Hope it helps.

**Comment by XingShuyu** [comment]
> 您的问题与 cpp-httplib 无关，但它只是一个常规的 HTTP 问题。 您需要做的是在“Content-Type”HTTP 标头中正确设置“charset”。 https://www.w3.org/International/articles/http-charset/index 希望对您有所帮助。

打扰一下，我该怎么设置这个东西(content-type)

**Comment by ztkboj58623** [comment]
> > 您的问题与 cpp-httplib 无关，但它只是一个常规的 HTTP 问题。 您需要做的是在“Content-Type”HTTP 标头中正确设置“charset”。 https://www.w3.org/International/articles/http-charset/index 希望对您有所帮助。
> 
> Excuse me, how to set content_type

你要发送UTF-8编码后的字符串，你找个转UTF-8的函数就行了
