### ISSUE TITLE
BindIPAddress when force address family to IPV6 and set outbound interface

### ISSUE THREAD

**Issue by CyberKoo** [yhirose/cpp-httplib#1235]
```
//
// Created by Kotarou on 2022/4/6.
//
#include <httplib.h>

std::unique_ptr<httplib::Client>
get_http_client(std::string_view url, int family = AF_UNSPEC, const char *nif_name = nullptr) {
    auto client = std::make_unique<httplib::Client>(url.data());

    // set outbound interface
    if (nif_name != nullptr) {
        client->set_interface(nif_name);
    }

    // set address family
    client->set_address_family(family);
    client->set_connection_timeout(5);
    client->set_read_timeout(5, 1000);
    client->set_follow_location(true);
    client->set_default_headers({{"User-Agent", "Mozilla"}});

    return client;
}

void print_response(const httplib::Result &result) {
    if (result) {
        std::cout << result->body << std::endl;
    } else {
        std::cerr << "Error: " << httplib::to_string(result.error()) << std::endl;
    }
}

int main(int argc, char *argv[]) {
    std::cout << "AF_UNSPEC, no nif" << std::endl;
    auto client = get_http_client("https://api.ip.sb:443");
    auto response = client->Get("/ip");
    print_response(response);

    std::cout << "AF_UNSPEC, en0" << std::endl;
    client = get_http_client("https://api.ip.sb:443", AF_UNSPEC, "en0");
    response = client->Get("/ip");
    print_response(response);

    std::cout << "AF_INET, no nif" << std::endl;
    client = get_http_client("https://api.ip.sb:443", AF_INET);
    response = client->Get("/ip");
    print_response(response);

    std::cout << "AF_INET, en0" << std::endl;
    client = get_http_client("https://api.ip.sb:443", AF_INET, "en0");
    response = client->Get("/ip");
    print_response(response);

    std::cout << "AF_INET6, no nif" << std::endl;
    client = get_http_client("https://api.ip.sb:443", AF_INET6);
    response = client->Get("/ip");
    print_response(response);

    std::cout << "AF_INET6, en0" << std::endl;
    client = get_http_client("https://api.ip.sb:443", AF_INET6, "en0");
    response = client->Get("/ip");
    print_response(response);
    
    return 0;
}
```

Output:
```
AF_UNSPEC, no nif
2405:aacf:acdc:6dc:33:cda2:153e:745

AF_UNSPEC, en0
38.13.192.76

AF_INET, no nif
38.13.192.76

AF_INET, en0
38.13.192.76

AF_INET6, no nif
2405:aacf:acdc:6dc:33:cda2:153e:745

AF_INET6, en0
Error: BindIPAddress
```

not sure what cause this, but when set address family to AF_INET6 and also force to use en0 as outbound interface, library returned a bind ip error.

**Comment by yhirose** [comment]
@CyberKoo, I feel that it's a general HTTP problem, not a cpp-httplib specific problem. Could you try with other HTTP libraries (or just use the system socket library) on your machine, so that we can check if it's a really cpp-httplib problem?
Thanks for your help!

**Comment by CyberKoo** [comment]
I think this problem was cause by the if2ip function, which only return IPV4 address.
https://github.com/yhirose/cpp-httplib/blob/020b0db090dc8e197cbedbdc4db7e3120eda5333/httplib.h#L2652

**Comment by yhirose** [comment]
Thanks for the report. Could you try again with #1236?

**Comment by CyberKoo** [comment]
Thanks for the fix, but here are some issues I've found.

1. this fix will return an ipv6 address even the address family is set to AF_INET,  need to pass the address_family from create_client_socket to if2ip.
<img width="624" alt="Snipaste_2022-04-07_10-57-39" src="https://user-images.githubusercontent.com/2918558/162111398-0565d044-5559-45ad-8f30-df4be17b06c1.png">

2. incorrect ipv6 address returned from if2ip, cast ifa->ifa_addr to sockaddr_in then use inet_ntop to extract IP address will result the address in backward.
<img width="609" alt="Snipaste_2022-04-07_10-41-48" src="https://user-images.githubusercontent.com/2918558/162109814-015a041d-7eef-42f8-b3f7-227df854470c.png">

for ipv6 address use struct sockaddr_in6 and &sa->sin6_addr
```
auto sa = reinterpret_cast<struct sockaddr_in6 *>(ifa->ifa_addr);
if (inet_ntop(af, &sa->sin6_addr, &buf[0], bufsiz)) {
  freeifaddrs(ifap);
  return buf;
}
```

3. function will return link-local address (fe80) instead of global unicast address.4. 
may be use if_nametoindex from <net/if.h> for POSIX systems? this will rule out need to dealing with ip address

<img width="832" alt="Snipaste_2022-04-07_10-49-47" src="https://user-images.githubusercontent.com/2918558/162110597-425d10ed-257d-472b-a912-3d7ea185618c.png">

**Comment by yhirose** [comment]
@CyberKoo, I updated #1236. Could you test again to see if it makes any progress?

**Comment by CyberKoo** [comment]
Now, I'm getting Connection error.

**Comment by yhirose** [comment]
@CyberKoo, since I can't run properly your example code on my machine, I am not able to debug... Could you debug my changes for me on your machine? (As you can see [here](https://github.com/yhirose/cpp-httplib/pull/1236/files), I actually made your 3 suggestions.) Thanks in advance!

**Comment by yhirose** [comment]
@CyberKoo, any response?

**Comment by CyberKoo** [comment]
Sorry for the delay, I've been busy lately.

Here is the full test project
https://github.com/CyberKoo/cpp-httplib_test

**Comment by CyberKoo** [comment]
<img width="268" alt="1" src="https://user-images.githubusercontent.com/2918558/162657977-ded47039-cbf7-4905-8c92-663e885feac8.png">
here is the output of my example code.

if pass AF_UNSPEC to if2ip no ip address will be returned.

**Comment by yhirose** [comment]
@CyberKoo, thanks for the more information. I would not like to access `api.ip.sb` since I basically don't trust external sites. Is it another way to reproduce the problem with `AF_INET6` and `en0`? If I can reproduce it on my machine, I'll start debugging it. Otherwise, could you debug it and send me a pull request? Thanks a lot!
