### ISSUE TITLE
How to download big file: MWE

### ISSUE THREAD

**Issue by andriish** [yhirose/cpp-httplib#1238]
Hi all,

I saw https://github.com/yhirose/cpp-httplib/issues/917 , but from the links in that answer I cannot understand how to create a minimal working example. Is there any available?
I would be very grateful and I think it is already a solved task.

Best regards,
Andrii

**Comment by yhirose** [comment]
Yes, you can see some content receiver examples in `test/test.cc`.

**Comment by andriish** [comment]
Thank you!
