### ISSUE TITLE
Without Reason-Phrase read_response_line regex fails

### ISSUE THREAD

**Issue by const-volatile** [yhirose/cpp-httplib#124]
The regex in `Client::read_response_line()` is defined as
`const static std::regex re("(HTTP/1\\.[01]) (\\d+?) .+\r\n");`, but certain HTTP server will omit the Reason-Phrase (which is in accordance with RFC 7230). The Reason-Phrase is defined there as:
> reason-phrase = *( HTAB / SP / VCHAR / obs-text )

The `*rule `is similar to the meaning in regex:

> \*rule: The character "\*" preceding an element indicates repetition. The full form is "<n>*<m>element" indicating at least <n> and at most <m> occurrences of element. Default values are 0 and infinity so that "*(element)" allows any number, including zero; "1*element" requires at least one; and "1*2element" allows one or two.

Which means the following is a perfectly valid response line in HTTP/1.1, but the current regex will not match it:
` "HTTP/1.1 404 \r\n"`

Due to that the HTTP status code and HTTP version will not be available in the `Response `object (`version = ""` (empty string) and status being `status = 0xffffffff`) for such response lines. I suggest to modify the regex
`const static std::regex re("(HTTP/1\\.[01]) (\\d+?) .+\r\n");`
to
`const static std::regex re("(HTTP/1\\.[01]) (\\d+?) .*\r\n");`.

Tested and working correctly at my end.

**Comment by const-volatile** [comment]
Pull Request #125

**Comment by yhirose** [comment]
@const-volatile, thanks for the full detailed bug report. It totally makes sense.
I have just merged your PR. Thank for your fine contribution!
