### ISSUE TITLE
why does httplib append back slash to result data

### ISSUE THREAD

**Issue by ckelsel** [yhirose/cpp-httplib#1240]
Why does this library change origin data, this is terrible.

unicode string `\u5403189`  was changed to `\\u5403189`.

How can I remove this back slash?

![image](https://user-images.githubusercontent.com/4329188/162672041-36ec2048-711a-4426-813f-0f9c06205001.png)

**Comment by yhirose** [comment]
@ckelsel, was it a problem on your side? Just curious.
