### ISSUE TITLE
Can I rename an image uploaded by httplib? After studying for a long time, I still don't know what to do. Looking forward to your reply

### ISSUE THREAD

**Issue by Haragarden** [yhirose/cpp-httplib#1250]

**Comment by yhirose** [comment]
Thanks for the feedback, but it's not clear to me...

**Comment by Haragarden** [comment]
#include "paddle_api.h"
#include "httplib.h"
#include "json.h"
#include <arm_neon.h&gt;
#include <stdio.h&gt;
#include <sys/time.h&gt;
#include <unistd.h&gt;
#include <vector&gt;
#include <limits&gt;
#include <iostream&gt;
#include <fstream&gt;
#include <signal.h&gt;
#include <sys/stat.h&gt;


//using namespace std;
using namespace httplib;
using namespace paddle::lite_api;




const char* html = R"(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<html&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<form id="formElem"&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<input type="file" name="image_file" accept="image/*"&gt;<br&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<input type="submit"&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</form&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<script&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;formElem.onsubmit = async (e) =&gt; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;e.preventDefault();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;let res = await fetch('/post', {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;method: 'POST',
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;body: new FormData(formElem)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;});
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;console.log(await res.text());
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;};
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</script&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</html&gt;&nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;)";


int main() {


&nbsp; &nbsp; //创建一个服务器对象
&nbsp; &nbsp; Server server;
&nbsp; &nbsp; server.set_base_dir("/opt/cpp_http");
&nbsp; &nbsp; // upload
&nbsp; &nbsp; server.Get("/upload", [](const Request&amp; req, Response&amp; res) {
&nbsp; &nbsp; &nbsp; &nbsp; (void)req;
&nbsp; &nbsp; &nbsp; &nbsp; res.set_content(html, "text/html");
&nbsp; &nbsp; &nbsp; &nbsp; });
&nbsp; &nbsp; int flag = 0;


&nbsp; &nbsp; server.Post("/post", [&amp;flag](const Request&amp; req, Response&amp; res) {
&nbsp; &nbsp; &nbsp; &nbsp; auto image_file = req.get_file_value("image_file");
&nbsp; &nbsp; &nbsp; &nbsp; //auto text_file = req.get_file_value("text_file");
&nbsp; &nbsp; &nbsp; &nbsp; //image_file.name = "test.jpg";
&nbsp; &nbsp; &nbsp; &nbsp; image_file.filename = "test.jpg";
&nbsp; &nbsp; &nbsp; &nbsp; printf("image file length:", image_file.content.length(), ";image file name:", image_file.filename);


&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; std::ofstream ofs(image_file.filename, std::ios::binary);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ofs << image_file.content;
&nbsp; &nbsp; &nbsp; &nbsp; }


&nbsp; &nbsp; &nbsp; &nbsp; std::string image_name = std::string(image_file.filename);
&nbsp; &nbsp; &nbsp; &nbsp; res.set_content("done", "text/plain");
&nbsp; &nbsp; &nbsp; &nbsp; });


start： subprogram;&nbsp; &nbsp;
//I want to jump back to the subprogram after server.listening(), but it doesn't seem to work


&nbsp; &nbsp; &nbsp; &nbsp;server.Get("/return", [result_2](const Request&amp; req, Response&amp; res) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; (void)req;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; std::string body = "<html&gt;" + result_2 + "</html&gt;";
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; res.set_content("<html&gt;" + result_2 + "</html&gt;", "text/html");




&nbsp; &nbsp; &nbsp; &nbsp; printf("before listen");
&nbsp; &nbsp; &nbsp; &nbsp; server.listen("0.0.0.0", 9000);
&nbsp; &nbsp; &nbsp; &nbsp; printf("after listen");
&nbsp; &nbsp; &nbsp; &nbsp; sleep(20);
&nbsp; &nbsp; &nbsp; &nbsp; printf("after sleep");
&nbsp; &nbsp; &nbsp; &nbsp; //The above three printf() do not work when running on Linux
&nbsp; &nbsp; &nbsp; &nbsp; flag = 1;
goto start


&nbsp; &nbsp; return 0;
}

**Comment by PixlRainbow** [comment]
> `// I want to jump back to the subprogram after server.listening(), but it doesn't seem to work`
> `// The above three printf() do not work when running on Linux`

the `listen()` function enters the main loop of the server. The server takes over control of the thread so that it can stay attentive to incoming requests. You cannot interrupt the thread or "jump" the server's thread or you will terminate the server. If you need to run anything alongside the server, you must start a second, parallel thread for the purpose.
<hr>

https://github.com/yhirose/cpp-httplib/blob/d87abeecf0ca2bd2899140208523413bef6fc523/httplib.h#L3776-L3780
@yhirose does this commented code mean the filename parsing is not ready yet?

**Comment by yhirose** [comment]
@PixlRainbow it does support content disposition message with `filename*` from Postman (#1212, a1df576e4ffac39185ef8f041cff3dd17fec5e3c). But, `filename*` has to be at the last in the content disposition header currently. To **fully** support the content disposition, we have to write a better parser without regex.
