### ISSUE TITLE
CMake fails after commit 33f6738

### ISSUE THREAD

**Issue by CyberKoo** [yhirose/cpp-httplib#1251]
CMake fails with the following error
```
CMake Warning at deps/cpp-httplib/CMakeLists.txt:72 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.
```

caused by commit 33f6738,
https://github.com/yhirose/cpp-httplib/blob/80a55cedebc598d338c0bedb093fc842ceee0983/httplib.h#L6201

Which breaks version match regex
https://github.com/yhirose/cpp-httplib/blob/80a55cedebc598d338c0bedb093fc842ceee0983/CMakeLists.txt#L66

**Comment by yhirose** [comment]
@CyberKoo, sorry about the bug. this is caused by my change for #1249 requested by @bart9h.
@sum01, is it possible to take a look at it if it can be easily fixed? If you think that it's not easy to fix, I'll revert my change.

**Comment by yhirose** [comment]
@sum01, should I make the version define symbol like `#define CPPHTTPLIB_VERSION "0.10.15"`, so that the CMakeLists.txt can detect the version string with `REGEX "CPPHTTPLIB_VERSION \"(\d+\.\d+.\d+)\""`?

**Comment by CyberKoo** [comment]
How about define ```CPPHTTPLIB_VERSION_MAJOR```, ```CPPHTTPLIB_VERSION_MINOR``` and ```CPPHTTPLIB_VERSION_PATCH``` in CMake
then use ```configure_file``` to generate new header file?
more detail: https://cmake.org/cmake/help/latest/command/configure_file.html

**Comment by yhirose** [comment]
@CyberKoo, thanks for the suggestion, but httplib.h should be 'generated' from a template, rather it should be the only source of truth.

**Comment by yhirose** [comment]
@sum01 could you check if there is any problem in my change at 4e28e4f74188c90ae494bbf0f321f6374ea03466 when you have time? Thanks!

**Comment by sum01** [comment]
@yhirose Looks good. Sorry I wasn't around earlier, I've been busy.

**Comment by eli-schwartz** [comment]
@Tachi107 This is relevant to meson.build too...

**Comment by eli-schwartz** [comment]
#1253
