### ISSUE TITLE
HTTP Post Request with headers?

### ISSUE THREAD

**Issue by niansa** [yhirose/cpp-httplib#1262]
Hey, how do I send a HTTP Post request with headers?

**Comment by GribanovIvan** [comment]
did you just solved it and didn't let us know how?

**Comment by iantorresg** [comment]
@GribanovIvan, @niansa 

```cpp
cli.Post(route, {{ "header-name", "header-value" }, { "another-header", "and-his-value" }})
```

**Comment by iantorresg** [comment]
@niansa @GribanovIvan 

https://github.com/yhirose/cpp-httplib/issues/1479

**Comment by SpiritSaint** [comment]
https://github.com/yhirose/cpp-httplib/issues/1479

**Comment by niansa** [comment]
I apologize for that, not sure what happened here :-(
