### ISSUE TITLE
how to use SSLclient?

### ISSUE THREAD

**Issue by WhyLogin** [yhirose/cpp-httplib#1263]
my code :
`httplib::Client cli("https://XXXXX.XXX.com");
`
but get error:
terminate called after throwing an instance of 'std::invalid_argument'
  what():  'https' scheme is not supported.

how to fix it?I found SSLClient in example, but it is not worked too.
Thank you all.

**Comment by PixlRainbow** [comment]
You must compile with [SSL support enabled and the supporting libraries linked](https://github.com/yhirose/cpp-httplib#ssl-support)
