### ISSUE TITLE
test case fail on riscv64 

### ISSUE THREAD

**Issue by yuzibo** [yhirose/cpp-httplib#1266]
Hi,
I am porting the Debian package to riscv64 arch.
And the cpp-httplib package on Debian has a ftbfs(fail to boot from source code) issue, the full buildd log is:

https://buildd.debian.org/status/fetch.php?pkg=cpp-httplib&arch=riscv64&ver=0.10.6%2Bds-1&stamp=1651132099&raw=0

The fail is two test cases:
```bash
[ RUN      ] ServerTest.PutLargeFileWithGzip
../test/test.cc:2949: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] ServerTest.PutLargeFileWithGzip (10415 ms)
[ RUN      ] ServerTest.PutLargeFileWithGzip2
../test/test.cc:2967: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] ServerTest.PutLargeFileWithGzip2 (10287 ms)
...
[  PASSED  ] 191 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] ServerTest.PutLargeFileWithGzip
[  FAILED  ] ServerTest.PutLargeFileWithGzip2

 2 FAILED TESTS

```
It is easy to disable the two test cases on riscv64 arch, but i am not sure that this will affect cpp-httplib stability and function.
Could you give advice how to deal with that?
If you need me to do more test please tell me, I have riscv64 real hardware(unmatched board) by hand :)

**Comment by PixlRainbow** [comment]
It seems like the riscv64 board running the test doesn't have enough resources to complete the large file compression/decompression tests within the timeout period, which is odd considering the specs of the HiFive Unmatched.  

Have you tried creating a 100MB file and then attempting to compress and decompress it with gzip outside of httplib?

**Comment by Tachi107** [comment]
Hi @yuzibo, thanks for looking into this! As I mentioned in #1199, the test suite seems to be quite flaky. On riscv64 in particular, the `ServerTest.PutLargeFileWithGzip` and `ServerTest.PutLargeFileWithGzip2` tests seem to almost always fail (all the logs are [here](https://buildd.debian.org/status/logs.php?pkg=cpp-httplib&arch=riscv64)).

The Debian machines `rv-mullvad-01`, `rv-mullvad-02` and `rv-rr44-01` have been able to build cpp-httplib successfully, while `rv-mullvad-03`, `rv-osuosl-01` and `rv-osuosl-02` always failed, so this might be a hardware-related issue as suggested @PixlRainbow - or maybe there's some kind of race condition somewhere and it's just a coincidence.

> It seems like the riscv64 board running the test doesn't have enough resources to complete the large file compression/decompression tests within the timeout period

You mean a timeout in the test suite or cpp-httplib itself?

**Comment by yuzibo** [comment]
Hi, @PixlRainbow It seems to work to compress and decompress it with gzip outside of httplib on unmatched board:
```bash
vimer@unmatched-local:~$ dd if=/dev/urandom of=bigfile bs=1024 count=102400
102400+0 records in
102400+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 4.94793 s, 21.2 MB/s
vimer@unmatched-local:~$ sha1sum bigfile
052a4acb32ab1cb158df8ae9b76edc4774a58ef4  bigfile
vimer@unmatched-local:~$ cat bigfile | gzip | zcat | sha1sum
052a4acb32ab1cb158df8ae9b76edc4774a58ef4  -
vimer@unmatched-local:~$ echo testing | gzip | zcat
testing
```

@Tachi107 Aha, you are welcome. Before I file the ftbfs on riscv64 bug, I think it would be better to ask for help from here:)

**Comment by PixlRainbow** [comment]
> It seems to work to compress and decompress it with gzip outside of httplib on unmatched board

How long did it take?

**Comment by yuzibo** [comment]
```bash
vimer@unmatched-local:~$ time cat bigfile | gzip | zcat | sha1sum
052a4acb32ab1cb158df8ae9b76edc4774a58ef4  -

real    0m26.263s
user    0m30.817s
sys     0m1.671s
```

**Comment by PixlRainbow** [comment]
> You mean a timeout in the test suite or cpp-httplib itself?

Maybe not necessarily a timeout, but I notice that the `osuosl` family machines always fail that test at close to 10 seconds, give or take a few hundred ms, while the `mullvad` family machines always fail the test at close to 13 seconds, give or take a few ms.

**Comment by yhirose** [comment]
@yuzibo, could you debug this problem to see if this is really caused by cpp-http or an os limitation, since I don't have a machine that can reveal this problem? Thanks for your help.

**Comment by yuzibo** [comment]
Hi, as @PixlRainbow giving the method to measure the gzip command performance, It seems it is ok(If I am wrong about usage please correct me).

Could you give some directory to dig it?  Or I can enable you to login in the real riscv64 hardware if you need :)

**Comment by PixlRainbow** [comment]
yhirose suggests that you add a statement to print the error code and if the error code is not helpful, maybe some breakpoints to try and trace the origin

**Comment by yhirose** [comment]
@yuzibo is it possible to simply remove cpp-httplib from the Debian package for riscv64 arch, since I am not using the environment and it will reduce your work as well. :)

**Comment by yhirose** [comment]
Dup #1199.

**Comment by yuzibo** [comment]
Hi, sorry for the later reply. It is ok to disable it on Debian riscv64 arch. Thank you~
