### ISSUE TITLE
Empty Client Response Using "Get()"

### ISSUE THREAD

**Issue by mipancha** [yhirose/cpp-httplib#1268]
I was having an issue pulling data off an API with the HTTP Client. Turns out that the default timeout in the httplib.h file is about 5 seconds. If you have a large amount of data coming from an API and your request returns an "empty" response it may be because it takes longer than 5 seconds to retrieve. I'd suggest setting this to a larger value in your code above the #include files.

#define CPPHTTPLIB_READ_TIMEOUT_SECOND 15
#define CPPHTTPLIB_READ_TIMEOUT_USECOND 15

**Comment by yhirose** [comment]
Thanks for the suggestion though, I am not going to take it. It all depends on the circumstances, and you can control the values by supplying them via `-D` option or directly putting the define symbols before including httplib.h.
