### ISSUE TITLE
Pipelined requests are dropped if in the same tcp frame

### ISSUE THREAD

**Issue by lecaro71** [yhirose/cpp-httplib#1271]
Multiple http requests (pipelined) in the same tcp frame are dropped, because the SocketStream strm object is "inside" the keep-alive loop, so further data in the buffer of the SocketStream object is discarded after the first request is processed.

**Comment by yhirose** [comment]
@lecaro71, thanks for the feedback. Yes, cpp-httplib doesn't support HTTP pipelining, and I am not planning to support it due to the complexity to implement it properly with good error handing.

**Comment by yhirose** [comment]
A pull request for this is always welcome!
