### ISSUE TITLE
How can I use this library to directly access HTTP services of type IP:PORTS?

### ISSUE THREAD

**Issue by CNLouisLiu** [yhirose/cpp-httplib#1275]
like 127.0.0.1:8080

**Comment by yhirose** [comment]
https://github.com/yhirose/cpp-httplib#client-1

**Comment by CNLouisLiu** [comment]
> https://github.com/yhirose/cpp-httplib#client-1

sorry.I tried, using "http://127.0.0.1:8080" he doesn't work.

**Comment by PixlRainbow** [comment]
please specify "doesn't work" and give code example of what you tried
