### ISSUE TITLE
Using sink.os will drop content

### ISSUE THREAD

**Issue by cozzyd** [yhirose/cpp-httplib#1277]
I've seen issues with using sink.os where it drops content some of the time in a ContentProvider. 

I think the reason is that `data_sink_streambuf` implements `xsputn` but not `overflow,` and which one gets called may depend on all sorts of things. I think the default `std::streambuf` implementation of `overflow` does nothing and the default implementation of `xsputn` calls `overflow`, so it's probably actually `overflow` you want to implement. 

But the naive implementation is going to be excruciatingly slow, so some buffering needs to be added (and the buffer must be shared between `xsputn` and `overflow` otherwise you can get stuff out of order). 

I got decent results using something like this instead, though it's probably far from optimal and I have to make sure it gets flushed before `sink.done()` is called (and the return values probably aren't really conforming to `std::streambuf`) : 
```
class SinkStream : public std::streambuf
{
        public:
                SinkStream(httplib::DataSink & sink, int bufsize = 1024)
                : sink_(sink), buf_(bufsize), filled_(0)
                {
                        ;
                }

                bool flush()
                {
                        bool success = sink_.write(&buf_[0], filled_);
                        filled_ = 0;
                        return success;
                }

                int overflow(int c) override
                {
                        if (c == EOF)
                        {
                                flush();
                                return EOF;
                        }
                        else
                        {
                                buf_[filled_++] = (char) c;
                                if (filled_ == buf_.size())
                                {
                                        return flush();
                                }
                                return 0;
                        }
                }
        private:
                httplib::DataSink & sink_;
                std::vector<char> buf_;
                size_t filled_;
};

```

**Comment by yhirose** [comment]
@cozzyd, thanks for the feedback. Could you please send a pull request with a unit test to validate the fix? Thanks.

**Comment by yhirose** [comment]
@cozzyd, any update?

**Comment by cozzyd** [comment]
Hi!

Sorry, have not had a chance to get a minimal example together yet.
Maybe this weekend...

Thanks,
-Cosmin

**Comment by yhirose** [comment]
Close it for now.
