### ISSUE TITLE
Server is set too early to "is_running"

### ISSUE THREAD

**Issue by theShmoo** [yhirose/cpp-httplib#1279]
The server is set to "is_running" before it is actually running

https://github.com/yhirose/cpp-httplib/blob/a449d82723ffb9f383196f156a2e659754ceff3f/httplib.h#L5339

I have a unit test which creates a server (in a backend thread) and closes it again:

(pseudo code here!)

```cpp
auto server = std::make_unique<server>(config);
auto server_thread = std::make_unique<std::thread>([&]() { is_listening = server ->start(); });
// busy wait until the server is running
while (is_listening && !server->is_running())
{
  std::this_thread::sleep_for(std::chrono::milliseconds{1});
}
ASSERT_TRUE(is_listening);
server->stop();
server_thread->join();
```

Here is a detected race condition in parts of the cpphttlib as the starting code is not yet finished, but the server is already set to "is_running".

I would suggest to move the variable `is_running_` to a later point. and even better provide an option to register a callback when the server started (or failed to start).

**Comment by yhirose** [comment]
@theShmoo, thank you for the report! Could you please send a pull request including your unit test and the solution that you suggested? Thanks a lot!

**Comment by theShmoo** [comment]
Thanks for your reply!

I will try to setup a unit test. Currently this only exists in our application (with an own thread pool).

Sorry this will take a while.

**Comment by theShmoo** [comment]
I tried to reproduce the error in a unit test directly in your library and found the great unit test: `ServerUpDownTest` which I modified a little bit.
But I could not reproduce the problem. I think the race condition it is in our application.

Still I think the flag is set to true too early.
