### ISSUE TITLE
Race condition with keep-alive timeout

### ISSUE THREAD

**Issue by ArnaudBienner** [yhirose/cpp-httplib#1282]
I use keep-alive in my application to reduce latency, and this works well :)

While trying to understand the potential issues keep-alive can introduce, I've found this [Wikipedia article](https://en.wikipedia.org/wiki/HTTP_persistent_connection#Disadvantages) which explains that a race condition can happen if the server closes the connection (because timeout) at the same time the client sends a new request on the same connection.

Wikipedia article references this [SO post](https://stackoverflow.com/questions/42631273/how-do-browsers-handle-http-keepalive-race-condition), which links this [python script](https://github.com/mikem23/keepalive-race) which I tried, and indeed I can see the issue happening when running it (more likely to happen when running the python client script on my computer and targeting a server remotely i.e. not running on localhost).

It seems that the server should send a 408 error code when the connection timeout.

It might be fine for clients to be aware of this and simply retry to send a request on connection close/failure, but I was wondering if this could be fixed in a nice way within cpp-httplib.

I tried to fix this by changing the logic in `process_server_socket_core` and `keep_alive` so we know if the keep_alive returns false because of a timeout. In this case, `close_connection = true` and we proceed calling `callback`.

The other change that might be needed is setting `res.status = 408` in `Server::write_response_core` after `res.set_header("Connection", "close");`

I tried that change but I'm not completely sure if the behavior I implemented is correct...

But I wanted to at least raise the issue so you're aware of it, and get your feedback about it.

**Comment by ArnaudBienner** [comment]
FWIW a similar bug report on node.js project: https://github.com/nodejs/node/issues/38890

**Comment by yhirose** [comment]
@ArnaudBienner, thank you for the feedback. Could you please try to reproduce the problem with the smallest possible server code and a client code? Then, I'll take a look at it to implement the feature. Thanks!

**Comment by yhirose** [comment]
I'll close this issue for now until I receive a clear evidence for this problem.
