### ISSUE TITLE
Unable to upload large data via post-request

### ISSUE THREAD

**Issue by chrxh** [yhirose/cpp-httplib#1285]
Hello,

I have a problem with sending larger data. It seems to be related to https://github.com/yhirose/cpp-httplib/issues/1211.
Here is a minimal example for my case:

```
httplib::SSLClient client(_address);
client.set_ca_cert_path("./resources/ca-bundle.crt");
client.enable_server_certificate_verification(true);

std::string test(1000000, '0');
httplib::MultipartFormDataItems items = {{"data", test, "", "application/octet-stream"}};
auto result = client.Post("/upload.php", items);

```
I obtain a `Write` (5) error. If the test string is smaller (~10 KB) then everything works.
Did I forget to configure something or is it because of the server (it's a hosted web server)?
(On the other hand, I had already managed to send larger data to this server via post using Qt and it worked.)

Thanks for the help in advance

**Comment by yhirose** [comment]
@chrxh, thank you for the report. Your code looks ok, and I honestly don't know why it returns with the Write error. Could you run the following unit test which uploads 2MB data to a server to find more information?

https://github.com/yhirose/cpp-httplib/blob/47044c05a8587dff86ab90526daabfef61079490/test/test.cc#L4881

Here is my result on my macOS.

```
[master] ~/cpp-httplib/test$ make test && ./test --gtest_filter="MultipartFormDataTest.LargeData"
make: `test' is up to date.
Running main() from gtest/gtest_main.cc
Note: Google Test filter = MultipartFormDataTest.LargeData
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from MultipartFormDataTest
[ RUN      ] MultipartFormDataTest.LargeData
[       OK ] MultipartFormDataTest.LargeData (1100 ms)
[----------] 1 test from MultipartFormDataTest (1100 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (1101 ms total)
[  PASSED  ] 1 test.
```

**Comment by yhirose** [comment]
I'll leave it open for a while. Please let me know if you find more information. Thanks!

**Comment by chrxh** [comment]
I've now found out that I was using an outdated version of cpp-httplib via vcpkg (namely 0.9.7). In the latest version my problem does not occur at all. Has something been fixed in this context?
In any case my I can close my pull request.
