### ISSUE TITLE
The compiler feature "cxx_attribute_deprecated" is not known to CXX

### ISSUE THREAD

**Issue by aengusjiang** [yhirose/cpp-httplib#1286]
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
when I use the find_package httplib, it occur the error
![image](https://user-images.githubusercontent.com/22406984/170288804-5ea2b43d-d141-4ba8-b861-b3dc279f31f7.png)

CMAKELists.txt
`cmake_minimum_required (VERSION 3.10.0)

# set the project name
project(test)

# set the g++ gcc flags
if(CMAKE_BUILD_TYPE STREQUAL Release)
    #set(CMAKE_CXX_FLAGS "-Wall -g -pipe -D_NEW_LIC -D_GNU_SOURCE -fPIC -D_REENTRANT -DDEBUG -Wno-deprecated -std=c++11")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -O3 -g -pipe -D_NEW_LIC -D_GNU_SOURCE -fPIC -D_REENTRANT -std=c++11 ")
else(CMAKE_BUILD_TYPE STREQUAL Release)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -g -pipe -D_NEW_LIC -D_GNU_SOURCE -fPIC -D_REENTRANT -std=c++11")
endif(CMAKE_BUILD_TYPE STREQUAL Release)

find_package(httplib)
# set the target name fot this target
set(TARGE_NAME "server")
# aux_source_directory("./hook" HOOK_SRC)
add_executable(${TARGE_NAME} server.cpp)
# target_link_libraries(${TARGE_NAME} ${LIBS_DEPEND} cppzmq)
target_link_libraries(${TARGE_NAME} ${LIBS_DEPEND} httplib::httplib)`

![image](https://user-images.githubusercontent.com/22406984/170288622-917e0600-56a4-4220-8dff-3cb99043b12f.png)

**Comment by yhirose** [comment]
Please see [this](https://github.com/yhirose/cpp-httplib#g).
