### ISSUE TITLE
http server can't provide zip file large than 2GB with project both defined _WIN32 and _WIN64

### ISSUE THREAD

**Issue by conghuawang** [yhirose/cpp-httplib#1290]
if project both defined _WIN32 and _WIN64, http server can't provide zip file large than 2GB

in function "SocketStream::write", change:

#ifdef _WIN32
  size =
      (std::min)(size, static_cast<size_t>((std::numeric_limits<int>::max)()));
#endif

to:

#if defined(_WIN32) && !defined(_WIN64)
  size =
      (std::min)(size, static_cast<size_t>((std::numeric_limits<int>::max)()));
#endif

resolve this problem.

**Comment by yhirose** [comment]
@conghuawang, thank you for the feedback. Could you send the patch as a pull request including at least one unit test? Thanks a lot!

**Comment by conghuawang** [comment]
I had send a pull request
