### ISSUE TITLE
Does cpp-httplib has HTML sanitization feature?

### ISSUE THREAD

**Issue by shujaatak** [yhirose/cpp-httplib#131]
Does cpp-httplib has HTML sanitization feature buit-in? Or can you point me to some resource, library, tutorial or anything helpful regarding it which may work with cpp-httplib please?

**Comment by yhirose** [comment]
@shujaatak, thanks for your interest. The short answer is no. This library itself is just caring for handling 'HTTP' protocol. How to handle various content formats such as HTML, JSON, JavaScript and so on are completely out of scope of this library. In other works, you can do anything by your self or it's up to you what kind of library is used to sanitize your content. Hope it helps!
