### ISSUE TITLE
Strange error while GET request

### ISSUE THREAD

**Issue by VernadskyDanya** [yhirose/cpp-httplib#1313]
Hi, I am not a professional at C++ and I got a strange error using this library. 
After 2-4 hours of running my program, I get error, which you can see on my screenshot. But my program sends this request every 5-10 seconds and it works fine. Does it mean, that it's my personal mistake in the program or it's some strange behavior of the library? (I don't have any parallel processes)

How can I figure out the reason of this problem? 
Thank you!!

![ScreenshotError](https://user-images.githubusercontent.com/67655038/175893184-b6a95a91-7aea-40c6-9551-31ff6a4f4e64.PNG)

**Comment by yhirose** [comment]
You have to check if `res` is valid first. The following README example shows how to do this:
https://github.com/yhirose/cpp-httplib#client-1
Hope it helps!

**Comment by VernadskyDanya** [comment]
Thank you! I will test it. But can you explain at least a little bit what is the reason of this kind of error?

**Comment by yhirose** [comment]
Please see https://github.com/yhirose/cpp-httplib#error-code in README.
