### ISSUE TITLE
SSLServer svr dont work in linux (Google Cloud Console)

### ISSUE THREAD

**Issue by Teruhashi12** [yhirose/cpp-httplib#1315]
SSLServer svr giving error like this
im use Linux in https://console.cloud.google.com

![Screenshot (75)](https://user-images.githubusercontent.com/90950171/176914597-b516ee97-21d4-4ed4-9275-3734af7734d5.png)
![Screenshot (76)](https://user-images.githubusercontent.com/90950171/176914606-50e0ff45-92f7-47ae-8904-1baaa21a8835.png)

**Comment by yhirose** [comment]
I think `CPPHTTPLIB_OPENSSL_SUPPORT` isn't declared in your code.

**Comment by Teruhashi12** [comment]
when im add #define CPPHTTPLIB_OPENSSL_SUPPORT
it giving error like this when im build the source
![Screenshot (48)](https://user-images.githubusercontent.com/90950171/176983751-90bafa6d-8cbb-4688-8af1-d6d29ffe9ee2.png)

**Comment by PixlRainbow** [comment]
Duplicate of #1263 
> You must compile with [SSL support enabled and the supporting libraries linked](https://github.com/yhirose/cpp-httplib#ssl-support)
