### ISSUE TITLE
 Handling user-defined exceptions

### ISSUE THREAD

**Issue by kuguma** [yhirose/cpp-httplib#1318]
I use httplib as the HTTP interface for my program (thanks for the great library!)

I have a question about exception handling.

My program has several exception classes that inherit from std::exception. These have their own methods for bug tracking.

The problem is that the httplib exception handler wraps all exceptions into std::exception.
When problems occur in routing (and subsequent my programs), I would like to handle them in the my exception class. However, I am having trouble finding a good way to do this.

Any advice would be appreciated.

**Comment by kuguma** [comment]
Is it practical to change httplib to use std::exception_ptr for the ExceptionHandler interface?
The user would be able to use std::rethrow_exception() to rethrow the exception and then try-catch to handle their own exception.
Currently, though, it would be possible to do the same with RTTI.

**Comment by yhirose** [comment]
@kuguma, thank you for the feedback. Could you show me a simple code example to explain what you would like to do?

**Comment by adamaa5** [comment]
You could use `std::runtime_error("<ERROR_CODE>")` and then in your post/get handler add a try/catch where you test `e.what() == "<ERROR_CODE>` to handle different exceptions differently.

**Comment by yhirose** [comment]
@kuguma, any response?

**Comment by kuguma** [comment]
Thank you for your reply! I made a pull request.

**Comment by kuguma** [comment]
> You could use `std::runtime_error("<ERROR_CODE>")` and then in your post/get handler add a try/catch where you test `e.what() == "<ERROR_CODE>` to handle different exceptions differently.

Well, I understand that the interface was created with such usage in mind.

**Comment by kuguma** [comment]
I've typoed the PR title:sob:

**Comment by yhirose** [comment]
@kuguma, thanks for the pull request. I now understand what you are trying to do. I'll place my comments in the pull request and close this issue.
