### ISSUE TITLE
Question/Request: Why does Client::Get not accept std::string as well?

### ISSUE THREAD

**Issue by n00b42** [yhirose/cpp-httplib#1322]
Is there a particular reason why `Server::Get` accepts std::string, but `Client::Get` does not?

**Comment by yhirose** [comment]
@n00b42, thanks for the question. There is not a particular reason. I may change both Client and Serve to use `std::string` for consistency.

**Comment by Tachi107** [comment]
> https://stackoverflow.com/questions/57951871/is-there-sense-in-using-const-stdstring-arguments-in-c17

I usually work around the NULL-termination issue by not using `std::string_view` directly, but by instead using a C++20 concept that requires that the `std::string_view` is either convertible to a `const char*` or a `std::string`, thus NULL-terminated. This way the user can pass into functions using this concept either a `const char*` or a `std::string`, but not a `std::string_view` that's not NULL-terminated, without having to do runtime checks.

```cpp
// NULL-terminated std::string_view
template<typename T>
concept Text = std::convertible_to<T, std::string_view> && (std::convertible_to<T, std::string> || std::convertible_to<T, const char*>);
```

This of course requires C++20, and cpp-httplib only uses C++11, but when the day will come you could look into using this little trick :)
