### ISSUE TITLE
Generate both pc file and cmake config files by calling just `meson` or `cmake`

### ISSUE THREAD

**Issue by paperchalice** [yhirose/cpp-httplib#1328]
Background: I want to add this library to homebrew-core, here is the PR: https://github.com/Homebrew/homebrew-core/pull/106003

I try to provide both pc file and cmake config file so other libraries can use it e.g. `llvm`, but I can't do that when I just only use `meson` or `cmake`, so currently I use both these build systems to generate them. Will this project support generate these two format in one build system? Seems there is no elegant way to do this. `cmake` needs a pc template. `meson` can configure the `httplibConfig.cmake.in` but exporting `cmake` target needs this [WIP feature](https://github.com/mesonbuild/meson/pull/9978). Keeping the exporting content same is also a problem.

**Comment by paperchalice** [comment]
Thanks for your replies! Static copy of target file makes sense here, but I'm not sure how configure options, e.g. `HTTPLIB_COMPILE`, affect here.

**Comment by sum01** [comment]
Not sure I understand what you want. Are you saying you want the build-specific conf files generated upon running Cmake? I don't think putting them in the repo will actually work since it varies based on build settings and some system stuff.

**Comment by paperchalice** [comment]
> Not sure I understand what you want. Are you saying you want the build-specific conf files generated upon running Cmake? I don't think putting them in the repo will actually work since it varies based on build settings and some system stuff.

Required files are `httplibTargets.cmake` and `httplibTargets-<CMAKE_BUILD_TYPE>.cmake`, they are indeed build settings related.

**Comment by eli-schwartz** [comment]
pkg-config files are usable in cmake via `find_package(PkgConfig)` and `pkg_check_modules()`, so that may be an option for projects to just use that, even if they too use cmake to build.

It's disappointing that cmake doesn't have anything like Meson's `dependency()` interface, which supports trying both pkg-config and cmake `find_package()` to look up a dependency. :(

**Comment by paperchalice** [comment]
So for this project I think I can keep what I've done in https://github.com/Homebrew/homebrew-core/pull/106003 from the feed back, thanks a lot!

**Comment by yhirose** [comment]
@paperchalice, what's the current state of this issue? Can I close it?

**Comment by paperchalice** [comment]
Sorry for another question. Could we generate pkg config file in `cmake`? `cmake` doesn't support generate pkg config file, see https://gitlab.kitware.com/cmake/cmake/-/issues/22621, so we need to use `configure_file` in `cmake`, does is make sense here?

**Comment by Tachi107** [comment]
You could by hardcoding a few values, but as cpp-httplib can be configured to optionally use various dependencies it would be a bit harder to do it properly with the `configure_file()` method.

You could give it a try if you want to, but if I were you I would simply distribute the .pc file generated by Meson, as it is usable by Meson, Muon, CMake, autotools, shell scripts, etc, while CMake config files are only usable by CMake and Meson.

**Comment by paperchalice** [comment]
Thanks!
