### ISSUE TITLE
Async Handler

### ISSUE THREAD

**Issue by abdulrehman-git** [yhirose/cpp-httplib#133]
In the following example, thread is going to sleep for a long operation:

    svr.Get("/slow", [](const Request& /*req*/, Response& res) {
            std::this_thread::sleep_for(std::chrono::seconds(2));
            res.set_content("Slow...\n", "text/plain");
    });

Is it possible to do something like the following?

    svr.Get("/slow", [](const Request& /*req*/, Response& res) {
            //two_second_long_async(req, res, onCompletedCallback); // without future/promise
            //return response on onCompletedCallback; //without blocking the thread
    });

Can we achieve asynchronous behavior somehow?

**Comment by yhirose** [comment]
@abdulrehman-git, thanks for your feedback!

Unfortunately, I don't come up with an easy way to handle your request in cpp-httplib.

If you really need the behavior right now, it would be better to look for other HTTP server libraries based on [libuv](https://github.com/libuv/libuv) or [Boost.Asio](https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio.html).

I'll label it as 'enhancement' for now.
