### ISSUE TITLE
Get IP address from connection/client

### ISSUE THREAD

**Issue by Rockybilly** [yhirose/cpp-httplib#1340]
I want to access which ip I am connected to, using the Client interface. I am not doing a hostname check myself, because dns results may change after a connection is established, but I want to know the socket I am sending requests to.

You can expose the socket underneath through a get_ function (just like how std::thread provides p_thread handler in linux), then people can use it for all purposes.

Or for this specific issue, a function could be written. But I would suggest making the socket available if needed. There all sorts of system-based functions people may want to call on a socket.

**Comment by yhirose** [comment]
@Rockybilly, thanks for the suggestion, but I can't think of any situations where I can use the enhancement in my projects. So, I am not planning to implement it. Of course, a pull request with a unit test is always welcome :)
