### ISSUE TITLE
Webview

### ISSUE THREAD

**Issue by wwderw** [yhirose/cpp-httplib#1343]
I have a webview project that uses WASM, so I need to have a file server in place in order to get around CORs with regard to the WASM.  I was wondering about two things: 

1.  In order to aid in distribution, I was going to try to have a virtual file system in binary that would have all my files, assets, scripts, wasm etc.

2.  Would would able to pick up on a virtual file system and would it also be able to register the termination of the webview to cancel the server?

Thanks for the help.

**Comment by yhirose** [comment]
@wwderw, thanks for the comment, but I honestly don't understand what you are talking about... Is it related to cpp-httplib?

**Comment by wwderw** [comment]
My thought is using httplib as a static file server for a webview project.  I have to use a server as I'm using WASM in order to get around CORs, and that is where httplib comes in. 

What I would like to do is embed all of those assets in the binary, instead of having separate (which all of this is fine, so far) files to distribute.  Is there a way to mount that virtual file system using httplib: so when you do something like this
`svr.set_mount_point("/", "public");`

"public" is replaced with the virtual file system.  Or would I need to write all of those files out on the HD and proceed to point to that?

**Comment by yhirose** [comment]
cpp-httplib supports only the regular file system on the current operating system where it is running on. Here is the code to handle file requests.

https://github.com/yhirose/cpp-httplib/blob/1bd88de2e591bac2d84a0fbf5521b47a3ebc3041/httplib.h#L5281-L5309

If you would like to support a virtual file system, you could re-implement `Server::handle_file_request` to access resources via your virtual file system instead of the regular file system. (I am not planning to implement it, since I don't know about 'virtual file system' and wonder if there is an easy way to make such a feature in a portable way without a third-party library.)

Also I don't know if it's really possible to compile a cpp-httplib server into a WASM binary, since it uses sockets and threads...

**Comment by PixlRainbow** [comment]
Unfortunately, it seems that abstract filesystem handles on the **_directory-level_** only became standard in C++17 but httplib is C++11. Below C++17, only file-level abstract handles are available in the form of `FILE`, `fstream` and their derivatives.

The closest C++11-compatible workaround could be to allow the user to provide a callback with the signature `std::ifstream (const std::string&)` httplib passes the callback a relative path, the callback returns an `ifstream` for the file at that path. If the file doesn't exist, `.good()` on the returned stream will be `false`.

**Comment by wwderw** [comment]
Well the lib that I'm using for the embed is also C++11.  The files appear to be FILE and EFILE.

**Comment by wwderw** [comment]
> cpp-httplib supports only the regular file system on the current operating system where it is running on. Here is the code to handle file requests.
> 
> https://github.com/yhirose/cpp-httplib/blob/1bd88de2e591bac2d84a0fbf5521b47a3ebc3041/httplib.h#L5281-L5309
> 
> If you would like to support a virtual file system, you could re-implement `Server::handle_file_request` to access resources via your virtual file system instead of the regular file system. (I am not planning to implement it, since I don't know about 'virtual file system' and wonder if there is an easy way to make such a feature in a portable way without a third-party library.)
> 
> Also I don't know if it's really possible to compile a cpp-httplib server into a WASM binary, since it uses sockets and threads...

No, the WASM module is it's own entity that would be compiled within the virtual file system.  httplib would not be in it.  It would be in the bit with webview, which is where if doing get/post etc requests would be handled.  So there is no issue there.

**Comment by yhirose** [comment]
As a summary, cpp-httplib can't provide such a virtual file system access at this point. You could fork httplib.h and re-implement `erver::handle_file_request` to utilize the virtual file system. Or you could implement a regular routing handler and put your virtual file system access code in it as below.

```cpp
#include <httplib.h>
using namespace httplib;

int main(void) {
  Server svr;

  svr.Get("/.*", [&](const Request &req, Response & /*res*/) {
    // Write your code which will access your 'virtual file system' here...
    // `req.path` contains the path.
  });

  auto t = std::thread([&]() { svr.listen("localhost", 8080); });

  Client("http://localhost:8080").Get("/path/to/file");

  svr.stop();
  t.join();
}
```

Hope the information helps!

**Comment by wwderw** [comment]
> As a summary, cpp-httplib can't provide such a virtual file system access at this point. You could fork httplib.h and re-implement `erver::handle_file_request` to utilize the virtual file system. Or you could implement a regular routing handler and put your virtual file system access code in it as below.
> 
> ```c++
> #include <httplib.h>
> using namespace httplib;
> 
> int main(void) {
>   Server svr;
> 
>   svr.Get("/.*", [&](const Request &req, Response & /*res*/) {
>     // Write your code which will access your 'virtual file system' here...
>     // `req.path` contains the path.
>   });
> 
>   auto t = std::thread([&]() { svr.listen("localhost", 8080); });
> 
>   Client("http://localhost:8080").Get("/path/to/file");
> 
>   svr.stop();
>   t.join();
> }
> ```
> 
> Hope the information helps!

I think this may work.  Thanks for all of the help.  I really do appreciate it.

**Comment by yhirose** [comment]
@wwderw, actually, it's better to use the pre routing handler.

```cpp
svr.set_pre_routing_handler([](const auto& req, auto& res) {
  if (req.path == "/hello") {
    res.set_content("world", "text/html");
    return Server::HandlerResponse::Handled;
  }
  return Server::HandlerResponse::Unhandled;
});
```

https://github.com/yhirose/cpp-httplib#pre-routing-handler

**Comment by wwderw** [comment]
@yhirose Thanks.  I'll give that a shot.

Thanks again for all the help.
