### ISSUE TITLE
bypass NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by Teruhashi12** [yhirose/cpp-httplib#1349]
when im trying to add https it give error Segmentation fault (core dumped)
but when im trying add http it not give error
i think this is the problem

how i can bypass this
![Screenshot (61)](https://user-images.githubusercontent.com/90950171/182570512-7e59b3f4-c3cc-49ab-9ff4-2f0be8630f24.png)
?

**Comment by yhirose** [comment]
Sorry, but there is too little information...

**Comment by PixlRainbow** [comment]
you can [disable server certificate verification](https://github.com/yhirose/cpp-httplib#ssl-support) as a workaround.

However, this is not a secure setup and I would recommend that you re-sign your server certificate as soon as possible.
