### ISSUE TITLE
Server can only parse the first param ?

### ISSUE THREAD

**Issue by h2cw2l** [yhirose/cpp-httplib#1352]
curl http://10.66.150.2:9001/?op=stopOne&app=app1

I use this cmd to access the server, only the first param can be parsed.

**Comment by yhirose** [comment]
@h2cw2l, thanks for the report. Could you take a look at the following unit test in `test/test.cc`? Hope it helps.

https://github.com/yhirose/cpp-httplib/blob/4f8407a3a7bfe04c85ecd3dae8e0fb3c40c5ec75/test/test.cc#L1543-L1551
https://github.com/yhirose/cpp-httplib/blob/4f8407a3a7bfe04c85ecd3dae8e0fb3c40c5ec75/test/test.cc#L2045-L2060
