### ISSUE TITLE
why there so many threads defaultly ? Can I configure it to reduce thread num ?

### ISSUE THREAD

**Issue by h2cw2l** [yhirose/cpp-httplib#1353]
(gdb) bt
#0  0x0000007fb7c002a4 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7fb00011f8)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7fb0001200, cond=0x7fb00011d0) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7fb00011d0, mutex=0x7fb0001200) at pthread_cond_wait.c:655
#3  0x0000007fb735bb78 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#4  0x0000007fb7e2c5ac in void std::condition_variable::wait<httplib::ThreadPool::worker::operator()()::{lambda()#1}>(std::unique_lock<std::mutex>&, httplib::ThreadPool::worker::operator()()::{lambda()#1}) () from /lib/libifos-vcl.so
#5  0x0000007fb7e05728 in httplib::ThreadPool::worker::operator()() () from /lib/libifos-vcl.so
#6  0x0000007fb7e86180 in void std::__invoke_impl<void, httplib::ThreadPool::worker>(std::__invoke_other, httplib::ThreadPool::worker&&) ()
   from /lib/libifos-vcl.so
#7  0x0000007fb7e74788 in std::__invoke_result<httplib::ThreadPool::worker>::type std::__invoke<httplib::ThreadPool::worker>(httplib::ThreadPool::worker&&) () from /lib/libifos-vcl.so
#8  0x0000007fb7ec95f8 in decltype (__invoke((_S_declval<0ul>)())) std::thread::_Invoker<std::tuple<httplib::ThreadPool::worker> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) () from /lib/libifos-vcl.so
#9  0x0000007fb7ec937c in std::thread::_Invoker<std::tuple<httplib::ThreadPool::worker> >::operator()() () from /lib/libifos-vcl.so
#10 0x0000007fb7ec9144 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<httplib::ThreadPool::worker> > >::_M_run() ()
   from /lib/libifos-vcl.so
#11 0x0000007fb7361e94 in ?? () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#12 0x0000007fb7bfa088 in start_thread (arg=0x7fb6ac103f) at pthread_create.c:463
#13 0x0000007fb71f8ffc in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78
(gdb)

  4    Thread 0x7fb69c0da0 (LWP 23830) "em_daemon" 0x0000007fb7c002a4 in futex_wait_cancelable (private=<optimized out>, expected=0,
    futex_word=0x7fb00011f8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  5    Thread 0x7fb68bfda0 (LWP 23831) "em_daemon" 0x0000007fb7c002a4 in futex_wait_cancelable (private=<optimized out>, expected=0,
    futex_word=0x7fb00011f8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  6    Thread 0x7fb67beda0 (LWP 23832) "em_daemon" 0x0000007fb7c002a4 in futex_wait_cancelable (private=<optimized out>, expected=0,
    futex_word=0x7fb00011f8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  7    Thread 0x7fb66bdda0 (LWP 23833) "em_daemon" 0x0000007fb7c002a4 in futex_wait_cancelable (private=<optimized out>, expected=0,
    futex_word=0x7fb00011f8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  8    Thread 0x7fb65bcda0 (LWP 23834) "em_daemon" 0x0000007fb7c002a4 in futex_wait_cancelable (private=<optimized out>, expected=0,
    futex_word=0x7fb00011f8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  9    Thread 0x7fb64bbda0 (LWP 23835) "em_daemon" 0x0000007fb7c002a4 in futex_wait_cancelable (private=<optimized out>, expected=0,
    futex_word=0x7fb00011f8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
* 10   Thread 0x7fb63bada0 (LWP 23836) "em_daemon" 0x0000007fb7c002a4 in futex_wait_cancelable (private=<optimized out>, expected=0,
    futex_word=0x7fb00011f8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  11   Thread 0x7fb62b9da0 (LWP 23837) "em_daemon" 0x0000007fb7c002a4 in futex_wait_cancelable (private=<optimized out>, expected=0,
    futex_word=0x7fb00011f8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88

**Comment by yhirose** [comment]
Hope [this information](https://github.com/yhirose/cpp-httplib#default-thread-pool-support) in README helps you.
