### ISSUE TITLE
Does  it support some link that must to be authorized?

### ISSUE THREAD

**Issue by sparrowyang** [yhirose/cpp-httplib#1354]
when I use httplib::Client to request some host，such as "http:://user:password@host:port/path"，I faild。Does  it support?

**Comment by PixlRainbow** [comment]
Duplicate of #1265 
Embedding the username and password in the URL is not supported. However, you can achieve the same functionality with `set_basic_auth`.

When you write the url `http:://user:password@host:port/path` into a web browser, the web browser actually converts it into a request to `http://host:port/path` with header `Authorization: Basic dXNlcjpwYXNzd29yZA==` where the string "user:password" is encoded with base64. The `set_basic_auth` function will generate this header.

**Comment by sparrowyang** [comment]
thanks
