### ISSUE TITLE
how to compress data via gzip and respone to client

### ISSUE THREAD

**Issue by raviruia522** [yhirose/cpp-httplib#1358]
i tried last 2 days but cant compress data from server, please help me
i tried but no success
data is sent but not compressed
`svr.set_pre_routing_handler([](const auto& req, auto& res)`
`{`
 `   if (req.path == "/servertime")`
`    {`
`         res.set_content("{\"success\":\"1660358340\"}", "gzip");`
`         return Server::HandlerResponse::Handled;`
`    }`
`}`

**Comment by PixlRainbow** [comment]
to enable response compression, several criteria must be met
1. compression support must be enabled and the respective supporting libraries must be linked
2. **the client must explicitly declare that it supports compression** by sending the `Accept-Encoding` request header with the values `gzip`, `deflate` or `br`

The server will then automatically enable compression on the response body.

Note that the second parameter of `set_content` is meant to be the mimetype/file type of the response. It is only meant to suggest to the client on how to parse the response, and does not affect how the response data is processed on the server side. Therefore setting it to `gzip` is invalid unless you intend the response to be a `.tar.gz` file. In your case, it should be `res.set_content("{\"success\":\"1660358340\"}", "application/json");`


<details>
  <summary><i>General notes about HTTP (click for details)</i></summary>
  <p>Another thing to note is that the standard HTTP protocol treats body compression as a form of "encoding". It is designed to assume that gzip is an extra protocol layer that sits on top of HTTP, not the type of the file being transferred. The payload may be some other data like <code>application/json</code> or <code>text/html</code>, and gzip is merely providing a communication channel through which that data may be transmitted.</p>
  <p>The fact that the gzip encoding is <i>actually</i> being used to compress the data and speed up transmission is beyond the design scope of HTTP. That is why the <code>Content-Type</code> header is not used to indicate compression type.</p>
</details>

**Comment by raviruia522** [comment]
thank you very much. it good
