### ISSUE TITLE
cookie callback

### ISSUE THREAD

**Issue by Sugar0612** [yhirose/cpp-httplib#1359]
Before httplib::client sends a Get request, I want to add a cookie, where should I add it? header? Or where?

**Comment by yhirose** [comment]
You can use `set_header` and set the key to `Set-Cookie`.

**Comment by Sugar0612** [comment]
> You can use `set_header` and set the key to `Set-Cookie`.

Thanks! But I still have some doubts, is there a cli.set_header function? Or should I define a httplib::header hdr;, and then hdr["Set-Cookie"] = cookie?

**Comment by yhirose** [comment]
Sorry about that. You could do it in the following way. 
https://github.com/yhirose/cpp-httplib#get-with-http-headers

```cpp
httplib::Headers headers = {
  { "Set-Cookie", "[prepare your cookie value...]" }
};
auto res = cli.Get("/hi", headers);
```

**Comment by Sugar0612** [comment]
> Sorry about that. You could do it in the following way. https://github.com/yhirose/cpp-httplib#get-with-http-headers
> 
> ```c++
> httplib::Headers headers = {
>   { "Set-Cookie", "[prepare your cookie value...]" }
> };
> auto res = cli.Get("/hi", headers);
> ```

I really, really appreciate your patient answer! Thank you so much, I got it this time! Thank you so much!!!! Words go beyond words!
