### ISSUE TITLE
Multiple Content-Lentgh headers

### ISSUE THREAD

**Issue by duckbill007** [yhirose/cpp-httplib#136]
When you setting Content-Length header before sending request, you should remove any previous value. If not, you can potentially have multiple Content-Length headers in response, which is not accepted by browsers.

**Comment by yhirose** [comment]
@duckbill007, thanks for the feedback. Could you explain more about the issue?

**Comment by duckbill007** [comment]
For example if I create reverse proxy and pass all headers from one response to another there will be two Content-Length header. One from original response and another added by cpp-httplib.

Also, if I by some reason manually add header Content-Length, there will be two of them.
