### ISSUE TITLE
client.enable_server_certificate_verification(true) 返回error: SSLServerVerification (10)

### ISSUE THREAD

**Issue by allen20200111** [yhirose/cpp-httplib#1360]
1、平台：
操作系统：centos 7
cpu:  Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
g++：8.3.1
C++：17
SSL： 1.1.1
2、实验：
curl -o 1.jpg https://pic1.zhimg.com/v2-c897d1dc759c9d7ee7be5ad75f68c62a_xl.jpg，得到结果正常。

**Comment by PixlRainbow** [comment]
Note: you did not specify what httplib code you used.
If you require certificate verification of general websites, you may need to install `ca-certificates` package first to obtain "well-known" public certificates. (for example, using `yum install -y ca-certificates`)
If you require certificate verification only for a specific website, you can download the Certificate Authority root bundle of the target website and use `set_ca_cert_path` to point to the bundle file.

**Comment by yhirose** [comment]
Hope the @PixlRainbow comment helps.

**Comment by PixlRainbow** [comment]
You still have to use openssl. Httplib does not know how to decode the encryption used by https websites; it depends on openssl to perform this feature.

**Comment by cngege** [comment]
> You still have to use openssl. Httplib does not know how to decode the content encryption used by https websites; it depends on openssl to perform this feature.

### You can't comment at this time.

**Comment by PixlRainbow** [comment]
If a website offers an unencrypted http version directly, you can just use httplib as-is. If the website you want strictly enforces encrypted https, you have to use a third party's TLS termination proxy. Examples include `stunnel` or nginx, though there are others. The proxy will decode the encryption so that your application sees a normal http stream instead of a https one.

**Comment by cngege** [comment]
> If a website offers an unencrypted http version directly, you can just use httplib as-is. If the website you want strictly enforces encrypted https, you have to use a third party's TLS termination proxy. Examples include `stunnel` or nginx, though there are others. The proxy will decode the encryption so that your application sees a normal http stream instead of a https one.

Thank you for the offer
