### ISSUE TITLE
is it possible to somehow execute any c++ code after svr.listen

### ISSUE THREAD

**Issue by tgcallsproject** [yhirose/cpp-httplib#1366]
is it possible to somehow execute any c++ code after `svr.listen("0.0.0.0", 1234);`

i found somethink like this

https://github.com/yhirose/cpp-httplib/issues/1186

If i put cpp-httplib it in a separate thread - will it help

**Comment by yhirose** [comment]
> If i put cpp-httplib it in a separate thread - will it help
Yes.
