### ISSUE TITLE
sha_256 & sha_512 marked DEPRECATED in openssl v3

### ISSUE THREAD

**Issue by hippymulehead** [yhirose/cpp-httplib#1368]
/usr/include/openssl/sha.h:126:27: note: declared here
126 | OSSL_DEPRECATEDIN_3_0 int SHA512_Final(unsigned char *md, SHA512_CTX *c);

**Comment by yhirose** [comment]
@hippymulehead, thanks for the feedback, but I didn't get any such a warning...

```
~/cpp-httplib/test$ make test
clang++ -o test -I.. -g -std=c++11 -I. -Wall -Wextra -Wtype-limits -Wconversion -Wshadow  test.cc include_httplib.cc gtest/gtest-all.cc gtest/gtest_main.cc -DCPPHTTPLIB_OPENSSL_SUPPORT -I/opt/homebrew/opt/openssl@3/include -L/opt/homebrew/opt/openssl@3/lib -lssl -lcrypto -DCPPHTTPLIB_ZLIB_SUPPORT -lz -DCPPHTTPLIB_BROTLI_SUPPORT -I/opt/homebrew/opt/brotli/include -L/opt/homebrew/opt/brotli/lib -lbrotlicommon -lbrotlienc -lbrotlidec -pthread

~/cpp-httplib/test$
```

**Comment by hippymulehead** [comment]
I think the homebrew version is behind.  Please see...

https://github.com/openssl/openssl/blob/master/include/openssl/sha.h

It's marked.

Just trying to give a heads up.  Really nice lib BTW!

Michael Romans
