### ISSUE TITLE
sha_256 & 512

### ISSUE THREAD

**Issue by hippymulehead** [yhirose/cpp-httplib#1369]
I think the homebrew version is behind.  Please see...

https://github.com/openssl/openssl/blob/master/include/openssl/sha.h

It's marked.

Just trying to give a heads up.  Really nice lib BTW!

**Comment by yhirose** [comment]
What warnings did you get and which OpenSSL functions are you talking about? I don't get any warning when building with httplib.h. Thanks.

```
$ brew info openssl
==> openssl@3: stable 3.0.5 (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/opt/homebrew/Cellar/openssl@3/3.0.5 (6,444 files, 27.9MB)
  Poured from bottle on 2022-07-07 at 06:44:55
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@3.rb
License: Apache-2.0
```

**Comment by PixlRainbow** [comment]
From this person's other issue:
https://github.com/yhirose/cpp-httplib/issues/1368#issuecomment-1227583810
Apparently they say the fork of OpenSSL hosted on Homebrew's github does not yet contain the updates from upstream master

**Comment by yhirose** [comment]
@hippymulehead, @PixlRainbow, Here is the comment in #1368, but I don't understand what it means because httplib.h doesn't use `SHA512_Final`. Please let me know more detial.

> /usr/include/openssl/sha.h:126:27: note: declared here
126 | OSSL_DEPRECATEDIN_3_0 int SHA512_Final(unsigned char *md, SHA512_CTX *c);

**Comment by hippymulehead** [comment]
Yes, that was my point.  I got dep warnings when compiling httplib on
Ubuntu and that does include the changes from upstream master.  I was
just rtying to give you a heads up that sha_256 & 512 are going away
becaus they are no longer considered secure.

For refrence...

/home/mromans/bin/clion/bin/cmake/linux/bin/cmake --build
/home/mromans/Programming/EZTools/ez/cmake-build-debug --target ez -j 9
[1/2] Building CXX object CMakeFiles/ez.dir/src/main.cpp.o
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h: In
function ‘std::string httplib::detail::MD5(const string&)’:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4044:37:
warning: ‘int MD5_Init(MD5_CTX*)’ is deprecated: Since OpenSSL 3.0 [-
Wdeprecated-declarations]
4044 | return message_digest<MD5_CTX>(s, MD5_Init, MD5_Update,
MD5_Final,
| ^~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:217,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/md5.h:49:27: note: declared here
49 | OSSL_DEPRECATEDIN_3_0 int MD5_Init(MD5_CTX *c);
| ^~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4044:47:
warning: ‘int MD5_Update(MD5_CTX*, const void*, size_t)’ is deprecated:
Since OpenSSL 3.0 [-Wdeprecated-declarations]
4044 | return message_digest<MD5_CTX>(s, MD5_Init, MD5_Update,
MD5_Final,
| ^~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:217,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/md5.h:50:27: note: declared here
50 | OSSL_DEPRECATEDIN_3_0 int MD5_Update(MD5_CTX *c, const void *data,
size_t len);
| ^~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4044:59:
warning: ‘int MD5_Final(unsigned char*, MD5_CTX*)’ is deprecated: Since
OpenSSL 3.0 [-Wdeprecated-declarations]
4044 | return message_digest<MD5_CTX>(s, MD5_Init, MD5_Update,
MD5_Final,
| ^~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:217,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/md5.h:51:27: note: declared here
51 | OSSL_DEPRECATEDIN_3_0 int MD5_Final(unsigned char *md, MD5_CTX
*c);
| ^~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4044:33:
warning: ‘int MD5_Init(MD5_CTX*)’ is deprecated: Since OpenSSL 3.0 [-
Wdeprecated-declarations]
4044 | return message_digest<MD5_CTX>(s, MD5_Init, MD5_Update,
MD5_Final,
| ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4045 | MD5_DIGEST_LENGTH);
| ~~~~~~~~~~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:217,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/md5.h:49:27: note: declared here
49 | OSSL_DEPRECATEDIN_3_0 int MD5_Init(MD5_CTX *c);
| ^~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4044:33:
warning: ‘int MD5_Update(MD5_CTX*, const void*, size_t)’ is deprecated:
Since OpenSSL 3.0 [-Wdeprecated-declarations]
4044 | return message_digest<MD5_CTX>(s, MD5_Init, MD5_Update,
MD5_Final,
| ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4045 | MD5_DIGEST_LENGTH);
| ~~~~~~~~~~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:217,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/md5.h:50:27: note: declared here
50 | OSSL_DEPRECATEDIN_3_0 int MD5_Update(MD5_CTX *c, const void *data,
size_t len);
| ^~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4044:33:
warning: ‘int MD5_Final(unsigned char*, MD5_CTX*)’ is deprecated: Since
OpenSSL 3.0 [-Wdeprecated-declarations]
4044 | return message_digest<MD5_CTX>(s, MD5_Init, MD5_Update,
MD5_Final,
| ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4045 | MD5_DIGEST_LENGTH);
| ~~~~~~~~~~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:217,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/md5.h:51:27: note: declared here
51 | OSSL_DEPRECATEDIN_3_0 int MD5_Final(unsigned char *md, MD5_CTX
*c);
| ^~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h: In
function ‘std::string httplib::detail::SHA_256(const string&)’:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4049:40:
warning: ‘int SHA256_Init(SHA256_CTX*)’ is deprecated: Since OpenSSL
3.0 [-Wdeprecated-declarations]
4049 | return message_digest<SHA256_CTX>(s, SHA256_Init, SHA256_Update,
SHA256_Final,
| ^~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
from /usr/include/openssl/ssl.h:31,
from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:218,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/sha.h:73:27: note: declared here
73 | OSSL_DEPRECATEDIN_3_0 int SHA256_Init(SHA256_CTX *c);
| ^~~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4049:53:
warning: ‘int SHA256_Update(SHA256_CTX*, const void*, size_t)’ is
deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
4049 | return message_digest<SHA256_CTX>(s, SHA256_Init, SHA256_Update,
SHA256_Final,
| ^~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
from /usr/include/openssl/ssl.h:31,
from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:218,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/sha.h:74:27: note: declared here
74 | OSSL_DEPRECATEDIN_3_0 int SHA256_Update(SHA256_CTX *c,
| ^~~~~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4049:68:
warning: ‘int SHA256_Final(unsigned char*, SHA256_CTX*)’ is deprecated:
Since OpenSSL 3.0 [-Wdeprecated-declarations]
4049 | return message_digest<SHA256_CTX>(s, SHA256_Init, SHA256_Update,
SHA256_Final,
| ^~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
from /usr/include/openssl/ssl.h:31,
from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:218,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/sha.h:76:27: note: declared here
76 | OSSL_DEPRECATEDIN_3_0 int SHA256_Final(unsigned char *md,
SHA256_CTX *c);
| ^~~~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4049:36:
warning: ‘int SHA256_Init(SHA256_CTX*)’ is deprecated: Since OpenSSL
3.0 [-Wdeprecated-declarations]
4049 | return message_digest<SHA256_CTX>(s, SHA256_Init, SHA256_Update,
SHA256_Final,
|
~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4050 | SHA256_DIGEST_LENGTH);
| ~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
from /usr/include/openssl/ssl.h:31,
from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:218,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/sha.h:73:27: note: declared here
73 | OSSL_DEPRECATEDIN_3_0 int SHA256_Init(SHA256_CTX *c);
| ^~~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4049:36:
warning: ‘int SHA256_Update(SHA256_CTX*, const void*, size_t)’ is
deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
4049 | return message_digest<SHA256_CTX>(s, SHA256_Init, SHA256_Update,
SHA256_Final,
|
~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4050 | SHA256_DIGEST_LENGTH);
| ~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
from /usr/include/openssl/ssl.h:31,
from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:218,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/sha.h:74:27: note: declared here
74 | OSSL_DEPRECATEDIN_3_0 int SHA256_Update(SHA256_CTX *c,
| ^~~~~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4049:36:
warning: ‘int SHA256_Final(unsigned char*, SHA256_CTX*)’ is deprecated:
Since OpenSSL 3.0 [-Wdeprecated-declarations]
4049 | return message_digest<SHA256_CTX>(s, SHA256_Init, SHA256_Update,
SHA256_Final,
|
~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4050 | SHA256_DIGEST_LENGTH);
| ~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
from /usr/include/openssl/ssl.h:31,
from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:218,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/sha.h:76:27: note: declared here
76 | OSSL_DEPRECATEDIN_3_0 int SHA256_Final(unsigned char *md,
SHA256_CTX *c);
| ^~~~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h: In
function ‘std::string httplib::detail::SHA_512(const string&)’:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4054:40:
warning: ‘int SHA512_Init(SHA512_CTX*)’ is deprecated: Since OpenSSL
3.0 [-Wdeprecated-declarations]
4054 | return message_digest<SHA512_CTX>(s, SHA512_Init, SHA512_Update,
SHA512_Final,
| ^~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
from /usr/include/openssl/ssl.h:31,
from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:218,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/sha.h:123:27: note: declared here
123 | OSSL_DEPRECATEDIN_3_0 int SHA512_Init(SHA512_CTX *c);
| ^~~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4054:53:
warning: ‘int SHA512_Update(SHA512_CTX*, const void*, size_t)’ is
deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
4054 | return message_digest<SHA512_CTX>(s, SHA512_Init, SHA512_Update,
SHA512_Final,
| ^~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
from /usr/include/openssl/ssl.h:31,
from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:218,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/sha.h:124:27: note: declared here
124 | OSSL_DEPRECATEDIN_3_0 int SHA512_Update(SHA512_CTX *c,
| ^~~~~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4054:68:
warning: ‘int SHA512_Final(unsigned char*, SHA512_CTX*)’ is deprecated:
Since OpenSSL 3.0 [-Wdeprecated-declarations]
4054 | return message_digest<SHA512_CTX>(s, SHA512_Init, SHA512_Update,
SHA512_Final,
| ^~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
from /usr/include/openssl/ssl.h:31,
from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:218,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/sha.h:126:27: note: declared here
126 | OSSL_DEPRECATEDIN_3_0 int SHA512_Final(unsigned char *md,
SHA512_CTX *c);
| ^~~~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4054:36:
warning: ‘int SHA512_Init(SHA512_CTX*)’ is deprecated: Since OpenSSL
3.0 [-Wdeprecated-declarations]
4054 | return message_digest<SHA512_CTX>(s, SHA512_Init, SHA512_Update,
SHA512_Final,
|
~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4055 | SHA512_DIGEST_LENGTH);
| ~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
from /usr/include/openssl/ssl.h:31,
from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:218,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/sha.h:123:27: note: declared here
123 | OSSL_DEPRECATEDIN_3_0 int SHA512_Init(SHA512_CTX *c);
| ^~~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4054:36:
warning: ‘int SHA512_Update(SHA512_CTX*, const void*, size_t)’ is
deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
4054 | return message_digest<SHA512_CTX>(s, SHA512_Init, SHA512_Update,
SHA512_Final,
|
~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4055 | SHA512_DIGEST_LENGTH);
| ~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
from /usr/include/openssl/ssl.h:31,
from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:218,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/sha.h:124:27: note: declared here
124 | OSSL_DEPRECATEDIN_3_0 int SHA512_Update(SHA512_CTX *c,
| ^~~~~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:4054:36:
warning: ‘int SHA512_Final(unsigned char*, SHA512_CTX*)’ is deprecated:
Since OpenSSL 3.0 [-Wdeprecated-declarations]
4054 | return message_digest<SHA512_CTX>(s, SHA512_Init, SHA512_Update,
SHA512_Final,
|
~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4055 | SHA512_DIGEST_LENGTH);
| ~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
from /usr/include/openssl/ssl.h:31,
from
/home/mromans/Programming/EZTools/ez/src/../testcode/httplib.h:218,
from /home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:8,
from /home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/usr/include/openssl/sha.h:126:27: note: declared here
126 | OSSL_DEPRECATEDIN_3_0 int SHA512_Final(unsigned char *md,
SHA512_CTX *c);
| ^~~~~~~~~~~~
In file included from
/home/mromans/Programming/EZTools/ez/src/main.cpp:12:
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h: In
function ‘EZTools::EZString
httptest::httpErrorAsString(httplib::Error)’:
/home/mromans/Programming/EZTools/ez/src/../testcode/httptest.h:44:5:
warning: control reaches end of non-void function [-Wreturn-type]
44 | }
| ^
[2/2] Linking CXX executable ez

Build finished

On Fri, 2022-08-26 at 00:28 -0700, Leow Yong Zheng wrote:
> From this person's other issue:
> #1368 (comment)
> Apparently they say the fork of OpenSSL hosted on Homebrew's github
> does not yet contain the updates from upstream master
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

**Comment by yhirose** [comment]
@hippymulehead it seems like you are using the very old version of httplib.h. This problem has already been fixed at https://github.com/yhirose/cpp-httplib/pull/1241. Could you make sure that the latest version ([v0.11.1](https://github.com/yhirose/cpp-httplib/tree/v0.11.1)) is used in your project?

**Comment by yhirose** [comment]
any response?
