### ISSUE TITLE
Logger receives empty Request if https is used on http server.

### ISSUE THREAD

**Issue by karlisolte** [yhirose/cpp-httplib#1374]
If I try to access http server with https protocol the logger registered with set_logger on server:
* ~~is invoked not once, but 12(!) times. (With `#define CPPHTTPLIB_THREAD_POOL_COUNT 1` it seems to be 8 times.)~~
* Parameter Request is empty (request.remote_addr and others are empty). I want to know who tired to access server and log it. Edit: I now understood why most fields are empty (like path as server never receives that information), but remote_addr should be possible to include?!

Also with this code:
```
    server.Get("/foo", [this](auto& request, auto& response) {
        LOG("handling request");
    });
    server.set_logger([this](auto& request, auto& response) {
        LOG("received request");
    });
```
The "handling request" gets logged before "received request". At least in my case that is not convenient.

**Comment by karlisolte** [comment]
It was invoked several times because browser apparently did several requests. With `curl` it is invoked just once. The other 2 questions however remain.

**Comment by yhirose** [comment]
What does it mean `Edit: I now understood why most fields are empty (like path as server never receives that information), but remote_addr should be possible to include?`. Could you provide more detail?

**Comment by karlisolte** [comment]
As per my understanding when client tries to access server using https it first tries to set up TLS and only then sends the actual HTTP request. If that fails server will never know what was client's requests hence it makes sense why HTTP related fields in Request are empty when logger callback gets invoked.

Server on the other hand should know what was remote_addr and remote_port that tried to set up TLS and failed and it would be useful to include this information in Request parameter if possible.

**Comment by yhirose** [comment]
Same as #870
