### ISSUE TITLE
gzip encoding

### ISSUE THREAD

**Issue by hippymulehead** [yhirose/cpp-httplib#1375]
When I run the following...

stringstream vn;
    vn << "EZTools v" << VERSION << ", myemail@mydomain.com";
    httplib::Headers headers = {
            {"User-Agent",vn.str()},
            {"Accept", "application/geo+json"},
            { "Accept-Encoding", "gzip" }
    };
    httplib::Client cli("https://api.weather.gov");
    cli.set_default_headers(headers);
    if (auto res = cli.Get("/stations/KLNK/observations?limit=1")) {
        cout << res->status << endl;
        cout << res->get_header_value("Content-Type") << endl;
        cout << res->body << endl;
    } else {
        cout << httplib::to_string(res.error()) << endl;
    }

It returns a read error.

If I remove gzip encoding, it works.  Like...
stringstream vn;
    vn << "EZTools v" << VERSION << ", myemail@mydomain.com";
    httplib::Headers headers = {
            {"User-Agent",vn.str()},
            {"Accept", "application/geo+json"}
    };
    httplib::Client cli("https://api.weather.gov");
    cli.set_default_headers(headers);
    if (auto res = cli.Get("/stations/KLNK/observations?limit=1")) {
        cout << res->status << endl;
        cout << res->get_header_value("Content-Type") << endl;
        cout << res->body << endl;
    } else {
        cout << httplib::to_string(res.error()) << endl;
    }

I found this because of NWS wanting everything to use gzip encoding.  This is with #define CPPHTTPLIB_VERSION "0.11.1"

**Comment by yhirose** [comment]
Could you test with curl on your machine to see if curl can handle the request with `Accept-Encoding: gzip`?

**Comment by hippymulehead** [comment]
It can amd does every 5 minutes as part of my weather software I wrote
to collect data from the API in the example.

**Comment by yhirose** [comment]
What does 'amd' stand for?

**Comment by hippymulehead** [comment]
Typo "and"  It can and does.

**Comment by hippymulehead** [comment]
This is from your documentation...

cli.set_default_headers({
  { "Accept-Encoding", "gzip, deflate" }
});
auto res = cli.Get("/hi");

**Comment by hippymulehead** [comment]
Please disregard.  NWS Doesn't use gzip but Weather Underground does.  My apologies.
