### ISSUE TITLE
[bcc32c Error] httplib.h(1972): use of undeclared identifier '_access_s'

### ISSUE THREAD

**Issue by Teruhashi12** [yhirose/cpp-httplib#1376]
when im build the source with rad studio i got error [bcc32c Error] httplib.h(1972): use of undeclared identifier '_access_s'
but when i build in visual studio im not got this error..
why??
![Screenshot (160)](https://user-images.githubusercontent.com/90950171/187231972-bde92d33-1000-4fd2-80a0-d2fdb2636479.png)

**Comment by yhirose** [comment]
Sorry, but I am not planning to support RAD Studio.

**Comment by yecate** [comment]
It may be because your project has an io.h header file
You can try to modify httplib.h file  #include <io.h> to #include <corecrt_io.h>

**Comment by Teruhashi12** [comment]
> 

it says the corecrt_io.h not found
![Screenshot (174)](https://user-images.githubusercontent.com/90950171/190884059-c78fec4a-ea57-46fc-a327-f9236d7e2f9b.png)

**Comment by Teruhashi12** [comment]
> It may be because your project has an io.h header file
> You can try to modify httplib.h file  #include <io.h> to #include <corecrt_io.h>

I done include openssl and lib too
