### ISSUE TITLE
Error importing httplib.h

### ISSUE THREAD

**Issue by StoicaNicusor** [yhirose/cpp-httplib#138]
I am using VS Community 2017, after adding the header file I get this error :
[http://prntscr.com/n5k8km](http://prntscr.com/n5k8kml)
If i put httplib.h in ` C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include` it just works.
What am I doing wrong ? Thanks in advance.

**Comment by DJuego** [comment]
Hmmm it seems that "the screenshot was removed", @StoicaNicusor .

DJuego

**Comment by yhirose** [comment]
@StoicaNicusor, I don't see the screenshot either.

**Comment by StoicaNicusor** [comment]
Sorry,got deleted. It says it can not import httplib.h

**Comment by yhirose** [comment]
@StoicaNicusor, is it a compile error, or a link error? If it's a compile error, you have to setup the include directory setting properly.
