### ISSUE TITLE
How to test web based functionalities without server

### ISSUE THREAD

**Issue by bialasjaroslaw** [yhirose/cpp-httplib#1381]
I want to test some behavior in my application. Under the hood `cpp-httplib` is used for network communication. I can not use local server for that. In some other libraries/frameworks I have been using in the past, there was a way to inject `NetworkAccessManager` or some other object that allowed to override some functions responsible for sending requests. That way I was able to provide predefined content for endpoints I was using in my application. 
I thought that I can extend `ClientImpl` but I am not sure if overriding`create_and_connect_socket` and `process_socket` was intended way to do that. Moreover `ClientImpl` is a private member, so that is not doable. Is it anything I can do except wrapping `httplib::Client` and providing my own interface?

**Comment by yhirose** [comment]
@bialasjaroslaw, thanks for the feedback, but I still quite don't understand what you are trying to do... Could you explain more clearly? Also could you provide the code that you tried so far? I can't give you any promise to implement it, but at least I would like to understand the situate that you face. Thanks!

**Comment by bialasjaroslaw** [comment]
I want to test my code in separation (without remote server). Something like code below (except inheriting from `httplib::Client` does not make sense in this case)

```c++
class Worker{
public:
  Worker(httplib::Client* client) : _client(client) {}
  void run(){
    httplib::Client client("http://example.com");
    client->Get("/resource");
  }
private:
	httplib::Client* _client;
}

class MockClient : public httplib::Client{
...
};

void run(){
	Worker(new httplib::Client).run(); // requests GET http://example.com/resource
}

bool resourceEndpoint(httplib::Response& response){
	response.status = 200;
	return true;
}

void test(){
	auto routing = Routing({{"GET", "/resource", resourceEndpoint}});
	Worker(new MockClient(routing)).run(); // use resourceEndpoint to handle request
}
```

**Comment by yhirose** [comment]
@bialasjaroslaw, thanks for the detail. cpp-httplib client API design basically doesn't allow users to override it and enhance it. It should be used as it is.
