### ISSUE TITLE
using post method with json body error

### ISSUE THREAD

**Issue by fsxss** [yhirose/cpp-httplib#1384]
I want to use post method with json body to post ,but it do not work。how to make it work？
Many thanks in advanced, 

`#include "./httplib.h"
#include <iostream>
#include <string>

using namespace httplib;

int main(void)
{
    httplib::Client cli("http://125.25.21.23:8887");

    httplib::Headers headers = {
        { "Content-Type", "application/json" }
    };

    std::string postJson = "{ \"task_id\":\"WO20220905025\", \"hg_names\":\"test_e1\"}";

    if(auto res = cli.Post("/test/api/task!create.action",headers, postJson, "application/json")) {
		std::cout << res->status << std::endl;
		std::cout << res->get_header_value("Content-Type") << std::endl;
		std::cout << res->body << std::endl; 
    }
    else 
        std::cout << res.error() << std::endl;
    
    return 0;
}`

return message：
200
text/html;charset=UTF-8
{"Code":-1}

![微信图片_20220905160020](https://user-images.githubusercontent.com/20676299/188398961-864e2c4f-6ef6-44ed-8ed4-e54492a029ea.jpg)

**Comment by PixlRainbow** [comment]
You used different JSON structure in the postman request
in your C++ request:
```json
{
  "task_id": "WO20220905025",
  "hg_names": "test_e1" // string
}
```
in your postman request
```json
{
  "task_id": "WO20220905025",
  "hg_names": [
    "test_e1" // array of string
  ]
}
```

**Comment by fsxss** [comment]
@PixlRainbow thank you very much, I modify my json string to 
 std::string postJson = "{\"task_id\":\"WO202209021603\", \"hg_names\":[\"test_e1\"]}";
 it can work now. thank you!
