### ISSUE TITLE
Sending data is different from receiving data

### ISSUE THREAD

**Issue by chen-github1** [yhirose/cpp-httplib#1386]
cpp-httplib,When the transmission data has @ characters,Sending data is different from receiving data.
for example,Send
{
	"videoUrl": "rtsp://admin:admin@192.168.1.1/stream1",
	"responseUrl": "http://192.168.1.2/data"
} 
but receive 
{
	"videoUrl": "rtsp://admin:admin@192.168.1.1/stream1",
	"responseUrl": "http:/192.168.1.2/data"
}

**Comment by yhirose** [comment]
@chen-github1, could you provide the smallest possible code example which reproduces the problem? Thanks!

**Comment by chen-github1** [comment]
#include <iostream>
#include "httplib.h"

int main() {
    // HTTP
    httplib::Server svr;

    svr.Post("/data", [](const httplib::Request &req, httplib::Response &res) {
        std::cout << "接收数据： " << req.body.c_str() << std::endl;
        res.set_content("{\"result\": \"ok\"}", "application/json");
    });

    svr.listen("0.0.0.0", 8080);
}

**Comment by yhirose** [comment]
Could you show your client code as well?

**Comment by chen-github1** [comment]
The apipost tool I use

**Comment by yhirose** [comment]
I don't think it's a problem on cpp-httplib. Could you make sure that your API post tool really sends a correct payload? For now, I'll close it. Thanks for your understanding!

**Comment by chen-github1** [comment]
Could you test the JSON data I sent? Thank you
