### ISSUE TITLE
Missing httplib::SSLClient enable_server_certificate_verification method on httplib::Client

### ISSUE THREAD

**Issue by bartols** [yhirose/cpp-httplib#1390]
I'd like to use the universal interface constructors to have an agnostic http client since I cannot predict what url will be configured. In case on an HTTPS I'd like to use "enable_server_certificate_verification" method but is missing. That mehtod is present only in SSLClient.
I'd like construct always the same class and configure for secure/unsecure connection.
From my point of view would be possible if:
- exist only httplib::Client class and is fully configuranle
- or httplib::Client and httplib::SSLClient derive from an interface and we can use them using polymorphism

**Comment by yhirose** [comment]
@bartols, `enable_server_certificate_verification` already exists in `httplib::Client` as below.
https://github.com/yhirose/cpp-httplib/blob/b57f79f43882bbc0268999647890bd621bd22c94/httplib.h#L1063-L1065

**Comment by bartols** [comment]
Oh my God what a stupid I am, I havent enabled the ssl define
Sorry
