### ISSUE TITLE
Good way to go from http::Error to string?

### ISSUE THREAD

**Issue by Docteh** [yhirose/cpp-httplib#1395]
Is there a good way to go from the Error enum over to a string?

I did some internet searching, and I guess I could add something like the following to my program, but then it can be out of date. 

```cpp
static const char *ErrorLookup[] =
{ "Success", "Unknown", "Connection", 
   "BindIPAddress", 
   "Read", 
   "Write", 
   "ExceedRedirectCount", 
   "Canceled", 
   "SSLConnection", 
   "SSLLoadingCerts", 
   "SSLServerVerification", 
   "UnsupportedMultipartBoundaryChars", 
   "Compression", 
   "ConnectionTimeout" };
```

Maybe something similar could be added to httplib.h?

**Comment by PixlRainbow** [comment]
there is a `httplib::to_string` method that accepts a `httplib::Error` object and returns a string. But you can also use the `<<` operator to print the error to terminal.
