### ISSUE TITLE
httplib::ClientImpl::stop works perfectly on Linux but not on Windows

### ISSUE THREAD

**Issue by fronald** [yhirose/cpp-httplib#1396]
When calling the `stop` method of the `httplib::ClientImpl` class on Windows, the request is not aborted immediately. Debugging, I verified that winsock2's shutdown method returns -1 and therefore httplib does not cancel the request.

Any idea?

Environment:

Windows 10 - 20H2
MSYS2 - CLang 15.0.1
Flags: CPPHTTPLIB_ZLIB_SUPPORT and CPPHTTPLIB_OPENSSL_SUPPORT

**Comment by yhirose** [comment]
@fronald, thanks for the feedback. Could you run the unit test suite to see if all the test cases including the `stop()` pass? 

```bash
cd test && make
```

By the way,  I officially support and tested the library only with the latest Visual Studio on Windows described in README.
https://github.com/yhirose/cpp-httplib#windows

**Comment by fronald** [comment]
All tests passed. But I think the behavior I'm referring to is not being tested. I can create a punctual example to send you.

![image](https://user-images.githubusercontent.com/580752/194340166-b6895e89-dec8-48cb-8908-ea298a08927c.png)

But anyway, I'm not implementing the callback to cancel the request today, I'm just calling the stop. On Linux the stop is stopping immediately, regardless of whether or not it has a callback.
But it could be that I'm using it wrong, relying only on the stop method.

I'll try to implement the callback, if the error persists I'll send you a standalone test, and we can solve it together.

**Comment by yhirose** [comment]
I'll close it for now until I receive further information.

**Comment by usernolan** [comment]
I am running into a similar behavior: `Client::stop()` works perfectly/immediately on Linux, but hangs on Windows. This is on the latest version of the library.

@fronald Did you ever resolve this?
