### ISSUE TITLE
the read buf are not cleared

### ISSUE THREAD

**Issue by chisheng** [yhirose/cpp-httplib#1398]
inline bool read_content_without_length(Stream &strm,
                                        ContentReceiverWithProgress out) {
  char buf[CPPHTTPLIB_RECV_BUFSIZ];
  uint64_t r = 0;
  for (;;) {
    auto n = strm.read(buf, CPPHTTPLIB_RECV_BUFSIZ);// **the read buf are not cleared befor read data from socket**
    if (n < 0) {
      return false;
    } else if (n == 0) {
      return true;
    }

    if (!out(buf, static_cast<size_t>(n), r, 0)) { return false; }
    r += static_cast<uint64_t>(n);
  }

  return true;
}

**Comment by yhirose** [comment]
What did you try to say? Just curious... :)
