### ISSUE TITLE
Crash on Clang 7 & Clang 8 on long URLs

### ISSUE THREAD

**Issue by sjk7** [yhirose/cpp-httplib#140]
Hello,
Great library, but consistently crashes during test:
TEST_F(ServerTest, LongQueryValue)
On ubuntu 18.04.
GCC works fine but Clang 7 or 8 (64-bit) both crash. It looks to be a forever recursive call to something deep in the bowels of regex. I will try to attach a screenie of the issue live in QtCreator (but note it crashes just the same from /test/make)
![crashed](https://user-images.githubusercontent.com/24289173/55841513-5afea200-5b27-11e9-81c9-8ed3b709a8f2.png)

**Comment by sjk7** [comment]
There is always this:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.15
It seems to be OK to refuse URLS that are greater than 8k at most. Possible workaround?
return 414 Request-URI Too Long ??

"

    Note: Servers ought to be cautious about depending on URI lengths above 255 bytes, because some older client or proxy implementations might not properly support these lengths.

The limit is in MSIE and Safari about 2KB, in Opera about 4KB and in Firefox about 8KB. We may thus assume that 8KB is the maximum possible length and that 2KB is a more affordable length to rely on at the server side and that 255 bytes is the safest length to assume that the entire URL will come in."

Source: https://stackoverflow.com/questions/2659952/maximum-length-of-http-get-request

**Comment by yhirose** [comment]
@sjk7, thanks for the bug report. It crashed at the line 1647, right? 

```cpp
    if (std::regex_match(s, m, re)) {
```

Your suggestion (return 414) sounds good to me. I am thinking to introduce something like the following, so that  users can control the value.

```cpp
#define CPPHTTPLIB_REQUEST_URI_MAXIMUM_LENGTH 8192
```

**Comment by sjk7** [comment]
Correct, yes

**Comment by yhirose** [comment]
@sjk7, I implemented it. Thanks for your contribution.
