### ISSUE TITLE
[Question] https client works without setting CPPHTTPLIB_OPENSSL_SUPPORT and linking openssl

### ISSUE THREAD

**Issue by hn-sl** [yhirose/cpp-httplib#1403]
Sending Post request to ```https://httpbin.org/post``` works without enabling and linking openssl. Is this expected?

/src/main.cpp

```c++
//#define CPPHTTPLIB_OPENSSL_SUPPORT
#include <iostream>
#include <httplib.h>

int main() {
    httplib::Client cli("https://httpbin.org");
    auto res = cli.Post("/post", "my data", "text/plain");
    auto status = res -> status;
    auto b = res -> body;

    std::cout << status << std::endl;
    std::cout << b << std::endl;
    return 0;
}
```
/CmakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.23)
project(some_test)

add_subdirectory(cpp-httplib)
set(CMAKE_CXX_STANDARD 17)

add_executable(some_test src/main.cpp)
target_link_libraries(some_test httplib::httplib)
```

/cpp-httplib is submodule path of https://github.com/yhirose/cpp-httplib.git

**Comment by yhirose** [comment]
@sum01, could you answer this question? Thanks!

**Comment by hn-sl** [comment]
I meam it is weird that it works though I didn't enable or link openssl. According to document I though that it is required to enable it to make https request work.

**Comment by hn-sl** [comment]
I meam it is weird that it works though I didn't enable or link openssl. According to document I though that it is required to enable it to make https request work.

**Comment by hn-sl** [comment]
I see, thanks for the answer.

**Comment by sum01** [comment]
By default, it does a sort of lazy/opportunistic linking.
`HTTPLIB_USE_OPENSSL_IF_AVAILABLE` is default-on, so if it finds OpenSSL on the system it'll link it.

So it might be linking even if you don't explicitly ask it to do so.
