### ISSUE TITLE
Post works for Days and then returns 2 (cannot connect)

### ISSUE THREAD

**Issue by mljanke** [yhirose/cpp-httplib#1407]
Hi,

Our target device (running Debian 10) works great and then starts giving error 2 on Post method calls. On our target device, we can connect using the command line (curl to the BASE_GCP_URL in code below) just fine while the Post call returns 2. A new httplib Client is created before each post as shown in code below. We would expect a different error if there was an issue with our payload, but it appears to be fine anyway.

Restarting out process does not fix the issue. Restarting our device fixes the issue. When getting this error, how can we recover from it without having to restart our target device? Again, curl commands to the same BASE_GCP_URL work fine while the lib is giving us error 2. Very strange.

Note that, as a test, we removed ethernet from our target (for about a min) and then reconnected it. While ethernet was disconnected, we got error 2, but as soon as we reconnected ethernet, Posts were successful again.

Thank you in advance for creating such a helpful lib and any support that you can provide.

Mark J

'''
// HTTPS client
httplib::Client GCPClient(BASE_GCP_URL);

// Define the path to a CA bundle
GCPClient.set_ca_cert_path("/etc/ssl/certs/ca-certificates.crt");

// POST request
httplib::Result httpPostRes = GCPClient.Post("/records/heartbeats", sPayload, "application/json");
'''

**Comment by yhirose** [comment]
@mljanke, thanks for the feedback. I can't give you any meaningful suggestions since I don't have the same exact network environment as yours....

But you could try to find what socket options are really used in curl by reading their source code, and to pass the same socket options with `Client::set_socket_options` method to see if it makes any difference.

Another think you could do is to find where `Error::Connection` is set on your debugger and check `errorno` to find the real cause of the error.

**Comment by mljanke** [comment]
> 

@yhirose, thank you for the reply. We will follow your recommendation and set socket options to match curl. C++ templates are new to us. Is there a set_socket_options() example? We expected to see a SocketOptions struct in the httplib.h, but cannot see this struct. We are unsure how to set options using set_socket_options().

**Comment by PixlRainbow** [comment]
socket options aren't a httplib-specific structure. httplib simply re-uses the POSIX or winsock API's struct.

`set_socket_options` allows you to provide a callback within which you may make modifications to the `socket_t` struct. You may refer to the default implementation as an example:
https://github.com/yhirose/cpp-httplib/blob/27cd4e6ffeca2c9978ec1df7de3d22b9303a71b4/httplib.h#L1595-L1611

**Comment by mljanke** [comment]
Hi,
For now, I am restarting my device whenever I get error 2. I plan to
implement a more elegant (and direct) fix in the next few weeks.

Regards,

Mark Janke - Deviceworx
p:1-250-339-9662  tf:1-888-409-2688  m:1-250-702-1693
***@***.***
