### ISSUE TITLE
Getting Error::Read when downloading large files to external device

### ISSUE THREAD

**Issue by alccetinkaya** [yhirose/cpp-httplib#1409]
Hi!

I am trying to download large files to an external device(USB and SSD) using Get(path, content_receiver) method. When I use SSD there is no problem with downloading, but when I use USB I get Error::Read after an unspecified time. I tried to increase the read_timeout value but it didn't work.

To narrow down the source of the problem, I removed writing to the file lines in ContentReceiver and in this case I didn't get such an error. But I couldn't understand how there could be a relationship between writing to file and ContentReceiver.  Maybe the method I applied is wrong so I am sharing the relevant piece of code below

```
std::ofstream ofs{filePath};
httplib::Client cli(baseURL);
            auto res = cli.Get(path,
                               [&](const char *data, size_t dataLen) {
                                   // write downloaded data to file
                                   ofs.write(data, dataLen);
                                   return true;
                               });
            // close file stream
            ofs.flush();
            ofs.close();
```

Thanks in advance!

**Comment by yhirose** [comment]
@alccetinkaya, thanks for the feedback. Honestly, I have not idea why that happens... You code looks good to me.

**Comment by GOOD-Stuff** [comment]
@alccetinkaya Hi!
What if you will be write by parts? I think that USB issue may cause because some system/inner buffers doesn't have enough memory. And if you try to write downloaded data by parts (for example, by 4/16/32 KB) it may help you.
