### ISSUE TITLE
Keep alive and workers question

### ISSUE THREAD

**Issue by evg82** [yhirose/cpp-httplib#1410]
Im using your lib in a server than receive short queries from clients (Also using your lib). Currently about 200 clients is sending a query each couple of seconds.

With keep alive disabled only a few workers are used and i can handle all my clients without problem.

If i enable keep alive (prefered) i need a worker to handle each client while the connection is alive, I implemented a thread pool than create new workers as needed.

Is there any way, or is in your roadmap something i can do to use keep alive without thousand of threads? I think in store active connections in some list and assign a worker when a request arrive, after handle it keep connection open and free the worker. Im not sure if this is too complex or anyone solve this otherway.

**Comment by yhirose** [comment]
@evg82, I don't understand what you mentioned though, what you are asking for seems to be too complex. :)
