### ISSUE TITLE
Can't access hidden (dot in front) directories

### ISSUE THREAD

**Issue by ClemsonCoder** [yhirose/cpp-httplib#1413]
I'm trying to use Let's Encrypt and part of it requires that it access a directory with the following path...

http://www.mywebsite.com/.well-known/acme-challenge/XXXXX

The problem is that your server mounting and get examples do not allow for a folder with a dot in front to be accessed. Is there a way to fix this? Also the XXXXXX is different each time so I would need a dynamic Get.

**Comment by yhirose** [comment]
@ClemsonCoder, thank you for the feedback. As you can see the code, there is no difference between dot directories and regular directories. Could you explain more about what you would like to do?

https://github.com/yhirose/cpp-httplib/blob/27cd4e6ffeca2c9978ec1df7de3d22b9303a71b4/httplib.h#L4905-L4915

**Comment by yhirose** [comment]
Close it for now until more evidence is provided.
