### ISSUE TITLE
JSON content in req.body is empty

### ISSUE THREAD

**Issue by raviruia** [yhirose/cpp-httplib#1420]
hi, i use POST method on client with json body, but server can't read it in log. it seems to return empty. please tell me how can i get it
Client:
`std::string postJson = "{\"task_id\":\"1\", \"names\":[\"test\"]}";`

    if (auto res = cli.Post("/content_receiver",  postJson, "application/json"))
    {
        cout << res->status << endl;
        cout << res->get_header_value("Content-Encoding") << endl;
        cout << res->body << endl;
    }
`
Server:
![Screenshot 2022-11-08 141847](https://user-images.githubusercontent.com/117713669/200499417-acbc724b-db6e-4423-9770-f21b9fe4bb6b.jpg)

**Comment by yhirose** [comment]
@raviruia, hope the following code examples will help you.

https://github.com/yhirose/cpp-httplib/blob/26196b70af0b5ae731c5d052977025bf7676ac04/test/test.cc#L2103-L2112
https://github.com/yhirose/cpp-httplib/blob/26196b70af0b5ae731c5d052977025bf7676ac04/test/test.cc#L1571-L1577
