### ISSUE TITLE
Post function donnot have the implement which only has path, header 

### ISSUE THREAD

**Issue by fengmao31** [yhirose/cpp-httplib#1421]
I post the request to server microsoft azure token server to access the tts service. But I find the source code have no implement which only has path, header. I need the header part. when I set body or  param nulptr, I find it throw a error. 
of course, it is easy to make a new implement function of Post similar to other implement. But I donnot want to change the source code to take the risk to maintain a different version from the public git repository.

**Comment by niuliwan** [comment]
I have the same problem.

**Comment by PixlRainbow** [comment]
do not use nullptr, use empty string e.g. `std::string()`

**Comment by yhirose** [comment]
@fengmao31, I added the Post method. (Also @PixlRainbow's comment should work.)
