### ISSUE TITLE
Completed content_provider Response hang for keep_alive_timeout 

### ISSUE THREAD

**Issue by vget** [yhirose/cpp-httplib#1422]
I have a GET query with highly variable content.
I noticed that all request have a minimal cost of 5s.
It seems that a content_provider hang for 5s after execution of the last callback.
If the keep_alive_timeout is set to n seconds the execution hang for n second.

I also noticed that a fixed len content provider lead to a crash if DataSink::done is invoked

Here follow a snippet with 3 Get testing various combination of set_content and set_content_provider that expose the issue

```shell
$ time curl http://localhost:8080/slow # why does it hang ?
no
real    0m5.144s
$ time curl http://localhost:8080/fast # fine
yes
real    0m0.109s
$ time curl http://localhost:8080/fixed # fine
yes
real    0m0.108s
```

```cpp
#define CPPHTTPLIB_USE_POLL
#include "httplib.h"
int main(int argc,const char **argv) {
  int port = 8080;
  using namespace httplib;
  Server svr;
  //svr.set_keep_alive_timeout(200);

  svr.Get("/fast", [&](const Request& , Response& res) {
    res.set_content("yes", "text/plain");
  });
  svr.Get("/slow", [&](const Request& , Response& res) {
    res.set_content_provider(
      "text/plain", // Content type
      [](size_t /*offset*/, DataSink &sink) {
        sink.write( "no", 2 );
        sink.done();
        return true; // return 'false' if you want to cancel the process.
      },
      [] (bool) {  });
    return true;
  });
  svr.Get("/fixed", [&](const Request& , Response& res) {
    res.set_content_provider(3,
      "text/plain", // Content type
      [](size_t /*offset*/, size_t , DataSink &sink) {
        sink.write( "yes", 3 );
        //sink.done(); <<= server crash if called
        return true; // return 'false' if you want to cancel the process.
      },
      [] (bool) {  });
    return true;
  });

  svr.listen("0.0.0.0", port);
  return 0;
}
```

**Comment by vget** [comment]
I just found out that the ``set_chunked_content_provider`` works fine for my use case.
Maybe I just misunderstood an expected behavior.

**Comment by NsPro04** [comment]
It seems like this is still happening.

Windows 10, CPPHTTPLIB_VERSION "0.32.0"
```cpp
#include "httplib.h"

int main() {
	using namespace std::chrono_literals;

	httplib::Server svr;

	svr.set_keep_alive_timeout(10); // 10 sec

	svr.Get("/", [](const httplib::Request& req, httplib::Response& res) {
		res.set_content_provider("text/html", [](size_t offset, httplib::DataSink& sink) {
			sink.write("123", 3);

			sink.done();
			return true;
		});
	});

	svr.listen("0.0.0.0", 8080);

	return 0;
};
```

<img width="831" height="483" alt="Image" src="https://github.com/user-attachments/assets/d7487705-46d9-4795-9abc-e05ec35a2a62" />

However, if ```return true``` after ```sink.done()``` is replaced with ```return false```, the 10-second delay is fixed:

<img width="1829" height="548" alt="Image" src="https://github.com/user-attachments/assets/44b9ca34-856d-478a-8b22-29f881e10c7f" />

I don't know if this behavior was actually intended, but it looks like a bug.

**Comment by NsPro04** [comment]
I checked the debugger, and it turns out the issue is in the ```keep_alive``` function:
<img width="1010" height="396" alt="Image" src="https://github.com/user-attachments/assets/f4e25200-d75e-43d4-bea3-e3d5938f0629" />

More specifically, in the ```while(true)``` loop, which runs until the timeout:
<img width="957" height="743" alt="Image" src="https://github.com/user-attachments/assets/745c352d-3eba-4cb7-9601-c93654395e88" />

The solution with ```return false``` is incorrect, because resource_releaser receives the result of the content provider, which will always be false if we do not want a 10-second delay. 
<img width="1115" height="267" alt="Image" src="https://github.com/user-attachments/assets/b0af2187-37aa-4e0a-bbfb-bcbea93d0f51" />

But maybe I'm missing something, I would appreciate an clarification @yhirose
