### ISSUE TITLE
Segment error (core has been dumped)

### ISSUE THREAD

**Issue by fengmao31** [yhirose/cpp-httplib#1424]
httplib::Client cli("https://127.0.0.1",4000); show the fault
   httplib::Client cli("https://127.0.0.1:4000"); is ok

**Comment by fengmao31** [comment]
![image](https://user-images.githubusercontent.com/19343842/201042264-651f29e5-8115-4dcd-a85d-0e80769a2213.png)
maybe it is only for http?

**Comment by yhirose** [comment]
`httplib::Client cli("https://127.0.0.1", 4000);` isn't supported.

It should be
`httplib::Client cli("https://127.0.0.1:4000");`  or
`httplib::SSLClient cli("127.0.0.1", 4000);` or
`httplib::SSLClient cli("127.0.0.1:4000");`.

Please see the following section in README.
https://github.com/yhirose/cpp-httplib#ssl-support

Hope it helps!

**Comment by fengmao31** [comment]
I hope add a IP example in the ssl-support. sometime, people will make the mistake to use it as me.

**Comment by yhirose** [comment]
That's not a problem with a IP, but 'scheme+host' and 'port'.
So `httplib::Client cli("https://localhost", 4000);` isn't supported either.

**Comment by fengmao31** [comment]
I understand it. Beginners may forget localhost is same as 127.0.0.1(IP).
