### ISSUE TITLE
body not in utf8 

### ISSUE THREAD

**Issue by ReneMueller4P** [yhirose/cpp-httplib#1425]
Hi,
my problem is that when I send a json to the server and there is a key or value with umlauts in it, it always comes out with a wrong value in body. I guess that no unicode is used. Is there a way to fix this?

example:

Ä Ö => Ã¶ Ã¤

**Comment by yhirose** [comment]
@ReneMueller4P, thank you for the feed back. But any HTTP library itself is neutral for any encoding, and it's a user's responsibility to encode body data properly in UTF-8 format. I am not sure that what encoding you are using on your system, but you have to find an appropriate encoder to convert your string to a std::string in UTF8 format. Thanks!
