### ISSUE TITLE
noexcept annotations?

### ISSUE THREAD

**Issue by bobbymcr** [yhirose/cpp-httplib#1430]
It would be good to annotate methods where we should not throw or do not call any throwing operations with `noexcept`. This helps ensure adherence to C++ guidelines, such as [E.12][1] and [F.6][2].

[1]: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Re-noexcept
[2]: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-noexcept

**Comment by yhirose** [comment]
@bobbymcr, thanks for the good suggestion! I'll get back to this when I have time.

**Comment by yhirose** [comment]
It's too much for me to investigate all the methods and apply `noexcept` properly... So I'll close it for now since I am not planning to do it any time soon.

**Comment by yhirose** [comment]
A pull request is always welcome!
