### ISSUE TITLE
httplib::Client method can not sand messages Continuously

### ISSUE THREAD

**Issue by QQiangren** [yhirose/cpp-httplib#1433]
I use the httplib::Client method to define the client and continuously send messages to the server. But after about 50 minutes, the link is disconnected and sending messages fails

![C224_202211181703100252180170147536fd](https://user-images.githubusercontent.com/23119784/202665248-a7664d57-2e8e-42dd-82ed-378ac8acdd04.png)

**Comment by yhirose** [comment]
Thanks for the information, but I don't know if it's a really cpp-httplib problem or your network environment causes the problem...

**Comment by QQiangren** [comment]
> Thanks for the information, but I don't know if it's a really cpp-httplib problem or your network environment causes the problem...

There is no problem with my network, because it is normal for me to send messages with the curl command, and it is no problem to send messages with python scripts. This happens only if cpp-httplib is used
