### ISSUE TITLE
Implementations for the "httplib.h" file.

### ISSUE THREAD

**Issue by iamalinaji** [yhirose/cpp-httplib#1435]
I was wondering where I could possibly find the implementations for the functions & constructors that you've defined inside the "httplib.h" file.

For example, for the ClientImpl class, how could I see the definitions of the constructors that you defined? Or how could I see for example how you implemented the GET method for the HTTP client?

I would really appreciate it if you consider helping me...

**Comment by yhirose** [comment]
@iamalinaji this is a 'header-only' library which means the httplib.h itself contains implementations as well. Hope it helps!
