### ISSUE TITLE
client.set_digest_auth  ret 400 

### ISSUE THREAD

**Issue by wangxiaoer3924** [yhirose/cpp-httplib#1436]
httplib::Client client("192.168.96.129", 80);
//    client.set_basic_auth("admin", "dixin_Admin123");
    client.set_digest_auth("admin", "dixin_Admin123");

//    if (auto res =  client.Get("/ISAPI/System/deviceInfo")) {
    if (auto res =  client.Put("/ISAPI/PTZCtrl/channels/1/presets/2/goto")) {
//    if (auto res =  client.Put("ISAPI/PTZCtrl/channels/1/homeposition/goto")) {
        if (res->status == 200) {
            std::cout << res->body << std::endl;
        } else {
            std::cout << "res->status=" << res->status << std::endl;
            std::cout << res->body << std::endl;
        }
    } else {
        auto err = res.error();
        std::cout << "HTTP error: " << httplib::to_string(err) << std::endl;
    }

res->status=400
<!DOCTYPE html>
<html><head><title>Document Error: Bad Request</title></head>
<body><h2>Access Error: 400 -- Bad Request</h2>
<p>Mulitple content length headers</p>
</body>
</html>

**Comment by yhirose** [comment]
@wangxiaoer3924, thank you for the feedback. But I cannot give you any help since I don't know your network environment and what your digest auth setting is like. So 400 might be correct. :)

**Comment by wangxiaoer3924** [comment]
我用curl使用摘要认证是没有问题的，摘要就是用户名和密码 "admin", "dixin_Admin123" ，相同的用户名和密码我感觉是不是用法上哪里出了问题

**Comment by KSdong** [comment]
你好，请问一下 这个set_digest_auth函数是在那里的呀？我的httplib.h里怎么没有这个函数
