### ISSUE TITLE
EXCEPTION_WHAT is not set if exception text contains newlines

### ISSUE THREAD

**Issue by oliver** [yhirose/cpp-httplib#1437]
If an HTTP server function throws an exception, normally httplib returns HTTP status 500 and sets the `EXCEPTION_WHAT` header to `e.what()`. But if  `e.what()` contains newlines, the `EXCEPTION_WHAT` header is not set at all.  
I hit this problem when my server function threw an exception which contained newlines due to a bug in my code; and the missing `EXCEPTION_WHAT` header made that bug even more puzzling.

The `EXCEPTION_WHAT` header is not set in this case because the `set_header()` method checks key and value for CR-LF, and does not set the header if newlines are found.

I guess one simple solution would be to call something like `res.set_header("EXCEPTION_WHAT", "UNKNOWN_DETAILS");` before calling `res.set_header("EXCEPTION_WHAT", e.what());`; that way the header would at least contain an indication that a "weird" exception had occurred.

A better solution would be to remove any newlines from the exception text before calling `res.set_header()`.

**Comment by yhirose** [comment]
@oliver, thanks for the feedback. I implemented the 'better solution'. Please let me know if you find any problem.

**Comment by oliver** [comment]
Looks great - I just tested the latest httplib.h file, and the HTTP 500 response is now complete. Thank you for you quick response, and for creating this library!
