### ISSUE TITLE
Read series of chunks as they are being sent from server

### ISSUE THREAD

**Issue by PasinduKollure** [yhirose/cpp-httplib#1439]
Im creating an HTTPS client which uses the `Transfer-Encoding: chunked` header and so I would like to read the incoming chunk data before the HTTPS request is complete. Is there a call back function to read the incoming chunk data or another way to do this?

Currently I am using the [socket_t ClientImpl::socket()](https://github.com/yhirose/cpp-httplib/blob/v0.11.2/httplib.h#L1005) function to get the socket descriptor but when I use the descriptor to [recv(socket_num,buf,sizeof(buf),MSG_PEEK);](https://man7.org/linux/man-pages/man2/recv.2.html) the socket from another thread, the [httplib::Post(...)](https://github.com/yhirose/cpp-httplib/blob/v0.11.2/httplib.h#L6785) call fails with the SSLConnection error.

**Comment by yhirose** [comment]
@PasinduKollure thanks for the feedback, but I honestly don't understand what you are trying to do with cpp-httplib...

First of all, `ClientImpl` class is not designed for direct use from users, but it should be used only by `Client` or `SSLClient`. 

Secondly, using `Transfer-Encoding: chunked` in a request header isn't a way to ask a HTTP server to send response body as chunked data. Also if a server sends response body as chunked data, you don't have to do any thing on your side. The client methods like `Get` and `Post` will take care of it for you.

If you want to send chunked data, please see [this information](https://github.com/yhirose/cpp-httplib#chunked-transfer-encoding-1) in README.

Hope the information helps!
