### ISSUE TITLE
SSL_get_peer_certificate() was deprecated in OpenSSL 3.0

### ISSUE THREAD

**Issue by jimmy-park** [yhirose/cpp-httplib#1442]
As shown in [OpenSSL manpage](https://www.openssl.org/docs/man3.0/man3/SSL_get_peer_certificate.html), `SSL_get_peer_certificate()` is an alias of `SSL_get1_peer_certificate()` and was deprecated in OpenSSL 3.0.
When OpenSSL is configured with `no-deprecated` option, [this line](https://github.com/yhirose/cpp-httplib/blob/c0b461a3b7b15877b5c8047b409c124aceec8fd9/httplib.h#L7768) will throw an error.

Personally, I just replace `SSL_get_peer_certificate()` with `SSL_get1_peer_certificate()` when linking OpenSSL 3.0. (because it's a single line of problem for me)
But, for the backward compatibility, I would suggest some workaround using OpenSSL's version macro.

```cpp
#if OPENSSL_VERSION_NUMBER < 0x30000000L
#define SSL_get1_peer_certificate SSL_get_peer_certificate
#endif

// Line 7768
auto server_cert = SSL_get1_peer_certificate(ssl2);
```

**Comment by yhirose** [comment]
@jimmy-park thanks for the contribution!
