### ISSUE TITLE
how to post  file with kv param use 'multipart/form-data'

### ISSUE THREAD

**Issue by lifw555** [yhirose/cpp-httplib#1443]
html content like this:

<form action="/post_server" method="post" enctype="multipart/form-data">
  <input name="text1" type="text" />
  <input name="text2" type="text" />
  <input name="text3" type="text" />
  <input name="file" type="file" />
  <input type="submit" />
</form>

like  #343

**Comment by yhirose** [comment]
Hope [this](https://github.com/yhirose/cpp-httplib#post-with-multipart-form-data) in README helps.

**Comment by lifw555** [comment]
i mean use httplib receive the post data on browser。 like #343 issue.

thx.

**Comment by lifw555** [comment]
i mean use httplib receive the post data on browser。 like #343 issue.

thx.
