### ISSUE TITLE
Slow response when set CPPHTTPLIB_THREAD_POOL_COUNT to 1

### ISSUE THREAD

**Issue by martinergb** [yhirose/cpp-httplib#1446]
The server serves only static files.
When I set CPPHTTPLIB_THREAD_POOL_COUNT to 1 and client requests many files at the same time, the server responses very slowly.

When I set CPPHTTPLIB_THREAD_POOL_COUNT to bigger number (5 or 10), the resposne is normal.

**Comment by yhirose** [comment]
Thanks for the feedback. That's an expected behavior.
