### ISSUE TITLE
always return error connection

### ISSUE THREAD

**Issue by 0x4d696e68** [yhirose/cpp-httplib#1449]
hi

it only works with
httplib::Client cli("http://127.0.0.1"); or httplib::Client cli("127.0.0.1", 80);
otherwise always return error connection
i tested
httplib::Client cli("http://127.0.0.1", 80) not works
httplib::Client cli("http://127.0.0.1/index.php") not works
httplib::Client cli("http://127.0.0.1/subdir")  not works
httplib::Client cli("http://127.0.0.1/subdir/index.php") not works

**Comment by yhirose** [comment]
Thanks for the feedback. They are expected behaviors. Please carefully read the README instruction. :)
