### ISSUE TITLE
static file server

### ISSUE THREAD

**Issue by RemoteSensingFrank** [yhirose/cpp-httplib#145]
I want to build a static file server and I set the base dir path how can I get file in the base dir? and the localhost:1234/index.html cannot be found

**Comment by yhirose** [comment]
@RemoteSensingFrank, as the README says, `svr.set_base_dir(BASE_DIR_PATH);`.
If you put `index.html` in the BASE_DIR_PATH, `index.html` can be found. Thanks you.

**Comment by RemoteSensingFrank** [comment]
Thanks
