### ISSUE TITLE
no handlers before serving file with a ssl static file server 

### ISSUE THREAD

**Issue by LangArthur** [yhirose/cpp-httplib#1453]
Hi!

I used your library to create a static file server (and much more but it is not related to my issue) using the Sslserver object. I want to add some checks about the content of the request before serving a file, but I can't find a way to do that properly.
At the moment I am using the set_file_request_handler to set a callback containing the piece of code I want to execute. The problem is, if my custom checks are not good, I have to manually delete the content of the server's which seems dirty to me (also it is not fully working at the moment but I did not dig that way).

I wanted then to used pre routing handler but it is not called with the SslServer (the method is still available though, might need a correction?).

Has far as I am aware, there is no way to do what I want. Do you confirm it is not possible at the moment? Do you have any solutions?

Thanks for your answer,

**Comment by yhirose** [comment]
@LangArthur, thanks for the feedback. There is no problem at all to update `res.body` in your file request handler based on your check logic.

As for the pre-routting handle, it's supposed on work with SSL. I just updated the unit test which shows how to use it.
https://github.com/yhirose/cpp-httplib/commit/93e53c91f741d2393a12ba043366ac6f55f56cc7

Hope it helps!
