### ISSUE TITLE
Why is the content not "hello word"?

### ISSUE THREAD

**Issue by 1274936135** [yhirose/cpp-httplib#1455]
// HTTP
httplib::Client cli("http://cpp-httplib-server.yhirose.repl.co");

auto res = cli.Get("/hi");
res->status;

std::cout << res->body<<endl;

Why is the content not "hello word"? I want to display text

**Comment by 1274936135** [comment]
<a href="https://cpp-httplib-server.yhirose.repl.co/hi">Permanent Redirect</a>.       Debugging outputs this

**Comment by yhirose** [comment]
I guess `cli.set_follow_location(true)` is needed.
