### ISSUE TITLE
res->body is a std::string, support for binary results?

### ISSUE THREAD

**Issue by Zelex** [yhirose/cpp-httplib#1457]
Does the client library support binary data? So like if I grabbed some random JPG and I wanted to write it to a file or what-not -- since the results are in a std::string, which is normally zero terminated. The problem with that is its not uncommon to have 0x00 in binary data, so returning the results in a std::string rather than say a std::vector is problematic.

**Comment by yhirose** [comment]
Hope #826 helps you.
