### ISSUE TITLE
Redirection 302/"Found" does not copy header Location to member like others

### ISSUE THREAD

**Issue by maudoin** [yhirose/cpp-httplib#1460]
Location must be retrieved manually like
```c++
if (res->status > 300 && res->status < 400 )
{
  location = res->location.empty()?
                               res->get_header_value("Location"):
                               res->location;
}
```
For context, I redirect manually to forward response cookies to the redirected request
```c++
if(res->has_header("Set-Cookie"))
{
  cookies.emplace_back(res->get_header_value("Set-Cookie"));
  headers.erase ("Cookies");
  headers.insert({"Cookies", join(cookies, ";")});
}
```

**Comment by yhirose** [comment]
@maudoin, thanks for the report. Could you explain more about the issue?

**Comment by maudoin** [comment]
@yhirose, my bad the API is working as implemented
I though the `location` field in `Result` was always filled with the header Location in case of redirection status in the response, except for status 302.
I did not see that this field is actually setup only when using `set_follow_location(true)`.

**Comment by maudoin** [comment]
not  bug
