### ISSUE TITLE
Issue with image [Problem]

### ISSUE THREAD

**Issue by anyeyongheng** [yhirose/cpp-httplib#1462]
how to acquire the data of image from url
[https://stackoverflow.com/questions/749517/how-to-download-an-image-from-an-url-to-a-local-dir](url)
curl can do this

**Comment by anyeyongheng** [comment]
i post a wrong url , here is the correct link [https://stackoverflow.com/questions/36702888/download-an-image-from-an-url-using-curl-in-c](url)

**Comment by yhirose** [comment]
Please use `Get` method on `Client`. You can see more information on README or `test/test.cc`. Hope it helps.
