### ISSUE TITLE
Getting the response time?

### ISSUE THREAD

**Issue by resal81** [yhirose/cpp-httplib#1464]
Thanks for this great library. Is there a recommended way to get/log the response time for a request? One way would be to calculate the time in the handler, but not sure how to access it in the logger function.

**Comment by yhirose** [comment]
@resal81, sorry for the late reply.

If you are talking about client call, you can simply do the following.

```cpp
auto start = std::chrono::system_clock::now();
cli.Get(...);
auto end = std::chrono::system_clock::now();
auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();
// Format and output `elapsed`...
```

But if you are talking about service side, there is no easy way to log response time. The only think that I can come up with is to make your own `TaskQueue` class and measure duration time as below.

```cpp
class ThreadPoolTaskQueueWithResponseTimeCalculation : public TaskQueue {
public:
  ThreadPoolTaskQueueWithResponseTimeCalculation(size_t n) {
    pool_.start_with_thread_count(n);
  }

  virtual void enqueue(std::function<void()> fn) override {
    pool_.enqueue([fn]() {
      auto start = std::chrono::system_clock::now();
      fn();
      auto end = std::chrono::system_clock::now();
      auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();
      // Format and output `elapsed`...
    });
  }

  virtual void shutdown() override {
    pool_.shutdown_gracefully();
  }

private:
  YourThreadPool pool_;
};

svr.new_task_queue = [] {
  return new ThreadPoolTaskQueueWithResponseTimeCalculation(12);
};
```

I know cpp-httplib lacks a good logging facility like #870. But hope the above workaround can help you for now.

**Comment by resal81** [comment]
Yes, I meant for the server side. Thanks for the detailed answer!
