### ISSUE TITLE
Passing ca-bundle as string

### ISSUE THREAD

**Issue by wagenaartje** [yhirose/cpp-httplib#1466]
We can set our CA-bundle like below. But when shipping the executable to a different machine, or simply running it from a different directory, it will fail to find `ca_bundle.crt`. Of course the executable could always be shipped with the certificate, but then we still have to modify the line below to search in the same folder as the executable.  

```cpp
// Use your CA bundle
cli.set_ca_cert_path("./ca-bundle.crt");
```

I was wondering if it is possible to hardcode the CA bundle, and pass it as a `std::string` or `const char *` instead? This way I don't have to deal with finding a seperate `ca-bundle.crt` file. We would get something like 

```cpp
// Use your CA bundle (ca_bundle_str is the full key chain)
cli.set_ca_cert_path(ca_bundle_str);
```

**Comment by yhirose** [comment]
`set_ca_cert_path` ends up calling `SSL_CTX_load_verify_locations` which takes only a file path or directory path. So what you could do is to write your hardcoded CA bundle to a temporary file and call `set_ca_cert_path`. Hope it helps!

**Comment by PixlRainbow** [comment]
See #1306 for another possible solution
