### ISSUE TITLE
AppleSilicon Mac cannot make binaries run on other Macs and cannot use openssl 3

### ISSUE THREAD

**Issue by kivvi3412** [yhirose/cpp-httplib#1469]
uname -a:

```bash
Darwin Macintosh.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
```

This is my Project Tree

```
Project
├── CMakeLists.txt
├── TestFile
│   └── httplib_test.cpp
└── include
    └── cpp-httplib
        └── httplib.h
```

CMakeLists.txt:

```makefile
cmake_minimum_required(VERSION 3.24)
project(Project)
set(CMAKE_CXX_STANDARD 17)

add_executable(httplib_test TestFile/httplib_test.cpp)

include_directories(${PROJECT_SOURCE_DIR}/include)
# OpenSSL3 An error will be reported
# target_link_libraries(httplib_test /opt/homebrew/Cellar/openssl@3/3.0.7/lib/libcrypto.a)
# target_link_libraries(httplib_test /opt/homebrew/Cellar/openssl@3/3.0.7/lib/libssl.a)
target_link_libraries(httplib_test /opt/homebrew/Cellar/openssl@1.1/1.1.1s/lib/libcrypto.a)
target_link_libraries(httplib_test /opt/homebrew/Cellar/openssl@1.1/1.1.1s/lib/libssl.a)
```

TestFile/httplib_test.cpp:

```cpp
#define CPPHTTPLIB_OPENSSL_SUPPORT

#include <iostream>
#include "cpp-httplib/httplib.h"

int main() {
    httplib::Client cli("https://bing.com");

    httplib::Result res = cli.Get("/");

    std::cout << res->status << std::endl;
    std::cout << res->get_header_value("Content-Type") << std::endl;
    std::cout << res->body << std::endl;
}
```

- OpenSSL3 Compilation error
    
    Using `openssl@1.1/ 1.1s` will work fine, but using `openssl@3/3.0.7` will get the following error
    I wrote other programs to ensure that `libcrypto.a` and `libssl.a` compile and work in other CPP files
    I tried `libssl.dylib` and `libcrypto.dylib` for OpenSSL3 and still produced the same error
    
    ```cpp
    [1/1] Linking CXX executable httplib_test
    FAILED: httplib_test 
    : && /Library/Developer/CommandLineTools/usr/bin/c++ -g -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/httplib_test.dir/TestFile/httplib_test.cpp.o -o httplib_test  /opt/homebrew/Cellar/openssl@3/3.0.7/lib/libssl.a  /opt/homebrew/Cellar/openssl@3/3.0.7/lib/libcrypto.a && :
    Undefined symbols for architecture arm64:
      "_SSL_get_peer_certificate", referenced from:
          httplib::SSLClient::initialize_ssl(httplib::ClientImpl::Socket&, httplib::Error&)::'lambda'(ssl_st*)::operator()(ssl_st*) const in httplib_test.cpp.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
    ```
    
- Cannot be moved to run on other Macs
    
    I will run the compiled binary on my machine using `openssl@1.1/ 1.1s`. I can get the result, for example:
    
    ```bash
    kivvi@Macintosh cmake-build-debug % ./httplib_test 
    301
    text/html; charset=utf-8
    <html><head><title>Object moved</title></head><body>
    <h2>Object moved to <a href="https://www.bing.com:443/?toWww=1&amp;redig=519996DEAD3E48AA9E95A85F43F68C20">here</a>.</h2>
    </body></html>
    ```
    
    The following error occurs when I move the binary file to another Mac (AppleSilicon)
    
    ```bash
    test@testdexuniji cmake-build-debug % ./httplib_test 
    zsh: segmentation fault  ./httplib_test
    ```
    

I'm not sure how to solve these two problems…

**Comment by PixlRainbow** [comment]
note: `res` can be `nullptr` if it could not connect to server
have you tried attaching a debugger to see at what point the segfault occurs?

**Comment by jimmy-park** [comment]
@kivvi3412 Recently, related issue was solved because of the deprecated `SSL_get_peer_certificate()` (#1442). It seems like this macro doesn't work for you.

https://github.com/yhirose/cpp-httplib/blob/7992b148969fbf8093230b37a6a36c2f61135937/httplib.h#L256-L260

Does `httplib_test` include the include directory of OpenSSL 3.0?
You may need to include OpenSSL 3.0's headers rather than 1.1.1

```CMake
target_include_directories(httplib_test PRIVATE /opt/homebrew/Cellar/openssl@3/3.0.7/include)
```

or, just update `httplib.h` version to `v0.11.4`.

**Comment by kivvi3412** [comment]
> @kivvi3412 Recently, related issue was solved because of the deprecated `SSL_get_peer_certificate()` (#1442). It seems like this macro doesn't work for you.
> 
> https://github.com/yhirose/cpp-httplib/blob/7992b148969fbf8093230b37a6a36c2f61135937/httplib.h#L256-L260
> 
> Does `httplib_test` include the include directory of OpenSSL 3.0? You may need to include OpenSSL 3.0's headers rather than 1.1.1
> 
> ```cmake
> target_include_directories(httplib_test PRIVATE /opt/homebrew/Cellar/openssl@3/3.0.7/include)
> ```
> 
> or, just update `httplib.h` version to `v0.11.4`.


Thanks for your reply, my `httplib.h` version is the latest version `CPPHTTPLIB_VERSION"0.11.4"`
but I changed the CMAKE file to

```makefile
cmake_minimum_required(VERSION 3.24)
project(Project)
set(CMAKE_CXX_STANDARD 17)

add_executable(httplib_test TestFile/httplib_test.cpp)

include_directories(${PROJECT_SOURCE_DIR}/include)
target_link_libraries(httplib_test /opt/homebrew/Cellar/openssl@3/3.0.7/lib/libcrypto.a)
target_link_libraries(httplib_test /opt/homebrew/Cellar/openssl@3/3.0.7/lib/libssl.a)
target_include_directories(httplib_test PRIVATE /opt/homebrew/Cellar/openssl@3/3.0.7/include)
```

This allowed me to compile using openssl3 without error, but moving the compiled binaries to another AppleSilicon Mac still produced the following error.

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/64115433/213407465-356816af-a525-4af1-b067-85790430c03f.png">


This is my binary file updated : `https://ztfot.com/httplib_test_updated_0`

**Comment by jimmy-park** [comment]
@kivvi3412 Did you install OpenSSL on another computer using `brew`? `brew` will install `cert.pem` to the `/usr/local/etc/openssl@3` when installing OpenSSL. If it isn't installed, you will have an SSL handshake error which results `res == nullptr` as @PixlRainbow mentioned.

**Comment by kivvi3412** [comment]
> Did you install OpenSSL on another computer using `brew`? `brew` will install `cert.pem` to the `/usr/local/etc/openssl@3` when installing OpenSSL. If it isn't installed, you will have an SSL handshake error which results `res == nullptr` as @PixlRainbow mentioned.

I want to package all the dependencies in binaries so that they can be used on any computer that doesn't have openssl installed, Can this be done ?

**Comment by PixlRainbow** [comment]
you can ship `cert.pem` file with your binary. It's not actually itself a library, it's just a list of every trusted TLS certificate authority that exists. Since shipping the file would put it in a non-default location, you would need to use `set_ca_cert_path` to direct it to the path of the `cert.pem` file

**Comment by kivvi3412** [comment]
> you can ship a copy of `cert.pem` file with your binary. It's not actually itself a library, it's just a list of every trusted TLS certificate authority that exists. Since shipping the file with your program would put it in a non-default location, you would need to use `set_ca_cert_path` to direct it to your copy of the `cert.pem` file.

Is there a manual or an example?

**Comment by PixlRainbow** [comment]
You can copy the `cert.pem` file from `/usr/local/etc/openssl@3` folder and paste it beside your binary before sending both files to your end user. You can do this manually in MacOS Finder, _or_ you can automate it with cmake `configure_file` like so
```cmake
configure_file(/usr/local/etc/openssl@3/cert.pem ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
```
To tell httplib that it should use `cert.pem` from the relative current directory instead of from brew,
in your code, add this line immediately after the `httplib::Client cli` constructor
```cpp
cli.set_ca_cert_path("./cert.pem");
```
When your binary is executed, the folder structure looks like this
```
.....some folder.....
├── httplib_test (executable)
└── cert.pem
```

**Comment by kivvi3412** [comment]
It works, Thanks a lot.

CMakeLists:

```makefile
cmake_minimum_required(VERSION 3.24)
project(Project)
set(CMAKE_CXX_STANDARD 17)

add_executable(httplib_test TestFile/httplib_test.cpp)

include_directories(${PROJECT_SOURCE_DIR}/include)
target_link_libraries(httplib_test /opt/homebrew/Cellar/openssl@3/3.0.7/lib/libcrypto.a)
target_link_libraries(httplib_test /opt/homebrew/Cellar/openssl@3/3.0.7/lib/libssl.a)
target_include_directories(httplib_test PRIVATE /opt/homebrew/Cellar/openssl@3/3.0.7/include)
```

httplib_test.cpp

```cpp
#define CPPHTTPLIB_OPENSSL_SUPPORT

#include <iostream>
#include "cpp-httplib/httplib.h"

int main() {
    httplib::Client cli("https://bing.com");
    cli.set_ca_cert_path("./cert.pem");
    httplib::Result res = cli.Get("/");

    std::cout << res->status << std::endl;
    std::cout << res->get_header_value("Content-Type") << std::endl;
    std::cout << res->body << std::endl;
}
```

Folder structure

```cpp
.....some folder.....
├── httplib_test (executable)
└── cert.pem
```
