### ISSUE TITLE
Help with PUT Request of XML file

### ISSUE THREAD

**Issue by frozenWaffles123** [yhirose/cpp-httplib#1472]
Hello,

I'm attempting to make a PUT request to upload an XML file to my server. In order to post to my server I need to be able to submit this where the body is "form-data". I've written the code below but I'm having trouble getting it to work.

Please note that the key-value pair for the form-data must be "file" and the value type as the data contained in the XML file.

```
// Client setup
httplib::Client* gCli = new httplib::Client("127.0.0.1", 8080);
gCli->set_basic_auth("username", "pwd");

// store XML data
std::ifstream xmlFile;
xmlFile.open("C:/file.xml");
std::string xmlData((std::istreambuf_iterator<char>(xmlFile)), std::istreambuf_iterator<char>());

// PUT request
std::string urlForPutRequest = "http://127.0.0.1:8080/rest/PathToPutXmlFile";
auto httpResponse = gCli->Put(urlForPutRequest.c_str(), xmlData, "file");
```

Thank you

**Comment by PixlRainbow** [comment]
the first parameter of the request methods (in this case, `Put()`) is not supposed to be complete URL, just the "path" component.
See this diagram for reference:
![](https://media.geeksforgeeks.org/wp-content/uploads/20210625160610/urldiag.PNG)


The second issue is that you are posting the raw content of the file directly as the request body with the content-type of `"file"`. If you want form-formatted content body instead, use the `[httplib::MultipartFormDataItems` interface](https://github.com/yhirose/cpp-httplib/blob/master/README.md#post-with-multipart-form-data)

**Comment by yhirose** [comment]
Hope @PixlRainbow's comment helps.
