### ISSUE TITLE
Issue using `set_content` with newline character

### ISSUE THREAD

**Issue by kenny-statsig** [yhirose/cpp-httplib#1473]
I am adding Server endpoint that returns a string response containing newline characters
But when I hit this endpoint from the client, I only get the characters from the last line.
This is an abridged version of my code. I've also tried passing it as a `char *` and assigning `res.body` directly. Any idea what I'm doing wrong?

```
server.Get("/list_1", [this](const httplib::Request &req, httplib::Response &res)
{
      std::string result = "-1\n+2\n";
      res.set_content(result, "text/html");
});
```
printing result shows:
-1
+2

```
auto res = client.Get("/list_1", headers);
```
printing res.body shows:
+2

**Comment by yhirose** [comment]
@kenny-statsig, thanks for the report. But I can't reproduce it. I modified `server.cc` and `simplecli.cc` in `example` folder. 

#### server.cc

```cpp
  svr.Get("/hi", [](const Request & /*req*/, Response &res) {
    // res.set_content("Hello World!\n", "text/plain");
    std::string result = "-1\n+2\n";
    res.set_content(result, "text/html");
  });
```

#### simplecli.cc

```cpp
  auto cli = httplib::Client(scheme_host_port);
  cli.enable_server_certificate_verification(false);

  if (auto res = cli.Get("/hi")) {
    cout << res->status << endl;
    cout << res->get_header_value("Content-Type") << endl;
    cout << res->body << endl;
  } else {
    cout << res.error() << endl;
  }
```

Here is my result.

```
> ./simplecli
200
text/html
-1
+2
```

Hope the above example helps you.
