### ISSUE TITLE
Infinite loop in write_content_chunked

### ISSUE THREAD

**Issue by aldoshkind** [yhirose/cpp-httplib#1475]
Hello, @yhirose !
I am using server-sent events and faced infinite loop. In my case infinite loop occurs when I reopen web-page/web-browser several times.
How to reproduce: run SSE example `ssesvr.cc`, open browser and reload page several times (5 or 6 in my case on 8-core processor). Voila, page not loading!
Infinite loop is here: https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L3764
My hotfix looks like this: `while (data_available && !is_shutting_down() && strm.is_writable()) {` (add `&& strm.is_writable()`). Not sure it's absolutely correct, so no PR from me :) Also I see there are similar pieces of code, maybe they are affected too.
Please investigate the problem!
Thanks!

**Comment by yhirose** [comment]
@aldoshkind thanks for the report. It's ok to send me a pull request even if you are not confident with your change. Thanks!
