### ISSUE TITLE
The way to set headers

### ISSUE THREAD

**Issue by SpiritSaint** [yhirose/cpp-httplib#1479]
Hi @yhirose 

Appreciate so much your job doing maintenance and project management.

I use this library on my projects and now i'm trying to use the client but i was facing a lot of issues to set headers.

Anyways, i'll leave my solution:

```cpp
cli.Get("/endpoint",{{"X-Authentication", "Bearer ..."}});
```

If you can add this to the documentation, would be awesome.

**Comment by yhirose** [comment]
@SpiritSaint thanks for the feedback!
