### ISSUE TITLE
Getting response code even when it fails to read

### ISSUE THREAD

**Issue by Kiryuumaru** [yhirose/cpp-httplib#1480]
I too have the same problem. After subsequent post calls, the "res" is empty and returns false. If I relaunch my app, it will work again.

_Originally posted by @Kiryuumaru in https://github.com/yhirose/cpp-httplib/issues/1477#issuecomment-1413371506_

**Comment by yhirose** [comment]
@Kiryuumaru, if your issue is same as #1477, it means that the request from the server isn't a correct HTTP response. So it's impossible to parse the status code from the invalid text...

**Comment by Kiryuumaru** [comment]
I looped the same request. Always have status 200 for like first 50 request, after that it starts failing. Need to restart the whole app to be able to work again

**Comment by PixlRainbow** [comment]
it suggests your http request has been blocked by some firewall, a network problem, or it might be a problem with keep-alive settings. There is no response code because the server never provided any kind of response, or the response is malformed and not following http structure.
