### ISSUE TITLE
transfer-encoding chunked issue

### ISSUE THREAD

**Issue by ChenXiaoTemp** [yhirose/cpp-httplib#1484]
When download file and transfer-encoding is `chunked` then , it is easy download failed.

**Comment by ChenXiaoTemp** [comment]
And I think the problem is from https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L3504

Is it should be 
```
 if (strcmp(line_reader.ptr(), "\r\n")==0) { break; }
```
?

**Comment by yhirose** [comment]
@ChenXiaoTemp thanks for the feedback, but it's too little information to figure out the problem...
