### ISSUE TITLE
Which Cert to Use for HTTPS?

### ISSUE THREAD

**Issue by anzenchitai** [yhirose/cpp-httplib#1485]
Hello,

I am using Cloudflare and Letsencrypt generated with Certbot but I don't know what to put here:
`cli.set_ca_cert_path("./ca-bundle.crt");`

I can't find a .crt file anywhere. Please help me. Thanks in advance.

**Comment by PixlRainbow** [comment]
`set_ca_cert_path` is used to indicate the path to the file that contains certificate authorities/issuers you wish to trust.
See:
https://github.com/yhirose/cpp-httplib/issues/1360#issuecomment-1216178509
https://github.com/yhirose/cpp-httplib/issues/458#issuecomment-622918727
