### ISSUE TITLE
Http client port error causes program crash

### ISSUE THREAD

**Issue by tanpopoycz** [yhirose/cpp-httplib#1487]
int main(void)
{
    try
    {
        httplib::Client cli("207.101.68.184:9002");
        auto res = cli.Get("/CBK/v1/Client/GetClientList");
        print_res(res);
    }
    catch (std::exception& e)
    {
        std::cout << "Error: " << e.what() << std::endl;
    }
    catch (...)
    {
        std::cout << "Error: " << "Unknown Exception" << std::endl;
    }
    return 0;
}
====Dividing line====
The above client instance connects to the server's 9002 port. In fact, the server port number is 9001. However, the program does not throw any exception. But I don't want the program to exit directly. How to do it? I hope someone can help me🌹

**Comment by yhirose** [comment]
Hope this helps.
https://github.com/yhirose/cpp-httplib#client-1

**Comment by tanpopoycz** [comment]
good job!
