### ISSUE TITLE
if the http server is not existed, the code will dump?

### ISSUE THREAD

**Issue by zxz970104** [yhirose/cpp-httplib#1488]
if the http server is not existed, the code will dump?

**Comment by yhirose** [comment]
Thanks for the question, but I don't know what the questing is asking...

**Comment by PixlRainbow** [comment]
Perhaps they mean `segmentation fault: core dumped`

The client request functions return nullptr if the server fails to respond, or if it is unable to contact the server. You need to wrap the return value in an `if` check first to account for this before you can safely access the response data.
