### ISSUE TITLE
(question) Does making it a DLL require any extra work?

### ISSUE THREAD

**Issue by MoongStory** [yhirose/cpp-httplib#1489]
I made a dll as the EXAMPLE code, but it doesn't work.

If I make an exe with the same code, it works normally.

Is there anything else I need to do to make it work as a DLL?

**Comment by yhirose** [comment]
I actually don't know... But you may find some helpful information from past issues.
https://github.com/yhirose/cpp-httplib/search?q=dll&type=issues

**Comment by MoongStory** [comment]
SELF ANSWER

WSAStartup function should not be called from dllmain.
So svr.listen("localhost", 8080); Make sure the function is not called from dllmain.
