### ISSUE TITLE
Allow getting raw bytes request body in server

### ISSUE THREAD

**Issue by Raizuuuuu** [yhirose/cpp-httplib#149]
I have several clients (third party) which submit raw binary data (application/octet-stream) directly in the body of post requests. However, on your server, response.body.data() returns an std::string. I have tried casting/reinterpreting this to char* but the std::string constructor appears to have modified the content body in such a way that it no longer perfectly matches uploaded data. There does not appear to be any function that returns char array or pointer or stream.

**Comment by yhirose** [comment]
@Raizuuuuu, thanks for the report. I probably don't fully understand what you are saying. I need more inform regarding it.

As you said, it's correct that this library uses `std::string` for body data. But `std::string::data` doesn't return `std::string`. Please see the http://www.cplusplus.com/reference/string/string/data/.
It clearly says that the signature of `std::string::datai` is`const char* data() const`. So this method returns `const char*` pointer.

You can see some my examples sending/receiving `application/octet-stream` data to handle the multipart form data in test/test.cc. 

Please let me know if I misunderstand what you mentioned. Thanks!

**Comment by yhirose** [comment]
@Raizuuuuu, thanks for the report. I probably don't fully understand what you are saying. I need more information regarding it.

As you said, it's correct that this library uses std::string for body data. But std::string::data doesn't return std::string. Please see the http://www.cplusplus.com/reference/string/string/data/.
It clearly says that the signature of std::string::datai isconst char* data() const. So this method returns const char* pointer.

You can see some my examples sending/receiving application/octet-stream data to handle the multipart form data in test/test.cc.

Please let me know if I misunderstand what you mentioned. Thanks!

**Comment by yhirose** [comment]
@Raizuuuuu, thanks for the report. I probably don't fully understand what you are saying. I need more information regarding it.

As you said, this library uses std::string for body data. But std::string::data doesn't return std::string. Please see the http://www.cplusplus.com/reference/string/string/data/.
It clearly says that the signature of std::string::datai isconst char* data() const. So this method returns const char* pointer.

You can see some my examples sending/receiving application/octet-stream data to handle the multipart form data in test/test.cc.

Please let me know if I misunderstand what you mentioned. Thanks!
