### ISSUE TITLE
Aliases for pc-files from different httplib flavors

### ISSUE THREAD

**Issue by svalx** [yhirose/cpp-httplib#1491]
I maintain the rpm package for openSUSE, and there is a problem with the shipped pkg-config files. We build a both flavors of library - compiled and headers-only. Every flavor provides the same-named pkg-config description file (**_cpp-httplib.pc_**), although in different directories. In any case, both rpm packages provide a **_pkgconfig(cpp-httplib)_**. Difficulties begin when you need to set a dependency in other rpm packages. The **BuildRequires: _pkgconfig(cpp-httplib)_** directive leads to a choice, and it is impossible to unambiguously specify which version of the library the project needs - compiled or not. This happens when processing dependencies in Open Build Service and chroot build environments like Mock or local osc. Automatic resolution without additional project configuration does not happen here, but it is not always possible. Locally I created a symlinks for pc-files: **_cpp-httplib-headers.pc_** and **_cpp-httplib-shared.pc_** for the relevant flavors in the same directories. Now it is possible to refer to the desired version of the package directly and it is not necessary to change the project code, because the original **_cpp-httplib.pc_** is also present. What do you think about it? Maybe it's worth including this in meson install configuration? Or is this approach incorrect?
See [obs://devel:libraries:c_c++/cpp-httplib](https://build.opensuse.org/package/show/devel:libraries:c_c++/cpp-httplib)

**Comment by yhirose** [comment]
@Tachi107 do you have any thought about it since you know very well about meson build system? Thanks!

**Comment by Tachi107** [comment]
Why would you need a specific flavour? Can't you always use e.g. the compiled variant?

**Comment by svalx** [comment]
> Why would you need a specific flavour? Can't you always use e.g. the compiled variant?
I try to provide all variants for end-users, any of them may be needed for different projects.

**Comment by Tachi107** [comment]
Conceptually, all you need to do to consume a library is to run `pkg-config --cflags --libs depname`, whether the command outputs a `-lname` flag or not you shouldn't really care. As a end user, providing both variants is confusing to me - do the two packages conflict? Which one should I install? Questions that in the end do not really matter, because the way to consume the dependency is exactly the same.

I've never seen a practical example where providing both library variants would be needed (apart from having code that just `#include`s the header file without running pkg-config or otherwise checking if the library is available, but that is a bug on its own). If there is, please let me know, but I'd suggest you to simply provide only one option.

The advantage of header-only "libraries" is that you can easily drop a `.h` file in your project's folder and you're done. On the other hand, if you're going to use dependencies provided by a package manager you should be ready to consume it properly.

**Comment by svalx** [comment]
We are talking about a package repository where both versions of the library are placed. Both of them provide _**pkgconfig(cpp-httplib)**_. Let's say there is a third package that needs a compiled cpp-httplib. In the spec-files, the preferred way to specify devel dependencies is pkgconfig(*). I write _**BuildRequires: pkgconfig(cpp-httplib)**_ there and this leads to an error, because the system cannot choose which of the packages to install in the build environment - compiled or header. If the compiled version provided a pkgconfig file with a different name, such a problem would not occurred. This is only necessary during dependency resolution at the build environment creation level.

**Comment by Tachi107** [comment]
I do understand this (I maintain the Debian package of cpp-httplib), but my point was that you shouldn't be packaging two different flavours, but only either the header-only or, preferably, only the compiled one.

As I said in my previous comment, unless there's a pragmatic reason to include both variants, I'd suggest you to simply provide only one option.

**Comment by svalx** [comment]
Why do you think that? Some projects use the header version - for example, yuzu, others may use the compiled version. If the repository will provide any type, it will be convenient for everyone... Am I not right?

**Comment by Tachi107** [comment]
A given project does not usually explicitly request a specific flavour (for instance, yuzu just runs [this CMake Find Module](https://github.com/yuzu-emu/yuzu/blob/770a49616d9f9772ffd6c1648a25da4abd4338e2/CMakeModules/Findhttplib.cmake), which checks for cpp-httplib via a CMake Config file and, if it fails, uses pkg-config - I maintain the yuzu Debian package too, and wrote that particular file).

What yuzu does, is using the _embedded_ `.h` file when the library is not found on the system.

When checking for a system-installed dependency, projects don't generally know, nor care, what flavour they'll get.

So, unless you're sure that also providing the header-only variant is required, please consider shipping only the compiled one in OpenSUSE. It'll simplify things, and also make SUSE more in line with what other distros ([Debian](https://salsa.debian.org/debian/cpp-httplib/-/blob/ad86f9ac586dffdb0759cd9b5cd591d4f1e7395d/debian/rules#L38) and [Fedora](https://src.fedoraproject.org/rpms/cpp-httplib/blob/f38/f/cpp-httplib.spec#_66)) do.

**Comment by svalx** [comment]
@Tachi107, thanks for the clarification. I followed the advice and disabled the header flavor build.

**Comment by yhirose** [comment]
@svalx, @Tachi107, so can I close this issue?

**Comment by Tachi107** [comment]
I think there's not much else to say, but I'd wait for the @svalx for a 
reply

**Comment by svalx** [comment]
> @svalx, @Tachi107, so can I close this issue?

Sure
