### ISSUE TITLE
SSLClient is hung by socket_mutex_ from time to time

### ISSUE THREAD

**Issue by george-liang** [yhirose/cpp-httplib#1492]
I am using cpp-httplib as client to send http request, I find the client is hung from time to time. I add some log to trace the flow and  find it is hung by socket_mutex_. See following call flow, it will cause dead lock. I check the latest code, it still has this issue even though lock_socket_and_shutdown_and_close() is refactored. Please have a look at this.

Call flow:
ClientImpl::send()
{
std::lock_guard<std::mutex> guard(socket_mutex_);
...
if (!is_alive) {
...
if (!scli.connect_with_proxy(socket_, res, success, error)){...}
...
}
}

SSLClient::connect_with_proxy()
{
...
return process_request(strm, req2, res2, false, error);
...
}

ClientImpl::process_request()
{
...
lock_socket_and_shutdown_and_close();
...
}

ClientImpl::lock_socket_and_shutdown_and_close()
{
...
std::lock_guard<std::mutex> guard(socket_mutex_);
...
}

**Comment by yhirose** [comment]
@george-liang thanks for the report. Could you provide the smallest possible code example to reproduce it? Then, I'll take a look at the problem. (Otherwise, it's pretty hard for me to confirm and debug the problem...)
Thanks!

**Comment by george-liang** [comment]
> 

Hi @yhirose ,
This issue does not always happen, it happens randomly, I create multiple threads, each thread has it's own client, so we can image that actually I am using a client in single thread.
The code is simple:

// create client instance
httplib::Client         cli;
  httplib::Headers headers = {
    { "Content-Type", "application/json" }
  };

  cli.set_default_headers( headers );
  cli.enable_server_certificate_verification(false);

  // Timeout
  cli.set_connection_timeout(5, 0); // 5 seconds
  cli.set_read_timeout(5, 0); // 5 seconds
  cli.set_write_timeout(5, 0); // 5 seconds

  // keep alive
  cli.set_keep_alive(true);

  // set proxy
  cli.set_proxy( MY_PROXY, MY_PORT );

// post message by cli
{
   while(true)
   {
      httplib::Result res = cli.Post( url.c_str(), content, nullptr/*content_type*/ );
    if ( res && res.error() == httplib::Error::Success && res->status == 200)
    {
      logd( "post ok" );
      rs = true;
    }
    else
    {
      logw( "post error res.error() );
      // we suppose that we have post correctly for the case of Error::Read
      if ( res.error() == httplib::Error::Read ) rs = true;;
    }
   }
}

I don't think it is easy for you to reproduce it. I have figured out the call flow, it is caused by the exception case: the connection is broken. See the code I post last time. simply, it is like below:

ClientImpl::send(in this function, It locks socket_mutex_ firstly) -> scli.connect_with_proxy() -> process_request() -> lock_socket_and_shutdown_and_close(in this function, it locks socket_mutex_ again, so it is dead lock)

The call flow above would have a chance to run in dead lock, it happens, you can check the source code. I know the source code does not have the function lock_socket_and_shutdown_and_close() any more, instead, it has following code, it is to say, it still try to lock socket_mutex_:
=====
  if (res.get_header_value("Connection") == "close" ||
      (res.version == "HTTP/1.0" && res.reason != "Connection established")) {
    // TODO this requires a not-entirely-obvious chain of calls to be correct
    // for this to be safe. Maybe a code refactor (such as moving this out to
    // the send function and getting rid of the recursiveness of the mutex)
    // could make this more obvious.

    // This is safe to call because process_request is only called by
    // handle_request which is only called by send, which locks the request
    // mutex during the process. It would be a bug to call it from a different
    // thread since it's a thread-safety issue to do these things to the socket
    // if another thread is using the socket.
    std::lock_guard<std::mutex> guard(socket_mutex_);
    shutdown_ssl(socket_, true);
    shutdown_socket(socket_);
    close_socket(socket_);

**Comment by george-liang** [comment]
@yhirose , I don't have a proposed solution for this issue. 
Since I am actually using client in single thread, I will comment this line std::lock_guard<std::mutex> guard(socket_mutex_); in ClientImpl::process_request() to have a test.

**Comment by yhirose** [comment]
@george-liang do you have any thought about this issue?

**Comment by yhirose** [comment]
@george-liang, could you try with the latest httplib.h in the master branch? It contains a couple of important fixes which might fix this issue as well. Thanks!

**Comment by yhirose** [comment]
@george-liang I'll close it in a few days unless I receive further information which confirms this still exits.

**Comment by george-liang** [comment]
@yhirose Since each thread has its own httpclient, I did some change to the httpclient(removed lock guard in ClientImpl::lock_socket_and_shutdown_and_close()) and this workaround works.

Yes, you can close this issue. I will test the master branch when I get a chance.

Thanks very much for you support.
