### ISSUE TITLE
SSL client fails when using OpenSSL 1.1.1u-dev

### ISSUE THREAD

**Issue by evansmal** [yhirose/cpp-httplib#1500]
I'm trying to compile the following application:

```cpp
#define CPPHTTPLIB_OPENSSL_SUPPORT

#include <httplib.h>

int main()
{
    httplib::Client cli("https://httpbin.org");
    const auto &result = cli.Get("/get");
    std::cout << result.error() << std::endl;
    return 0;
}
```

Compiling with OpenSSL 1.1.1f works as expected (1.1.1f is installed on my system in `/usr/lib/x86_64-linux-gnu/`):

```sh
$ clang++ main.cpp \
     /usr/lib/x86_64-linux-gnu/libssl.a \
     /usr/lib/x86_64-linux-gnu/libcrypto.a \
     -pthread -ldl
$ ./a.out
Success (no error) (0)
````

But if I test with OpenSSL 1.1.1u-dev  (which is installed on my system in `/usr/local/lib/`)::

```sh
$ clang++ main.cpp \
     /usr/local/lib/libssl.a \
     /usr/local/lib/libcrypto.a \
     -pthread -ldl
$ ./a.out
SSL server verification failed (10)
````

Is this a bug? I believe OpenSSL 1.1.1u-dev is the latest stable release which may explain why it doesn't work here.

**Comment by evansmal** [comment]
Version `1.1.1t` doesn't appear to work either. Might be an issue on my side - the system default works but not when I install manually.

**Comment by yhirose** [comment]
I have just installed 1.1.1t via Homebrew on my iMac and run the unit tests with it. I confirmed that everything worked fine. Hope you will find the actual cause of the issue.

**Comment by harsh-im** [comment]
@evansmal  have you found out the solution for this issue? I am getting similar issue while using cpp-httplib with android JNI.
