### ISSUE TITLE
Close connection call back

### ISSUE THREAD

**Issue by poor1017** [yhirose/cpp-httplib#1503]
Hi @yhirose 

I want to accept a persistent connection and do something when the connection is closing. How to add call back function to closing connection?

Thank you.

**Comment by yhirose** [comment]
@poor1017 this is no such a feature. But you could check if 'Connection' in a HTTP response is 'close' from a server.
https://github.com/yhirose/cpp-httplib/blob/75053bf8558a1ebfd3a249d9b9c55ad11fe09b31/test/test.cc#L3468-L3472

**Comment by poor1017** [comment]
@yhirose Thank you for your quick reply. 
On my server side, the persistent connection will maitain a session, so when closing the connection, I need to clean the session.

If the client send a "end session" request, I can clean the session normally, but if the client do NOT send this request, I need clean the session when the connection closed by myselfe. How to do this?

Thank you.

**Comment by poor1017** [comment]
Hi @yhirose

Could this issue be reopened?
