### ISSUE TITLE
File Descriptor (FD) exceeds from the limit after a while .

### ISSUE THREAD

**Issue by Rasoul-A** [yhirose/cpp-httplib#1505]
Ubuntu 20.04.1 
Sending Web socket Using Boost library 1.7
Handling http requests using cpp-httplib released on 2021.
File Descriptor increases up to a point more than the limit.
Then the subsequent http request will be failed by status code 500.
How do I solve this ? Why should we limit the FD ?

**Comment by yhirose** [comment]
That's an intended behavior. I think cpp-httplib isn't suitable in your situation. I recommend you to use libuv based libraries.
Also #215 and #1135 might help you.
