### ISSUE TITLE
Client POST parameter values are not encoded properly

### ISSUE THREAD

**Issue by hans-erickson** [yhirose/cpp-httplib#151]
When a POST request is received by the server, the function decode_url() is called on the parameter values to properly decode any encoded characters. This behavior seems to be correct.

However, on the client side, a matching encode_url() is not called on the parameter values. This can result in the key/value pairs being sent by the client in a way that can be parsed incorrectly by the server.

A suggested patch is attached.

[encode_patch.txt](https://github.com/yhirose/cpp-httplib/files/3195593/encode_patch.txt)

**Comment by yhirose** [comment]
@hans-erickson, thanks for the report. Could you send it as a pull request?

**Comment by yhirose** [comment]
Closed by #151.
