### ISSUE TITLE
Security?

### ISSUE THREAD

**Issue by blitz-research** [yhirose/cpp-httplib#1510]
Hi,

I am really enjoying using httplib and would like to continue using it in a large-ish project. 

A lot of what I will be doing involves dynamically generated content, which I understand will be more or less up to me to make secure, but I'd also like to use httplib to provide a simple 'static' server using code like this:

```
auto server = new httplib::Server();

server->set_mount_point("/", rootDir.u8string());

server->set_file_request_handler([](const httplib::Request& request, httplib::Response& response) { //
    log() << "### Server file request:" << request.path;
});

log() << "### Server Listening...";

server->listen(host, port);
```

But how secure is this? It seems simple and safe enough to me, but is there any chance people will be able to access files 'above' rootDir by using '../' in URLs or something? Or should I be validating requests in the file request handler somehow?

Anything else I should be wary of?

Bye!
Mark

**Comment by yhirose** [comment]
@blitz-research, thanks for the question. `is_valid_path` checks if any actual file access must be 'below' the root directory. I think you can easily confirm it with your example code above. Hope it helps!
https://github.com/yhirose/cpp-httplib/blob/bab5c0e907f84d0af2ed038eca6b9fdbc5af314e/httplib.h#L2110-L2112
