### ISSUE TITLE
Thread occupied

### ISSUE THREAD

**Issue by yangzijianGit** [yhirose/cpp-httplib#1511]
No more connections can be opened to this service when the message processing is chunked because the threads are full.
`
    svr.Get("/event2", [&](const Request& /*req*/, Response& res) {
        cout << "connected to event2..." << endl;
        res.set_chunked_content_provider("text/event-stream",
            [&](size_t /*offset*/, DataSink& sink) {
                ed.wait_event(&sink);
                return true;
            });
        });
`

**Comment by yangzijianGit** [comment]
I could change the number of threads in the TaskQueue to 1000, but that wouldn't be a good way to handle it

**Comment by yhirose** [comment]
@yangzijianGit, thanks for the feedback, but I don't understand what 'because the threads are full' means...

**Comment by PixlRainbow** [comment]
They mean that since httplib dedicates a thread per request, that means that long running requests such as SSE streams or media streams will occupy threads, which limits the number of concurrent clients to the number of available threads

**Comment by yhirose** [comment]
Please see the comment from @PixlRainbow. So it's a limitation. You can also consider to provide your own TaskQueue implementation for better thread management instead of using the default `ThreadPool`.
