### ISSUE TITLE
When the port conflicts, listen will not report an error and fall into a dead loop

### ISSUE THREAD

**Issue by fuzhufang** [yhirose/cpp-httplib#1514]
svr.listen(ip, port)
Use in windows
When the port conflicts, listen will not report an error and fall into a dead loop
![image](https://user-images.githubusercontent.com/6743583/222972410-2bffa4e1-995b-44a6-bf42-f0ad411bf470.png)

**Comment by yhirose** [comment]
@fuzhufang, could you provide the smallest possible code example to reproduce the problem? Thanks!

**Comment by yhirose** [comment]
@fuzhufang I now understand your situation better. It's an intended behavior, since `SO_REUSEPORT` socket option is used as default. You can disable port sharing by controlling socket options by using `set_socket_options` method.
You can see #759, #506, #250 for more detail. Thanks!

**Comment by fuzhufang** [comment]
I see. Thank you very much for your answer!
