### ISSUE TITLE
use of https schema fails to build on Ubuntu

### ISSUE THREAD

**Issue by timrichardson** [yhirose/cpp-httplib#1520]
Hi. I downloaded the latest release of cpp-httplib and installed it earlier today.
I am using system libraries for everything else
Ubuntu 22.10

```
tim@yellow:~/Downloads/cpp-httplib-0.12.0/test$ openssl version
OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)

I installed the lib-crypto-dev package too (8.7.0+git220824-1)

```

the test suite passes. 

http client works, but when I try to use https, trouble. 

I am an absolute beginner with C++, getting this far feels like an amazing achievement.
I am now however confused. I can't get any meaningful insight into this problem. 

```
#define CPPHTTPLIB_OPENSSL_SUPPORT
#include <httplib.h>

/*
 cmake .
 sudo cmake -P cmake_install.cmake

 */

using namespace std;
int main() {
    cout << "Hello, World!" << endl;
    // HTTP
    httplib::Client cli("http://cpp-httplib-server.yhirose.repl.co");
    auto res = cli.Get("/hi");
    res->status;
    res->body;
    // HTTPS
    httplib::Client cli_https("https://cpp-httplib-server.yhirose.repl.co");

    auto res_https = cli_https.Get("/hi");
    res_https->status;
    res_https->body;
    return 0;
}
```

when trying to build and run that above: 
(using CLion)

```


====================[ Build | untitled | Debug ]================================
/home/tim/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/bin/cmake/linux/x64/bin/cmake --build /home/tim/CLionProjects/untitled/cmake-build-debug --target untitled -j 6
[1/1] Linking CXX executable untitled
FAILED: untitled 
: && /usr/bin/c++ -g  CMakeFiles/untitled.dir/main.cpp.o -o untitled   && :
/usr/bin/ld: CMakeFiles/untitled.dir/main.cpp.o: in function `httplib::detail::message_digest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, evp_md_st const*)':
/usr/local/include/httplib.h:4359: undefined reference to `EVP_MD_CTX_free'
/usr/bin/ld: /usr/local/include/httplib.h:4359: undefined reference to `EVP_MD_CTX_new'
/usr/bin/ld: /usr/local/include/httplib.h:4364: undefined reference to `EVP_DigestInit_ex'
/usr/bin/ld: /usr/local/include/httplib.h:4365: undefined reference to `EVP_DigestUpdate'
/usr/bin/ld: /usr/local/include/httplib.h:4366: undefined reference to `EVP_DigestFinal_ex'
/usr/bin/ld: CMakeFiles/untitled.dir/main.cpp.o: in function `httplib::detail::MD5(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/local/include/httplib.h:4378: undefined reference to `EVP_md5'

```

**Comment by timrichardson** [comment]
this is an invalid bug report, sorry. I needed to explicitly add the openssl library to cmakelist.txt

find_package(OpenSSL REQUIRED)
target_link_libraries(httpclient OpenSSL::SSL)

**Comment by sum01** [comment]
@timrichardson what does your `CMakeLists.txt` look like? You shouldn't need to manually link the lib against OpenSSL, it should do it for you if done correctly.

If you used Cmake to install the library and didn't just manually install the header into your includes, something like `find_package(httplib COMPONENTS OpenSSL REQUIRED)` should be enough. Components are supported since v0.12.1, before that you must either use the build option `HTTPLIB_REQUIRE_OPENSSL=true` when invoking the build command, or do `set(HTTPLIB_REQUIRE_OPENSSL ON)` before `find_package(httplib REQUIRED)`.

The docs at the top of https://github.com/yhirose/cpp-httplib/blob/master/CMakeLists.txt should be helpful for proper usage.
