### ISSUE TITLE
Getting the headers of an user-cancelled request 

### ISSUE THREAD

**Issue by VincenzoLaSpesa-Eaton** [yhirose/cpp-httplib#1521]
What I'm trying to do is this:
1. Start a get request
2. Read some data 
3. Stop the request from the `httplib::ContentReceiver` ( by returning false )
4. get the header of the response, the data I've read and do some stuff

Currently httplib will raise an error, even if I cancelled the request.
Is there a way for getting the header anyway? i can't directly use `Client::send` as the server wants digest authentication.

**Comment by yhirose** [comment]
@VincenzoLaSpesa-Eaton, could you show the smallest possible code example to reproduce it? Thanks.

**Comment by VincenzoLaSpesa-Eaton** [comment]
I've discovered that I can do it by using the httplib::ResponseHandler. Now i understand more the design choices and they make more sense than what I had in mind.

I'll to create a minimal example if you want, just for documentation.
We can close the issue.

**Comment by yhirose** [comment]
@VincenzoLaSpesa-Eaton glad to hear you found the solution. I don't need an example any more. Thanks!
