### ISSUE TITLE
switch statement of strings with _t operator causes compiler warnings

### ISSUE THREAD

**Issue by JohannesFluegelHighyag** [yhirose/cpp-httplib#1528]
Your method

```
inline bool can_compress_content_type(const std::string &content_type) {
	using udl::operator""_t;

	auto tag = str2tag(content_type);

	switch (tag) {
	case "image/svg+xml"_t:
	case "application/javascript"_t:
	case "application/json"_t:
	case "application/xml"_t:
	case "application/protobuf"_t:
	case "application/xhtml+xml"_t: return true;

	default:
		return !content_type.rfind("text/", 0) && tag != "text/event-stream"_t;
	}
}
```

causes the compiler warnings ` warning C4307: '*': integral constant overflow` for all lines with `case`. Something does not seem ok with your `_t` operator and the `str2tag()` function.

I have fixed it by using oldscool string comparisons:

```
inline bool can_compress_content_type(const std::string &content_type) {
	return (!content_type.rfind("text/", 0) && content_type != "text/event-stream") ||
		content_type == "image/svg+xml" ||
		content_type == "application/javascript" ||
		content_type == "application/json" ||
		content_type == "application/xml" ||
		content_type == "application/protobuf" ||
		content_type == "application/xhtml+xml";
```

**Comment by yhirose** [comment]
@JohannesFluegelHighyag thanks for the feedback, but the current implementation is much faster than your proposal. What compiler are you using?

**Comment by JohannesFluegelHighyag** [comment]
@yhirose I am using Visual Studio 2017. I am with you, it is a good idea to use switch statements and user defined literals, that convert strings into whole numbers that can be used in the switch statements. But there must be an overflow while computing these whole numbers, if the string is too long. E. g. `case "123456"_t` is ok, but `case "1234567"_t` produces an overflow. I assume something is not ok with your "hash function" `str2tag_core()`. But the main thing is, that the whole numbers in the case clauses are unique.

**Comment by yhirose** [comment]
Are you compiling with 32bit architecture, or 64?

**Comment by JohannesFluegelHighyag** [comment]
64 bit.

**Comment by JohannesFluegelHighyag** [comment]
Have a look at

```
inline constexpr unsigned int str2tag_core(const char *s, size_t l,
	unsigned int h) {
	return (l == 0) ? h
		: str2tag_core(s + 1, l - 1,
		(h * 33) ^ static_cast<unsigned char>(*s));
}
```

The overflow may happen in `(h * 33)`. You may fix it by using `(0xffff & h * 33)`; in this case the warnings do not appear anymore.

**Comment by yhirose** [comment]
Thanks for the observation. Could you try it on your environment, since I have already switched to VS2022 and don't have VS2017 any more. If your suggestion works, could you send a pull request?

**Comment by JohannesFluegelHighyag** [comment]
I can do it.

But I still have concerns with the concept, that you don't compare the strings directly, but use a hash function and a switch construct instead, because collisions are theoretically possible.

**Comment by JohannesFluegelHighyag** [comment]
Sorry, but I did not succeed in creating a pull request, because I cannot push my new branch. You have to do it by yourself.

**Comment by JohannesFluegelHighyag** [comment]
I guess I am not allowed to create new branches.

**Comment by JohannesFluegelHighyag** [comment]
The most accurate solution would be something like
```
inline constexpr unsigned int str2tag_core(const char *s, size_t l,
	unsigned int h) {
	return (l == 0) ? h
		: str2tag_core(s + 1, l - 1,
		((numeric_limits<unsigned int>::max() >> 6) & h * 33) ^ static_cast<unsigned char>(*s));
}
```
Even if `h` is big, `(numeric_limits<unsigned int>::max() >> 6) & h * 33` will not cause an overflow.

**Comment by yhirose** [comment]
> Sorry, but I did not succeed in creating a pull request, because I cannot push my new branch. You have to do it by yourself.

First of all, you have to make a fork of cpp-httplib and make a branch on your fork and commit the fix, then make a pull request and send it to cpp-httplib. Here is the documentation: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

All the pull requests from other contributors in the Pull requests page have been made in this way. Thanks!
