### ISSUE TITLE
encode_url for ":"

### ISSUE THREAD

**Issue by zhubeilife** [yhirose/cpp-httplib#1530]
https://github.com/yhirose/cpp-httplib/blob/88a9278872c3a06702c0c3af99b5deb5e6c0442f/httplib.h#L2167
```c++
inline std::string encode_url(const std::string &s) {
    std::string result;
    result.reserve(s.size());

    for (size_t i = 0; s[i]; i++) {
        switch (s[i]) {
            case ',': result += "%2C"; break;
            **case ':': result += "%3A"; break; // ok? probably...**
            case ';': result += "%3B"; break;
            default:
                break;
        }
    }

    return result;
}
```

Hi, may I know why this ';' is commented?

I have one issue where I use cpp-httplib as server and python as a client.

for python side
```python
import request
import datetime

url = http://0.0.0.0
query = {"time": datetime.datetime.now().isoformat()}
r = request(url, params=query)
```

the time string format is 
'2023-03-17T14:18:24.161765'

but the python side generates the URL with urlencode, and the finally URL is 

http://0.0.0.0?time=2023-03-17T14%3A18%3A24.161765

thus I have some issues for call the encode_url()

**Comment by yhirose** [comment]
@zhubeilife the decision came from #303. Could you explain more about the problem on your server?

**Comment by zhubeilife** [comment]
@yhirose I use the patch from https://github.com/yhirose/cpp-httplib/pull/952 from Digest Support on the server side.
For the md5 check part, it should use the URL for MD5 calculation. Where the server side uses encode_url function call which leaving the ":" as %3A. So the MD5 results is different from the client part.
I am not sure do we need to uncomment or I just add another encode_url function.

```c++
 // case ':': result += "%3A"; break; // ok? probably... 
```

**Comment by yhirose** [comment]
@zhubeilife I think you can use `params_to_query_str` or `encode_query_param` in your patch code. Hope it helps!
