### ISSUE TITLE
Digest Authentication ERROR

### ISSUE THREAD

**Issue by chen-github1** [yhirose/cpp-httplib#1539]
{
httplib::SSLClient cli("http://xxxxx");
 cli.set_digest_auth("user", "password");
}

log: HTTP error: Could not establish connection, 

http client in the digest authentication, print this log, please ask, this log may be what reason, thanks!

**Comment by yhirose** [comment]
@chen-github1 could you take a look at example in `test/test.cc`. Hope it helps!
