### ISSUE TITLE
Support SSL client certificates

### ISSUE THREAD

**Issue by PixlRainbow** [yhirose/cpp-httplib#154]
Does cpp-httplib currently support?

1. (server side) requesting the client to submit a "client certificate" or
2. (client side) submitting a "client certificate" if requested to do so by a server
3. (server side) if (1.) is true, rejecting client if the client did not submit a "client certificate"

**Comment by yhirose** [comment]
@PixlRainbow, you are asking for the feature like `curl -E CERT_FILE`, right?
I haven't implemented the feature, yet... I put the 'enhancement' label for my reminder.
Thanks for your feedback!

**Comment by PixlRainbow** [comment]
I've implemented this feature in #162 but through testing I've noticed that Firefox does not appear to be able to handle intermediary-signed client certificates.

## Tested Conditions
| Certificate  | Client Type                                               | Result                            |
|--------------|-----------------------------------------------------------|-----------------------------------|
| Signed by CA | Firefox                                                   | SSL_ERROR_HANDSHAKE_FAILURE_ALERT |
| Self Signed  | Firefox                                                   | OK                                |
| Signed by CA | cURL,<br>OpenSSL s_client,<br>Google Chrome,<br>cpp-httplib client | OK                                |
| Self Signed  | cURL,<br>OpenSSL s_client,<br>Google Chrome,<br>cpp-httplib client | OK                                | 

Searching online for related issues brings up results that mention Firefox has a strange policy where the client certificate's issuer must match the host's SSL certificate issuer, so it may just be me not creating the certificates correctly.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the PR. I'll put comments on #162 instead of here.

**Comment by yhirose** [comment]
Fixed by #162
