### ISSUE TITLE
Can the server return the result asynchronously?

### ISSUE THREAD

**Issue by shadowbanewuha** [yhirose/cpp-httplib#1543]
I want the server to receive a request, process the request asynchronously, and return the result to the client. Can this be achieved?

**Comment by PixlRainbow** [comment]
httplib is a HTTP/1.1 server. The HTTP/1.1 protocol standard only allows for synchronous calls. However, you may build an asynchronous API on top of synchronous calls yourself by following the [async request-reply pattern](https://learn.microsoft.com/en-us/azure/architecture/patterns/async-request-reply).

The server responds to the first request immediately with a statement that it has accepted or rejected the request for further processing, with a job/task/queue number. The client then sends another request later with its assigned number and the server responds with the completed result. If the result is not yet ready by the second request, the server should return a statement that the client should come back later.

If you prefer not to repeatedly send requests to check for completion, you can use [Server-Sent Events stream](https://github.com/yhirose/cpp-httplib/blob/master/README.md#server-sent-events) to allow the client to wait until the server sends an event indicating the result is ready.
