### ISSUE TITLE
SIGSEGV from SSL_peek when using proxy

### ISSUE THREAD

**Issue by caozhanhao** [yhirose/cpp-httplib#1544]
```c++
#include <iostream>
#define CPPHTTPLIB_OPENSSL_SUPPORT
#include "cpp-httplib/httplib.h"
int main()
{
  httplib::SSLClient cli("google.com");
  cli.set_proxy("172.18.144.1", 10809);
  auto res = cli.Get("/");
  std::cout << res->body << std::endl;
  return 0;
}
```
some call stack info:
- SSL_peek 0x00007ffff7c64be7
- httplib::ClientImpl::process_request httplib.h:6825
- <lambda#1>::operator()(httplib::Stream &) const httplib.h:7987
- httplib::detail::process_client_socket(int, long, long, long, long, std::function<bool (httplib::Stream &)>) httplib.h:2625
- httplib::SSLClient::connect_with_proxy httplib.h:7981
- httplib::ClientImpl::send_ httplib.h:6379
- httplib::ClientImpl::send httplib.h:6339
- httplib::ClientImpl::send_ httplib.h:6444
- httplib::ClientImpl::Get(const std::string &, const std::multimap<std::string, std::string, httplib::detail::ci> &, std::function<bool (unsigned long, unsigned long)>) httplib.h:6982
- httplib::ClientImpl::Get httplib.h:6963

![issue](https://user-images.githubusercontent.com/64004730/229168520-1fee791e-ac71-4e09-b1c1-c7b2325fd1a8.png)
socket_.ssl is NULL here.

Is this an issue with my proxy? Should there be some error handling?

**Comment by yhirose** [comment]
@caozhanhao, v0.12.2 should fix the problem.
