### ISSUE TITLE
Using set_content_provider with length of 0 makes it infinitely loop

### ISSUE THREAD

**Issue by gtnardy** [yhirose/cpp-httplib#1545]
Hey, I got an interesting case when trying to send an empty file through set_content_provider, 

I have a thing simple as this just to clarify (reduced code):

```cpp
struct NFile
{
	std::string Data;
	std::uint64_t Size;
};

NFile* File;

// Load file content into File.data string.
// ...

Res.set_content_provider(
	File->Size,
	"application/octet-stream",
	[File](std::size_t Offset, std::size_t Length, httplib::DataSink& Sink)
	{
		Sink.write(&File->Data[Offset], std::min(Length, 1024 * 1024)); // 1 MB Chunks
		return true;
	}
);
```

But if string is empty (file is empty), the content_provider keeps looping infinitely (triggering the callback), but the request never finishes in fact.

Not sure if this should be something I would need to treat (I'm going to), or if it can enlighten that there's a bug somewhere in the lib internally.

**Comment by PixlRainbow** [comment]
you can return false in your content provider to cancel the response as a temporary fix, but zero length is likely a case httplib should check for as well internally

**Comment by yhirose** [comment]
@gtnardy thanks for the report!
