### ISSUE TITLE
What is the meaning of connection timeout?

### ISSUE THREAD

**Issue by poor1017** [yhirose/cpp-httplib#1549]
Hi @yhirose 

My server need some time to process the request, so my client need wait.

I see the default value of `connection_timeout_sec_` is `CPPHTTPLIB_CONNECTION_TIMEOUT_SECOND` which is `300`.
So, I think my client will wait for `300` seconds.
But, why my client quit in less than one second?

Here is my client code:
```cpp
HttpClient::HttpClient(std::string &server_ip,
                       int server_port,
                       std::string &uri,
                       std::string &content_type,
                       std::string &payload)
    : server_ip_(server_ip),
      server_port_(server_port),
      uri_(uri),
      content_type_(content_type),
      payload_(payload)
{
    // HTTP
    cli_ = std::make_unique<httplib::Client>(server_ip_, server_port_);
}

int
HttpClient::Init()
{
    return 0;
}

httplib::Result
HttpClient::Start()
{
    httplib::Result res = cli_->Post(uri_, payload_, content_type_);

    return res;
}
```

**Comment by yhirose** [comment]
@poor1017, you can see a number of unit tests using `set_connection_timeout` in `test/test.cc`. Hope those examples help you.
