### ISSUE TITLE
http put digest authentication　ret 401

### ISSUE THREAD

**Issue by wangxiaoer3924** [yhirose/cpp-httplib#1550]
When I use cpp-httplib for summary authentication, it returns 401. I compared the process of curl implementation and would like to ask how I can call it to authenticate successfully

`
#define CPPHTTPLIB_OPENSSL_SUPPORT
#include <httplib.h>
#include <iostream>
#include "ISAPI.hpp"
using namespace std;

int main(void) {
    httplib::Client cli("192.168.96.245", 80);
    cli.set_digest_auth("admin", "dixin_Admin123");
    cli.set_connection_timeout(0, 300000); // 300 milliseconds
    cli.set_read_timeout(5, 0); // 5 seconds
    cli.set_write_timeout(5, 0); // 5 seconds

    if (auto res =cli.Put("/ISAPI/PTZCtrl/channels/1/homeposition/goto") ){
        cout << res->status << endl;
        cout << res->get_header_value("Content-Type") << endl;
        cout << res->body << endl;
    } else {

        cout << "error code: " << res.error() << std::endl;
        auto result = cli.get_openssl_verify_result();
        if (result) {
            cout << "verify error: " << X509_verify_cert_error_string(result) << endl;
        }
    }
//    ISAPI::PTZCtrlGotoHomeposition("192.168.96.245","admin", "dixin_Admin123");
    while (1) {
        usleep(10000);
    }
    return 0;
}
`
[wireshark.zip](https://github.com/yhirose/cpp-httplib/files/11175651/wireshark.zip)

Through packet capturing, I found that this field is missing. How should I handle this

cnonce="ZGZlMjI5MGMzNGI3MjcyNTBiMzdiNmM4NTcxOGMxZWE="

**Comment by yhirose** [comment]
@wangxiaoer3924 thanks for the feedback. Hope the following living example can help you!

https://github.com/yhirose/cpp-httplib/blob/985ceba525a7a1d566f2d8ba64930907bc60fef3/test/test.cc#L779-L825

**Comment by wangxiaoer3924** [comment]
I have already referred to this, but it still doesn't work
