### ISSUE TITLE
Response for full threadpool

### ISSUE THREAD

**Issue by poor1017** [yhirose/cpp-httplib#1553]
Hi @yhirose 

If the server has 4 threads to process requests, and there are 5 requests arrive at the same time, how to response to the 5th request? I just want to response: `No resource avaliable.`

Thank you!

**Comment by poor1017** [comment]
Request processing is time consuming, and client will keep connection to wait for responsing.

**Comment by yhirose** [comment]
That's totally up to a TaskQueue implementation. The default one just keeps in its queue, and wait until any thread becomes available.

**Comment by poor1017** [comment]
Maybe I can allocate an extra thread from threadpool for responsing thread unavaliable.
