### ISSUE TITLE
send cookies by set_header

### ISSUE THREAD

**Issue by KSdong** [yhirose/cpp-httplib#1555]
i want to send a post request. And i want to keep this session all the time  ，until  close program.
so i want to set cookie(include sessionid) in header.
`
httplib::Headers cliHeaders{ {"Accept","application/xhtml+xml;v=2.0"},{ "Set-Cookie",[-http-session-=52::http.session::689dc5618e596140ee14ed4ad0908269; path=/; domain=127.0.0.1; httponly],[ABBCX=43; path=/; domain=127.0.0.1; httponly] } };
auto res = cli.Post("/rw/motionsystem/mechunits/ROB_1?action=mechunit-position", cliHeaders, + (TCHAR_TO_UTF8(*ResultString)),"application/x-www-form-urlencoded");`

At first, I wrote a program like this, but I couldn’t keep a session. The server returned a new session in the cookie. Is there something wrong with the cookie format I sent?

**Comment by KSdong** [comment]
Using Postman to send a POST request can maintain a session ID.
the cookies in postman like this：
![image](https://user-images.githubusercontent.com/84620929/231055106-0a031610-d7c4-406c-9cdd-786e817bd9f6.png)
![image](https://user-images.githubusercontent.com/84620929/231055131-46620b5d-4ed4-4a3d-9a4a-cf42a8ede739.png)

**Comment by PixlRainbow** [comment]
`Set-Cookie` is the header used by the server to indicate to the client that it should update it's local cookie. Since you are programming a client, you should be using `Cookie` header instead to indicate to the server the current state of the client local cookie.

**Comment by KSdong** [comment]
> Cookie

Thank you very, very, very much. Your answer was really concise and efficient。 i solved my problem
