### ISSUE TITLE
Any method to use my own custom file loader for static files?

### ISSUE THREAD

**Issue by TechArtLife** [yhirose/cpp-httplib#1556]
My static files cannot been assessed directly from system filesystem. Any method to use custom file loader?

**Comment by yhirose** [comment]
@TechArtLife there is no method to handle custom fie loaders. The static file server feature only cares for the OS file system.

https://github.com/yhirose/cpp-httplib/blob/c2e156e0e0e6af7df6971456255044197678a982/httplib.h#L5685-L5686
