### ISSUE TITLE
Compile failed when building httplib with mingw

### ISSUE THREAD

**Issue by faushine** [yhirose/cpp-httplib#1561]
PS D:\safetool\SafeTool\build> mingw32-make
Consolidate compiler generated dependencies of target SafeTool
[  7%] Building CXX object src/CMakeFiles/SafeTool.dir/main.cpp.obj
In file included from C:/Users/IDEA/.conan/data/cpp-httplib/0.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/httplib/httplib.h:152,
                 from D:\safetool\SafeTool\src\http/HttpServer.h:3,
                 from D:\safetool\SafeTool\src\main.cpp:6:
D:/mingw64/x86_64-w64-mingw32/include/winsock2.h:15:2: warning: #warning Please include winsock2.h before windows.h [-Wcpp]
   15 | #warning Please include winsock2.h before windows.h
      |  ^~~~~~~
In file included from C:/Users/IDEA/.conan/data/cpp-httplib/0.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/httplib/httplib.h:151:
D:/mingw64/x86_64-w64-mingw32/include/io.h:21:9: error: '#pragma' is not allowed here
   21 | #pragma pack(push,_CRT_PACKING)
      |         ^~~~
C:/Users/IDEA/.conan/data/cpp-httplib/0.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/httplib/httplib.h: In function 'bool httplib::detail::is_file(const std::string&)':
C:/Users/IDEA/.conan/data/cpp-httplib/0.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/httplib/httplib.h:1995:10: error: '_access_s' was not declared in this scope
 1995 |   return _access_s(path.c_str(), 0) == 0;

**Comment by faushine** [comment]
cmake file:
cmake_minimum_required (VERSION 3.0)
project (SafeTool)

set(CSP_LIBRARY_NAME "ShuttleCsp11_3000GM.dll")
set(CSP_LIBRARY_PATH "${LIB}/Csp/lib_x64")
set(CSP_LIBRARY "${CSP_LIBRARY_PATH}/${CSP_LIBRARY_NAME}")

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

find_package(httplib)
find_package(OpenSSL)
find_package(nlohmann_json)

file(GLOB CPP_FILES "*.cpp")
file(GLOB CPP_MNG_FILES "./mangers/*.cpp")
file(GLOB CPP_COM_FILES "./common/*.cpp")

add_executable(SafeTool ${CPP_MNG_FILES} ${CPP_COM_FILES} ${CPP_FILES} )

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -static-libgcc -static-libstdc++")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static")

target_link_libraries(SafeTool PRIVATE ${CSP_LIBRARY} wsock32 ws2_32 crypt32 OpenSSL::SSL OpenSSL::Crypto nlohmann_json::nlohmann_json httplib::httplib)

target_include_directories(SafeTool PRIVATE ${ROOT}/Include ./ ./mangers ./common)

**Comment by JamesBremner** [comment]
`target_link_libraries(SafeTool PRIVATE ${CSP_LIBRARY} wsock32 ws2_32 crypt32 OpenSSL::SSL OpenSSL::Crypto`

There libraries are in the wrong order.  See #1669 for details.
