### ISSUE TITLE
Any reason that Params doesn't keep an order?

### ISSUE THREAD

**Issue by bodzio131** [yhirose/cpp-httplib#1562]
I would like to ask you if there is any particular reason to not keep url params order, particularly to have `using Params = std::multimap<std::string, std::string>;` instead for example `using Params = std::vector<std::pair<std::string, std::string>>;` ?
 I've just needed to iterate `Request::params` and realized it doesn't keep an order.

**Comment by yhirose** [comment]
If a parameter list becomes longer, it is faster to look up an item using std::multimap (binary search) than using std::vector (linear search). Additionally, the HTTP specification does not require that the order of query parameters be maintained.

**Comment by bodzio131** [comment]
> If a parameter list becomes longer, it is faster to look up an item using std::multimap (binary search) than using std::vector (linear search). 

This was my first thought, and next was: how long a list of parameters should be to see any noticeable gain?

>Additionally, the HTTP specification does not require that the order of query parameters be maintained.

I was looking if it strictly prohibits maintaining order, and didn't find it. In my case the order was crucial.

Anyway, just shared this for your consideration. Patching the lib needs just few lines of code so any can do this if needed.

Thanks!
