### ISSUE TITLE
how to support multicast?

### ISSUE THREAD

**Issue by tms2003** [yhirose/cpp-httplib#1565]
I want to use cpp-httplib for multicast onvif.my  code like this:
```



  const char* multicast_ip = "239.255.255.250";
int port = 3702;

httplib::Client client2(multicast_ip, port);
auto res2 = client2.Get("/"); // 发送GET请求到组播地址
if (!res2) {
        cerr << "Error: network." << endl;
        return -1;
    }


```

so,I got Error: network.this seem that cpp-httplib cannot support multicast? so, how can i do for this?

**Comment by yhirose** [comment]
cpp-httplib is supposed to work on TCP. I am not familiar to the multicasting though, it seems you need to find different socket libraries which work on UDP.
