### ISSUE TITLE
socket_mutex_ deadloack  

### ISSUE THREAD

**Issue by ramiazr** [yhirose/cpp-httplib#1571]
Hi, we encounter a deadlock with version v0.10.1, the deadlock is present also in master (v0.12.3)

call flow for v0.12.3 :
 
#1 inline bool ClientImpl::send_(Request &req, Response &res, Error &error) {
        **std::lock_guard<std::mutex> guard(socket_mutex_);**
#2 inline bool SSLClient::connect_with_proxy(Socket &socket, Response &res, bool &success, Error &error) {
#3 inline bool process_client_socket(socket_t sock, time_t read_timeout_sec,
                                  time_t read_timeout_usec,
                                  time_t write_timeout_sec,
                                  time_t write_timeout_usec,
                                  std::function<bool(Stream &)> callback) {
#4 inline bool ClientImpl::process_request(Stream &strm, Request &req,
                                        Response &res, bool close_connection,
                                        Error &error) {
    in line 6924
    **std::lock_guard<std::mutex> guard(socket_mutex_);  deadlock!**

**Comment by yhirose** [comment]
@ramiazr thanks for the report. Could you show the smallest possible example code which shows the issue, so that I can reproduce it for debugging?

**Comment by ramiazr** [comment]
I apologize, it is challenging to provide an exact setup . However, it appears that the issue originated from an internal error in the proxy. The proxy seems to have returned a response header with the field "Connection" set to "close."
which triggered the issue.

It's worth noting that it the setup uses SSL and proxy server.  
there is a possibility for this issue to happen, when using HTTP 1.0. However, in our specific case, the likelihood of this happening is relatively low.

**Comment by yhirose** [comment]
@ramiazr thanks for the additional information. For now, I am not working on it and make it close, since there is no way for me to see the problem... Please come back to this issue when you get more information. Thanks for your understanding!

**Comment by ramiazr** [comment]
Hi yhirose,
I am sorry to hear that you are closing this issue without resolving the
issue.

The code is clear and the deadlock is easy to understand, this is not an
intermittent issue

I may be able to provide you with a real call stack, if you are willing to
fix this issue.
Regards, Rami
