### ISSUE TITLE
Unit test fails

### ISSUE THREAD

**Issue by DarthGandalf** [yhirose/cpp-httplib#1573]
```
[ RUN      ] DigestAuthTest.FromHTTPWatch_Online
test.cc:812: Failure
Expected equality of these values:
  401
  res->status
    Which is: 502
[  FAILED  ] DigestAuthTest.FromHTTPWatch_Online (11329 ms)
```

version 0.12.4 on gentoo linux, amd64

though it's flaky, and on second attempt it succeeded

**Comment by yhirose** [comment]
Thanks for the report. In my experiences, www.httpwatch.org (and also httpbin.org) gets down once in a while, and we get 502 for a while (sometimes need to wait a few days). So far, there is nothing to do for it on our side... Do you have any clue?

**Comment by DarthGandalf** [comment]
Oh, that may explain it!

Could the test be hermetic instead, and reach only localhost?

**Comment by yhirose** [comment]
@DarthGandalf it's already possible to exclude such tests. Could you take a look at [this](https://github.com/yhirose/cpp-httplib/pull/1026)? Hope it helps.

**Comment by DarthGandalf** [comment]
Yep, that works, thanks
