### ISSUE TITLE
Does HTTPS support HTTP requests at the same time, and how

### ISSUE THREAD

**Issue by jiagushuai** [yhirose/cpp-httplib#158]
+ If I cannot receive HTTP requests, but only HTTPS requests, how can I modify them to support both

**Comment by jiagushuai** [comment]
+ 
![image](https://user-images.githubusercontent.com/29997741/58775580-bcf3f900-85f8-11e9-8ae1-87f060e26bd3.png)
+ 
![image](https://user-images.githubusercontent.com/29997741/58775598-d1d08c80-85f8-11e9-9cba-3ef72fc3a4f4.png)

**Comment by yhirose** [comment]
@jiagushuai, thanks for the question. Unfortunately, we cannot handle both HTTPS and HTTP request simultaneously with cpp-httplib.
