### ISSUE TITLE
Is there a POST SSE example？

### ISSUE THREAD

**Issue by WenchiLe** [yhirose/cpp-httplib#1584]
I want to call the openAI API，such as [chat](https://platform.openai.com/docs/api-reference/chat/create)。Since it is a POST API and it support SSE， how can I write a http client to get the stream data。

**Comment by PixlRainbow** [comment]
See #850 for workaround to use `ContentReceiver` in a POST request.
You can check the GET SSE client example for how to use `ContentReceiver` interface.
