### ISSUE TITLE
Client::set_connection_timeout doesn't work

### ISSUE THREAD

**Issue by WenchiLe** [yhirose/cpp-httplib#1588]
I want to use the SSE example([Server example](https://github.com/yhirose/cpp-httplib/blob/master/example/ssesvr.cc) and [Client example](https://github.com/yhirose/cpp-httplib/blob/master/example/ssecli.cc).).  I found that if the server doesn't write data back in time, the client will close the connect. So I did some test based on the SSE example. I made the serve sent data every 10s, and set the client's connection timeout to 20s.  As a result, the client didn't get any data and quit.
Here's the code:
client:
```
    auto client = Client("http://localhost:1234");
    client.set_connection_timeout(std::chrono::seconds(20));
    client.Get("/event1", [&](const char *data, size_t data_length) {
        std::cout << "client:" << string(data, data_length) << endl;
        return true;
        });
   cout << "end" << endl;
```
server:
```
  thread t([&] {
    int id = 0;
    while (true) {
      this_thread::sleep_for(chrono::milliseconds(10000));
      cout << "send event: " << id << std::endl;
      std::stringstream ss;
      ss << "data: " << id << "\n\n";
      ed.send_event(ss.str());
      id++;
    }
    //ed.send_event("[DONE]");
  });
```
So how can I get the server's sse,(while curl can work).

**Comment by yhirose** [comment]
Thanks for the report. You should use `set_read_timeout` instead.

**Comment by WenchiLe** [comment]
`set_read_timeout` works！Thank you so much！
