### ISSUE TITLE
How to set response headers

### ISSUE THREAD

**Issue by jiagushuai** [yhirose/cpp-httplib#159]
Access will cross domain, how do I set the response header
+ Error is as follows
![image](https://user-images.githubusercontent.com/29997741/58787199-df4b3e00-861b-11e9-9bb9-f3bca6eb8dc0.png)
+ I know to add the following request headers, but I don't know how to add each response header
![image](https://user-images.githubusercontent.com/29997741/58787271-0dc91900-861c-11e9-9151-0c7eafb50b75.png)
Looking forward to your reply

**Comment by yhirose** [comment]
You can use `set_header` on `Response`. Thank you.

**Comment by jiagushuai** [comment]
+ I'm sorry I didn't make myself clear。
+ I tried to set it up, but maybe I didn't set it right, so I kept returning 404
![image](https://user-images.githubusercontent.com/29997741/58844541-37c91c80-86aa-11e9-847c-d75833751040.png)
## Should I set it somewhere else?

**Comment by jiagushuai** [comment]
+ Go directly to `set_error_handler`,Where do I set set_header on Response
![image](https://user-images.githubusercontent.com/29997741/58844680-e2413f80-86aa-11e9-990e-0edadc642be0.png)

**Comment by jiagushuai** [comment]
+ I set this, but it doesn't seem to work
![image](https://user-images.githubusercontent.com/29997741/58845759-fa1ac280-86ae-11e9-9e1b-9dbeb228eeba.png)

**Comment by yhirose** [comment]
You are doing fine with `set_header` in your code. The following is enough actually.

```cpp
  svr.Get("/hi", [](const Request & /*req*/, Response &res) {
    res.set_header("Access-Control-Allow-Origin", "*");
    res.set_content("Hello World!", "text/plain");
  });
```

So I guess the problem comes from something else.

**Comment by yhirose** [comment]
You are doing fine with `set_header` in your code. Adding `res.set_header("Access-Control-Allow-Origin", "*");` is enough actually to handle CORS.

```cpp
  svr.Get("/hi", [](const Request & /*req*/, Response &res) {
    res.set_header("Access-Control-Allow-Origin", "*");
    res.set_content("Hello World!", "text/plain");
  });
```

So I guess the problem comes from something else.

**Comment by jiagushuai** [comment]
+ After adding option can be
```
svr.Options("/(.*)",
			[&](const Request & /*req*/, Response &res) {
			res.set_header("Access-Control-Allow-Methods", " POST, GET, OPTIONS");
			res.set_header("Content-Type", "text/html; charset=utf-8");
			res.set_header("Access-Control-Allow-Headers", "X-Requested-With, Content-Type, Accept");
			res.set_header("Access-Control-Allow-Origin", "*");
			res.set_header("Connection", "close");
		});
```

## In addition, I would like to ask, what is R"(\*)", I replace it with "/(.*)" in order to properly cross domain

**Comment by yhirose** [comment]
That's C++11 'Raw string literal'.

**Comment by sweihub** [comment]
> * After adding option can be
> 
> ```
> svr.Options("/(.*)",
> 			[&](const Request & /*req*/, Response &res) {
> 			res.set_header("Access-Control-Allow-Methods", " POST, GET, OPTIONS");
> 			res.set_header("Content-Type", "text/html; charset=utf-8");
> 			res.set_header("Access-Control-Allow-Headers", "X-Requested-With, Content-Type, Accept");
> 			res.set_header("Access-Control-Allow-Origin", "*");
> 			res.set_header("Connection", "close");
> 		});
> ```
> 
> ## In addition, I would like to ask, what is `R"(\*)"`, I replace it with `"/(.*)"` in order to properly cross domain

This saved my day, this the so called `preflight check` of chrome. After setting this, and the cross origin issue was solved.

Thank you!

```cpp
// preflight for cross origin
server.Options("/(.*)",
                      [&](const Request & /*req*/, Response &res) {
                      res.set_header("Access-Control-Allow-Methods", "*");
                      res.set_header("Access-Control-Allow-Headers", "*");
                      res.set_header("Access-Control-Allow-Origin", "*");
                      res.set_header("Connection", "close");
                      });
```
// Then in any response, set the header
```cpp
res.set_header("Access-Control-Allow-Origin", "*");
```
