### ISSUE TITLE
HTTP Client POST operation hangs in case of proxy error "Proxy Authentication Required"

### ISSUE THREAD

**Issue by pappa5** [yhirose/cpp-httplib#1590]
I'm using httplib version 0.12.5

I configured a proxy with basic authentication and I try to use the httplib::Client::Post method with content provider.
It looks like `socket_mutex_` is locked when processing the request which causes the operation to hang, in case of invalid proxy credentials.

I think the issue is that the mutex is locked in `send_` method, but when calling `process_request` as a callback function from  `process_client_socket` we are still in the original `send_` scope so the mutex is still locked.

call stack: 
httplib::ClientImpl::process_request httplib.h:6922 ***
<lambda#1>::operator()(httplib::Stream &) const httplib.h:8009
std::__invoke_impl<…>(std::__invoke_other, <lambda#1> &, httplib::Stream &) invoke.h:61
std::__invoke_r<…>(<lambda#1> &, httplib::Stream &) invoke.h:114
std::_Function_handler::_M_invoke(const std::_Any_data &, httplib::Stream &) std_function.h:290
std::function::operator()(httplib::Stream &) const std_function.h:590
httplib::detail::process_client_socket(int, long, long, long, long, std::function<…>) httplib.h:2630 ***
httplib::SSLClient::connect_with_proxy httplib.h:8003 ***
httplib::ClientImpl::send_ httplib.h:6402 ***
httplib::ClientImpl::send httplib.h:6362
httplib::ClientImpl::send_with_content_provider(httplib::Request &, const char *, unsigned long, std::function<…>, std::function<…>, const std::string &, httplib::Error &) httplib.h:6809
httplib::ClientImpl::send_with_content_provider(const std::string &, const std::string &, const std::multimap<…> &, const char *, unsigned long, std::function<…>, std::function<…>, const std::string &) httplib.h:6826
httplib::ClientImpl::Post(const std::string &, const std::multimap<…> &, unsigned long, std::function<…>, const std::string &)
httplib::Client::Post(const std::string &, const std::multimap<…> &, unsigned long, std::function<…>, const std::string &)

Please have a look on this, thank you!

**Comment by yhirose** [comment]
@pappa5 thanks for the report. Could you provide the smallest possible complete code which can reproduce the problem? Thanks!

**Comment by pappa5** [comment]
hi @yhirose ! Thanks for taking care of this. The problem should be easily reproducible, just create a client with wrong proxy password, and try to make a network request. See the following example code below: 

```cpp
bool testConnection()
{
	auto httpClient = httplib::Client { "https://www.google.com" };

	httpClient.enable_server_certificate_verification(false);
	httpClient.set_connection_timeout(1, 0);
	httpClient.set_read_timeout(5, 0);
	httpClient.set_write_timeout(5, 0);

	httpClient.set_proxy("127.0.0.1", 8088);
	httpClient.set_proxy_basic_auth("User", "wrongpass");

	auto result { httpClient.Get("/") };
	if (result == nullptr || result->status != 200) {
		return false;
	}

	return true;
}
```

I used this tiny proxy implementation for test (On Linux)
http://tinyproxy.github.io/

With basic settings: 
```
Port 8088
Listen 127.0.0.1
Timeout 600
Allow 127.0.0.1
BasicAuth User rightpass
```

**Comment by akinelden** [comment]
@yhirose are you working on this issue? I made some changes to fix this error. I can open a PR if you can review it.

**Comment by yhirose** [comment]
@akinelden I haven't started yet. Could you send the PR? Thanks!

**Comment by yhirose** [comment]
@akinelden thanks for sending the pull request!
@pappa5 could you verify the code in the pull request #1630 fixes your problem? Then, I'll do the final code review.
