### ISSUE TITLE
Can't create a stream

### ISSUE THREAD

**Issue by bugdea1er** [yhirose/cpp-httplib#1604]
Hi there! Tried to extend a readme stream with a bigger data sample
```cpp
const size_t DATA_CHUNK_SIZE = 4;

server->Get("/stream", [&](const httplib::Request &req, httplib::Response &res) {
    std::string* data = new std::string("");
    for (int i = 0; i < 4000000; i++) {
        *data += std::string("abcdefg");
    }

    res.set_content_provider(
        data->size(), // Content length
        "text/plain", // Content type
        [&](size_t offset, size_t length, httplib::DataSink &sink) {
            const auto &d = *data;
            sink.write(&d[offset], std::min(length, DATA_CHUNK_SIZE));
            return true; // return 'false' if you want to cancel the process.
        },
        [data](bool success) { delete data; });
});
```

Tried this with both curl and axios.js in our web-client. Curl says this:
```
curl: (18) transfer closed with 28000000 bytes remaining to read
```

Our web-client says `Failed to load resource: The network connection was lost.`

Server logger (which was set with set_logger) prints just a regural log with full request and response, no error messages or exceptions.

What am I doing wrong?

**Comment by yhirose** [comment]
@bugdea1er, `data` should be transferred to the content provider lambda function as a copy instead of reference as below. It's because the reference address for `data` in the content provider will be gone as soon as we get out of the Get handler. It's more like a general C++ lambda issue instead of cpp-httplib. Hope it helps!

```cpp
            [&, data](size_t offset, size_t length, httplib::DataSink &sink) {
```

**Comment by bugdea1er** [comment]
@yhirose Thanks, that worked

By the way, can you update the readme example here?
https://github.com/yhirose/cpp-httplib#send-content-with-the-content-provider

DATA_CHUNK_SIZE is not captured

**Comment by yhirose** [comment]
> DATA_CHUNK_SIZE is not captured

Good catch!
