### ISSUE TITLE
ODR (One Definition Rule) compliance

### ISSUE THREAD

**Issue by zzdever** [yhirose/cpp-httplib#1605]
According to cpp language guidance, we should comply to One Definition Rule.

Ref:  [https://en.cppreference.com/w/cpp/language/definition](url)

Specifically: **For an inline function or inline variable (since C++17), a definition is required in every translation unit where it is odr-used.  For a class, a definition is required wherever the class is used in a way that requires it to be complete.**

As we can see some member variables in `ClientImpl` (not limited to) class are commented out according to the `CPPHTTPLIB_OPENSSL_SUPPORT` feature macro. It may result in different class definitions in different compilation units (when included with or without the macro). This will result in a memory issue. (By the way, the member functions are OK)

Suggestion: use an `SSLClientImpl` class to inherit the `ClientImpl` class, and put the SSL related codes in the derived class, and wrap the whole derived class in the feature macro.

**Comment by yhirose** [comment]
@zzdever thanks for the suggestion. I don't have time to work on it right now. Could you please try it and send a pull request? Thanks a lot!

**Comment by yhirose** [comment]
I close it for now, since I don't have a plan to work on it in the near future.
