### ISSUE TITLE
Is there a way to access a Client's host?

### ISSUE THREAD

**Issue by jpgaribotti** [yhirose/cpp-httplib#1607]
When you construct a `Client`, you pass it a host string, which gets stored as a `const std::string` in `ClientImpl`. Is there any way to get this string back?

My current issue is that I create a Client object and store it, and then reuse it for later requests to the same host. I want to be able to print some information about the request, including the host, but I can only do that if I store and pass along the host as a separate string together with the client.

**Comment by yhirose** [comment]
@jpgaribotti I added `cli.host()` and `cli.port()` for you. :)
