### ISSUE TITLE
Pase data from Response like "json"

### ISSUE THREAD

**Issue by purpl3F0x** [yhirose/cpp-httplib#161]
Is there any way to parse the response like a "json" or I can just get a string from it, and then I will need to convert it to json with another lib? I didn't see any function in the example, tried read the header but oof.

**Comment by yhirose** [comment]
@purpl3F0x, thank you for your feedback . This library doesn't give a functionality to parse response text such as JSON, XML and so on. It just handles one responsibility of HTTP communication. I use https://github.com/nlohmann/json for parsing JSON text in my projects, which is much better than the code I would write. :)
