### ISSUE TITLE
After some time of a successful connection , CONNECTION errors starts to come in every few seconds

### ISSUE THREAD

**Issue by rk85097** [yhirose/cpp-httplib#1611]
- I am sending 60 times per second a string via TCP.
- It works for few min, then gets unstable with CONNECTION errors.
- Also when checking used ports via cmd, I get a strange long list with the port I use.
- Debuggin library code brought me to LINE 2941:
` if (sock != INVALID_SOCKET) {`

Server:

```
svr.Get("/data", [](const httplib::Request&, httplib::Response& res) {
if (isDataReady)
{
	res.set_content(to_string(dataJson), "application/json");
}
});

svr.set_error_handler([](const auto& req, auto& res) {
auto fmt = "<p>Error Status: <span style='color:red;'>%d</span></p>";
char buf[BUFSIZ];
snprintf(buf, sizeof(buf), fmt, res.status);
res.set_content(buf, "text/html");
});

svr.listen("127.0.0.1", port);
```

Client:

```
thread clientThread([this]() {
  cli = new httplib::Client("127.0.0.1", port);
  auto res = cli->Get("/data");
  if (res)
  {
	  int statsCode = res->status;
  
	  if (statsCode == 200)
	  {
......
```

Strange output of used ports from cmd (with my port)

![434343](https://github.com/yhirose/cpp-httplib/assets/5455346/9064c622-a433-43ff-99a3-f6b0749fceba)

**Comment by PixlRainbow** [comment]
60 times a second? How are you repeating the request? I do not see a loop.

**Comment by PixlRainbow** [comment]
My guess is that one side is configured to keep the connection alive for reuse, but the other side is configured to discard the connection for each request. So new connections are repeatedly being created without being closed.

Just a question, but for a streaming application like this, why are you using client initiated polling instead of [server sent events](https://github.com/yhirose/cpp-httplib/blob/master/README.md#server-sent-events)?

**Comment by rk85097** [comment]
Thanks! I will look into that indeed. What is going to be the benefit of this? one way data flow?

**Comment by PixlRainbow** [comment]
Partially. The other benefit is, well, notice that your server side code must have an additional conditional check and must also waste resources to send an empty message with a 200 OK code.
```cpp
if (isDataReady) {
    res.set_content(to_string(dataJson), "application/json"); 
}
```

If your server simply sends the data when it is ready, it does not have to prepare and send blank acknowledgement responses or check the state of the data.

The server will still have to send occasional empty heartbeat messages so the client can diagnose if it is still connected correctly, but you do not have to do so every frame. You only have to do so with an interval slightly shorter than the timeout interval, and only if the server has nothing else to send for an extended period of time.

**Comment by PixlRainbow** [comment]
Oh, but there's a catch. The default work pool implementation that comes with this library isn't capable of multiplexing -- each connection will occupy a dedicated worker thread on the server. This means that this library is not capable of handling a large amount of simultaneous users "out of the box"; you must attach your own work pool which is capable of doing so.

**Comment by rk85097** [comment]
@PixlRainbow When get return with a value, I get something like this:
`{"acType":2,"agl":-0.0053471410647034645,"aircraftTitle":"b738","batteryState":true,"emptyWeight":41412.99609375,"engineSpeed":55.10869598388672,"flapsPosition":0.0,"gearCenterPosition":1.0,"gforce":1.019375205039978,"groundSpeed":0.045262567698955536,"hasFloats":false,"hasRetractableGear":true,"ias":0.0,"isConnected":true,"isEngineRunning":true,"isOnGround":true,"isSimPaused":false,"reverseThrustSpeed":0.0,"spoilersPosition":0.0,"stallPercentage":0.0,"surfaceType":4,"totalWeight":79015.8203125,"vecticalSpeed":0.03739779070019722,"vne":340.0,"vso":114.0,"windshieldWindVelocity":0.0}ÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌ`

Any idea why a json string comes back as such?

**Comment by PixlRainbow** [comment]
Have you checked if you marked the end of your string correctly on the client side? That looks like uninitialized memory.

**Comment by yhirose** [comment]
@rk85097, It looks the issue on the title has been resolved by properly releasing client objects. So I'll close it.
@PixlRainbow thanks for the support.

**Comment by rk85097** [comment]
It is all working perfect with server events - thanks for the great work and help - topic can be closed indeed.
