### ISSUE TITLE
Delayed http response?

### ISSUE THREAD

**Issue by blitz-research** [yhirose/cpp-httplib#1617]
Hi,

With cpp-httplib (and http in general!) is it possible for a server to 'delay' returning the response to an http request for an indefinite amount of time, while simultaneously handling other unrelated requests? Could doing this potentially run out of threads in cpp-httlib?

Basically, I'm trying to achieve some kind of server 'push' system, so JS client code would execute a 'fetch' and then block waiting for the response, so effectively the response is the message being 'pushed' to the client.

Are there any other ways to achieve this?

**Comment by yhirose** [comment]
@blitz-research, yes, this is a general HTTP question. I think what you are trying to do is 'long polling'. Each connection consumes a thread and a socket. So if a server receives tons of requests, threads and sockets may run out eventually.
https://www.pubnub.com/blog/http-long-polling/

The best way to do such a thing is to use WebSocket. But cpp-httplib doesn't support it. You could also use SSE (Server Sent Event). cpp-httplib doesn't support SSE as a built-in feature. You could do SSE by looking at an example `example/ssesvr.cc`.

Hope it helps!
