### ISSUE TITLE
Multipart file max count constant

### ISSUE THREAD

**Issue by csd-ableton** [yhirose/cpp-httplib#1620]
With version 0.11.2, specifically since this commit, https://github.com/yhirose/cpp-httplib/commit/cba9ef8c0bc2ae41cec3b17a458af736122ed09e, now the multipart form data has a file count limit.

Is this only necessary as a customization point so that if the client code needs to limit this or is there a technical reason to limit this as well?

**Comment by yhirose** [comment]
This is to protect a server from attacks with long multiform-data which is reported by oss-fuzz. Hope it helps!
