### ISSUE TITLE
undef CPPHTTPLIB_OPENSSL_SUPPORT not work

### ISSUE THREAD

**Issue by ShadowZzj** [yhirose/cpp-httplib#1625]
I use this code on Windows  visual studio 2022, and I change the source code of httplib like below:
```cpp
#undef CPPHTTPLIB_OPENSSL_SUPPORT
#include <cpp-httplib/httplib.h>
void Func()
{
    int a           = 4;
    int b           = 5;
    std::string url = "http://www.baidu.com";
    httplib::Client cli(url);
    int c = 5;


    auto response = cli.Post("/agent/strategy", "123", "application/json");
    return;
}
int main(int argc, char *argv[])
{
    Func();
    return 0;
}

```

![image](https://github.com/yhirose/cpp-httplib/assets/22760144/8afa0cba-cfb5-449c-afc3-9bbc1c09e8a2)

When I compile, the visual studio shows the error:
![image](https://github.com/yhirose/cpp-httplib/assets/22760144/94dca9bc-cb8e-440a-a674-09c76fe66ed6)

Why could it happen? I think the operation that undef CPPHTTPLIB_OPENSSL_SUPPORT will not make the compiler compile bool is_ssl_ = false. So if I comment it, It will have no effect.

**Comment by yhirose** [comment]
I don't know your intention to modify httplib.h in such a way... If you don't need the SSL support, you can just compile your source code including httplib.h without `CPPHTTPLIB_OPENSSL_SUPPORT`. You don't have to specify `#undef CPPHTTPLIB_OPENSSL_SUPPORT`. Hope it helps!
