### ISSUE TITLE
undefined reference to `__imp_Cert...'

### ISSUE THREAD

**Issue by rautyrauty** [yhirose/cpp-httplib#1629]
undefined reference to `__imp_CertOpenSystemStoreW`
undefined reference to `__imp_CertEnumCertificatesInStore`
undefined reference to `__imp_CertEnumCertificatesInStore`
undefined reference to `__imp_CertFreeCertificateContext`
undefined reference to `__imp_CertCloseStore`
undefined reference to `__imp_CertOpenSystemStoreW`
undefined reference to `__imp_CertEnumCertificatesInStore`
undefined reference to `__imp_CertEnumCertificatesInStore`
undefined reference to `__imp_CertFreeCertificateContext`
undefined reference to `__imp_CertCloseStore`
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

FAILED: untitled1.exe 
cmd.exe /C "cd . && D:\Qt\Tools\mingw810_64\bin\g++.exe -O3 -DNDEBUG  CMakeFiles/untitled1.dir/main.cpp.obj -o untitled1.exe -Wl,--out-implib,libuntitled1.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lws2_32  D:/Qt/Tools/OpenSSL/Win_x64/lib/libssl.lib  D:/Qt/Tools/OpenSSL/Win_x64/lib/libcrypto.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd 

### CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.14)

project(untitled1 LANGUAGES CXX)

set(CMAKE_INCLUDE_CURRENT_DIR ON)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

IF (OPENSSL_INCLUDE_DIR)
      UNSET(OPENSSL_INCLUDE_DIR)
      UNSET(OPENSSL_INCLUDE_DIR CACHE)
ENDIF()

set(OPENSSL_ROOT_DIR "D:/Qt/Tools/OpenSSL/Win_x64")

find_package(OPENSSL REQUIRED)
message(STATUS ${OPENSSL_VERSION})
message(STATUS ${OPENSSL_INCLUDE_DIR})

add_executable(untitled1
  main.cpp
  httplib.h
)

target_link_libraries(untitled1 ws2_32)

if (OPENSSL_FOUND)
    target_link_libraries(untitled1 ${CMAKE_DL_LIBS} OpenSSL::SSL OpenSSL::Crypto)
else()
    message(FATAL_ERROR "OpenSSL not found")
endif()

```
### main.cpp:
```c++
#define CPPHTTPLIB_OPENSSL_SUPPORT
#include <httplib.h>
#include <iostream>

int main(void)
{
  httplib::SSLClient cli("https://httpbin.org");
  if (auto res = cli.Get("/anything")) {
    if (res->status == 200) {
      std::cout << res->body << std::endl;
    }
  } else {
    auto err = res.error();
    std::cout << "HTTP error: " << httplib::to_string(err) << std::endl;
  }
}
```
Before that, I tried https requests on Qt using OpenSSL and everything is OK.
Without #define CPPHTTPLIB_OPENSSL_SUPPORT http requests work.

**Comment by yhirose** [comment]
@rautyrauty could you take a look at test/test.sln, and test/test.vcxproj? It builds the Windows test executable and it runs correctly on GitHub Actions workflow. Hope it helps!
