### ISSUE TITLE
How to force use https

### ISSUE THREAD

**Issue by purpl3F0x** [yhirose/cpp-httplib#163]
I want to make an request to github api. 
Let's say I do this, 
```cpp
httplib::Client cli("api.github.com");
auto res = cli.Get("/users");
```
Because github api uses accepts only https requests it returns 301 code with the link as https. Is there a way I should force use https from the start, or  somehow to be able to make the request to the new url. I tried setting the Client port to 443, but that return an error.

**Comment by yhirose** [comment]
@purpl3F0x, please check the information at https://github.com/yhirose/cpp-httplib#openssl-support in README.md.

**Comment by purpl3F0x** [comment]
thank, you I somehow missed that.

**Comment by pmehul55** [comment]
I am not able to use this class **SSLClient**. Can you please help me ?
