### ISSUE TITLE
Suggestion Support HTTP2 or a new project

### ISSUE THREAD

**Issue by elli-one** [yhirose/cpp-httplib#1631]
Hello,

good  C++ support for HTTP2 exits not in real world.  I know nghttp2, but usage of SSE is totaly unclear and
seems untested, no sample exists. It is a pain.

I have used your great library with 100 % success for HTTP 1.1 client and server. It was simple.

What is your road map for future ?

regards
 elli

**Comment by yhirose** [comment]
@elli-one thanks for the question. I am satisfied with HTTP/1.1 and don't have any plan to support HTTP/2 features. Also the change requires massive changes and I simply don't have time to work on in. Hope it helps!
