### ISSUE TITLE
Error::SSLServerVerification Linux only

### ISSUE THREAD

**Issue by romanholidaypancakes** [yhirose/cpp-httplib#1637]
i have seen: https://github.com/yhirose/cpp-httplib/issues/673

I don't want to use `cli.enable_server_certificate_verification(false);` this will bring new errors
```
status 422
reason "Unprocessable Entity"
```
This error also occurs for requests that were originally successful on windows.
  In linux I have done the following steps
```
apt install ca-certificates -y
```
But nothing works, any suggestions? Thanks

**Comment by yhirose** [comment]
@romanholidaypancakes thanks for the feedback, but I can't give you any meaningful suggestion at this point. It's up to how your Linux OS's system cert works with the OpenSSL library. In httplib.h, I just delegate the cert loading task to `SSL_CTX_set_default_verify_paths`. Please see the following code.

https://github.com/yhirose/cpp-httplib/blob/67f6ff7fa94cd9c3196bd264db29e65f25b0403d/httplib.h#L8514

Could you try to do the same with curl? If it works, it shows cpp-httplib is missing something that curls does, and I'll take a look at it.

**Comment by yhirose** [comment]
Could you run the unit test suite? It might show you the cause of this problem.
`cd test && make`

**Comment by harsh-im** [comment]
@yhirose @romanholidaypancakes  I am facing the similar error while using cpp-httplib in android using JNI.
any suggestions on how to fix it?

**Comment by yhirose** [comment]
@romanholidaypancakes on Ubuntu, all the unit tests work successfully. https://github.com/yhirose/cpp-httplib/actions/runs/5755617548/job/15603436611

It seems like `SSL_CTX_set_default_verify_paths` is not working properly on your linux, and I have no idea why the problem happens on your environment...

**Comment by harsh-im** [comment]
@yhirose any suggestions regarding the similar error on the android platform?

**Comment by harsh-im** [comment]
@yhirose any updates? It is working for linux but not on android
<img width="466" alt="image" src="https://github.com/yhirose/cpp-httplib/assets/85297965/c5b5868e-acf9-412d-87c0-0ce7c5644627">

**Comment by JoSoReal** [comment]
Hi
I got the same issue on Debian and solved it by manually passing the certificate directory to the client like:

`cli.set_ca_cert_path("", "/etc/ssl/certs");`

After that the certificate verification is working.

For my distribution the path was /etc/ssl/certs. The path might differ depending on the Linux distribution you are using, but Google gives very good answers to where the default cert path is located.

Hope this solves your issue as well.

**Comment by yhirose** [comment]
@JoSoReal thanks for the very helpful info!
@romanholidaypancakes @harsh-im could you try @JoSoReal's suggestion?

**Comment by harsh-im** [comment]
@yhirose  I am still getting the same error
I have debugged my code and I found out this condition is getting failed
<img width="561" alt="image" src="https://github.com/yhirose/cpp-httplib/assets/85297965/254c82f5-8c2b-4818-89e0-fe5262d9dbbd">

**Comment by harsh-im** [comment]
@JoSoReal  I have tried implementing your solution by providing the path of installed ca certificates in the android system i.e. `/system/etc/security/cacerts`.
any other suggestions which I can implement?

@yhirose Also, can you confirm that the cause of error might be cpp-httplib? 
or it can be an error related to openssl?

**Comment by jimmy-park** [comment]
@harsh-im I had similar errors when I was testing on Android. Providing path isn't not enough because Android uses the different hash function for file names. Try to build OpenSSL with this [patch](https://github.com/jimmy-park/openssl-cmake/blob/main/patch/android.patch).

**Comment by harsh-im** [comment]
@jimmy-park Hello, I followed your suggestion and applied the patch to build OpenSSL. Subsequently, I linked OpenSSL statically with my custom C++ shared library. I attempted two approaches:
1. By specifying the CA certs default directory path.
2. Without specifying the path.
However, I encountered the same error in both cases.

**Comment by jimmy-park** [comment]
@harsh-im Actually I didn't try `cli.set_ca_cert_path("", "/system/etc/security/cacerts");`, but configured OpenSSL with `--openssldir=/system/etc/security/cacerts` option. How about this way?

**Comment by harsh-im** [comment]
@jimmy-park as suggested I have tried building openssl on mac M1 by specifying `--openssldir` option, but it didn't work out.

can you please verify the command I used for configuring openssl?
`  ./Configure android-"${ABI}" no-asm no-tests --prefix="${BUILD_DIR}" --openssldir=/system/etc/security/cacerts`

**Comment by jimmy-park** [comment]
@harsh-im I think your cmd is valid. Could you check if there are cert files something like `09123008.0` in `/system/etc/security/cacerts` using Android Studio?

**Comment by harsh-im** [comment]
@jimmy-park Please find the attached screenshot of the emulator's (android 13- google pixel) `/system/etc/security/cacerts` directory
<img width="1287" alt="image" src="https://github.com/yhirose/cpp-httplib/assets/85297965/9ecc11bf-405b-4623-8d80-5587e24da35b">

**Comment by jimmy-park** [comment]
@harsh-im Sorry I have no idea what's wrong with your environment. You may configure OpenSSL with `--debug` to find the actual problem with debugger.

**Comment by harsh-im** [comment]
@jimmy-park can you just confirm that it is the problem related openssl & not with the cpp-http library itself?

**Comment by jimmy-park** [comment]
@harsh-im Sorry I really don't know.

**Comment by harsh-im** [comment]
@jimmy-park your patch does solve this problem right?
<img width="673" alt="image" src="https://github.com/yhirose/cpp-httplib/assets/85297965/70cc064f-93ca-40ce-ac83-d16cb44abf10">

**Comment by harsh-im** [comment]
@jimmy-park Thank you for all the help! 
I am able to resolve the error by using custom ca bundle (cacerts.pem file  -[https://curl.se/docs/caextract.html](url))

@yhirose @jimmy-park Just one more question, how do I link cacerts.pem file with cpp-http lib (during build) so that I won't need to push the bundle into the android device.

**Comment by jimmy-park** [comment]
@harsh-im Here is what I do to embed CA certs.
1. Create `cert.h` which embeds character string from `cert.pem`. (I'm doing this using [CMake](https://github.com/jimmy-park/cert-cmake/blob/main/CMakeLists.txt))
2. Use that with `SSLClient::load_ca_cert_store()`

You can find a specific example in `test.cc`
https://github.com/yhirose/cpp-httplib/blob/afe627e7af13f78225076af1639c9ea40a807921/test/test.cc#L4925-L4955

**Comment by yhirose** [comment]
Glad to hear that the certs problem on Android is gone now! I believe this information is helpful for users who have similar certs issues on other linux-based platforms. I'll keep it as 'information' for a while. Thanks for your fine contribution!

**Comment by harsh-im** [comment]
@yhirose @jimmy-park Thank you very much for all the support!

**Comment by yhirose** [comment]
All the credit goes to @jimmy-park. :)
