### ISSUE TITLE
get_header_value should not compile with unknown types

### ISSUE THREAD

**Issue by kiwixz** [yhirose/cpp-httplib#1638]
Currently an empty function gets called but doesn't return a value so at best it segfaults.  See [here](https://github.com/yhirose/cpp-httplib/blob/67f6ff7fa94cd9c3196bd264db29e65f25b0403d/httplib.h#L1713C1-L1716C51).

One solution in recent standards would be to have some kind of static_assert; but in C++11 I don't know...  Maybe to not define it so we get a linker error ?

**Comment by yhirose** [comment]
@kiwixz this is for making sure that only `detail::get_header_value<uint64_t> is allowed in httplib.h. This function is only for internal use anyway. So you don't have to worry about. :)

**Comment by kiwixz** [comment]
I linked the underlying function, but it happened to me when calling the public one [here](https://github.com/yhirose/cpp-httplib/blob/67f6ff7fa94cd9c3196bd264db29e65f25b0403d/httplib.h#L1739).

**Comment by yhirose** [comment]
You can see the calling example of the public method of Response object:
https://github.com/yhirose/cpp-httplib/blob/67f6ff7fa94cd9c3196bd264db29e65f25b0403d/test/test.cc#L1019

As I mentioned for the internal one, this public method also allows only `uint64_t` type. If we put a different type, the code won't be compiled. Hope it helps.

**Comment by kiwixz** [comment]
Thanks for looking into it!

I opened this issue because unfortunately the code does actually compile with other types, and then lead to segfaults.  ([godbolt](https://godbolt.org/z/KheeKvhqv))

```cpp
#include <cassert>
#include <httplib.h>

int main() {
    httplib::Client client{"example.com"};
    httplib::Result res = client.Get("/");
    assert(res);
    res->get_header_value<int>("some_header");
}
```

I'm including httplib as a system header, so I didn't even get the helpful warning in my project!

**Comment by yhirose** [comment]
@kiwixz, I removed the template functions and added `get_header_value_u64` instead. So there is now no ambiguity.
