### ISSUE TITLE
Sockets should not be inheritable

### ISSUE THREAD

**Issue by axel-habermaier** [yhirose/cpp-httplib#164]
The sockets used by the library, in particular the listening socket used for the server, are inheritable. This is almost always a bug when the process that creates the server spawns child processes that outlive the parent process. In that case, the parent process cannot be started again as the listening socket is still in use. For instance, Microsoft also changed this for .NET core (see https://github.com/dotnet/corefx/issues/32902).

The Windows fix is to use ``WSASocket(rp->ai_family, rp->ai_socktype, rp->ai_protocol, nullptr, 0, WSA_FLAG_NO_HANDLE_INHERIT);`` instead of ``socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol);``. Not sure about other OSes.

**Comment by yhirose** [comment]
@axel-habermaier, thanks for the bug report. I would like to add the case to the unit tests in `test.cc`. Do you have a small example code to reproduce it, so that I could confirm the issue on my Windows machine?

**Comment by axel-habermaier** [comment]
Unfortunately, I don't have a small standalone example demonstrating the problem. This is also probably quite inconvenient to unit-test, as it involves at least two processes and the parent process has to be shut down and restarted for the problem to manifest itself.

**Comment by yhirose** [comment]
Yes, I now understand that it doesn't make sense to make a unit test for this issue .

But I still need to make an example code to reproduce the issue to look into it. What does 'the process that creates the server spawns child processes that outlive the parent process' mean? Also how large do you think the example is going to be? Thanks for your help!

**Comment by yhirose** [comment]
Yes, I now understand that it doesn't make sense to make a unit test for this issue .

But I still need to make an example code to reproduce the issue to look into it. What does "_the process that creates the server spawns child processes that outlive the parent process_" mean? Also how large do you think the example is going to be? Thanks for your help!

**Comment by axel-habermaier** [comment]
The example is not going to be that large. Use the following steps to reproduce:

* Launch executable A to create process A1 that creates a ``httplib::Server`` and binds it to some socket, say ``5002``.
* Afterwards, process A1 launches process B1 (can be any executable) using ``CreateProcess`` (https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-createprocessa), making sure to set ``bInheritHandles`` to ``true`` (otherwise, the problem won't occur; settings this to ``true`` is important for multiple reasons).
* Make sure you can access an endpoint of process A1's ``httplib::Server`` instance via http.
* Now kill process A1 via the Visual Studio debugger or the Windows Task Manager. Process B1 should continue to run.
* Now start executable A again to create process A2 (it will start process B2, which we don't care about).
* Observer that you *cannot* access process A2's ``httplib::Server`` instance via http (this is the symptom of the problem).
* Close process B1. Observer that you can now access process A2's ``httplib::Server`` instance via http.

At any point, you can run ``netstat -a -o -n`` from the command prompt. Even after killing process A1, you can see that socket ``5002`` is still being listened on (this is the underlying problem, i.e., the socket remains open as it is inherited by process B1 and only closed when B1 also exits).

Hope this helps. Please ask if you need further info. 

And, by the way, thanks for your quick answer and your awesome work on this very helpful library!

**Comment by yhirose** [comment]
Great! I'll try to reproduce it when I am not busy. Thanks for the helpful information!

**Comment by yhirose** [comment]
@axel-habermaier, I applied your suggestion and tried to do the same for non Windows OSs. Could you test with the latest `httplib.h` when you have time? Thanks!

**Comment by axel-habermaier** [comment]
@yhirose: Thanks for this update! Works great for me! I only tried it on Windows, though...

**Comment by jzySaber1996** [comment]
Hello, we're investigating the issue reports in security. Since our automatic tool has observed that this issue may relate to a potential vulnerability (maybe it is not a reproducible issue, but our tool cannot check it. If so, please let us know), has it been disclosed in CVE already? Hope to receive your reply.
