### ISSUE TITLE
50 clients, each sending four or five requests within one second

### ISSUE THREAD

**Issue by nyl0330** [yhirose/cpp-httplib#1640]
50 clients, each sending four or five requests within one second, may not refresh the page in a timely manner and may need to wait for 5 seconds or even longer. The default value of "CPPHTTPPLIB.THREAD_POOL_COUNT" is 8, but after modifying "CPPHTTPPLIB.THREAD_POOL_COUNT" to 50, the effect is not significant. How can I improve the concurrency ability of the service and which parameters need to be modified

**Comment by yhirose** [comment]
@nyl0330 thanks for the question. You may adjust the following parameters. 

```
#define CPPHTTPLIB_KEEPALIVE_TIMEOUT_SECOND 5
#define CPPHTTPLIB_READ_TIMEOUT_SECOND 5
```

Or, your make your own thread-pool implementation for better performance in your situation.
https://github.com/yhirose/cpp-httplib#override-the-default-thread-pool-with-yours

Hope it helps!
