### ISSUE TITLE
400 Bad Request when using application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by MHYCWasTaken** [yhirose/cpp-httplib#1641]
i need to use application/x-www-form-encoded, but when i set content type to it, server always give back 400 Bad Request  
any other content type is ok and returns 200 (but i need to use x-www-form-urlencoded)  
ive tested those ways but none of them work, is there something else i have to notice to use x-www-form-urlencoded?
```
auto res = cli.Post("/", body, "application/x-www-form-urlencoded");
auto res = cli.Post("/", headers, body, "application/x-www-form-urlencoded");
auto res = cli.Post("/", body.c_str(), size_t(sizeof(body)), "application/x-www-form-urlencode");
```
~~ive been working on this bad request for a whold day :(~~

**Comment by yhirose** [comment]
@MHYCWasTaken thanks for the question. You can see the following example in `test/test.cc`. Hope it helps!

https://github.com/yhirose/cpp-httplib/blob/afe627e7af13f78225076af1639c9ea40a807921/test/test.cc#L2278-L2279

**Comment by MHYCWasTaken** [comment]
yes i did like that, but seems not working  
is there any way to check the entire http message the program sent so that i can find where is the problem
