### ISSUE TITLE
Usage of make_digest_authentication_header

### ISSUE THREAD

**Issue by pedrety** [yhirose/cpp-httplib#1642]
Hi, I'm trying to connect to a camera which need to be authenticated with a digest authentication header and I'm not being able to do it.

This is the function I'm having trouble with:
```cpp
std::pair<std::string, std::string> make_digest_authentication_header(
    const Request &req, const std::map<std::string, std::string> &auth,
    size_t cnonce_count, const std::string &cnonce, const std::string &username,
    const std::string &password, bool is_proxy = false)
```
Reading it I'm guessing that `req` is more likely the URL where I want to do the request, then `username` and `password` my credentials. My problem comes with the other parameters, how am I suppose to create them? My main concern is `cnone_count` and `cnone` since i don't get how to create them. Then the map `auth` seems like the Authentication header itself, but again I'm not really sure. 

I don't see any kind of information in how to use this in the repo so if you could help me here I would really appreciated it.

**Comment by yhirose** [comment]
@pedrety `make_digest_authentication_header` is a private function and it shouldn't be called by users. You can take a look at test/test_proxy.cc to see how the digest authentication is handled. Hope it helps!
