### ISSUE TITLE
SSL server verification failed with examples server and client

### ISSUE THREAD

**Issue by hartvon** [yhirose/cpp-httplib#1652]
Hi, Thanks for the awesome project!
I have cloned this project and built the files example/{server.cc,client,cc} successfully.
But when I tried to run the executable ./example/client, I met the error "SSL server verification failed", see below:
```
> ./server
> ./client 
error code: SSL server verification failed (10)
verify error: self-signed certificate
```

The files `cert.pem` and `key.pem` in the `example` directory are generated by the command `make pem`.
The os info is WSL2 Ubuntu 20.04.6, and g++ version is 9.4.0.
Currently, the openssl's version is 3.0.10,  which is build from source, I have also tried 1.1.1v, 1.1.1t and 3.1.2 versions, neither worked, and were the same problem.

```
> openssl version
OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)
```

Could you please provide some advice for me?

**Comment by yhirose** [comment]
@hartvon since the server is a local server, you have to set `enable_server_certificate_verification` to `false`. Hope it helps.

```cpp
  cli.enable_server_certificate_verification(false);
```
