### ISSUE TITLE
http Get request returns null

### ISSUE THREAD

**Issue by slgu** [yhirose/cpp-httplib#1653]
I am trying to use this library in android JNI, somehow

httplib::Client client(host);
 __android_log_print(ANDROID_LOG_DEBUG, tag, "start fetching host path %s %s", host, path);
auto res = client.Get(path);

res is null in this case 

host = http://httpbin.org
path = /anything

I double check I include android permission for network

<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.INTERNET" />

How can I debug further in this case

**Comment by yhirose** [comment]
You can check the error code with `res.error()`.

**Comment by slgu** [comment]
@yhirose as I mentioned, res is null in this case

**Comment by yhirose** [comment]
The return value of `Get` is a `Result` object. It can never be null.
https://github.com/yhirose/cpp-httplib/blob/30b7732565c4630263b43c34267a605a1511f794/httplib.h#L1388

**Comment by slgu** [comment]
Aha, nvm, looks like I am using an incorrect version.
