### ISSUE TITLE
On the issue of Range size

### ISSUE THREAD

**Issue by maxbad** [yhirose/cpp-httplib#1654]
Compile 32-bit programs and use make when downloading large files_ Range_ Creating a Range in the header may be inaccurate, as the file exceeds the long size

**Comment by yhirose** [comment]
@maxbad thank you for your feedback, but I'm not sure I fully understand what you're trying to convey... Could you explain it clearly?

**Comment by maxbad** [comment]
![image](https://github.com/yhirose/cpp-httplib/assets/37558406/01e6a539-f862-47e2-b872-ef5b6dc3678e)

@yhirose  As shown in the above figure: The correct bytes should be 7188266780-7188266785

**Comment by PixlRainbow** [comment]
I believe what they mean is that the definition of size_t varies depending on target architecture, and on some platforms it may not be sufficiently wide to accommodate offsets > 4GB.

**Comment by yhirose** [comment]
@PixlRainbow thanks for making it clear to me.

@maxbad Unfortunately, there is nothing to do for it on cpp-httplib side.

```cpp
#include <iostream>

int main(void) {
  int32_t a = 7188266780;
  std::cout << a << std::endl;
}
```

```bash
> g++ a.cpp && ./a.out
a.cpp:4:15: warning: implicit conversion from 'long' to 'int32_t' (aka 'int') changes value from 7188266780 to -1401667812 [-Wconstant-conversion]
  int32_t a = 7188266780;
          ~   ^~~~~~~~~~
1 warning generated.
-1401667812
```

`ssize_t` on `Reage` is 32bits. So it doesn't not have enough space to accommodate the 7188266780. A C++ compiler truncates overflown value and makes it to the 32 bits signed integer...

**Comment by PixlRainbow** [comment]
A suggestion would be to replace usage of `size_t` with more explicit references to bit width, such as `uint64_t`, in httplib.
However, it may be difficult to identify which parts of the code are acceptable to perform this replacement, and which parts the original `size_t` must be retained for parameter/return type compatibility with stdlib.
