### ISSUE TITLE
Check if sink.write() has completed before re-invoking for chunked_content_provider 

### ISSUE THREAD

**Issue by Kadle11** [yhirose/cpp-httplib#1655]
Hi,

Thank you for maintaining this lightweight, easy-to-use library!

I have a question about using the chunked_content_provider(). I have a program that keeps fetching batches of data for the same GET request and I am using the chunked_content_provider to send the batches of data. 

The issue I am facing is that sometimes the data length I specify on the server side is not the same as that received on the client side and the data received on the client side has traces of strings from the previous invocation of sink.write().

*Server Side Code* 
```cpp
svr.Get("/run", [&](const httplib::Request &req, httplib::Response &res) {
        res.set_chunked_content_provider("text/plain", [&](size_t offset, httplib::DataSink &sink) {
            uint64_t moreParts = 1;
            uint64_t moreSize = sizeof(moreParts);
            while (moreParts)
            {
                zmq::message_t recvMsg;
                auto rc = socket.recv(recvMsg, zmq::recv_flags::none);

                if (rc == 0)
                {
                    std::cout << "[Worker] Error receiving message" << std::endl;
                    res.status = Status::ERROR;
                    return false;
                }

                std::string recvMsgStr = recvMsg.to_string();
                const char *recvMsgCStr = recvMsgStr.c_str();

                sink.write(recvMsgCStr, recvMsgStr.size() + 1);
                // The sleep here seems to alleviate the issue.
                // usleep(25000);

                socket.getsockopt(ZMQ_RCVMORE, &moreParts, &moreSize);
            }

            sink.done();
            return true;
        });
```

*Client Side Code*
```cpp
httplib::Request getReq;
getReq.method = "GET";
getReq.path = "/run";
getReq.headers.insert(std::make_pair("Content-Type", "application/json"));
getReq.content_receiver = [&](const char *data, size_t data_length, uint64_t offset, uint64_t total_length) {
        json responseData = json::parse(data);
        float oldResidual = 0.0;
        for (uint32_t ii = 0; ii < responseData[RunParams::MINIMAL_RM_UPDATES].size(); ++ii)
        {
         // some computations are done         
        }
        return true;
};

auto getResponse = workerClients[workerIdx].send(getReq);
if (getResponse->status != Status::OK)
{
        std::cout << "[Leader] Worker #" << workerIdx << " failed to run with status " << getResponse->status << std::endl;
}
```
Adding a sleep after the sink.write() seems to solve the issue, but I don't think that is the right fix. I wanted to know if there was anyway to wait for the sink.write() to finish completely as I may be calling it too fast for the amount of data I am sending.  

Some of the previous issues mention `sink.is_writable()` as a function, but the DataSink does not seem to have an `is_writable()` function.

This may also be because of the limit of 4096 bytes because I am sending more than that amount. Is there anyway to increase that limit?

Please let me know if there is any flaw with my current implementation. 

Thank you for your time.

**Comment by MihanEntalpo** [comment]
I have similar problem, and came to solution by reading this issue: https://github.com/yhirose/cpp-httplib/issues/1679

Actually, you should not run all the data producing in a single call of set_chunked_content_provider's lambda.
Each lambda call should generate small amount of data, send it to DataSink, and return 1.

So, in your case, you should take one message a time, put it into DataSink and wait for next call of lambda.

httplib call lambda next time when DataSink is need new chunk of data

```cpp
svr.Get("/run", [&](const httplib::Request &req, httplib::Response &res) {

        uint64_t moreParts = 1;
        uint64_t moreSize = sizeof(moreParts);

        res.set_chunked_content_provider("text/plain", [&](size_t offset, httplib::DataSink &sink) {
            
            if (moreParts)
            {
                zmq::message_t recvMsg;
                auto rc = socket.recv(recvMsg, zmq::recv_flags::none);

                if (rc == 0)
                {
                    std::cout << "[Worker] Error receiving message" << std::endl;
                    res.status = Status::ERROR;
                    return false;
                }

                std::string recvMsgStr = recvMsg.to_string();
                const char *recvMsgCStr = recvMsgStr.c_str();

                sink.write(recvMsgCStr, recvMsgStr.size() + 1);
                // The sleep here seems to alleviate the issue.
                // usleep(25000);

                socket.getsockopt(ZMQ_RCVMORE, &moreParts, &moreSize);
            }
            else
            {
                  sink.done();
            }

            return true;
        });
```

**Comment by yhirose** [comment]
@MihanEntalpo thanks for the information. @Kadle11 hope the above comment helpful for you.
