### ISSUE TITLE
process finish with exit code -1

### ISSUE THREAD

**Issue by raymond-li0518** [yhirose/cpp-httplib#1657]
start a server and receive the post request from a python client, but about 20-50minutes, the process finish with exit code -1.
I debug for 2 days, but still can not slove the problem

**Comment by yhirose** [comment]
Sorry to hear that. It's too little information for me to help you....

**Comment by raymond-li0518** [comment]
I think maybe it is because the server stop the listen process due to some exception, so i wanna ask for help how to set up the listen timeout of server. Thank you
