### ISSUE TITLE
How should I use Post in client?

### ISSUE THREAD

**Issue by njh0602** [yhirose/cpp-httplib#166]
Can I replace the curl library to use a simple get post function? 
For example, in my case I sent the following Post request using curl.

```
auto curl = curl_easy_init();
string data = "grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion=" + get_jwt();
curl_easy_setopt(curl, CURLOPT_URL, "https://www.googleapis.com/oauth2/v4/token");
curl_easy_setopt(curl, CURLOPT_POSTFIELDS, data.c_str());
curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_callback);
curl_easy_setopt(curl, CURLOPT_WRITEDATA, &read_buffer);
if (curl_easy_perform(curl) == CURLE_OK)
{
	cout << read_buffer << endl;
}
curl_easy_cleanup(curl);
```

Always worked well. And I ported it as follows. (is this the right way?)

```
httplib::Client cli("https://www.googleapis.com/oauth2/v4");
string data = "grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion=" + get_jwt();
auto res = cli.Post("/token", data.c_str(), "text/plain");
if (res) 
{
	if (res->status == 200)
	{
	      cout << res->body << endl;
	}
	else
	{
		cout << res->status << endl;
	}
}
else
{
	cout << "res is null" << endl;
}
```

And I tried this too.

```
httplib::Client cli("https://www.googleapis.com/oauth2/v4/token");
httplib::Params params;
params.emplace("grant_type", "urn:ietf:params:oauth:grant-type:jwt-bearer");
params.emplace("assertion", get_jwt());
auto res = cli.Post("/", params);
// same code ...
```

Always "res is null" is printed.
I need help.

**Comment by yhirose** [comment]
@njh0602, can you try it with `httplib::SSLClient` instead?
https://github.com/yhirose/cpp-httplib#openssl-support

**Comment by njh0602** [comment]
@yhirose, 
Thank you for your quick reply.
I tried, but the result is same.  Is this not an authentication issue with ssl? (such as CA list)

```
cli.set_cert_path(...);
cli.enable server_certificate_verifacation(true);
```

I do not currently have any certificates. Or what else should I do? I don't know about this part.

**Comment by njh0602** [comment]
```
httplib::SSLClient cli("https://www.google.com");
cli.set_ca_cert_path("./cacert.pem");
cli.enable_server_certificate_verification(true);
auto res = cli.Get("/");
// ...
```

cacert.pem was downloaded with the following command:
```> curl --remote-name --time-cond cacert.pem https://curl.haxx.se/ca/cacert.pem```

but code is not work.
Is there any other part I missed?

**Comment by yhirose** [comment]
@njh0602, your latest code looks good to me. The ca cert that you downloaded may not be good.

Here is working unit test on CI servers. Hope it helps.
https://github.com/yhirose/cpp-httplib/blob/master/test/test.cc#L1354-L1369
