### ISSUE TITLE
Linker error when creating server

### ISSUE THREAD

**Issue by kisbAlt** [yhirose/cpp-httplib#1661]
I included the header file like this in my .cpp file:
`#include <httplib.h>`
The code compiles successfully without calling any function, but as soon as I declare the server in my main function like `httplib::Server svr;` I am getting the following error:

`Error	LNK2001	unresolved external symbol "__declspec(dllimport) private: static void __cdecl std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >::_Start_element_lifetimes(char * const,unsigned __int64)" (__imp_?_Start_element_lifetimes@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@CAXQEAD_K@Z)`

I did add the directory in the additional include directories, where the httplib.h is present. Is there something I messed up when linking the header?

**Comment by yhirose** [comment]
@kisbAlt thanks for the feedback. `_Start_element_lifetimes` isn't a part of cpp-httplib. So I actually don't know...
