### ISSUE TITLE
how to post form-data as client?

### ISSUE THREAD

**Issue by Seazer-x** [yhirose/cpp-httplib#1662]
![image](https://github.com/yhirose/cpp-httplib/assets/62045004/4495e18f-bac9-4275-94cb-b62ecd29d115)
It includes a file and a key-value map. I found an API that can only accept Multipart Form Data but cannot simultaneously add key-value data.

**Comment by yhirose** [comment]
Please see [README](https://github.com/yhirose/cpp-httplib#post-with-multipart-form-data) and examples in `test/test/cc`.

**Comment by Seazer-x** [comment]
![image](https://github.com/yhirose/cpp-httplib/assets/62045004/53bbaa56-457a-41f5-8637-8fda19a88e19)
![image](https://github.com/yhirose/cpp-httplib/assets/62045004/d72a9c2b-a1ee-453d-b877-56c7fcf002dd)
I believe that "expiry" and "filePath" should not be included within the multipart part. Instead, they should be passed as key-value pairs, and not appear as multipart parts. The Spring Boot backend is unable to correctly parse "expiry" and "filePath" in this multipart part context.How can this problem be resolved? Could you please provide me with an example code? I'm not very skilled at this.

**Comment by Seazer-x** [comment]
![image](https://github.com/yhirose/cpp-httplib/assets/62045004/cb68c45c-982c-4ef3-aace-19839df89c86)
i used curl and cpp-httplib post data,but only curl post data be decode successly？
