### ISSUE TITLE
cpp-httplib supporting mTLS

### ISSUE THREAD

**Issue by DANGOEHR** [yhirose/cpp-httplib#1666]
I saw so far from the examples that its possible to use TLS, 
now comes up from our side following question:
is it also possible to use mTLS? Are this feature already implemented.

Thank you very much

**Comment by yhirose** [comment]
cpp-httplib doesn't provide APIs to handle mTLS directly. But, SSLClient can specify a client certificate in the constructor, and SSLServer can get a peer cert object via `SSL_get_peer_certificate`. Hope it helps.

https://github.com/yhirose/cpp-httplib/blob/c029597a5a92e48a3f373a615b82962c2e35621c/test/test.cc#L4981

**Comment by DANGOEHR** [comment]
Thank you very much! for your time and prompt response. Yes I will check it out how I can achieve with your suggestion the mTLS in indirect way.
