### ISSUE TITLE
Example SSL / TLS Certificates and Keys

### ISSUE THREAD

**Issue by DANGOEHR** [yhirose/cpp-httplib#1667]
At the example we found one which explain roughly how to setup an ssl / tls connection.

Our problem is how to generate all this PEM and CRT files which are used bei this libary. Can somebody please
give an example to have it with and selfsigned CA?

We used following commands and failed to establish the connection if we wanted to switch on server cert verification:

OpenSSL:
openssl genrsa 2048 > ca-key.pem
openssl req -new -x509 -nodes -days 365000 -key ca-key.pem -out ca-cert.pem 

openssl req -newkey rsa:2048 -nodes -days 365000 -keyout server-key.pem -out server-req.pem
openssl x509 -req -days 365000 -set_serial 01 -in server-req.pem -out server-cert.pem -CA ca-cert.pem -CAkey ca-key.pem

openssl req -newkey rsa:2048 -nodes -days 365000 -keyout client-key.pem -out client-req.pem
openssl x509 -req -days 365000 -set_serial 01 -in client-req.pem -out client-cert.pem -CA ca-cert.pem -CAkey ca-key.pem

We created then the crt files from client-key.pem, client-cert.pem and it got not really accepted.

**Comment by yhirose** [comment]
@DANGOEHR thanks for the question, but it's not about cpp-httplib related matters, but it's a general question about OpenSSL. So I'll close it. Thanks for your understanding.

**Comment by DANGOEHR** [comment]
Thank you very much for your fast response! Well I suggest to have at least a full set of such pem/crt in the repository for fast testing and understanding the procedure of it. At the moment its for me not completely clear what precisely needs to be in the ca bundle crt file. However thank you very much!
