### ISSUE TITLE
SSL build fails with mingw

### ISSUE THREAD

**Issue by JamesBremner** [yhirose/cpp-httplib#1669]
The README states

>SSL support is available with CPPHTTPLIB_OPENSSL_SUPPORT. libssl and libcrypto should be linked.

Using this, the linker generate many undefined errors

Issue #1561 states

> target_link_libraries(SafeTool PRIVATE ${CSP_LIBRARY} wsock32 ws2_32 crypt32 OpenSSL::SSL OpenSSL::Crypto

This also generate undefined errors.

To successfully build SSL support in mingw the following libraries need to be linked _in this order_

`-lcrypt32 -lssl -lcrypto -lws2_32`

Note: this is a documentation bug.

**Comment by yhirose** [comment]
@JamesBremner thanks for the feedback since I have never used cpp-httplib with mingw before. The README statement is just a general instruction. I'll keep it as 'information' so that other mingw users could benefit from it.

**Comment by JamesBremner** [comment]
Please edit your readme so that it has the correct instructions for building with mingw.  You should also edit issue #1561 since the 'fix' is wrong.

**Comment by sum01** [comment]
Sort of unrelated, but since the person in #1561 was using Cmake, couldn't they could just do
```cmake
find_package(httplib COMPONENTS OpenSSL REQUIRED)
``` 
and then link against `httplib:httplib`, unless something broke since I last tested it?

 Although I haven't tested the `COMPONENTS` impl on MinGW but... w/e

**Comment by JamesBremner** [comment]
I am not very familiar with the intricacies of CMAKE, but as I remember the problem with #1561 was that it links the libraries in the wrong order, so undefined reference errors are generated.  I do not think that your suggestion addresses that problem.

**Comment by sum01** [comment]
So simply reordering the [target_link_libraries](https://github.com/yhirose/cpp-httplib/blob/cefb5a88226bf832c9219fea7349e839094c1606/CMakeLists.txt#L217-L231) is really all that's needed?

I currently don't have an env setup for MinGW testing anymore, but it's a simple fix if this is really all it is.

**Comment by JamesBremner** [comment]
As I stated when I opened this issue:  "this is a documentation bug."

The documentation is still wrong.  Please update the documentation and THEN close the issue.
