### ISSUE TITLE
Segmentation fault on status access after Get with empty query

### ISSUE THREAD

**Issue by JamesBremner** [yhirose/cpp-httplib#1670]
This code works perfectly

```
#define WIN32_LEAN_AND_MEAN
#include <Windows.h>
#include "httplib.h"

#include "cOSMOverpass.h"

void cOSMOverpass::doQuery()
{

    // https://github.com/yhirose/cpp-httplib

    httplib::Client cli(myHost);

    makeQuery();

    auto res = cli.Get(myQuery);

    std::cout << res->status << "\n";
}
```

However if something goes wrong in the makeQuery method, accessing res->status generates an application crash with segmentation fault.  

Simulated like this

![image](https://github.com/yhirose/cpp-httplib/assets/2046227/ac6f1155-a15f-45ed-ab67-19e1816587d9)

`httplib::Client::Get()` should throw an exception or return a properly formed `res->status` if the query is malformed.

This is a coding bug.

**Comment by yhirose** [comment]
Please see [ the 'Client' section](https://github.com/yhirose/cpp-httplib#client-1) in README.

Your code should be as below:

```cpp
if (res) {
  std::cout << res->status << std::endl;
} else {
  auto err = res.error();
  std::cout << "HTTP error: " << httplib::to_string(err) << std::endl;
}
```

Hope it helps.

**Comment by JamesBremner** [comment]
Your suggested code does NOT fix the problem.

The line

    std::cout << res->status << std::endl;

generates a segmentation fault and crashes the application.

Please re-open this bug issue

**Comment by JamesBremner** [comment]
I see.

res evaluates to false if there is a problem, even though res->status is OK.

You should really document that behaviour - it is weird!

This code fixes things

        auto res = cli.Get(myQuery);

        if( ! res )
            throw std::runtime_error(
                "cOSMOverpass: Bad Query" );
