### ISSUE TITLE
Help: 'Expected unqalified-id before `-` token at `#define INVALID_SOCKET (-1)` on armv7hf

### ISSUE THREAD

**Issue by sk-lemken** [yhirose/cpp-httplib#1672]
Hi there,

the problem could be me.
But I included the lib in a project to serve some static files and one computed resource.

On compilation I get the following error:
```
error: expected unqualified-id before ‘-’ token
 #define INVALID_SOCKET (-1)
```

GCC Version: 8.3.0
Platform: armv7hf
C++ 17
libstdc++ 11

Any hints, how to solve this is appreciated.

**Comment by yhirose** [comment]
@sk-lemken sorry, but I have no idea... The following article could be helpful, and also you can find a number of stackoverflow posts related to this error message.

https://www.geeksforgeeks.org/expected-unqualified-id-error-in-cpp/#
