### ISSUE TITLE
+ = ? # dont work in url for get and works only with post (but not for =)

### ISSUE THREAD

**Issue by sip-for-telegram-com** [yhirose/cpp-httplib#1673]
hi @yhirose 

am using this

```
svr.Get(R"(/api/carrier/send?([a-z0-9\\-]+))", [&](const Request& req, Response& res) {
    text = req.get_param_value("message");  
    svr.stop();
 });
```

is there is any idea how to parce this url

`/api/carrier/send?message="[test] 123 ?????? ##### ++++ test ====  123"
`

or here are no solution coz of http standarts?

this works for post only 

and only for `? # +`

not for` =`

https://reqbin.com/

```
 svr.Post(R"(.*)", [&](const Request& req, Response& res) {
    text = req.get_param_value("message");
    res.set_content(text, "text/plain");
    svr.stop();
 });
```

![image](https://github.com/yhirose/cpp-httplib/assets/112954968/c000b000-d382-4966-9df8-0c7397150a7e)

**Comment by sip-for-telegram-com** [comment]
this do same result(

```
 svr.Get(R"(.*)", [&](const Request& req, Response& res) {
 text = req.get_param_value("message");  
    svr.stop();
 });
```

**Comment by sip-for-telegram-com** [comment]
this works for post only

https://reqbin.com/


```
 svr.Post(R"(.*)", [&](const Request& req, Response& res) {
    text = req.get_param_value("message");
    res.set_content(text, "text/plain");
    svr.stop();
 });
```

**Comment by yhirose** [comment]
@sip-for-telegram-com `R"(/api/carrier/send?([a-z0-9\\-]+))"` should be `R"(/api/carrier/send)"`. 
https://github.com/yhirose/cpp-httplib/blob/c029597a5a92e48a3f373a615b82962c2e35621c/test/test.cc#L1229-L1264
Hope it helps.

**Comment by sip-for-telegram-com** [comment]
> `R"(/api/carrier/send?([a-z0-9\\-]+))"` should be `R"(/api/carrier/send)"`.

@yhirose 

it doesn't matter 

these 4 characters still don't work in get

the example from cpp-httplib/test/test.cc also does not work

```
svr.Get("/foo", [](const Request &req, Response &res) {
      auto a = req.params.find("a");
```

it won't work with these symbols `+ = ? #`

**Comment by yhirose** [comment]
I don't think it's a problem in cpp-httplib. Could you make sure that those characters in the query string keys and values are properly encoded (URL encoding, or percent encoding) in your client program?

**Comment by sip-for-telegram-com** [comment]
> I don't think it's a problem in cpp-httplib. Could you make sure that those characters in the query string keys and values are properly encoded (URL encoding, or percent encoding) in your client program?


`This is definitely a cpp-httplib problem` - I tested nging from the browser today and it correctly parsed these characters from the url

You can test my simple example on your local host through a browser to make sure I'm right

this will not work for 

/api/carrier/send?message="[test] 123 ?????? ##### ++++ test ====  123"

at sami time - nginx work with this url

you can just put this in chrome and test on localhost -  its 100% cpp-httplib issue




```
#include "httplib.h"
#include <iostream>
using namespace std;
using namespace httplib;

Server svr;

int main() {
 
svr.Get(R"(/api/carrier/send?([a-z0-9\\-]+))", [&](const Request& req, Response& res) {
    string text = req.get_param_value("message");
    cout << text;
 });


    svr.listen("0.0.0.0", 1111);

return 0;}
```

**Comment by yhirose** [comment]
As I mentioned, your Get handler code isn't correct, and it should be as below:

```cpp
svr.Get(R"(/api/carrier/send)", [&](const Request& req, Response& res) {
    string text = req.get_param_value("message");
    cout << text;
 });
```

Also your query value string `"[test] 123 ?????? ##### ++++ test ====  123"` should be properly encoded as `%22%5Btest%5D%20123%20%3F%3F%3F%3F%3F%3F%20%23%23%23%23%23%20%2B%2B%2B%2B%20test%20%3D%3D%3D%3D%20%20123%22`.

Here is my test code, and I confirmed it worked fine.

```cpp
int main() {
  httplib::Server svr;

  svr.Get("/test", [&](const httplib::Request &req, httplib::Response &res) {
    std::cout << "a request has been sent..." << std::endl;
    res.body = req.get_param_value("message");
  });

  svr.listen("localhost", 8080);
  return 0;
}
```

<img width="565" alt="image" src="https://github.com/yhirose/cpp-httplib/assets/357397/2f073e08-baf7-4739-aed5-9de288cf7a69">

Hope it helps!

**Comment by sip-for-telegram-com** [comment]
hi @yhirose
thanks for your support.

it works!

thanks
