### ISSUE TITLE
+ = ? # and svr.Get

### ISSUE THREAD

**Issue by sip-for-telegram-com** [yhirose/cpp-httplib#1674]
Is a working example possible?

how on the server side parce these symbols

`+ = ? #`

`svr.Get `is generally able to work with them? i done see any working samples even in test.cc

`svr.Post` works only with     `+ ? # `   but still does not accept `=`

**Comment by yhirose** [comment]
Closed since it is the same as #1673.

**Comment by sip-for-telegram-com** [comment]
> Closed since it is the same as #1673.
@yhirose 
it is the same because there is no solution
