### ISSUE TITLE
HTTP [Errno 104] Connection reset by peer if more than 5 simultaneous requests

### ISSUE THREAD

**Issue by sip-for-telegram-com** [yhirose/cpp-httplib#1675]
hi @yhirose

Is there any limit on the number of simultaneous requests equal to 5?

looks like this Limit on simultaneous open http sessions

Is there any way to increase the acceptance parameter is launched in the server?

```
GET http://1.1.1.1:1111/api/carrier/status?messageId=1f640d11-d14f-4a1c-b57d-918798f078c8

ERROR: except with an other error in HTTP [Errno 104] Connection reset by peer
```

maybe there is simple way how to make it work for 10-50-100 simultaneous requests, not only for 5?

it`s log from client side

it can be easy tested by

`siege http://localhost/api/carrier/send?message=aaaaaaaaa`

**Comment by sip-for-telegram-com** [comment]
seems like 
https://github.com/yhirose/cpp-httplib/pull/957

**Comment by sip-for-telegram-com** [comment]
it can be easy tested by

`siege http://localhost/api/carrier/send?message=aaaaaaaaa`

**Comment by sip-for-telegram-com** [comment]
NOTE: This library uses 'blocking' socket I/O. If you are looking for a library with 'non-blocking' socket I/O, this is not the one that you want.

seems its  library limitations and even in multi-threading I will not be able to solve my problem?

**Comment by yhirose** [comment]
> maybe there is simple way how to make it work for 10-50-100 simultaneous requests, not only for 5?

You may want to try adjusting the thread pool parameters mentioned in the following:
https://github.com/yhirose/cpp-httplib#default-thread-pool-support

If it doesn't solve your problem, cpp-httplib is probably not for you and please find another library.

**Comment by sip-for-telegram-com** [comment]
so far I've done this

svr.new_task_queue = [] { return new ThreadPool(9999); };

this works for about 10 simultaneous requests

I'm not sure this is the right way...
