### ISSUE TITLE
is there any way to find out from clien side only - if cli.Get(url) was successful?

### ISSUE THREAD

**Issue by sip-for-telegram-com** [yhirose/cpp-httplib#1676]
```
 Client cli(....);
cli.Get(.....);
```

is there any way to check whether the client's request to the server was successful?

 I'm using cpphttp for server and client
and sometimes my server binaries hang

is there any way to find out from clien side only - if cli.Get(url) was successful?

**Comment by yhirose** [comment]
Please see the readme info here:
https://github.com/yhirose/cpp-httplib#client-1
