### ISSUE TITLE
between localhost - HTTP error : Failed to read connection &  HTTP error : Could not establish connection

### ISSUE THREAD

**Issue by sip-for-telegram-com** [yhirose/cpp-httplib#1677]
hi @yhirose [yhirose](https://github.com/yhirose)
i use client and server only on localhost - 2 app - client and server  running on 127.0.0.1
very often i get this  in cpp httplib logs

```
HTTP error : Failed to read connection
HTTP error : Could not establish connection
```
code client
```
    Client gw(localhost:8888);
    gw.set_keep_alive(true);
    gw.set_connection_timeout(0, 1000000); 
    gw.set_read_timeout(1, 0); 
    gw.set_write_timeout(1, 0);



if (auto res = gw.Get(s_url))  {
   if (res->status == 200)  
    cout<< ok << endl;               }
    
    else                                                          {
    auto err = res.error();
    cout<< httplib::to_string(err) << endl;  }

```

server part

```
svr.set_keep_alive_max_count(1);
svr.set_keep_alive_timeout(1);
svr.set_read_timeout(1, 0); 
svr.set_write_timeout(1, 0);
svr.set_idle_interval(0, 500000); 
svr.set_payload_max_length(1024 * 1024 * 1); 
```

Interestingly

if I put requests in a loop - one out of 2-3 will be successful

then these errors again

and again successful requests

maybe I need to change the timeout values or something like that?

What optimal timeout values can you recommend for localhost? 

Maybe I specified something incorrectly?

**Comment by yhirose** [comment]
Since I don't know the actual situation of your network environment, I am not able to give you any meaningful information. Please try to find the best possible parameter values yourself. Sorry about that...

**Comment by sip-for-telegram-com** [comment]
> Since I don't know the actual situation of your network environment, I am not able to give you any meaningful information. Please try to find the best possible parameter values yourself. Sorry about that...

I was just surprised by these errors, where can they come from if I just use localhost...
