### ISSUE TITLE
macOS webcam streaming.

### ISSUE THREAD

**Issue by rvegele** [yhirose/cpp-httplib#1678]
Hello, 

I'm trying to use cpp-httplib for streaming from a webcam. 
I'm also using it with openframeworks library. 
I'm working in Xcode 15 on macOS 

I'm faced with a strange problem that I can't really explain. I've first tried using cpp-httplib yesterday and it worked OK (setting up the server). Today however (without any code changes) I can't seem to get the server to start. The project builds but it seemingly gets stuck on the following step svr.listen("localhost", 1234);. If I comment it out the project builds fine and I get my application window to show up. 

I'm not getting any build errors or anything :/ Just wondering if anyone's faces this type of a problem before and what I could do to debug this. 

Is there any cache I need to reset or something? As it seems I can't start the server :/

**Comment by rvegele** [comment]
No sure if this helps but I got " Thread 1 : signal SIGTERM " at
line 6153 : socket_t sock = accept(svr_sock, nullptr, nullptr)

**Comment by rvegele** [comment]
hmm... it seems that the sever starts, but it seemingly stops my GLFWWindow from showing up.

**Comment by rvegele** [comment]
hmmm... it does seem like the http library totally messes up my openFrameworks loop, so nothing is being updated in the background any more

**Comment by rvegele** [comment]
Putting httpcpp on its own thread seems to have solved my GL problems.

**Comment by yhirose** [comment]
@rvegele, yes, you have to call the `listen` method in a separate method. You can see a number of examples in `test/test/cc`. Anyway, I am glad to see that  you found a correct way to set the server up!
