### ISSUE TITLE
 VS2015 build fail 

### ISSUE THREAD

**Issue by huangshangbin** [yhirose/cpp-httplib#168]
error C2589: “(”:“::”  Illegal marking on the right

line 93, #define CPPHTTPLIB_PAYLOAD_MAX_LENGTH std::numeric_limits<size_t>::max()
Change to
            #define CPPHTTPLIB_PAYLOAD_MAX_LENGTH (std::numeric_limits<size_t>::max)()

**Comment by yhirose** [comment]
@huangshangbin, thanks for your contribution!
