### ISSUE TITLE
Suspend / resume handling of requests

### ISSUE THREAD

**Issue by floli** [yhirose/cpp-httplib#1680]
Hello,

this is is only a question / support request.

We have an application with a number of handlers scattered through the code. The handler access objects, which are not thread safe. There is, however, a single place where updates to the object are triggered, i.e., outside of the update cycle, it's safe to access the objects used in the handlers.

I am looking for something like that:

```
server.pause();
update_my_objects();
server.resume();
```

when the server is paused, no handlers are called and incoming requests are sent to the ThreadPool.

Is something like that possible? Or do you see an alternative approach to my problem?

Thanks a lot!

**Comment by yhirose** [comment]
Sorry for the late reply It's pretty hard to implement such features...
