### ISSUE TITLE
send content to css div variable

### ISSUE THREAD

**Issue by xjsxujingsong** [yhirose/cpp-httplib#1682]
Hi, I basically have a format html which can recieve two variables to update. Given the below html code, how should I use "res.set_content" to send values to the two variable: page_head and image? Thanks. 
    auto ret = svr.set_mount_point("/", "./static");
 svr.Get("/", [](const httplib::Request&, httplib::Response& res) {
        res.set_content("", "text/html");
});

![image](https://github.com/yhirose/cpp-httplib/assets/1683858/0400aa77-3a2c-4ded-95fe-19a1673f9e1f)

**Comment by yhirose** [comment]
It's not a question about cpp-httplib, I have no idea. Sorry...

**Comment by xjsxujingsong** [comment]
@yhirose Thanks for your quick response.
I found an issue https://github.com/yhirose/cpp-httplib/issues/235#issuecomment-539620500 and thought how it works.

_Alternatively, you may send the base64 encoded image with the text/plain or text/html content type and use JavaScript or HTML to put that string into the src of an <img> element_
