### ISSUE TITLE
Do you have an example of how to encode text correctly?

### ISSUE THREAD

**Issue by sip-for-telegram-com** [yhirose/cpp-httplib#1684]
from https://github.com/yhirose/cpp-httplib/issues/1673

i have this string

`"[test] 123 ?????? ##### ++++ test ====  123"`

i want use it for send to srv.

hot do i can get this 

`"%5Btest%5D%20123%20%3F%3F%3F%3F%3F%3F%20%23%23%23%23%23%20%2B%2B%2B%2B%20test%20%3D%3D%3D%3D%20%20123".`

Perhaps there are some standard simple encoding methods?

**Comment by yhirose** [comment]
https://developer.mozilla.org/en-US/docs/Glossary/Percent-encoding

**Comment by sip-for-telegram-com** [comment]
hi @yhirose 
thanks

I tried something like
https://techoverflow.net/2023/05/05/how-to-encode-url-query-parameters-in-c-using-boost-url/

but it looks like boost has its own logic

instead of
`%5Btest%5D%20123%20%3F%3F%3F%3F%3F%3F%20%23%23%23%23%23%20%2B%2B%2B%2B%20test%20%3D%3D %3D%3D%20%20123`

I only received
`%5Btest%5D%20123%20??????%20%23%23%23%23%23%20++++%20test%20====%20%20123`

I will try other libraries
