### ISSUE TITLE
svr.Get - processing simultaneous http requests

### ISSUE THREAD

**Issue by sip-for-telegram-com** [yhirose/cpp-httplib#1686]
hi [yhirose](https://github.com/yhirose) @yhirose

is there any easy way to add all requests to svr.Get into a new thread?

**Comment by yhirose** [comment]
Thanks for the question, but I don't understand what you are asking...

**Comment by sip-for-telegram-com** [comment]
hi @yhirose 

Thanks for the reply.

I meant maybe you have simple sample

how to  call `svr.Get` every time in a new c++ thread

calling all server code including `svr.listen`

so that each new request to` svr.Get` is processed in a separate thread

**Comment by yhirose** [comment]
cpp-httplib server already puts incoming requests in separate threads (thread managed by ThreadPool). Only exception is when the HTTP KeepAlive is enabled. In this case, a series of KeepAlive requests from the same endpoint should be serialized and cannot be put into a different thread. Hope this information helps.
