### ISSUE TITLE
https scheme error ： debug aborted

### ISSUE THREAD

**Issue by breaking153** [yhirose/cpp-httplib#1688]
i'm using cmake+vcpkg, show error like :
![图片](https://github.com/yhirose/cpp-httplib/assets/49428332/256edaf0-59e6-4b3e-9767-d722816d0f09)

and http scheme can normally work

**Comment by breaking153** [comment]
![图片](https://github.com/yhirose/cpp-httplib/assets/49428332/54bd32fa-8301-4783-aadf-dc34bc9f5dae)
vcpkg:
![图片](https://github.com/yhirose/cpp-httplib/assets/49428332/8e3b428c-743d-4ef6-93dd-335b882b15aa)

**Comment by yhirose** [comment]
I guess I haven't installed OpenSSL in your system.
