### ISSUE TITLE
Way to consume raw requests?

### ISSUE THREAD

**Issue by Alex-dev02** [yhirose/cpp-httplib#1696]
Hi!

Sorry for bothering, but I have a question. Is there any way to use the library to parse a raw request, for example a function that would take as param only a string being the raw http request and would consume it? I looked through the header but couldn't find something like this.

Example:
```
Request req;
req.parse(raw_request);
req.get_param(key);
req.get_body();
```

**Comment by yhirose** [comment]
@Alex-dev02 thanks for the question, but unfortunately there is not such a thing in cpp-httplib...
