### ISSUE TITLE
If it is possible to make a loosen rule for path that contains `?` character

### ISSUE THREAD

**Issue by neil4dong** [yhirose/cpp-httplib#1697]
Now cpp-httplib checks URL that the parameters part should contains at most 2 `?` 
This made some user case not feasible. 

**the code in cpp-httplib:**
```c++
inline bool Server::parse_request_line(const char *s, Request &req) {
    .........

    size_t count = 0;

    detail::split(req.target.data(), req.target.data() + req.target.size(), '?',
                  [&](const char *b, const char *e) {
                    switch (count) {
                    case 0:
                      req.path = detail::decode_url(std::string(b, e), false);
                      break;
                    case 1: {
                      if (e - b > 0) {
                        detail::parse_query_text(std::string(b, e), req.params);
                      }
                      break;
                    }
                    default: break;
                    }
                    count++;
                  });

    if (count > 2) { return false; }
  }

  return true;
}
``` 

for example:
https://host/concat-file-path??/path/file1.js,/path/file2.js?timestample=123456
Now， cpp-httplib will response STATUS 400

**Other lib：**
1. In nginx there is a built-in plugin call `nginx-concat`, this plugin can response multiple file in one http roundtrip

2. In Tomcat，  will only consider the first `?` as the separator between path and parameters.   the second and so on will consider as normal characters.

**Comment by yhirose** [comment]
@neil4dong thanks for the suggestion, but I would like to keep cpp-httplib simple and focus on the standard URI format only.
