### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by omaralvarez** [yhirose/cpp-httplib#170]
Would it be possible for you to release a initial version (even if it is 0.1)? Using tags and the github release system. I would like to create a conan package that points to your repo for easy compilation using CMake.

I have made a pull request to add CMake support. Once you are satisfied with it, it would be nice if you made a release so I can properly add Conan support for master and the first version number.

**Comment by omaralvarez** [comment]
@yhirose Now that CMake support is added is a perfect time for a release! :wink: I will have another pull request with Conan support as soon as it is created.

**Comment by yhirose** [comment]
@omaralvarez, I just added 'v0.2.0' tag. Let me know what else should be done on my side.

**Comment by omaralvarez** [comment]
@omaralvarez Perfect! Now the ball is in my court. 👍

**Comment by yhirose** [comment]
@omaralvarez, any progress?

**Comment by omaralvarez** [comment]
I actually was working on it today, but CMake gave me issues, I may have to open another pull request.

**Comment by omaralvarez** [comment]
CMake error fixed. Would it be possible for you to accept it and recreate `v0.2.0`? The conan package is ready, and will just need these changes to work.

**Comment by yhirose** [comment]
@omaralvarez, thanks for the progress. Only thing is the version number. Does 'recreate `v0.2.0`' mean remove the tag and add it to the latest commit, or something else? The reason why I am concerned with the version number is that someone kindly registered cpp-httplib to vcpkg library manager at https://github.com/Microsoft/vcpkg/pull/7037. So I just wonder if the `v0.2.0` should stay at the current commit (2f8479016fa9af9a63056571992b31c32741d89b).

**Comment by omaralvarez** [comment]
Sounds good. Just release a new version then. e.g. v0.2.1

**Comment by yhirose** [comment]
@omaralvarez, I added `v0.2.1` tag.

**Comment by omaralvarez** [comment]
@yhirose Thanks a lot and sorry for my silly mistake that made us create another tag. Another pull request coming with information about using Conan with the library.

**Comment by omaralvarez** [comment]
@yhirose Done! #195

**Comment by yhirose** [comment]
@omaralvarez, @Pospelove, thanks for your contribution.

In fact, a serious bug has been reported after `v0.2.1` has been released, and `v0.2.2` may be coming soon. Also there will be even more coming one after another for bug fixes and new features. :)

Since I would like to encourage people to always use the latest release, it would be nice if there is a way to detect a new release of cpp-httplib and register it to Conan and vcpkg **automatically not without notifying you**. Otherwise, people may keep using older versions...

Do you have any thought? Thanks!

**Comment by ras0219-msft** [comment]
In vcpkg, we have some automatic-upgrade processes that we run occasionally. However, at any time, if you want an upgrade to happen sooner, we're happy to accept one-off PRs to upgrade a specific library.

**Comment by omaralvarez** [comment]
For now I have never done it automatically, but I'll look into it. I will be paying close attention meanwhile and update the repo manually.

**Comment by omaralvarez** [comment]
I have updated the latest versions and also added OpenSSL support. Automatization still not sure.

**Comment by yhirose** [comment]
https://github.com/memunix/conan-cpp-httplib
https://github.com/microsoft/vcpkg/pull/8172

**Comment by omaralvarez** [comment]
My recipe is here:

https://github.com/omaralvarez/conan-httplib

Everything has been updated and working fine with OpenSSL also.

**Comment by yhirose** [comment]
@omaralvarez, thanks for keeping it up to date!

**Comment by yhirose** [comment]
Close it for now.
