### ISSUE TITLE
Mingw cross-compilation -lcryptui not found.

### ISSUE THREAD

**Issue by montarcannon** [yhirose/cpp-httplib#1703]
I'm trying to cross-compile small project that uses cpp-httplib with openssl using cmake and mingw. 
Cmake runs fine but make fails with following output:
`
[ 50%] Linking CXX executable cr_persist.exe
/usr/bin/i686-w64-mingw32-ld: cannot find -lcryptui: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/cr_persist.dir/build.make:106: cr_persist.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/cr_persist.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`
probably i'm missing some library but i don't know which.

**Comment by yhirose** [comment]
@sum01, @jimmy-park  do you have any clue?

**Comment by jimmy-park** [comment]
I have successfully built with MinGW-w64 on my [CMake workflow](https://github.com/jimmy-park/cpp-httplib/actions/runs/6723104501/job/18272437145).
It seems like `cryptui.dll` is missing on your machine.

**Comment by jimmy-park** [comment]
Do we really need to link the `cryptui` library on Windows? I couldn't find any method provided by `cryptui`.
And removing `cryptui` doesn't affect on building with `httplib.h`.

**Comment by yhirose** [comment]
@jimmy-park, thanks for the answers. @montarcannon, hope the above inform helps.

**Comment by montarcannon** [comment]
> I have successfully built with MinGW-w64 but failed with MinGW32. Please see my [CMake workflow](https://github.com/jimmy-park/cpp-httplib/actions/runs/6723743785/job/18274474044). It seems like `cryptui.dll` is missing on MinGW32.

you ran into same problems as i did
