### ISSUE TITLE
Decompress gzip-compressed Json

### ISSUE THREAD

**Issue by Skipper89rus** [yhirose/cpp-httplib#1705]
Hi! Thank you for very nice lib!
I'm trying to write a client for my rest api.
What I need is to send post request with gzip-compressed Json and than receive gzip-compressed Json. 
Looks, compression for request works ok, but I can't understand how to get decompressed Json in res->body.
I'm trying to debug gzip_decompressor::decompress, and with next code reached this function. But still has compressed data in body.
What I'm doing wrong, or mb this function doesn't work?) Can you please help me here)
`
#define CPPHTTPLIB_ZLIB_SUPPORT

httplib::Client client(_host, _port);
client.set_compress(true);

const auto res = client.Post(buildUrl(path), { { "Accept-Encoding", "gzip" } }, requestData.dump(), "application/gzip");
if (res->status == 200) {
      std::cout << res->body << std::endl; // still compressed
      return json::parse(y);
}
`

**Comment by Skipper89rus** [comment]
For now I've done this workaround. Client post methods don't have functions with ContentReceiver, like get methods have.
`
const auto res = client.Post(buildUrl(path), { { "Accept-Encoding", "gzip" } }, requestData.dump(), "application/gzip");
if (res->status == 200) {
   std::cout << res->body << std::endl;

std::string body;
httplib::detail::gzip_decompressor decompressor;
decompressor.decompress(res->body.c_str(), res->body.size(), [&](const char* data, size_t data_length) {
   body.append(data, data_length);
   return true; // return 'false' if you want to cancel the request.
 });
`

**Comment by yhirose** [comment]
I'll close it for now. @Skipper89rus if you still have the problem, please let me know.
