### ISSUE TITLE
Unable to connect to localhost. 

### ISSUE THREAD

**Issue by montarcannon** [yhirose/cpp-httplib#1711]
I'm using examples/client.cc with minor modifications (using "define" for host port and path). I'm compiling my project with cmake and make.
Python http.server is running at port 8000.  It compiles alright but while trying to test it it throws ```error code: Could not establish connection (2)``` and does nothing more. Server receives no connection and wireshark sees no traffic. It happens regardless i'm using http or https. 

uname -a shows:
```Linux pop-os 6.5.4-76060504-generic #202309191142~1695998943~22.04~070916d SMP PREEMPT_DYNAMIC Fri S x86_64 x86_64 x86_64 GNU/Linux```

I'm including cpp-httplib as subdirectory of my project.

**Comment by yhirose** [comment]
Thank you for the feedback, but I can't give you any help from the information above. Sorry...
