### ISSUE TITLE
Behaviour when number of threads are exceeded.

### ISSUE THREAD

**Issue by marcovc** [yhirose/cpp-httplib#1718]
Hi,

Thanks for your libray. Sorry for the basic question, but I would like to know what happens to a request if all configured threads are still serving their corresponding requests. Will that request be dropped, or will it be maintained in some queue until one of the threads becomes available for processing?

Thanks!

**Comment by yhirose** [comment]
@marcovc it's up to a TaskQueue implementation given. As a default, it will use ThreadPool which is a simple thread pool implementation.

https://github.com/yhirose/cpp-httplib/blob/7fc8682a0a3eb0530314495005067dce8148a1aa/httplib.h#L590

If all the threads are in use, the request will wait until any thread becomes available.

You can make your own TaskQueue to control request queuing behavior as described in the following section in README.
https://github.com/yhirose/cpp-httplib#default-thread-pool-support

**Comment by marcovc** [comment]
Thanks!
