### ISSUE TITLE
Client timeout

### ISSUE THREAD

**Issue by marcovc** [yhirose/cpp-httplib#1733]
Hi,

I must be doing something wrong:

```
httplib::Client http_client(url);
auto timeout = std::chrono::milliseconds(200);
http_client.set_connection_timeout(timeout);
http_client.set_read_timeout(timeout);
http_client.set_write_timeout(timeout);

auto tic = std::chrono::system_clock::now();

http_client.Get(
  "endpoint", 
  params,
  headers
);

std::cout << std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now() -tic).count() << std::endl;
```

This prints 1861 (ms). I was expecting that it gives up waiting after 200 ms. What could be the issue?

Thanks

**Comment by yhirose** [comment]
Could you check the error code according to the example in README? It will tell you the reason. Hope it helps!

```cpp
#include <httplib.h>
#include <iostream>

int main(void)
{
  httplib::Client cli("localhost", 1234);

  if (auto res = cli.Get("/hi")) {
    if (res->status == 200) {
      std::cout << res->body << std::endl;
    }
  } else {
    auto err = res.error();
    std::cout << "HTTP error: " << httplib::to_string(err) << std::endl;
  }
}
```

**Comment by marcovc** [comment]
Sorry, but there is no error (res->status is 200). Should I still inspect the `res.error()` to understand why it is not timing out?

**Comment by yhirose** [comment]
If it returns 200, the connection was established and a http request has been handled properly. I am not sure why it took that long. Could you investigate the server side as well? At this point, I am not able to give you any helpful information...

**Comment by marcovc** [comment]
Unfortunately I have no access to the server. I'll try to create a minimum example.
