### ISSUE TITLE
When making a form-data request using OkHttp, a status code of 400 is returned.

### ISSUE THREAD

**Issue by yuanqi-pythoner** [yhirose/cpp-httplib#1736]
When making a form-data request using OkHttp, a status code of 400 is returned. Here is the captured packet phenomenon.
It seems that when there is a Content-Length field between the boundaries, this situation occurs.
![image](https://github.com/yhirose/cpp-httplib/assets/53937587/a1dfaffe-e5be-44a5-a88c-382c4ae8b972)

However, when I use curl to make a form-data request, it works fine, as shown below.
![image](https://github.com/yhirose/cpp-httplib/assets/53937587/9226815a-6997-48fe-a0b6-6950158220f6)

I have debugged cpp-httplib using Visual Studio 2019 breakpoints and found that it may be related to the following code snippet.
![image](https://github.com/yhirose/cpp-httplib/assets/53937587/e4f1a5bf-3336-4adf-9fae-c82d59faae84)

**Comment by yhirose** [comment]
@yuanqi-pythoner thanks for the report. I fixed it and it will be included in the next release '0.14.3'.
