### ISSUE TITLE
Function to format & send args with HTTP Get Request

### ISSUE THREAD

**Issue by ArjunNarayan2066** [yhirose/cpp-httplib#174]
I am trying to use this to send an HTTP Get Request to a URL that requires arguments. I was wondering if there is a supported Get Request Call to take & format args?

The default calls below:
```
  std::shared_ptr<Response> Get(const char *path, Progress progress = nullptr);
  std::shared_ptr<Response> Get(const char *path, const Headers &headers,
                                Progress progress = nullptr);
```
do not seem to support taking in arguments.

Thanks for your help

**Comment by yhirose** [comment]
@ArjunNarayan2066, sorry that README doesn't describe it well. Please see an example [here](https://github.com/yhirose/cpp-httplib/blob/master/test/test.cc#L1112-L1116).
