### ISSUE TITLE
post multipart/form-data errror

### ISSUE THREAD

**Issue by xiangxyq** [yhirose/cpp-httplib#1746]
hi

Server code as below:
` for (int i = 0; i < req.files.size(); i++) {

          std::string file_name = "file_" + std::to_string(i);
          const auto& file = req.get_file_value(file_name);
          std::cout <<  file_name << " " << file.content.size() << std::endl;
}`

if I post with more than one file, All files except the first file get size is 0. logs as below
<img width="240" alt="image" src="https://github.com/yhirose/cpp-httplib/assets/18209169/d7e3d038-8e09-4ff5-8ed5-0b48b3bd082e">

test code:
`import sys
from json.decoder import JSONDecodeError
from requests import post
from pathlib import Path

def _test(file):
  response = post("http://127.0.0.1:8765/test_api", files=file)

  try:
    return response.json()
  except JSONDecodeError:
    raise ValueError(f"返回的文本:{response.text}")

if __name__ == '__main__':
  file = sys.argv[1]
  with Path(file).open("rb") as test_file:
    __test_file = {"file_0": test_file.read(), "file_1": test_file.read(), "file_2": test_file.read()}
    print(_test(__test_file))
`

**Comment by yhirose** [comment]
@xiangxyq your python code looks incorrect...

a.py
```
from pathlib import Path

with Path('a.py').open("rb") as f:
    s = f.read()
    print(len(s))
    s = f.read()
    print(len(s))
    s = f.read()
    print(len(s))
```

```
> python3 a.py
166
0
0
```
