### ISSUE TITLE
Doesn't work containerized

### ISSUE THREAD

**Issue by jamesii-b** [yhirose/cpp-httplib#1753]
While I try to run the server locally on system it works fine, even with `wsl`. But when i docker containerize the `linux` image and run the `c++` server onto it, while i navigate to forwarded port, the server can't be seen. But inside the container, `curl` to the server:port as `localhost:portNo` seems working.

**Comment by yhirose** [comment]
@jamesii-b thanks for the feedback, but I don't think it's a cpp-httplib specific issue, but a general network configuration problem on docker. Could you try it with other HTTP libraries like oat++ to see if the same issue happens? Thanks!
