### ISSUE TITLE
Client not blocking for longer requests

### ISSUE THREAD

**Issue by rip32700** [yhirose/cpp-httplib#176]
I'm sending a request to a server instance that takes a few seconds to generate the response. However, the client side call is not blocking, it returns after 2-3 seconds before the server response is ready.

Client:
```
auto res = cli.Get("/get_value");
if (res && res->status == 200) { /*... */}
```

Server:
```
svr.Get("/get_value", [](const Request& req, Response& res){
   /* trigger calculation, takes a few seconds */
   res.set_content(value, "text/plain");
});
```

Is this intended behavior and if so is it possible to extend the timeout value?

**Comment by yhirose** [comment]
@rip32700, thanks for the feedback. You can configure the read timeout value with `#define CPPHTTPLIB_READ_TIMEOUT_SECOND 5` at https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L95.
Please let me know if it doesn't solve your issue.

**Comment by rip32700** [comment]
@yhirose did solve it, thanks!
