### ISSUE TITLE
Severe directory traversal vulnerability (dotdotslash)

### ISSUE THREAD

**Issue by cristiulian** [yhirose/cpp-httplib#1768]
It looks like you can easily attack a server written with this library via a directory traversal method.

The %2e%2e%5c character is equivalent to .. so by forging a special url, you can easily request any file on current drive (windows) or anywhere in the system (linux). There are some other equivalent characters too, I've only tested with the one above.
The is_valid_path function only tests against "..", but the list should be way longer.
You can traverse back from a folder (mount point) all the way to any folder and request files such as win.ini or /etc/passwd, expecially when you use the library from a service with elevated access.
This issue is extremely severe in my opinion, is there any way to prevent this behaviour?

**Comment by yhirose** [comment]
@cristiulian thanks for the report, but I am not able to reproduce it. I checked with 'example/simplesvr.cc' and curl.

Here is the result:
<img width="1201" alt="image" src="https://github.com/yhirose/cpp-httplib/assets/357397/d113ea12-9d99-4eb2-89fc-ddca8197bce4">

The cpp-httplib server decodes the percent encoded codes to '..', but `Server::is_valid_path` returns `false` if the path tries to see above the root.

https://github.com/yhirose/cpp-httplib/blob/82a90a2325343faaf1c0604561a5e2859fccc3fb/httplib.h#L2429-L2431

Could you really confirm that the problem happened on your environment? Also could you provide the smallest possible code example that can reproduce the problem?

Thanks for your help.

**Comment by cristiulian** [comment]
I've compiled simplesrv.cc and I can confirm it is happening on my environment (WIN 10, VS 2017 and VS 2022). I have used the **%2e%2e%5c** sequence, although the list of possible sequences is much longer, I can provide it if you want to. For some reason, some of them make it through the is_valid_path ".." check, I suppose they're not converted to "..".
Your example above uses a different sequence and indeed it works as expected and the request is rejected.

`curl -kI "http://localhost:8080/%2e%2e%5c/httplib.h"`

![dotdotslash1](https://github.com/yhirose/cpp-httplib/assets/419728/2db5083d-5792-4ec9-9fb4-797150a7d8c3)

**Comment by yhirose** [comment]
@cristiulian I confirmed this issue on my Windows machine and fixed it. Thanks for your report!

**Comment by yhirose** [comment]
Yes, I confirmed that it happened only on Windows.
