### ISSUE TITLE
Work with FreeRTOS to send a simple https request

### ISSUE THREAD

**Issue by alaarihan** [yhirose/cpp-httplib#177]
How can I use this with FreeRTOS to send a https request?  I think we need to use wolfSSL instead of openssl

**Comment by yhirose** [comment]
@alaarihan, thank you for the feedback. Unfortunately, I don't know anything about FreeRTOS. So I am not in a position to give you a correct answer. At least I know, the library should work if it supports C++11 compiler fully. I don't know anything about wolfSSL either. Right now, cpp-http only suports OpenSSL. Sorry about that. (A pull request for wolfSSl is very much welcome, of course. 😃 )
