### ISSUE TITLE
Breaking change on WinRT/UWP

### ISSUE THREAD

**Issue by sergio-nsk** [yhirose/cpp-httplib#1773]
This change https://github.com/yhirose/cpp-httplib/pull/1632 breaks WinRT/UWP builds - there is no [`CreateFileA()`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea#requirements) available

**Comment by yhirose** [comment]
@sergio-nsk thanks for the report. But I am not interested in working on it, since there is no way for me to test on WinRT/UWP. Could you handle it and send me a pull request? If so, I'll keep it as open. Thanks for your understanding.

**Comment by sergio-nsk** [comment]
Yes, I can, maybe later today.
