### ISSUE TITLE
Redirect to https

### ISSUE THREAD

**Issue by PixlRainbow** [yhirose/cpp-httplib#178]
Similar to #158, but not quite the same.
I figure it would be possible to implement automatic redirect from http to https, by starting both a Server and an SSLServer and simply sending 301 responses from the vanilla server directing clients to the port of the SSLServer. However, it would be a painfully manual process to have to manually implement a redirect for each and every SSLServer endpoint on the Server. I think it would be a good idea to have a function that let's you specify a host to redirect all requests to with the same path.

**Comment by yhirose** [comment]
@PixlRainbow, I made a new server example [`example/redirect.cc`](https://github.com/yhirose/cpp-httplib/blob/master/example/redirect.cc) to give you an idea with existing functionalities in httplib.h. 

After compiling it and run the server, you can test it with the following curl command.

```bash
$ curl -L -k http://localhost:8080/
Hello World!
```

As you can see in the code, I used `set_error_handler` method to redirect a HTTP request to the HTTPS server. I think what you mentioned above could be implemented in a similar way. In your handler function, you can prepend 'https://[HOSTNAME]' to `req.path` and call `res.set_content` with the url string.

Hope it helps.

**Comment by PixlRainbow** [comment]
Oh, good idea! Thanks!

**Comment by PixlRainbow** [comment]
@yhirose I have recently learned that it is not a good practice to use 301 redirect to make clients go to the https version of the site -- even if it does work and is functional. [More details here](https://security.stackexchange.com/questions/129273/whats-the-difference-between-using-hsts-and-doing-a-301-redirection)
Instead we should be recommending people [use HSTS header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) to "recommend" to a supported client to automatically visit the https version of the site instead. For example, like this:
```cpp
httplib::Headers headers = {
    { "Strict-Transport-Security", "max-age=300" }
};
```

**Comment by AndrewDavis** [comment]
I tried the following (unsure if the `substr()` part is correct):

```c++
httplib::Server httpServer;
httpServer.set_error_handler([](const httplib::Request& request, httplib::Response& response) {
  response.set_header("Strict-Transport-Security", "max-age=63072000");
  response.set_redirect("s://" + request.path.substr(4));
});
httpServer.listen("0.0.0.0", 1234);
```

However, the obvious problem here is that, you can't use the same port..... The whole point of this was to redirect the user in case they type `http://` instead of `https://`...
