### ISSUE TITLE
Unable to download file on Android emulator

### ISSUE THREAD

**Issue by 0x4d696e68** [yhirose/cpp-httplib#1780]
Hello,

I tested it on Android Studio's emulator. Sometimes it works, sometimes not. The success rate is about 20%, and it returns a "Failed to read connection" error.

**Comment by yhirose** [comment]
@0x4d696e68 thanks for the report. But I only test on Windows, MacOS and Ubuntu. You could use it on Android since it's a linux as well, but no guarantee. Thanks for your understanding.

**Comment by PixlRainbow** [comment]
Android has more aggressive memory management and application state model, so you may need to check if Android is suspending the connection or suspending the app before it can finish the download.
