### ISSUE TITLE
"Get" method can not receive body

### ISSUE THREAD

**Issue by LongTengYiFei** [yhirose/cpp-httplib#1784]
svr.Get("/hi", [](const httplib::Request & req, httplib::Response &res) {
  cout<<req.body<<endl;
});

The req.body is an empty string.

**Comment by yhirose** [comment]
@LongTengYiFei it's too little information...

**Comment by LongTengYiFei** [comment]
i mean, when i use Post, the req can receive body. But when i use Get, the req can not receive body, whatever the body of request i set, the req.body is always empty.
