### ISSUE TITLE
listen port random

### ISSUE THREAD

**Issue by jingchuang** [yhirose/cpp-httplib#179]
I specify use this function, listen("0.0.0.0", 9300, SO_REUSEPORT)
But when my program runs, there will be a random listening port. can you help me?
Sometimes it's the result I want, sometimes it's not.

**Comment by yhirose** [comment]
@jingchuang, thanks for the question, but I can't probably give you a right answer because I am not familiar to SO_REUSEPORT.  Could you explain more clearly what you are trying to do with it?

**Comment by jingchuang** [comment]
> @jingchuang，谢谢你的问题，但我不能给你一个正确的答案，因为我对SO_REUSEPORT并不熟悉。你能更清楚地解释一下你想用它做什么吗？

I want my program listening port to be 9300, so I use the listen("0.0.0.0", 9300) function, but after running the program is a random port, I thought it was the reason for port reuse, so use the SO_REUSEPORT option. Actually add This parameter does not solve the problem.

I used the "netstat -tlnp | grep adasrvd" command and found that my program is not listening to port 9300, but any port.
first time:      tcp        0      0 0.0.0.0:32765           0.0.0.0:*               LISTEN      18999/./adasrvd
second time: tcp        0      0 0.0.0.0:32766           0.0.0.0:*               LISTEN      18958/./adasrvd
third time:     tcp        0      0 0.0.0.0:9300            0.0.0.0:*               LISTEN      18968/./adasrvd
fourth time:  tcp        0      0 0.0.0.0:32767           0.0.0.0:*               LISTEN      17693/./adasrvd

The third time is the result I want,  I don't understand why this happens because I have specified to listen on port 9300.
my env: centos7.6, gcc7.3

**Comment by yhirose** [comment]
Thanks for the detailed information. I fixed it. You don't need to pass `SO_REUSEPORT` to `listen` method. (The 3rd parameter is not for socket option, but for socket flags.)

Could you try with the latest code to see if it fixes the problem on your machine? Thanks!
