### ISSUE TITLE
client can't open the encrypted private key

### ISSUE THREAD

**Issue by pbwang002** [yhirose/cpp-httplib#1793]
There is no constructor whose input parameter is ctx or password, which is used to open the encrypted private key.

**Comment by yhirose** [comment]
Thank you for the feedback, but I am not planning to make such a constructor accepting a SSL context object from outside.

**Comment by pbwang002** [comment]
Client:When the client has an encrypted private key, the private key cannot be decrypted
![image](https://github.com/yhirose/cpp-httplib/assets/12571367/673b1b63-a8a1-4a7c-a2ca-aa50041f179a)

**Comment by pbwang002** [comment]
> Thank you for the feedback, but I am not planning to make such a constructor accepting a SSL context object from outside.
Client:When the client has an encrypted private key, the private key cannot be decrypted
image

**Comment by yhirose** [comment]
@pbwang002 I see what you mean. :)

**Comment by yhirose** [comment]
Implemented.
