### ISSUE TITLE
`GetRangeWithMaxLongLength` failing on 32-bit

### ISSUE THREAD

**Issue by Tachi107** [yhirose/cpp-httplib#1795]
Hi, it seems that commit fceada9ef42ce1af64a1d5941d8009dd0520901a broke the `GetRangeWithMaxLongLength` test on 32-bit machines - I've tested in a Linux i686 chroot.

    Running main() from ./googletest/src/gtest_main.cc
    Note: Google Test filter = ServerTest.GetRangeWithMaxLongLength
    [==========] Running 1 test from 1 test suite.
    [----------] Global test environment set-up.
    [----------] 1 test from ServerTest
    [ RUN      ] ServerTest.GetRangeWithMaxLongLength
    ../test/test.cc:2982: Failure
    Expected equality of these values:
      StatusCode::RangeNotSatisfiable_416
        Which is: 416
      res->status
        Which is: 206
    
    ../test/test.cc:2983: Failure
    Expected equality of these values:
      "0"
      res->get_header_value("Content-Length")
        Which is: "7"
    
    ../test/test.cc:2984: Failure
    Expected equality of these values:
      false
      res->has_header("Content-Range")
        Which is: true
    
    ../test/test.cc:2985: Failure
    Expected equality of these values:
      0
      res->body.size()
        Which is: 7
    
    [  FAILED  ] ServerTest.GetRangeWithMaxLongLength (18 ms)
    [----------] 1 test from ServerTest (18 ms total)
    
    [----------] Global test environment tear-down
    [==========] 1 test from 1 test suite ran. (18 ms total)
    [  PASSED  ] 0 tests.
    [  FAILED  ] 1 test, listed below:
    [  FAILED  ] ServerTest.GetRangeWithMaxLongLength
    
     1 FAILED TEST

As shown above, the test response returns a status code of `206` an a `Content-Lenght` of `7`, just like it did before the commit. It's almost like the change was ineffective on 32-bit machines.

I'm pretty sure there's an overflow somewhere in the new code which is only triggered on machines with smaller integer types, but I can't tell where it is.

What do you think is the cause of the problem?

Thanks!

**Comment by q2a3z** [comment]
Hi @Tachi107 
I thinked this is why.
Maybe your 32bit-machines was not returned the Error  416 (Range Not Satisfiable) in here.
```c++:httplib.h
inline bool range_error(Request &req, Response &res) {
  if (!req.ranges.empty() && 200 <= res.status && res.status < 300) {
    ssize_t contant_len = static_cast<ssize_t>(
        res.content_length_ ? res.content_length_ : res.body.size());

    ssize_t prev_first_pos = -1;
    ssize_t prev_last_pos = -1;
    size_t overwrapping_count = 0;

    // NOTE: The following Range check is based on '14.2. Range' in RFC 9110
    // 'HTTP Semantics' to avoid potential denial-of-service attacks.
    // https://www.rfc-editor.org/rfc/rfc9110#section-14.2

    // Too many ranges
    if (req.ranges.size() > CPPHTTPLIB_RANGE_MAX_COUNT) { return true; }

    for (auto &r : req.ranges) {
      auto &first_pos = r.first;
      auto &last_pos = r.second;
```
As above  `auto &first_pos = r.first;` would get 0,
and `auto &last_pos = r.second;` would get  the test condition 9223372036854775807.

but the Range was used **ssize_t** to pair the size.
```c++:httplib.h
using Range = std::pair<ssize_t, ssize_t>;
using Ranges = std::vector<Range>;

struct Request {
  ...
  Ranges ranges;
```
I thinked your 32bit-machines was sized as unsigned int maximize 4294967295, was oversize the test condition 9223372036854775807.
If you want the test be ok, I thinked shrink the end size for your 32bit-machines will be done.
Usually, unsigned int(4bit) was be enough for our work.

**Comment by Tachi107** [comment]
Hi @q2a3z, thanks for your suggestions! I've submitted #1867 which fixes this issue.

**Comment by yhirose** [comment]
@q2a3z @Tachi107 thanks for your contribution!
