### ISSUE TITLE
Provides a way to ignore host verify

### ISSUE THREAD

**Issue by pbwang002** [yhirose/cpp-httplib#1796]
![image](https://github.com/yhirose/cpp-httplib/assets/12571367/087f2a18-4e53-4274-b4fc-7b140aa922c4)
When setting the client authentication mode to SSL_VERIFY_NONE, the host verification is not ignored.
Provides a way to ignore host verify.

**Comment by PixlRainbow** [comment]
Use `enable_server_certificate_verification(false)` method on `SSLClient`

**Comment by pbwang002** [comment]
> Use `enable_server_certificate_verification(false)` method on `SSLClient`
1. Java spring boot and python http client generally support two options, enabling ssl authentication and whether to ignore host_name authentication, which is more flexible.
2. cpp-httplib now has SSL authentication enabled and must verify the hostname, which is too inflexible.

**Comment by pbwang002** [comment]
@yhirose @PixlRainbow

**Comment by PixlRainbow** [comment]
Ah, so you want to still run `SSL_get_verify_result` https://github.com/yhirose/cpp-httplib/blob/548dfff0aef25e36e971af96b49ce7fbb72d840e/httplib.h#L8759-L8760
But have an option to skip just `verify_host`
https://github.com/yhirose/cpp-httplib/blob/548dfff0aef25e36e971af96b49ce7fbb72d840e/httplib.h#L8774-L8778

**Comment by pbwang002** [comment]
> Ah, so you want to still run `SSL_get_verify_result`
> 
> https://github.com/yhirose/cpp-httplib/blob/548dfff0aef25e36e971af96b49ce7fbb72d840e/httplib.h#L8759-L8760
> 
> 
> But have an option to skip just `verify_host`
> https://github.com/yhirose/cpp-httplib/blob/548dfff0aef25e36e971af96b49ce7fbb72d840e/httplib.h#L8774-L8778
> 
> 
> The curl equivalent being `CURLOPT_SSL_VERIFYHOST = 0`

Yes, httplib does not provide this capability now

**Comment by yhirose** [comment]
Thanks for the clear explanation.
