### ISSUE TITLE
std::async run  httplib::client error 

### ISSUE THREAD

**Issue by car520120** [yhirose/cpp-httplib#1797]
![image](https://github.com/yhirose/cpp-httplib/assets/36702004/f7896c87-76b9-448f-8ab6-a682391a542a)
![image](https://github.com/yhirose/cpp-httplib/assets/36702004/28420e93-b577-4147-8db1-031499aa7f15)

**Comment by yhirose** [comment]
@car520120 thanks for the feedback. Could you please give me the following information?

1. What error did you get?
2. Do you get the same error when you use std::thread instead of std::async?
