### ISSUE TITLE
Please append port number to HOST header 

### ISSUE THREAD

**Issue by toge** [yhirose/cpp-httplib#18]
In RFC 7230(HTTP1.1),
> if the connection's incoming TCP port number
> differs from the default port for the effective request URI's
> scheme, then a colon (":") and the incoming port number (in
> decimal form) are appended to the authority component.

While I know your library supports HTTP/1.0,
I'm glad to append port number to HOST header like following:

```
#-    req.set_header("Host", host_.c_str());
+    req.set_header("Host", (host_ + ":" + std::to_string(port_)).c_str());

```

**Comment by yhirose** [comment]
@toge, thanks for the good suggestion. I have implemented it at https://github.com/yhirose/cpp-httplib/commit/bd089e9499e06f63565f6c8663373f3a6d6cfe79.
