### ISSUE TITLE
IPV6_V6ONLY is a little weird on freebsd 

### ISSUE THREAD

**Issue by laduke** [yhirose/cpp-httplib#1802]
Sorry for making this issue. I'm not a FreeBSD user but I do support some. 

When IPV6_V6ONLY is turned off, requests to v4 addresses appear to come from `::ffff:<v4-address>` like `::ffff:127.0.0.1`

https://github.com/yhirose/cpp-httplib/commit/b2203bb05aa241a3dd00719c8afd07d82900ba3d

other info 
https://forums.freebsd.org/threads/creating-a-ipv4-ipv6-socket-in-c.92530/
"IIRC you get V6-notation for all address strings"

I'm not sure what the solution is. Make it configurable by the caller? ifdef for freebsd? 
Just patch my local copy of httplib.h? 

Thanks for this library. Just wanted to make a note of this, not necessarily get something changed.

**Comment by yhirose** [comment]
@laduke sorry for the late reply. Could you explain more about this issue? Where do you see `::ffff:<v4-address>` in cpp-httplib?

**Comment by laduke** [comment]
I forget. I think we were checking the source of a requests `req.remote_addr`, to make sure it's coming from loopback. 
But on bsd we were getting ::ffff:127.0.0.1 instead of the expected 127.0.0.1, ::1, etc., even though we make the request to 127.0.0.1 (curl -4 http://127.0.0.1/)
Those links are semi-related? But it's more about the Request's remote_addr. 

I guess we eventually figured it out https://github.com/zerotier/ZeroTierOne/issues/2151#issuecomment-1998533021

**Comment by yhirose** [comment]
OK. if the server machine picks the IPv6 addrinfo item in the addrinfo list from getaddrinfo system call when making a socket, cpp-httplib will also make it work with IPv4 by setting IPV6_V6ONLY option to 0 as you already know. 

So even if you call `curl -4 ...` and the server socket is IPv6, it accepts the IPv4 connection, and the `req.remote_addr` (which comes from `getpeername` systen call) will be 'IPv4-mapped IPv6'. That's what we expect.

Here is my test on MacOS.

```cpp
#include <httplib.h>
using namespace httplib;

int main(void) {
  Server svr;
  svr.set_address_family(AF_INET6);

  svr.Get("/hi", [](const Request & req, Response &res) {
    res.set_content(req.remote_addr, "text/plain");
  });

  svr.listen("0.0.0.0", 8080);
}
```

```bash
> curl -4 http://localhost:8080/hi
::ffff:127.0.0.1
```

Hope it helps!

**Comment by laduke** [comment]
I guess the confusing part was on linux you get back `127.0.0.1`

on mac even if you use
`svr.set_address_family(AF_INET);` 

you get `::ffff:127.0.0.1`

I'll leave you alone now
