### ISSUE TITLE
about the `:` in path param 

### ISSUE THREAD

**Issue by BiuXWT** [yhirose/cpp-httplib#1805]
A url like this 
```
/usr/:name/number/:id/do:work
```
the `:work` is not a param , the whole `do:work` string is a phrase ,
but now , the framework will consider `work` as a param,could you please fix it

**Comment by yhirose** [comment]
@BiuXWT thanks for the report!

**Comment by yhirose** [comment]
@bgs99 do you have any thoughts on this issue?

**Comment by bgs99** [comment]
> @bgs99 do you have any thoughts on this issue?

I guess we could limit path parameters capture to whole path segments, so `/:param` would be a capture, but `/not:param` would be a literal segment with `:` in the middle.

It might break code for the users that are already depend on capturing segment parts. But on the other hand, it seems that path parameter capture on segment parts is neither fully supported nor documented: it uses `/:` to select between named params capture and regex capture and only full segment capture is shown as examples in the docs.

Alternatively, if we want maximum flexibility, it should be possible to provide some kind of escaping mechanism, like writing `/not\:param` to mean `/not:param` literal.

**Comment by yhirose** [comment]
@bgs99 I like "limit path parameters capture to whole path segments". Could you take care of it and make a pull request, since I don't know much about the `PathParamsMatcher` code. Thanks!
