### ISSUE TITLE
Arguments of type form-data could not be resolved

### ISSUE THREAD

**Issue by ChengduDreamer** [yhirose/cpp-httplib#1807]
![image](https://github.com/yhirose/cpp-httplib/assets/53937587/f4e2f058-29a8-4da4-b715-dda70eff0332)

If a client-side request is made using the form-data format and no files are transmitted, only a few ordinary parameters, but the server-side is unable to parse them, you can obtain the parameter names solely through httplib::MultipartFormData within the content_reader object.

**Comment by yhirose** [comment]
Yes, you are right and I understand it's not convenient... But there is no way to confirm that there is no file item in the content body unless parsing it. So for efficiency in mind, I'll stick to this interface.
