### ISSUE TITLE
Support MinGW

### ISSUE THREAD

**Issue by Sean537** [yhirose/cpp-httplib#1824]
Why not cpp-httplib support MinGW？I think it's necessary. Because MinGW is also the world's mainstream C++ compiler. I also use it to develop some programs. Hopefully, MinGW can be supported in the future, thanks.

**Comment by yhirose** [comment]
Thank for the suggestion. But, it's just my personal project, and I don't have enough time to support all the possible environments that users request. Thanks for your consideration!
