### ISSUE TITLE
Windows platform only? Other platforms, MAC, Linux

### ISSUE THREAD

**Issue by jiagushuai** [yhirose/cpp-httplib#183]
I don't see any other platforms mentioned here. Do you support cross-platform HTTP and HTTPS

**Comment by PixlRainbow** [comment]
This is a cross-platform library. To use it, you simply move the file `httplib.h` to a location you can access and `#include` it in your C++ code

**Comment by jiagushuai** [comment]
thanks ! I'll test that later
