### ISSUE TITLE
Getting a list of missing identifiers

### ISSUE THREAD

**Issue by chandrianAW** [yhirose/cpp-httplib#1832]
![image](https://github.com/yhirose/cpp-httplib/assets/111806711/549fbae5-5c7b-40a5-851f-0891e299d71a)

I have read that it could be an issue of an old version of OpenSSL but I am referencing v3

**Comment by yhirose** [comment]
I guess OpenSSL is not properly installed on your machine. Please check with `cd test; make`. Hope it helps.

**Comment by chandrianAW** [comment]
I tried reinstalling many times. I eventually switched to Eclipse and I am not getting the long list of errors but I am getting this:

"..\src\httplib.h:2819:14: error: '::CreateFile2' has not been declared"

Any clue there?

**Comment by tilongzs** [comment]
> I tried reinstalling many times. I eventually switched to Eclipse and I am not getting the long list of errors but I am getting this:
> 
> "..\src\httplib.h:2819:14: error: '::CreateFile2' has not been declared"
> 
> Any clue there?

This is the default definition issue for `_WIN32_WINNT`, which can be resolved by adding a line
```
#define _WIN32_WINNT 0x0602
#include <Windows.h>
```
