### ISSUE TITLE
 When acting as a server, receiving a POST request with an empty body that takes a long time to respond.

### ISSUE THREAD

**Issue by BromideY** [yhirose/cpp-httplib#1833]
Server code：

    httplib::Server svr;

    svr.Post("/hi", [](const httplib::Request &, httplib::Response &res) {
        res.set_content("Hello World!", "text/plain");
    });

    svr.listen("0.0.0.0", 10001);

Then use curl to request：

   curl -X POST localhost:10001/hi

Usually it will take 2s or 3s to respond ...

**Comment by yhirose** [comment]
Thanks for the feedback, but it's too little information. It seems like your network environment causes the problem.

**Comment by DreamGenX** [comment]
I can reproduce this issue. It does not happen for GET requests.

```
# slow
curl -X POST http://127.0.0.1:8080/foo

# fast
curl -X POST http://127.0.0.1:8080/foo -d {}
```

Setting the body explicitly empty makes it work as expected.
