### ISSUE TITLE
HttpServer Keep-Alive

### ISSUE THREAD

**Issue by ENMOJY** [yhirose/cpp-httplib#1835]
When I try to use http long connection, I set the timeout and maximum number to 10, the response received by my browser is still "Connection:close"

After I set the breakpoint, I found that "req.get_header_value("Connection") == "close"" is FALSE, but the return value of "req.get_header_value("Connection")" is " ". Why does "==" behave like this?

![image](https://github.com/yhirose/cpp-httplib/assets/67402352/f324be9a-034b-43ad-b797-0dcf76445c8c)

**Comment by yhirose** [comment]
I don't know your situation fully though, `close_connection` could be `true`.

**Comment by ENMOJY** [comment]
Thanks,but close_connection is `true`,and std::string's `=='` return `true`
