### ISSUE TITLE
MinGW make error, Windows platform.

### ISSUE THREAD

**Issue by Wq-dd** [yhirose/cpp-httplib#1842]
I included httplib.h in my cpp file. And after cmake -G "MinGW Makefiles", I use make to compile my app. I get ther following error.
```
httplib.h:2819:14: error: '::CreateFile2' has not been declared; did you mean 'CreateFileW'?
2819 |   hFile_ = ::CreateFile2(wpath.c_str(), GENERIC_READ, FILE_SHARE_READ,
```
Does this project cannot be compiled using mingw? Please help.

**Comment by yhirose** [comment]
Please see #1824.

**Comment by maben-mw** [comment]
Note that MinGW _does_ support `CreateFile2`, but it requires `_WIN32_WINNT` to be set to a high enough value (i.e. recent enough Windows version). Ideally cmake would ensure it gets set correctly, alternatively you might just be able to manually add `-D_WIN32_WINNT=0x0A00` (Windows 10) to your compiler switches or use a `#define` in your code.
