### ISSUE TITLE
ContentReceiver chunk size cannot greater than 4096

### ISSUE THREAD

**Issue by Huweicai** [yhirose/cpp-httplib#1845]
I am using cpp-httplib to watch server side events, instead of downloading some big files.

The interface looks like below while using `curl` 
<img width="1261" alt="pic" src="https://github.com/yhirose/cpp-httplib/assets/29170746/e4c15853-b898-4ba2-8b07-f146e527b12a">

My code looks like below:
```c++
auto res = cli.Get("/events,watch=true", [&](const char *data, size_t data_length) -> bool {
        auto event = json_parse(data, data_length);
        handle_event(event);
        return true;
    });
```

Each chunk stands for an event, but sometimes the event may be bigger than 4096, then it will be cut down, and json parse will fail.

I've seen the issue https://github.com/yhirose/cpp-httplib/issues/1191,  avoid to regard the data as a whole piece, but it's hard for me to distinguish the boundary of each event  to put it together.

Do you have any good idea on it?
- add another flag to indicate the chunk finished
- increase the read buffer size

**Comment by yhirose** [comment]
@Huweicai sorry for the late reply. Here are my suggestions. Hope it helps.

```c++
// Non-stream-based JSON parser
std::string body;
auto res = cli.Get("/events,watch=true",
                   [&](const char *data, size_t data_length) -> bool {
                     body.append(data, data_length);
                     return true;
                   });
auto event = json_parse(body.data(), body.size());
handle_event(event);

// Stream-based JSON parser
stream_json_parser json_parser;
auto res = cli.Get("/events,watch=true",
                   [&](const char *data, size_t data_length) -> bool {
                     json_parser.feed(data, data_length);
                     return true;
                   });
auto event = json_parser.end();
handle_event(event);
```
