### ISSUE TITLE
I use this header for iOS, https runs well in iOS simulator but not in real iphone

### ISSUE THREAD

**Issue by RightFS** [yhirose/cpp-httplib#1847]
Any iOS expert here can tell me why it works in iOS simulator, not as expected (it shouldn't run, because of the root certs not loaded)

**Comment by yhirose** [comment]
@RightFS thanks for feedback. I don't support iOS though, you may be able to do something similar to `load_system_certs_on_macos` to load the system root certs. Hope it helps!
