### ISSUE TITLE
Windows7 createFile2 error

### ISSUE THREAD

**Issue by Wq-dd** [yhirose/cpp-httplib#1850]
After I build an exe file,  I copy the exe file to a win7 computer, I get an error  "cannot locate createFile2 to dll lib KERNEL32.dll", when  
 excuting my exe file.
Does this project supported on win7?

**Comment by yhirose** [comment]
This library works only on Windows 8 or later which supports createFile2.
https://github.com/yhirose/cpp-httplib?tab=readme-ov-file#windows
