### ISSUE TITLE
Callback to the main thread to perform the specified action

### ISSUE THREAD

**Issue by jiagushuai** [yhirose/cpp-httplib#186]
+ Qt is used in the project. UI can only be operated on the main thread.

![image](https://user-images.githubusercontent.com/29997741/60939115-20b0c680-a309-11e9-81cf-7a1fc0f7fe4d.png)

**Comment by PixlRainbow** [comment]
This is not a question related to httplib, what you are asking for is just general thread management. You can just have a boolean global variable, set it to true from the request handler and call `listen` on a new thread. Then in the main thread, have a while loop on the boolean variable, containing just `std::this_thread::yield` after you start the server thread. If you want to have better CPU efficiency, you can look into condition variables which allow you to `wait` and `notify`

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the clear answer to the question!

**Comment by jiagushuai** [comment]
> This is not a question related to httplib, what you are asking for is just general thread management. You can just have a boolean global variable, set it to true from the request handler and call `listen` on a new thread. Then in the main thread, have a while loop on the boolean variable, containing just `std::this_thread::yield` after you start the server thread. If you want to have better CPU efficiency, you can look into `std::condition_variable` which allow you to `wait` and `notify`
+ Thank you for your answer, this is exactly my question! I 
+ don't know how to implement it, so would you please help me。If I understand you correctly, is this the picture below
![image](https://user-images.githubusercontent.com/29997741/61016702-2e2a8700-a3c3-11e9-9b31-ed5f7717149f.png)

**Comment by PixlRainbow** [comment]
```cpp
std::thread t(svr.listen, "localhost", 1234);
while(!flag) {
    //std::this_thread::yield(); //optional
}
printf("can I do this in main thread after hi has been executed");

t.join();
```

**Comment by jiagushuai** [comment]
I'm sorry to restate my problem
```
#include <httplib.h>

void GetStr(char * pin,int argc, char *argv[])
{
    printf("here\tMac execution crashes but window works");
}

int main(int argc, char *argv[])
{
    using namespace httplib;

    Server svr;

    svr.Get("/hi", [argc,argv](const Request& req, Response& res) {
        std::string paramData = req.get_param_value("pin", 0);
        const char * pin = paramData.c_str();
        if(paramData.length() <= 0)
            GetStr((char *)pin, argc, argv);
        printf("The set_content function is also executed if GetStr performs res normally\n");
        res.set_content("Hello World!", "text/plain");
    });

    svr.listen("localhost", 1234);
}
```
+ When executing the getStr function,GetStr is followed by res.set_content
```
2019-07-11 15:19:03.652 SD_http[34802:737891] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1349.91/Misc.subproj/NSUndoManager.m:363
2019-07-11 15:19:03.653 SD_http[34802:737891] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9b1aa2cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffaffe848d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9b1af042 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff9cbf7be0 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   Foundation                          0x00007fff9cb82093 +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 170
	5   AppKit                              0x00007fff98c0c4ed -[NSApplication run] + 1200
	6   libsdUi.dylib                       0x00000001050129ff GetStr + 116927
	7   libsdUi.dylib                       0x00000001058f2fee GetStr + 9424558
	8   libsdUi.dylib                       0x00000001058f777f GetStr + 9442879
	9   libsdUi.dylib                       0x0000000104ff6194 GetStr + 84
	10  SD_http                             0x0000000104f58703 SD_http + 120579
	11  SD_http                             0x0000000104f4eb94 SD_http + 80788
	12  SD_http                             0x0000000104f4a859 SD_http + 63577
	13  SD_http                             0x0000000104f49bb6 SD_http + 60342
	14  SD_http                             0x0000000104f498e2 SD_http + 59618
	15  libsystem_pthread.dylib             0x00007fffb0b3b93b _pthread_body + 180
	16  libsystem_pthread.dylib             0x00007fffb0b3b887 _pthread_body + 0
	17  libsystem_pthread.dylib             0x00007fffb0b3b08d thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
error: execv(/Users/shandikeji/Desktop/sd-cpp/sdSocketKey_win_http/build/macosx/x86_64/release/SD_http) failed(-1)!
```

**Comment by jiagushuai** [comment]
The getStr function is inside hi
This is an error for HTTP access to hi
+ Is there a better way to think about it

**Comment by PixlRainbow** [comment]
Request handlers are not run when you declare them. When there is a new incoming request, a new thread is spawned to handle the request and your handler is then run in that thread. Cocoa (Qt dependency on Mac OSX) does not allow GUI functions to be run from that thread. The best you can do is to find some way to make the main thread wait/check for new info or events from the handlers, and run a function when there is something to do on the GUI
