### ISSUE TITLE
"collect2.exe: error: ld returned 1 exit status" whenever I try to compile

### ISSUE THREAD

**Issue by BarneyAtAldi2** [yhirose/cpp-httplib#1860]
I run "g++ main.o -o main" and it says

C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib22default_socket_optionsEy[_ZN7httplib22default_socket_optionsEy]+0x37): undefined reference to `__imp_setsockopt'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib22default_socket_optionsEy[_ZN7httplib22default_socket_optionsEy]+0x61): undefined reference to `__imp_setsockopt'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail12close_socketEy[_ZN7httplib6detail12close_socketEy]+0x16): undefined reference to `__imp_closesocket'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZZN7httplib6detail11read_socketEyPvyiENKUlvE_clEv[_ZZN7httplib6detail11read_socketEyPvyiENKUlvE_clEv]+0x42): undefined reference to `__imp_recv'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZZN7httplib6detail11send_socketEyPKvyiENKUlvE_clEv[_ZZN7httplib6detail11send_socketEyPKvyiENKUlvE_clEv]+0x42): undefined reference to `__imp_send'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZZN7httplib6detail11select_readEyxxENKUlvE_clEv[_ZZN7httplib6detail11select_readEyxxENKUlvE_clEv]+0x40): undefined reference to `__imp_select'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZZN7httplib6detail12select_writeEyxxENKUlvE_clEv[_ZZN7httplib6detail12select_writeEyxxENKUlvE_clEv]+0x45): undefined reference to `__imp_select'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZZN7httplib6detail26wait_until_socket_is_readyEyxxENKUlvE_clEv[_ZZN7httplib6detail26wait_until_socket_is_readyEyxxENKUlvE_clEv]+0x44): undefined reference to `__imp_select'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail26wait_until_socket_is_readyEyxx[_ZN7httplib6detail26wait_until_socket_is_readyEyxx]+0x1ac): undefined reference to `__WSAFDIsSet'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail26wait_until_socket_is_readyEyxx[_ZN7httplib6detail26wait_until_socket_is_readyEyxx]+0x1c6): undefined reference to `__WSAFDIsSet'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail26wait_until_socket_is_readyEyxx[_ZN7httplib6detail26wait_until_socket_is_readyEyxx]+0x214): undefined reference to `__imp_getsockopt'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail15shutdown_socketEy[_ZN7httplib6detail15shutdown_socketEy]+0x1b): undefined reference to `__imp_shutdown'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail15set_nonblockingEyb[_ZN7httplib6detail15set_nonblockingEyb]+0x3c): undefined reference to `__imp_ioctlsocket'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail19is_connection_errorEv[_ZN7httplib6detail19is_connection_errorEv]+0xb): undefined reference to `__imp_WSAGetLastError'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZZN7httplib6detail20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_iibSt8functionIFvyEExxxxxxS8_RNS_5ErrorEENKUlyR8addrinfoE_clEySF_[_ZZN7httplib6detail20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_iibSt8functionIFvyEExxxxxxS8_RNS_5ErrorEENKUlyR8addrinfoE_clEySF_]+0x56): undefined reference to `__imp_connect'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZZN7httplib6detail20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_iibSt8functionIFvyEExxxxxxS8_RNS_5ErrorEENKUlyR8addrinfoE_clEySF_[_ZZN7httplib6detail20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_iibSt8functionIFvyEExxxxxxS8_RNS_5ErrorEENKUlyR8addrinfoE_clEySF_]+0x145): undefined reference to `__imp_setsockopt'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZZN7httplib6detail20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_iibSt8functionIFvyEExxxxxxS8_RNS_5ErrorEENKUlyR8addrinfoE_clEySF_[_ZZN7httplib6detail20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_iibSt8functionIFvyEExxxxxxS8_RNS_5ErrorEENKUlyR8addrinfoE_clEySF_]+0x1b2): undefined reference to `__imp_setsockopt'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail15get_ip_and_portERK16sockaddr_storageiRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi[_ZN7httplib6detail15get_ip_and_portERK16sockaddr_storageiRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi]+0x4f): undefined reference to `__imp_ntohs'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail15get_ip_and_portERK16sockaddr_storageiRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi[_ZN7httplib6detail15get_ip_and_portERK16sockaddr_storageiRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi]+0x86): undefined reference to `__imp_ntohs'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail15get_ip_and_portERK16sockaddr_storageiRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi[_ZN7httplib6detail15get_ip_and_portERK16sockaddr_storageiRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi]+0xff): undefined reference to `__imp_getnameinfo'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail21get_local_ip_and_portEyRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi[_ZN7httplib6detail21get_local_ip_and_portEyRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi]+0x39): undefined reference to `__imp_getsockname'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail22get_remote_ip_and_portEyRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi[_ZN7httplib6detail22get_remote_ip_and_portEyRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi]+0x39): undefined reference to `__imp_getpeername'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail6WSInitC1Ev[_ZN7httplib6detail6WSInitC1Ev]+0x30): undefined reference to `__imp_WSAStartup'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail6WSInitD1Ev[_ZN7httplib6detail6WSInitD1Ev]+0x1a): undefined reference to `__imp_WSACleanup'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZZNK7httplib6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEENKUlyR8addrinfoE_clEySD_[_ZZNK7httplib6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEENKUlyR8addrinfoE_clEySD_]+0x33): undefined reference to `__imp_bind'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZZNK7httplib6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEENKUlyR8addrinfoE_clEySD_[_ZZNK7httplib6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEENKUlyR8addrinfoE_clEySD_]+0x58): undefined reference to `__imp_listen'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6Server13bind_internalERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEii[_ZN7httplib6Server13bind_internalERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEii]+0xfd): undefined reference to `__imp_getsockname'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6Server13bind_internalERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEii[_ZN7httplib6Server13bind_internalERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEii]+0x134): undefined reference to `__imp_ntohs'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6Server13bind_internalERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEii[_ZN7httplib6Server13bind_internalERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEii]+0x15f): undefined reference to `__imp_ntohs'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6Server15listen_internalEv[_ZN7httplib6Server15listen_internalEv]+0x119): undefined reference to `__imp_accept'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6Server15listen_internalEv[_ZN7httplib6Server15listen_internalEv]+0x24d): undefined reference to `__imp_setsockopt'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6Server15listen_internalEv[_ZN7httplib6Server15listen_internalEv]+0x2ba): undefined reference to `__imp_setsockopt'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0xef): undefined reference to `__imp_getaddrinfo'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x14a): undefined reference to `__imp_WSASocketW'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x178): undefined reference to `__imp_socket'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x1c7): undefined reference to `__imp_setsockopt'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x22a): undefined reference to `__imp_setsockopt'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x255): undefined reference to `__imp_freeaddrinfo'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x291): undefined reference to `__imp_freeaddrinfo'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0xef): undefined reference to `__imp_getaddrinfo'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x14a): undefined reference to `__imp_WSASocketW'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x178): undefined reference to `__imp_socket'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x1c7): undefined reference to `__imp_setsockopt'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x22a): undefined reference to `__imp_setsockopt'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x258): undefined reference to `__imp_freeaddrinfo'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: main.o:main.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x294): undefined reference to `__imp_freeaddrinfo'
collect2.exe: error: ld returned 1 exit status
PS C:\Users\rc682\Documents\Code\C++\HTTPTest>

**Comment by yhirose** [comment]
Sorry, but this library doesn't support mingw32...
