### ISSUE TITLE
select returns 0, error code 115

### ISSUE THREAD

**Issue by pytho12** [yhirose/cpp-httplib#1863]
Hello, your work is excellent, but when I use it, when the client makes multiple concurrent requests to the server, the server sends data to the client, but when the server uses select(), it returns 0, and the error code printed out is 115, and sometimes the error code is 0.
The following is the data packet captured when the error code occurs：
<img width="1832" alt="截屏2024-06-17 20 06 46" src="https://github.com/yhirose/cpp-httplib/assets/82310073/c3f31009-a29b-449b-bf16-7c9fabeaf75d">
From the picture, it seems that the server actively closed the connection, but I don't understand why? I don't know what the reason is, I would like to ask you for help.

**Comment by yhirose** [comment]
Sorry, I don't know why either...
