### ISSUE TITLE
Sporadically http clients show the error that the server connection has been reset

### ISSUE THREAD

**Issue by RainerSchielke** [yhirose/cpp-httplib#1870]
Sporadically our java client logs the message "HttpURLConnection.getInputStream  java.io.IOException: Error writing to server" which ocurred  because the receiving server closed the connection.

Our Windows-http client shows the windows error code 12030, which means "The connection with the server has been reset or terminated"
 
I increased the receive buffer size to 256k and the number of threads to 64. This reduced the occurence to about once in 1000 requests.

Then I added a retry in my clients, which helped. But I am not happy with that.

Btw. we do not use "keep alive", at server initialization we call set_keep_alive_timeout (0). Without that, every requests delays for 5 seconds. 

Why resets the httplib server the connection sporadically ?

**Comment by lukasberbuer** [comment]
I face the same problem getting sporadic `ERR_CONNECTION_RESET` from the JavaScript client with following setup:

```cpp
// single threaded server
#define CPPHTTPLIB_THREAD_POOL_COUNT 1
#include <httplib.h>

httplib::Server server;
server.set_keep_alive_timeout(0);

// setup endpoints...

server.listen("0.0.0.0", 8080);
```

Any ideas?

**Comment by RainerSchielke** [comment]
Looks like a keep-alive problem. I came up with it when I read the issue #1825 which was fixed with disabling keep-alive on the client side. Probably the function **process_server_socket_core** causes this:

![Screenshot 2024-07-17 175043](https://github.com/user-attachments/assets/f081f210-704b-4c7c-8ea4-aae3e1b62c68)
I assume that if the number of keep alive connections is exhausted, a connection is closed and that causes the client error.
The solution is quite simple: call **set_keep_alive_max_count ()** to increase the keep_alive_max_count to more than 5 e.g. 100 and the problem disappears. Other servers like tomcat or jetty allow 100 to 256 keep alive connections.
My very well working setup ist now:

 **set_keep_alive_timeout (5);   // default
 set_keep_alive_max_count (300);**

@yhirose I suggest to increase the default value for keep_alive_max_count_ or at least mention that in the documentation.

**Comment by lukasberbuer** [comment]
Thank you for the deep dive @RainerSchielke.

Following settings seem to work for me:

```cpp
#define CPPHTTPLIB_THREAD_POOL_COUNT 2
#define CPPHTTPLIB_KEEPALIVE_TIMEOUT_SECOND 5
#define CPPHTTPLIB_KEEPALIVE_MAX_COUNT 300
```

Whenever I switch to a single-threaded server (`#define CPPHTTPLIB_THREAD_POOL_COUNT 1`), it seems to work but I face another issues of hanging requests (#454).

**Comment by yhirose** [comment]
@RainerSchielke thanks for the report. The documentation already mentions it as below, and I feel it's enough for those who know the HTTP/1.1 Keep-Alive connection spec.

<img width="437" alt="image" src="https://github.com/user-attachments/assets/178e4355-f047-4386-8489-97c1a2b689a3">

https://github.com/yhirose/cpp-httplib?tab=readme-ov-file#keep-alive-connection

But of course, any pull request which updates README is welcome!
