### ISSUE TITLE
Missing `Head` method for server

### ISSUE THREAD

**Issue by hardingadonis** [yhirose/cpp-httplib#1876]
I want to write a server that can handle Head HTTP Method, but I don't see any function to to this.

Also `httplib::Server` and `httplib::SSLServer` are missing Head HTTP Method.

**Comment by yhirose** [comment]
cpp-httplib server handles HEAD requests with Get handlers returning no content.

https://github.com/yhirose/cpp-httplib/blob/52a18c78a52b1bcffc10506fe5fdc76568b3c646/test/test.cc#L2295
https://github.com/yhirose/cpp-httplib/blob/52a18c78a52b1bcffc10506fe5fdc76568b3c646/test/test.cc#L2935
