### ISSUE TITLE
Performance Problem with "Connection: close" and "set_keep_alive_max_count"

### ISSUE THREAD

**Issue by octocat9lee** [yhirose/cpp-httplib#1880]
#### version
`#define CPPHTTPLIB_VERSION "0.16.0"`
#### Operation System
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
```

### Example Code
```
#include "httplib.h"

void HttplibTest01() {
    std::cout << "start ut signal server" << std::endl;
    httplib::Server svr;
    svr.Post("/index/hook/on_play", [](const httplib::Request &req, httplib::Response &res) {
        std::cout << "receive on_play: " << req.body << std::endl;
        std::string response = R"({"code":0,"msg":"success"})";
        res.set_content(response, "application/json; charset=utf-8");
    });

    // svr.set_keep_alive_max_count(1); // key statement
    svr.listen("0.0.0.0", 30080);
}

int main(int argc, char **argv) {
    HttplibTest01();
    return 0;
}
```

#### Case 1
The http request hearders **dosen't contain** the `Connection: close`, and the example code **dosen't set** the `svr.set_keep_alive_max_count(1)` , the performance test result as blow, the min reponse time is **42 ms**, max response time is **1060 ms**, and 90% response time is **58 ms**。
![image](https://github.com/yhirose/cpp-httplib/assets/11806847/6c1c709e-bc8a-448c-89b8-20abeb5da4df)

#### Case 2
The http request hearders  **contain** the `Connection: close`, and the example code **dosen't set** the `svr.set_keep_alive_max_count(1)` , the performance test result as blow, the min response time is **7 ms**, max response time is **1021 ms**, and 90% response time is **6 ms**。
![image](https://github.com/yhirose/cpp-httplib/assets/11806847/5ec321e8-aae6-4129-92fe-6380ecca6edf)

### Case 3
The http request hearders **dosen't contain** the `Connection: close`, but the example code **set** the `svr.set_keep_alive_max_count(1)` , the performance test result as blow, the min reponse time is **6 ms**, max response time is **1004 ms**, and 90% response time is **6 ms**。
![image](https://github.com/yhirose/cpp-httplib/assets/11806847/6fb6779d-4c2e-4199-b737-0ab2b88fe2c6)

### Case 4
The http request hearders **dosen't contain** the `Connection: close`, but the example code **set** the `svr.set_keep_alive_max_count(3)` , the performance test result as blow, the min reponse time is **42 ms**, max response time is **460ms**, and 90% response time is **57 ms**。
![image](https://github.com/yhirose/cpp-httplib/assets/11806847/2064fef7-baeb-46c7-bd00-315986b629cc)

### Case 5
The http request hearders **dosen't contain** the `Connection: close`, but the example code **set** the `svr.set_keep_alive_max_count(10)` , the performance test result as blow, the min reponse time is **42 ms**, max response time is **622 ms**, and 90% response time is **57 ms**。
![image](https://github.com/yhirose/cpp-httplib/assets/11806847/13c89965-9c68-4cb7-873e-cb57c07b4dde)

### Need Help
Can someone explain why there's such a huge discrepancy in the performance data? I'm really struggling to understand what's causing this phenomenon. Any insights or explanations would be greatly appreciated. Looking forward to your responses!

**Comment by ChinaGuCheng** [comment]
The default read timeout for long connections is 10 milliseconds
The default receiving and sending times of the long connection are 5

If you want to increase the corresponding speed, you need to close the long connection from the client request header:
Connection : keep-alive

https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L3152
https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L3175C2-L3182

**Comment by ChinaGuCheng** [comment]
svr.set_keep_alive_max_count(10) is also 57ms, Maybe the client has its own timeout, such as 50 milliseconds？

**Comment by octocat9lee** [comment]
In our scenario, the client's HTTP requests may not include the "Connection: close" header, but we want to improve the response speed. What is the best practice in httplib for this situation?
Currently, we've found that by setting **svr.set_keep_alive_max_count(1)** , we can improve the response speed even when the "Connection: close" header is not present. However, we're not sure if this is a reasonable approach? or there are some potential alternatives?

**Comment by ChinaGuCheng** [comment]
svr.set_keep_alive_max_count(1) is to close long connections, which I think is correct. 
You can also modify the default macro to do this,
 for example 
 // #define CPPHTTPLIB_KEEPALIVE_MAX_COUNT 5
 #define CPPHTTPLIB_KEEPALIVE_MAX_COUNT 1

**Comment by yhirose** [comment]
@octocat9lee hope @ChinaGuCheng's comments help you. It's all about the HTTP/1.1 Keep-Alive connection mechanism.
