### ISSUE TITLE
Memory leak at line# 9390 "0.16.0"

### ISSUE THREAD

**Issue by OneMeanDragon** [yhirose/cpp-httplib#1881]
```c++
        const /*static*/ std::regex re(
            R"((?:([a-z]+):\/\/)?(?:\[([a-fA-F\d:]+)\]|([^:/?#]+))(?::(\d+))?)");
```
the static regex object is not getting released. temporary fix above.

**Comment by OneMeanDragon** [comment]
another in the httplib::Response somewhere thats is currently eluding me heh.

**Comment by sum01** [comment]
Why are you considering a static object a memory leak? It's obvious it won't be released, that's part of what `static` is supposed to do.

**Comment by yhirose** [comment]
@OneMeanDragon as @sum01 mentioned, I don't consider this situation as memory leak, and I would like to keep them as static for performance reason. Thanks for your understanding.
