### ISSUE TITLE
Support for openSSL version 1.1.1

### ISSUE THREAD

**Issue by itzikChaver** [yhirose/cpp-httplib#1883]
Is there any release of the library that supports openSSL version 1.1.1?

**Comment by sum01** [comment]
@itzikChaver If I remember right, [v0.14.3](https://github.com/yhirose/cpp-httplib/releases/tag/v0.14.3) was the last tag with support for OpenSSL v1.1.1. After that the minimum was raised to v3.

**Comment by yhirose** [comment]
@itzikChaver yes, v0.14.3 is the last version supporting OpenSSL v1.1.1. But I don't recommend to use it since it lacks some important changes like #1768.
