### ISSUE TITLE
client POST request always returns nullptr

### ISSUE THREAD

**Issue by swoopae** [yhirose/cpp-httplib#189]
so, i'm trying to send a post request to a php in a folder on my server. i have this piece of code.
my problem is response is always nullptr, no matter what i do to the code. is this even the right way of going about it?

thanks.

```
		httplib::Client client("https://some.site/");
		httplib::Params params;

		if (requires_username)
			params.emplace(_str("username"), config::username);

		if (requires_password)
			params.emplace(_str("password"), utilities::md5(config::password));

		auto response = client.Post("some_folder/some_php.php", params);

		while (response == nullptr) {
			response = client.Post("some_folder/some_php.php", params);
		}; // always nullptr`

**Comment by yhirose** [comment]
@swoopae, the client constructor accepts host name, not url. Also if you want to send a https request, you have to use `httplib::SSLClient`.

https://github.com/yhirose/cpp-httplib#openssl-support

```c++
httplib::SSLClient client("some.site");
cli.set_ca_cert_path("./ca-bundle.crt");
cli.enable_server_certificate_verification(true);
```

Hope it helps.
