### ISSUE TITLE
connection timed out

### ISSUE THREAD

**Issue by yz-java** [yhirose/cpp-httplib#1891]
Thread pool blocking causes connection timeout

**Comment by yhirose** [comment]
Thanks for the info, but it's too little information.

**Comment by yz-java** [comment]
If the number of SSE connections opened exceeds the number of CPU core threads, all subsequent requests will be blocked！
Extremely low throughput！

**Comment by yz-java** [comment]
> Thanks for the info, but it's too little information.

If the number of SSE connections opened exceeds the number of CPU core threads, all subsequent requests will be blocked！
http server extremely low throughput！

**Comment by PixlRainbow** [comment]
@yz-java httplib uses "blocking" socket model, and also does not use "async-await" coroutines, so the number of worker threads is the max number of simultaneous connections. The number of worker threads can be configured by [`#define`-ing a value for `CPPHTTPLIB_THREAD_POOL_COUNT`](https://github.com/yhirose/cpp-httplib/blob/master/README.md#default-thread-pool-support), but note that this increases memory usage.

**Comment by paulharris** [comment]
I think there is something wrong.
I turned the threadpool count down to 1, and ran the server in HTTP mode.
I requested /ping ie from the example with curl -v 'http://localhost:8080/ping', multiple times on one command line, one after the other.
and I get long timeouts where the server appears to be waiting at line 6678 ie `sock=accept4()`

Here is the Firefox network graph with 1 thread in the pool, requesting simple files on the localhost:
![image](https://github.com/user-attachments/assets/b749cdc7-b894-4502-be67-e727ebb83791)

Not sure how to start diagnosing this.

**Comment by paulharris** [comment]
I think the problem is all about the keepalive vs the threadpool.

The default settings are `CPPHTTPLIB_KEEPALIVE_MAX_COUNT=100`
but the max threadpool depends on the CPU.

My guess (please correct me if I am wrong) is that each keepalive connection ties up a thread.

When I ensure `CPPHTTPLIB_THREAD_POOL_COUNT > CPPHTTPLIB_KEEPALIVE_MAX_COUNT` then it seems to behave appropriately.

**Comment by paulharris** [comment]
@yhirose not sure if this notifies you if I comment on a closed issue?
