### ISSUE TITLE
Assertion `s[i]' failed.

### ISSUE THREAD

**Issue by pavolzetor** [yhirose/cpp-httplib#19]
Every now and then my server crashes with following error.

```main: ext/httplib.h:651: std::string httplib::detail::decode_url(const string&): Assertion `s[i]' failed.```

**Comment by yhirose** [comment]
@pavolzetor, thanks for the report.
Could you give me the URL string that causes the assertion, so that I could easily debug the problem?
Thank you!

**Comment by yhirose** [comment]
@pavolzetor, I think I fixed the problem you encountered. Please let me know if you still have the problem with the latest code. Thanks again for your fine report.

**Comment by pavolzetor** [comment]
No crash for quite bit time so I guess it fixed it. Thank you.
