### ISSUE TITLE
httpclient

### ISSUE THREAD

**Issue by weijx1903** [yhirose/cpp-httplib#190]
Recently, I find that it need to build with gcc-version 7.4.0 if you want to use http-client.
I build the project with gcc-version 5.4.0, Segment fault occurred by using function 
httplib::Client::Get.

**Comment by PixlRainbow** [comment]
Please provide more details such as code you were using and stack trace on the segfault

**Comment by yhirose** [comment]
@weijx1903, in addition to @PixlRainbow's comment, could you provide your OS and a minimal code snippet which reproduce the problem on my machine. Thanks!

**Comment by yhirose** [comment]
@weijx1903, I tested with g++ 5.5.0 on Ubuntu 18.04 server, and worked fine. Could you test with 5.5.0 as well and please let me know if you have the problem only with 5.4.0? I'll close it for now until I get more information from you. Thanks!
