### ISSUE TITLE
How to bind the local address and port when acting as a client?

### ISSUE THREAD

**Issue by mzgcz** [yhirose/cpp-httplib#1900]
as title says

**Comment by yhirose** [comment]
https://github.com/yhirose/cpp-httplib?tab=readme-ov-file#client-1

**Comment by mzgcz** [comment]
@yhirose I have two network cards in client computer.
I see. I can use `cli.set_interface("eth0"); // Interface name, IP address or host name` to bind source ip.

Can I use set_socket_options to bind source ip and port like this:
```
client.set_socket_options([&](socket_t sock) {
    sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons(0);
    inet_pton(AF_INET, "192.168.1.100", &addr.sin_addr);
    if (bind(sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        perror("bind");
    }
});
```

**Comment by mzgcz** [comment]
> @yhirose I have two network cards in client computer. I see. I can use `cli.set_interface("eth0"); // Interface name, IP address or host name` to bind source ip.
> 
> Can I use set_socket_options to bind source ip and port like this:
> 
> ```
> client.set_socket_options([&](socket_t sock) {
>     sockaddr_in addr;
>     memset(&addr, 0, sizeof(addr));
>     addr.sin_family = AF_INET;
>     addr.sin_port = htons(0);
>     inet_pton(AF_INET, "192.168.1.100", &addr.sin_addr);
>     if (bind(sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
>         perror("bind");
>     }
> });
> ```

It's not work. :-(
