### ISSUE TITLE
LARGE_INTEGER (windows 7,8 not supported?)

### ISSUE THREAD

**Issue by UnrealKaraulov** [yhirose/cpp-httplib#1901]
![image](https://github.com/user-attachments/assets/ed5a850d-98d6-4387-b3d0-bb22c312cacb)

**Comment by UnrealKaraulov** [comment]
```
httplib.h(2862): error C2228: left of '.HighPart' must have class/struct/union 
```

**Comment by UnrealKaraulov** [comment]
Also I has randomly strange warnings

```
                     D:\a\testProjectWin7\testProjectWin7\testProjectWin7\src\httplib.h(2832): warning C4067: unexpected tokens following preprocessor directive - expected a newline [D:\a\testProjectWin7\testProjectWin7\testProjectWin7\testProjectWin7.vcxproj]
                     D:\a\testProjectWin7\testProjectWin7\testProjectWin7\src\httplib.h(2844): warning C4067: unexpected tokens following preprocessor directive - expected a newline [D:\a\testProjectWin7\testProjectWin7\testProjectWin7\testProjectWin7.vcxproj]
                     D:\a\testProjectWin7\testProjectWin7\testProjectWin7\src\httplib.h(2854): warning C4293: '<<': shift count negative or too big, undefined behavior [D:\a\testProjectWin7\testProjectWin7\testProjectWin7\testProjectWin7.vcxproj]
                     D:\a\testProjectWin7\testProjectWin7\testProjectWin7\src\httplib.h(2857): warning C4067: unexpected tokens following preprocessor directive - expected a newline [D:\a\testProjectWin7\testProjectWin7\testProjectWin7\testProjectWin7.vcxproj]
                     D:\a\testProjectWin7\testProjectWin7\testProjectWin7\src\httplib.h(2871): warning C4067: unexpected tokens following preprocessor directive - expected a newline [D:\a\testProjectWin7\testProjectWin7\testProjectWin7\testProjectWin7.vcxproj]
                     ```

**Comment by UnrealKaraulov** [comment]
If Microsoft stopped support Windows XP, 7, 8, 9, that doesn't mean that users don't use these versions of the OS!" Users use Windows 7,8 massive, even WinXP sometimes))

**Comment by UnrealKaraulov** [comment]
Possible invalid ```#if...#else``` order.

**Comment by yhirose** [comment]
@UnrealKaraulov please keep in mind that cpp-httplib doesn't officially support Windows 8 or lower.
https://github.com/yhirose/cpp-httplib?tab=readme-ov-file#windows

@mol123, @sergio-nsk, do you have any thoughts on this?

**Comment by UnrealKaraulov** [comment]
Possible need something like : 
![image](https://github.com/user-attachments/assets/645167a4-7b39-4744-b45f-e3b49699f224)

**Comment by UnrealKaraulov** [comment]
> @UnrealKaraulov please keep in mind that cpp-httplib doesn't officially support Windows 8 or lower. https://github.com/yhirose/cpp-httplib?tab=readme-ov-file#windows
> 
> @mol123, @sergio-nsk, do you have any thoughts on this?

But why? Then users can stop support cpp-httplib in own projects...

**Comment by mol123** [comment]
@UnrealKaraulov, can you please confirm that you're using the right preprocessor flags (see here: https://github.com/yhirose/cpp-httplib/pull/1869#issuecomment-2203380530) when compiling your code?

**Comment by UnrealKaraulov** [comment]
> @UnrealKaraulov, can you please confirm that you're using the right preprocessor flags (see here: [#1869 (comment)](https://github.com/yhirose/cpp-httplib/pull/1869#issuecomment-2203380530)) when compiling your code?

Yes, 
![image](https://github.com/user-attachments/assets/b000e342-f5b4-443b-87b7-6c66e741e6fc)

Looks like 'size' variable passed not same as CreateFileMappingW case. (Not same ```#if...#else checks```)

**Comment by mol123** [comment]
@UnrealKaraulov, would you mind testing, if the following change fixes the issue?

Replace this line:

```c++
  hMapping_ = ::CreateFileMappingW(hFile_, NULL, PAGE_READONLY, size.HighPart,
                                   size.LowPart, NULL);
```

With the following line:

```c++
  hMapping_ = ::CreateFileMappingW(hFile_, NULL, PAGE_READONLY,
    static_cast<DWORD>((size_ >> 32) & 0xFFFFFFFF),
    static_cast<DWORD>(size_ & 0xFFFFFFFF), NULL);
```

**Comment by sergio-nsk** [comment]
> If Microsoft stopped support Windows XP, 7, 8, 9, that doesn't mean that users don't use these versions of the OS!
> 
> Users still use Windows 7,8 massive, even WinXP 🤣 sometimes))

Obviously such user can use older cpp-httplib releases.

**Comment by sergio-nsk** [comment]
> @mol123, @sergio-nsk, do you have any thoughts on this?

Windows 7 users can use older cpp-httplib releases.

**Comment by UnrealKaraulov** [comment]
> @UnrealKaraulov, would you mind testing, if the following change fixes the issue?
> 
> Replace this line:
> 
> ```c++
>   hMapping_ = ::CreateFileMappingW(hFile_, NULL, PAGE_READONLY, size.HighPart,
>                                    size.LowPart, NULL);
> ```
> 
> With the following line:
> 
> ```c++
>   hMapping_ = ::CreateFileMappingW(hFile_, NULL, PAGE_READONLY,
>     static_cast<DWORD>((size_ >> 32) & 0xFFFFFFFF),
>     static_cast<DWORD>(size_ & 0xFFFFFFFF), NULL);
> ```

Yes

I think the problem is that LARGE_INTEGER does not always get passed to the CreateFileMappingW function because the #if...#else checks differ.
There is a high probability that LARGE_INTEGER will not exist, and something other than the size variable is passed to CreateFileMappingW.
GetFileSizeEx is available in WinXP+, so maybe we can simply cut out the case of using GetFileSize?

**Comment by sergio-nsk** [comment]
I bet the issues are related to OP's use of the Windows SDK, which is very outdated even for Windows 7.

**Comment by yhirose** [comment]
Moved to #1903.
