### ISSUE TITLE
Nice way to call "handle_file_request" from user code

### ISSUE THREAD

**Issue by paulharris** [yhirose/cpp-httplib#1906]
Hi, this was partially addressed in #235 ,
I think it would be nice if we could write code along the lines of:
```
srv.Get("/favicon.ico", [=](const httplib::Request &, httplib::Response &res) {
    srv.send_file( location_of_favicon, res );
}
```

or something similar.
The point is `Server::handle_file_request` calls find_content_type() and does the neat mmap async method now, it would be nice to simply be able to ask httplib to send a specific file when desired.

favicon.ico is a simplistic example, but there are other cases where you compute a filename and want to send that.

**Comment by yhirose** [comment]
@paulharris thanks for the idea. There is no need for it in any my projects for now. But a pull request is always welcome!

**Comment by sonavalepratham** [comment]
@paulharris I am beginner in open source & would like to work on this. can you please explain me what needs to be done here?

**Comment by yhirose** [comment]
@paulharris I implemented it. (https://github.com/yhirose/cpp-httplib?tab=readme-ov-file#send-file-content)

```cpp
svr.Get("/content", [&](const Request &req, Response &res) {
  res.set_file_content("./path/to/conent.html");
});

svr.Get("/content", [&](const Request &req, Response &res) {
  res.set_file_content("./path/to/conent", "text/html");
});
```
