### ISSUE TITLE
Header parser incorrectly accepts NUL and CR within header values

### ISSUE THREAD

**Issue by kenballus** [yhirose/cpp-httplib#1908]
From RFC 9110:
> Field values containing CR, LF, or NUL characters are invalid and dangerous, due to the varying ways that implementations might parse and interpret those characters; a recipient of CR, LF, or NUL within a field value MUST either reject the message or replace each of those characters with SP before further processing or forwarding of that message.

cpp-httplib does not enforce this rule for CR and NUL. You can see this by running a simple example that echoes back header values (such as [this](https://github.com/narfindustries/http-garden/blob/main/images/cpp_httplib/server.cpp)), and sending it a request containing NUL and CR within a header value:
```sh
printf 'GET / HTTP/1.1\r\nHost: whatever\r\nTest: \r\x00\r\n\r\n' \
  | timeout 1 ncat --no-shutdown localhost 80 \
  | grep '"headers"' \
  | jq '.["headers"][1][1]' \
  | xargs echo \
  | base64 -d \
  | xxd
```
```
00000000: 0d00                                     ..
```

**Comment by yhirose** [comment]
@kenballus thanks for the report!

**Comment by yhirose** [comment]
@kenballus I have merged my pull request for this. Could you test with the latest httplib.h? If you confirm it works, I'll bump the version to v0.17.1, since it's a pretty critical bug. Thanks!

**Comment by yhirose** [comment]
Interesting chart! It looks the majority of implementations reject such requests with 400. I can change the current cpp-httplib behavior to return 400. What do you think?

**Comment by kenballus** [comment]
If it were me, I'd make it respond 400, but you know your users better than I do. If you think cpp-httplib's use cases warrant extra parsing leniency, then translating to SP might be the right call.

**Comment by yhirose** [comment]
@yhirose I decided to reject such requests. I'll bump up the version to v0.17.1 soon.
Thanks for your fine contribution!
