### ISSUE TITLE
how to close server gracefully

### ISSUE THREAD

**Issue by wnpllrzodiac** [yhirose/cpp-httplib#191]
code is blocked after call listen() api
Any mechanism to interrupt the block code?

**Comment by PixlRainbow** [comment]
Server and SSLServer have a function `stop` . This function should be safe to execute from any other thread or request handler, but I would ask @yhirose to be sure.

**Comment by yhirose** [comment]
@wnpllrzodiac, hope the following issue helps.
https://github.com/yhirose/cpp-httplib/issues/43
