### ISSUE TITLE
Delete method

### ISSUE THREAD

**Issue by Dimitrius-dev** [yhirose/cpp-httplib#1916]
Hi, i found out something and I want to clarify)

httplib::SSLClient has several methods like: put, post, get etc.
__Put__, __Post__, __Get__ have signature `(const std::string &path, const Headers &headers,
             const Params &params)`

But __Delete__ method has no. Is it valid?

**Comment by yhirose** [comment]
Same as #1551

**Comment by Dimitrius-dev** [comment]
I misunderstood library's request "params". I thought it means http standard params like `source.com?name=me&age=99`
