### ISSUE TITLE
Deprecate OpenSSL versions below 1.1.1

### ISSUE THREAD

**Issue by yhirose** [yhirose/cpp-httplib#192]
https://www.openssl.org/policies/releasestrat.html

Version 1.1.0 will be supported until 2019-09-11.
Version 1.0.2 will be supported until 2019-12-31 (LTS).
Version 1.0.1 is no longer supported.
Version 1.0.0 is no longer supported.
Version 0.9.8 is no longer supported.

**Comment by yamashi** [comment]
Does this mean currently the lib doesn't support the latest openssl versions ? I am running into build issues with openssl 1.1.x

**Comment by yhirose** [comment]
@yamashi, I have just copied the chart as it is from the link. ('will be' looks a bit confusing...)
Anyway, it supports 1.1.1, and I confirmed again all the unit tests passed with 1.1.1. Thanks for asking.

**Comment by yhirose** [comment]
Mac OS used by Github Action still uses an OpenSSL version less than 1.1.1...
