### ISSUE TITLE
SSL Certificate for localhost IP address

### ISSUE THREAD

**Issue by thanoue** [yhirose/cpp-httplib#1938]
Hi Team,
I'm trying to start a HTTPS server using your library. It's working perfectly, Thank you so much for that.
But It comes up with an issue when I create cert files to setup the SSL connection. I created a ca.pem file to sign the self-certificate, but it require me to use the SANs.cnf file, which includes the restriction domain, DNS, IP address.... But the problem is I start the server on local machine, which means the IP address can be changed all the time. So I have to regenerate keys file time after time! That is not good way. 
So could you help me with this? Or can I use the cfx file with a password instead?
Thanks.

**Comment by grootgordon** [comment]
Does API `enable_server_certificate_verification` meet your needs?

**Comment by thanoue** [comment]
Sorry I'm not sure what you mean, I'm creating a server, not client with this library.

**Comment by yhirose** [comment]
@thanoue thanks for the question, but I am not in a good position to answer your question since I am not an expert of TLS/SSL... The only think I can say is to obtain a global IP address and use it, so that the IP address won't change. Soryy for my lock of the knowledge in this area.

**Comment by thanoue** [comment]
so how can I obtain the global Ip address and use it as a local one @yhirose ?

**Comment by thanoue** [comment]
For someone who still facing this issue, you can use some libraries (BouncyCastle for sure) to generate the server.pem file in application's runtime instead of OpenSSL.  with that way you can get the current local IP address on your device and let the library do the rest for you.
