### ISSUE TITLE
server side connection_timeout supported?

### ISSUE THREAD

**Issue by hassan379** [yhirose/cpp-httplib#1939]
Thank you for this great library.
Does this library support connection timeouts on server side?
I have a function that can run for a long time depending on the passed parameters.
Does the server cancel the request and throw an exception or error that can be handled to send a proper response after a specific time?
I tried using keep-alive connections and timeout functions, but without success.
Thanks in advance.

**Comment by yhirose** [comment]
@hassan379 thanks for the question. cpp-httplib server doesn't support connection timeout. Sorry about that...

**Comment by hassan379** [comment]
is there any plan to support it later ?

**Comment by yhirose** [comment]
There is no plan for it. It has to be handled in a request handler.

```cpp
svr.Post("/long", [](const httplib::Request &, httplib::Response &res) {
  try {
    auto body = function_which_takes_long_time(); // throw an exception when the execution time is too long...
    res.set_content(body, "text/plain");
  } catch (...) {
    res.status = StatusCode::InternalServerError_500;
    res.set_content("NG", "text/plain");
  }
});
```
