### ISSUE TITLE
How to post binary file?

### ISSUE THREAD

**Issue by wu1274704958** [yhirose/cpp-httplib#194]
How to post binary file?

**Comment by yhirose** [comment]
@wu1274704958, thanks for the question, but it's a general HTTP question.
https://stackoverflow.com/questions/8196124/sending-binary-data-over-http

**Comment by PixlRainbow** [comment]
@wu1274704958 2 ways:
1. Multipart form with file form field
2. Set content type to file type, write binary data directly to post body
