### ISSUE TITLE
Error c0000005 in DLL using cpp-httlib and running under an azure application

### ISSUE THREAD

**Issue by siaict** [yhirose/cpp-httplib#1942]
We are using cpp-httplib in a VisualStudio cpp DLL project.
Within this DLL we are using your library to create a simple http POST.
This DLL compile correctly.

Then we have an Azure Function Project in c# that includes this DLL.
If we run this app locally on VisualStudio everything runs ok and the DLL does the POST correctly.
When we publish this project on azure and call the azure function with postman, the app crashes on client.POST statement.

The error on azure is:

CoreCLR Version: 6.0.3224.31407
.NET Version: 6.0.32
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFE33364089 (00007FFE33190000) with exit code c0000005

**We are compiling DLL with the last version of VisualStudio (17.11.4) and we also noticed that if we compile DLL on a PC with a lower version of VisualStudio (17.9.5) the DLL runs ok also on azure.**

**Comment by yhirose** [comment]
@siaict thank you for the feedback. But to be honest, I have no idea since I have never mixed this library with C# code. Sorry that I am not able to give you a help...

**Comment by LanChestK** [comment]
I missed this problem in C++ demo,undered the windows plat, i think this lib maybe cannot used on windows msvc platform.

**Comment by LanChestK** [comment]
> I missed this problem in C++ demo,undered the windows plat, i think this lib maybe cannot used on windows msvc platform.



> @siaict thank you for the feedback. But to be honest, I have no idea since I have never mixed this library with C# code. Sorry that I am not able to give you a help...
