### ISSUE TITLE
Received HTTP/0.9 when not allowed

### ISSUE THREAD

**Issue by rogerwangzy** [yhirose/cpp-httplib#1945]
// HTTP
	httplib::Server svr;
	svr.Get("/hi", [](const httplib::Request &, httplib::Response &res) {
		res.set_content("Hello World!", "text/plain");
	});
	svr.listen("localhost", 8080);

what i do from cmd:
curl http://127.0.0.1:8080/hi

it returns

curl: (1) Received HTTP/0.9 when not allowed

**Comment by yhirose** [comment]
Thanks for the message, but I have no idea. You could try with `curl http://localhost:8080/hi`.
