### ISSUE TITLE
server directly crash after 1 or 2 seconds without info with Release version

### ISSUE THREAD

**Issue by TianmengChen** [yhirose/cpp-httplib#1951]
server.cpp code is shown as bellow

```
#include <httplib.h>

int main(void)
{
  using namespace httplib;
  Server svr;

  svr.Get("/hi", [](const Request& req, Response& res) {
    res.set_content("Hello World!", "text/plain");
  });
  svr.listen("127.0.0.1", 8080);
}

```
build on windows: cmake -S .\ -B .\build\ && cmake --build .\build\ --config Release -j8
but Debug version it works: make -S .\ -B .\build\ && cmake --build .\build\ --config Debug -j8

and cannot have error info by try catch or if else for  svr.listen("127.0.0.1", 8080);

using db tools, and we have

```
Process 7664 stopped
* thread #8, stop reason = Exception 0xc0000005 encountered at address 0x7ffa44923020: Access violation reading location 0x00000000
    frame #0: 0x00007ffa44923020 msvcp140.dll`_Thrd_yield + 272
msvcp140.dll`_Thrd_yield:
->  0x7ffa44923020 <+272>: movq   (%rax), %rax
    0x7ffa44923023 <+275>: callq  *0x4268f(%rip)
    0x7ffa44923029 <+281>: jmp    0x7ffa449230b6 ; <+422>
    0x7ffa4492302e <+286>: cmpq   $0x0, (%rdx)
```

**Comment by yhirose** [comment]
Sorry, I am not able to give you any meaningful help... You can get ideas from CMake or meson related files in this repo to make release build correctly.

**Comment by FocusedSG** [comment]
> server.cpp code is shown as bellow
> 
> 
> 
> ```
> 
> #include <httplib.h>
> 
> 
> 
> int main(void)
> 
> {
> 
>   using namespace httplib;
> 
>   Server svr;
> 
> 
> 
>   svr.Get("/hi", [](const Request& req, Response& res) {
> 
>     res.set_content("Hello World!", "text/plain");
> 
>   });
> 
>   svr.listen("127.0.0.1", 8080);
> 
> }
> 
> 
> 
> ```
> 
> build on windows: cmake -S .\ -B .\build\ && cmake --build .\build\ --config Release -j8
> 
> but Debug version it works: make -S .\ -B .\build\ && cmake --build .\build\ --config Debug -j8
> 
> 
> 
> and cannot have error info by try catch or if else for  svr.listen("127.0.0.1", 8080);
> 
> 
> 
> using db tools, and we have
> 
> 
> 
> ```
> 
> Process 7664 stopped
> 
> * thread #8, stop reason = Exception 0xc0000005 encountered at address 0x7ffa44923020: Access violation reading location 0x00000000
> 
>     frame #0: 0x00007ffa44923020 msvcp140.dll`_Thrd_yield + 272
> 
> msvcp140.dll`_Thrd_yield:
> 
> ->  0x7ffa44923020 <+272>: movq   (%rax), %rax
> 
>     0x7ffa44923023 <+275>: callq  *0x4268f(%rip)
> 
>     0x7ffa44923029 <+281>: jmp    0x7ffa449230b6 ; <+422>
> 
>     0x7ffa4492302e <+286>: cmpq   $0x0, (%rdx)
> 
> ```
> 
> 

Hi, did you figure out what was causing the crash? I'm having the same issue.

**Comment by apinge** [comment]
@FocusedSG 
Hi, we've found a workaround for the issue. To resolve the problem, you can set compiler option "Runtime Library" to "Multi-threaded (/MT)" which should address the condition.
Alternatively you can add the following line to your CMakeLists.txt:
```
if (MSVC)
  set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded")
endif()
```
This issue appears to occur only when building multithreaded code with MSVC. For more information, please refer to the following link: https://developercommunity.visualstudio.com/t/debug-build-works-but-release-build-failsas-well-a/428160
Please try the above solution and let us know if it works for you.

**Comment by FocusedSG** [comment]
@apinge Thank you! Yes I was trying to build a multithreaded application and encountered the issue. Your solution worked perfectly.
