### ISSUE TITLE
Question/help request: How to have more than 8 outstanding SSE clients?

### ISSUE THREAD

**Issue by 314159** [yhirose/cpp-httplib#1953]
I am writing a server that should communicate with several browsers, and show the on-air status of that user's camera.  I thought that SSE would be a great way to do that.  I've written the program and all is well.

However, I cannot get more than 8 clients listening at the same time -- any more requests just hang.  I suspect that each worker thread is associated with a single SSE client, and since we are limited to the number of threads the system can handle (maximum of 8), this means I can only have 8 browsers connected at the same time.  I would like to have two browsers per camera, one facing the operator and another facing the stage for the talent to know which camera is active.  This setup limits me to four cameras, which is doable now, but not in the future.

Is there some other way to handle more than 8 clients, i.e., can a thread be made to handle more than one client, or can I create more threads than what my processor can handle at the same time?  The number of simultaneous events will be very small.  They will only occur when a camera is taken on or off air, being previewed (potentially the next camera to be on-air) or not, or when the director sends a message.

Thank you in advance for any comments or help.

**Comment by yhirose** [comment]
@314159 thanks for your feedback. The default thread count is defined by `CPPHTTPLIB_THREAD_POOL_COUNT`, and it's declared as below. So it depends on a user's hardware, and it guarantees that the thread pool count should be at least 8.

https://github.com/yhirose/cpp-httplib/blob/10d68cff5081d8c7b7cae74000e0c423107dc7b8/httplib.h#L122-L125

So you can manually change it by setting `CPPHTTPLIB_THREAD_POOL_COUNT` to whatever appropriate count in your situation.

Also there is another way to change the thread count, and even you can configure the max queued requests in the thread pool. Here is the excerpt from [Default thread pool support](https://github.com/yhirose/cpp-httplib?tab=readme-ov-file#default-thread-pool-support) section in README.

```cpp
svr.new_task_queue = [] { return new ThreadPool(/*num_threads=*/12, /*max_queued_requests=*/18); };
```

You can pass proper values to the constructor of `ThreadPool` which fit in your situation.

If your system expects many concurrent requests like hundreds, cpp-httplib isn't a right choice for you, and I recommend to try one of non-blocking HTTP server libraries.

Hope it helps!

**Comment by 314159** [comment]
Thanks, I'll try that. No worries about hundreds of connections: I actually can work with 8, but I feel uncomfortable that I couldn't go higher if needed.

**Comment by 314159** [comment]
@yhirose I moved my `#include` into a new `http.hpp` file and included that instead.  But I did not see any difference in behavior.

Here is `http.hpp`:

```cpp
#pragma once

#define CPPHTTPLIB_THREAD_POOL_COUNT 16
#include <httplib.h>
```

I am using version `0.18.0`.

Have any ideas?
