### ISSUE TITLE
Solution to #139 breaks large gzipped responses

### ISSUE THREAD

**Issue by RichardSteele** [yhirose/cpp-httplib#196]
The `decompressor` introduced with 6f663028e9293f2fd2f30b0b3c6c152ddecf0c76 breaks the complete retrieval of large gzipped responses because its `decompress` function assembles the piecewise decompressed data into a local string `decompressed`. Turning this string into an instance variable solves the problem.

To reproduce the issue, set `CPPHTTPLIB_RECV_BUFSIZ` to some really small value like 16 and run the tests.

**Comment by yhirose** [comment]
@RichardSteele, thanks for the report! It's a really bad problem... I'll look into it this weekend.
