### ISSUE TITLE
Does cpp-httplib have problems with serving large files?

### ISSUE THREAD

**Issue by XLIMIT1337** [yhirose/cpp-httplib#1961]
#include <httplib.h>
#include <iostream>
#include <filesystem>
#include <fstream>

namespace fs = std::filesystem;

int main() {
    httplib::Server svr;

    svr.Get("/", [](const httplib::Request& req, httplib::Response& res) {
        std::string htmlContent = "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>XLIMIT</title><style>body{margin:0;padding:0;background-color:#d3d3d3;font-family:Arial;color:#000;}#container{width:100%;max-width:900px;margin:50px auto;background-color:#f0f0f0;border:1px solid #a9a9a9;}#title{font-size:14px;font-weight:normal;color:#000;background-color:#b0b0b0;padding:8px 10px;border-bottom:1px solid #a9a9a9;text-align:left;}#file-container{display:flex;justify-content:space-between;align-items:center;padding:8px 10px;border-bottom:1px solid #a9a9a9;font-size:12px;}#file-container:last-child{border-bottom:none;}#file-container a{color:#ff6600;text-decoration:none;font-size:12px;font-weight:bold;}#file-container a:hover{text-decoration:underline;}#file-name{font-size:12px;color:#000;}</style></head><body><div id='container'><div id='title'>XLIMIT</div>";

        for (const auto& entry : fs::directory_iterator(".")) {
            if (fs::is_regular_file(entry.path())) {
                htmlContent += "<div id='file-container'><div id='file-name'>" + entry.path().filename().string() + "</div><a href='/" + entry.path().filename().string() + "' download>DOWNLOAD</a></div>";
            }
        }

        htmlContent += "</div></body></html>";
        res.set_content(htmlContent, "text/html");
        });

    svr.Get(R"(/(.*))", [](const httplib::Request& req, httplib::Response& res) {
        std::string filePath = "." + req.path;
        if (fs::exists(filePath) && fs::is_regular_file(filePath)) {
            std::ifstream file(filePath, std::ios::binary);
            std::ostringstream oss;
            oss << file.rdbuf();
            res.set_content(oss.str(), "application/octet-stream");
        }
        else {
            res.status = 404;
            res.set_content("File Not Found", "text/plain");
        }
        });

    std::cout << "XLIMIT listening on Port 80" << std::endl;
    svr.listen("0.0.0.0", 80);

    return 0;
}

This is my code, if i try to download an file around the 90mb mark it just keeps loading forever

**Comment by yhirose** [comment]
@XLIMIT1337 I am able to serve a 100MB file successfully in the following unit test. So if your code doesn't work, it could be related to your network condition instead of cpp-httplib itself.

https://github.com/yhirose/cpp-httplib/blob/e0ebc431dc78e3eee04400c0619162f94f6476ab/test/test.cc#L46C14-L46C24
https://github.com/yhirose/cpp-httplib/blob/e0ebc431dc78e3eee04400c0619162f94f6476ab/test/test.cc#L2652-L2656

**Comment by XLIMIT1337** [comment]
Okay thank you! :)
