### ISSUE TITLE
Support for HTTP range requests in server?

### ISSUE THREAD

**Issue by kpeeters** [yhirose/cpp-httplib#197]
I am using httplib to serve video files, using `response.content_provider` to serve the data. This works fine, apart from the fact that httplib's server does not seem to understand clients that make an http range request. Am I doing something wrong, or is this indeed not supported? If the latter, are there any intentions to support this feature in the future? 

(I am aware of the fact that ranges are supported for requests (clients), but that is not what I am looking for).

**Comment by PixlRainbow** [comment]
From inspecting the implementation of `content_producer`, I can see that the range header is completely ignored. The offset given to your handler is only the number of bytes read so far. However, support might be added in the future as it does not seem to be a difficult change to make.

**Comment by yhirose** [comment]
Thanks for the report! The server part doesn't handle the HTTP range header. I'll look into it to find a good interface to support it, and get back to you.

**Comment by yhirose** [comment]
@kpeeters, in order to support the HTTP range request, I made a major interface change to the content_provider interface. Here is the new way to use the `content_provider`.

```cpp
svr.Get("/stream", [&](const auto &req, atuo &res) {
  auto data = std::make_shared<std::string>("abcdefg");

  res.set_content_provider(
    data->size(),
    [data](uint64_t offset, uint64_t length, Out out) {
      out(&d[offset], length);
    });
});
```

The httplib server now fully supports the HTTP range request, and you don't have to do anything to enable it. It's a built-in feature. You can test with the sample hello server in the example folder.

```
> ./example/hello
```

As you can see below, the server now responses to the HTTP range request from curl.

```
> curl http://localhost:1234/hi -I
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 12
Content-Type: text/plain
```

```
> curl http://localhost:1234/hi
Hello World!
```

```
> curl http://localhost:1234/hi -r "1-3"
ell
```

```
> curl http://localhost:1234/hi -r "0-0,-1"
----cpp-httplib-multipart-data-nJcLnoHXqvUXix4r
Content-Type: text/plain
Content-Range: bytes 0-0/12

H
----cpp-httplib-multipart-data-nJcLnoHXqvUXix4r
Content-Type: text/plain
Content-Range: bytes 11-11/12

!
----cpp-httplib-multipart-data-nJcLnoHXqvUXix4r--
```

Please let me know if you find any problem. Thanks for your feedback!

**Comment by kpeeters** [comment]
Thanks, that's quick! 

In the new `content_provider`,  am I still allowed to return less than the requested length (and does httplib then call my provider again to get the remainder of the requested chunk)?

**Comment by yhirose** [comment]
Yes, indeed! If you provide less than the content size, the callback will be called with the adjusted offset and length representing the remainder of the content.

https://github.com/yhirose/cpp-httplib/tree/9d7b7175043d70365bc9633db68f575667122764#stream-content-with-content-provider

https://github.com/yhirose/cpp-httplib/blob/9d7b7175043d70365bc9633db68f575667122764/test/test.cc#L519-L529

**Comment by kpeeters** [comment]
It seems to work with my own tests using curl, but now Chrome does not like the video which I sent it anymore, not even when I just play from beginning to end (that is, when a range request is made. I have verified that the right bytes get sent to the `out` object, so the only thing I can think of that could upset Chrome is a header issue. Firefox' video player plays this fine, so it's close though.

Looking at the docs at https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests , it seems to me that a 206 response header should include a `Content-Range` header, but httplib does not send this when a simple range request is made (as in the examples you gave above). 

So can you please add that `Content-Range` header in any 206 response? Then I'll give it another shot.

**Comment by yhirose** [comment]
@kpeeters, oops... I have just added `Content-Range` header for a singe range header as well. Could you try with the latest? Sorry for the problem.

**Comment by kpeeters** [comment]
Thanks a million, all works fine now! 

One final question related to this: is there any way for me to get a notification when the client closes the connection, so in other words, when I will no longer receive calls to the `content_provider` for a given stream? I am reading data from a file on demand, so I need to keep a file open for reading as I typically get more calls to my `content_provider`. The client will typically stop requesting data when I have sent the last byte, so I use that as a signal to close the file now. But that may not always be true (e.g. when the client wants to re-play a segment of the video served). So it would be good to have a clear signal that 'the client has closed the connection'.

**Comment by yhirose** [comment]
@kpeeters, glad to hear the change works for you. It doesn't notify the connection close initiated by client. As a reminder for my self, could you submit another issue? I'll look into it when I have time. It may require a change to the `content_provider` interface or can be done differently without any interface change. Thanks!
