### ISSUE TITLE
set_error_handler and set_exception_handler both called on exception

### ISSUE THREAD

**Issue by glindsell** [yhirose/cpp-httplib#1970]
This may be misuse of the library on my side. So please let me know if I'm missing something glaringly obvious, and apologies if so.

When we set functions to be called in both `set_error_handler` and `set_exception_handler` on the server, both functions are called when an exception is thrown while handling a request. It seems that first the function from `set_exception_handler` is called, followed by the function from `set_error_handler`.

This means that using code such as that given in the examples, the exception message which is set as the content in the `set_exception_handler` function is replaced by the error message which is set as the response content in the `set_error_handler` function. Is this expected behaviour, or a bug?

If expected behaviour, what is the suggested way to preserve the exception message that is set as the content in the `set_exception_handler` function? For now we have added a custom header `"X-Exception-Handled"` to `"true"` in the `set_exception_handler` function, which we then check for in the `set_error_handler` function before deciding whether to set the content. Thanks in advance for any help, and please let me know if anything doesn't make sense or more information is needed.

**Comment by yhirose** [comment]
@glindsell thanks for the question. I think your solution can work. Also you can simply check if `res.body` is empty, then the error handler can set content.

I added a unit test case to show how my solution works. Hope it helps!
https://github.com/yhirose/cpp-httplib/blob/924f214303b860b78350e1e2dfb0521a8724464f/test/test.cc#L2114

**Comment by glindsell** [comment]
> @glindsell thanks for the question. I think your solution can work. Also you can simply check if `res.body` is empty, then the error handler can set content.
> 
> I added a unit test case to show how my solution works. Hope it helps!
> 
> https://github.com/yhirose/cpp-httplib/blob/924f214303b860b78350e1e2dfb0521a8724464f/test/test.cc#L2114

Thanks @yhirose. That makes sense and is simpler than the custom exception method!
