### ISSUE TITLE
http server async method

### ISSUE THREAD

**Issue by thanoue** [yhirose/cpp-httplib#1974]
Hi team,
I have a question about the HTTP server. When I start a server in an application, and send a request from another application on the same device. the server will move itself to the foreground and do a long-term process (~10 seconds) before sending the response back to the client. Will that be good for memory and CPU consuming? Or I should create 2  short-term APIs, one for starting the process, and one for getting the status/response of the process later, when the client application was moving back to the foreground.

Thanks.

**Comment by yhirose** [comment]
cpp-httplib server is a multithreaded blocking server. Each request needs a worker thread in a thread pool. If you expect thousands of requests simultaneously, I think cpp-httplib is not a tool that you want to use, and I suggest you to find a server library using non-blocking I/O socket. Hope it helps!
