### ISSUE TITLE
Default Accept-Encoding header for the client

### ISSUE THREAD

**Issue by Yogurt4** [yhirose/cpp-httplib#1975]
Suggestion: `httplib::Client` could set a default Accept-Encoding header automatically, based on the compile options, like

```
#if defined CPPHTTPLIB_ZLIB_SUPPORT
		{ "Accept-Encoding", "gzip, deflate" }
#endif

```
(plus the combinations with Brotli).

It's quite trivial to implement. Shall I provide a pull request though?

**Comment by yhirose** [comment]
@Yogurt4 I implemented it. Thanks for the suggestion!

**Comment by Yogurt4** [comment]
Wow! Thanks for the superfast response, and for implenting it.
