### ISSUE TITLE
Need inlined u8string_to_wstring?

### ISSUE THREAD

**Issue by vytools** [yhirose/cpp-httplib#1977]
It looks like the commit: 9dd565b6e37c843129ade4e02761e18657297c33
adds a definition
"u8string_to_wstring"
with my application I now get
fatal error LNK1169: one or more multiply defined symbols found for that definition. 
Could it be inlined?

 `
#if defined(_WIN32)
inline std::wstring u8string_to_wstring(const char *s) {
`

I'm happy to do a pull request, but I'm sure it would be easier for you to fix than to give me permissions :). Thanks.

**Comment by yhirose** [comment]
@vytools thanks for the report!
