### ISSUE TITLE
to_lower impl return different values than std::tolower

### ISSUE THREAD

**Issue by s-kzv** [yhirose/cpp-httplib#1987]
detail::case_ignore::to_lower have table with different values than std::tolower. Is this a mistake?
code for check

```
#include <cctype>
#include <iostream>

#include "httplib.h"

int main() {
    for (int i = 0; i < 256; ++i) {
      int result_std = std::tolower(i);
      int result_httplib = httplib::detail::case_ignore::to_lower(i);
      if (result_std != result_httplib) {
        std::cout << "input i = " << i << ": result: std " << result_std
                  << " != " << result_httplib << " httplib" << std::endl;
      }
    }
}
```

> input i = 192: result: std 192 != 224 httplib
> input i = 193: result: std 193 != 225 httplib
> input i = 194: result: std 194 != 226 httplib
> input i = 195: result: std 195 != 227 httplib
> input i = 196: result: std 196 != 228 httplib
> input i = 197: result: std 197 != 229 httplib
> input i = 198: result: std 198 != 230 httplib
> input i = 199: result: std 199 != 231 httplib
> input i = 200: result: std 200 != 232 httplib
> input i = 201: result: std 201 != 233 httplib
> input i = 202: result: std 202 != 234 httplib
> input i = 203: result: std 203 != 235 httplib
> input i = 204: result: std 204 != 236 httplib
> input i = 205: result: std 205 != 237 httplib
> input i = 206: result: std 206 != 238 httplib
> input i = 207: result: std 207 != 239 httplib
> input i = 208: result: std 208 != 240 httplib
> input i = 209: result: std 209 != 241 httplib
> input i = 210: result: std 210 != 242 httplib
> input i = 211: result: std 211 != 243 httplib
> input i = 212: result: std 212 != 244 httplib
> input i = 213: result: std 213 != 245 httplib
> input i = 214: result: std 214 != 246 httplib
> input i = 216: result: std 216 != 248 httplib
> input i = 217: result: std 217 != 249 httplib
> input i = 218: result: std 218 != 250 httplib
> input i = 219: result: std 219 != 251 httplib
> input i = 220: result: std 220 != 252 httplib
> input i = 221: result: std 221 != 253 httplib
> input i = 222: result: std 222 != 254 httplib

**Comment by yhirose** [comment]
@s-kzv it's intentional. `detail::case_ignore::to_lower` is for UTF-8 Latin-1, and won't be affected by the system locale. If you add `std::setlocale(LC_ALL, "en_US.UTF-8");` in your code, it works as expected. Hope it helps.

https://www.unicode.org/charts/PDF/U0080.pdf

**Comment by sum01** [comment]
If that was what you're worried about, there's
```cpp
template< class CharT >
CharT tolower( CharT ch, const locale& loc );
```
in `<locale>` which would let you force a locale. Then you can either force `en_US.UTF-8` or use the `std::locale::classic()` to get the `"C"` locale that can't be altered.

I think `std::strcmp` ignores locale too?

---

Just for fun, I wrote up a string comparison speed-test against a few different ways of doing it.
Each run has randomized string gen & what strings are compared.

Here's the results (on my machine) using `g++ -std=c++11 -O2`. No effort was made to parallelize or use threads in some way, it's all relatively straightforward.
```
Beginning generation of 30000 random strings between 1-50 in length...
Beginning testing of 8 functions using randomly chosen strings from 30000 strings, with 2147483 iterations per function...

Test "test::std_string_operator_equals" averaged 41ns.
Test "test::std_string_compare" averaged 109ns.
Test "test::std_strcmp" averaged 58ns.
Test "test::icase::httplib_to_lower" averaged 47ns.
Test "test::icase::std_tolower" averaged 41ns.
Test "test::icase::native_cmp" averaged 62ns.
Test "test::icase::std_tolower_force_enUS_UTF8" averaged 43ns.
Test "test::icase::std_tolower_classic_locale" averaged 42ns.

```

Here's the code if you're curious https://gist.github.com/sum01/7f0d9e086796c6b394462db066885c00

**Comment by yhirose** [comment]
@sum01 sorry for the late reply.  Thanks for the excellent benchmark test!

Here is the result on my M1 MacBook Pro.

```bash
> g++ -std=c++11 -O2 str_comp_test.cpp && ./a.out
Beginning generation of 30000 random strings between 1-50 in length...
Beginning testing of 8 functions using randomly chosen strings from 30000 strings, with 2147483 iterations per function...

Test "test::std_string_operator_equals" averaged 17ns.
Test "test::std_string_compare" averaged 18ns.
Test "test::std_strcmp" averaged 16ns.
Test "test::icase::httplib_to_lower" averaged 16ns.
Test "test::icase::std_tolower" averaged 18ns.
Test "test::icase::native_cmp" averaged 18ns.
Test "test::icase::std_tolower_force_enUS_UTF8" averaged 18ns.
Test "test::icase::std_tolower_classic_locale" averaged 18ns.
```
