### ISSUE TITLE
README.md update about enable_server_host_verification

### ISSUE THREAD

**Issue by gillesdegottex** [yhirose/cpp-httplib#1992]
Hey,

I believe this is outdated:

https://github.com/yhirose/cpp-httplib/blob/fe07660f40c3f29bdda84f0c637e6b7dc4734ee4/README.md?plain=1#L82

(can't find it in httplib.h)

**Comment by yhirose** [comment]
@gillesdegottex thanks for the report!

**Comment by gillesdegottex** [comment]
You're welcome! And thanks for this great lib!
