### ISSUE TITLE
Notify ContentProvider when connection closes

### ISSUE THREAD

**Issue by kpeeters** [yhirose/cpp-httplib#200]
The current `ContentProvider` is only informed about which data is needed, but there is no mechanism to let it know that no further data will be requested. It would be nice to have some way to get informed that a connection has been closed, either directly by using an extra argument for the `ContentProvider` function, or by using a separate callback function that gets called when the connection closes.

Background: I am using the `ContentProvider` to stream large amounts of data, which I cannot pre-load all into memory. So I open a file, then use a `ContentProvider` function which gets passed a reference to the file object as a capture variable, so that I can read the required data from the file on each call to that function. However, I need to 'guess' when I can safely close the file and delete the file object, as httplib will not tell me. Reaching the last byte is not always a reliable indicator (the connection may be closed before reaching the end, or there may be a range requests which reads more data after the last byte has been read).

**Comment by yhirose** [comment]
@kpeeters, I added the third parameter in `set_content_provider ` which takes `content_provider_resource_releaser`. It's guaranteed that the releaser will be called regardless a request completes or not. So it's the best place to close the open resource. Please let me know if this change is enough to handle what you try to do.

https://github.com/yhirose/cpp-httplib/blob/2823a94fc17f59fa0d874e5d91521e9dadbea8c7/test/test.cc#L519-L530

**Comment by kpeeters** [comment]
Yes, that does the trick, thanks!

**Comment by yhirose** [comment]
Thanks for the replay.
