### ISSUE TITLE
How to identify malicious attacks and slow down their response speed?

### ISSUE THREAD

**Issue by ztkboj58623** [yhirose/cpp-httplib#2003]
I am using httplib to provide a login service. If a hacker attempts to crack the username and password using a dictionary attack, the thread priority for the IP address decreases as the number of incorrect attempts exceeds three. The higher the number of incorrect attempts, the longer the response time (e.g., 3 seconds). Furthermore, during this 3-second delay, any new incoming requests should not be blocked from being processed.

**Comment by yhirose** [comment]
@ztkboj58623 thanks for the report. But it is beyond the cpp-httplib responsibility, but it's a more like general HTTP communication issue. Thanks for your understanding!
