### ISSUE TITLE
Post request: httplib.h hanging with a EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by Aebian** [yhirose/cpp-httplib#2006]
Hi yhirose,

Thanks for the library, appreciated.  I have a issue with a post request and I'm not sure where the issue comes from. 

*Problem Description:*
httplib.h hanging with a EXC_BAD_ACCESS. --> Exception: EXC_BAD_ACCESS (code=1, address=0x10)
Cause unkown. I get redirect to the function.h in CLion on line 379 which has the following code:       __f_ = __f.__f_->__clone();

*Steps to reproduce:*
1. Have a simple httplib.h Server running that accepts arguments.
2. Call that URL and let it execute your function.
3. Function gets called and spits put a connected, then tries a post request.
4. Server crashes with a EXC_BAD_ACCESS fault. --> Exception: EXC_BAD_ACCESS (code=1, address=0x10)
5. The CLion debugger mentions something that this = httplib:DataSink& at 0x16f5ac068 but it seems empty.
6. Post request failed.

*Expected Result:* The post request succeeds and a json response is returned. At least a 200 should be picked up. In CURL this works...

*Impact:*
Application throws major exception and hangs. 

*Attachments:*
1. Code snippet (the function) of my post request
2. Screenshot of the params values 
3. Screenshot of the Crash

*Additional Information:*
It does not matter if I hardcode the params directly (including the base_url). I get the same error always. 
With my IDE I can confirm the crash only happens when the post request is being executed. Everything before works flawless. 

I can also confirm that the params are all strings and correctly filled. 
Can you please help me understand, if something on my side is causing the issue and not the library? 

I did a test via ``curl -X POST "https://<complete-url>" -d <complete-list-of-params>`` and it returned a 200 and a josn response.   

```cpp
bool handleAuthCode(const std::string& code, const std::string& acsRef)
{
    httplib::SSLClient cliACS("login.microsoftonline.com", 443);
    httplib::Params acsParams
    {
        {"client_id", std::string(client_id)},
        {"redirect_uri", acsBaseURL() + "/auth/proc"},
        {"grant_type", "authorization_code"},
        {"client_secret", std::string(client_secret)},
        {"code", code},
        {"state", acsRef}
    };
    std::string base_url = "/" + std::string(tenant_id) + "/oauth2/v2.0/token";

    try
    {
        const auto res = cliACS.Post (base_url, acsParams);
        if (!res)
        {
            std::print("HTTP Error: {0}\n", to_string(res.error()));
            std::cerr << "HTTP Error:" << to_string(res.error());
            return false;
        }
        if (res->status == 200)
        {
            return true;
        }
    }
    catch (const std::exception& e)
    {
        std::cerr << "ACS warning: handleAuthCode function had a major malfunction" << e.what() << std::endl;
    }
    return false;
}
```
![image](https://github.com/user-attachments/assets/4050f251-d600-4d8b-b5a0-489858ec3b0c)
<img width="1298" alt="image" src="https://github.com/user-attachments/assets/55cb2682-aacd-4281-be9b-3c545b97b2bf" />

**Comment by yhirose** [comment]
@Aebian thank you for the report, but I don't know why the problem happens to be honest. There is one issue talking about EXC_BAD_ACCESS, but it was a user's mistake. Could you investigate a possibility that outside code causes this EXC_BAD_ACCESS  problem instead of cpp-httplib? Sorry that I can't be of much help...

https://github.com/yhirose/cpp-httplib/issues/635#issuecomment-686446935

**Comment by Aebian** [comment]
@yhirose Thanks for the reply. 

I have a hard time finding the root cause for the EXC_BAD_ACCESS.
It only gets triggered when the ``const auto res = cliACS.Post (base_url, acsParams);`` is fired. When I set a breakpoint on this, as long as I don't let it execute, No issue. 

I stepped into the call and the last thing it did was:
```cpp
inline Result ClientImpl::Post(const std::string &path, const Headers &headers,
                               const Params &params) {
  auto query = detail::params_to_query_str(params);
  return Post(path, headers, query, "application/x-www-form-urlencoded");
}```
The return basically, but I'm not sure if this is just a false positive. 
The library was building the query_string correctly, I saw that in my debugging. 

As seen above, all params are filled, I also tried hardcoding the values. 
If it would be outside code, I wonder why it only crashes when the post is executed, but not before. 

Do you have other ideas that I could try? Is there a way I could get detailed error logging of the post request itself? 
I'm unsure what exactly causes the crash, but if Microsoft would be at fault, I would expect a error message to be returned, but my debug efforts in catching a error that helps me find the root cause.

Thanks!

**Comment by yhirose** [comment]
How about Get method as below?

```
  httplib::Client client("https://google.com");
  client.set_follow_location(true);
  auto res = client.Get("/");
```

**Comment by Aebian** [comment]
That's odd. 
It causes the crash problem too and goes to the same cursor in function.h on line 379 which has the following code: _f = __f._f->__clone();

<img width="778" alt="image" src="https://github.com/user-attachments/assets/8e230d8a-842a-4dfd-a208-631fe9fb1e87" />

If I set a breakpoint and don't let it run, no crash. 
If I comment out the post and let the program run without a post, it doesn't crash and continues as expected.


My version of httplib.h seems to be 0.18.3 (so the latest published release)
Oh gosh and what I forgot to add, my C++ version used is 23.  Not sure if this could cause issues, as it is still in development...

**Comment by yhirose** [comment]
If the simple Get method doesn't work, the problem seems to reside out of cpp-httplib since I have never experienced EXC_BAD_ACCESS in the past. I recommend you to make the smallest possible example which can reproduce the problem. Sorry that I am not able to give you meaningful information...

**Comment by Aebian** [comment]
Hi,

I built a sample test program now.  The C++ code for it is:

```cpp
#include <iostream>
#define CPPHTTPLIB_OPENSSL_SUPPORT
#include <httplib.h>

int main()
{
    httplib::Server srvACS;

    srvACS.Get("/", [](const httplib::Request& req, httplib::Response& res)
    {
        httplib::Client client("https://google.com");
        client.set_follow_location(true);
        client.enable_server_certificate_verification(false);
        auto res2 = client.Get("/");

        if (res2->status == 200)
        {
            std::cerr << "Likely success." << std::endl;
        }
        else
        {
            std::cerr << "Likely failed." << std::endl;
        }
    });

    std::print("{0}\n", "Test Server is running on port 4288");
    srvACS.listen("0.0.0.0", 4288);
}
```
And it seems to work...
<img width="1397" alt="image" src="https://github.com/user-attachments/assets/96bd6754-a806-4f02-90ac-3b115ad75dcb" />

This is strange... In my main project it only happens on the Post. But the debugger tells me, all variables are filled as strings. 
It makes no sense to me. But seems like httplib.h under C++23 is not the issue here, otherwise the test program would've failed as well...

**Comment by Aebian** [comment]
Okay found the reason for the crash. I passed along the request and response as references and not directly and it seems those were already destroyed by the time my other code kicked in. 

Thanks for the help!
