### ISSUE TITLE
Infinite loop in 'set_chunked_content_provider' lambda when reload page

### ISSUE THREAD

**Issue by sitesv** [yhirose/cpp-httplib#2007]
Hi! 
ver. 0.18.3
Trying to use ssesrv.cc example.
And I in stuck... 
I see an infinite loop in 'set_chunked_content_provider' lambda when reload page.
What is going wrong?

![2024-12-17_16-56-13](https://github.com/user-attachments/assets/3684dd44-0c34-4acb-b50e-f27bd7371b99)

`const auto html = R"(
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>SSE demo</title>
</head>
<body>
<script>
const ev1 = new EventSource("event1");
ev1.onmessage = function(e){
  console.log('ev1',e.data);
}
const ev2 = new EventSource("event2");
ev2.onmessage = function(e){
  console.log('ev2',e.data);
}
</script>
</body>
</html>
)";

int main() {
	cout << CPPHTTPLIB_VERSION << endl;
	uint64_t ev1_id = 0;

	httplib::Server svr;
	if(!svr.is_valid()){
		std::cout << "server has an error..." << std::endl;
		return -1;
	}

	svr.Get("/",[&](const Request &/*req*/, Response &res){
		res.set_content(html,"text/html");
	});

	EventDispatcher ed;
	svr.Get("/event1", [&](const Request & /*req*/, Response &res){
		cout << "connected to event1..." << endl;
		res.set_chunked_content_provider("text/event-stream", [&](size_t offset, DataSink &sink){
			cout << "set_chunked_content_provider " << ev1_id++ << endl;
			ed.wait_event(&sink);
			return true;
		});
	});

	thread t([&]{
		int id = 0;
		while(true){
			this_thread::sleep_for(chrono::seconds(5));
			cout << "send event: " << id << std::endl;
			std::stringstream ss;
			ss << "data: " << id << "\n\n";
			ed.send_event(ss.str());
			id++;
		}
	});
	svr.listen("0.0.0.0", 8080);
	return 0;
}`

**Comment by yhirose** [comment]
@sitesv thanks for the report, but I don't have time to debug your code... I suggests to use ssesvr.cc as it is without making any change, and see if it works. (I confirmed it works with request from ssecli and a browser on localhost:1234.)

**Comment by sitesv** [comment]
> @sitesv thanks for the report, but I don't have time to debug your code... I suggests to use ssesvr.cc as it is without making any change, and see if it works. (I confirmed it works with request from ssecli and a browser on localhost:1234.)

thank you for fast answer. your code works fine. 
found a bug in my version.
