### ISSUE TITLE
get given path in url and save it as string

### ISSUE THREAD

**Issue by Golpe82** [yhirose/cpp-httplib#202]
Hi!
i am using this library and trying to solve something since  a couple days ago.
I have something like this:

`Server svr;

  svr.Get("/1/1/1", [](const Request& req, Response& res) {
        res.set_content("Hello World!", "text/plain");
    });`
My Request is in this form: http://<Socket>/1/1/1
the path /1/1/1 represents an address, that runs a subprocess.
I have a csv file as database where are all this adresses (/x/x/x).
I look up the .csv file in the body of the lambda function and call the corresponding subprocess.
My problem is that i would like to get the adress (path) of the request to look up in the file.
I thought i kann get it with req.path or req.target. but it is not possible cause the req object will be created IF the first argument of get function "/1/1/1" is given.

How can i get the given path in the request and pass it to the lambda function?
or
how can i get the given path in the request and save it in a string?

i hope u understand me...

thanks!

**Comment by PixlRainbow** [comment]
your request URL is wrong. Your server is set up correctly but you have omitted the "host" part of the URL on the client side.

![URL structure](https://vijaybhabhor.com/wp-content/uploads/2016/01/1-url-structure-query-parameter.jpg)

You said your request is in the form `http:///1/1/1`. You have included the protocol and the path, but left out the "host" (IP address, hostname or "localhost" if running locally) which is mandatory.

**Comment by PixlRainbow** [comment]
If you intended to have the path be variable numbers on the server GET handler, look into using regex expressions. There is an example in [README.md](https://github.com/yhirose/cpp-httplib/blob/master/README.md#server-example) with the path that starts with `R`

**Comment by Golpe82** [comment]
Thanks! I didnt type hier the Host but i used It ( It has a Typo) (127.0.0.1:1234/1/1/1).
I Will Take a look to the example with regex...

**Comment by yhirose** [comment]
@Golpe82, hope the answer from @PixlRainbow helps. @PixlRainbow, thanks for the detailed information. I'll make it 'close'.

**Comment by Golpe82** [comment]
It helped!
Thank u very much!
