### ISSUE TITLE
Does it support Windows xp？

### ISSUE THREAD

**Issue by jiagushuai** [yhirose/cpp-httplib#205]
+ Run listen on xp and quit
![image](https://user-images.githubusercontent.com/29997741/62844979-a6080c00-bcf7-11e9-96b7-2466dfa25a68.png)
+ The results are as follows
![image](https://user-images.githubusercontent.com/29997741/62844996-b02a0a80-bcf7-11e9-8470-6244922503fb.png)
+ Works fine in Windows 10
![image](https://user-images.githubusercontent.com/29997741/62845017-d6e84100-bcf7-11e9-8856-c35fd570e84f.png)

**Comment by yhirose** [comment]
No, it doesn't.
