### ISSUE TITLE
Fails to build with OpenSSL enabled on Windows using MinGW-w64 32-bit compiler version 8.1

### ISSUE THREAD

**Issue by thekvs** [yhirose/cpp-httplib#210]
Compilation process fails with the following error:

```
In file included from C:\Users\expadmin\Work\cpp-httplib-example\src\client1.cpp:4:
C:/Users/expadmin/Work/cpp-httplib-example/build/third_party/httplib/install/include/httplib/httplib.h: In member function 'bool httplib::SSLClient::verify_host_with_subject_alt_name(X509*) const':
C:/Users/expadmin/Work/cpp-httplib-example/build/third_party/httplib/install/include/httplib/httplib.h:3255:7: error: 'inet_pton' was not declared in this scope
   if (inet_pton(AF_INET6, host_.c_str(), &addr6)) {
       ^~~~~~~~~
C:/Users/expadmin/Work/cpp-httplib-example/build/third_party/httplib/install/include/httplib/httplib.h:3255:7: note: suggested alternative: 'inet_ntoa'
   if (inet_pton(AF_INET6, host_.c_str(), &addr6)) {
       ^~~~~~~~~
       inet_ntoa
```

**Comment by yhirose** [comment]
@thekvs, thanks for the report. What version of OpenSSL are you using?

**Comment by thekvs** [comment]
I used this OpenSSL binaries: https://bintray.com/vszakats/generic/download_file?file_path=openssl-1.1.1c-win32-mingw.zip (advized on the official OpenSSL site https://wiki.openssl.org/index.php/Binaries)

**Comment by yhirose** [comment]
It is because MinGW doesn't `inet_ntoa`. Same as https://github.com/yhirose/cpp-httplib/issues/60.

**Comment by thekvs** [comment]
Is some sort of workaround possible? We need a simple http client with OpenSSL & zlib (and ideally with keep-alive) support for Windows and your project seems very promising. Unfortunately we can't change compiler.

**Comment by yhirose** [comment]
@thekvs,It seems to fix the build error to use `getaddrinfo` instead of `inet_pton`. When I am not  busy, I'll take a look at it, and may ask you to verify the fix since I am not using MinGW on my Windows. Of course a pull request from you or others is always welcome!

**Comment by yhirose** [comment]
@thekvs, I just disable a part of `verify_host_with_subject_alt_name` which depends on `inet_pton`. The latest code should work with MinGW. Could you check on your machine? Thanks!

**Comment by thekvs** [comment]
Now it compiles Ok with MinGW.

Thanks!

Just a quick question: https will still work with this change?

**Comment by yhirose** [comment]
Glad to hear that!

The https communication still works. But as you can see in my change at https://github.com/yhirose/cpp-httplib/commit/bdbfc6cfe744c5615861fda39e74f860e5405cd6, it can no longer accept an IP address string such as '172.0.0.1'. You always have to use a domain name such as 'localhost' or 'google.com'.
