### ISSUE TITLE
cpp-httplib should use poll() instead of select() due to FD_SETSIZE limit

### ISSUE THREAD

**Issue by tv1wnd** [yhirose/cpp-httplib#215]
Hi,

on Linux FD_SETSIZE is hardcoded to fds < 1024
in an program where a lot of file descriptors are used (e.g. many boost::asio instances) that might lead to fd exhaustion 

I made a quick'n dirty patch (against release 0.2.4) which enables poll() through #define CPPHTTPLIB_USE_POLL for reads

It works on linux/windows, but I unfortunately haven't had the time to thoroughly test it and properly merge it

Cheers

attached diff
[httplib.h.diff.txt](https://github.com/yhirose/cpp-httplib/files/3615364/httplib.h.diff.txt)

**Comment by yhirose** [comment]
@tv1wnd, thank you for the contribution. Could you at least test it with the unit test on your Linux environment for me? (`cd test && make`) Thanks!

**Comment by tv1wnd** [comment]
@yhirose  ... looks OK so far 
for OpenSSL I used the Version supplied by vcpkg though (see attached Makefile)
OS was Ubuntu 19.04 

Cheers

[----------] Global test environment tear-down
[==========] 93 tests from 22 test cases ran. (35810 ms total)
[  PASSED  ] 93 tests.

[Makefile.txt](https://github.com/yhirose/cpp-httplib/files/3617123/Makefile.txt)

**Comment by yhirose** [comment]
@tv1wnd, thanks for the report. Another question. I saw the following code which tries to support Windows.

```cpp
#ifdef CPPHTTPLIB_USE_POLL
#define poll WSAPoll
#endif
````

Are you able to test on Windows as well? (Or did you do it already?) If it works on both Windows and Linux, I'll make this `poll` implementatin as the default behavior and leave the `select` implementation only for Mac OS. 

Thanks for your support!

**Comment by tv1wnd** [comment]
@yhirose 
Yes I did, but just using my own application
haven't encountered any issues so far

I would use 
#ifdef CPPHTTPLIB_USE_POLL
#define poll(fds,nfds,timeout) WSAPoll(fds,nfds,timeout)
#endif
instead though

I would make poll optional, since most use cases are covered by select anyway I think

Cheers

**Comment by yhirose** [comment]
@tv1wnd, I confirmed the PR #217 passed all the unit tests on Linux and Windows on CI and on macOS on my MacBook. (This is based on your patch, and I made one change to make it work on macOS.) So it seems to be a great improvement!

If the `poll` implementation has the advantage (no FD_SETSIZE limit) over `select` and it works on three environments with no problem, I would like to switch to it and get rid of the `select` implementation. Do you think If there is any particular situation that we really need the `select` implementation?

**Comment by tv1wnd** [comment]
Can't really think of any, except user choice or maybe some obscure embedded system where poll is not available/broken for some reason

Cheers

**Comment by yhirose** [comment]
OK. I'll leave the `select` implementation. Thanks for your fine contribution!
