### ISSUE TITLE
Error using SSLClient (possibly user error)

### ISSUE THREAD

**Issue by ihowell** [yhirose/cpp-httplib#219]
I am working on Mac OS X Mojave and the Clang Apple's clang version 10.0.1. I cannot get the SSLClient to work. I've created a minimal example program to verify my issue:

```
#include <iostream>
#include <string>
#include "httplib.h"

int main()
{
	httplib::SSLClient cli("https://google.com", 443);
	cli.enable_server_certificate_verification(false);

	auto response =
	    cli.Get("/", [&](const char * data, uint64_t data_length, uint64_t offset, uint64_t content_length) {
		    std::string body{data, data_length};
		    std::cout << "Receieved: " << body << std::endl;
		    return true;
	    });

	if (response == nullptr)
		std::cout << "Error occured" << std::endl;

	return 0;
}
```

With makefile:

```
all:
	clang++ main.cpp -g --std=c++17 -stdlib=libc++ -DCPPHTTPLIB_OPENSSL_SUPPORT -lssl -lcrypto
```

I get the output that an error occured, even though I'm not checking the certificate or anything. Upon further investigation I found that it goes wrong at line 1123. `getaddrinfo(host, service.c_str(), &hints, &result)` returns nonzero.

```
host = "https://google.com"
service.c_str() = "443"
hints = {
  ai_flags = 0
  ai_family = 0
  ai_socktype = 1
  ai_protocol = 0
  ai_addrlen = 0
  ai_canonname = nullptr
  ai_addr = nullptr
  ai_next = nullptr
}
```

I don't know much about networking, so I tried to provide as much information as possible.

Edit: Line number for master and compiler.

**Comment by ihowell** [comment]
I have since tested what the exact error `getaddrinfo` is spitting out. It is an `EAI_NONAME` error, which means that (https://linux.die.net/man/3/getaddrinfo):

The node or service is not known; or both node and service are NULL; or AI_NUMERICSERV was specified in hints.ai_flags and service was not a numeric port-number string.

I'm not sure how this is happening. I also tested with using `"https://www.google.com"` as the host, but that didn't change anything.

**Comment by ihowell** [comment]
I found the error. Apparently, including `https` in the host name causes `getaddrinfo` to fail. While I did find a work-around, I'm curious as to know what you would think should be the standard for this library.

**Comment by yhirose** [comment]
Thanks for the reports. Here are the constructors of `Client` and `SSLClient`. As you can see, the first parameter of them should be a host name such as `google.com`.

```cpp
  Client(const char *host, int port = 80, time_t timeout_sec = 300);
```
```cpp
  SSLClient(const char *host, int port = 443, time_t timeout_sec = 300,
            const char *client_cert_path = nullptr,
            const char *client_key_path = nullptr);
```

 `https://google.com` contains not only host name, but URL scheme (https) as well. That's why your example fails.

You can also see tons of client examples in `test/test.cc`.
