### ISSUE TITLE
Header file conflict code bug

### ISSUE THREAD

**Issue by HeMinzhang** [yhirose/cpp-httplib#220]
```c++
//reappear bug
#include <openssl/sha.h>
#include <openssl/aes.h>
#include <openssl/evp.h>
#ifndef CPPHTTPLIB_OPENSSL_SUPPORT
#define CPPHTTPLIB_OPENSSL_SUPPORT
#endif
#include <httplib.h>
```

the conflict between the above code and the [httplib project](https://github.com/yhirose/cpp-httplib)
[reappear bug example](https://github.com/HeMinzhang/opensslbug/blob/master/src/makeBug/main.cpp)

[openssl github issue](https://github.com/openssl/openssl/issues/9981)

[httplib github issue](https://github.com/yhirose/cpp-httplib/issues/220)

[Previous discussion in qt bugreport](https://bugreports.qt.io/browse/QTBUG-78642)

**Comment by yhirose** [comment]
@HeMinzhang, thanks for the report. But it's not clear to me Could you explain more details? Thanks.

**Comment by HeMinzhang** [comment]
[vs2019 c++ demo bug](https://github.com/HeMinzhang/opensslbug/blob/master/vs_src/ConsoleApplication1/ConsoleApplication1/ConsoleApplication1.cpp) 

When the project references both the openssl and httplib codebases, the following code will cause an error.

```c++
//reappear bug
#include <openssl/sha.h>
#include <openssl/aes.h>
#include <openssl/evp.h>
#ifndef CPPHTTPLIB_OPENSSL_SUPPORT
#define CPPHTTPLIB_OPENSSL_SUPPORT
#endif
#include <httplib.h>
```

**Comment by yhirose** [comment]
What version of openssl are you using in your project?

**Comment by PixlRainbow** [comment]
Does `#pragma once` fix the issue?

**Comment by PixlRainbow** [comment]
Do not `#include` OpenSSL headers if you are already referencing httplib.

**Comment by yhirose** [comment]
@HeMinzhang, I confirmed that it doesn't happen on Mac OS, and looked into the OpenSSL header files. It turns out that the following Windows specific code causes the compile errors.

https://github.com/openssl/openssl/blob/7c2a981ff7ca721a85687dcd972d54361434806f/include/openssl/ossl_typ.h#L68-L75

So I cannot do anything on my side. As @PixlRainbow, only thing you could do is not to include any OpenSSl headers before `httplib.h`. Sorry about that. Hope it helps.

**Comment by HeMinzhang** [comment]
@yhirose @PixlRainbow Thank you.

**Comment by HeMinzhang** [comment]
I have found a solution before. For c++ projects, avoid putting openssl and httplib into the class header file (.h, .hpp) to avoid this bug.
