### ISSUE TITLE
Concurrent access

### ISSUE THREAD

**Issue by andre237** [yhirose/cpp-httplib#229]
Does the library handles concurrent requests or should I myself synchronize access to resources inside each handler?

**Comment by yhirose** [comment]
@andre237, thanks for the question. Your question is not too clear to me though, I'll try to do my best to answer the question. The cpp-httplib server itself can accept concurrent requests as many as the thread pool can handle. (You can confirm with the Apache Bench utility and so on.) But the resource handling like reading files is a totally another issue. If resources are mutable, they should be protected with mutex or other synchronization mechanism. Hope it helps!

**Comment by andre237** [comment]
Indeed it helped, I was referring to file reading/writing within a request. Will make them synced from now on. Thanks for the support!
