### ISSUE TITLE
File response problem (image)

### ISSUE THREAD

**Issue by naimGur** [yhirose/cpp-httplib#235]
Hello, I am having problem with responding with file. I am trying to send image as response with the function `res.set_content();`
The image I am trying to send is base64 presentation of a picture:
` std::string binary_image = "data:image/png;base64,iVBORw0KG..........................kSuQmCC";`
I produced `binary_image` variable by converting a small png image(16x16) into base64 string. I double checked that it is formal base64 image. I use the function like below: 
`res.set_content(binary_image, "image/png");`
And I get a broken image on my browser. Headers and Content-length are right. But image is not there. What am I doing wrong in here? Any advice or example code snippet for usage of image response would be really helpful. Thanks :-)

**Comment by PixlRainbow** [comment]
Browsers do not automatically decode content served in base64 encoding if it is served in the response body. Since the `content-type` is `image/png`, your browser expected to find a binary png image.
Browsers only decode base64 if provides one as an **URL**

**Comment by naimGur** [comment]
Sending `<img src="base64_string">` as `text/html` worked. Thanks for quick and precise reply!

**Comment by PixlRainbow** [comment]
if you feel that the issue is resolved, please click on "close issue"

**Comment by naimGur** [comment]
Actually `text/html` method worked, but my use case is blocked when `html` handles image. I had to send image directly to browser. So I tried to use the other method which is to send `.raw` as binary string. But I could not do that by the reason of my lack of understanding on general subject. Could you please explain the solution with a more explicit or algorithmic way? Or can you provide a document or code implementation?

**Comment by PixlRainbow** [comment]
@naimGur alternatively, a simpler example. Notice that there is *no encoding*. The file data is read and immediately sent.
```cpp
#include <fstream>
#include <sstream>
#include <string>
#include <httplib.h>
constexpr const char* filename = "example.png";
......
......
server.Get("/test", [](const http::Request&, http::Response& res){
    std::ifstream in(filename, std::ios::in | std::ios::binary);
    if(in){
        std::ostringstream contents;
        contents << in.rdbuf();
        in.close();
        res.set_content(contents.str(), "image/png");
    }else{
        res.status = 404;
    }
});
......
......
```
