### ISSUE TITLE
Complicated url won't work.

### ISSUE THREAD

**Issue by d1kkop** [yhirose/cpp-httplib#238]
This link works in browser:

https://research.geodan.nl/geoserver/research/wms?service=WMS&version=1.1.0&request=GetMap&LAYERS=research:bgt&BBOX=122000,447000,123000,448000&WIDTH=1024&HEIGHT=1024&FORMAT=image/png&srs=EPSG:28992&FORMAT_OPTIONS=antialias:none

But not from code.
To confirm that the code is correct, I ripped a host and url from one of your test schemes, which does indeed work.

![image](https://user-images.githubusercontent.com/10207653/66783093-7df37f80-eed7-11e9-96af-6a7f875eb98e.png)

**Comment by yhirose** [comment]
@d1kkop, thanks for the feedback. Your URL uses 'https' scheme. Could you try again with `httplib::SSLClient` to see what's going to happen instead of `httplib::Client`? (You need to install OpenSSL library to build the code.)

**Comment by PixlRainbow** [comment]
Just a note: `Content-Type` header is ignored by servers if included in `GET` requests, since `GET` requests do not have a content body. If you want to indicate to the server what type of data you would *prefer* to receive, use the `Accept` header

**Comment by PixlRainbow** [comment]
Also, to use `SSLClient` you need to build with `#define CPPHTTPLIB_OPENSSL_SUPPORT`

**Comment by d1kkop** [comment]
![image](https://user-images.githubusercontent.com/10207653/66863267-eb181b00-ef92-11e9-9b19-db42c240b402.png)

No luck.
I tried for the host both with and without https:// in front.
I noticed this was necessary when using 'normal' Client (remove the http in front).
If you concat the host + url and put https:// in front, it works in the browser.
Furthermore, there are some compile errors and warnings.
Perhaps the code was compiled with warning level 3 instead of 4?

**Comment by yhirose** [comment]
What happens with curl?

**Comment by yhirose** [comment]
I tried with the following code:

```cpp
#include <httplib.h>
#include <iostream>

using namespace std;

int main(void) {
  httplib::SSLClient cli("research.geodan.nl");

  auto res = cli.Get("/geoserver/research/wms?service=WMS&version=1.1.0&request=GetMap&LAYERS=research:bgt&BBOX=121893.000000,487418.000000,122021.000000,487546.000000&WIDTH=1024&HEIGHT=1024&FORMAT=image/png&srs=EPSG:28992&FORMAT_OPTIONS=antialias:none");

  if (res) {
    cout << res->status << endl;
    cout << res->get_header_value("Content-Type") << endl;
    // cout << res->body << endl;
  }

  return 0;
}
```

I got this result successfully:

```
200
image/png
```

Hope it helps.

**Comment by d1kkop** [comment]
![image](https://user-images.githubusercontent.com/10207653/66865725-223cfb00-ef98-11e9-8c3a-a0ad5afc1fa9.png)

**Comment by d1kkop** [comment]
> I tried with the following code:
> 
> ```c++
> #include <httplib.h>
> #include <iostream>
> 
> using namespace std;
> 
> int main(void) {
>   httplib::SSLClient cli("research.geodan.nl");
> 
>   auto res = cli.Get("/geoserver/research/wms?service=WMS&version=1.1.0&request=GetMap&LAYERS=research:bgt&BBOX=121893.000000,487418.000000,122021.000000,487546.000000&WIDTH=1024&HEIGHT=1024&FORMAT=image/png&srs=EPSG:28992&FORMAT_OPTIONS=antialias:none");
> 
>   if (res) {
>     cout << res->status << endl;
>     cout << res->get_header_value("Content-Type") << endl;
>     // cout << res->body << endl;
>   }
> 
>   return 0;
> }
> ```
> 
> I got this result successfully:
> 
> ```
> 200
> image/png
> ```
> 
> Hope it helps.

With the exact same hard coded lines, i get empty response, lol.

**Comment by yhirose** [comment]
If `SSL_connect` returns `-1`, this problem has nothing to do with cpp-httplib itself and I can't help you any more... Only thing that I could suggest is to make sure that the OpenSSL library that you are using is properly installed (I am using the OpenSSL 1.1.1d.) and your executable is allowed to make outgoing HTTPS request on your machine. If there is no problem on your OpenSSL setting, you may want to use https://github.com/oktal/pistache instead of cpp-httplib. Sorry for causing the inconvenience.

**Comment by d1kkop** [comment]
You are absolutely right. No problem man:)

Op di 15 okt. 2019 23:25 schreef yhirose <notifications@github.com>:
