### ISSUE TITLE
Error in README.md sample code

### ISSUE THREAD

**Issue by acreskeyYouI** [yhirose/cpp-httplib#24]
Great library -- one issue is that the sample code in the README.md doesn't compile because 
the parameters `const Response& res` are actually supposed to be non-const:  `Response& res`

```
svr.get("/hi", [](const Request& req, const Response& res) {
        res.set_content("Hello World!", "text/plain");
    });
```
and
```
    svr.get(R"(/numbers/(\d+))", [&](const Request& req, const Response& res) {
        auto numbers = req.matches[1];
        res.set_content(numbers, "text/plain");
    });
```

**Comment by yhirose** [comment]
@acreskeyYouI, thank you for finding the stupid mistake... I'll correct it right away.

**Comment by yhirose** [comment]
I just found that you made a pull request already. Thanks for your contribution!

**Comment by acreskeyYouI** [comment]
Awesome!
