### ISSUE TITLE
streaming post requests in http server

### ISSUE THREAD

**Issue by sophana** [yhirose/cpp-httplib#241]
Hi

I'd like the server to handle huge post requests like big file uploads.
I'm looking at the source, and it seems that in process_request, read_content reads the whole request body and loads it into a string, before calling the request handler.

It would have been nice if the handler could register a content receiver. 

I made a pull request where you can register a streamHandler, the handler receives an additionnal argument which is the stream, and it is called before the request body is read.
It is the handler that reads the request body.
The simpleSvr example is updated with a stream handler.

Thanks

**Comment by PixlRainbow** [comment]
referenced PR: #242

**Comment by yhirose** [comment]
@sophana, thank you for bringing up this thing. I'll try to implement it when I have time.

**Comment by sophana** [comment]
Ok thanks. 
I also have the same problem on the client side post.
I also need to upload very large files with on the fly gzipping to the server.
Curl doesn't perform gzipping. I can pipe the file through gzip to curl, but unfortunately, it seems that curl must store the whole file before sending it on the network, probably because it must compute the size before sending it.

The client doesn't accept a content provider for Post request.

I also corrected a small bug in the decompressor which doesn't work with large splitted (multiple socket read) body. The inflate return value is 0 when the decompression is not over, then it goes to 1 (STREAM_END) for the last packet. So Decompressor::decompress should return true at the end.

I tested with a server that computes md5 of posted files, and tested hundred of megabytes files uploads with curl (gzipped and not)

**Comment by yhirose** [comment]
@sophana, thanks for the reply. Could you make a pull request about your bug fix for the decompressor bug, since it's a separat issue?

> I also corrected a small bug in the decompressor which doesn't work with large splitted (multiple socket read) body. The inflate return value is 0 when the decompression is not over, then it goes to 1 (STREAM_END) for the last packet. So Decompressor::decompress should return true at the end.
> 
> I tested with a server that computes md5 of posted files, and tested hundred of megabytes files uploads with curl (gzipped and not)

**Comment by PixlRainbow** [comment]
> The client doesn't accept a content provider for Post request.
Added in 5f32c424c2d819a74bf00851b1fb5e1b28a88e57

**Comment by yhirose** [comment]
Yes, I implemented the feature to accept a content provider for Post/Put/Patch requests.
When it comes to content receiver on server handler, it's a bit more difficult to implement it properly. But I'll get back to you when it completes. Thanks for your patience!

**Comment by DaveBlakeman** [comment]
I independently found and fixed the same issue as @sophana:-

> I also corrected a small bug in the decompressor which doesn't work with large splitted (multiple socket read) body. The inflate return value is 0 when the decompression is not over, then it goes to 1 (STREAM_END) for the last packet. So Decompressor::decompress should return true at the end.

It's a bit of a showstopper for anyone implementing receipt of large compressed post data and took a bit of finding...

**Comment by yhirose** [comment]
@DaveBlakeman (also @sophana), could you make a pull request for the decompress problem, or show me the code snippet? I'll gladly merge it to the master, so that anyone could benefit from the fix. Thanks!

**Comment by sophana** [comment]
Please have a look at this commit in httplib:
https://github.com/sophana/cpp-httplib/commit/0423358b662076e8b1fa70ae7a63c59afd2727de

Please note that it could check 2 possible return values: I think they are Z_STREAM_END or Z_STREAM_OK
But there are enough error checks just before, I think.

**Comment by yhirose** [comment]
@sophana, thanks for the helpful information. Do you think if the following change works?

```cpp
    return ret == Z_OK || ret == Z_STREAM_END;
```

Also I would like to know how large a gzipped file should be to reproduce the problem? I'll make a unit test for the problem as well. Thanks for your great help!

**Comment by yhirose** [comment]
@sophana and @DaveBlakeman, since the decompressor problem is a different issue, I opened a separate issue #273. Please respond there regarding this matter. Thanks!

**Comment by yhirose** [comment]
I have finally supported the content receiver on server.
https://github.com/yhirose/cpp-httplib#receive-content-with-content-receiver
