### ISSUE TITLE
Request need long time

### ISSUE THREAD

**Issue by elli-one** [yhirose/cpp-httplib#245]
Hi,
When I POST a request to server (on local host) than the consumed time  is very long (> 1000ms). Normaly for raw socket communication I connect , send a request and receive the response < 10ms.
What is here the blocker ?
 elli

**Comment by yhirose** [comment]
@elli-one, thanks for the report. I don't know which one (server or client) you are talking about though, but I anyway tested performance on both sides on my MacBook.

As you can see my results below, both server and client perform pretty well. 
I feel something on your environment seems to be causing the slowness.
Hope you will find the reason why your result is slow soon!

#### Server

I have tested server performance with `example/hello.cc` server.

```
[master] ~/cpp-httplib/example$ ab -n12 -c4 http://localhost:1234/hi
This is ApacheBench, Version 2.3 <$Revision: 1826891 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient).....done


Server Software:        
Server Hostname:        localhost
Server Port:            1234

Document Path:          /hi
Document Length:        12 bytes

Concurrency Level:      4
Time taken for tests:   0.003 seconds
Complete requests:      12
Failed requests:        0
Total transferred:      1188 bytes
HTML transferred:       144 bytes
Requests per second:    4424.78 [#/sec] (mean)
Time per request:       0.904 [ms] (mean)
Time per request:       0.226 [ms] (mean, across all concurrent requests)
Transfer rate:          427.79 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:     0    1   0.1      1       1
Waiting:        0    1   0.1      1       1
Total:          1    1   0.1      1       1

Percentage of the requests served within a certain time (ms)
  50%      1
  66%      1
  75%      1
  80%      1
  90%      1
  95%      1
  98%      1
  99%      1
 100%      1 (longest request)
```

#### Client

I have tested client performance with `example/benchmark.cc`

```
[master] ~/cpp-httplib/example$ ./benchmark 
0: 85 millisec.
1: 27 millisec.
2: 58 millisec.
```

**Comment by elli-one** [comment]
Re: [yhirose/cpp-httplib] Request need long time (#245)



Hello,

sorry, your benchmark test run against a external HTTP implementation. !!
Not your own server.
What I use is the httplib server and httplib client implementation. Currently this
test is with Windows 7. Tomorrow I check with Linux.

elli






@elli-one, thanks for the report. I don't know which one (server or client) you are talking about though, but I anyway tested performance on both sides on my MacBook.
As you can see my results below, both server and client perform pretty well.
I feel something on your environment seems to be causing the slowness.
Hope you will find the reason why your result is slow soon!
Server
I have tested server performance with example/hello.cc server.
[master] ~/cpp-httplib/example$ ab -n12 -c4 http://localhost:1234/hi
This is ApacheBench, Version 2.3 <$Revision: 1826891 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient).....done


Server Software:        
Server Hostname:        localhost
Server Port:            1234

Document Path:          /hi
Document Length:        12 bytes

Concurrency Level:      4
Time taken for tests:   0.003 seconds
Complete requests:      12
Failed requests:        0
Total transferred:      1188 bytes
HTML transferred:       144 bytes
Requests per second:    4424.78 [#/sec] (mean)
Time per request:       0.904 [ms] (mean)
Time per request:       0.226 [ms] (mean, across all concurrent requests)
Transfer rate:          427.79 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:     0    1   0.1      1       1
Waiting:        0    1   0.1      1       1
Total:          1    1   0.1      1       1

Percentage of the requests served within a certain time (ms)
  50%      1
  66%      1
  75%      1
  80%      1
  90%      1
  95%      1
  98%      1
  99%      1
 100%      1 (longest request)
Client
I have tested client performance with example/benchmark.cc
[master] ~/cpp-httplib/example$ ./benchmark 

0: 85 millisec.

1: 27 millisec.

2: 58 millisec.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



 
	
      
		Virenfrei. www.avast.com

**Comment by yhirose** [comment]
OK. I modified `example/hello.cc` and 'example/benchmark.cc` to meet your situation as below:

#### example/hello.cc
```cpp
  // svr.Get("/hi", [](const Request & #<{(|req|)}>#, Response &res) {
  svr.Post("/post", [](const Request & /*req*/, Response &res) {
    res.set_content("Hello World!", "text/plain");
  });
```
#### example/benchmark.cc
```cpp
  // httplib::Client cli("httpbin.org", 80);
  httplib::Client cli("localhost", 1234);
```

Here is the result when executing the benchmark against the hello server:
```
[master] ~/cpp-httplib/example$ ./benchmark 
0: 6 millisec.
1: 3 millisec.
2: 3 millisec.
```

It's even much faster than accessing `httpbin.org`. Hope it helps.

**Comment by elli-one** [comment]
Re: [yhirose/cpp-httplib] Request need long time (#245)



Hallo,

yes, it make sense to show the speed for all access methods. Inbetween I have testet with
Linux and can see expected fast access. So this problem seems my system. This sounds a little
strange for me, but I have enough computer to test it.
This library is very nice and usefull !.
elli





OK. I modified example/hello.cc and 'example/benchmark.cc` to meet your situation as below:
example/hello.cc
  // svr.Get("/hi", [](const Request & #<{(|req|)}>#, Response &res) {
  svr.Post("/post", [](const Request & /*req*/, Response &res) {
    res.set_content("Hello World!", "text/plain");
  });
example/benchmark.cc
  // httplib::Client cli("httpbin.org", 80);

  httplib::Client cli("localhost", 1234);
Here is the result when executing the benchmark against the hello server:
[master] ~/cpp-httplib/example$ ./benchmark 

0: 6 millisec.

1: 3 millisec.

2: 3 millisec.


It's even much faster than accessing httpbin.org. Hope it helps.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



 
	
      
		Virenfrei. www.avast.com

**Comment by wantalgh** [comment]
I also encountered this problem in my code, and I found that as long as I use 127.0.0.1 instead of localhost, the request is no longer slow.
