### ISSUE TITLE
How to implement breakpoint continuous transmission of large files

### ISSUE THREAD

**Issue by ChineseBoyLY** [yhirose/cpp-httplib#249]
How to implement breakpoint continuous transmission of large files

**Comment by yhirose** [comment]
@ChineseBoyLY, thanks for the question. But I don't understand what you are exactly asking.
It seems like this is not a question for cpp-httplib, but a general question about HTTP. Sorry that I couldn't help you...

**Comment by PixlRainbow** [comment]
Please explain what you want. Do you want "streaming" http transfer? Why did you add the word "breakpoint"?
