### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG error from time to time

### ISSUE THREAD

**Issue by marty1885** [yhirose/cpp-httplib#259]
Hi,

I'm programming a wabapp using the library. The library works perfectly under HTTP. But Firefox starts to show the SSL_ERROR_RX_RECORD_TOO_LONG error when HTTPS is turned on. What can I be doing wrong?

Thanks.

OS: Arch Linux
libssl: 1.1.1.d-1
Compiler: GCC 9.2.0
Linux: 5.1.4
Cert Issuer: Gandi

**Comment by yhirose** [comment]
@marty1885, thank you for the report. I did some research, but it seems there is little to do on cpp-http side. The following article may be helpful for you to find the actual cause of the problem.
https://www.thesslstore.com/blog/ssl_error_rx_record_too_long/
Could you make sure if your server settings are ok, such as port number and SSL version?

**Comment by PixlRainbow** [comment]
Other potential issues may be that your browser has cached a certificate from a previous project on the same address, or that your site certificate has been created in a way that isn't compatible with browser use.

**Comment by yhirose** [comment]
Please let me know if you find something which really shows cpp-httplib causes the problem. Thanks!
