### ISSUE TITLE
How about Websocket support

### ISSUE THREAD

**Issue by tabvn** [yhirose/cpp-httplib#260]
@yhirose i must say you did great job.
i 'm also a fan of c++, if this library support you could create a demo how websocket support.
i really like to use it plus with redis to create scalable pubsub  websocket for next project.
Thank you and keep up the good work.

Best regards,
Toan

**Comment by yhirose** [comment]
@tabvn, thank you for the feedback! cpp-httplib doesn't support websocket, and I am not planning to support it at this point. If you need 'event push' from server to client, you can use 'long polling' technique or SSE. Hope it helps.
https://github.com/yhirose/cpp-httplib/issues/233

**Comment by kingdudely** [comment]
https://github.com/yhirose/cpp-httplib/blob/master/README-websocket.md
