### ISSUE TITLE
SSL Client Constructors & type of response

### ISSUE THREAD

**Issue by mnik17** [yhirose/cpp-httplib#264]
Hi,

I checked the examples in the README but I still have a few questions related to the syntax. Basically I want to make an https request and I found out in previous issues that I ought to use an `httplib::SSLClient`. However I don't want to provide the url immeadiately. This is because I want to declare the client as a class parameter and then initialize it in the constructor. Is this possible or if not could you suggest a workaround? And a further question: if I use the constructor like this:
```
httplib::SSLClient cli("https://my.site");
auto res = cli.Post("/directory1/subdirectory2","text","plain_text");
```
am I actually accessing` https://my.site/directory1/subdirectory2`?

My second question is related to the response. The server is supposed to give me a response in the form of a JSON. Since the `res` variable in the examples was always set to auto I'm not entirely sure what to expect. I would assume that the reponse will be saved in a string, so I tried declaring `res` as string since I can't use auto in the class declaration, but of course it doesn't compile. Any suggestions?

Regards

**Comment by yhirose** [comment]
Thank you for asking the questions. I probably don't understand fully what you meant with your questions... But at least I can tell that `httplib:SSLClient` should take 'hostname' instead of URL (Also 'text_plain' is not a valid MIME type). Your example should be like this:

```cpp
httplib::SSLClient cli("my.site");
auto res = cli.Post("/directory1/subdirectory2","text","text/plain");
```

When it comes to `auto`, this is a C++11 feature, and it is same as `std::shared_ptr<httplib::Response>`.

Hope the explanation helps.

**Comment by mnik17** [comment]
Hi,

thanks for the quick response. I'll try to explain my question better: I wanted to use the client this way:
```
class MyClass {
   httplib::SSLClient cli;
   MyClass(std::string hostname){
      cli.host= hostname;
   }
```

i.e. I wanted to give the url in the constructor of my class. I checked the source code of the library and found only one constructor of the `SSLClient` class, namely:

```
 SSLClient(const char *host, int port = 443, time_t timeout_sec = 300,
            const char *client_cert_path = nullptr,
            const char *client_key_path = nullptr);

```
i.e. what I was asking for is not possible with the current implementation(or at least that's what I think). Is it going to be time consuming to implement such a feature?

**Comment by PixlRainbow** [comment]
@mnik17 
```cpp
class MyClass {
    httplib::SSLClient cli;
    MyClass(std::string hostname) : cli(hostname.c_str()) {}
}
```
Note:
1. If sending repeated requests to the same host, the same Client/SSLClient object can be reused
2. If sending to a new host, Client/SSLClient must be re-constructed. You can safely overwrite the old variable with a new Client/SSLClient like so `cli = httplib::SSLClient(newHostname);` as long as you have made sure to copy the downloaded data you need beforehand.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the clear answer.
