### ISSUE TITLE
Please provide remote address to see the IP address from caller. (server side)

### ISSUE THREAD

**Issue by elli-one** [yhirose/cpp-httplib#265]
Hi,
I cannot see any function like getpeerName() to get the address from remote caller. I would be fine
when this address is accessable in struct Request.

regards

**Comment by yhirose** [comment]
Thank you for the request. It's already in the headers in Request (#41):

https://github.com/yhirose/cpp-httplib/blob/9d5789935294564be8c72f8f74a578bdfe7d3908/test/test.cc#L578-L582

Hope it helps.

**Comment by elli-one** [comment]
Re: [yhirose/cpp-httplib] Please provide remote address to see the IP address from caller. (server side) (#265)



Hi,
ok, thanks. Yes make sense the HTTP way and not sockets.
regards





Thank you for the request. It's already in the headers in Request (#41):
https://github.com/yhirose/cpp-httplib/blob/9d5789935294564be8c72f8f74a578bdfe7d3908/test/test.cc#L578-L582
Hope it helps.
