### ISSUE TITLE
Approach for single threaded server?

### ISSUE THREAD

**Issue by strangelookingnerd** [yhirose/cpp-httplib#268]
Hello there,

I embedded the httplib server into an extension point of an existing application in order to be able to execute certain routines like so:

Main application -> load DLL with exposed entry point -> start httplib server -> listen to requests -> process request (e.g calls to main application)

This works really well for the most part - however the fact that certain routines are executed outside of the main thread via the request handlers of httplib leads to problems for the application and I can't seem to work around that (easy put: not my code, can't change a thing about it...).
I validated this issue by switching to a single threaded server implementation (mongoose) and suddenly the before faulty routines worked just fine. 
However I was really happy with using httplib over mongoose as it is waaaaaaay easier to work with for me. Just a heads up: It has been a while since I last tried myself on any C++ so please bear with me ;)

Anyway I was looking into a way of making httplib server single threaded and have no clue where to start or if this is even possible. Any help is appreciated!

**Comment by yhirose** [comment]
@strangelookingnerd, thanks for the feedback. Unfortunately, cpp-httplib is a '**multi-threaded, synchronous, blocking**' server, whereas mongoose is '**single-threaded, asynchronous, non-blocking**'...

Of course we can make httplib.h 'single-threaded', but it can never be 'asynchronous, non-blocking', and the change may cause a bad performance problem when the server receives tons of requests simultaneously. So I don't recommend to do so, but here is a way to make a 'single-threaded, synchronous, blocking' server just in case you don't need to worry about the performance issue too much. 

1) Add the following class in `httplib.h':

```cpp
class SingleThread : public TaskQueue {
public:
  SingleThread() {}
  virtual ~SingleThread() {}
  virtual void enqueue(std::function<void()> fn) override { fn(); }
  virtual void shutdown() override {}
};
```

2) Modify `Server::Server()` to use the above task queue

```cpp
// HTTP server implementation
inline Server::Server()
    : keep_alive_max_count_(CPPHTTPLIB_KEEPALIVE_MAX_COUNT),
      read_timeout_sec_(CPPHTTPLIB_READ_TIMEOUT_SECOND),
      read_timeout_usec_(CPPHTTPLIB_READ_TIMEOUT_USECOND),
      payload_max_length_(CPPHTTPLIB_PAYLOAD_MAX_LENGTH), is_running_(false),
      svr_sock_(INVALID_SOCKET) {
#ifndef _WIN32
  signal(SIGPIPE, SIG_IGN);
#endif
  new_task_queue = [] {
    return new SingleThread();
  };
}
```

Hope it helps.

**Comment by strangelookingnerd** [comment]
@yhirose Thank you so much for your help! 

For my use case I'm not too concerned about performance. The underlying application can only process a single request at a time anyway - so single-threaded, synchronous, blocking is basically exactly what I'm locking for.

Your changes got my problem fixed, I really can't thank you enough.
Keep up the excellent work, really appreciated!

**Comment by yhirose** [comment]
@strangelookingnerd, thanks for the reply. I actually added it to httplib.h.

If you download the latest httplib.h and change the following line to ` #define CPPHTTPLIB_THREAD_POOL_COUNT -1 `, the server works with 'No Thread' task queue.

https://github.com/yhirose/cpp-httplib/blob/d45676b0642883f6ef015c6d4f91b920efe2bc11/httplib.h#L52
