### ISSUE TITLE
Fail to route on empty querystring with `?`

### ISSUE THREAD

**Issue by utatti** [yhirose/cpp-httplib#270]
Reproduction:

1. Prepare a simple server
  ```
  srv.Get("/", ...);
  ```
2. Access `http://hostname/?`
3. It returns 404.
  + Expected: 200 and the rendered page.

Even if the URL is with only `?` at the end, it should handle it as an empty querystring.

**Comment by yhirose** [comment]
@utattil thanks for finding the bug. Could you try with the latest httplib.h?

**Comment by utatti** [comment]
Worked. Thanks!
