### ISSUE TITLE
CRLF/LF change on parsing POST body

### ISSUE THREAD

**Issue by utatti** [yhirose/cpp-httplib#271]
Reproduce:

1. Send a POST param value with newlines (for example using `<textarea>`).
2. Check the body and the param value.

```c++
req.body.find("\r\n") != std::string::npos // this will be false (no CRLF)
req.get_param_value("foo").find("\r\n") != std::string::npos // this will be true (CRLF)
```

It seems the library force-changes all the LF's in the body to CRLF's. Can we keep the original value after parsing?

**Comment by yhirose** [comment]
@utatti, thanks for the feedback. After the library receives data, it keeps it as it is in `req.body` without touching it. The library doesn't modify the data in `req.body` when parsing the 'application/x-www-form-urlencoded' data as well.

You can see what the library actually does in the following functions.

https://github.com/yhirose/cpp-httplib/blob/d8da740597e3ab400f2939864fbed1255a048f1d/httplib.h#L2645-L2672

https://github.com/yhirose/cpp-httplib/blob/d8da740597e3ab400f2939864fbed1255a048f1d/httplib.h#L1824-L1837

I would like to know more about the problem you experienced. Could you explain more detail? Thanks!

**Comment by PixlRainbow** [comment]
@utatti wait, is your form submitted as url-encoded or multipart? If your form was submitted as url-encoded, the CRLF will be escaped into the readable characters `%0D%0A` instead of the binary literals, and thus will not be detected by `find("\r\n")`.

based on my testing, manually forcing the form to be multipart by adding the attribute `enctype='multipart/form-data'` to the `<form>` element will cause your test `req.body.find("\r\n") != std::string::npos` to return `true`

demo:
```cpp
#include <httplib.h>
#include <string>
namespace http = httplib;
int main(){
        http::Server srv;
        srv.Post("/", [](const http::Request &req, http::Response &res){
                std::string content;
                if(req.body.find("\r\n") != std::string::npos)
                        content = "found CRLF";
                else
                        content = "did not find CRLF";
                res.set_content(content,"text/plain");
        });
        srv.Get("/", [](const http::Request &req, http::Response &res){
                //the following defaults to URL-encoded -- CRLF has been escaped to %0D%0A
                //std::string content = "<form method='post' id='form1'>";
                //the following forces multipart encoding and thus literal binary CRLF
                std::string content = "<form method='post' id='form1' enctype='multipart/form-data'>";
                content += "<input type='password' name='pass'>";
                content += "<textarea form='form1' name='name2'></textarea>";
                content += "<input type='submit'>";
                content += "</form>";
                res.set_content(content, "text/html");
        });
        srv.listen("localhost",8000);
}
```
**Result:**
`found CRLF`

**Comment by utatti** [comment]
It makes sense. I'll check it out again.

**Comment by utatti** [comment]
I'm very sorry that this was my mistake. I didn't know that newlines in  `textarea` are encoded as CRLF by default.

https://www.w3.org/MarkUp/html-spec/html-spec_8.html#SEC8.2.1
