### ISSUE TITLE
binary file data

### ISSUE THREAD

**Issue by RemoteSensingFrank** [yhirose/cpp-httplib#272]
Hi！ I post a formdata like 
![image](https://user-images.githubusercontent.com/25923674/69688299-9ffc3680-1100-11ea-8ba2-813ec67d7f42.png)
but i don't know how to the binary file data，when I use the code like
![image](https://user-images.githubusercontent.com/25923674/69688463-1862f780-1101-11ea-8c84-808102ce677b.png)

I can get other parameters but when I get the file the size of the file is only 16 bytes

**Comment by yhirose** [comment]
@RemoteSensingFrank, thanks for the feedback. How did you send the post message? From a web browser, or curl?

**Comment by RemoteSensingFrank** [comment]
from web browser chrome发自我的华为手机-------- 原始邮件 --------主题：Re: [yhirose/cpp-httplib] binary file data (#272)发件人：yhirose 收件人：yhirose/cpp-httplib 抄送：Frank Wu ,Mention @RemoteSensingFrank, thanks for the feedback. How did you send the post message? From a web browser, or curl?

**Comment by RemoteSensingFrank** [comment]
The post request was send by browser with chrome，I don't know how to get the data in binary，but when I using the python flask server，the binary data can be extracted，and my python code is：
![image](https://user-images.githubusercontent.com/25923674/69816026-89ee9300-1232-11ea-8bf4-4a66ed2107f4.png)

**Comment by yhirose** [comment]
@RemoteSensingFrank, could you check my following test code which shows how to receive binary data from browser?

```cpp
#include <httplib.h>
#include <iostream>
#include <fstream>
using namespace httplib;
using namespace std;

const char* html = R"(
<form id="formElem">
  Name: <input type="text" name="name" value="John">
  File: <input type="file" name="file" accept="image/*">
  <input type="submit">
</form>
<script>
  formElem.onsubmit = async (e) => {
    e.preventDefault();
    let res = await fetch('/post', {
      method: 'POST',
      body: new FormData(formElem)
    });
    console.log(await res.text());
  };
</script>
)";

int main(void) {
  Server svr;

  svr.Get("/", [](const Request & /*req*/, Response &res) {
    res.set_content(html, "text/html");
  });

  svr.Post("/post", [](const Request & req, Response &res) {
    auto name = req.get_file_value("name");
    auto file = req.get_file_value("file");

    cout << "name: " << req.body.substr(name.offset, name.length) << endl;
    cout << "file: " << file.offset << ":" << file.length << ":" << file.filename << endl;

    ofstream ofs(file.filename, ios::binary);
    ofs << req.body.substr(file.offset, file.length);

    res.set_content("done", "text/plain");
  });

  cout << "start..." << endl;
  svr.listen("localhost", 1234);
}
```

I confirmed that I was successfully able to receive binary data. Please let me know the different between your case and my case. Thanks!

**Comment by RemoteSensingFrank** [comment]
Hi:
I used your code and tested,the request of the browser is like

![image](https://user-images.githubusercontent.com/25923674/69837792-79b6d200-128b-11ea-9009-41a00dfbbff5.png)

and it seems that the file can be gotten
![image](https://user-images.githubusercontent.com/25923674/69837991-7b34ca00-128c-11ea-87ac-94f33f6ca0e0.png)

**Comment by yhirose** [comment]
Thank you for the report. Does it meant that there is no problem in cpp-httplib?

**Comment by RemoteSensingFrank** [comment]
Thanks a lot, I find that there is no problem when I use the auto type to get file. @yhirose
