### ISSUE TITLE
Deprecated SSL_CTX_load_verify_locations

### ISSUE THREAD

**Issue by stegemma** [yhirose/cpp-httplib#274]
Can't compile because SSL_CTX_load_verify_locations function has been deprecated in the latest OpenSSL (master branch on github).

Sample code:

`#define CPPHTTPLIB_OPENSSL_SUPPORT
#define CPPHTTPLIB_ZLIB_SUPPORT

// this patch eventually pre-defines the deprectaed function, to allow compiling:
// bool SSL_CTX_load_verify_locations(const void* a, const void* b, const void* c) { return true; }

#include "httplib.h"
#include <iostream>

bool TestHttpLib()
{
	httplib::SSLClient cli("www.somedummywebsite.com");
	//cli.set_ca_cert_path("./ca-bundle.crt");
	cli.enable_server_certificate_verification(false);

	auto res = cli.Get("/");
	if (res && res->status == 200)
	{
		std::cout << res->body << std::endl;
	}
	return true;
}

gives this error on VC++ on Windows:

1>D:\A\LIGS\Altri\cpp-httplib\httplib.h(3767,7): error C3861: 'SSL_CTX_load_verify_locations': identificatore non trovato
1>D:\A\LIGS\Altri\cpp-httplib\httplib.h(3856,23): error C3861: 'SSL_CTX_load_verify_locations': identificatore non trovato
`
`

(NB: "identificatore non trovato" is "identifier not found")

With the suggested patch in user code, it works but, of course, the function has been ignored, in the library.

**Comment by PixlRainbow** [comment]
openssl/openssl#10392 indicates that `SSL_CTX_load_verify_locations` has been depreciated and new wrapper functions have been added.
However, when cloning the latest branch of openssl/openssl, I found that the function is still present and defined in `openssl/ssl.h` and `ssl/ssl_lib.c`. In `ssl.h` the function header has been wrapped with a depreciation warning, but it should not break your compiler entirely unless your compiler is incompatible with custom warnings, or unless you have enabled a flag to drop depreciated functions entirely.

**Comment by yhirose** [comment]
@PixlRainbow, thank you for the excellent research!
@stegemma, I should have mentioned that cpp-httplib supports only officially supported OpenSSL versions such as 1.1.1 and 1.0.2 on README. (I have just updated README to mention it.) Thanks for bring it to my attention anyway.
