### ISSUE TITLE
499 when web-server make heavy task.

### ISSUE THREAD

**Issue by m-garanin** [yhirose/cpp-httplib#278]
Hello,
I have GET-method "/my_heavy_task" on my server (nginx+python), it takes about 2mins before writing response.

If I do response from Chrome - no problem, I get result.

If I do response  "auto res = cli.Get("/my_heavy_task");"  then I got NULL.  
I see request from cpp-httplib in nginx log and  it has HTTP status code "499" ("the client closed the connection before the server answered the request.").  

Can you please explain what I should do ?

**Comment by yhirose** [comment]
@m-garanin, thanks for the feedback. You may want to try longer timeout seconds for CPPHTTPLIB_READ_TIMEOUT_SECOND.

https://github.com/yhirose/cpp-httplib/blob/5e37e383982c3bda0535c61c31e79e3829b0d684/httplib.h#L28

Please let me know if it doesn't solve the problem.

**Comment by m-garanin** [comment]
thank you, it works.
