### ISSUE TITLE
httplib.h produces the following error when compiling.

### ISSUE THREAD

**Issue by StaRT1337** [yhirose/cpp-httplib#284]
Windows 10
Visual studio
MSVC v142
Shared library compiling to x32
```cpp
#pragma once

#include "Defines.hpp"

#include <string>

#define CPPHTTPLIB_OPENSSL_SUPPORT
#include <httplib.h>


namespace xcord
{
	class XCORD_API REST
	{
	public:
		static REST& get_instance();

		static const std::string_view url;
		static const std::string_view cdn;
		static const std::string path(const std::string_view& path);

		static const int version;

		const std::string get(const std::string_view& path);
	private:
		REST();
		//httplib::SSLClient cli_;
	};
}
```
Error:
```
httplib.h(2909,1): error C2451: conditional expression of type 'std::_Binder<std::_Unforced,socket_t &,sockaddr *&,int>' is illegal
```

**Comment by StaRT1337** [comment]
I just checked and this error also reproducing when just doing
```cpp
#pragma once

#include <httplib.h>
```

**Comment by StaRT1337** [comment]
Apparently the error doesn't reproduce when including httplib.h in other headers. This is really confusing.

**Comment by yhirose** [comment]
@StaRT1337, thanks for the report, but I couldn't reproduce it. I took the following steps:

1) Create a new empty solution and project with VC++ 2019
2) Add **httplib.h**, **test.h** and **test.cpp** to the project
3) Set'**Configuration Type**' to '**Static library (.lib)**'
4) Press F7 to build the project

test.h
```cpp
#pragma once
#include "httplib.h"
```

test.cpp
```cpp
#include "test.h"
```

I got the following output:
```
1>------ Build started: Project: staticlib_test, Configuration: Debug Win32 ------
1>test.cpp
1>staticlib_test.vcxproj -> D:\Projects\staticlib_test\Debug\staticlib_test.lib
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

Please let me know what I am missing to reproduce it. Thanks.

**Comment by StaRT1337** [comment]
Thanks you for responding @yhirose, the problem fixed itself and I forgot to close the issue, all i had to do was create a new file put the code and it just worked. Weird stuff ¯\_(ツ)_/¯
