### ISSUE TITLE
Q: Client request through specific network interface.

### ISSUE THREAD

**Issue by m-garanin** [yhirose/cpp-httplib#285]
Hello, let me ask:
my PC has 3 internet connections (different providers),  so
how I can send requests by httplib::Client  through specific interface? 
// I known httplib::Server  supports it but what's about for Client...

**Comment by yhirose** [comment]
@m-garanin, thanks for the question. cpp-httplib doesn't support the feature right now. But I know curl supports `--interface` option that does what you are asking for. I'll consider to implement it when I have time.

**Comment by yhirose** [comment]
https://github.com/yhirose/cpp-httplib#use-a-specitic-network-interface
