### ISSUE TITLE
Is there a non-header-only version of this library available?

### ISSUE THREAD

**Issue by KowalskiThomas** [yhirose/cpp-httplib#287]
Hi,

I know this might be a pretty naive question, but I was wondering whether a non-header-only version was available for cpp-httplib. I am compiling C++ code in pretty constrained environments and my compile times have skyrocketed since I've started using this library. 

Thanks a lot

**Comment by yhirose** [comment]
@KowalskiThomas, thanks for the request. I am not planning to make a no-header-only version, but I made `split.py` to make `httplib.h` and `httplib.cc` in `out` directory. Does it work for you?

**Comment by KowalskiThomas** [comment]
It's exactly what I needed and what I would have done if you had not. 
Thank you very much!

**Comment by hak8or** [comment]
For anyone googling around and coming to here and wondering if it's worth it to get this going, yes, and it's pretty simple.

To start off, as suggested in the readme, you go into the cpp-httplib directory and run split.py, which gives you ```httplib.cc``` and ```httplib.h```. In your code, you just include the header and link against the cc variant.

On my Ryzen 2700x running GCC 10.2.0, with faa5f1d8023746a3da9f275c51867ded2a672ee9 ```v0.8.6``` of this library, I was able to get compilation from roughly 22.5 seconds down to a blistering **2.8 seconds**!

I cannot thank you enough, both to @yhirose for allowing this to be in the library (and putting it into the readme), and @KowalskiThomas for asking about this so Google indexer bot sees it. The QoL improvement of allowing a non header only variant of your library is genuinely huge via saving time when compiling. Now I just wish this can be somehow integrated into the ```CMakeLists.txt```for this library to step upon #470 (please don't remove CMake support, many of us do actually use it). I might play around with that, but my CMake skills aren't exactly stellar.

**Comment by yhirose** [comment]
@hak8or, thanks for the feedback. `CMakeLists.txt` is kindly maintained by @sum01, and I think it has already the support for `split.py`. Please see the following code.

https://github.com/yhirose/cpp-httplib/blob/faa5f1d8023746a3da9f275c51867ded2a672ee9/CMakeLists.txt#L158-L196

> please don't remove CMake support, many of us do actually use it

The current version of CMakeLists.txt is well maintained even if I didn't make the file. So don't worry, I am not going to remove it. 😄

**Comment by sum01** [comment]
Correct, all you need to do is enable the `HTTPLIB_COMPILE` option when using Cmake and it will manage splitting the file and compiling it for you (requires Python v3 installed).

Here's an edited version of the Cmake command ot build & install (taken from my [AUR package](https://aur.archlinux.org/packages/cpp-httplib-compiled/))
```cmake
mkdir -p "build"
cd "build"
cmake -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_SHARED_LIBS=ON \
  -DHTTPLIB_COMPILE=ON \
  -DCMAKE_INSTALL_PREFIX=/usr ..
cmake --build .
cmake --build . --target install
```

Take a look at [the PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cpp-httplib-compiled) if you need any ideas (and are familiar with bash).
