### ISSUE TITLE
Use _WIN32 defintion to detect Windows instead of _MSC_VER

### ISSUE THREAD

**Issue by moonshadow565** [yhirose/cpp-httplib#29]
Currently you are assuming that windows compiler is always MSVC (by checking_MSC_VER) which might not be true (as is in my case).
You should change it to check for (_WIN32) in all places first.
Also you might consider adding autodetection for headers when c++17 compiler is found...
Example:
```cpp
#if ( __cplusplus > 201703L)
#if __has_include(<openssl/ssl.h>)
#ifndef CPPHTTPLIB_OPENSSL_SUPPORT
#define CPPHTTPLIB_OPENSSL_SUPPORT
#endif
#endif
#endif
```

**Comment by yhirose** [comment]
@moonshadow565, good suggestions!
