### ISSUE TITLE
Emscripten support

### ISSUE THREAD

**Issue by anragab** [yhirose/cpp-httplib#298]
[Emscripten](http://emscripten.org) is a toolchain for compiling to asm.js and WebAssembly, built using LLVM, that lets you run C and C++ on the web at near-native speed without plugins. Emscripten has a [Fetch interface](https://emscripten.org/docs/api_reference/fetch.html?highlight=fetch) that can be wrapped under your library

**Comment by yhirose** [comment]
@anragab, thanks for the info.
