### ISSUE TITLE
Default headers for Client:send

### ISSUE THREAD

**Issue by moonshadow565** [yhirose/cpp-httplib#30]
It would be nice if  ``Client:send`` added default_headers (``HOST``, ``User-Agent``, ``Accept``)  when they are not set :)

**Comment by yhirose** [comment]
@moonshadow565, thanks for the suggestion. 

```c++
inline bool Client::send(const Request& req, Response& res)
```

If we remove `const` from 'const Request& req', it's possible to add the default headers. But making the `req` mutable doesn't sound good idea...

Or in `Client::send`, we could clone the `req` argument and add the default headers. In this way, we can keep the `req` immutable, but cloning may cost a lot if the `req` is a big object.

I'll ponder over it for a while to find a better solution.

**Comment by moonshadow565** [comment]
Instead of adding them you could simply write them to the stream :)

**Comment by yhirose** [comment]
`httplib.h` writes headers in the `write_headers`.

```c++
inline void write_headers(Stream& strm, const T& info)
```

If we want to write out `HOST` header here for example, it cannot write it unless the function is given the host and port information. Also it is used for  HTTP response which doesn't need the `HOST` header...

Anyway, I'll look into it more on this. Thanks!

**Comment by moonshadow565** [comment]
@yhirose 
Anything goes really :)
What i really need is to have send method that takes as arguments:
-method
-body
-"addtional" headers that are used as arguments on REST server
Also ``HEAD`` request still has headers as response and no body AFAIK.
