### ISSUE TITLE
about cli.Post()

### ISSUE THREAD

**Issue by hctym1995** [yhirose/cpp-httplib#302]
i want to know how can i set "params" and "body" at the same time when i use the "cli.Post()"?

	httplib::Params params{
		{ "department", "aaaaaaTTTTT" },
		{ "user", "john" }
	};

	res = cli.Post("/service/video.ReporIAnalyse", params, "mybody", "text/plain");

like these code, but it seems wrong. 
3Q so much

**Comment by yhirose** [comment]
Please see the following example:

https://github.com/yhirose/cpp-httplib/blob/aa543240dbf3a5a5c860065a375e47bf3a54076b/test/test.cc#L1683-L1687

Hope it helps.

**Comment by yhirose** [comment]
Also server side code:

https://github.com/yhirose/cpp-httplib/blob/aa543240dbf3a5a5c860065a375e47bf3a54076b/test/test.cc#L907-L912

**Comment by hctym1995** [comment]
thanks fot reply , i'll trt it :) merry xmas
