### ISSUE TITLE
Should colon be allowed in path?

### ISSUE THREAD

**Issue by Gjergj** [yhirose/cpp-httplib#303]
[This](https://www.urlencoder.io/learn/#url-encoding-percent-encoding) says no but there are some places where colons are used in the path
https://en.wikipedia.org/wiki/Template:Welcome
https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken

This library encodes the colon in path.
I think it should be allowed in path.

**Comment by Gjergj** [comment]
In the case of googleapi if the colon in the path is encoded than google returns 404

**Comment by yhirose** [comment]
@Gjergj, thanks for the feedback, but I couldn't reproduce it on my machine. I tested with the following code and it worked fine. Did I miss something?

```cpp
#include <iostream>
#include <httplib.h>
using namespace httplib;
using namespace std;

int main(void) {
  httplib::SSLClient cli("en.wikipedia.org");
  auto res = cli.Get("/wiki/Template:Welcome");
  if (res) {
    cout << res->status << endl;
    cout << res->body << endl;
  }
  return 0;
}
```

**Comment by Gjergj** [comment]
Apparently it is just google. Try:

```
 httplib::SSLClient cli("identitytoolkit.googleapis.com");
 auto res = cli.Post("/v1/accounts:signUp?key=A7J5WTaUK8YA",R"({"email":"xyz@zyx.com","password":"superpassword","returnSecureToken":true})","application/json" );

    if (res) {
        std::cout << res->status << std::endl;
        std::cout << res->body << std::endl;
    }
```

**Comment by yhirose** [comment]
@Gjergj, thanks for the report. I don't have time the rest of this week to work on it. But at least, could you do the same test with curl to see what happens? It will be helpful. Thanks!

**Comment by Gjergj** [comment]
With curl it is ok.
```
curl 'https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key=123456789' -H 'Content-Type: application/json' --data-binary '{"token":"123456789","returnSecureToken":true}'
```
It will just complain because of wrong token and key but will not give 404.

**Comment by yhirose** [comment]
@Gjergj, I have actually fixed it. Thanks for your contribution!
