### ISSUE TITLE
httplib.h  

### ISSUE THREAD

**Issue by vijaysoul** [yhirose/cpp-httplib#305]
//hello.cc

#include "httplib.h"
using namespace httplib;

int main(void) {
  Server svr;

  svr.Get("/hi", [](const Request & /*req*/, Response &res) {
    res.set_content("Hello World!", "text/plain");
  });

  svr.listen("localhost", 1234);
}

I Got this error

/usr/bin/ld: /tmp/cc0bjPgQ.o: in function `main::{lambda(httplib::Request const&, httplib::Response&)#1}::operator()(httplib::Request const&, httplib::Response&) const':
hello.cc:(.text+0x5d): undefined reference to `httplib::Response::set_content(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*)'
/usr/bin/ld: /tmp/cc0bjPgQ.o: in function `main':
hello.cc:(.text+0xf4): undefined reference to `httplib::Server::Server()'
/usr/bin/ld: hello.cc:(.text+0x120): undefined reference to `httplib::Server::Get(char const*, std::function<void (httplib::Request const&, httplib::Response&)>)'
/usr/bin/ld: hello.cc:(.text+0x14f): undefined reference to `httplib::Server::listen(char const*, int, int)'
/usr/bin/ld: hello.cc:(.text+0x15e): undefined reference to `httplib::Server::~Server()'
/usr/bin/ld: hello.cc:(.text+0x1a2): undefined reference to `httplib::Server::~Server()'
collect2: error: ld returned 1 exit status

**Comment by yhirose** [comment]
@vijaysoul, thanks for the feedback. You must be missing something when building it. Could you please take a look at' example/Makefile' which shows how to build it. Hope it helps!

**Comment by afwn90cj93201nixr2e1re** [comment]
@yhirose 
```
httplib::Client cli("http://dummy.restapiexample.com"); 
		cli.set_timeout_sec(10);
		cli.set_read_timeout(10, 20);
		printf("%d\n", cli.is_valid());
		auto res = cli.Get("/api/v1/employees");
		printf("res is %x | %d\n", res, res?1:0);
		if (res && res->status) {
			printf("response is %d\n",res->status);
			if(res->status==200)printf("response is %s\n",res->body.c_str());
		}
```
why it's everytime nullptr? (p.s im not using any ssl in defines, just added w2s to depends in project and added header file also just defined this `#define _WINSOCKAPI_ #include <Windows.h>`)

**Comment by afwn90cj93201nixr2e1re** [comment]
@yhirose

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/75203857-39ba9a80-5767-11ea-9025-6c5fe3f892ca.png)
Same with ur example proj.
Win 10.

**Comment by afwn90cj93201nixr2e1re** [comment]
ended up with  URLOpenBlockingStream.
```
IStream* stream;
		if (!URLOpenBlockingStream(0, "https://url/v", &stream, 0, 0)){
			char buffer[100];
			unsigned long bytesRead;
			stringstream ss; stream->Read(buffer, 100, &bytesRead);
			while (bytesRead > 0){
				ss.write(buffer, (long long)bytesRead);
				stream->Read(buffer, 100, &bytesRead);
			}
			printf("%s\n", ss.str().c_str());
		}
		stream->Release();

```

**Comment by yhirose** [comment]
`httplib::Client cli("restapiexample.com");` is incorrect. It should be `httplib::Client cli("http://dummy.restapiexample.com"); `. In other words, `httplic:Client` takes hostname, but **not** URL.

You can see the example [here](https://github.com/yhirose/cpp-httplib#get) in README:
```cpp
#include <httplib.h>
#include <iostream>

int main(void)
{
  httplib::Client cli("localhost", 1234);

  auto res = cli.Get("/hi");
  if (res && res->status == 200) {
    std::cout << res->body << std::endl;
  }
}
```

Hope it helps! (But if you just care for Windows environment, I understand `URLOpenBlockingStream ` would be better.)

**Comment by afwn90cj93201nixr2e1re** [comment]
oh, get u, maybe you should add some words about it in readme? Also how we can handle any errors coz it's just nullptr btw cli.is_valid() return true? Is here any try catch which gonna return some of usable notify without including ssl? Also what do you think about adding callbacks for async code(non-blocking)?

> httplib::Client cli("restapiexample.com"); is incorrect. It should be httplib::Client cli("http://dummy.restapiexample.com"); 

Maybe first is correct and second incorrect?)

And one more, maybe it's better to add instructions about how we can split client and server too?

**Comment by afwn90cj93201nixr2e1re** [comment]
@vijaysoul

**Comment by afwn90cj93201nixr2e1re** [comment]
@yhirose

**Comment by yhirose** [comment]
Oops...  You are right.
> Maybe first is correct and second incorrect?) (#305 (comment))


>
