### ISSUE TITLE
custom mimetype mappings for `set_base_dir`

### ISSUE THREAD

**Issue by PixlRainbow** [yhirose/cpp-httplib#306]
When using `set_base_dir` to automatically serve files, there should be an option to provide extra file extension -> mimetype mappings. When custom mappings are provided, they should not delete *all* existing mappings, but rather continue to use existing mappings as a fallback if a file extension cannot be found in the custom mappings.  

On an unrelated note, you should add `application/wasm` for `.wasm` files to your default list of recognized extensions. That is the mimetype for WebAssembly files and will likely be more frequently used by front-end developers in the future.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the suggestion. They have been implemented.
