### ISSUE TITLE
Is there plan to support vs2013

### ISSUE THREAD

**Issue by zywj** [yhirose/cpp-httplib#308]
It seems not to be supported in vs2013

**Comment by yhirose** [comment]
Thank you for the question. I don't test  this library on VS2013 any more since I no longer use VS2013 (and VS2015. Since this is just my personal project, I don't have enough resource to support such old environment. Thanks for your consideration. :)

**Comment by PixlRainbow** [comment]
The actual provided `.sln` does not support VS2013. However, httplib.h itself is platform independent and should work with any IDE that supports C++11, as long as you are willing to manually configure library linking (e.g. threads, WinAPI, OpenSSL, zlib) and header include directories.
