### ISSUE TITLE
service cann't be access by other computers

### ISSUE THREAD

**Issue by tianpengli** [yhirose/cpp-httplib#309]
1. When I run the example with localhost, it's ok.
2. When I bind to IP, it directly exited in cloud server.
3. When I bind to localhost in cloud server  and use same server configuration as wamp, it can't be accessed by other computer while wamp does.

**Comment by yhirose** [comment]
Thanks for asking. I don't understand your exact environment, but at least I can saythat cpp-httplib is not like Apache which supports virtual host mechanism. Sorry that I can't give a meaningful help...

You might be interested in the following posts:
https://stackoverflow.com/questions/38175020/cant-access-localhost-via-ip-address
https://stackoverflow.com/questions/11364406/access-to-a-site-on-localhost-from-remote
https://superuser.com/questions/1303093/cant-access-localhost-from-computer-running-on-same-network

**Comment by PixlRainbow** [comment]
What do you mean by "bind to IP"?  
Note that for a cloud server, the actual server has its own local network, and the cloud provider performs forwarding to allow external clients to connect to the cloud server. The IP as displayed to external clients may not be the same as the IP that the cloud server identifies itself with.
