### ISSUE TITLE
bug with WindowsXp

### ISSUE THREAD

**Issue by sidyhe** [yhirose/cpp-httplib#310]
IDE: VS2017
Toolset: v141_xp
OS: Windows XP SP3

Hi!
I found that http request fail on winxp
in function ``detail::create_socket``, by WinApi ``WSASocketW`` with error ``WSAEPROTOTYPE``
change to use ``socket`` is fine
please fix it
thanks

**Comment by yhirose** [comment]
Thanks for asking, but it doesn't officially support it. (I don't have a XP machine. So I can't do anything for it.)
https://github.com/yhirose/cpp-httplib/issues/205

@Bendr0id tries to support older versions of Windows:
https://github.com/yhirose/cpp-httplib/pull/292

If you fix it on your XP and post a pull request, we are very much welcome! :)
