### ISSUE TITLE
does http client support non-blocking/asynchronous request?

### ISSUE THREAD

**Issue by 0xffff00** [yhirose/cpp-httplib#312]
I cannot find any clue in readme.md or example codes.
All examples seem be blocking call.
However I want something like:
```cpp
cli.Get("/hi",[](HttpResponse resp){...});
```
or
```cpp
cli.Get("/hi")
.Then([](HttpResponse resp){...})
```
Are these features already supported or not?

**Comment by yhirose** [comment]
@0xffff00, thanks for the question. Hope these items help you.
https://github.com/yhirose/cpp-httplib/issues/133
https://github.com/yhirose/cpp-httplib/issues/156

**Comment by PixlRainbow** [comment]
native C++11 has `std::async` which will give you an `std::future` object.  
```cpp
#include "httplib.h"
#include <future>
#include <chrono>

int main(){
    namespace http = httplib;
    // http://anglesharp.azurewebsites.net/Chunked
    // this website will take ~1.1 seconds to finish loading
    http::Client cli("anglesharp.azurewebsites.net");
    // Client::Get is an overloaded function
    // compiler will get confused unless you explicitly specify which version of Get
    std::shared_ptr<http::Response> (http::Client::*gf)(const char *) = &http::Client::Get;
    auto a1 = std::async(std::launch::async, gf, cli, "/Chunked");

    // spend 2 seconds doing something in main thread
    std::this_thread::sleep_for(std::chrono::seconds(2));
    printf("This prints first\n");
    auto res = a1.get();
    printf("This prints immediately because the request was finished in background\n");
    // but even if the request isn't finished, a1.get() will also force main thread to wait until done.
    if(res){
        printf("%i\n", res->status);
    }
    else{
        printf("no luck\n");
    }
    return 0;
}
```

**Comment by ChristophPech** [comment]
This library is very elegant and minimalistic, but the lack of non-blocking is bad. The server will create with as many threads as I have cores which would only make sense if we are CPU bound.

Let's assume I have 4 cores then the whole server will be blocked if 4 sockets block because of IO which will happen easily with slow network connections.

For the client std::async and std::future might be an acceptable workaround but it will create one thread for every async operation being very unperformant for a large count of requests. 

I'm going to make the client side non-blocking, if anyone is interested, I can put up a fork on github.

**Comment by yhirose** [comment]
@ChristophPech, thank you for your interest in this library! The following issue might be helpful.
https://github.com/skalenetwork/skaled/issues/219

**Comment by ChristophPech** [comment]
Thanks for the tip, seems they made the server side more scalable. But I need the client side, I'll use it for games with tight performance limitations, I'm not allowed to block or create threads so I have to do it myself.

Looking deeper into your client I think it would be either too hacky or take too much refactor to go completely non blocking, so I will write one from scratch as small as possible. Thanks though.

**Comment by yhirose** [comment]
Hope it goes well!

**Comment by tangm421** [comment]
> This library is very elegant and minimalistic, but the lack of non-blocking is bad. The server will create with as many threads as I have cores which would only make sense if we are CPU bound.
> 
> Let's assume I have 4 cores then the whole server will be blocked if 4 sockets block because of IO which will happen easily with slow network connections.
> 
> For the client std::async and std::future might be an acceptable workaround but it will create one thread for every async operation being very unperformant for a large count of requests.
> 
> I'm going to make the client side non-blocking, if anyone is interested, I can put up a fork on github.

How's the progress？

**Comment by ChristophPech** [comment]
@tangm421 I basically started from scratch, it works now for openssl on windows, doing the hostname resolving via GetAddrInfoExW/getaddrinfo_a. Now I have to finish the linux port, and add native API support for Windows (WININET) and Xbox to be able to run without openssl. Still a way to go before being publishable.

**Comment by PixlRainbow** [comment]
@fsxss this code is based on the version of httplib from two years ago. The interface of httplib has changed and now no longer accepts `const char*` as parameter but instead `const std::string&`. The return type has also changed from `std::shared_ptr<httplib::Response>` to `httplib::Result`

**Comment by fsxss** [comment]
> @fsxss this code is based on the version of httplib from two years ago. The interface of httplib has changed and now no longer accepts `const char*` as parameter but instead `const std::string&`. The return type has also changed from `std::shared_ptr<httplib::Response>` to `httplib::Result`

thank you for your reply!

**Comment by QGB** [comment]
@PixlRainbow 

why my code  Segmentation fault (core dumped)

```


```

**Comment by PixlRainbow** [comment]
@QGB did you mean to include an empty code block in your comment?
