### ISSUE TITLE
Static file server should issue a warning if specified folder does not exist

### ISSUE THREAD

**Issue by BeatWolf** [yhirose/cpp-httplib#315]
I came across this problem when running the examples in an IDE such as CLion.

In a simple example where we set a folder as the base directory for the static file server, and the folder does not exist, the library does not complain. Now this could perhaps sometimes be wanted, but i think it would be save to print a warning in that case, because its most certainly not what was intended.

The code i'm talking about looks like this:
svr.set_base_dir("./www", "/public");

The problem is that for example CLion does not run the executable, by default, in the project root folder, but the build directory. As there are no errors, its not an easy to debug issue.

**Comment by yhirose** [comment]
@BeatWolf, thanks for the feedback. In fact, `set_base_dir` tries to check if the given directory exists as below.

https://github.com/yhirose/cpp-httplib/blob/96e9ec0663bad6deab2564de0b38612fdb4767a3/httplib.h#L2855-L2864

Could you give me more detail of your problem? Thanks!

**Comment by BeatWolf** [comment]
Thank you for the quick answer. As the example given in the readme does not actually check for the return value, when following the examples it is not obvious that it actually fails.

I'm teaching a course where we use httplib, and this particular issue is one multiple students faced, which is why i thought it was worth reporting. Maybe updating the example to actually check for the return value would do the trick?

**Comment by yhirose** [comment]
Thanks for the good suggestion! I updated REAME and example/simplesvr.cc.
Hope students no longer get confused with the silent failure.
