### ISSUE TITLE
Determine why server.listen is failing?I

### ISSUE THREAD

**Issue by vedantroy** [yhirose/cpp-httplib#316]
I am trying to make my http server publicly accessible. To do this, I found my public ip address and did this

`server.listen("<public ip address>", 3000)`.

However, server.listen is returning `0` and the program closes. How do I determine what the cause of failure is?

**Comment by yhirose** [comment]
@vedantroy, you can just simply to run the server on debugger like gdb or lldb. I don't know your network environment though, it seems like the IP address or the port 3000 is not allowed for public.

You can change the line
https://github.com/yhirose/cpp-httplib/blob/96e9ec0663bad6deab2564de0b38612fdb4767a3/httplib.h#L1344
to
```cpp
auto error = getaddrinfo(host, service.c_str(), &hints, &result);
// Check the error code.
if (error != 0) { 
```

Hope it helps!
