### ISSUE TITLE
Update broke VS2013 Support

### ISSUE THREAD

**Issue by lordbendtner1337** [yhirose/cpp-httplib#327]
Hello,

It seems that latest update broke support, due to;

  Response() = default;
  Response(const Response &) = default;
  Response &operator=(const Response &) = default;
  Response(Response &&) = default;
  Response &operator=(Response &&) = default;

**Comment by yhirose** [comment]
@lordbendtner1337, thanks for the report.
@hyperxor, it seems like #322 causes the problem...

Supporting old compilers takes extra time, also they unable me to use C++11 features  fully. So, I am now thinking of dropping old compilers like VS2013. (I am right now using only VS2017 and VS2019 on Windows environment at my work place.)

**Comment by yhirose** [comment]
#329

**Comment by lordbendtner1337** [comment]
That's totally fine, I'll just keep using the older version :)

**Comment by hyperxor** [comment]
@yhirose @lordbendtner1337 Hello, I'm so sorry that I didn't take into account compilers that partially support C++. I will be more careful with changes in future.
Maybe more  toolchains (with different compilters versions) should be added to PR checks?

**Comment by yhirose** [comment]
@hyperxor, don't worry about it at all. It's impossible to check with all the compilers anyway. 😅 

@lordbendtner1337, could you check if the following code can fix the VS2013 build problem when you have time? Thanks!

```cpp
#if (_MSC_VER >= 1900)
Response() = default;
Response(const Response &) = default;
Response &operator=(const Response &) = default;
Response(Response &&) = default;
Response &operator=(Response &&) = default;
#endif
```
