### ISSUE TITLE
add GET with byte range

### ISSUE THREAD

**Issue by ReneKeilwerth** [yhirose/cpp-httplib#33]
added functionality to get downloading portions of big files using range_low & range_high
can be easily achieved with following code:
( default parameter values must be defined in the class definition, they are just in the implementation for ovesight )
`
        inline void Client::add_range_header (Request &req, int64_t range_low, int64_t range_high)
        {
                std::string range_str = "bytes=";

                if ( range_low >= 0 )
                {
                        range_str += std::to_string (range_low);
                }

                range_str += "-";

                if ( range_high >= 0 )
                        range_str += std::to_string (range_high);
                
                req.set_header ("Range", range_str.c_str ());
        }

        inline std::shared_ptr<Response> Client::get (const char* path, Progress callback, int64_t range_low=-1, int64_t range_high=-1)
        {
                Request req;
                req.method = "GET";
                req.path = path;
                req.progress = callback;
                add_default_headers (req);

                if ( range_low >= 0 )
                        add_range_header (req, range_low, range_high);

                auto res = std::make_shared<Response> ();

                return send (req, *res) ? res : nullptr;
        }
`

**Comment by yhirose** [comment]
@ReneKeilwerth, thanks for the suggestion! I put label 'enhancement' and 'HTTP/1.1'.

**Comment by yhirose** [comment]
@ReneKeilwerth, the HTTP range has been supported.
https://github.com/yhirose/cpp-httplib#range-http11
