### ISSUE TITLE
Httplib::Client PUT is missing parameter support

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [yhirose/cpp-httplib#330]
The Httplib::Client object is missing` Put(url, param)` implementations for PUT requests with parameter data. PUT is associated with updating a resource on a RESTFUL API. e,g,

PUT localhost:3000/v1/users
with x-www-form-url-encoded key/pairs: username=Bob

would update the record with the new information. 

`Post(...)` has all the proper implementations so `Put(...)` should mirror those expectations. I currently cannot use the lib in its vanilla state to update my API from C++ until this is resolved.

**Comment by yhirose** [comment]
@TheMaverickProgrammer, thanks for the feedback. So you need the following functions, right?

```cpp
std::shared_ptr<Response> Post(const char *path, const Params &params);
std::shared_ptr<Response> Post(const char *path, const Headers &headers, const Params &params);
```

Please let me know if you need more. Thank you for your contribution!

**Comment by TheMaverickProgrammer** [comment]
Yes thats right :)

**Comment by yhirose** [comment]
They are now available.

**Comment by TheMaverickProgrammer** [comment]
Youre amazing! 🙌
