### ISSUE TITLE
Potentially mistaken processing order in Server::handle_file_request()?

### ISSUE THREAD

**Issue by CingKong** [yhirose/cpp-httplib#331]
https://github.com/yhirose/cpp-httplib/blob/b4f808da7446733ae0aa7b3bd949bd0bdf4279a8/httplib.h#L3173

```
inline bool Server::handle_file_request(Request &req, Response &res) {
    ... ... 
    if (detail::is_file(path)) {
        detail::read_file(path, res.body);
        auto type =
            detail::find_content_type(path, file_extension_and_mimetype_map_);
        if (type) { res.set_header("Content-Type", type); }
        res.status = 200;
        if (file_request_handler_) { file_request_handler_(req, res); }
        return true;
    }
    ... ...
    return false;
}
```

in here why is the default process put before custom file request handler,
and so even if users set a custom handler, it still goes through the default process first?
what is the actual purpose of a Server::set_file_request_handler(),
why don't we make it like 
```
inline bool Server::handle_file_request(Request &req, Response &res) {
    if (file_request_handler_) { 
        file_request_handler_(req, res);
        return true;
    }
    ... ...
}
```
because this could save a lot of resource if using a custom handler?

**Comment by CingKong** [comment]
i know in custom handler one can use `Response::set_content()` to return arbitrary date, but because of the default process is involved, it actually generates extra overhead.

**Comment by yhirose** [comment]
@CingKong, thank you for the feedback. I probably don't fully understand what you are saying though, the current implementation is what I actually intended to do. The basic motivation of this implementation is to allow users to make a file based HTTP server easily like python's `python -m SimpleHTTPServer` and `python3 -m http.server`. I want to put priority on such file resources first. The server doesn't discover it,  then handle the request with regular handlers. Hope the explanation helps!

**Comment by CingKong** [comment]
Sorry for not explaining it clear.

lemme try this:
if ima set up a custom handler through `Server::set_file_request_handler()` and i want that handler provides some arbitrary datas rather than returning the actually file. then the prior codes esp these
```
detail::read_file(path, res.body);
auto type =
    detail::find_content_type(path, file_extension_and_mimetype_map_);
if (type) { res.set_header("Content-Type", type); }
res.status = 200;
```
are actually useless for me.

there it involves file i/o and streams, it could be a serious computing resource eater.

(haven't look into the default process' implementation yet, not sure if it will conflict with my custom handler, eg. mixing the output of the custom handler)

**Comment by yhirose** [comment]
This file request handle cannot handle your request unfortunately... But you could do what you want in regular Get handler instead. (Of course, you have to manually check the file existence with the given path though, you can have more freedom.)
