### ISSUE TITLE
form-data improperly handled in SSLServer

### ISSUE THREAD

**Issue by CingKong** [yhirose/cpp-httplib#332]
server code is simple:
```
#include <iostream>
#define CPPHTTPLIB_OPENSSL_SUPPORT
#include "httplib.h"

const char *certificate = "./certificate";
const char *key = "./key";
const char *address = "localhost";
const int port = 8888;
const int flags = 0;

int main()
{
    using httplib::Request;
    using httplib::Response;
//    httplib::SSLServer server(certificate, key);
    httplib::Server server;

    if (!server.is_valid())
    {
        printf("server has an error...\n");
        return -1;
    }

    server.Post("/", [](const Request & req, Response &res)
    {
        for (auto &[k,v] : req.files)
            std::cout << k << ": " << v.content << std::endl;
        std::cout << std::endl;
    });

    printf("Server listening on address %s: %d. \n", address, port);
    server.listen(address, port, flags);
}
```
switched between ssl and non-ssl, tested with postman:
![Screenshot from 2020-01-14 02-48-53](https://user-images.githubusercontent.com/8308991/72324273-901cbf80-3678-11ea-965d-b36a1aa1fe78.png)

server output for non-ssl:
![Screenshot from 2020-01-14 02-49-08](https://user-images.githubusercontent.com/8308991/72324275-901cbf80-3678-11ea-91a9-37dc972721ad.png)

server output for ssl:
![Screenshot from 2020-01-14 02-49-43](https://user-images.githubusercontent.com/8308991/72324278-90b55600-3678-11ea-8eda-a7c9768f46a8.png)

results are same for master and v0.5.1

**Comment by yhirose** [comment]
@CingKong, thanks for the report. Could you make sure that you sent a SSL request message to the SSL server?

**Comment by yhirose** [comment]
@CingKong, thanks for finding the bug! I fixed it on master. Could you try it again?

**Comment by CingKong** [comment]
the test ran well. nice.
