### ISSUE TITLE
Send binary data over Multipart Form Data

### ISSUE THREAD

**Issue by tassadarius** [yhirose/cpp-httplib#336]
Hello guys, It's not really an issue and I don't even know if my question respects the specs. But since the docs are not quite clear I will post it here.

I have a HTTP endpoint which I have to access from C++ so I wanted to use your library.
However the examples don't seem to cover sending binary data with application/octetet-stream. I wondered if this is even possible?

A (non-compiling) example code so you know what I mean.

```cpp
std::vector<char> data { 0x08, 0x07, 0x11, 0x00, 0x11, 0x00, 0x44, 0x33 };

  httplib::MultipartFormDataItems items = {
    { "file3", data.data(), "filename.bin", "application/octet-stream" },
  };

  auto res = cli.Post("/endpoint", items);
```

My server quits this with:

> Exception Type: EOFError at /endpoint/
> Exception Value: read() didn't return enough bytes

Sorry for the inconvenience

**Comment by yhirose** [comment]
@tassadarius, thanks for the feedback. Could you try the following code to see if it fixes the truncated data problem?

```cpp
  httplib::MultipartFormDataItems items = {
    { "file3", std::string(data.data(), data.size()), "filename.bin", "application/octet-stream" },
  };
```

**Comment by tassadarius** [comment]
Great, this worked. Thanks for your help!

**Comment by fatrolls** [comment]
How do I get this to work on binary files without messing up the 0x0D character? is that possible?

			FILE *fl = fopen("c:\\test.exe", "rb");
			fseek(fl, 0, SEEK_END);
			long len = ftell(fl);
			unsigned char *file = new unsigned char[len];
			fseek(fl, 0, SEEK_SET);
			fread(file, 1, len, fl);
			fclose(fl);
			printf("%02x %02x\n", file[0x423], file[0x424]);

std::vector<unsigned char> data(file, file + len);
			httplib::MultipartFormDataItems items = {
				{ "a", std::string((char*)data.data(), data.size()), filename, "application/octet-stream" },
			};

Original file
![before](https://i.imgur.com/johfvEA.png)
Here is the file I get on my webserver
![after](https://i.imgur.com/YMAbFLm.png)

output from printf is 0x0A 0x40 (which is correctly loaded).
