### ISSUE TITLE
Allow to remove base directories in runtime

### ISSUE THREAD

**Issue by trollixx** [yhirose/cpp-httplib#341]
`set_base_dir()` allows adding new directories, but there is no way to remove them.

Some kind of `remove_base_dir(prefix)` or `remove_mount_point(mount_point)` could address this. I think the function should take prefix, and not path, because the same directory can be added under different prefixes.

**Comment by yhirose** [comment]
@trollixx, thanks for the feedback. I just wonder when you need to call the `remove_???` methods? Do you want to call them **before** or **after** a server starts?

If it's **before**, there is no problem adding and using those methods.

But if it' **after**, we have to do it in a different thread. That means that the server now needs to project `base_dirs_` member variable in `handle_file_request` with a `std::mutex` which could cause really bad performance and the server can no longer accepts simultaneous requests effectively.

**Comment by PixlRainbow** [comment]
Unfortunately, `std::shared_mutex` was only added in C++17 and is not available in C++11. May be possible to reproduce its features with semaphores or flags though.  
Alternatively there is `std::shared_future` which has a locking `get()` but it may reduce performance of the server because of extra copy operations.

**Comment by trollixx** [comment]
I am trying to use `cpp-httplib` to serve content locally in [my project](https://github.com/zealdocs/zeal). It's a documentation manager, and docsets (basically bundles of HTML pages) can be installed and removed at any time. I have added `remove_mount_point` function, and ignored thread safety for the initial implementation (see zealdocs/zeal#1182), and it seems to work as desired.

I think that due to the way Zeal works it's not even possible to trigger issues from the lack of synchronization between threads, but before merging the PR I am planning to address that. Performance drawbacks are not a concern in this use case, in the end it's a single user application.

**Comment by PixlRainbow** [comment]
The race condition should only occur if a client attempts to send the server a request at the same moment that any mount point is changed. But when that occurs there will likely be a segfault.  
Also note that threads and clients will not always have a one-to-one ratio. Some web browsers, in order to speed up webpage loading times, will load page assets (e.g. images and other media, stylesheets etc) in parallel using multiple connections. When doing so they will use multiple threads on the server.

**Comment by yhirose** [comment]
@trollixx, thanks for the clear explanation. I took a look at `remove_mount_point` and looks good to me. So I actually merged it to master by #342. It also added `set_mount_point` which is almost same as `set_base_dir` except it doesn't accept default value for `mount_point`. REAME has been updated as well to indicate that the static files server methods are not thread safe. Please let me know if you have any problems with the new static file server methods.

**Comment by trollixx** [comment]
@yhirose thank you for the quick turnaround! I just tested the code from the master branch, and it works perfectly.

Another question, maybe it would make sense to provide thread safe versions of these methods? In my case I don't mind sacrificing a few milliseconds to avoid an unlikely but possible crash.

**Comment by yhirose** [comment]
@trollixx, thank you for noting it. I have reformatted the code with clangformat.

When it comes to the thread-safe implementation, `std::shared_mutex` and `std::shraed_lock` are not available in c+11. So there is no effective way to do it. I don't want to sacrifice the reading performance with `std::mutex` and `std:: lock_guard` (or `std::unique_lock`)...

`set_mounting_point` is used before starting a server in most cases, and I think `remove_mounting_point` is rarely used by users. So I'll leave the code as it is for now, and I'll use `std::shared_mutext` when cpp-httplib can safely move to C++17 in the future.

Anyway, thank you very much for great your contribution, and hope the new feature in your project will go well!
