### ISSUE TITLE
POST with path, body, headers, params

### ISSUE THREAD

**Issue by jarednm** [yhirose/cpp-httplib#344]
I am trying to do a POST which involves path, body, headers, and params (query).  Looking through the code it appears you do not support all of these together in POST.  Is that correct?

**Comment by PixlRainbow** [comment]
params (query) refers query-encoded body of `application/x-www-form-urlencoded` post request. The params go inside the post body. Therefore, once you are using Params, you cannot have a custom post body.

**Comment by yhirose** [comment]
@jarednm, please see the above comment from @PixlRainbow. If you really want to send query parameters and body content, you may be interested in the following unit test case.

https://github.com/yhirose/cpp-httplib/blob/b251668522dd459d2c6a75c10390a11b640be708/test/test.cc#L1775-L1780

Hope it helps.
