### ISSUE TITLE
Sending binary file data using the Client API

### ISSUE THREAD

**Issue by prabindh** [yhirose/cpp-httplib#346]
When sending binary content using POST and multipart, I see the multipart data content is of type std::string. From code, I do not see any inbuilt base64 being done on the input string data. Does this mean, the input binary content needs to be base64'ed before feeding into the client API for POST ?

```
struct MultipartFormData {
  std::string name;
  **std::string content;**
  std::string filename;
  std::string content_type;
};
```

**Comment by yhirose** [comment]
Could you check with the following issues to get an answer?
https://github.com/yhirose/cpp-httplib/search?q=binary&type=Issues
