### ISSUE TITLE
Expect: 100-Continue support

### ISSUE THREAD

**Issue by oleg-st** [yhirose/cpp-httplib#349]
Some clients, such as curl, use this mechanism by default.
It would be nice to be able to acknowledge or reject request body before reading it.
Sending a file via curl now causes a delay of 1 second due to a timeout waiting for `100 Continue`. 

```
$ time curl -v -XPOST 'http://localhost:8003/' -F 'file=@testfile'
* About to connect() to localhost port 8003 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8003 (#0)
> POST / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8003
> Accept: */*
> Content-Length: 200
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=----------------------------1a479a81f757
> 
* Done waiting for 100-continue
< HTTP/1.1 404 Not Found
< Accept-Ranges: bytes
< Content-Length: 0
< Content-Type: text/plain
* HTTP error before end of send, stop sending
< 
* Closing connection 0

real    0m1.015s
user    0m0.005s
sys     0m0.005s
```

**Comment by yhirose** [comment]
@oleg-st, thanks for the report! I'll take care of it when I have time.

**Comment by yhirose** [comment]
@oleg-st, please let me know if the latest master code fixes the problem on your machine.
https://github.com/yhirose/cpp-httplib#expect-100-continue-handler

If it's ok, I'll bump up the version number. Thanks!

**Comment by oleg-st** [comment]
@yhirose, yes, the problem is fixed, thanks!

**Comment by yhirose** [comment]
Thanks!
