### ISSUE TITLE
could the library be used in a dynamic library(dll) built by Visual Studio?

### ISSUE THREAD

**Issue by zjbpku** [yhirose/cpp-httplib#350]
I failed to build in dynamic library by Visual Studio, but succeed in static library.  
errors:
![image](https://user-images.githubusercontent.com/2306486/74248491-9eff9c00-4d22-11ea-8b46-2b1b7b1484ef.png)

errors relates to  *std::min()* and *std::numeric_limits<size_t>::max()*

**Comment by yhirose** [comment]
@zjbpku, thanks for the report. Could you provide more specific info to reproduce it?

**Comment by vitalyster** [comment]
`#define NOMINMAX` before `#include <windows.h>` ?

**Comment by yhirose** [comment]
@vitalyster, thanks for the valuable info.
@zjbpku, hope the above info helps.

**Comment by zjbpku** [comment]
@vitalyster  @yhirose thanks very much. I did it.
and another question:
how to request https links?
it will get empty result by codes below:
```
httplib::Client cli("https://httpbin.org",443);
cli.Get("/get");
```

**Comment by jabin-zhao** [comment]
> @vitalyster @yhirose thanks very much. I did it.
> and another question:
> how to request https links?
> it will get empty result by codes below:
> 
> ```
> httplib::Client cli("https://httpbin.org",443);
> cli.Get("/get");
> ```

I got it.  thanks

**Comment by zjbpku** [comment]
@vitalyster @yhirose thanks very much. I did it.
