### ISSUE TITLE
ThreadPool doesn't work if std::thread::hardware_concurrency() returns 1

### ISSUE THREAD

**Issue by joesdiner** [yhirose/cpp-httplib#351]
`Server::listen_internal()` creates a `TaskQueue`, which is essentially a `ThreadPool`. The number of threads in this thread pool is `CPPHTTPLIB_THREAD_POOL_COUNT` which is defined as:

`#define CPPHTTPLIB_THREAD_POOL_COUNT                                           \`
`   (std::thread::hardware_concurrency()                                         \`
`       ? std::thread::hardware_concurrency() - 1                               \`
`       : 2)`

However, if `std::thread::hardware_concurrency()` returns 1, this means `CPPHTTPLIB_THREAD_POOL_COUNT` will be 0, no threads will be created, and the server won't process any requests. Perhaps `CPPHTTPLIB_THREAD_POOL_COUNT` should be changed to:

`#define CPPHTTPLIB_THREAD_POOL_COUNT                                           \`
`  (std::thread::hardware_concurrency() > 1                                     \`
`       ? std::thread::hardware_concurrency() - 1                               \`
`       : 2)`

**Comment by yhirose** [comment]
@joesdiner, do you have any comment on that?

**Comment by yhirose** [comment]
@stupedama, do you have any comment on that?

**Comment by joesdiner** [comment]
> 
> 
> @stupedama, do you have any comment on that? (#333)

I think that is what's causing the problem for me. That PR seems to address the issue if `std::thread::hardware_concurrency()` returned 0, but it also seems to introduce a regression if `std::thread::hardware_concurrency()` returns 1, since `CPPHTTPLIB_THREAD_POOL_COUNT ` will evaluate to 0 and the thread pool will not have any threads to do work.

**Comment by PixlRainbow** [comment]
how about `std::max(2, std::thread::hardware_concurrency() - 1)`? It is shorter and more readable, while also more efficient as you only call `hardware_concurrency` once.

**Comment by joesdiner** [comment]
Yeah, that seems even better.

**Comment by yhirose** [comment]
@joesdiner and @PixlRainbow, thank you for the suggestion. I implemented accordingly. Thanks!
