### ISSUE TITLE
Set http-get timeout

### ISSUE THREAD

**Issue by LemonAniLabs** [yhirose/cpp-httplib#353]
Hello, I have try the function  set_read_timeout and set_timeout_sec, but it is no use.
Because I have a http server it need a few second to generate the response.
So I think I can adjust the timeout on my client process. Is my code section correct to use the timeout?

Or what should I do if I want to extend the timeout on my client?
Thanks~~
```
httplib::Client cli("localhost", 8280);	
cli.set_timeout_sec(15);
cli.set_read_timeout(100,1000);
auto res = cli.Get(string("/avcp/info?packid="+ aPackID).c_str());
```

**Comment by PixlRainbow** [comment]
I tested your provided code on an intentionally delayed server successfully. Have you made sure there is no other services in between your client and the HTTP server which is cutting off your connection before you can finish? e.g. proxy, shared virtual host.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the comment.
@LemonAniLabs, hope the above comment help. Please let me know if you think still it's really an issue in cpp-httplib.
