### ISSUE TITLE
SSLServer bind_to_any_port, is_valid() constantly returns false

### ISSUE THREAD

**Issue by Brannydonowt** [yhirose/cpp-httplib#354]
![image](https://user-images.githubusercontent.com/36974368/74527881-c02cdc00-4f1e-11ea-850e-58a571c928ef.png)

Currently when trying to bind a created SSL Server to any port, I consistently fail to bind to port because is_valid returns false.

![image](https://user-images.githubusercontent.com/36974368/74527982-0124f080-4f1f-11ea-8cbe-b42fbbacdcd4.png)

Whilst using a standard HTTP server, everything works correctly and as expected. 

Any input, or is this a bug?

**Comment by yhirose** [comment]
@Brannydonowt, thank you for the report. Could you try to run `make` in `test` folder, since the unit test suite has some test cases for `is_valid` and `bind_to_any_port`? At least on my machine, the Travis CI and Github Actions, the unit test passes successfully. Thanks!

**Comment by PixlRainbow** [comment]
You appear to be using unreal engine. However, I cannot find any documentation for certificate and key getters for UE's HttpServer. So I have to ask:  
Does `GetCertificate` and `GetKey` actually return paths, or does it return the binary contents of the files?  
If it returns paths, are they relative or absolute?  
If they are relative, do they have the same point of reference as httplib?

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the comment.
@Brannydonowt, hope the comment from @PixlRainbow helps you.
