### ISSUE TITLE
Binding lambda function to member function

### ISSUE THREAD

**Issue by webfolderio** [yhirose/cpp-httplib#364]
Hi,

I am trying to learn c++ and not familiar with basic things.

My server has several endpoints and lambda style seems bit ugly for me.
What is the correct why to bind `Handler = std::function<void(const Request &, Response &)>` to a member function.

Is this following code correct way to bind lambda to member function? Are there any alternative solution?

I am sorry, for asking such a silly question.

```cpp
class HttpServer {

  private:
    void hi(const Request &req, Response& res) {
      res.set_content("Hello World!", "text/plain");
    }
}

Server server;

server.Get("/hi", [this](const Request &req, Response &res) {
  hi(std::move(req), res);
});
```

**Comment by PixlRainbow** [comment]
aren't you still using lambdas in your code? In addition, it is not recommended that you modify classes inside libraries unless you intend to extend the functionality of the library.  
you can reference functions directly:  
```cpp
void hi(const Request &req, Response& res){
  res.set_content("Hello World!", "text/plain");
}

Server server;
server.Get("/hi", hi);
```  
You can also use namespaces to organize your functions.  
```cpp
namespace webfolder {
  namespace handlers {
    void hi(const Request &req, Response& res){
      res.set_content("Hello World!", "text/plain");
    }
  }
  Server server;
}
// .....
webfolder::server.Get("/hi", webfolder::handlers::hi);
```

**Comment by yhirose** [comment]
Or like this?

```cpp
class HttpServer {
  public:
    HttpServer() {
      server.Get("/hi", [this](const Request &req, Response &res) {
        hi(req, res);
      });
    }

    Server server;

  private:
    void hi(const Request &req, Response& res) {
      res.set_content("Hello World!", "text/plain");
    }
}
```

**Comment by webfolderio** [comment]
Thanks!

**Comment by alongL** [comment]
`server.Get("/hi", [this](const Request &req, Response &res) {
        hi(req, res);
      });`
I also use this method.
