### ISSUE TITLE
Any way to do a direct GET without a client?

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [yhirose/cpp-httplib#370]
I have some image data I'd like to fetch from public URLs. The client expects to connect to a domain before using the GET endpoint but in my case I don't need to connect to any particular domain. Something like:

```
httplib::Get("http://www.somewebsite.com/images/454.png", reciever);
```

The closest thing to this I could find uses a vector of `Request` objects and they all expect a domain too. I just want to fetch public data directly.

**Comment by yhirose** [comment]
@TheMaverickProgrammer, thanks for the feedback. It's same as #357.
