### ISSUE TITLE
Details for fails

### ISSUE THREAD

**Issue by mrpuzzler** [yhirose/cpp-httplib#379]
It's completely unclear why connection fails sometime. It will be great to have some error code (or description).

**Comment by yhirose** [comment]
@mrpuzzler, thank you for your feedback. Which side are you talking about, server or client? Also what kind of information would you like to see? Although it might not be able to report such detailed error information without changing the current API interface, at least I'll take a look at a possibility. Thanks!

**Comment by mrpuzzler** [comment]
I'm interested in client side. Now I have a problem and can't find sources. I send Post request to server, I see server get it, stack and do response with some delay. But cpp-httplib client can't catch it ... probably timeout, but set_timeout does not help at all.

**Comment by yhirose** [comment]
@mrpuzzler, thanks for the detail. I'll try to emulate your situation and put it in my unit test suite. Could you try to send the same request from `curl -v` to see the actual error information from the server? (It would be 'connection timeout', 'read timeout', or something else.) It will greatly help me to handle this issue. Thanks a lot!

**Comment by mrpuzzler** [comment]
No any errors from server. Server put into queue request ... but client don't wait for response and just return false

**Comment by yhirose** [comment]
@mrpuzzler, OK. Could you try `curl -v` to see what curl reports in this situation? Thanks!

**Comment by mrpuzzler** [comment]
I can't reproduce it ... I see logs, where cpp-httplib fails to connect, but on server side I see request was accepted (but not processed). I try to change timeout settings on cpp-httplib side, but it does not change anything. Any ideas how to wait response from server?

**Comment by mrpuzzler** [comment]
Without any error codes on client side it's impossible to fix it ... it just fails and return false.

**Comment by mrpuzzler** [comment]
I'm not sure ... but here ... we send and try immediately read response ... but server can delay response ...

`inline bool Client::process_request(Stream &strm, const Request &req,
                                    Response &res, bool last_connection,
                                    bool &connection_close) {
  // Send request
  if (!write_request(strm, req, last_connection)) { return false; }

  // Receive response and headers
  if (!read_response_line(strm, res) ||
      !detail::read_headers(strm, res.headers)) {
    return false;
  }`

**Comment by mrpuzzler** [comment]
What exactly ```set_timeout_sec``` does? Set timeout to establish connection?

**Comment by mrpuzzler** [comment]
Also, we need a way to cancel request ... now with large timeout value this async task is not cancelable ... if I want to close app, I have to wait until all threads completed ... looks not good for user to wait.

**Comment by yhirose** [comment]
@mrpuzzler, thanks for the detail.

`set_set_timeout_sec` setups TCP/IP **connection timeout**. Please see [this README descripbion](https://github.com/yhirose/cpp-httplib#connection-timeout).

Although I don't actively want to advertise, there is another timeout method `set_read_timeout`. This is for **reading timeout**. I haven't fully tested this API yet, since I simply didn't have time for it. But you can at least try to see if it can solve your problem. (If it works on your machine, I'll mention this API on README for other users.) Here is the method signature.

https://github.com/yhirose/cpp-httplib/blob/26deffe0c6a1e177e393416b94cdc0f340ca79bd/httplib.h#L690

If the `set_read_timeout` doesn't solve your problem. I have no idea to handle this honestly. Seeing the log from `curl -v` on your machine is an only way to get a clue for this problem. Thanks for your help in advance.

 > Also, we need a way to cancel request ...

Unfortunately, this is no crenelation feature on httplib::Client. I am not planning to provide it, since this is 'blocking' socket library. If you need the cancellation feature on client side, you may want to consider to try 'non-blocking' HTTP libraries which can give you such an opportunity. Sorry about that...

**Comment by mrpuzzler** [comment]
yhirose, do you have time to implement special non-blocking version for me? paid job? contact me at mrpuzzler@gmail.com

**Comment by yhirose** [comment]
@mrpuzzler, thank you for the kind offer. But it requires tons of work, and I am satisfied with this blocking HTTP library and there is no need non-blocking API in my projects. Sorry about that.

By the way, I found that a project called [SKALED](https://github.com/skalenetwork/skaled) forked my cpp-httplib library and they are trying to add **async** functionalities:
https://github.com/skalenetwork/skaled/pull/196
https://github.com/skalenetwork/skaled/blob/ad0e9906d4ec6173f9c0a03aaf2adb4f9f57b5d1/libskutils/include/skutils/http.h
https://github.com/skalenetwork/skaled/blob/ad0e9906d4ec6173f9c0a03aaf2adb4f9f57b5d1/libskutils/src/http.cpp
So you may want to contact them to see if their fork meets your requirement.

Anyway, thank you for showing interest in this library. I'll close this issue for now.

**Comment by mrpuzzler** [comment]
Thanks for the link

**Comment by yhirose** [comment]
https://github.com/skalenetwork/skaled/issues/219

**Comment by PixlRainbow** [comment]
technically, it is possible to cancel a connection even on a blocking socket. If you run the socket close or socket shutdown method of the request's socket from another thread, the request will be cancelled. But this behavior is not consistent across platforms.

**Comment by mrpuzzler** [comment]
yhirose, could you add this experimental feature to cancel the task? I can test it on iOS/Android/Window/Mac ...

**Comment by yhirose** [comment]
@mrpuzzler, it requires quite some changes in client code. I may think about it when I have time in the future.

Meanwhile, could you try the following for me to see the curl behavior? Thanks.

> If the set_read_timeout doesn't solve your problem. I have no idea to handle this honestly. Seeing the log from curl -v on your machine is an only way to get a clue for this problem. Thanks for your help in advance.

**Comment by mrpuzzler** [comment]
I have changed server load ... now it works much faster and looks like I can't catch this bug anymore. Anyway, I'll post here once I get it.

**Comment by yhirose** [comment]
@mrpuzzler, you may be interested in this comment. 
https://github.com/skalenetwork/skaled/issues/219#issuecomment-602492845
