### ISSUE TITLE
Add support for Botan SSL

### ISSUE THREAD

**Issue by mwasplund** [yhirose/cpp-httplib#380]
I am hitting issues with integrating OpenSSL into my project and wanted to see if there is any interest in integrating Botan as an alternative to OpenSSL for the SSLClient.

https://botan.randombit.net/handbook/index.html

**Comment by yhirose** [comment]
@mwasplund, thank you for your feedback. But I am personally not interested in adding the Botan SSL support at this point. (I am a bit interested in LibreSSL support, but I don't have time to work on it...) Thanks for your understanding. Of course, a pull request for Botan SSL support is very much welcome!

**Comment by mwasplund** [comment]
I'm curious why you would prefer LibreSSL over Botan? I just started looking into what is available for SSL support in C++ and the few discussions I could find pointed toward Botan as the best available C++11 library.

Side note: Can we also leave this issue open as a feature request and/or discussion for supporting more SSL libraries. That way others can weigh in if they have additional opinions on the available options or +1 if they would also use Botan support.

**Comment by yhirose** [comment]
@mwasplund, thank you for your comment. Honestly, I am not interested in both LibreSSL and Botan supports at this point, because OpenSSL is good enough to me in my projects. As you see the code, I spent quite some time to integrate OpenSSL and make it work in various test cases. So I simply don;'t have time to do the same work again for another SSL libraries... (This is just my 'after work' personal project. 😄) So I don't want to raise users's expectations by leaving this issue open. Of course, pull requests are always welcome. Thanks for your understanding!

**Comment by demon36** [comment]
sorry to bring this back up, just a thought here, the main advantages of this library is that the api is pretty easy to understand and it is very easy to include in another project, but with adding openssl to the picture with its dependency on perl and the prebuild scripts, the process of integrating cpp-httpib becomes a bit annoying. can the use of either botan or libressl help with this situation ?

**Comment by yhirose** [comment]
@demon36, thanks for the feedback, but I honestly don't know since I am not familiar to either library. Sorry about that...

**Comment by yhirose** [comment]
@demon36, I don't have time to work on those libraries though, pull requests are always welcome!

**Comment by demon36** [comment]
@yhirose taking the time to reply is much appreciated, also thanks for such a great library
@mwasplund do u have a recommendation for a TLS library that would make integration easier?

**Comment by mwasplund** [comment]
@demon36 I will admit that I only have a basic understanding of the different TLS libraries available, but this question was proposed for the exact reason that you bring up. I am working on a build system with an integrated package manager solution for C++ and having an https client with an easy to build encryption library is a must. From the quick investigations I did Botan seemed to have a much cleaner requirement set to build (not Perl or NASM), which would make it a lot easier to port from make/nmake to my solution.
