### ISSUE TITLE
Request path with + not accepted.

### ISSUE THREAD

**Issue by jims-1234** [yhirose/cpp-httplib#382]
A cpp-httplib server doesn't seem to like having a '+' in the request path.

Request.path replaces the + with a whitespace ' '

I've tried using my browser with both + and %2B, both having the same effect.

There maybe other special characters that do the same...?

Cheers

James

**Comment by yhirose** [comment]
@jims-1234, thanks for the feedback. It seems to a serious bug.
https://stackoverflow.com/questions/2678551/when-to-encode-space-to-plus-or-20

**Comment by yhirose** [comment]
@jims-1234, I think I fixed it. Could you try with the latest code?
