### ISSUE TITLE
Lack of performance tests

### ISSUE THREAD

**Issue by mfbalin** [yhirose/cpp-httplib#384]
Hello,

I am looking to for different networking libraries and I am looking for one that is easy to use such as your library. However, there doesn't seem to be any benchmarking for this library. I had some code that was using Pistache, and in tests that I was running on localhost, Pistache was performing 4-5 times better than cpp-httplib. Why might this be the case?

My application has lots of post requests with small payload and they are very frequent thus I am looking for latencies to be as minimal as possible.

**Comment by mfbalin** [comment]
In my case, I noticed that detail::select_read function takes 0.03 seconds, dominating the latency. Do you have any suggestions to optimize that part of the library? Or do you have any plans to optimize this?

**Comment by yhirose** [comment]
@mfbalin, I mainly focus on making this library cross platform, and giving an easy way to embed HTTP functionality to existing applications in my projects. Honestly, I haven't been using this library in a serious server which expects lots of requests simultaneously. Sorry about that...

`detail::select_read` is used for handling 'read timeout' and using `select` system call to do the work. Could you try to use `poll` implementation with `CPPHTTPLIB_USE_POLL` to see if it improves the performance? If the performance is still not acceptable and you don't need 'read timeout' functionality, you can just remove all the call sites of `detail::select_read`. Hope it helps!

**Comment by mfbalin** [comment]
Thanks for your reply! I tried polling and the performance is similar. In the case that I remove all the call sites of detail::select_read, what should I put for the return value of the function?

**Comment by yhirose** [comment]
#### What I meant by "you can just remove all the call sites of detail::select_read" is:

Change the following
https://github.com/yhirose/cpp-httplib/blob/e1acb949e74c663dc9dedc04e41d8bb0dfafb7c7/httplib.h#L1327-L1330
to
```cpp
    while (count > 0 && is_client_request) {
```
Change the following
https://github.com/yhirose/cpp-httplib/blob/e1acb949e74c663dc9dedc04e41d8bb0dfafb7c7/httplib.h#L2819-L2821
to
```cpp
inline bool SocketStream::is_readable() const {
  return true;
}
```
Remove the following entirely.
https://github.com/yhirose/cpp-httplib/blob/e1acb949e74c663dc9dedc04e41d8bb0dfafb7c7/httplib.h#L3368-L3372

You have to make the same change to all the call sites.

#### What I meant by "or always return true in the function" is:

Change the following

https://github.com/yhirose/cpp-httplib/blob/e1acb949e74c663dc9dedc04e41d8bb0dfafb7c7/httplib.h#L1175-L1177

to

```cpp
inline int select_read(socket_t sock, time_t sec, time_t usec) {
 return 1;
}
```

In this case, you don't have to do anything else.

I don't know if the above suggestions can really work, but I think it's worth to try them.
Please let me know your result. Thanks.

**Comment by mfbalin** [comment]
Unfortunately, it doesn't improve performance. Thanks for your concern though.

**Comment by yhirose** [comment]
@mfbalin, thanks for the result. But if the following doesn't solve the performance, it doesn't make sense that `detail::select_read` causes the latency problem, right? It seems like the real cause of this problem resides in a different place. If you find any other clue about the performance, please let me know. Thanks!

```cpp
inline int select_read(socket_t sock, time_t sec, time_t usec) {
 return 1;
}
```

**Comment by PixlRainbow** [comment]
`select_read` is a system call. Performance will vary from machine to machine, from OS to OS
