### ISSUE TITLE
Example for Get request which accepts param.

### ISSUE THREAD

**Issue by Kartikvk1996** [yhirose/cpp-httplib#385]
How to get 'Get' request parameters. No doc related to this.

Ex : localhost:9809/abc?param=123&param2=22
How to get param & param2.

I tried using req.get_param_value() function. No use at all, Nothing is returned.

The same applies to post requests.

Function
server.Post("(/abc)",[&](const httplib::Request& req, httplib::Response& resp)
    {
        std::cout<<"Request inflow\n";
        //if(req.has_param("param"))
        {
            std::string data(req.get_param_value("param"));
            std::cout<<data<<"\n";
            std::cout<<req.body<<"\n";
            for (auto it = req.params.begin(); it != req.params.end(); ++it) {
            const auto &x = *it;
                printf("%c%s=%s",(it == req.params.begin()) ? '?' : '&', x.first.c_str(),
                         x.second.c_str());
            }
        }
    });

**Comment by yhirose** [comment]
@Kartikvk1996, thanks for the feedback. I'll update the document when I have time. Here is how to access query values:

https://github.com/yhirose/cpp-httplib/blob/e1acb949e74c663dc9dedc04e41d8bb0dfafb7c7/test/test.cc#L889-L894

Hope it help!

**Comment by yhirose** [comment]
@Kartikvk1996, updated to the server example in README to show how to get header and query parameter values.

**Comment by Kartikvk1996** [comment]
Thanks @yhirose :-)
