### ISSUE TITLE
Winsock2.h problem and fix

### ISSUE THREAD

**Issue by nkindt** [yhirose/cpp-httplib#387]
Just including the header won't always work on Windows, resulting in tons of errors of the kind (around 1810 errors in my case):

Error	C2446	'!=': no conversion from 'long' to 'int (__cdecl *)(void)'
Error	C2027	use of undefined type 'fd_set' 
Error	C2375	'WSAAsyncGetServByName': redefinition; different linkage
...

The fix is to include Winsock2.h first (before Windows.h) or include Windows.h by defining WIN32_LEAN_AND_MEAN beforehand:
#define WIN32_LEAN_AND_MEAN
#include <Windows.h>

Might be good to mention this somewhere since otherwise it's not as easy as simply including the header and get going because of this.

**Comment by yhirose** [comment]
@nkindt, thanks for the feedback. I couldn't reproduce it. Here is what I did. 

#### a.cc
```cpp
#include "./httplib.h"
int main(void) {
  httplib::Client cli("localhost", 8080);
  cli.Get("/hi");
  return 0;
}
```

```
D:\cpp-httplib>cl a.cc /EHsc
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

a.cc
Microsoft (R) Incremental Linker Version 14.23.28106.4
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:a.exe
a.obj

D:\cpp-httplib>
```

Do I miss something to reproduce the problem? Thanks.

**Comment by dnlopez** [comment]
Ran into this myself just now - using Visual Studio 2017 Community, Windows 8.1 - and both of nkindt's fixes (either Winsock2.h, or WIN32_LEAN_AND_MEAN and Windows.h) work for me.

This is the first time I've tried to compile my previously Unix-based program on Windows, so I can't say whether this problem goes back any particular length of time. The opening of this thread is pretty perfect timing for me though! Thanks :)

**Comment by yhirose** [comment]
Thanks for the detail. I tried this with VS2019.

```cpp
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include "./httplib.h"
int main(void) {
  httplib::Client cli("localhost", 8080);
  cli.Get("/hi");
  return 0;
}
```

I still got the following errors:

```
D:\cpp-httplib>cl a.cc  /EHsc
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

a.cc
D:\Projects\cpp-httplib\./httplib.h(1788): error C2589: '(': illegal token on right side of '::'
D:\Projects\cpp-httplib\./httplib.h(1788): error C2062: type 'unknown-type' unexpected
D:\Projects\cpp-httplib\./httplib.h(1788): error C2059: syntax error: ')'
D:\Projects\cpp-httplib\./httplib.h(1789): error C3536: 'n': cannot be used before it is initialized
D:\Projects\cpp-httplib\./httplib.h(1808): error C2589: '(': illegal token on right side of '::'
D:\Projects\cpp-httplib\./httplib.h(1808): error C2062: type 'unknown-type' unexpected
D:\Projects\cpp-httplib\./httplib.h(1808): error C2059: syntax error: ')'
D:\Projects\cpp-httplib\./httplib.h(1809): error C3536: 'n': cannot be used before it is initialized
D:\Projects\cpp-httplib\./httplib.h(2872): warning C4003: not enough arguments for function-like macro invocation 'max'
D:\Projects\cpp-httplib\./httplib.h(2872): error C2589: '(': illegal token on right side of '::'
D:\Projects\cpp-httplib\./httplib.h(2872): error C2059: syntax error: ')'
D:\Projects\cpp-httplib\./httplib.h(2872): error C2612: trailing '>' illegal in base/member initializer list
D:\Projects\cpp-httplib\./httplib.h(4008): warning C4003: not enough arguments for function-like macro invocation 'max'
a.cc(9): fatal error C1004: unexpected end-of-file found

D:\cpp-httplib>
```

Something conflicts with `std::min`...
Anyway, I'll work on the bug when I have time. Thanks for the great report!

**Comment by yhirose** [comment]
By the way, I confirmed that this works:

```cpp
#include "./httplib.h"
#include <windows.h>
int main(void) {
  httplib::Client cli("localhost", 8080);
  cli.Get("/hi");
  return 0;
}
```

**Comment by nkindt** [comment]
> 
> 
> By the way, I confirmed that this works:
> 
> ```c++
> #include "./httplib.h"
> #include <windows.h>
> int main(void) {
>   httplib::Client cli("localhost", 8080);
>   cli.Get("/hi");
>   return 0;
> }
> ```

This works because Winsock2.h is included "before" Windows.h. The problem occurs if it's the other way around.

**Comment by nkindt** [comment]
> 
> 
> Thanks for the detail. I tried this with VS2019.
> 
> ```c++
> #define WIN32_LEAN_AND_MEAN
> #include <windows.h>
> #include "./httplib.h"
> int main(void) {
>   httplib::Client cli("localhost", 8080);
>   cli.Get("/hi");
>   return 0;
> }
> ```
> 
> I still got the following errors:
> 
> ```
> D:\cpp-httplib>cl a.cc  /EHsc
> Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x86
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> a.cc
> D:\Projects\cpp-httplib\./httplib.h(1788): error C2589: '(': illegal token on right side of '::'
> D:\Projects\cpp-httplib\./httplib.h(1788): error C2062: type 'unknown-type' unexpected
> D:\Projects\cpp-httplib\./httplib.h(1788): error C2059: syntax error: ')'
> D:\Projects\cpp-httplib\./httplib.h(1789): error C3536: 'n': cannot be used before it is initialized
> D:\Projects\cpp-httplib\./httplib.h(1808): error C2589: '(': illegal token on right side of '::'
> D:\Projects\cpp-httplib\./httplib.h(1808): error C2062: type 'unknown-type' unexpected
> D:\Projects\cpp-httplib\./httplib.h(1808): error C2059: syntax error: ')'
> D:\Projects\cpp-httplib\./httplib.h(1809): error C3536: 'n': cannot be used before it is initialized
> D:\Projects\cpp-httplib\./httplib.h(2872): warning C4003: not enough arguments for function-like macro invocation 'max'
> D:\Projects\cpp-httplib\./httplib.h(2872): error C2589: '(': illegal token on right side of '::'
> D:\Projects\cpp-httplib\./httplib.h(2872): error C2059: syntax error: ')'
> D:\Projects\cpp-httplib\./httplib.h(2872): error C2612: trailing '>' illegal in base/member initializer list
> D:\Projects\cpp-httplib\./httplib.h(4008): warning C4003: not enough arguments for function-like macro invocation 'max'
> a.cc(9): fatal error C1004: unexpected end-of-file found
> 
> D:\cpp-httplib>
> ```
> 
> Something conflicts with `std::min`...
> Anyway, I'll work on the bug when I have time. Thanks for the great report!

That's weird. Both arguments are size_t type. Might be a bug in MSVS. Does it help to add the type explicitly any chance? - std::min<size_t>(read_len, CPPHTTPLIB_RECV_BUFSIZ)

**Comment by dnlopez** [comment]
I've been running into that std::min and max issue today too, not just in httplib (though I wasn't able to fully reproduce it there, so I didn't mention it), but in some of my own code.

Adding the type explicitly as you just demonstrated, nkindt, did fix it.

Also "#define NOMINMAX" before "#include <Windows.h>" fixes it also - an idea I got from
https://github.com/nlohmann/json/issues/506

**Comment by nkindt** [comment]
> 
> 
> I've been running into that std::min and max issue today too, not just in httplib (though I wasn't able to fully reproduce it there, so I didn't mention it), but in some of my own code.
> 
> Adding the type explicitly as you just demonstrated, nkindt, did fix it.
> 
> Also "#define NOMINMAX" before "#include <Windows.h>" fixes it also - an idea I got from
> [nlohmann/json#506](https://github.com/nlohmann/json/issues/506)

Great catch! I missed that NOMINMAX define. That's definitely the culprit. No need for explicit type.

**Comment by yhirose** [comment]
Thanks for the great investigation. I took the same way as nlohmann/json does, so that users don't need to declare `NOMINMAX`.
https://github.com/yhirose/cpp-httplib/commit/685533ba500786e80aa97640ffd9cfb1c7d31288
https://github.com/nlohmann/json/commit/95474e420de25ec7db4875e889201229820ef564
https://stackoverflow.com/questions/27442885/syntax-error-with-stdnumeric-limitsmax/27443191#27443191

I'll update the README for Windows users later. Thanks for your great contribution!

**Comment by nkindt** [comment]
You are welcome! Thanks for the great library!

**Comment by zacario-li** [comment]
> If you include Windows.h before httplib.h then it should be repro. If you get those errors then a #define WIN32_LEAN_AND_MEAN before Windows.h should fix it.
> 
> The fix is to define WIN32_LEAN_AND_MEAN or reorder those 2 includes. Reordering isn't always a solution however especially in huge projects.
> 
> Edit: Visual Studio 2017

love you bro.
