### ISSUE TITLE
This is multi-threaded http server?  

### ISSUE THREAD

**Issue by 2020karaulov2020** [yhirose/cpp-httplib#388]
Possible to connect and process 1000+ clients at one moment ? (download static file, send / recv messages, etc)

(sorry if english bad language)

**Comment by PixlRainbow** [comment]
yes, but depends on available memory and CPU cores. You may need to adjust the value of `CPPHTTPLIB_THREAD_POOL_COUNT`.

**Comment by 2020karaulov2020** [comment]
@PixlRainbow thanks for answer!

What value needed for CPPHTTPLIB_THREAD_POOL_COUNT if i wan't to process more than 5000 clients at one moment ?

**Comment by aviezab** [comment]
Hi Amazing guys!
@yhirose @PixlRainbow I have done load testing to this library and died with only 40 concurrent/s. The amazing fact about this library is: when running stay with lower memory.


The testing is configured for 100 concurrents and 15 seconds hit.
![image](https://user-images.githubusercontent.com/34294278/77227285-bba8b280-6bb1-11ea-8c0c-5f5455e48f8f.png)
At the second of 14, the server segmentation fault.
![image](https://user-images.githubusercontent.com/34294278/77227258-95831280-6bb1-11ea-949b-56dfd1d55e31.png)

Please answer @2020karaulov2020 as I also needed the value of CPPHTTPLIB_THREAD_POOL_COUNT

**Comment by yhirose** [comment]
@2020karaulov2020, thank you for the question and comment. As @PixlRainbow mentioned, You have to figure out an appropriate value for your machine environment by adjusting `CPPHTTPLIB_THREAD_POOL_COUNT ` by yourself.

I just tried it with Apache Bench on my Ubuntu 18.04 on VirtulBox on 2016 MacBook, and put my results in example/1000-concurrency-result. I tested against example/simplesvr.cc without SSL support, and tried 1, 10, 20, 30 and 40 for `CPPHTTPLIB_THREAD_POOL_COUNT`, and run `ab -n 10000 -c 1000 http://localhost:8080/hello.cc > w1` (`w10`, `w20`, `w30` or `w40` depending on the count). In my case, a server with any thread pool count was able to handle 1000 concurrent requests successfully, but the thread count 20 is the fastest. I also put a diff3 result between w20 , w30 and w30 in `diff3-w10-w20-w30`.

I also put `check-hardware-concurrency-count.cc` which shows the result of `std::thread_hardware_concurrency()`. It uses this value in the built-in thread pool unless `CPPHTTPLIB_THREAD_POOL_COUNT` by user.

Hope it helps!

**Comment by yhirose** [comment]
@aviezab, thanks for the detailed report! As you can see my comment above, my test handles 1000 concurrent requests sent by Apache Bench successfully. So I just wonder where cpp-httplib crashes in your test case. Since this is an different issue, could you open an issue for this problem and explain the more detail? Thank you for your help!

**Comment by aviezab** [comment]
@yhirose thanks for reply.
I have found the solution, because this will be real implementation on production.

This is the example of the solution:
```
std::mutex muteks;
int main(){}
Server svr;
svr.Post("/", [&](const Request& req, Response& res) {
    muteks.lock();
    // YOUR CODE HERE
    muteks.unlock(); 
  });
}
```

It should be placed mutex lock and unlock for large and real concurrency system.
I got 1000 concurrents even more after test, and stable until about 1200 with i9 9900 processor.

**Comment by yhirose** [comment]
@aviezab, thanks for the solution. Glad to hear the result!
