### ISSUE TITLE
no parameters

### ISSUE THREAD

**Issue by 2020karaulov2020** [yhirose/cpp-httplib#392]
```
		svr.Post("/upload", [ & ](const Request& req, Response& res) {
		if (req.is_multipart_form_data())
		{
			std::cout << "params: " << req.params.size() << std::endl;
		}
```
I always got params:0

How to read parameters via httplib  ?

**Comment by 2020karaulov2020** [comment]
@yhirose 
Strange... Why **parameters** saved to **files**. This is error ?

**Comment by yhirose** [comment]
@2020karaulov2020, thanks for the feedback. It has been already discussed before, and here is the comment regarding this question. https://github.com/yhirose/cpp-httplib/issues/343#issuecomment-581913839
Hope it helps.
