### ISSUE TITLE
std::string::find usage inconsistent

### ISSUE THREAD

**Issue by ben-sol** [yhirose/cpp-httplib#397]
The problematic places are mostly the header-content-checks. But generally spoken, if the usage pattern (just an example!):
`if (!content_type.find("application/x-www-form-urlencoded"))`
 is intended, an explanation should be provided.
Note: in this particular case, I think it's a mistake as of lines 1627, 2692, 3228.

**Comment by yhirose** [comment]
@ben-sol, thanks for the feedback. I'll try to reproduce the problem. Could you give me the smallest possible code example to cause the problem? Thanks!

**Comment by ben-sol** [comment]
It's not a problem, it was a _code review_. Take it or leave it :)

**Comment by ben-sol** [comment]
Sorry for the inconvenience: I revisited the code portions and they are fine.
