### ISSUE TITLE
Brotli support ?

### ISSUE THREAD

**Issue by Rockybilly** [yhirose/cpp-httplib#400]
Is there a Brotli decompression support within httplib ? I received a response that is:

`Content-Encoding br`

Can it be decoded or do I need an external library ?

**Comment by yhirose** [comment]
@Rockybilly, thank you for the feecback. It doesn't support Brotili, and I am not planing to support it because I don't currently need it.

You may be able to add the Brotli support by your self by referring to the gzip support code in cpp-htpplib. A pull request is always welcome! 😄

**Comment by kdcz** [comment]
@Rockybilly this is what has worked for me, requiring https://github.com/google/brotli

```
class brotli_decompressor
        {
        public:
            brotli_decompressor()
            {
                decoder_s = BrotliDecoderCreateInstance(0, 0, 0);
                decoder_r = decoder_s ? BROTLI_DECODER_RESULT_NEEDS_MORE_INPUT : BROTLI_DECODER_RESULT_ERROR;
            }

            ~brotli_decompressor()
            {
                if (decoder_s)
                {
                    BrotliDecoderDestroyInstance(decoder_s);
                }
            }

            template <typename T>
            bool decompress(const char* data, size_t data_length, T callback)
            {
                if (decoder_r == BROTLI_DECODER_RESULT_SUCCESS || decoder_r == BROTLI_DECODER_RESULT_ERROR)
                    return 0;

                const uint8_t* next_in = (const uint8_t*)data;
                size_t avail_in = data_length;
                size_t total_out;

                decoder_r = BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT;

                while (decoder_r == BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT)
                {
                    char output[1024];
                    char* next_out = output;
                    size_t avail_out = sizeof(output);

                    decoder_r = BrotliDecoderDecompressStream(decoder_s, &avail_in, &next_in, &avail_out, reinterpret_cast<unsigned char**>(&next_out), &total_out);
                    
                    if (decoder_r == BROTLI_DECODER_RESULT_ERROR)
                    {
                        return false;
                    }

                    if (!callback((const char*)output, sizeof(output) - avail_out)) {
                        return false;
                    }

                }
                
                return decoder_r == BROTLI_DECODER_RESULT_SUCCESS || decoder_r == BROTLI_DECODER_RESULT_NEEDS_MORE_INPUT;
            }

        private:
            BrotliDecoderResult decoder_r;
            BrotliDecoderState* decoder_s;
        };
```

then in read_content(Stream& strm, T& x, size_t payload_max_length, int& status, Progress progress, ContentReceiver receiver) :

```
                brotli_decompressor brotli_decompressor;

                out = [&](const char* buf, size_t n) {
                    return content_encoding.find("br") != std::string::npos ? brotli_decompressor.decompress(
                        buf, n, [&](const char* buf, size_t n) { return receiver(buf, n); }) : decompressor.decompress(
                            buf, n, [&](const char* buf, size_t n) { return receiver(buf, n); });
                };
```

hopefully it helps you !

**Comment by yhirose** [comment]
@kdcz, sorry for the late reply. When I have time, I'll try to integrate it to the master. Thank you for your contribution!

**Comment by dyfet** [comment]
Probably "application/wasm" should also be added to can_compress.  Wasm is particularly favorable for use with brotli, too.

**Comment by yhirose** [comment]
@dyfet, I though the MIME type for .wasm should be 'application/wasm'. But it seems there is no entry for WASM in the official list, yet...
https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by yhirose** [comment]
@kdcz, I merged you code into the master branch. Thanks for your contribution!
By the way, do you have Brotli compressor code as well?

**Comment by hiltonj** [comment]
Hi, just to note I think this defaults to maximum quality `BROTLI_DEFAULT_QUALITY` (11) which can be quite slow. To set this to a lower value you can update the state after creation:

```
inline brotli_compressor::brotli_compressor() {
  state_ = BrotliEncoderCreateInstance(nullptr, nullptr, nullptr);
  BrotliEncoderSetParameter(state_, BROTLI_PARAM_QUALITY, 6);
}
```

Where the '6' is the quality, set between `BROTLI_MIN_QUALITY` (0) and `BROTLI_MAX_QUALITY` (11).

This library is great btw, thanks for all your efforts!

**Comment by yhirose** [comment]
@hiltonj thanks for the information. Could you make a separate issue for it? I'll keep it with 'enhancement' label. Thanks!
