### ISSUE TITLE
Add More Status Messages for the HTTP Status Codes

### ISSUE THREAD

**Issue by SoenkeHeeren** [yhirose/cpp-httplib#403]
I propose to add more status messages for the HTTP status codes.
A list of codes can be found here:
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

A pull request for one specific status code is already created, as I need this one for my project.

**Comment by SoenkeHeeren** [comment]
Pull request for status code 201:
https://github.com/yhirose/cpp-httplib/pull/402

**Comment by yhirose** [comment]
@SoenkeHeeren, thanks for the suggestion. I added missing status codes described in the MDN document.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

**Comment by SoenkeHeeren** [comment]
@yhirose Thanks for the quick response and implementation! :+1:
