### ISSUE TITLE
This is not critical error ?))

### ISSUE THREAD

**Issue by 2020karaulov2020** [yhirose/cpp-httplib#404]
https://github.com/yhirose/cpp-httplib/blob/171fc2e353d60989106117cc17cbe7ff9e8308fd/httplib.h#L2137

**cppcheck : Out of bounds access of s, index 's.size()' is out of bounds.**

_(and warnings: Uninitialized struct member: req.content_length, Member variable 'Client::proxy_port_' is not initialized in the constructor)._

**Comment by yhirose** [comment]
@2020karaulov2020, thanks for the feedback. But I think it's a false-positive detection on cppcheck, since the reference comes with `&`. If you still think is a critical error, could you show a smallest possible code example that reveals the problem that you think? Thanks!

**Comment by 2020karaulov2020** [comment]
@yhirose you disable this false positive ?)))

`split(&s[0], &s[s.size()], '&', [&](const char *b, const char *e) `
to 
`split(s.c_str(), s.c_str() + s.size(), '&', [&](const char *b, const char *e) `
or
`split(s.begin(), s.end(), '&', [&](const char *b, const char *e) `

**Comment by 2020karaulov2020** [comment]
@yhirose http://cpp.sh/2dcat

Why it do produce twice actions on '1=2' string ?

**Comment by 2020karaulov2020** [comment]
@yhirose possible it can be simplified. Just send std::string, and don't need be check for '\0'
