### ISSUE TITLE
Can't seem to get response from server 

### ISSUE THREAD

**Issue by mnik17** [yhirose/cpp-httplib#405]
Hi, 

I've been trying to send a multipart POST request to a server. I can't vouch for the server, since I haven't worked on it and just need to implement a client to communicate with it. 

So first of all I tried to just send an empty request using curl from the command line and here's what happened:

Request:
```
curl -X POST http://localhost:6666/web/mgw21/message/sendmultipart
```
Response:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><sendResponse version="1.0" code="500" info="the request doesn't contain a multipart/form-data or multipart/mixed stream, content type header is null"/>
```

The I tried the same thing using httplib, but I can't seem to get the response back: 

Request:
```
httplib::SSLClient m_cli{ "localhost:6666" }
std::shared_ptr<httplib::Response> m_res;
httplib::MultipartFormDataItems m_items;
m_res = m_cli.Post("/web/mgw21/message/sendmultipart", m_items, true);
std::cout << "Response: " << m_res->body << "\n";
```
I've used similar code before and I haven't had problems. This one compiles, but when I execute it `m_res` remains empty and when I try to print it, an exception is thrown. I also tried using `httplib::Client` but to no avail. Any idea why that might happen?

**Comment by PixlRainbow** [comment]
1. Your code does not check whether `m_res` is null to detect whether the server actually responded
2. Your client is connecting to host with domain name "localhost:6666" at default port (443 for https, 80 for http). It is assuming that 6666 is also part of the name localhost. Httplib does not automatically seperate port numbers in the name. Port numbers need to be provided as a second parameter.

**Comment by yhirose** [comment]
@mnik17, thanks for the report. Hope @PixlRainbow's comment helps you.

**Comment by mnik17** [comment]
Hi @PixlRainbow, @yhirose,

thanks for the fast answers. While I was aware that I wasn't checking if the response is null, I must've missed that I had to provide the port separately as an argument, so thanks for the tip, it works flawlessly now. 

I have another, this time more general question, but I don't think it's worth it to open a new issue for it, so I'll just use this thread. 

When I'm sending a file using a multipart POST request, is there a way to directly source the file from a given directory or should I load the contents and provide them as a parameter as showed in the example on the main page? 

Cheers

**Comment by PixlRainbow** [comment]
For now, you will have to handle file loading yourself
