### ISSUE TITLE
Streaming Motion JPEG

### ISSUE THREAD

**Issue by kienvu58** [yhirose/cpp-httplib#409]
Hi, does this library support streaming motion JPEG?
It means a client request a GET request and the server streams the sequence of JPEG frames with a special mime-type content type `multipart/x-mixed-replace;boundary=<boundary-name>`.

**Comment by PixlRainbow** [comment]
This library does not itself implement streaming MJPEG, and neither is it the responsibility of this library. This library is merely responsible for implementing the base HTTP standard and some helper functions.  

**However**, there is no reason you can't implement a MJPEG streamer *on top* of httplib by using [`set_content_provider` in server handler](https://github.com/yhirose/cpp-httplib#send-content-with-content-provider)

**Comment by kienvu58** [comment]
@PixlRainbow thank you, I appreciate your hint about implementing MJPEG streamer.

**Comment by spawnrider** [comment]
Hi,

Please let me know if you finally made it. 
I'm looking for the same thing.

**Comment by kienvu58** [comment]
> Hi,
> 
> Please let me know if you finally made it.
> I'm looking for the same thing.
I decided to use POCO library, which has more features and better documentation. Although, it is not header-only.
You can do this to stream motion jpeg:
```cpp
void handleRequest(HTTPServerRequest& request, HTTPServerResponse& response)
{
        response.setContentType("multipart/x-mixed-replace; boundary=--jpgboundary");
        cv::Mat frame = cv::imread("image.png");
        std::vector<uchar> buffer;
        cv::imencode(".jpg", frame, buffer);
        std::string str(buffer.begin(), buffer.end());
        std::ostream& ostr = response.send();
        MultipartWriter writer(ostr, "jpgboundary");
        while (true)
        {
            MessageHeader mh;
            writer.nextPart(mh);
            ostr << str;
        }
}
```
