### ISSUE TITLE
Better way to handle path parameter instead of using regular expression.

### ISSUE THREAD

**Issue by anarchyrucks** [yhirose/cpp-httplib#411]
Hi,

Is it possible to provide simpler way to handle path parameter instead of using regex in the url? Using regex directly is a bit unreadable and prone to errors.

Most of the http libs I've seen provide named path parameters such as **"/account/:user/profile/:section"**, which will then be parsed and provided as a map with keys "user" and "section".

I can work on this feature if it is an acceptable feature request.

Thanks.

**Comment by PixlRainbow** [comment]
Hi, note that this library is designed based on Express.js, which uses [*only* regex for path definition](https://expressjs.com/en/5x/api.html#path-examples).  

However, if you wish to implement a different path definition scheme, feel free to do so as long as you document it and create the corresponding tests.

**Comment by anarchyrucks** [comment]
Hi,

Although I'm not much familiar with ExpressJS, from what I have found they also provide [named path parameters](https://expressjs.com/en/guide/routing.html#route-parameters) in addition to regex.

**Comment by yhirose** [comment]
@anarchyrucks, I don't want to replace the regular expression way with the simpler way because my projects (and others) already depend on it. But it's acceptable if it can handle both together like `/user/:userId(\d+)`.

As @PixlRainbow mentioned, the pull request is always welcome as long as you document it and create the corresponding tests. Thanks!

**Comment by yhirose** [comment]
@anarchyrucks, if you need the named path parameters right now, you may be interested in Oat++. It supports it with this notation: `/users/{userId}`. Also it provides the similar simple API as cpp-httplib does. So it seems not to be difficult to migrate to Oat++. https://github.com/oatpp/oatpp
