### ISSUE TITLE
How to parse the data from post request?

### ISSUE THREAD

**Issue by huge818** [yhirose/cpp-httplib#412]
How to parse the data from post request?

post or put request, there is body data, it is **JSON** data, how to get it ?

maybe is not req.get_param_value,  or   req.get_file_value.

Can you help me ?

**Comment by yhirose** [comment]
@huge818, the post data is stored in req.body unless the content-type is 'application/x-www-form-urlencoded' or the content received is used in your request. cpp-httplib itself doesn't parse the body data. You can want to use a famous JSON library such as https://github.com/nlohmann/json.

You can find real examples by users here:
https://github.com/search?l=C%2B%2B&q=cpp-httplib+json+post&type=Code

Hope it helps!
