### ISSUE TITLE
Parallel execution of requests

### ISSUE THREAD

**Issue by Pramod-Devireddy** [yhirose/cpp-httplib#415]
Hi,
I am using your cpp-httplib library for server implementation.
Is there any provision to serve requests of multiple clients parallelly?

Each client request's response may contain huge JSON data. How can I send the data from the server in chunks and properly receive it at the client-side? May be with MultipartFormData?

Also what can be the maximum size of data(each chunk size) that can be sent from the server?

Please provide some examples. That would be of great help. Thank you.

**Comment by yhirose** [comment]
@Pramod-Devireddy, thank you for your feedback. I don't fully understand what you mean by 'multiple clients parallelly'. if you mean sending multiple contents in on HTTP response, you can probably do it with `ContentType: multipart/form-data` in your response. But it seems to be unusual in real world, and the cpp-httplib server doesn't give any support it and not planning to give the support. So you have do compose the response by yourself. (By the way, cpp-httplib client gives the multipart/form-data support with `MultipartFormData` structure which can be used to upload multiple files in one HTTP request.)

If you wan't to send a response by chunks, you can see information in README ('Send content with Content provider' and 'Chunked transfer encoding') and find examples in test/test.cpp.

Hope this explanation helps!

**Comment by PixlRainbow** [comment]
cpp-httplib uses a thread pool, as long as there are less clients than there are available threads, all clients will be served in parallel.
If you want to *stream* a single type of response (namely json) you can use content provider.
