### ISSUE TITLE
Add support for DELETE request body

### ISSUE THREAD

**Issue by altaitai** [yhirose/cpp-httplib#417]
According to MDN web docs (https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE), the DELETE request may have a body. Hence, support should be added, i.e. I will open a PR with the following changes to implement new functionality:
- Add `HandlersForContentReader delete_handlers_for_content_reader_` private member to `Server`
- Add `Server & Delete(const char *pattern, HandlerWithContentReader handler);` overload to `Server`
- Dispatch request with content to new DELETE handler with content in `Server::routing`

**Comment by yhirose** [comment]
@altaitai, thanks for your contribution! Could also add a corresponding test case in test/test.cc when you submit the PR? Thanks.

**Comment by yhirose** [comment]
Fixed by #418.
