### ISSUE TITLE
How to use a WebSocket with cpp-httplib?

### ISSUE THREAD

**Issue by yurivict** [yhirose/cpp-httplib#419]
Is there an example on how to use a WebSocket with cpp-httplib?

RFC: https://tools.ietf.org/html/rfc6455

**Comment by yhirose** [comment]
@yurivict, thank you for the question. Unfortunately, cpp-httplib doesn't support WebSocket. If you need WebSocket functionality, you may want to check https://github.com/uNetworking/uWebSockets. uWebSockets supports regular HTTP request as well. Thanks!

**Comment by yurivict** [comment]
Thank you.

**Comment by pfeatherstone** [comment]
uWebSockets depends on C++17 which isn't great for portability and haven't got it to work properly serving static files. You're library is really awesome and websocket support would be a great addition.

**Comment by yhirose** [comment]
@yurivict, thanks for the info!
