### ISSUE TITLE
std::regex constructor throw std::bad_cast

### ISSUE THREAD

**Issue by Piasy** [yhirose/cpp-httplib#422]
I'm using the `v0.5.8` tag, and [this line](https://github.com/yhirose/cpp-httplib/blob/v0.5.8/httplib.h#L3662) cause the issue:

```cpp
  const static std::regex re("(HTTP/1\\.[01]) (\\d+?) .*\r\n");
```

I'm building and running on Ubuntu 18.04 x64, using CMake, and compiler versions are:

```bash
# cc --version
cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# c++ --version
c++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

After some googling, I try to add `add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)` into my CMakeLists.txt, and it fix the issue.

Do you have any idea what's the reason? Can I rely on this fix? Thanks!

**Comment by yhirose** [comment]
@Piasy, thank you for the report. But I don't have any idea why that happens. The only thing that I can tell is that you should make sure if your compiler uses `--std=c++11` (`11` can be `14` or `17` of course). Hope it helps!

**Comment by Piasy** [comment]
Hi @yhirose , I have already set `-std=c++14`. Anyway, thanks for your response.
