### ISSUE TITLE
SSE Events

### ISSUE THREAD

**Issue by spriggsy** [yhirose/cpp-httplib#426]
After subscribing to a SSE event that is working well, how can the event be closed if the client refreshes his page?

At the moment if I refresh the page more than 5 times Chrome fails to load the webpage, I guess this is because the server is overloaded with too many still open SSE eventdispatchers?

Thanks

Spriggsy

**Comment by yhirose** [comment]
@spriggsy, I tested my SSE code example and confirmed it worked even after I refreshed the page on Chrome. Hope it helps.
https://github.com/yhirose/cpp-httplib/blob/master/example/sse.cc
