### ISSUE TITLE
Post response is empty

### ISSUE THREAD

**Issue by labriea** [yhirose/cpp-httplib#427]
Hi, 
I try to communicate with a REST api.  I can post a json, but the response is empty (res->content_length==0) and status is 200.

Did I miss something to allow a response from the server?
This is the code I'm using.
Cheers
Alex

#define CPPHTTPLIB_OPENSSL_SUPPORT

#include <stdio.h>
#include "httplib.h"

using string = std::string;
using namespace httplib;

int main()
{
    std::string szForm = "{\"Value1\": \"1\", \"Agent\": \"0.0.1.1\"}";
    httplib::Headers headers = {
        { "User-Agent", "TestAgent" },
        {"Accept","*/*"}
    };
    SSLClient cli("postman-echo.com");
    cli.set_ca_cert_path("./ca-bundle.crt");
    cli.enable_server_certificate_verification(true);
    auto res = cli.Post("/post", headers, szForm, "application/json"); 
    printf("SSL verify error: %u\n", cli.get_openssl_verify_result());
    if (res)
    {
        printf("res->status: %u\n",res->status);
        printf("res->content_length: %llu\n", res->content_length);
        if(res->content_length>0)
            printf("res->body: %s\n", res->body);
    }
    else
    {
        printf("res is null\n");
    }
    return 0;
}

**Comment by yhirose** [comment]
@labriea, thanks you for the question. But I can't help you much since I cannot see what the server exactly does. Your code itself looks good to me. Maybe the content of `szForm` is incorrect.

**Comment by labriea** [comment]
Hi, 
postman-echo.com is a test site people can get, post, put... I have the same behaviour with my test website (not accessible from the Internet).  If I do a get it works, if I do a post using libcurl it works, but the response using cpp-httplib is empty.
I noticed my szForm is missing the \\escape before " but that was a copy/paste issue.  I used that same value with libcurl successfully.
Good to know I'm not missing anything for post.
Cheers
Alex

**Comment by 3pa2Pro** [comment]
hola lo que pasa es que soy nuevo en c++ y tengo que realizar un post request a un servidor en https y e buscado en muchos lugares para ver si al igual que en algunos lenguajes de alto nivel, existe una especie de librería para eso en c++, he probado con varias y aun no me dan los resultados esperado ya que por postman todo funciona bien pero cuando trato de hacer el request desde el programa falla todo, es mas si cres que me pudieras ayudar un poco aunque sea teóricamente para entender y hacer funcionar esto, en aproximadamente 1h voy a probar tu librería aver que tal.
