### ISSUE TITLE
https:// sites try to connect with port 80.. (nevermind you can't use http:// or https://)

### ISSUE THREAD

**Issue by fatrolls** [yhirose/cpp-httplib#429]
tried this simple example

```
httplib::Client cli("https://highgamer.com");
cli.set_follow_location(true);
auto res = cli.Get("/");
Log("status = %d\n", res->status);
if (res->body.empty()) {
    Log("empty\n");
} else {
    Log("Got Len = %d\n", res->body.length());
    Log("Got Data = %s\n", res->body.c_str());
}
```

I didn't get any messages on screen.. no empty no Got Len, no Got Data.

I did some debugging and found the problem is at 

```
inline bool Client::send(const Request &req, Response &res) {
  auto sock = create_client_socket();
  if (sock == INVALID_SOCKET) { return false; }
}
```

it always would return false .. so I added some debugging and found out https:// tries to connect on port 80.

If I just did 

`httplib::Client cli("highgamer.com");`

without the `https://`

it works fine then.

I figured out my problem I need to use

`httplib::SSLClient cli("highgamer.com");`

and it would work, there isn't any SSLClient examples on the github page so I couldn't figure it out for a long time you should post a SSLClient example using GET.

also

`httplib::SSLClient cli("https://highgamer.com");`

also doesn't work..

P.S.>
I found a little bug you probably overlooked this

```
             [&](SSL * /*ssl*/, Stream &strm, bool last_connection,
                 bool &connection_close) {
               return callback(strm, last_connection, connection_close);
             });
```

There is a commented out ssl for the parameter idk why but I reinstated that comment back.

Question? do I need to compile with OpenSSL if my webserver uses plain http.. but has a redirect to https? also should I use `httplib::Client` or `httplib::SSLClient` as `httplib::Client` seems to work fine.. and `httplib::SSLClient` is a bit slower.

Okay I figured out I definitely need to link with 
`#define CPPHTTPLIB_OPENSSL_SUPPORT`
so ya I need OpenSSL regardless if I use Client or SSLClient because of the https redirect or else I get no output at all.

**Comment by PixlRainbow** [comment]
please click "close issue" if you think you no longer need assistance to mark this report as finished

**Comment by asfarley** [comment]
I was very surprised when I came to understand this behavior. The error message doesn't help much in this case. Yes, the README does give working examples, but it seems very surprising that the parameter for SSLClient's constructor cannot accept the https prefix, while the constructor for the regular Client can.
