### ISSUE TITLE
Is it possible use Client Put method without Content-Type header?

### ISSUE THREAD

**Issue by szclsya** [yhirose/cpp-httplib#436]
One of the server I'm dealing with uses an empty PUT method to trigger an event (and will return a 204 if successful). But it doesn't accept PUT methods with a `Content-Type` header.

Is there any way I can disable `Content-Type` when using the client's Put function? Or it is possible to add a Put function with only the path?

Thanks!

**Comment by yhirose** [comment]
@szclsya, I added `Post` and `Put` without body and content-type parameters. Hope you enjoy them!
