### ISSUE TITLE
DELETE request without a body fails

### ISSUE THREAD

**Issue by ben-sol** [yhirose/cpp-httplib#437]
... waiting in select until the read-timeout and stating SocketStream beeing not readable.

follow-up for #418 ?

**Comment by yhirose** [comment]
@ben-sol, thanks for the report. But the unit test on CIs (TravisCI, AppVeyor, GithubActions) works fine. I think it's caused by your network setting. Hope it helps.

https://github.com/yhirose/cpp-httplib/blob/05e02531950009409b365a7002fadd890e2b71b7/test/test.cc#L1898-L1903

**Comment by ben-sol** [comment]
nope. just use curl :)

**Comment by altaitai** [comment]
@ben-sol The DELETE with request body is actually very useful and required by standard. Original test case still passed, why reverting my commit for a non-issue ?
