### ISSUE TITLE
 endless loop in parsing multipart form-data headers

### ISSUE THREAD

**Issue by ben-sol** [yhirose/cpp-httplib#438]
Is the #396. again. closing the issues does not make the problems go away. you're welcome to flag them as 'postponed', but _please_, don't close them.

Reasons: state = 2 in the mentioned method has two holes (endless loop):
1. small input buffer. If you hit the limit, a partial header remains there.unparsable -> remains in state 2 == endless loop)
2. any other characters remaining in the first buffer (CR was in mine) between the fragments. A partial header remains ... (rest as before)

I git your need for 'examples' but you also may _look_ at the code :)
Still a promise... again....: example at weekend.

**Comment by yhirose** [comment]
Reopened #396.

**Comment by ben-sol** [comment]
Resolved in the current(0.7) version: it returns now false.
