### ISSUE TITLE
How to properly handle SIGTERM?

### ISSUE THREAD

**Issue by bstarynk** [yhirose/cpp-httplib#447]
With cpp-httplib commit 2feea0c9ab86939610cb83e for the [helpcovid](https://github.com/bstarynk/helpcovid) GPLv3+ project using httplib.h we are unable to properly handle SIGTERM.

Our [helpcovid issue #35](https://github.com/bstarynk/helpcovid/issues/35) document [here](https://github.com/bstarynk/helpcovid/issues/35#issuecomment-619356244) all the relevant details, including `gdb`  backtraces. Beware, we added two comment lines to your `httplib.h`  

On our side, the bug is absolutely reproducible.

Since our  [helpcovid](https://github.com/bstarynk/helpcovid) uses both `cpp-httplib`  and a [PostGreSQL](http://postgresql.org/) database, we absolutely need to handle `SIGTERM` properly (to at least stop web processing one one side, and stop database interaction on another side, all this in different C++ threads).

The [helpcovid](https://github.com/bstarynk/helpcovid)  project uses a [signalfd(2)](http://man7.org/linux/man-pages/man2/signalfd.2.html) approach to handle `SIGTERM`, explained [here](https://stackoverflow.com/q/61370635/841108)

It seems that some HttpLib `std::~thread`  destructors are improperly raising some exception, and then we get `std::terminate`-d.

Cheers.

Basile Starynkevitch, near Paris, France
<basile@starynkevitch.net>
http://starynkevitch.net/Basile/

**Comment by yhirose** [comment]
@bstarynk, this is a typical symptom of not joining a thread. 

https://github.com/bstarynk/helpcovid/blob/d61cbfe1f22e04dd966598825b4dc9b094bd76d1/hcv_background.cc#L249-L252

```cpp
  hcv_bgthread = std::thread([]()
  {
    hcv_background_thread_body();
  });
```

I don't see any where `hcv_bgthread` is joined. You must call `hcv_bgthread.join()` somewhere in your code before exit. Please try the solution to see if it fixed the problem.

Hope it helps.
