### ISSUE TITLE
set_proxy compile error

### ISSUE THREAD

**Issue by dotkt** [yhirose/cpp-httplib#449]
compile error:
"set_proxy": is not member of "httplib::Client" 
how to set proxy?

**Comment by yhirose** [comment]
@dotkt, thanks for the question. It's there in httplib::Client.

https://github.com/yhirose/cpp-httplib/blob/776b3ffbf95520047eb6e21ccdb9237eb5c4eaee/httplib.h#L721

Hope it helps!
