### ISSUE TITLE
Program terminated with signal 11, Segmentation fault.

### ISSUE THREAD

**Issue by guchuanhang** [yhirose/cpp-httplib#452]
`[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./hikversionApp'.
Program terminated with signal 11, Segmentation fault.
#0  httplib::detail::create_client_socket(char const*, int, long, std::string const&)::{lambda(int, addrinfo&)#1}::operat
    __closure@entry=<error reading variable: Cannot access memory at address 0xb9e1911a8>, sock=<error reading variable:
    ai=<error reading variable: Cannot access memory at address 0xb9e191168>, ai@entry=<error reading variable: Cannot ac
1502                close_socket(sock);
Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-id-2.23.2-61.el7_7.1.x86_64 openssl-devel-1.0.2k-19.el7.x86_64 openssl-libs-1.0.2k-19.el7.x86_64 pcre-8.32-17.el7.x86_64
(gdb) bt
#0  httplib::detail::create_client_socket(char const*, int, long, std::string const&)::{lambda(int, addrinfo&)#1}::operat
    __closure@entry=<error reading variable: Cannot access memory at address 0xb9e1911a8>, sock=<error reading variable:
    ai=<error reading variable: Cannot access memory at address 0xb9e191168>, ai@entry=<error reading variable: Cannot ac
Cannot access memory at address 0xb9e1911a8
(gdb)
#0  httplib::detail::create_client_socket(char const*, int, long, std::string const&)::{lambda(int, addrinfo&)#1}::operat
    __closure@entry=<error reading variable: Cannot access memory at address 0xb9e1911a8>, sock=<error reading variable:
    ai=<error reading variable: Cannot access memory at address 0xb9e191168>, ai@entry=<error reading variable: Cannot ac
Cannot access memory at address 0xb9e1911a8
(gdb) exit`
My App crash and show that problem. And this problem is hard to reappear. Any suggestion is appricate.

**Comment by PixlRainbow** [comment]
it is very difficult to see what is happening as your crash report is not formatted correctly and some of the lines are incomplete.
in addition, backtrace is not working correctly, and not showing a complete stack.

**Comment by guchuanhang** [comment]
thx.
