### ISSUE TITLE
URL parsing utilities

### ISSUE THREAD

**Issue by miketsts** [yhirose/cpp-httplib#453]
I came to a need similar to described in #357. But since my goal is different, I open a separate issue. Feel free to merge the two if you find it appropriate.

I'm implementing a REST client using this library. The first need is to create a proper client (either Client or SSLClient based on the server URL. Except that, my API endpoints can return hyperlinks to other APIs according to HATEOAS, and those links are full URIs including scheme, host and port. So, in order to use the same client, I need to parse the URI, strip out the scheme/host/port, and assert that this is the same site/port the client has been created for.
I have already implemented the if/else for Client/SSLClient creation, similar to what the author of #357 describes. Now I'm thinking about creation of a separate Url class which will mainly parse the full URL and allow to extract its parts (scheme, host, port, etc.).

BTW, as we all know that reading regular expressions in the code is nearly impossible :-), for parsing the URL I've taken the regex from https://tools.ietf.org/html/rfc3986#page-50, without modifications. and with the link and the explanation in the comments. I think this way the code will look more credible for those who inherits my code. The idea came from https://gist.github.com/curtisz/11139b2cfcaef4a261e0

I think there is a place in this library for URL management utilities. I believe many users implement the similar stuff themselves.

**Comment by yhirose** [comment]
@miketsts, thank you for your thought. However, I am not interested in providing the URL parsing utility at this point. I would like to focus on just the HTTP capabilities only. Sorry about that...

When it comes to the reference regex implementation at RFC3986, I have already used the reference implementation in cpp-httplib at two places. But I was not able to use it as it is. Each place has slightly difference requirement and the reference implementation didn't satisfy the need. So I had to make some modification at each place. It's hard to provide only one implementation that meets all the requirement with a simple way.

https://github.com/yhirose/cpp-httplib/blob/8333340e2cdf370d9c6ac4020e5fcaa1b2ece1da/httplib.h#L3954-L3955

https://github.com/yhirose/cpp-httplib/blob/8333340e2cdf370d9c6ac4020e5fcaa1b2ece1da/httplib.h#L5068-L5069

Anyway, the URL parsing capability is out of cpp-httplib responsibility, and I suggests users to look for existing C++ URL parsing/constructing utilities which are more useful and robust.

Anyway, thank you for your suggestion!
