### ISSUE TITLE
trivial level 4 warnings on ms vs_142, cpp2017

### ISSUE THREAD

**Issue by vacazboara** [yhirose/cpp-httplib#456]
I'd suggest fixing:
..\cpp-httplib\httplib.h(1518,45): warning C4100: 'ifn': unreferenced formal parameter
and
..\cpp-httplib\httplib.h(2852,65): warning C4458: declaration of 'status' hides class member

Thanks

**Comment by yhirose** [comment]
@vacazboara, thanks for the report!

**Comment by vacazboara** [comment]
wow, that was fast! thanks!
