### ISSUE TITLE
SSL Problem 

### ISSUE THREAD

**Issue by AlexWhiteS** [yhirose/cpp-httplib#458]
using an example site request with SSL

#define CA_CERT_FILE "/ca-bundle.crt"
#define CPPHTTPLIB_OPENSSL_SUPPORT

    httplib::SSLClient cli("https://mysite.ru", 80); 
    cli.set_ca_cert_path(CA_CERT_FILE);
    cli.enable_server_certificate_verification(true);
    auto res = cli.Get("/");
    if (res) 
    {
        cout << res->status << endl;
        cout << res->get_header_value("Content-Type") << endl;
        cout << res->body << endl;
    }
    else
    {

        auto result = cli.get_openssl_verify_result();
        if (result)
        {
            cout << "verify error: " << X509_verify_cert_error_string(result) << endl;
        }

    }
    system("pause");
I changed the port to 443, set HTTPS without the protocol - nothing helps. The console is empty. Only the standard label to continue, press the key.

**Comment by yhirose** [comment]
@AlexWhiteS, could you see the following example in test/test/cc?

https://github.com/yhirose/cpp-httplib/blob/ed1b6afa10f8749ce30734fc47b0e2f1847c09ea/test/test.cc#L2636-L2651

Hope it helps.

**Comment by AlexWhiteS** [comment]
Is there any way to do without google test?
And to connect to your site using the certificate "letnsenctypt" you need to use it in a local file or the certificate that you offer (ca-bundle)

**Comment by AlexWhiteS** [comment]
@yhirose

**Comment by PixlRainbow** [comment]
you are misunderstanding his reference. The google test he is quoting is to give you an example of how the client is intended to be used. He is not asking you to go through the google server.

If you look at the example code, you will notice that the client only references **domain name** NOT including the protocol. In other words, `"mysite.ru"` not `"https://mysite.ru"`.  
In addition, you have enabled certificate verification in `enable_server_certificate_verification(true)` which is not mandatory, although it helps improve security. The side effect is that the server's certificate MUST be signed by an authority that is present in `set_ca_cert_path(CA_CERT_FILE)` or the connection will be rejected by the client.

**Comment by AlexWhiteS** [comment]
I use a certificate from my site, which is officially signed letnsenctypt

**Comment by PixlRainbow** [comment]
you need to make sure letsencrypt's public CA cert is present in the bundle file. This means the authority's certificate, not *your* certificate.

**Comment by AlexWhiteS** [comment]
How can I get the file from the site and save it? used to urldownloadtofile

**Comment by PixlRainbow** [comment]
LetsEncrypt provides their authority certificates at https://letsencrypt.org/certificates/  
Note that the exact certificates that you need will depend on when you were issued a certificate.  
[This is a forum thread discussing a related issue.](https://community.letsencrypt.org/t/where-can-i-download-the-trusted-root-ca-certificates-for-lets-encrypt/33241/2)

**Comment by AlexWhiteS** [comment]
How can I get the file from the site and save it? before used to urldownloadtofile

**Comment by PixlRainbow** [comment]
Find the link that describes the PEM file that applies to you, and use urldownloadtofile with that link OR just save as from browser OR copy and paste text into notepad. The cert file extension is the same as the pem file extension, it is just to make it easier to tell that the file is a certificate and not a private key.

**Comment by srvasn** [comment]
I needed to include the certificate for `DST Root CA X3` to the `fullchain.pem` file issued by Let'sEncrypt certbot to get server certificate verification to work. DST is the signing authority for `Let's Encrypt Authority X3` which is in turn the signing authority for certificates issued by certbot.

The file from which I grabbed the certificate for `DST Root CA X3` can be found
[here](https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt).

**Comment by wagenaartje** [comment]
> I needed to include the certificate for `DST Root CA X3` to the `fullchain.pem` file issued by Let'sEncrypt certbot to get server certificate verification to work. DST is the signing authority for `Let's Encrypt Authority X3` which is in turn the signing authority for certificates issued by certbot.
> 
> The file from which I grabbed the certificate for `DST Root CA X3` can be found [here](https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt).

Could you elaborate more @srvasn? I downloaded the `DST Root CA X3` certificate from https://letsencrypt.org/certificates/ and added in the `fullchain.pem` given by Let's Encrypt certbot and still got the `SSLServerVerification` error.
