### ISSUE TITLE
select_write doesn't check if connection has been closed by peer

### ISSUE THREAD

**Issue by jraynal** [yhirose/cpp-httplib#459]
Hi there,

First, thank you for maintaining this really nice and lightweight library.

I was playing around with building a mjpeg streaming server, and encountered an issue: when a client leaves the stream, the stream would stay writable. I am not sure this is an expected behavior, and I was able to edit `select_write` so that it detects when the peer has closed the connections, and we should stop writing in it. It may no be the correct way to solve the issue.

<details><summary>  Example test </summary>

```cpp
#include <thread>
#include <future>
#include <iostream>
#include <iomanip>

#include <httplib.h>

int
main()
{
	constexpr char ep[] = "/stream";
	std::cerr << "Creating server\n";
	httplib::Server server;
	server.Get(ep, [](const httplib::Request&, httplib::Response& res){
		std::cerr << "Received connection\n";
		res.headers.emplace("Content-Type", "multipart/x-mixed-replace; boundary=---");
		res.set_chunked_content_provider([&](uint64_t, httplib::DataSink& sink)
			{
				static const std::string message{"\r\n-----\r\n\r\nA message in plain text\r\n"};
				while (sink.is_writable())
				{
					std::cerr << "Sending message to client\n";
					sink.write(message.data(), message.size());
				}
				std::cerr << "Client disconnected\n";
				
				static const std::string endMessage{"\r\n-------\r\n"};
				sink.write(endMessage.data(), endMessage.size());
				sink.done();
				std::cerr << "Response closed\n";
			});
	});

	auto fut = std::async(std::launch::async, [&server](){
		std::cerr << "Starting server\n";
		server.listen("0.0.0.0", 8080);
	});

	// Kicking background thread
	fut.wait_for(std::chrono::nanoseconds::zero());
	while (!server.is_running())
	{
		std::this_thread::yield();
	}
	std::cerr << "Server started\nStaring client...\n";

	httplib::Client client("localhost", 8080);
	client.Get(ep, [](const char* data, std::size_t size) {
		std::cerr << "Received: " << std::quoted(std::string(data, size));
		return false;
	});
	std::cerr << "Closed connection to server, killing server in a bit\n";

	std::this_thread::sleep_for(std::chrono::seconds(1));

	std::cerr << "Stopping server\n";
	server.stop();
	while (server.is_running())
	{
		std::this_thread::yield();
	}

	return 0;
}
```

</details>

<details><summary> Diff of my hack </summary>

```diff
diff --git a/httplib.h b/httplib.h
index d9611df..e5d4c4f 100644
--- a/httplib.h
+++ b/httplib.h
@@ -1228,7 +1228,15 @@ inline int select_write(socket_t sock, time_t sec, time_t usec) {
 
   auto timeout = static_cast<int>(sec * 1000 + usec / 1000);
 
-  return poll(&pfd_read, 1, timeout);
+  const auto status = poll(&pfd_read, 1, timeout);
+  if (pfd_read.revents != POLLOUT)
+  {
+	  return 0;
+  }
+  else
+  {
+	  return status;
+  }
 #else
   fd_set fds;
   FD_ZERO(&fds);
@@ -1238,7 +1246,16 @@ inline int select_write(socket_t sock, time_t sec, time_t usec) {
   tv.tv_sec = static_cast<long>(sec);
   tv.tv_usec = static_cast<decltype(tv.tv_usec)>(usec);
 
-  return select(static_cast<int>(sock + 1), nullptr, &fds, nullptr, &tv);
+  const auto status = select(static_cast<int>(sock + 1), nullptr, &fds, nullptr, &tv);
+  // Detect closed connection
+  if (status > 0)
+  {
+	return select_read(sock, sec, usec) > 0 ? 0 : status;
+  }
+  else
+  {
+	  return status;
+  }
 #endif
 }
 

```

</details>

I am working on Windows. I tested my hack in both Windows proper and WSL, it does behave as _I_ would expect. I followed the microsoft documentation to make the hack:

https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-select
https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsapoll

**Comment by yhirose** [comment]
@jraynal, thank you for the bug fix! I'll find time to check your code this weekend, and get back to you.

**Comment by yhirose** [comment]
@jraynal, I applied your fix to the latest httplib.h on my Mac OS. But regardless I use `poll` or `select`, I got the following result:

```
Creating server
Starting server
Server started
Staring client...
Bus error: 10
```

Here is my code when testing:

```cpp
inline ssize_t select_read(socket_t sock, time_t sec, time_t usec) {
#ifdef CPPHTTPLIB_USE_POLL
  struct pollfd pfd_read;
  pfd_read.fd = sock;
  pfd_read.events = POLLIN;

  auto timeout = static_cast<int>(sec * 1000 + usec / 1000);

  auto status = HANDLE_EINTR(poll, &pfd_read, 1, timeout);
  if (pfd_read.revents != POLLOUT) {
    return 0;
  }
  return status;
#else
  fd_set fds;
  FD_ZERO(&fds);
  FD_SET(sock, &fds);

  timeval tv;
  tv.tv_sec = static_cast<long>(sec);
  tv.tv_usec = static_cast<decltype(tv.tv_usec)>(usec);

  auto status HANDLE_EINTR(select, static_cast<int>(sock + 1), &fds, nullptr,
                      nullptr, &tv);
  if (status > 0) {
    return select_read(sock, sec, usec) > 0 ? 0 : status;
  }
  return status;
#endif
}
```

Could you try your change with the latest httplib.h, again? Also please show me what the result should look like? Thanks for your hlep!

**Comment by yhirose** [comment]
@jraynal, please see #469 that includes the hack.

When I tested your example code, it worked fine:

```
> ~/Projects/cpp-httplib$ g++ a.cpp -I./ -std=c++14

> ~/Projects/cpp-httplib$ ./a.out 
Creating server
Starting server
Server started
Staring client...
Closed connection to server, killing server in a bit
Stopping server
```

But a number of unit tests now fail...
https://github.com/yhirose/cpp-httplib/pull/469/checks?check_run_id=659497155

Could you try to run the unit test on your machine? (`test/test.sln` is the solution file for VC++)
Thanks for your help.

**Comment by DrBarbare** [comment]
Thank you for looking into it! I will try to run the tests on your branch. I did not call it a fix because I am not sure I thought about all the edge cases (or know of them, I am not very experimented in the ways of sockets).

What I have noticed is that `poll` may set `revents` to 0, but the reasons are not always very clear:

<details><summary> Not clear for POSIX http://man7.org/linux/man-pages/man2/poll.2.html </summary>

> The field revents is an output parameter, filled by the kernel with the events that actually occurred.  The bits returned in revents can include any of those specified in events, or one of the values POLLERR, POLLHUP, or POLLNVAL.  (These three bits are meaningless in the events field, and will be set in the revents field whenever the corresponding condition is true.)

and

>  The field fd contains a file descriptor for an open file.  If this field is negative, then the corresponding events field is ignored and the revents field returns zero.  (This provides an easy way of ignoring a file descriptor for a single poll() call: simply negate the fd field.  Note, however, that this technique can't be used to ignore file descriptor 0.)

</details>

<details><summary> Somehow clear wording in https://docs.microsoft.com/en-us/windows/win32/api/winsock2/ns-winsock2-wsapollfd </summary>

> For sockets that do not satisfy the status query, and have no error, the revents member is set to zero upon return.

</details>

Therefore it may be only necessary to check `POLLHUP` flag is set in `revents` to detect a disconnection. I would not know what to do with the `select` implementation.

Also of note, I am using the chunked content writer to send my custom multipart stream, so I may have overlooked other content senders as the one failing your unit tests.

I may also not be using the library correctly, as when I open my "stream" with the client chunk reader, I receive ghost messages even after closing the server response.

**Comment by jraynal** [comment]
Thank you for looking into it! I will try to run the tests on your branch. I did not call it a fix because I am not sure I thought about all the edge cases (or know of them, I am not very experimented in the ways of sockets).

What I have noticed is that `poll` may set `revents` to 0, but the reasons are not always very clear:

<details><summary> Not clear for POSIX http://man7.org/linux/man-pages/man2/poll.2.html </summary>

> The field revents is an output parameter, filled by the kernel with the events that actually occurred.  The bits returned in revents can include any of those specified in events, or one of the values POLLERR, POLLHUP, or POLLNVAL.  (These three bits are meaningless in the events field, and will be set in the revents field whenever the corresponding condition is true.)

and

>  The field fd contains a file descriptor for an open file.  If this field is negative, then the corresponding events field is ignored and the revents field returns zero.  (This provides an easy way of ignoring a file descriptor for a single poll() call: simply negate the fd field.  Note, however, that this technique can't be used to ignore file descriptor 0.)

</details>

<details><summary> Somehow clear wording in https://docs.microsoft.com/en-us/windows/win32/api/winsock2/ns-winsock2-wsapollfd </summary>

> For sockets that do not satisfy the status query, and have no error, the revents member is set to zero upon return.

</details>

Therefore it may be only necessary to check `POLLHUP` flag is set in `revents` to detect a disconnection. I would not know what to do with the `select` implementation.

Also of note, I am using the chunked content writer to send my custom multipart stream, so I may have overlooked other content senders as the one failing your unit tests.

I may also not be using the library correctly, as when I open my "stream" with the client chunk reader, I receive ghost messages even after closing the server response.

**Comment by yhirose** [comment]
@jraynal, thank you for the comment. I'll looking to this problem deeper when I have time.
Anyway, thank you for finding the bug that I didn't know!

**Comment by yhirose** [comment]
@jraynal, I fixed it. When I have time, could you test with the latest code? Thank you!

**Comment by jraynal** [comment]
Looks like it works. Sorry for misleading you with my hack! Thank you very much for your quick follow up though.
