### ISSUE TITLE
How can a server recieve Unicode string ?

### ISSUE THREAD

**Issue by dhiahassen** [yhirose/cpp-httplib#463]
How to extract Unicode string send in a get request ? Thanks <3

**Comment by PixlRainbow** [comment]
I'm not sure what you're asking. You are asking for how the *server* can *receive* data, but then you give the example of a GET request which cannot have body content.

**Comment by yhirose** [comment]
@dhiahassen, hope @PixlRainbow' answer helps you.

**Comment by dhiahassen** [comment]
So this is how issues are closed for this library ?

Due to timezone diffrence  , I wasnt able to read that at time, but it is clased in 3 hours.

Suppose thro an API a server is being sent text in chinise/arabic or another asian language , how to recieve it and convert it to wstring without currupting it , thanks

**Comment by PixlRainbow** [comment]
httplib receives data and processes it as if it is a raw binary blob. It does not alter the received data in any way during processing. The `std::string` contained in `Request::body` is merely a container that is used to store "raw data" with no regard to its encoding. You can safely implement your own wstring conversion on top of httplib, [for example, using `codecvt`](https://stackoverflow.com/questions/2573834/c-convert-string-or-char-to-wstring-or-wchar-t).  
Note that httplib is only designed to handle the basic HTTP receiving and sending functionality and to organize functions with paths; any additional data parsing or processing is up to you.
