### ISSUE TITLE
How to implement the progress bar in client?

### ISSUE THREAD

**Issue by bingzhe123** [yhirose/cpp-httplib#464]
Is there any solution to implement a progress bar when i post data in client?

**Comment by PixlRainbow** [comment]
We do not currently have a progress callback for POST requests at the time of writing but it is a feature we can add.  
However, if you are not using multipart posting, it is also possible to [implement your own stream writer](https://github.com/yhirose/cpp-httplib#send-content-with-content-provider) and then calculate progress that way.

**Comment by yhirose** [comment]
@bingzhe123, as you see the comment from @PixlRainbow.

I actually implemented the 'upload progress callback' in this branch this evening:
https://github.com/yhirose/cpp-httplib/tree/upload_progress

Could you try this branch if it satisfies your need? Thanks.

**Comment by bingzhe123** [comment]
@yhirose thank you for the help,I'll test it in the next few days

**Comment by yhirose** [comment]
@bingzhe123, just one more thing about the change. The upload progress works based on the return length from `strm.write(req.body.data() + offset, end_offset - offset)`. So if request body is not long, you don't benefit from this change.

https://github.com/yhirose/cpp-httplib/blob/b0f36e43454762d4e266761247789fa406fafb4b/httplib.h#L4148-L4157
