### ISSUE TITLE
Digest authentication error

### ISSUE THREAD

**Issue by bengomz** [yhirose/cpp-httplib#465]
The authentication code has error, the username is hardcoded to 'hello'.

  auto field = "Digest username=\"hello\", realm=\"" + auth.at("realm") +
               "\", nonce=\"" + auth.at("nonce") + "\", uri=\"" + req.path +
               "\", algorithm=" + algo + ", qop=" + qop + ", nc=\"" + nc +
               "\", cnonce=\"" + cnonce + "\", response=\"" + response + "\"";

changed to below and it works.
  auto field = "Digest username=\"" + username + "\", realm=\"" + auth.at("realm") +
               "\", nonce=\"" + auth.at("nonce") + "\", uri=\"" + req.path +
               "\", algorithm=" + algo + ", qop=" + qop + ", nc=\"" + nc +
               "\", cnonce=\"" + cnonce + "\", response=\"" + response + "\"";

**Comment by PixlRainbow** [comment]
bengomz is referring to these lines. The username is still using `"hello"` test value.

https://github.com/yhirose/cpp-httplib/blob/85637844c9cbd34c4087dfb914f8351b7fa13742/httplib.h#L2736-L2739

**Comment by yhirose** [comment]
@bengomz, thanks for finding my stupid bug...
@PixlRainbow, thanks for fixing the bug right away at #466.
