### ISSUE TITLE
Case sensitivity in regex for multipart/form-data

### ISSUE THREAD

**Issue by squashmode** [yhirose/cpp-httplib#47]
Some browsers seem to send metadata about MultipartFiles as lower-case 'content-type' and 'content-disposition'.  This seems to be consistent with the specification (RFC7578).  Currently, these are missed with this http server and are therefore not handled correctly.

The simple diff below changes the regex(es) that look for this metadata to case-insensitive and fixes this problem.

```
$ git diff httplib.h
diff --git a/httplib.h b/httplib.h
index 1716d0e..461c1e4 100644
--- a/httplib.h
+++ b/httplib.h
@@ -1026,10 +1026,9 @@ inline bool parse_multipart_formdata(
     static std::string crlf = "\r\n";

     static std::regex re_content_type(
-        "Content-Type: (.*?)");
+        "Content-Type: (.*?)", std::regex_constants::icase);
     static std::regex re_content_disposition(
-        "Content-Disposition: form-data; name=\"(.*?)\"(?:; filename=\"(.*?)\")?");
+        "Content-Disposition: form-data; name=\"(.*?)\"(?:; filename=\"(.*?)\")?", std::regex_constants::icase);

     auto dash_boundary = dash + boundary;
```

**Comment by yhirose** [comment]
@squashmode, thanks for the bug report. I implemented your solution and works fine.
Thanks again for your conrribution!
