### ISSUE TITLE
Unsigned undeflow in macro 

### ISSUE THREAD

**Issue by Malibushko** [yhirose/cpp-httplib#471]
`#ifndef CPPHTTPLIB_THREAD_POOL_COUNT
#define CPPHTTPLIB_THREAD_POOL_COUNT                                           \
  ((std::max)(8u, std::thread::hardware_concurrency() - 1))
#endif`
According to C++ documentation` std::thread::hardware_concurrency` can return 0 if information about threads is not available, in this situation we will have a unsigned underflow (and most likely crash).

**Comment by yhirose** [comment]
@Malibushko, thanks for the good catch!
