### ISSUE TITLE
Does this repo support TLS 1.3

### ISSUE THREAD

**Issue by Colfad** [yhirose/cpp-httplib#476]
Does this project support TLS 1.3 feature with boring-SSL?

**Comment by PixlRainbow** [comment]
we use automatic version negotiation disabling only the older SSL protocols, so if TLS 1.3 is available in the provided SSL library during compile time it should be used.  
However, `httplib.h` only explicitly `#include` openssl. You are not required to use the *original* OpenSSL, however the library that you provide must be API-compatible with OpenSSL 1.1.1 or above.

**Comment by Colfad** [comment]
Thx, I will try to use boringSSL seeing what it comes.

**Comment by yhirose** [comment]
@Colfad, hope the answer from @PixlRainbow helps you
