### ISSUE TITLE
any plans to generate documentation?

### ISSUE THREAD

**Issue by benman64** [yhirose/cpp-httplib#478]
or perhaps in source documentation as a start.

**Comment by yhirose** [comment]
Good question. But no plan at this point.

**Comment by graph** [comment]
will you accept such pull requests? Pull requests will likely be partial in doxygen format. I really like this library, but I keep having to check what the source code does.

**Comment by yhirose** [comment]
@graph, thank you for your offer! But I am not interested in document generators such as doxygen at this point. I am actually more interested in 'how to' documentation. (I agree that the current README document doesn't cover everything that cpp-httplib can do...)

Right now, I am focusing on completing all the necessary features, and making APIs easier to use. So when I feel cpp-httplib API design becomes mature enough, I'll spend more time on better documentation.
