### ISSUE TITLE
Race in startup/shutdown test code

### ISSUE THREAD

**Issue by sgraham** [yhirose/cpp-httplib#48]
I think this only really affects the test code, but I thought perhaps you would want to know.

In investigating a possible patch for #46, I split `listen()` into helper functions locally. After I did that I was experiencing an occasional crash in the server tests. I made a repro by adding a short sleep() in the body of listen() on master like this: https://github.com/yhirose/cpp-httplib/compare/master...sgraham:start-stop-crash?expand=1

When I run this (on a Mac), ASAN reports a crash in the thread: 
https://gist.github.com/sgraham/461f286144ef8c7e531dad75ec2960d1

I think this is because the `svr_.is_running()` in the test SetUp() passes while `listen()` is in the sleep, then the server is immediately stopped, *then* the thread continues on to `detail::select_read()`, but `svr_sock_` is now -1, so `select_read()` crashes in `FD_SET(-1, &fds)`.

(Sorry for the long explanation without a fix, I wasn't immediately sure where the correct place to synchronize would be.)

**Comment by yhirose** [comment]
@sgraham, thanks for the bug report. I fixed it at b6df220 with your nice test sample. Please let me know if you still have the problem. Thanks for your help!
