### ISSUE TITLE
Feature request: Stream output via std::ostream

### ISSUE THREAD

**Issue by thall** [yhirose/cpp-httplib#482]
Hi!

Thanks for a great library!

It would be nice if it was possible to stream large object, an example is when you have a large json object, and that library support streaming via `std::ostream`, and you then could do something similar to
```
...
res.getOutputStream() << json
```

This way you don't need to allocate an giant `std::string` upfront, that you then send.

**Comment by yhirose** [comment]
@thall, thanks for the feedback. 

I understand `std::ostream` is very convenient. But the current cpp-htpplib design doesn't allow is to be implemented easily... But there are ways to do what you want.

1) If `json` is a std::string, `res.body.swap(json)` or `res.body = std::move(json)` may work to avoid another memory allocation.

2) If `json` is a null terminated C string, we can use `ContentProvider` as below:

### Send content with Content provider
```cpp
svr.Get("/stream", [&](const Request &req, Response &res) {
  const char* json = nullptr;
  // Construct JSON string here...
  res.set_content_provider(
    strlen(json), // Content length
    [json](size_t offset, size_t length, DataSink &sink) {
      sink.write(json + offset, length);
      return true;
    },
    [json] { delete [] json; });
});
```

### Chunked transfer encoding

```cpp
svr.Get("/chunked-stream", [&](const Request& req, Response& res) {
  res.set_chunked_content_provider(
    [](size_t /*offset*/, DataSink &sink) {
      const char* json = nullptr;
      // Construct JSON string here...
      auto len = sink.write(json, strlen(json));
      assert(len == strlen(json));
      sink.done();
      delete [] json;
      return true;
    }
  );
});
```

If I am missing something, please let me know. Thanks!

**Comment by thall** [comment]
@yhirose thanks for the fast response!

Ah alright, sad to hear.

1. Isn't that was already happening here? https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L2916
2. Usually you have an JSON class object, that you want to serialize to a `string`. What I want to avoid is to allocate a giant `string`.

In you example with `content_provider` you must allocate the whole `string` before you can start to send it.

**Comment by yhirose** [comment]
@thall, I just implemented an experimental std::ostream object in DataSink at 25aa3ca982af822273957a58f791522634b68407.

It's still not a very simple way though, no data allocation is required at least.
Hope it can satisfy your need. 

### Send content with Content provider

```cpp
svr.Get("/stream", [&](const Request &req, Response &res) {
  res.set_content_provider(
    json.serialized_size(), // Content length
    [json](size_t offset, size_t length, DataSink &sink) {
      sink.os << json;
      return true;
    });
});
```

### Chunked transfer encoding

```cpp
svr.Get("/chunked-stream", [&](const Request& req, Response& res) {
  res.set_chunked_content_provider(
    [](size_t /*offset*/, DataSink &sink) {
      sink.os << json;
      sink.done();
      return true;
    }
  );
});
```

**Comment by PixlRainbow** [comment]
why not keep the old content provider implementation, and then just add a `res.getOutputStream()` like the original suggestion, which returns a new `std::ostream` that is merely constructed as a wrapper around `content_provider`?
So when a stream write operation is performed on the ostream, the streambuf will forward the written chars to the content provider. A queue of promises or futures can be used to synchronize between the content provider (called by server thread) and the ostream (called by producer thread)

**Comment by yhirose** [comment]
@PixlRainbow, thank you for the comment.

I have actually tried to keep the current content provider implementation as it is. Of course I added a new member `std::ostream os` in `DataSink`, but it doesn't affect at all to the current implementation.

This member is just a wrapper around the `DataSink` itself, and `sink.os << ???` calls `sink.write` internally. You can see the code below:

```cpp
class DataSink {
public:
  DataSink() : os(&sb_), sb_(*this) {}

  DataSink(const DataSink &) = delete;
  DataSink &operator=(const DataSink &) = delete;
  DataSink(DataSink &&) = delete;
  DataSink &operator=(DataSink &&) = delete;

  std::function<void(const char *data, size_t data_len)> write;
  std::function<void()> done;
  std::function<bool()> is_writable;
  std::ostream os;

private:
  class data_sink_streambuf : public std::streambuf {
  public:
    data_sink_streambuf(DataSink &sink) : sink_(sink) {}

  protected:
    std::streamsize xsputn(const char *s, std::streamsize n) {
      sink_.write(s, static_cast<size_t>(n));
      return n;
    }

  private:
    DataSink &sink_;
  };

  data_sink_streambuf sb_;
};
```

I'll stay with this simple approach for now.

**Comment by thall** [comment]
Thanks @yhirose for your implementation!
