### ISSUE TITLE
Using set_content_provider to serve large files closes connection

### ISSUE THREAD

**Issue by csk-ableton** [yhirose/cpp-httplib#486]
I'd like to use `set_content_provider` to serve large files in chunks, however the response connection closes unexpectedly. 

I've written a content provider for serving files, which fails from time to time. However here is a minimal example that consistently fails for me when using `curl`. I'd appreciate any help.

# Code

```cpp
int main(int, char**) {
  httplib::Server server;

  server.Get("/large-file", [](const httplib::Request&, httplib::Response& res) {
    const size_t chunkSize = 1024 * 1024;      // 1mb chunks
    const size_t dataSize = 1024 * 1024 * 500; // simulate a 500mb file
    auto buffer = new std::vector<char>(chunkSize, '!');

    res.set_content_provider(
      dataSize,
      [buffer, chunkSize](size_t, size_t length, httplib::DataSink& sink) {
        sink.write(buffer->data(), std::min(length, chunkSize));
        return true;
      },
      [buffer]() { delete buffer; });
  });

  server.listen("0.0.0.0", 80);

  return 0;
}
```

# Expected
Calling `curl http://localhost/large-file > test-file` downloads a 500mb large file

# Actual
The connection is closed and the file isn't transferred.

```
curl: (18) transfer closed with 434110464 bytes remaining to read
```

# Environment
OS: macOS 10.14.6
Version: v0.6.2
Flags: none

**Comment by yhirose** [comment]
@csk-ableton, thank you for the report. I have tried to reproduce it on my Mac OS, but I couldn't...
Are you using the latest httplib.h? If not, do you remember when you downloaded it?
Thank you!

**Comment by csk-ableton** [comment]
@yhirose Thank you for the quick reply. I tried this with version `v0.6.2`. I don't use any flags (like `CPPHTTPLIB_USE_POLL`). I can also reproduce this when trying to download the file over Google Chrome or Safari.

**Comment by yhirose** [comment]
@csk-ableton, thank you for the info. I am now able to reproduce the problem with v0.6.2. 
This problem should be fixed with this commit at https://github.com/yhirose/cpp-httplib/commit/01058659ab0733cfdee6ba731152661ed12b294f.

I have just release v0.6.3 including the above fix. Could you try with the newest version of httplib.h?

**Comment by csk-ableton** [comment]
@yhirose I just tried to reproduce the problem with v0.6.3 and multiple clients. I cannot reproduce the problem anymore, so it seems to be fixed. Thank you very much for the quick response!

**Comment by yhirose** [comment]
@csk-ableton, glad to hear that. All the credit should go to @ottigeda though. :)
