### ISSUE TITLE
Server's DELETE method

### ISSUE THREAD

**Issue by thehemen** [yhirose/cpp-httplib#489]
I'm trying to test some server's methods like PUT and DELETE.

```c++
Server svr;
svr.set_keep_alive_max_count(keep_alive_count);

svr.Put("/put", [&](const Request& req, Response& res)
{
    res.set_content("HTTP/1.1 201 Created", "text/plain");
});

svr.Delete("/delete", [&](const Request& req, Response& res)
{
    res.set_content("HTTP/1.1 204 No Content", "text/plain");
});
```

When I'm doing GET or PUT requests by Postman GUI, it works well. However, when i'm trying to use DELETE with address http://localhost:1234/delete/, it throws "400 Bad Request".

I'm not sure is it a library's trouble, but how to make it clear, is it a proper instruction?

**Comment by Abduvakilov** [comment]
@thehemen Have you fond a solution? I am getting similar issue and found why it is happening
If I send a `DELETE` request with no `Content-Length=0`, It is waiting for content and closing connection after ~5 seconds with 400 code.

**Comment by Abduvakilov** [comment]
Hmmm. Adding `const ContentReader &content_reader` to args solved the issue.
```C
[&](const Request& req, Response& res, const ContentReader &content_reader) { ... }
```

**Comment by thehemen** [comment]
> @thehemen Have you fond a solution? I am getting similar issue and found why it is happening
> If I send a `DELETE` request with no `Content-Length=0`, It is waiting for content and closing connection after ~5 seconds with 400 code.

Yes. I've just commented lines with ContentReader so that DELETE can't be processed WITH the body. For my personal task, that appeared to be enough...

**Comment by thehemen** [comment]
> Hmmm. Adding `const ContentReader &content_reader` to args solved the issue.
> 
> ```c
> [&](const Request& req, Response& res, const ContentReader &content_reader) { ... }
> ```

It's solved, thanks!

**Comment by yhirose** [comment]
@thehemen, @Abduvakilov, this is a bug in cpp-httplib. You shouldn't have to add `const ContentReader &content_reader`. I'll fix it soon. Thanks for finding the bug!

**Comment by yhirose** [comment]
I fixed it. Could you try with the latest httplib.h? If it works on your machines, I'll bump up the version number to v0.6.6. Thanks for you help.

**Comment by thehemen** [comment]
> I fixed it. Could you try with the latest httplib.h? If it works on your machines, I'll bump up the version number to v0.6.6. Thanks for you help.

It seems to be working now, with and without a body.
![Снимок экрана от 2020-05-25 12-48-11](https://user-images.githubusercontent.com/12379560/82782281-2ca46900-9e86-11ea-8fdc-b991e8062000.png)
