### ISSUE TITLE
Using an arbituary filename in the method's pattern

### ISSUE THREAD

**Issue by thehemen** [yhirose/cpp-httplib#490]
Say, I want to run this:
```c++
svr.Put("/article.html", [&](const Request& req, Response& res)
{
    res.status = 201;  // Created
});
```

However, that's not enough for me to use just one filename.

Is it possible to use different names like *.html?

**Comment by PixlRainbow** [comment]
the path parameter is a [regex pattern](https://cs.lmu.edu/~ray/notes/regex/). For example, you can use `".*\\.html$"` to match all files ending with `.html`. Note that you may need to tweak the pattern yourself to match any constraints you may have on file names.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the clear explanation!
