### ISSUE TITLE
Default TaskQueue does not implement on_idle

### ISSUE THREAD

**Issue by smlehbleh** [yhirose/cpp-httplib#491]
The default TaskQueue implementation doesn't implement on_idle which causes unnecessary CPU usage while the server is idle.

On average, CPU usage was 2% higher with an empty on_idle vs an implementation of on_idle with std::sleep(1 millisecond). (on an i7-8650U)

**Comment by yhirose** [comment]
@smlehbleh, thanks for the report. How did you measure the result?

**Comment by smlehbleh** [comment]
Hi, it was httplib.h from master about 3 days ago (I could try with a specific release instead). The result was measured with the htop command in Ubuntu with and without an on_idle implementation.

**Comment by yhirose** [comment]
@smlehbleh, one more question. Is your change is like this?

```cpp
  virtual void on_idle(){
    std::this_thread::sleep_for(std::chrono::milliseconds(1));
  };
```

**Comment by smlehbleh** [comment]
Hi,
I actually did usleep(1000), although I suspect it will be the same - I can experiment with the stdlib version

**Comment by yhirose** [comment]
@smlehbleh, I have tested on my macOS. Interestingly, the one with `std::this_thread::sleep_for` is actually slower (CPU usage 0.3%) than the empty one (0.2%). The difference is really tiny...

**Comment by yhirose** [comment]
@smlehbleh, it seems this performance depends on a user's machine. So I'll leave it as empty for now. Actually, the best thing you could do is set both `CPPHTTPLIB_IDLE_INTERVAL_SECOND` and `CPPHTTPLIB_IDLE_INTERVAL_USECOND` to 0. (Or you can do it with `Server::set_idle_interval` as well.) By doing this on non-Windows OS, you can completely skip this process. Thank you!

https://github.com/yhirose/cpp-httplib/blob/b3a40453008047c309235bb29a0a2c1315ab2bcc/httplib.h#L4016-L4027

**Comment by smlehbleh** [comment]
Hi, I see, ok thanks. What are the implications of setting
CPPHTTPLIB_IDLE_INTERVAL_SECOND and  CPPHTTPLIB_IDLE_INTERVAL_USECOND  to
0? From the code it looks like it would no longer read the socket? Would
that not cause any issues?

**Comment by yhirose** [comment]
@smlehbleh, `detail::select_read` just waits until incoming data arrives. If `val` is not 0, the latter code will actually read the data.
