### ISSUE TITLE
No notification or error handling on client timeout

### ISSUE THREAD

**Issue by TheNicker** [yhirose/cpp-httplib#495]
For example:
```
httplib::Client client("myserver.com", 80);
auto res = client.Post("/api/v5", "somePostData", nullptr);
// res is null on timeout
```

**Comment by PixlRainbow** [comment]
that is why all our examples surround `res` with an `if` statement -- if the client is unable to get a response for whatever reason, like network error, timeout or invalid domain etc, the response is `null`

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the explanation.
@TheNicker, sorry that cpp-httplib doesn't provide detailed error information... If you really need to detect timeout error, I recommend to use libcurl which gives you `CURLE_OPERATION_TIMEDOUT `.

**Comment by TheNicker** [comment]
@PixlRainbow , having return value of null is completely fine, not knowing why is unheard-of.

@yhirose , thanks for the reference. I need an http client for a mission critical application so it's obvious that httplib is not usable as-is as but it does have its advantages.

Inhibiting the ability to handle known and especially common use cases **"as design"** seems to me illogical in respect to software engineering as it introduces bugs in your use case even before writing a single line of code.

I would expect leaving it as an open bug, even if there's no intention to implement it. Debugging time could be saved for the next developer.

**Comment by yhirose** [comment]
@TheNicker, totally makes sense. I made a new issue #498 to remind me of this enhancement. Thanks!
