### ISSUE TITLE
This library has a conflict with libuv

### ISSUE THREAD

**Issue by Starfa** [yhirose/cpp-httplib#496]
I found this code in httplib.It will cause libuv bind error(invalid argument, windows 10).What does this code do?
```C++
template <typename Fn>
socket_t create_socket(const char *host, int port, Fn fn,
                       int socket_flags = 0) {
#ifdef _WIN32
#define SO_SYNCHRONOUS_NONALERT 0x20
#define SO_OPENTYPE 0x7008

  int opt = SO_SYNCHRONOUS_NONALERT;
  setsockopt(INVALID_SOCKET, SOL_SOCKET, SO_OPENTYPE, (char *)&opt,
             sizeof(opt));
#endif
......
}
```

**Comment by yhirose** [comment]
@Starfa, thanks for the report. That's actually the legacy code which was necessary to run `socket` function on Windows.

But I have changed `create_socket` to use `WSASocket` WinSock function at #164, and `WSASocket` doesn't need the workaround anymore.

I have just fixed it. Please let me know if this change solves the issue on you machine.
Thanks!

**Comment by Starfa** [comment]
Thank you! It works well, my issue has been solved.
