### ISSUE TITLE
WSASocket timeout

### ISSUE THREAD

**Issue by kdcz** [yhirose/cpp-httplib#497]
Hello,
I was testing the lib with residentials proxies (= time out very often) and I noticed that they don't time out but the `strm_.read` function would just hang forever.

Fixed it by adding the `WSA_FLAG_OVERLAPPED` flag and `SO_RCVTIMEO` socket option.

**Comment by yhirose** [comment]
@kdcz, thanks for the report. Could you send a pull request? Thanks!

**Comment by yhirose** [comment]
@kdcz, I now think your suggestion cannot be applied to cpp-httplib... Please see this comment, https://github.com/yhirose/cpp-httplib/issues/150#issuecomment-493052143.

> @aj3423, thanks for the report. Unfortunately, we cannot use WSA_FLAG_OVERLAPPED since this library uses a 'blocking socket'. If you want non-blocking behavior, I recommend you to use libuv-based socket libraries.
> 
> This library actually handles the timeout check for reading by using select function at https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L1721. (You can find more information at https://stackoverflow.com/questions/30395258/setting-timeout-to-recv-function/30395738#answer-30395738) So if it blocks at recv. the server that you are connecting to may have a problem. Is the server is a public server that I can also connect?
