### ISSUE TITLE
Better error handling on Client

### ISSUE THREAD

**Issue by yhirose** [yhirose/cpp-httplib#498]
Currently, the client API returns `std::shared<httplib::Response>` if the request succeeds. Otherwise , API returns just `nullptr` and doesn't give any additional error information such as connection timeout.

It is desirable to add an error report mechanism to the existing client API without breaking existing users' code.

**Comment by yhirose** [comment]
`get_last_error` could be added which simply returns `errno` on non Windows and calls `WSAGetLastError` on Windows.

**Comment by Chao-Zeng** [comment]
hope this feature can be develop as soon as possible. otherwise, it's hard to know why res is nullptr.

**Comment by TheNicker** [comment]
One solution would be to always return a valid `std::shared<httplib::Response>` (never null)  and to overload `nullptr_t` operator and mark it deprecated so users would know not to use that as the compiler generates a warning.

The implementation of `nullptr_t` operator will check whether connection has failed, in that case comparison against null will return true.

Another more comprehensive solution would be to carefully rethink the error handling system, branch the library to a new major version. refactor and apply any desired changes. Most of the effort would go to the new branch, while some effort that will fade over time would go to the current branch, so virtually there are no breaking changes.

**Comment by yhirose** [comment]
```cpp
#include <iostream>

struct Body {
  Body() = default;
  Body(Body&& rhs) = default;
  Body& operator=(const Body& rhs) {
    std::cout << "assignment operator is invoked..." << std::endl;
    std::cout << "unnecessary copy takes place..." << std::endl;
    return *this;
  }
};

struct Response {
  Body body;
};

struct Client {
  bool send(Response& res) { return true; }
  Response Get() { Response res; send(res); return std::move(res); }
};

struct Client2 : public Client {
  Response Get() { return cli_.Get(); }
  Client cli_;
};

int main() {
  Client2 cli;

  Response res;
  res = cli.Get();
}
```

```bash
 ~/tmp$ g++ -std=c++11 a.cpp && ./a.out 
assignment operator is invoked...
unnecessary copy takes place...
```

**Comment by TheNicker** [comment]
Separating deceleration from initialization when declaring 'Response' prevents RVO from kicking in, copy assignment shouldn't occur and furthermore the other way around should be faster.

As depicted in the following snippet:
https://godbolt.org/z/b7KGhs

One thing that I left out for full backward compatibility was also to overload the dereference operator.
If declaring it const break changes then constness can be removed:
```
[[deprecated("Structure dereference operator (->) is deprecated, for accesing members please use the Structure reference operator (.) instead.")]]
const Response* operator->() const
{
	return this;
}
```

**Comment by yhirose** [comment]
@TheNicker, I was using `Response res; res = cli.Get();` just as an example that users may easily fall into unknowingly. That's why I don't prefer returning an object instead of a smart pointer that will never cause such unintentional copying of body text which might contain Giga bytes. Anyway, thanks for your suggestions!

**Comment by TheNicker** [comment]
In principle compilers nowdays would warn you about such behaviour, but I can see that this path won't bear fruit as new to some experienced developers usually don't pay attentions to these nuances, thus I would greatly would like to see the code gets internally forked, for maybe even a substantial make over.

**Comment by yhirose** [comment]
`std::expected` or `throw`:
https://www.reddit.com/r/cpp/comments/c75ipk/why_stdexpected_is_not_in_the_standard_yet_is_it/

**Comment by TheNicker** [comment]
I think that the fundamental idea of std::expected is very good , but I would bet against it getting into the standard.
The C++ committee is taking the dual exception handling system very seriously, but according to progress I would except to  see it maybe in C++(26).

`std::expected` - I believe not.
`throw` -  If it was (allegedly) 2026 and Herb Sutter's ideas from his talk last year at CPP con would come to realization then throw all the way, but currently the library **doesn't actively throw even once**, so it might be worth keep it that way and even remove the API calls that do throw and mark noexcept whenever possible.

**Comment by yhirose** [comment]
#601

**Comment by yhirose** [comment]
Boost Outcome: https://ned14.github.io/outcome/

**Comment by yhirose** [comment]
#601 

https://github.com/yhirose/cpp-httplib/blob/654bf22e0640c5b32b25e8b673973c26e144f3bc/test/test.cc#L3234-L3254

**Comment by yhirose** [comment]
It required massive changes though, I have finally finished my first draft.
https://github.com/yhirose/cpp-httplib/pull/601/files
