### ISSUE TITLE
Better support for Keep-alive on the client side

### ISSUE THREAD

**Issue by gatopeich** [yhirose/cpp-httplib#499]
Not being able to keep a connection alive renders this library unusable for many projects.

The so-called "keep-alive Client API" (see #369) is not usable for anything beyond very basic testing of the server.
```
bool Client::send(const std::vector<Request> &requests, std::vector<Response> &responses)
```
This just sends a pre-canned batch of requests... Can't see how to use that in real life.

The client should just not send "Connection: close" by default. Let the user, or the server, decide what to do if it is too hard to do it in the client code.

In this case just don't add Connection headers if user doesn't. As usual, less is more.

**Comment by yhirose** [comment]
@gatopeich, thanks for the feedback. I am sorry that I haven't found time to work on it so far... It also relates to the longstanding issue #6.

If you need the Keep-alive connection on client now, I recommend you to use libcurl which supports Keep-alive connection as default. It's anyway more robust, and it has more nice features. :)

Thanks for bringing it up again. I'll leave this issue open for a while.

P.S. I'll quote my comment in #369 for your reference:

> thank you for the detail. Yes, you are totally right! I understand the regular Client API should set 'keep-alive' to 'Connection' header. But it's difficult to implement to keep the same connection over more than one requests right now due to the defect of the regular Client API design. I would like to fix it, but it requires fundamental changes in this library. In the future, I may get back to this. Sorry for causing the inconvenience...
> 
> Because of that reason, I provided the 'Keep-Alive' Client API as a workaround. Of course, I understand that this workaround doesn't solve all the problems. @PixlRainbow has already mentioned a problem that the batch client API cannot solve in his comment #45 (comment). That's why I still cannot solve #45 (SSE (Sever-Sent Events) support on client). (As a matter of fact, it was pretty easy for me to handle 'Keep-Alive' connection in the server and the batch client APIs.)
> 
> Thank you for your consideration for the problem. :)

**Comment by gatopeich** [comment]
Yep. It is a very promising library but Keep-alive should work by default.

Why don't you just leave it on the server's hands?

On the client side I would assume connections always keep alive unless the server sends `Connection: close` header, or the user adds `Connection: close` explicity.

Would that really require big changes?

**Comment by gatopeich** [comment]
I don't get the resource management issue. You can always close the socket on destruction.

Honestly if your "Client" became a "ClientSession" (Client+KeepAlive), we would have here a very attractive HTTP library... Maintenance costs would increase due to the growth in user base!

**Comment by yhirose** [comment]
@gatopeich, please check an experimental version on `keepalive-on-client` branch. It supports the Keep-Alive connection on Client that you requested. For backward compatibility, the default behavior is not keep-alive currently. You have to call `cli.set_keep_alive(true)`.

```cpp
httplib::Client cli("localhost", 1234);

// Default is not Keep-Alve for backward compatibility
cli.Get("/path");         // with "Connection: close"
cli.Get("/path");         // with "Connection: close"
cli.Get("/path");         // with "Connection: close"

// Keep-Alive
cli.set_keep_alive(true);
cli.Get("/path");
cli.Get("/path");
cli.Get("/path");

// For the last request
cli.set_keep_alive(false);
cli.Get("/last-request");  // with "Connection: close"
 or
cli.Get("/last-request", {{"Connection", "close"}});  // with "Connection: close"
```

As you can see the above example, one drawback of this approach is that the server doesn't receive the final request with "Connection: clone" unless a user calls `set_keep_alive(false)` or sets the HTTP connection header manually.

Since the really extensive code changes were required to support the feature, could you test this version on your environment as soon as possible  to see any problems before it will be merged into the master?

Thanks a lot for your help!

**Comment by yhirose** [comment]
I have merged it to the master.

**Comment by gatopeich** [comment]
Wow this looks good, thanks 🙂
I will test ASAP.
(It may take a while cause I am quite busy ATM).
