### ISSUE TITLE
Poor performance on VPN

### ISSUE THREAD

**Issue by guteksan** [yhirose/cpp-httplib#501]
Hi,
This is a follow-up of the issue: https://github.com/yhirose/cpp-httplib/issues/424, which was closed, as I couldn't provide an update at that time. Finally I managed to prepare a new analysis of performance of various C++ REST frameworks, including Httplib, and provide projects I used for my tests:
https://github.com/guteksan/REST-CPP-benchmark
I hope this will help you find the bottleneck in Httplib.

**Comment by yhirose** [comment]
@guteksan, fantastic! Honestly, I haven't focused on performance very much so far. I believe it can be a nice performance measurement tool!

**Comment by yhirose** [comment]
@guteksan, I just tried to build basic-httplib on my macOS, but I got some compile errors with log4cplus stuf... I'll fix the build errors this weekend, then start performance improvement.

When I checked your web site, I noticed that the benchmark uses v0.5.8. The latest one is v.0.6.6, right now. Is it possible to measure performance with the latest as baseline on your site?

Also there is another very good HTTP server library [oat++](https://github.com/oatpp/oatpp). I recommend you to include it in your benchmark as well.

Thanks for your great work!

**Comment by guteksan** [comment]
@yhirose , sorry, it is not clear to me from your log what you did exactly. Did you clone log4cplus into basic-httplib project folder, and then tried to build basic-httplib? The correct way is to clone log4cplus repo separately, build it and install, and then build basic-httplib. Alternatively, you can install log4cplus in the system using apt-get (some version should be available in Ubuntu packages). Unfortunately I may not be able to help you with building log4cplus, as I never built it myself.

Thanks for the tip with oat++. I'll look it up.

**Comment by yhirose** [comment]
@guteksan, I gave up getting it up running... When you have time, could you update httplib.h to the latest version in your project? I just would like to see how much the current master improved the performance. Thanks!

**Comment by yhirose** [comment]
@guteksank, I have just send a pull request to your repo. Could you do the benchmark test again, since I can't run the benchmark on my machine? Thanks a lot!
https://github.com/guteksan/REST-CPP-benchmark/pull/4

**Comment by yhirose** [comment]
@guteksan, since I don't hear from you a while, I'll close it for now since the version cpp-httplib is not pretty old, and the benchmark may not reflect the current performance of cpp-httplib.
