### ISSUE TITLE
Client2 implementation makes it impossible to compile with -fno-rtti

### ISSUE THREAD

**Issue by Bendr0id** [yhirose/cpp-httplib#504]
The dynamic_casting makes it impossible to compile with -error: ‘dynamic_cast’ not permitted with the ‘-fno-rtti’ compile flag.

`error: ‘dynamic_cast’ not permitted with ‘-fno-rtti’`

Something you could do:

```
#ifdef CXXOPTS_NO_RTTI
      return static_cast<SSLClient &> ....
#else
      return dynamic_cast<SSLClient &> ....
#endif
```

Or just search and replace `dynamic_cast` with `static_cast`

**Comment by yhirose** [comment]
@Bendr0id, thanks for the report. In fact, if `is_ssl` is true, we can safely cast it into SSLClient with `static_cast`. I'll make the change soon. Thanks for the report!
