### ISSUE TITLE
Use of SO_REUSEADDR

### ISSUE THREAD

**Issue by vshu3000** [yhirose/cpp-httplib#506]
```
1908     // Make 'reuse address' option available
1909     int yes = 1;
1910     setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, reinterpret_cast<char *>(&yes),
1911                sizeof(yes));
1912 
1913 #ifdef SO_REUSEPORT
1914     setsockopt(sock, SOL_SOCKET, SO_REUSEPORT, reinterpret_cast<char *>(&yes),
1915                sizeof(yes));
1916 #endif
```

So now it always reuses socket.  The line outside ifdef should be removed.

**Comment by vshu3000** [comment]
The code actually always tries to reuse port.  That means in my case two servers can bind to the same port without causing EADDRINUSE.  This is unexpected behavior.

**Comment by yhirose** [comment]
@vshu3000, are you saying that line 1910-1911 should be removed?

**Comment by yhirose** [comment]
We need to handle this matter carefully according to the following information:
https://stackoverflow.com/questions/14388706/how-do-so-reuseaddr-and-so-reuseport-differ
