### ISSUE TITLE
URL with subdomain doesn't work

### ISSUE THREAD

**Issue by prophetl33t** [yhirose/cpp-httplib#510]
httplib::Client cli("api.shodan.com");
auto Res = cli.Get("/tools/myip");

Res always equals null.

URL without subdomain works fine.

**Comment by yhirose** [comment]
@prophetl33t, thanks for the feedback, but I don't think it's a problem of cpp-httplib. Does it happen with curl as well?

**Comment by prophetl33t** [comment]
@yhirose Nope, everything is okay when i use curl.

**Comment by yhirose** [comment]
@prophetl33t, thanks for the additional info. But I honestly don't know why that happens.
Here are test cases that shows httplib::Client is working with subdomain:

https://github.com/yhirose/cpp-httplib/blob/aea60feb850d837a8d68f65be96b11efae9ca690/test/test.cc#L641-L652

https://github.com/yhirose/cpp-httplib/blob/aea60feb850d837a8d68f65be96b11efae9ca690/test/test.cc#L2747-L2756

**Comment by prophetl33t** [comment]
Your test examples with YT and yahoo are working for me. It's something with URL i used (api.shodan.io). It works with curl and it works in httplib without subdomain (shodan.io).

**Comment by yhirose** [comment]
@prophetl33t, I don't have any problem with subdomain at all. (cpp-httplib calls just `getaddrinfo` to resolve the hostname.)

Sorry for the problem that you are having though, I'll close it for now until more specific evidences are reported. Thanks for your understanding!

**Comment by PixlRainbow** [comment]
Did you compile with openssl support?
