### ISSUE TITLE
Support response compression of client request

### ISSUE THREAD

**Issue by leeyiw** [yhirose/cpp-httplib#515]
Hello, Currently the `CPPHTTPLIB_ZLIB_SUPPORT` only affect the request compression of client request. The client can't add a `Accept-Encoding: gzip` header to enable server side response compress. The `Client::set_compress()` API only enable the request body's compress.

It would be nice if cpp-httplib add this small feature.

**Comment by yhirose** [comment]
@leeyiw, thanks for the question. The server actually can send compressed data if a request from client has a proper `Accept-Enclding` header. Hope the following test case helps you to understand it.

https://github.com/yhirose/cpp-httplib/blob/919a51091f4dd73f6b93b5bf3059b9d4c3117718/test/test.cc#L2158-L2172

**Comment by leeyiw** [comment]
@yhirose Got it. But it's not so convenient for users. :-)
