### ISSUE TITLE
[Question] How to setup a client for connecting to the google server and issue command.

### ISSUE THREAD

**Issue by seccpur** [yhirose/cpp-httplib#516]
**Intention**
Need to setup a client for connecting to the google server to issue a command to update a shared googlesheet.  Typing 
> https://script.google.com/macros/s/MyApiKey/exec?StnID=E732323&Date=19/03/2020&Time=14:49:26&Power=70&Refl=1&Status=ON

 on the browser directly works find, but I want to use cpp-hhtplib from a c++ program. Here's what I have tried using your example implementation , but without success. 

**Code**

```
int main(void) {
    httplib::Client cli("https://google.com", 80);

    auto res = cli.Post("/post", "/macros/s/MyApiKey/exec?StnID=E732323&Date=06/06/2020&Time=14:49:26&Power=70&Refl=1&Status=ON", nullptr);

    assert(res->status == 200);

    return 0;
}
```

**Result**

D:\Projects\Sender\x64\Debug\Sender.exe (process 2864) exited with code -1073741819.

**Comment by yhirose** [comment]
Please see the 'IMPORTANT' message in the example:
https://github.com/yhirose/cpp-httplib#client-example

**Comment by PixlRainbow** [comment]
several problems with your code
1. as yhirose has mentioned, please omit protocol (e.g. `http://`) from the host string
2. By running `cli.Post("/post", "/macros/s/MyApiKey/exec?StnID=E732323&Date=06/06/2020&Time=14:49:26&Power=70&Refl=1&Status=ON", nullptr);` with the host `google.com`, you are accessing the address "http://google.com/post" and uploading a string `/macros/s/MyApiKey/exec?StnID=E732323&Date=06/06/2020&Time=14:49:26&Power=70&Refl=1&Status=ON` <br> You are not sending an empty post request to "https://script.google.com/macros/s/MyApiKey/exec?StnID=E732323&Date=19/03/2020&Time=14:49:26&Power=70&Refl=1&Status=ON" as you expected.

**Comment by seccpur** [comment]
@PixlRainbow:  I had to include openssl library in the project to use class httplib::SSLClient. Thanks it works like charm now.
