### ISSUE TITLE
Visual Studio 2013

### ISSUE THREAD

**Issue by lordbendtner1337** [yhirose/cpp-httplib#517]
No idea how to use GitHub, however these are fixes to make it work for Visual Studio 2013.

Comment out;
  Response(Response &&) = default;
  Response &operator=(Response &&) = default;

Change;
auto sn = _snprintf_s(buf, bufsiz, buf.size() - 1, fmt, args...);

to;
 auto sn = _snprintf_s(buf.data(), 2048, buf.size() - 1, fmt, args...);

**Comment by yhirose** [comment]
@lordbendtner1337, thanks for the feedback. But I no longer have time to maintain and validate such an old compiler which doesn't fully support C++11 features. Sorry about that... Thanks for your consideration.
