### ISSUE TITLE
Crashing on shutdown due to handler threads

### ISSUE THREAD

**Issue by sgraham** [yhirose/cpp-httplib#52]
I'm finding I have crashes on shutdown due to https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L1596.

In this case, the worker thread is copying `this` by value. If, while the thread is servicing the request the server is shutdown, listen() returns, and Server is destroyed, then e.g. `Server::process_request` can try to access freed memory running on the thread.

A simple way to fix this would be to have `listen()` store the std::threads instead of `detach()`ing them and then `.join()` before exiting `listen()`. However, that would be very inefficient for a long running server as that list would grow during each request and not be cleared until `stop()`.

Implementing the "// TODO: Use thread pool..." near there might be a good way to fix this (assuming the pool is joined before shutdown).

A more direct slightly hacky way might be to increment an atomic when a thread is started, decrement it on thread exit, and wait until it's zero before exiting `listen()`.

**Comment by yhirose** [comment]
@sgraham, thanks for the bug report. You are completely right.

Until thread pool is implemented, it may be sufficient to use the 'hacky way'. I implemented it with C++11 `std::mutex` at 'issue-52' branch. https://github.com/yhirose/cpp-httplib/compare/issue-52?expand=1.

Does this solution work for you? (We could use `std::atomic<int>`, but I feel that not all C++ compilers properly support the feature.)

**Comment by sgraham** [comment]
Yeah, that looks good to me, thanks for the quick fix.

**Comment by yhirose** [comment]
Fixed at #53.
