### ISSUE TITLE
Server hang when multipart data was malformed

### ISSUE THREAD

**Issue by tlethanh-sdi** [yhirose/cpp-httplib#522]
We integred cpp-httplib in our lora server in order to handle internal webservice requests. Everything works fine until we introduce some file upload functions via multipart form data.

The working thread dedicated to webservice hangs sometimes (about 1 per 10 requests). Debugging shows that the while loop was repeated forever (state_ = 2, buffer size n = 4096).

https://github.com/yhirose/cpp-httplib/blob/ec00fe5d5bb2edacf2c6af500623a7220f05f4ff/httplib.h#L2839-L2870

The parse() function will be never terminated if there is no crlf_ found in buf_ string when state_ = 2 (it means no header found in a new multipart section).

We use a Qt application as client, the boundary implemented may not suit the standard used by cpp-httplib, that we need to look deeper.

**Comment by yhirose** [comment]
@tlethanh-sdi, thanks for finding the bug and fine report. I fixed it with the last master code. Could you verify on your machine? Thanks!

**Comment by tlethanh-sdi** [comment]
@yhirose  Thanks for your quick and effective reaction. The code was passed the test phase and the software is now in the validation chain. We hope to pass this in production very soon.

**Comment by yhirose** [comment]
@tlethanh-sdi , thanks for confirming it works on your machine! I'll release it in v0.6.7 soon.
