### ISSUE TITLE
Client-only header (suggestion)

### ISSUE THREAD

**Issue by gatopeich** [yhirose/cpp-httplib#526]
HTTP 1.1 Client is arguably the most common use case for this library.

A client-only header might be much lighter and bring less dependencies, providing all that is needed for this use case.

Have you considered that?

**Comment by PixlRainbow** [comment]
It would be helpful for older compilers or compilers targeting unusual platforms. But the average modern PC compiler is able to automatically exclude unused code from the executable and will automatically skip dependencies that are unused.
E.g. when compiling an executable that constructs a server, `gcc` will ask you to link a thread library, but when compiling an executable that only uses client, `gcc` will not give error even if thread library is not linked.

**Comment by yhirose** [comment]
@gatopeich, thanks for the suggestion. In addition to the @PixlRainbow's comment, I would like to keep it as a single-file-header-only library because it's the most selling point. Thanks for your understanding the decision!
