### ISSUE TITLE
how to send post request with chunked mode?

### ISSUE THREAD

**Issue by bingoIsCoder** [yhirose/cpp-httplib#532]
hi 
I have a requirement, send a psot request and write streaming data to body.
Is there anyway to do this? 
Thanks!

**Comment by PixlRainbow** [comment]
yes, refer to [the readme](https://github.com/yhirose/cpp-httplib#send-content-with-content-provider-1)

**Comment by yhirose** [comment]
@bingoIsCoder, please see the @PixlRainbow's comment.
@PixlRainbow, I always appreciate your excellent support!
