### ISSUE TITLE
the space char should be urlencode as  "+"

### ISSUE THREAD

**Issue by nopol** [yhirose/cpp-httplib#537]
e.g.

```
2020-06-22 11:48:52
```

urlencode:

```
2020-06-22+11%3A48%3A52
```

See more  [RFC-1738](https://datatracker.ietf.org/doc/rfc1738)

**Comment by nopol** [comment]
also `'=' -> "%3d"`

**Comment by PixlRainbow** [comment]
[RFC-3986](https://tools.ietf.org/html/rfc3986) indicates that spaces should be encoded as `%20` in URLs, but `application/x-www-form-urlencoded` submissions should use `+`.  
In practice, the convention is inconsistent and many different servers use either one or the other in URLs, and sometimes both.

**Comment by yhirose** [comment]
@nopol, hope @PixlRainbow's comment helps.
