### ISSUE TITLE
Serving lots of data

### ISSUE THREAD

**Issue by tsilia** [yhirose/cpp-httplib#541]
Hello. Thank you for your library, it's cute and neat! I'm using it to stream some MP4 video to a video.js player in Firefox/Chrome. However I've run into an issue.
I'm trying to send as much data as the client requests. But looks like ContentProvider stalls at some point and won't proceed with serving the rest of the data and the player in browser can't display the video stream anymore.

The details.
I modified your `server.cc` example as below. TLDR; I'm just setting the desired headers, parsing 'Range' header to determine the size of the response and then setting the content provider callback which just reads the `video.mp4` file in ~small~ big 1MB portions (for a simpler debug log).
```cpp
uint32_t nCPId = 0; // content provider id, for debugging purposes
using Buffer = std::vector<char>;
using BufMap = std::map<int, Buffer>;
BufMap buffers;
svr.Get("/video.mp4", [&buffers, &fReader, &nCPId](const Request &req, Response &res)
{
	Beep(1000, 250);
	// set the desired headers in the response:
	std::cout << "\n\n" << CurrTime() << "Serving /video.mp4..." << std::endl;
	res.set_header("Server", "just_a_streamer v0.1");
	res.set_header("Accept-Ranges", "bytes");
	res.set_header("Cache-Control", "no-cache");
	res.set_header("Connection", "keep-alive");// "close");
	res.set_header("Content-Type", "video/mp4");
	// parse the Range header from the request:
	std::string sRange;
	if (req.has_header("Range"))
		sRange = req.get_header_value("Range");
	else
	{
		std::cerr << "No Range header found!" << std::endl;
		return;
	}
	if (!sRange.empty())
		printf("Raw range: %s\n", sRange.c_str());
	Ranges ranges;
	auto ret = detail::parse_range_header(sRange, ranges);
	uintmax_t umTotalRangeSize = 0;
	const auto umFileSize = fReader.GetFileSize();
	const uintmax_t MaxRangeSize = umFileSize;// 1 * 1024 * 1024;
	// calculate total range size:
	for (auto& r : ranges)
	{
		std::cout << "Parsed range: " << r.first << "-" << r.second << std::endl;
		if (r.second == -1)
			r.second = std::min(MaxRangeSize - 1, umFileSize - 1);
		else if (r.first == -1)	// r.first is -1 here O_O
			throw std::runtime_error("r.first == -1 !!!");

		umTotalRangeSize += (r.second - r.first + 1);
	}
	std::cout << "Total range size: " << umTotalRangeSize << std::endl;
	std::cout << "Resulting ranges:" << std::endl;
	for (const auto& r : ranges)
		std::cout << r.first << "-" << r.second << std::endl;

	if (fReader.Seek(ranges[0].first) == -1LL)
	{
		std::cerr << "Failed to seek to " << ranges[0].first << "!" << std::endl;
		return;
	}

	// set the content provider callback:
	nCPId++;
	const size_t BufSize = 1048576;// 65536;
	buffers[nCPId].resize(BufSize);
	res.set_content_provider(umTotalRangeSize, 
		[&buffers, &fReader, BufSize, nCPId](size_t offset, size_t length, DataSink& sink)
		{
			std::cout << CurrTime() << "Content provider #" << nCPId << ": " 
				<< std::setw(9) << offset << " / " << std::setw(9) << length << std::endl;

			auto& buf = buffers[nCPId];
			const auto nToRead = std::min(BufSize, length);
			const auto llRead = fReader.Read(buf.data(), nToRead);
			sink.write(buf.data(), llRead);
			if (length <= BufSize)
			{
				std::cout << CurrTime() << "Content provider #" << nCPId << " finished!" << std::endl;
				return false;
			}
			else
				return true;
		}
	);

	Beep(500, 250);
	std::cout << CurrTime() << "Finished http handler" << std::endl;
});
```
fReader is of my FileReader class which is just a thin wrapper over an std::fstream object. fReader opens `video.mp4` file (24,499,458 bytes).

I've put some logging code to the ContentProvider callback. Curiously, I get the following output:
```
2020.06.25 11:08:52  Serving /video.mp4...
Raw range: bytes=0-
Parsed range: 0--1
Total range size: 24499458
Resulting ranges:
0-24499457
2020.06.25 11:08:52  Finished http handler
2020.06.25 11:08:52  Content provider #1: 0 / 24499458
2020.06.25 11:08:52  Content provider #1: 1048576 / 23450882
2020.06.25 11:08:52  Content provider #1: 2097152 / 22402306
2020.06.25 11:08:52  Content provider #1: 3145728 / 21353730
2020.06.25 11:08:52  Content provider #1: 4194304 / 20305154
2020.06.25 11:08:52  Content provider #1: 5242880 / 19256578
2020.06.25 11:08:52  Content provider #1: 6291456 / 18208002
2020.06.25 11:08:52  Content provider #1: 7340032 / 17159426
2020.06.25 11:08:52  Content provider #1: 8388608 / 16110850
2020.06.25 11:08:52  Content provider #1: 9437184 / 15062274
2020.06.25 11:08:52  Content provider #1: 10485760 / 14013698
2020.06.25 11:08:52  Content provider #1: 11534336 / 12965122


2020.06.25 11:10:28  Serving /video.mp4...
Raw range: bytes=11534336-
Parsed range: 11534336--1
Total range size: 12965122
Resulting ranges:
11534336-24499457
2020.06.25 11:10:28  Finished http handler
2020.06.25 11:10:28  Content provider #2: 11534336 / 1430786
2020.06.25 11:10:28  Content provider #2: 12582912 / 382210
2020.06.25 11:10:28  Content provider #2 finished!


2020.06.25 11:10:29  Serving /video.mp4...
Raw range: bytes=12965122-
Parsed range: 12965122--1
Total range size: 11534336
Resulting ranges:
12965122-24499457
2020.06.25 11:10:29  Finished http handler
```
Please note that ContentProvider `#1` never finished, the last response is never sent and your original request/response logging code from `server.cc` doesn't get called (it is there, I just omitted it from the snippet above for brevity).
Also, I have this screenshot:
![firefox_network](https://user-images.githubusercontent.com/60840213/85683641-16ccd280-b6d6-11ea-9c76-334db9d172a0.png)
It's a console in Firefox which shows network activity: HTTP requests, responses, etc. Please note that the last request doesn't have associated response.

So, my question is: am I missing something or doing it completely wrong? Is there anything in your library interface I should call before serving lots of data? Or is it a bug maybe?
Also, does ContentProvider respect the original ranges that come with HTTP request? What if client decides to request previous data (e.g., user clicks in the beginning of the timeline in the player)? Should I put a call to the Seek() function *inside* the ContentProvider callback?

Thanks in advance.

PS. I have captured the traffic with WireShark. Just tell me if you need it.

**Comment by PixlRainbow** [comment]
> Please note that ContentProvider #1 never finished

That's actually because the client stopped the request before the full range was sent, so your condition `length <= BufSize` is never met and it does not print your message. It may have silently finished.

> the last response is never sent

Interesting, the logs say that the request handler finished but the content provider was never run. **Might be a bug in cpp-httplib.**

**Comment by tsilia** [comment]
Thank you for your response.

> > Please note that ContentProvider `#1` never finished
> 
> That's actually because the client stopped the request before the full range was sent, so your condition `length <= BufSize` is never met and it does not print your message. It may have silently finished.

Good catch, thanx for the hint. I specified a release callback with another log message and got the message written after the last chunk read. So yes, ContentProvider did silently finish. Somehow I got misled by a wireshark capture: I think I didn't see client close connection. Might have missed tho.

I've run some more tests with smaller buffer size and found something interesting. Looks like there might be a miscalculation of the content length or content range, see below (the log was a bit too long, so I removed most of the recurring messages putting in `<...>` instead).
```
2020.06.25 16:15:20  Serving /video.mp4...
Raw range: bytes=0-
Parsed range: 0--1
Resulting ranges:
0-24499457
Total range size: 24499458
2020.06.25 16:15:20  Setting content provider #1 to serve 24499458 bytes
2020.06.25 16:15:21  Finished http handler
2020.06.25 16:15:21  Content provider #1:         0 /  24499458
2020.06.25 16:15:21  Content provider #1:     65536 /  24433922
2020.06.25 16:15:21  Content provider #1:    131072 /  24368386
<...>
2020.06.25 16:15:21  Content provider #1:   9699328 /  14800130
2020.06.25 16:15:21  Content provider #1:   9764864 /  14734594
2020.06.25 16:15:21  Content provider #1:   9830400 /  14669058


2020.06.25 16:17:02  Serving /video.mp4...
Raw range: bytes=9830400-
Parsed range: 9830400--1
Resulting ranges:
9830400-24499457
Total range size: 14669058
2020.06.25 16:17:02  Setting content provider #2 to serve 14669058 bytes
2020.06.25 16:17:02  Finished http handler
2020.06.25 16:17:02  Content provider #2:   9830400 /   4838658
2020.06.25 16:17:02  Content provider #2:   9895936 /   4773122
2020.06.25 16:17:02  Content provider #2:   9961472 /   4707586
<...>
2020.06.25 16:17:02  Content provider #2:  14483456 /    185602
2020.06.25 16:17:02  Content provider #2:  14548992 /    120066
2020.06.25 16:17:02  Content provider #2:  14614528 /     54530
2020.06.25 16:17:02  Content provider #2 finished!


2020.06.25 16:18:07  Serving /video.mp4...
Raw range: bytes=14669058-
Parsed range: 14669058--1
Resulting ranges:
14669058-24499457
Total range size: 9830400
2020.06.25 16:18:07  Setting content provider #3 to serve 9830400 bytes
2020.06.25 16:18:07  Finished http handler
2020.06.25 16:18:07   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
GET HTTP/1.1 /video.mp4
Accept: video/webm,video/ogg,video/*;q=0.9,application/ogg;q=0.7,audio/*;q=0.6,*/*;q=0.5
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
DNT: 1
Host: localhost:8080
Range: bytes=14669058-
REMOTE_ADDR: ::1
REMOTE_PORT: 65229
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
206 HTTP/1.1
Accept-Ranges: bytes
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 4290128638
Content-Range: bytes 14669058-9830399/9830400
Content-Type: video/mp4
Server: just_a_streamer v0.1
```
Please note the last `Content-Length` entry: it actually specifies something that's bigger than 4 GB. In the debugger, I've stepped into the `Server::write_response` method and found that function `get_range_offset_and_length` ends up subtracting greater value from a smaller one, which results in getting negative content length. It can also be seen in the line `Content-Range: bytes 14669058-9830399/9830400` of the log where beginning of the range is greater than the ending. So, I guess it's the `Content-Range` that was calculated incorrectly at some point.

**Comment by tsilia** [comment]
I reckon, _if ContentProvider does respect_ the original ranges that come with an HTTP request, then the content length it expects should be set to that of the entire resource, not just the requested part, right? @PixlRainbow @yhirose could you please confirm that? I did so in my code, i.e., changed the line
```cpp
res.set_content_provider(umTotalRangeSize,
```
to
```cpp
res.set_content_provider(umFileSize,
```
and it worked like a charm! All responses are now sent correctly.
So, I guess this can be closed now. Thank you for your time!

**Comment by yhirose** [comment]
@tsilia, thanks for the feedback. I am right now busy to read your comments carefully though. The following unit test might be helpful to you:

https://github.com/yhirose/cpp-httplib/blob/0a2cb20223190d4e3f153ac99067f60970e1c3ba/test/test.cc#L919-L934

Does it answer your question?

**Comment by tsilia** [comment]
Yes, it does, thank you @yhirose!
I, however, have one more question regarding the topic.
Is it, by any chance, possible that different requests coming from the same client could be processed simultaneously by your library, like in parallel threads? I mean, do I need to protect my file reader using some kind of synchronisation primitive in the ContentProvider callback or make a separate reader instance for every ContentProvider callback I call? (I open my video files in read-only mode anyway).

**Comment by PixlRainbow** [comment]
yes, requests are handled by a thread pool. More than one request can be handled at once.

**Comment by tsilia** [comment]
Ok, thanks for your time! I'm closing the issue then.
