### ISSUE TITLE
Sending requests with follow_location will return null

### ISSUE THREAD

**Issue by TheOnlyArtz** [yhirose/cpp-httplib#542]
```cpp
	httplib::Client cli("gist.githubusercontent.com");
	cli.set_follow_location(true);

	auto res = cli.Get("/TheOnlyArtz/096a139a25d151b88b36f350c5a100cb/raw/b2180d7d64432762bc6e22ab0c6206ce8e34b612/a.json");
```

Hey! this code doesn't seem to work and I can't figure out exactly why, without the follow_location res->status is 301 but with follow_location the res is just nothing (?)

**Comment by yhirose** [comment]
@TheOnlyArtz, do you get the same result with `curl -L [YOUR URL]`?

**Comment by PixlRainbow** [comment]
did you compile with openssl support?

**Comment by yhirose** [comment]
@PixlRainbow, good point!

**Comment by TheOnlyArtz** [comment]
> did you compile with openssl support? The URL you provide redirects from HTTP to HTTPS and without OpenSSL, the client cannot use HTTPS.

Oh, probably didn't. maybe that's why :)
