### ISSUE TITLE
each request is a new session id

### ISSUE THREAD

**Issue by killahypens1998** [yhirose/cpp-httplib#543]
I make a post request to the file and create a session there, which in the future will be needed for use in all files, but it remains only in the file in which it was created, each new request changes PHPSESSID. session_start(); I have it only in the file.

example:

file_for_include.php

session_start();
code,code,code...
============

other files.php

include 'file_for_include.php';
code,code,code...
============

request 1:
https://prnt.sc/t820zz

request 2: 
https://prnt.sc/t8219w

**Comment by PixlRainbow** [comment]
I don't think httplib manages cookies automatically. You will have to implement cookies on your own by reading and setting headers.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the comment.
@killahypens1998, thanks for the feedback. Hope @PixlRainbow, 's comment helps you.
