### ISSUE TITLE
Compression in chunked transfers

### ISSUE THREAD

**Issue by evg82** [yhirose/cpp-httplib#557]
Compression is not used when set_chunked_content_provider is set.

I think it would be necessary to add the "Content-Encoding: gzip" header if the client supports compression and pass the data by the compressor before write it.

This can be done outside the lib (create a zlib instance and write to it with flush flags to get a compressed output. Then write this output. However its tricky to get if client support compression from request.

I use this to stream a big csv file generated in realtime. Normal send works ok, but i need all data before send. Chunked works ok, but no compression make transfer slow.

Please send some advices and i can try to solve it

**Comment by yhirose** [comment]
@evg82, please see my comment in #561. I'll try to implement it when I have time.

**Comment by yhirose** [comment]
When working on this issue, we have to take #400 into consideration as well.
