### ISSUE TITLE
having Linker problem ....

### ISSUE THREAD

**Issue by Mamlesh** [yhirose/cpp-httplib#56]
LNK2019	unresolved external symbol __imp_WSAStartup referenced in function "public: __cdecl httplib::detail::WSInit::WSInit(void)" (??0WSInit@detail@httplib@@QEAA@XZ)	

got this error when i add <httplib.h> file in my project....
pls help...

**Comment by yhirose** [comment]
@Mamlesh, I guess you forgot linking Ws2_32.lib. Please check the 'Requirements' section in the MSDN document.
https://msdn.microsoft.com/en-us/library/windows/desktop/ms742213(v=vs.85).aspx

Also you can find my VC sample projects in 'example' folder.
Hope it helps.
