### ISSUE TITLE
Advice: Can it be migrated to libuv (for better parallel performance)?

### ISSUE THREAD

**Issue by ScSofts** [yhirose/cpp-httplib#562]
I like this project very much. But it just runs in single thread,so it cannot undertake much requests.I think using [libuv ](https://github.com/libuv/libuv)is a good solution.

**Comment by yhirose** [comment]
@ScSofts, thank you for the feedback. Are you talking about server or client? cpp-httplib server is actually a 'multi-thread', but 'synchronous' server. Client is a 'single-thread' and  'synchronous' server.

You can find more information regarding it at https://github.com/yhirose/cpp-httplib/issues/312.
Thanks!

**Comment by ScSofts** [comment]
thanks
