### ISSUE TITLE
LPWSTR vs LPSTR

### ISSUE THREAD

**Issue by P-e-g-a-s-u-s** [yhirose/cpp-httplib#564]
Hello.
I'm trying to compile in VS2013 update 5.

httplib.h(3234): error C2664: 'HCERTSTORE CertOpenSystemStoreA(HCRYPTPROV_LEGACY,LPCSTR)' : cannot convert argument 2 from 'const wchar_t [5]' to 'LPCSTR'

3234 auto hStore = CertOpenSystemStore((HCRYPTPROV_LEGACY)NULL, **L"ROOT"**);
**L"ROOT"** change to **_T"ROOT"** or **TEXT("ROOT")**

httplib.h(3533): error C2065: 'bufsiz' : undeclared identifier

#if defined(_MSC_VER) && _MSC_VER < 1900
3533  auto sn = _snprintf_s(buf, **bufsiz**, buf.size() - 1, fmt, args...);
#else

perhaps
  auto sn = _snprintf_s(**buf.data()**, **buf.size()** , buf.size() - 1, fmt, args...);
or
  auto sn = _snprintf_s(**buf.data()**, **buf.size() _-1_**, buf.size() - 1, fmt, args...);

**Comment by yhirose** [comment]
@P-e-g-a-s-u-s, thanks for the report! Please let me know if the latest version works.

**Comment by P-e-g-a-s-u-s** [comment]
I dropped out of work for a month.
Now checked the error remained.

httplib.h(3576): error C2664: 'int _snprintf_s(char *,size_t,size_t,const char *,...)' : cannot convert argument 1 from 'std::array<char,2048>' to 'char*'
...
httplib.h(3576)  auto sn = _snprintf_s(**buf**, bufsiz - 1, buf.size() - 1, fmt, args...);
change to 
 auto sn = _snprintf_s(**buf.data()**, bufsiz - 1, buf.size() - 1, fmt, args...);

**Comment by yhirose** [comment]
@P-e-g-a-s-u-s, thanks for the report. Could you try with the latest?

**Comment by P-e-g-a-s-u-s** [comment]
There is no error.

**Comment by yhirose** [comment]
@P-e-g-a-s-u-s, thanks for the confirmation!
