### ISSUE TITLE
usec conversion question

### ISSUE THREAD

**Issue by ben-sol** [yhirose/cpp-httplib#565]
#### merge founds
line 1732: auto timeout = static_cast<int>(sec * 1000 + usec);
line 1756: auto timeout = static_cast<int>(sec * 1000 + usec / 1000);
line 1789: auto timeout = static_cast<int>(sec * 1000 + usec);

Is 'usec' sometimes 'msec'?

**Comment by yhirose** [comment]
@ben-sol, thanks for the report! It should always be 'milliseconds'. So the line 1756 is wrong... I'll correct it.
https://pubs.opengroup.org/onlinepubs/007908775/xsh/systime.h.html

**Comment by ben-sol** [comment]
I'm glad you posted it:
```
time_t         tv_sec      seconds
suseconds_t    tv_usec     microseconds
```
so it's MICROSECONDS!
