### ISSUE TITLE
Again: #565

### ISSUE THREAD

**Issue by ben-sol** [yhirose/cpp-httplib#566]
#### merge founds
line 1732: auto timeout = static_cast<int>(sec * 1000 + usec);
line 1756: auto timeout = static_cast<int>(sec * 1000 + usec / 1000);
line 1789: auto timeout = static_cast<int>(sec * 1000 + usec);

It's always MICROSECONDS, so please reconsider your commit (1732 and 1789 are wrong).
Note you're _very_ fast (that's good), but it was the wrong direction this time. Sorry, I will be more precise next time...

**Comment by bluecataudio** [comment]
I think there are actually other inconsistencies (poll expects milliseconds as input for example), so there is a mix of microseconds and milliseconds in several places.

**Comment by ben-sol** [comment]
actually, all setiings are in microseconds, so the state _is consistent_. This is the only place I found.

**Comment by bluecataudio** [comment]
I might be wrong, but on Line 1732 it seems to me that it does not work as expected:
  auto timeout = static_cast<int>(sec * 1000 + usec);
  return handle_EINTR([&]() { return poll(&pfd_read, 1, timeout); });
(poll is also documented as using milliseconds)

By the way, on line 1884 I am not 100% that I understand the computation done here, there is probably also a timing issue mixed with a typo:
while (true) {
    auto val = select_read(sock, 0, 10000);
    if (val < 0) {
      return false;
    } else if (val == 0) {
      auto current = steady_clock::now();
      auto duration = duration_cast<**milliseconds**>(current - start);
      auto timeout = **CPPHTTPLIB_KEEPALIVE_TIMEOUT_SECOND** * 100 +
                     **CPPHTTPLIB_KEEPALIVE_TIMEOUT_SECOND;**
      if (duration.count() > timeout) { return false; }

Great library by the way!

**Comment by yhirose** [comment]
@ben-sol, @bluecataudio, thank you for the comments and bug reports. I'll take a look at all the places where timeout is used. Here is the result of my research.

## select

https://pubs.opengroup.org/onlinepubs/007908775/xsh/systime.h.html

```
 DESCRIPTION
The <sys/time.h> header defines the timeval structure that includes at least the following members:

time_t         tv_sec      seconds
suseconds_t    tv_usec     microseconds
```

`usec` should be treaded as microseconds, not milliseconds. It was my mistake.

## poll

```
int poll(struct pollfd *fds, nfds_t nfds, int timeout);

The timeout argument specifies the number of milliseconds that poll() should block waiting for a file descriptor to become ready.  
```

`timeout` should be milliseconds.
