### ISSUE TITLE
How to handle cross domain requests from browsers

### ISSUE THREAD

**Issue by opentianwe** [yhirose/cpp-httplib#567]

**Comment by PixlRainbow** [comment]
## If viewing third party domain's website and accessing your domain's API
You need to include [a header that permits the third party domain](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin).  
More details [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).  
## If viewing your domain's website and accessing third party domain's API
You must either
1. inform your API provider that they need to set up their cross origin headers ***OR***
2. proxy requests to third party domains through your server.

**Comment by yhirose** [comment]
Thank you for the question and the fine answers!
