### ISSUE TITLE
Minor, warning - %zu/%lu in example.simplesvr.cc

### ISSUE THREAD

**Issue by sgarriga** [yhirose/cpp-httplib#571]
g++ 7.5.0 under Ubuntu is happy using %lu in simplsvr.cc

snprintf(buf, sizeof(buf), "text length: %lu\n", file.content.size());

but g++ 8.3.0 under Raspbian warns it should be %zu

I've spent a few hours searching, but I don't think there's a standard macro in C++ that the preprocessor can use to determine which is correct.

**Comment by yhirose** [comment]
@sgarriga, thank you for the report!
