### ISSUE TITLE
Url's with spaces and pluses do not processing properly

### ISSUE THREAD

**Issue by RozeFound** [yhirose/cpp-httplib#576]
Days ago i tried to download some files with this library, and i found that url's with spaces and pluses always return 403 error (access denied).

Here is two url from one CDN: 
1. https://edge.forgecdn.net/files/2745/846/mcjtylib-1.12-3.5.4.jar
2. https://edge.forgecdn.net/files/2595/310/Neat 1.4-17.jar

I tried to download it with SSLClient, fake browser headers, follow_location (true) and default GET construction (response handler, content receiver, progress callback).

And the first file download properly, but second always return 403.
The code: https://pastebin.com/0Rw6s91p

**Comment by yhirose** [comment]
@RozeFound, thanks for the feedback. But I don't think it has to do with cpp-httplib since the status is 403. Please let me know if you find enough evidence that it is really caused by this library.

**Comment by RozeFound** [comment]
@yhirose I have a 150+ similar links, and error 403 appear only with link with spaces and pluses, In addition to this, any other library (like cpr) can easily download this files.

**Comment by yhirose** [comment]
@RozeFound, thanks for the info! If curl can handle the request, there must be a bug in cpp-httplib. I'll take a look at it when I have time.

**Comment by yhirose** [comment]
@RozeFound, could you try with the latest master code? Thanks!

**Comment by RozeFound** [comment]
Very thank you for your library, and fast fixes. Your library is easy to
use like cpr, but faster and without dependencies!
  Now I can continue to work on my project. Thank you again!
