### ISSUE TITLE
Minor: new compiler warning if not CPPHTTPLIB_BROTLI_SUPPORT or CPPHTTPLIB_ZLIB_SUPPORT

### ISSUE THREAD

**Issue by electromaggot** [yhirose/cpp-httplib#581]
Minor, but still...  Line 2354:
```
.../httplib.h:2354:15: warning: unused variable 's' [-Wunused-variable]
  const auto &s = req.get_header_value("Accept-Encoding");
```
(Great project, by the way, thank you @yhirose!)

**Comment by yhirose** [comment]
@electromaggot, thanks for the report! I actually noticed that before committing the Brotli support, but I didn't come up with any simple or elegant way to suppress the warning and just left it... It's the benefit of open source project that any thing cannot be hidden from other developers' eyes! I'll take a look at it when I have time. Thanks!

**Comment by electromaggot** [comment]
I should be thanking you! ...for the timely fix, and for those punctilious of us treating warnings as errors.  I thought your suppression elegantly avoided a somewhat ugly "compound #ifdef" or code repetition.  Bravo!
