### ISSUE TITLE
Brotli support in CMake

### ISSUE THREAD

**Issue by yhirose** [yhirose/cpp-httplib#582]

**Comment by yhirose** [comment]
@sum01, I have recently added Brotli compression support on client which can be configured with `CPPHTTPLIB_BROTLI_SUPPORT`. It requires brotli libraries. (https://github.com/google/brotli)

If it possible to support it in the CMakeLists.txt as `CPPHTTPLIB_ZLIB_SUPPORT` when you have time?
Thank you for your help!

**Comment by sum01** [comment]
@yhirose Do you need all 3 libs (decode, encode, and common) or just specific ones?

**Comment by yhirose** [comment]
@sum01, currently, the library supports only decoder, but I am thinking to support encoder soon as well. So it would be nice to include 3 libraries. As for the minimum version, I have installed 1.0.7 with homebrew on macOS and confirmed it works. Thanks!

```[master] ~/Projects/cpp-httplib$ brew info brotli
brotli: stable 1.0.7 (bottled), HEAD
Generic-purpose lossless compression algorithm by Google
https://github.com/google/brotli
/usr/local/Cellar/brotli/1.0.7 (25 files, 2.2MB) *
  Poured from bottle on 2020-07-25 at 11:39:48
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/brotli.rb
License: MIT
==> Dependencies
Build: cmake ✘
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 23,343 (30 days), 71,928 (90 days), 319,606 (365 days)
install-on-request: 378 (30 days), 1,261 (90 days), 5,550 (365 days)
build-error: 0 (30 days)
```

**Comment by yhirose** [comment]
@sum01, thanks for the quick support! I have just merged the pull request.

**Comment by ElonH** [comment]
I got a problem when `HTTPLIB_USE_BROTLI_IF_AVAILABLE` was `on`
```
CMake Error at /usr/local/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:261 (message):
  No REQUIRED_VARS specified for FIND_PACKAGE_HANDLE_STANDARD_ARGS()
Call Stack (most recent call first):
  cmake/FindBrotli.cmake:173 (find_package_handle_standard_args)
  CMakeLists.txt:146 (find_package)
```

**Comment by sum01** [comment]
@ElonH Hmm. Do you not have Brotli installed? I think I might see where that could happen if so.

**Comment by ElonH** [comment]
@sum01 I never used it before, not even install it.

**Comment by ElonH** [comment]
@sum01 Sorry for my delay, my system was crashed, I have to reinstall it.
https://github.com/yhirose/cpp-httplib/pull/598 doesn't workaround.
I print variable
`Brotli_FOUND` is False
`_target_name` is nothing

```

Brotli_FOUND: FALSE
_brotli_req_vars: 
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:226 (message):
  No REQUIRED_VARS specified for FIND_PACKAGE_HANDLE_STANDARD_ARGS()
Call Stack (most recent call first):
  libs/httplib/cmake/FindBrotli.cmake:178 (find_package_handle_standard_args)
  libs/httplib/CMakeLists.txt:146 (find_package)

```


```cmake

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Brotli
	FOUND_VAR Brotli_FOUND
	REQUIRED_VARS ${_brotli_req_vars}
	HANDLE_COMPONENTS
)
```

Moving above code into `if(Brotli_FOUND)` statement?

https://github.com/yhirose/cpp-httplib/blob/dfec2de5b57c16b6c446d4cd0962b37e3c1e5fba/cmake/FindBrotli.cmake#L170-L185

**Comment by sum01** [comment]
@ElonH I tested https://github.com/yhirose/cpp-httplib/pull/598 on a Windows VM with no Brotli installed.

Can you give me more information, like OS, compiler, compiler std version used, Cmake version, etc?

**Comment by ElonH** [comment]
@sum01 
my previous environment:
```
os: ubuntu18.04
cmake: 3.17
compiler: clang-11
```

current environment:
```
os: kubuntu20.04
cmake: 3.16
compiler: clang-12
```

I also switch os to win10, and use msys2 (mingw64, gcc9.2.0) and cmake3.16 to generate `Unix Makefiles`, but still no work
