### ISSUE TITLE
getaddrinfo in template <typename BindOrConnect> socket_t create_socket(.....)

### ISSUE THREAD

**Issue by ThePiso** [yhirose/cpp-httplib#587]
Useful and beautiful library compliments.

The problem that occurs is this:
on unstable WiFi connections it happens that the "getaddrinfo" function always returns the error with code -2 (EAI_NONAME) and there is no way to get out of it if not by restarting, it would seem that it is not detected that the connection has actually become active again.

I am trying to use the Client part of this library.

**Comment by ThePiso** [comment]
Hi all,

on the return of an error by the function
getaddrinfo I tried adding the res_init () function
and it seems to work

**Comment by yhirose** [comment]
@ThePiso, thanks for the feedback. What does it mean by `there is no way to get out of it`? Also could you send a pull request with your fix? Thanks!

**Comment by ThePiso** [comment]
Hi yhirose,

when I say, "there is no way to get out of it", I mean that once the "getaddrinfo" function loses the north wind, it continues to give the same error and cannot recognize that the connection is active, always returning the same error.
This is because the "resolve.conf" file is read one at the beginning after which this information is cached, and is no longer updated.
With the call to the res_init () function, everything seems to return to normal.
I take some time to test the patch, then I will make a pull request.

Thank you

**Comment by ThePiso** [comment]
Hi yhirose,

has my pull request arrived?

**Comment by yhirose** [comment]
No, yet.
