### ISSUE TITLE
Client keep-alive with timeout will return wrong result

### ISSUE THREAD

**Issue by naleksiev** [yhirose/cpp-httplib#591]
Looks like if I have a client with keep-alive connection that times out, the next Get will return the previous result.

cli.set_keep_alive(true);
cli.set_read_timeout(1, 0);
cli.Get("/a"); // returns null due to time out
cli.Get("/b"); // returns "/a"

**Comment by yhirose** [comment]
@naleksiev, thanks for the bug report! Could you try the latest master code?

**Comment by naleksiev** [comment]
Works as expected! Thank you for sharing the lib and for the quick fix.

PS: I made similar work around yesterday in app space where I was recreating the client object. I was trying to figure out a good fix where I keep the connection alive even after timeout... I had a naive client impl that was working reasonably but my app now works on HoloLens 2 and I think I'm hitting OS bug where sockets are not recycled. I make a lot of tiny HTTP requests and after probably few hundreds/thousands the OS refuses to connect for about 10 seconds. The same problem exists with cpp-httplib, but keep-alive works well. The problem is even more noticeable since I can't afford to make the timeout very long. Because of dependencies between the requests and the realtime nature of the app I need to keep the timeout close to 1sec.
