### ISSUE TITLE
applink.c not found

### ISSUE THREAD

**Issue by RozeFound** [yhirose/cpp-httplib#592]
I'm so sorry but what is applink.c, this is not part of default includes of openssl, i cannot compile my project with new versions of cpp-httplib.
If i doing something wrong, please say me what literally i do wrong.

**Comment by PixlRainbow** [comment]
`openssl/applink.c` is required for OpenSSL to work on Windows, when compiled by MSVC (Miscrosoft Visual Studio Compiler). It is included in the Windows version of OpenSSL from 1.1.0 and above, but is excluded on OpenSSL for Mac, Linux or MinGW

**Comment by RozeFound** [comment]
@PixlRainbow Okay I'm workin' on windows, and how i can compile my program? OpenSSL is installed and  work properly.

**Comment by PixlRainbow** [comment]
According to the [OpenSSL FAQ](https://www.openssl.org/docs/faq.html#PROG3):  
> The snippet gets installed as \<install-root\>/include/openssl/applink.c 

You may need to add the OpenSSL  `\<install-root\>/include/` folder to the project search directories, but if your installation does not come with the file, then you either have the wrong version, or you have yet to compile the OpenSSL DLL binaries.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the clear comment!

**Comment by RozeFound** [comment]
@PixlRainbow I installed OpenSSL with vcpkg into static library,  and all works fine on older versions of cpp-httplib where is not dependency applink.c

**Comment by PixlRainbow** [comment]
try the patch and see if it fixes anything @RozeFound

**Comment by RozeFound** [comment]
Yup, now it's work just fine, thank you @PixlRainbow
