### ISSUE TITLE
Support for application/octet-stream MIME types

### ISSUE THREAD

**Issue by aosterthun** [yhirose/cpp-httplib#597]
Hello there,

I'm looking foreward to using this library. I looked through the supported MIME types and noticed that application/octet-stream seems to be unsupported at the moment. I wonder if this is really the case or if it might just not be noted in the readme file. 

In general is there a possibilty to send binary data/raw arrays with this libraray ?

**Comment by PixlRainbow** [comment]
This library does not distinguish between human-readable text and binary data.
If you are writing your own path handler, the `content-type` of the response is arbitrary and defined by you -- you just have to follow HTTP conventions and write sensible code.
The list of MIME types is not a support list -- it is for the automatic file hosting mode, for automatically selecting response MIME type based on file extension.

**Comment by yhirose** [comment]
@PixlRainbow, thank you for the clear explanation.
@aosterthun, in addition to @PixlRainbow's comment, you can see some examples in the unit test suite.
