### ISSUE TITLE
Certain compiling issues

### ISSUE THREAD

**Issue by PT400C** [yhirose/cpp-httplib#599]
Hey,

new to using this library I noticed that on my end some errors happen when including the header file.

One of those is: `httplib.h:1896: undefined reference to '__imp_freeaddrinfo'`

As a quick reference, I use the latest `mingw-w64 8.1.0 with posix and seh`

Thanks in advance

PT400C

**Comment by yhirose** [comment]
@PT400C, thanks for the question. Hope the following helps.
https://github.com/yhirose/cpp-httplib/search?q=freeaddrinfo&type=Issues
