### ISSUE TITLE
Headers as part of Client

### ISSUE THREAD

**Issue by RozeFound** [yhirose/cpp-httplib#600]
For example, i have the code: https://pastebin.com/8tRuhSUn
And i really don`t think that downloadFile func need to care about headers.

With headers as part of Client the following functions will have view like:
```
main() {
   Client session(scheme_host);
   session.headers = {...};

   someFunc(session); //etc
}
```
Seens much better, you don't think so?

**Comment by yhirose** [comment]
@RozeFound, thanks for the feedback. The cpp-httplib client API is similar to [the way that cpr does](https://whoshuu.github.io/cpr/advanced-usage.html#request-headers), and this API gives flexibility to each request.

But I understand your situation that you don't want to set the same header entries again every time you send another request. So I am thinking to add something like `Client::set_default_headers(Headers headers)`.

**Comment by yhirose** [comment]
Could you try [the version on this branch](https://github.com/yhirose/cpp-httplib/tree/set_default_headers)?

**Comment by RozeFound** [comment]
@yhirose yup, it's work fine for me, but you forgot add constructor without headers for Get overload with response handler, content receiver and progress.

**Comment by RozeFound** [comment]
> The cpp-httplib client API is similar to [the way that cpr does](https://whoshuu.github.io/cpr/advanced-usage.html#request-headers), and this API gives flexibility to each request.
But cpr have a little bit different structure, it have session object, and also can make fully individual GET requests. Unlike cpp-httplib, wich have something between session, and individual requests.

**Comment by yhirose** [comment]
@RozeFound, thanks for the reply. What do you mean by "but you forgot add constructor without headers for Get overload with response handler, content receiver and progress"? Thanks.

**Comment by RozeFound** [comment]
> What do you mean by "but you forgot add constructor without headers for Get overload with response handler, content receiver and progress"? Thanks.
>
This:
![image](https://user-images.githubusercontent.com/68745888/89238011-ece4c500-d61e-11ea-863f-10fa83a4ef01.png)

You forgot 
```
std::shared_ptr<Response> Get(const char* path,
            ResponseHandler response_handler,
            ContentReceiver content_receiver,
            Progress progress);
```

Or am I confusing something and everything is as it should be?

**Comment by yhirose** [comment]
@RozeFound, got it! I'll add the one. Thanks.
