### ISSUE TITLE
occur an error when downloading big file

### ISSUE THREAD

**Issue by OceanScottY** [yhirose/cpp-httplib#602]
When downloading a big file, some data blocks of this file are lost. The data obtained is such an error message: "404 no such key ...".cpp-httplib thinks it is the data block information. Therefore, “out of range” occurs in write_response method "res.body = res.body.substr(offset, length)"

**Comment by yhirose** [comment]
@OceanScottY, thanks for the report. Could you show the smallest possible code that can reproduce the problem on my machine as well? Thanks!
