### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Xyncgas** [yhirose/cpp-httplib#606]
Couple months ago I didn't have this library and I kinda stopped programming, because I hated using libcurl where I couldn't find the correct configurations to build my codes. I am a student that's not in cs, and it's really difficult to deal with the build process, I just wanted to be writing codes.
I love this library, and thanks lot.
how cross platform is this thing?

**Comment by Xyncgas** [comment]
btw I can't use https somehow
![image](https://user-images.githubusercontent.com/35312807/89760955-3f503680-daa2-11ea-8871-24de62794f60.png)

**Comment by Xyncgas** [comment]
httplib::Client cli("https://www.google,com");

		if (auto res = cli.Get("/")) {
			if (res->status == 200) {
				std::cout << res->body << std::endl;
			}
			else
			{
				std::cout << "A" << std::endl;
			}
		}
		else {
			std::cout << "B" << std::endl;
			auto err = res.error();

		}
		std::cout << "C" << std::endl;
		std::cin.ignore();

**Comment by Xyncgas** [comment]
literally my codes

**Comment by yhirose** [comment]
@Xyncgas, thank you for your feedback. I don't fully understand your problem though, it seems like you forgot to install OpenSSL library and enable it with `CPPHTTPLIB_OPENSSL_SUPPORT`. Hope it helps!
