### ISSUE TITLE
Request handler with ContentReader not called without Content-Length header

### ISSUE THREAD

**Issue by csk-ableton** [yhirose/cpp-httplib#609]
Handlers with a `ContentReader` are called when sending a request that contains the HTTP header `Content-Length: 0` but not if the body is empty and this header is missing. This is surprising and unfortunately not possible to test this with `httplib::Client`, as the `Content-Length` header is appended automatically. The behavior changed in a recent version of the library, which broke our API when used in a browser that is not appending the `Content-Length` header but not unit tests that where using `httplib::Client`.

# Reproduction

Given the following example server:
```cpp
httplib::Server& httpServer;
httpServer.Delete("/delete", []( const httplib::Request& request, httplib::Response& response, const httplib::ContentReader& reader) { 
  response.set_content("ok", "text/plain"); 
});
httpServer.listen("localhost", 80);
```

Make the following curl call
```
curl -v -X DELETE http://localhost/delete
```

Expected:
```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> DELETE /delete HTTP/1.1
> Host: localhost
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Content-Length: 2
< Content-Type: text/plain
< 
* Connection #0 to host localhost left intact
ok* Closing connection 0
```

Actual:
```
*   Trying ::1...
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> DELETE /delete HTTP/1.1
> Host: localhost
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
* Closing connection 0
```

**Comment by yhirose** [comment]
@csk-ableton, thanks for the feedback.

> The behavior changed in a recent version of the library

Which version (or commit number) was working?

**Comment by csk-ableton** [comment]
> Which version (or commit number) was working?

The code worked fine in v0.6.3 but didn't after upgrading to v0.7.0. I tried v0.7.4 but it's the same behavior.

**Comment by yhirose** [comment]
@csk-ableton, thanks! I'll take a look at it when I have time.

**Comment by csk-ableton** [comment]
Great thanks!

To be clear I know that using the second overload that isn't taking a `ContentReader` works fine. However I thought I report this behavior as somebody else might run into it.
