### ISSUE TITLE
Class Client has no member named set_digest_auth

### ISSUE THREAD

**Issue by cvvan** [yhirose/cpp-httplib#615]
When compiling a Client  I get following error:

**error: ‘class httplib::Client’ has no member named ‘set_digest_auth’; did you mean ‘set_basic_auth’?**

I have cloned the git repository again as well as I have updated OpenSSL, is there something I'm missing?
I wish to use digest authentication in the client, otherwise I can't acess most functions from a server I'm working with.

I hope someone has an idea

**Comment by yhirose** [comment]
@cvvan, thanks for the feedback, but I can't reproduce it. Did you enable the OpenSSL support with `CPPHTTPLIB_OPENSSL_SUPPORT`?
