### ISSUE TITLE
Unable to make HTTPS request?

### ISSUE THREAD

**Issue by michaelcheers** [yhirose/cpp-httplib#623]
I was having an issue with communicating with a server and I tried a simple test to see what the problem was. I tried webhook.site and made a simple script: 

```c++
#include "httplib.h"
#include <iostream>

int main(void)
{
    httplib::Client cli("https://webhook.site");

    if (auto res = cli.Get("/my-webhook-id")) {
        if (res->status == 200) {
            std::cout << res->body << std::endl;
        }
    }
    else {
        auto err = res.error();
        std::cout << "Something super bad!";
    }
}
```

When I made the request with my browser, there was no problem and I was able to successfully make http requests by removing https://. When I run it with my program, it crashes and says memory access violation and it does not appear on webhook's list of sites. I downloaded the latest version of httplib.h today for the test. Any idea why it wouldn't work. Is there a problem with HTTPS requests?

**Comment by yhirose** [comment]
@michaelcheers, did you follow the [instruction](https://github.com/yhirose/cpp-httplib#openssl-support) in README?

**Comment by michaelcheers** [comment]
@yhirose, no but it works now. Thank you.
