### ISSUE TITLE
Non-copyable but movable objects can't be used as ContentProviders

### ISSUE THREAD

**Issue by Fefer-Ivan** [yhirose/cpp-httplib#624]
Hi.

I see this as a problem, because we can't use std::unique_ptr and other non-copyable objects as captures in ContentProvider.

Maybe, it is possible to replace using ContentProvider = std::function<..> with a class with virtual operator() and make set_content_provider into function templates that accept anything callable (for backward compatibility)?
Also, it will make resource_releaser obsolete (because all releasing will be done in ContentProvider destructor), so maybe it will be possible to deprecate it.

If you think this is a good idea, I will make a pull request.

Thanks.

**Comment by yhirose** [comment]
@Fefer-Ivan, thanks for your feedback. Could you show a code example that explains the problem?

**Comment by Fefer-Ivan** [comment]
For example, if I have several threads that return chunks of response, I might want to make a ContentProvider functor that accepts a queue of futures and waits and writes them one by one 
``` 
  class AsyncContentProvider {
  public:
    AsyncContentProvider(
        std::queue<std::future<std::string>> data_queue
    ):
        data_queue_(std::move(data_queue)) {}

    bool operator() (size_t /*offset*/, DataSink& sink) {
      if (data_queue_.empty()) {
        sink.done();
        return true;
      }
      std::string data = data_queue_.front().get();
      data_queue_.pop();
      sink.write(data.c_str(), data.size());
    }

  private:
    std::queue<std::future<std::string>> data_queue_;
  };
```

But it won't compile because std::future is not copyable, but std::function require anything passed to it to have a copy constructor.

Also, if my ContentProvider contains a lot of data (for example, large vector with different places to get data from), I want to avoid it being copied needlessly.

**Comment by PixlRainbow** [comment]
isn't there a referencing capture that will not copy objects?

**Comment by Fefer-Ivan** [comment]
In case of capture by reference, user will have to keep ownership of the resources and release it in resource_releaser function, which works, but doesn't look like RAII, which is preferred way of handling stuff in modern C++, in my opinion. 

Also, shared_ptr will do the trick too.

**Comment by yhirose** [comment]
@Fefer-Ivan, thank you for explaining your idea. I actually don't have any inconvenience with this interface. But I now understand what you are struggling with. Could you implement your idea and send me a pull request? Then, I'll review it. (Please don't forget to add a unit test.) Thanks!

**Comment by yhirose** [comment]
@yhirose, I'll close for now, but a pull request from you is always welcome!
