### ISSUE TITLE
MSVC - Visual Studio 16.7.2- Incorrect error returned from Client functions

### ISSUE THREAD

**Issue by AndyBrown91** [yhirose/cpp-httplib#628]
Hi,

It seems as though MSVC is taking code like:
```
inline Result ClientImpl::Patch(const char *path, const Headers &headers,
                                size_t content_length,
                                ContentProvider content_provider,
                                const char *content_type) {
  return Result{send_with_content_provider("PATCH", path, headers,
                                           std::string(), content_length,
                                           content_provider, content_type),
                get_last_error()};
}
```

and evaluating `get_last_error()` before the call to `send_with_content_provider`
Meaning that the "error" returned is the state of `error_` before the call to `send_with_content_provider` 

This seems to be just an MSVC issue, but I've only got one version of Visual Studio available to check

I can do a PR which works around this by saving the result to a variable and then using that to construct the `Result` object, but I don't know if you have any better suggestions?

Thanks

**Comment by yhirose** [comment]
@AndyBrown91, thanks you for the feedback. Yes, it's an obvious bug...
https://stackoverflow.com/questions/2934904/order-of-evaluation-in-c-function-parameters

I have just fixed it. Could you try with the latest code? Thanks!

**Comment by AndyBrown91** [comment]
Thanks a lot @yhirose, looks good to me
