### ISSUE TITLE
Please mention supported HTTP versions.

### ISSUE THREAD

**Issue by kushwahashivam** [yhirose/cpp-httplib#630]
I tried to find which HTTP versions (HTTP/1.0, HTTP/1.1, HTTP/2, HTTP/3) are supported by httplib but I did not get any information. Please document this info. And also, how to setup these versions in code?

**Comment by PixlRainbow** [comment]
Hi, based on inspecting the code this library only supports 1.0 and 1.1, although it will *always* automatically prefer 1.1. There is no way to configure version used.

**Comment by kushwahashivam** [comment]
Thanks. This is the fastest github response I got :)
