### ISSUE TITLE
CPPHTTPLIB_THREAD_POOL_COUNT allowed to be zero

### ISSUE THREAD

**Issue by genakazachek** [yhirose/cpp-httplib#633]
If std::thread::hardware_concurrency() returns 1, which is possible for virtual environments, CPPHTTPLIB_THREAD_POOL_COUNT macro evaluate to zero leading to non working application

**Comment by yhirose** [comment]
@genakazachek, thank you for the feedback, but I probably don't fully understand the situation that you are talking about. In the current code, `CPPHTTPLIB_THREAD_POOL_COUNT` becomes at least 8 even when `std::thread::hardware_concurrency()` returns 1;

```cpp
#define CPPHTTPLIB_THREAD_POOL_COUNT                                           \
  ((std::max)(8u, std::thread::hardware_concurrency() > 0                      \
                      ? std::thread::hardware_concurrency() - 1                \
                      : 0))
```

Hope it helps!
