### ISSUE TITLE
CMake 3.18.2 on linux + GCC 10.2  cmake makes empty -D options

### ISSUE THREAD

**Issue by JodiTheTigger** [yhirose/cpp-httplib#638]
the quote marks in the cmake file confuse cmake and result in the command line doing silly things like `-D\"CPPHTTPLIB_BROTLI_SUPPORT\"`. Which confuses everything involved resulting in a failed build.

solution is to change the following:
```cmake
# Set the definitions to enable optional features
target_compile_definitions(${PROJECT_NAME} ${_INTERFACE_OR_PUBLIC}
	$<$<BOOL:${HTTPLIB_IS_USING_BROTLI}>:"CPPHTTPLIB_BROTLI_SUPPORT">
	$<$<BOOL:${HTTPLIB_IS_USING_ZLIB}>:"CPPHTTPLIB_ZLIB_SUPPORT">
	$<$<BOOL:${HTTPLIB_IS_USING_OPENSSL}>:"CPPHTTPLIB_OPENSSL_SUPPORT">
)
```

to

```cmake
# Set the definitions to enable optional features
target_compile_definitions(${PROJECT_NAME} ${_INTERFACE_OR_PUBLIC}
	$<$<BOOL:${HTTPLIB_IS_USING_BROTLI}>:CPPHTTPLIB_BROTLI_SUPPORT>
	$<$<BOOL:${HTTPLIB_IS_USING_ZLIB}>:CPPHTTPLIB_ZLIB_SUPPORT>
	$<$<BOOL:${HTTPLIB_IS_USING_OPENSSL}>:CPPHTTPLIB_OPENSSL_SUPPORT>
)
```

tested:
* Win10 - MSVC2017
* Arch Linux - GCC 10.2

**Comment by sum01** [comment]
Huh, I never had this issue and I'm on Arch as well.

**Comment by yhirose** [comment]
@JodiTheTigger, thank you for the suggestion. I don't maintain the CMake related code. Could you make a pull request for it? Then, if @sum01 thinks the change looks ok, I'll merge it right away. Thanks!

**Comment by yhirose** [comment]
@sum01, please let me know if you approve #645.

**Comment by sum01** [comment]
@yhirose Looks good
