### ISSUE TITLE
how to user https?It went wrong ...

### ISSUE THREAD

**Issue by Ives88** [yhirose/cpp-httplib#640]
I use like bellow:
`httplib::Client cli2("https\://www.baidu.com");
auto res0 = cli2.Get("/test");`
or 
`httplib::Client cli2("https://www.baidu.com");
auto res0 = cli2.Get("/test");`
it went wrong, how should I use https??

**Comment by yhirose** [comment]
@Ives88, as long as the site supports https requests, you can use it.

**Comment by Ives88** [comment]
Forgive me for not being familiar with C++，Is that my writing wrong?

**Comment by Ives88** [comment]
> @Ives88, as long as the site supports https requests, you can use it.

I run on windows, but crash

**Comment by yhirose** [comment]
@Ives88, sorry, but I don't have time to help you... The only thing I can tell you is to make sure you install the OpenSSL library and follow the instruction on README, then it should work. Hope it helps.

**Comment by Ives88** [comment]
I'm sure it will happen while use https as below test code:
![微信截图_20200909140753](https://user-images.githubusercontent.com/1811464/92561069-12ac5c00-f2a6-11ea-8159-68badacb32f1.png)
and other test code without https in your test.cc is ok 
![微信截图_20200909141019](https://user-images.githubusercontent.com/1811464/92561152-3e2f4680-f2a6-11ea-91e0-468dba6865de.png)
@yhirose

**Comment by Ives88** [comment]
I used vs2017 on windows...
