### ISSUE TITLE
Chinese parameter garbled code

### ISSUE THREAD

**Issue by hailiangchen** [yhirose/cpp-httplib#641]
std::string content = request.get_param_value("message");

**Comment by yhirose** [comment]
@hailiangchen, could you explain more about it?

**Comment by hailiangchen** [comment]
I know the reason of the problem, the Chinese parameters need to use GB2312 Urlencode

**Comment by yhirose** [comment]
@hailiangchen, thank you for the explanation. This library doesn't do encoding/decoding for user given text such as parameter text or body text even for UTF-8. It's a totally user's responsibility.
