### ISSUE TITLE
Substitute for removed  set_timeout_sec

### ISSUE THREAD

**Issue by Zbysekz** [yhirose/cpp-httplib#642]
With commit
72ce293fed9f9335e92c95ab7d085feed18c0ee8
(20.7.2020)

set_timeout_sec() was removed, is there any alternative or it is not important anymore?

I can't find anything more about this.

Thank you

**Comment by yhirose** [comment]
@Zbysekz, `set_connection_timeout` is the one you want. Hope it helps!
