### ISSUE TITLE
Is there a way can calculate the response time of each request?

### ISSUE THREAD

**Issue by EVINK** [yhirose/cpp-httplib#646]
I love your work, it is really great. I look up your sample code in this repository, but I did not find a way can calculate the response time...

It will be great if this lib can provide related api when before a request arrive/ after response sent.

It is like ...
```c++

     Server server;
     server.before_request();
     server.after_response();
   
```

**Comment by yhirose** [comment]
@EVINK, thank you for the question. The short answer is no, also I am not interested in adding such functions on the server. I usually use HTTP performance measuring tools like Apache Bench. Hope it helps!
