### ISSUE TITLE
Is it safe to use errno for socket errors?

### ISSUE THREAD

**Issue by miketsts** [yhirose/cpp-httplib#647]
Hi,

From recently, the library provides more detailed error codes which is very nice addition.
In my case, I've got Error::Read or Error::Write. Would it be safe to use errno for further error details?

Thanks

**Comment by yhirose** [comment]
@miketsts, thanks for the feedback. I don't think errno is not reliable at the time the when an API call returns in most of situations. In other words, errno could be wiped out with a next error. So I don't recommend to do it. Hope it helps.
