### ISSUE TITLE
Client Got 401 error code

### ISSUE THREAD

**Issue by Zhehua-Hu** [yhirose/cpp-httplib#650]
Hi, first of all , goodjob for your library!

I have a server api need basic auth with blank user name and effective password, but `cli.set_basic_auth("", "12345"); `does not achieve goal. I use postman to prove that api works and need blank username.

Any idea about how to solve it?

**Comment by PixlRainbow** [comment]
@yhirose I've identified the offending section: https://github.com/yhirose/cpp-httplib/blob/e9575bcb783d9b731c133be47c50b03130d9ef8d/httplib.h#L4874-L4883

Interestingly, although [RFC 7613](https://tools.ietf.org/html/rfc7613) states that "_A username MUST NOT be zero bytes in length._" this does not appear to be enforced in practice, as [Chrome supports sending zero length usernames](https://stackoverflow.com/a/27044051) and various servers ([example](https://skovpen.org/tst/)) support blank usernames.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the research. I am tending to lift the restriction due to the fact that a number of servers accept blank username. I'll ponder over it for a while.

@Zhehua-Hu, could you try the following change at line 4874 in httplib.h to see your server now responds to the request?

```cpp
if (!basic_auth_password_.empty()) { 
```

Thanks!

**Comment by Zhehua-Hu** [comment]
Thank you all! It is the correct code that solved my problem! 
Goodjob , guys!

**Comment by yhirose** [comment]
@Zhehua-Hu, thanks for the confirmation. I just merged the change to the master branch.
