### ISSUE TITLE
Compatibility with OpenSSL versions < 1.1.1

### ISSUE THREAD

**Issue by omjego** [yhirose/cpp-httplib#651]
Hey @yhirose , recently the library [stopped supporting](https://github.com/yhirose/cpp-httplib/commit/8a348f17fdab9d40336a5b4a12959df4e6ac4653)  openssl versions < 1.1.1   
But apparently it doesn't use any incompatible API, as it compiles with old version of openssl anyways. So is it safe to ignore the version check?   
Thank you :)

**Comment by yhirose** [comment]
@omjego, please see #192. Hope it helps.
