### ISSUE TITLE
Problem with server: *** stack smashing detected ***: <unknown> terminated 

### ISSUE THREAD

**Issue by zenereyes** [yhirose/cpp-httplib#655]
I initialized the following server with some POST. 

`#ifdef CPPHTTPLIB_OPENSSL_SUPPORT
    SSLServer svr(SERVER_CERT_FILE, SERVER_PRIVATE_KEY_FILE);
#else
    Server svr;
#endif
    try
    {

    svr.Post("/SendSensorInit", [&](const Request& req, Response & res) {

        int v2 = rand() % 10 + 1;

        if (v2 >= RANGE_LOW && v2 <= RANGE_HIGHT)
                res.set_content("ERROR", "esito");
        else
            res.set_content("OK", "esito");
        
        cout << req.remote_port << endl;
        cout << k++ << endl;
        });`

The client calls POST repeatedly, but after 1081 calls the server says:

*** stack smashing detected ***: <unknown> terminated 

I noticed that the client always changes the connection port (req.remote change always), though the client is always connected.

Thanks

**Comment by yhirose** [comment]
@zenereyes, thanks for the the information. It seems to be a bug in Keep-Alive connection handing code. I'll take a look it when I have time.

**Comment by yhirose** [comment]
@zenereyes, I took a look at this problem a little bit, but I can't reproduce the problem that a connection port of client is always different... What client are you using, curl or `httplib::Client`? (If you are using `httplib::Client`, did you set `true` to `cli.set_keep_alive` method?

**Comment by zenereyes** [comment]
I used httplib::SSLClient not httplib::Client.
I will set true in cli.set_keep_alive

**Comment by yhirose** [comment]
It doesn't matter. Hope it helps!
