### ISSUE TITLE
Get Json response from an API call.

### ISSUE THREAD

**Issue by shubhwicked** [yhirose/cpp-httplib#665]
How can we get JSON response while calling an API with Get request.

**Comment by yhirose** [comment]
@shubhwicked, thanks for the feedback. This library doesn't do anything with body text with MIME type`. In order to parse a JSON response, you have to use other JSON library like https://github.com/nlohmann/json. Hope it helps!

**Comment by shubhwicked** [comment]
Can you help me or give me some link, how to do that in your library. I am very new to cpp. How can i use this json.hpp library to get json response in Get request.

**Comment by PixlRainbow** [comment]
The response body is an `std::string`. In the case of JSON responses, it will contain the json text. If you want to know how to convert a string into a "proper" object with real nested attributes, ask the other library; our library is only responsible for handling networking and the base HTTP communication.

If the API endpoint does not correctly respond with JSON, you may need to add a header "Accept" with the value "application/json"
