### ISSUE TITLE
HTTPS support.

### ISSUE THREAD

**Issue by shubhwicked** [yhirose/cpp-httplib#667]
How to get HTTPS support.

**Comment by PixlRainbow** [comment]
[see this section of the readme](https://github.com/yhirose/cpp-httplib#openssl-support)

**Comment by yhirose** [comment]
Hope the @PixlRainbow's comment helps.

**Comment by shubhwicked** [comment]
Yes, I saw that, but it cannot be added in android like OpenSSL classes are not available with a single header file, that is httplib. If I add all the classes of OpenSSL from an external source, then it cannot be built.

**Comment by PixlRainbow** [comment]
then build and link OpenSSL statically so that it will be built into your single binary.

**Comment by shubhwicked** [comment]
It throw `httplib.h:5589: error: undefined reference to 'OPENSSL_init_ssl'` error all the time, while building, any idea?

**Comment by PixlRainbow** [comment]
Possible reasons:
1. linked in incorrect order
2. OpenSSL version mismatch or conflict
3. static binaries not available

**Comment by shubhwicked** [comment]
Can you give me the correct order of the binary binding, and I am using
openssl 1.1.1h

**Comment by PixlRainbow** [comment]
`-lcrypto` must come before `-lssl` but there may be other parameters needed, check StackOverflow website

**Comment by shubhwicked** [comment]
Hey with help, I build all stuff with openssl, libcrypto.a,-libssl.a  &  httplib.
but when I make a request, it always returns null as a response.

`   httplib::SSLClient cli("myhost");
    cli.set_ca_cert_path("/src/main/ca-bundle.crt");
    cli.enable_server_certificate_verification(true);
     auto res=cli.Get("sub-domain");`

res always return null. Is anything else need to be done.
