### ISSUE TITLE
Client GET and POST to ssl server does not work

### ISSUE THREAD

**Issue by YourCodeShepherd** [yhirose/cpp-httplib#668]
Hello,

when I try to get an authorization token from our server or I use an valid token of the type bearer I always get the error httplib::SSLConnection in my client. The server can be pinged. I test the functionality with two different ways to use the lib:

`
#define CPPHTTPLIB_OPENSSL_SUPPORT
#include "httplib.h"

int main(int ac, char* av[])
{
    
    httplib::Client client("https://192.168.1.2");
    client.set_bearer_token_auth("xxxxx");
    auto res = client.Get("/automation/api/v1/?type=browse"); 
    if (res){
      std::cout << "response = " <<  res->status << std::endl;
      std::cout << "body = " <<  res->body << std::endl;
    }
    else{
      std::cout << "ERROR GET" << std::endl;
    }
    
    httplib::SSLClient authclient("192.168.1.2");    
    authclient.set_default_headers({
       { "Content-Type","application/json" }
    });

    httplib::Params params{
      { "name", "xxxxx" },
      { "password", "xxxxx" }
    };

    res = authclient.Post("/identity-manager/api/v1.0/auth/token", params); 
    if (res){
      std::cout << "response = " <<  res->status << std::endl;
      std::cout << "body = " <<  res->body << std::endl;
    }
    else{
      std::cout << "ERROR POST" << std::endl;
    }

}
`
![2020-09-24_17h13_26](https://user-images.githubusercontent.com/55376411/94164638-93b04980-fe89-11ea-800d-038bf5d72a6d.png)
![2020-09-24_17h23_11](https://user-images.githubusercontent.com/55376411/94165548-a2e3c700-fe8a-11ea-8840-61aba8d9d311.png)

When using an REST clinet in my browser the same requests are working:
![2020-09-24_17h24_18](https://user-images.githubusercontent.com/55376411/94165855-f229f780-fe8a-11ea-8dce-e38b6da99f17.png)

What am I doing wrong?

**Comment by yhirose** [comment]
@YourCodeShepherd, yes. You should `set_content`. Hope it helps.
