### ISSUE TITLE
Get request

### ISSUE THREAD

**Issue by godrays** [yhirose/cpp-httplib#670]
Hi,

I'm trying to use httplib to get the following request. What would be the simplest equivalent code for the following request with httplib?

curl -X GET --header "Authorization: " "https://api.tdameritrade.com/v1/marketdata/AAPL/pricehistory?apikey=XXXXXXXX&periodType=day&period=1&frequencyType=minute&frequency=1"

I'm also interested to see if httplib can include the following parametes in given url programmatically.
"apikey=XXXXXXXX&periodType=day&period=1&frequencyType=minute&frequency=1"

Thanks!

**Comment by PixlRainbow** [comment]
You haven't indicated the value of the authorization header/the type of authorization, [though we do provide pre-made headers for several types](https://github.com/yhirose/cpp-httplib#authentication).

We do not provide automatic URL parameter construction for client requests. You will have to construct the path string yourself.

**Comment by yhirose** [comment]
Hope @PixlRainbow's comment helps you.
