### ISSUE TITLE
disable request path encoding

### ISSUE THREAD

**Issue by hlafet-ledger** [yhirose/cpp-httplib#672]
Is it possible to add some kind of parameter or a preprocessor option to give the choice to the user of the library to encode or not the request path:

Current code:
https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L4838
Suggestion:
const auto &path = someParameter ? detail::encode_url(req.path) : req.path;

Thanks

**Comment by yhirose** [comment]
@hlafet-ledger, thanks for the feedback, but I have never found it necessary, and I feel that's not a safe thing to do. Could you explain more why such feature is needed?

**Comment by yhirose** [comment]
@hlafet-ledger, I decided not to implement the suggestion. Please let me know if you think there is a valid reason and many others can also benefit from the change. Thanks!
