### ISSUE TITLE
The server doesnot work on ubuntu

### ISSUE THREAD

**Issue by zxnblake** [yhirose/cpp-httplib#675]
It can listen on a port, but when a client does get/post, the server will throw error:
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Signal: SIGABRT (Aborted)
Can anyone help me out?

**Comment by yhirose** [comment]
@zxnblake, thanks for the feedback. I don't know your environment, but there are two possibilities:

* https://github.com/yhirose/cpp-httplib#g
* Your URL is invalid regular expression

Hope it helps!

**Comment by zxnblake** [comment]
is there any wrong with the following url: curl -G http://localhost:8080/hi?

> @zxnblake, thanks for the feedback. I don't know your environment, but there are two possibilities:
> 
> * https://github.com/yhirose/cpp-httplib#g
> * Your URL is invalid regular expression
> 
> Hope it helps!

Is there any wrong with the following url: curl -G http://localhost:8080/hi?

**Comment by yhirose** [comment]
I think 4.8.5 also has the regular expression problem. I recommend to upgrade it to 4.9 or later.

**Comment by zxnblake** [comment]
OK， I will have a try, thank you!

> I think 4.8.5 also has the regular expression problem. I recommend to upgrade it to 4.9 or later.
