### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by vader-coder** [yhirose/cpp-httplib#677]
When I try to run this code I get a Segmentation Fault.

#include "httplib.h"
#include <iostream>
using namespace std;
int main() {
    cout << "running";
    httplib::Client cli("http://cpp-httplib-server.yhirose.repl.co");
    auto res = cli.Get("/hi");
    if (res->status == 200) {
        cout << res->body << endl;
    }
return 0;
}

**Comment by yhirose** [comment]
@vader-coder, could you run unit tests on your machine? `cd test && make test`? Thanks!

**Comment by yhirose** [comment]
@vader-coder, I cound't reproduce it. Here is my result.

```bash
> cat main.cpp 
#include <iostream>
#include "./httplib.h"

int main() {
  httplib::Client cli("http://cpp-httplib-server.yhirose.repl.co");
  
  auto res = cli.Get("/hi");

  if (res) {
    std::cout << res->status << std::endl;
    std::cout << res->body << std::endl;
  }
}

> g++ -std=c++17 -o main main.cpp

> ./main 
Debug: 12
Debug: text/plain
Debug: Sat, 03 Oct 2020 02:33:29 GMT
Debug: 1.1 google
Debug: close
200
Hello World!
```

Hope it helps.

**Comment by PixlRainbow** [comment]
@vader-coder your code does not check if `res` is nullptr, which it will be if there is no connection to the server (e.g. offline). See yhirose's example
