### ISSUE TITLE
params["name"] = "john" doesn't compile

### ISSUE THREAD

**Issue by mkdotcom** [yhirose/cpp-httplib#68]
Hello
Thanks for the lib!

I got an issue with "httplib::Params". 

According to readme we can fill in post parameters like this :

httplib::Params params;
params["name"] = "john";

But it doesn't compile : error C2676: binary '[': 'httplib::Params' does not define this operator or a conversion to a type acceptable to the predefined operator

Params is a std::multimap and it seems it doesn't support this way to insert element.

**Comment by yhirose** [comment]
@mkdotcom, thanks for the report. yes, you are correct.

I changed to use std::multimap from std::map at this commit https://github.com/yhirose/cpp-httplib/commit/c3346a481538f01748e5a60b158ac18aac6197ac.

```cpp
params.emplace("key", "value");
```

I think it's not very convenient. I'll think about making the interface easier to use. We now have to do as bellow.

**Comment by mkdotcom** [comment]
Thanks you
