### ISSUE TITLE
Timeouts don't apply to SSLClient*

### ISSUE THREAD

**Issue by FrozenSource** [yhirose/cpp-httplib#680]
Hi,
Loving this library so far, however I seem to have found a problem in which the timeouts do not apply to at least the SSLClient.

```cpp
#define CPPHTTPLIB_OPENSSL_SUPPORT
#define CPPHTTPLIB_CONNECTION_TIMEOUT_SECOND 2
#define CPPHTTPLIB_CONNECTION_TIMEOUT_USECOND 0
#define CPPHTTPLIB_READ_TIMEOUT_SECOND 2
#define CPPHTTPLIB_READ_TIMEOUT_USECOND 0
#include <httplib.h>
```

For the following configuration, the ssl implementation waits for about 30s or so....

```cpp
httplib::SSLClient cli(C_ServerRemote, 443);
cli.enable_server_certificate_verification(false);
cli.set_follow_location(true);
std::string sBuffer;
httplib::Headers headers;
headers.emplace("Accept-Encoding", "gzip, deflate");
headers.emplace("Accept", "text/plain");
auto res = cli.Get("/cli/latest", headers);
```

The following returns in 2 seconds as expected.

```cpp
httplib::Client cli(C_ServerRemote, 80);
cli.set_follow_location(true);
std::tring sBuffer;
httplib::Headers headers;
headers.emplace("Accept-Encoding", "gzip, deflate");
headers.emplace("Accept", "text/plain");
auto res = cli.Get("/cli/latest", headers);
```

Wonder if you know a fix for this?

Sincerely,
FrozenSource

**Comment by yhirose** [comment]
@FrozenSource, could you format the code snippets to make it more readable? Thanks!

**Comment by yhirose** [comment]
@FrozenSource, thank you! (I make another simple formatting change to use the GitHub markdown code highlighting feature.)
I would like to clarify the issue. Which has the problem, `CPPHTTPLIB_CONNECTION_TIMEOUT_SECOND` or `CPPHTTPLIB_READ_TIMEOUT_SECOND`?

**Comment by FrozenSource** [comment]
@yhirose I see so you need three of those '`'. Since you get a read error when the connection could not be made since the remote is offline I take it `CPPHTTPLIB_READ_TIMEOUT_SECOND` is not working in an SSL envrionment.

**Comment by yhirose** [comment]
@FrozenSource, sorry that my question confuses you. I am asking, is it a connection timeout problem, or a reading timeout problem?

**Comment by FrozenSource** [comment]
@yhirose A read timeout error, since the connection is made but no answer is provided.

**Comment by yhirose** [comment]
@FrozenSource, I acknowledged the problem on my machine. I'll work on it when I have time. Thanks!

**Comment by yhirose** [comment]
@FrozenSource, I tried to reproduce the problem on my machine, but I didn't succeed so far. Here is a new unit test to simulate read time out on SSL (read timeout on client is 1 second. server response takes 2 seconds).

https://github.com/yhirose/cpp-httplib/blob/316add860b22578bdeebcced8dfa7e45b57ccf61/test/test.cc#L2995-L3035

The unit test succeeds without any problem on my machine. Could you run the test on your machine as well with `cd test && make test && ./test --gtest_filter="*Timeout*"`?

Thanks for your help.

**Comment by FrozenSource** [comment]
I totally trust the unit tests! 

I have been looking into this a little further... The infrastructure is like this. Domainname->Router->Proxy-Server->Host. The proxy-server in this instance is a normal ngix server with ssl enabled, host is a normal httplib::Server. Should the Host be offline nginx will apparently wait 60s before returning 503. Now I would suggest that this should comply with the READ_TIMEOUT but this is something that is not the case. The weird thing is that over a plain connection this is the case and returns normally. I have only worked with openssl a little but it might be an openssl thing, unless you know a way to make this work.

**Comment by yhirose** [comment]
@yhirose, could you try to send the same HTTPS request with curl to see what happens?

**Comment by FrozenSource** [comment]
curl -s -m 2 https://domain Returns empty just fine....

**Comment by yhirose** [comment]
I mean `curl -m 2 "https://${C_ServerRemote}/cli/latest"` (${C_ServerRemote} should be replaced with the same host name in your example.)?

**Comment by FrozenSource** [comment]
Yeah that one, then again it didn’t matter since the host is offline.

**Comment by yhirose** [comment]
@FrozenSource, thanks for the report. I honestly don't understand why the problem happens in your network environment. Since the regular HTTP call works, the problem seems to be caused in OpenSSL. But I can't say my guess is true, because I am not able to reproduce it and cannot confirm it on my machine... So I would very much appreciate it if you debug the read timeout problem on your machine. The reading timeout is handled here in httplib.h:

https://github.com/yhirose/cpp-httplib/blob/7e8db1dc68b94bb9949bffe2a5e23e6eea1277a4/httplib.h#L3678-L3680

I guess `select_read` call doesn't timeout as expected on your machine. Sorry that I can't help you very much, but hope this information helps you!

**Comment by FrozenSource** [comment]
Very well will look into that then. Btw to be precise if you want to reproduce it. I use this https://github.com/jlesage/docker-nginx-proxy-manager in docker as the proxy.

**Comment by FrozenSource** [comment]
Okay I found it out, 5676 is a blocking call..... (SSL_read). Since the socket connection is readable it enters that state at 5675 but since data only becomes available 60s later it only then returns. iPending in this case is still 0 when it enters the blocking call... Problem is that I am not familiar with the code, so am unable to really try anything. Removing the is_available makes it returning practically instantly and not only after 2 seconds like I except it to, maybe you can help at this point?

**Comment by yhirose** [comment]
@FrozenSource, thanks for the deail. It rings a bell actually. It sounds similar to https://github.com/yhirose/cpp-httplib/issues/150#issuecomment-506338268. As you can see in the comment, it's pretty hard to fix the problem because we can not control the blocking behavior happening inside `SSL-read`. But I'll ponder over it to find a way to solve the problem.
Thanks again for the valuable information!

**Comment by FrozenSource** [comment]
Well atleast we found it. Now it might not be the best and a bit c++17 but might I suggest this since this seems to work just fine.... Also dont blame me for the hungarian Pascal I am not the snake kinda guy.

```
#include <chrono>
inline ssize_t SSLSocketStream::read(char *ptr, size_t size) {
  auto oTime = std::chrono::steady_clock::now();
  auto uiMiliseconds = (read_timeout_sec_ * 1000) + read_timeout_usec_;
  const unsigned int uiSleepTime = 1;
  while ((unsigned int)(std::chrono::duration_cast<std::chrono::milliseconds>(
                            std::chrono::steady_clock::now() - oTime)
                            .count()) < uiMiliseconds &&
         is_readable()) {
    if (SSL_pending(ssl_) > 0) {
      return SSL_read(ssl_, ptr, static_cast<int>(size));
    }
#if defined(__linux__) || defined(__APPLE__)
    usleep(uiSleepTime *
           1000); // usleep takes sleep time in us (1 millionth of a second)
#elif defined(_WIN32) || defined(_WIN64)
    Sleep(uiSleepTime);
#endif
  }
  return -1;
}
```

**Comment by yhirose** [comment]
@FrozenSource, great! Could you confirm that your suggested code fixes the problem on your machine since I am not able to reproduce it right now. Then could you make a pull request and send it, so that GitHub Actions flow will check if all the existing unit tests pass with the pull request. But no rush! (I'll also do some research about SSL_read with non-blocking socket.)

**Comment by FrozenSource** [comment]
Will do I wrote this in a sec since I am in transit when I have time tomorrow I will optimize and do as you suggest.

**Comment by FrozenSource** [comment]
Could you give me permissions, I can't seem to create a branch...?

**Comment by yhirose** [comment]
@FrozenSource, since this is a GitHub project, you have to work on a fork. You can do it by hitting the "Fork" button on the top right corner. Please see the GitHub documentation about how to create a pull request from a fork.

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

Hope it helps!

**Comment by FrozenSource** [comment]
@yhirose Is it possible for you to check the unix based? I don't have such system available... Seems only the windows platform succeeded which is what I also use.

**Comment by yhirose** [comment]
@FrozenSource, I would like to check on Mac and Linux, but since I am not able to reproduce the problem on my machine, there is no way for me to check. Is it possible for you to make it fully cross-platform?

**Comment by FrozenSource** [comment]
well if you want it is really quite easy just install docker and run 
```
docker run -d \
    --name=nginx-proxy-manager \
    -p 8181:8181 \
    -p 8080:8080 \
    -p 4443:4443 \
    -v /docker/appdata/nginx-proxy-manager:/config:rw \
    jlesage/nginx-proxy-manager
```
Create a proxy and no host needs to be attached since that is the issue. As I specified above linux doesn't have this problem thus also supposing MacOS doesn't because they both use the posix specification. The SSL_Read function uses the recv() function internally and should comply with the read timeout which is set. But I believe on windows maybe a definition (integer) or something might be different on Windows causing it to not work. Should you be able to reproduce on your Mac is would either be a definition problem or OpenSSL problem entirely. But you might know the definitions better since you have been working on this far longer... I wrote a http library once but came here because it didn't work like it should.

**Comment by yhirose** [comment]
@FrozenSource, thanks for the information. I'll try to setup the proxy and reproduce the problem on my machine when I have time. Thanks!

**Comment by yhirose** [comment]
@FrozenSource, what happened with https://github.com/yhirose/cpp-httplib/pull/693?

**Comment by FrozenSource** [comment]
It did not work in this case because of API above. None the matter since it should be a socket thing. Did you find anything out concerning this?

**Comment by yhirose** [comment]
@FrozenSource, no, I haven't started investigating it, since it's pretty hard to reproduce it. So, I was just thinking to review your pull request first, and merge it to the master if it looks good and doesn't make any side effects on Mac and Ubuntu.

**Comment by yhirose** [comment]
@FrozenSource, it may be related to #698. The latest master httplib.h has the fix. Could you try it on your environment to see if your issue still exists? Thanks!

**Comment by FrozenSource** [comment]
Thx will do!

**Comment by yhirose** [comment]
@FrozenSource, thanks. As soon as I hear from you, I'll release the new version v0.7.11 including this fix.

**Comment by FrozenSource** [comment]
At the current master I get a compiler error on cToken ::3167 
````
C:\dev\df-cli\build\httplib-source\httplib.h(3167,20): error C2589: '(': illegal token on right side of '::' [C:\dev\df-cli\build\df-cli-lib.vcxproj]
[build] C:\dev\df-cli\build\httplib-source\httplib.h(3167,20): error C2062: type 'unknown-type' unexpected [C:\dev\df-cli\build\df-cli-lib.vcxproj]
[build] C:\dev\df-cli\build\httplib-source\httplib.h(3167,20): error C2059: syntax error: ')' [C:\dev\df-cli\build\df-cli-lib.vcxproj]
````
https://github.com/FrozenSource/cpp-httplib my fork didn't have this compiler error but I can't find out what changed.

**Comment by yhirose** [comment]
It seems #711 causes this problem. I guess it only happens with pretty old compilers. I made a change at 953600c1775c5e8645c62e3f4eefd32d6c41cbdd.
Could you try with the latest? Thanks!

**Comment by FrozenSource** [comment]
Oh no this happens when Windows.h is included. this provides min and max. Will try in a couple hours.

**Comment by FrozenSource** [comment]
It is solved! Nice! btw. "old compiler".... 🗡️ VS2019.

**Comment by yhirose** [comment]
@FrozenSource, thanks a lot for testing and long patience! I'll release it soon.
