### ISSUE TITLE
Cert format

### ISSUE THREAD

**Issue by blkdragn77** [yhirose/cpp-httplib#681]
I apologize for asking this, but the document did not specify.  What format do the ca certs need to be in for this library?  I have created a CA bundle from the Windows certificate store on my laptop and converted that from PKCS12 to PEM.  When attempting a SSLClient connection, the result comes back null.

I created a connection to http://www.apache.org using httplib::Client just to make sure I could connect to a site and it came back just fine.  Maybe I am missing something with the SSLCert?  Here is what I currently have setup.

`httplib::SSLClient cli("https://www.google.com", 443);`
`cli.set_ca_cert_path(cert.c_str());`
`cli.enable_server_certificate_verification(false);`
`auto res = cli.Get("/");`

Here is the error when attempting to read res->status

res.res_._Ptr was nullptr

Any suggestions would be much appreciated.

Also, huge appreciation for the work everyone has done on this library.  This is so much simpler than the other projects like C++ REST SDK.

**Comment by yhirose** [comment]
@blkdragn77, thanks for the feedback. As you can see the following code, the given cert path will eventually be passed to the OpenSSL API `SSL_CTX_load_verify_locations`. 

https://github.com/yhirose/cpp-httplib/blob/143b2dd15a6e89aca19bbc65730f0dd9f8b7b1e1/httplib.h#L5923-L5933

So I recommend you to check with the OpenSSL document to get the most accurate information:
https://www.openssl.org/docs/manmaster/man3/SSL_CTX_load_verify_locations.html

Hope it helps!

**Comment by PixlRainbow** [comment]
> `cli.enable_server_certificate_verification(false);`

@blkdragn77 the fact that you have disabled server certificate verification means that the cert you provided will be ignored, and the validity of the server's certificate is also ignored. This means that the connection will be "approved" by the client regardless of the validity of the certificate you provided.
**_Thus, it is unlikely that the connection is null because of the certificate_** and more likely that something else is happening e.g. bad connection or incorrect domain or path format

**Comment by yhirose** [comment]
@PixlRainbow, thank you for the much better observation and explanation!

**Comment by blkdragn77** [comment]
Thank you.  You are correct, I disabled cert verification to avoid the whole handshake.  That slipped my mind after trying to figure this out for an hour or so.  Just a little frustrated that the non-SSL returns fine, but I cannot get the SSL client to return anything.  I printed out the OpenSSL error string, but it was all zeros.

error:00000000:lib(0):func(0):reason(0)

I switched over to https://www.apache.org as it looks like Google is doing a redirect and thought maybe that was causing a problem, but same result with the Apache https site....no error reported from OpenSSL and result is null pointer.

`httplib::Client cli("http://www.apache.org");`
`auto res = cli.Get("/");`
Returns
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Home page of The Apache Software Foundation">

While
`httplib::SSLClient cli("https://www.apache.org", 443);`
`cli.enable_server_certificate_verification(false);`
`auto res = cli.Get("/");`
Returns
OpenSSL Error:  error:00000000:lib(0):func(0):reason(0)
VS Debug for Client:  error_	Connection (2)	httplib::Error
Result variable:  res.res_._Ptr was nullptr

Is there something stupid simple that I am missing here?

**Comment by PixlRainbow** [comment]
try omitting the `https://` from the front of the domain?

**Comment by blkdragn77** [comment]
Right.  Thank you.  Not sure why I didn't try that.  :(  The non-SSL worked with http:// so I guess I assumed https:// would as well.  That's what I get for assuming.  Works fine now.

Again, great work you all have done here.  To hit an API within C++ with just a few lines of code is very nice.
