### ISSUE TITLE
Get request do not work in app (and work fine from chrome browser)

### ISSUE THREAD

**Issue by OldSnake22** [yhirose/cpp-httplib#685]
Hello i'm currently running into an issue. My request return a '400 bad request' error but when I test the same request in chrome browser for example or with API online test tools this request works perfectly.

Here is the code:

 httplib::SSLClient _Client("myurl.com");
 httplib::Result _Result = _Client.Get("/api/core/hello?key=MYKEY");
...

Nothing fancy, so this is returning "400 bad request". Same request from chrome browser is working nicely. I can't understand what is going wrong. Do someone have an idea ? 

I am also using Google API and some other API's without any issues in my app. 

Thanks for your help !

**Comment by PixlRainbow** [comment]
maybe you need to set some headers? Or that your `accept` header must indicate that your client is compatible with JSON, XML, TXT, or otherwise? Either that or cookies.

**Comment by OldSnake22** [comment]
It seems that no headers are required. When I test the request with this online tool with no headers: https://extendsclass.com/rest-client-online.html

Everything is working. But the request in my app still give a "400 bad request"...

Here is the response header if it can help: 

HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: 117
Connection: keep-alive
Date: Thu, 08 Oct 2020 11:17:51 GMT
Server: Apache/2.4.46 (Amazon) OpenSSL/1.0.2k-fips PHP/7.3.21
X-Powered-By: PHP/7.3.21
Set-Cookie: PHPSESSID=dl9i7l6ceapvv8fer829s8dlls; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-IPS-LoggedIn: 0
X-XSS-Protection: 0
X-Frame-Options: sameorigin
Vary: cookie
X-Cache: Miss from cloudfront
Via: 1.1 e11502649b2fdd9cb3960f027c8c1ea2.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: LHR3-C2
X-Amz-Cf-Id: --xzHACVMRW6hRuhgMoBbtfay5WYJn-_5NiccM2rEd3-a8ZxCYeUTg==

**Comment by yhirose** [comment]
@OldSnake22, could you try to send the same request with `curl -v` to see what will happen?

**Comment by OldSnake22** [comment]
Hello @yhirose this request is also working with curl on my machine as you can see: 

PS C:\Users\Franck\Desktop\curl-7.72.0-win64-mingw\bin> curl -v https://www.rwcentral.com/api/core/hello?key=492e8c965007865ce6bd8c4beea01497
COMMENTAIRES : GET https://www.rwcentral.com/api/core/hello?key=492e8c965007865ce6bd8c4beea01497 with 0-byte payload
COMMENTAIRES : received 117-byte response of content type application/json;charset=UTF-8

StatusCode        : 200
StatusDescription : OK
Content           : {
                        "communityName": "RW Central",
                        "communityUrl": "https:\/\/www.rwcentral.com\/",
                        "ipsVersion": "4.5.3"
                    }
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Pragma: no-cache
                    X-IPS-LoggedIn: 0
                    X-XSS-Protection: 0
                    X-Frame-Options: sameorigin
                    Vary: cookie
                    X-Cache: Miss from cloudfront
                    X-Amz-Cf-Pop: MRS52-C1
                    X-A...
Forms             : {}
Headers           : {[Connection, keep-alive], [Pragma, no-cache], [X-IPS-LoggedIn, 0], [X-XSS-Protection, 0]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : System.__ComObject
RawContentLength  : 117

**Comment by OldSnake22** [comment]
Also if you would like to test it yourself I could set up a special key for you so you can test it. Please let me know :)

**Comment by yhirose** [comment]
@OldSnake22, thanks for the log, but I wanted to see what header values were added when you were sending the request with curl. It usually add `Host`, `User-Agent` and `Accept` headers.

**Comment by OldSnake22** [comment]
This is the only infos i get when I use the -v option with curl in command line.

**Comment by OldSnake22** [comment]
I have generated a special API KEY if you want to test it yourself. 
So just test this URL and it should work: https://www.rwcentral.com/api/core/hello?key=f499e98d53cb48e71a107ffb514747d9

Thank you for your support !

**Comment by PixlRainbow** [comment]
your curl version appears to be a variant with non-standard output formatting, so it unfortunately did not include the respective information. In any case, here is the full log:
```
*   Trying 2600:9000:2062:e000:11:1600:9380:93a1...
* TCP_NODELAY set
* Connected to www.rwcentral.com (2600:9000:2062:e000:11:1600:9380:93a1) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=rwcentral.com
*  start date: May 12 00:00:00 2020 GMT
*  expire date: Jun 12 12:00:00 2021 GMT
*  subjectAltName: host "www.rwcentral.com" matched cert's "www.rwcentral.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> GET /api/core/hello?key=f499e98d53cb48e71a107ffb514747d9 HTTP/1.1
> Host: www.rwcentral.com
> User-Agent: curl/7.58.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 200 OK
< Content-Type: application/json;charset=UTF-8
< Content-Length: 117
< Connection: keep-alive
< Date: Thu, 08 Oct 2020 13:09:13 GMT
< Server: Apache/2.4.46 (Amazon) OpenSSL/1.0.2k-fips PHP/7.3.21
< X-Powered-By: PHP/7.3.21
< Set-Cookie: PHPSESSID=in28if2mtl79m2dg1ct5gvl1mn; path=/
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< X-IPS-LoggedIn: 0
< X-XSS-Protection: 0
< X-Frame-Options: sameorigin
< Vary: cookie
< X-Cache: Miss from cloudfront
< Via: 1.1 cd8f4ac94836dc54b056844b56c2bb70.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: LHR62-C5
< X-Amz-Cf-Id: ou-7gZDCbHUjRmF8qocmVbNKfZSroKHIk2_irrKVXdHlr0JQTekQZA==
< 
{
    "communityName": "RW Central",
    "communityUrl": "https:\/\/www.rwcentral.com\/",
    "ipsVersion": "4.5.3"
* Connection #0 to host www.rwcentral.com left intact
```

**Comment by OldSnake22** [comment]
Thank you for the detailed log. Can you see anything that could cause the same request in httplib to fail ? Here is my C++ code:

```
 httplib::SSLClient _Client("rwcentral.com");

    httplib::Headers headers = {
      { "Host", "www.rwcentral.com" },
      { "Accept", "*/*" },
    };

    httplib::Result _Result = _Client.Get("/api/core/hello?key=f499e98d53cb48e71a107ffb514747d9", headers);
```

**Comment by PixlRainbow** [comment]
```
TLSv1.3
Status: 400
Connection: close
Content-Length: 122
Content-Type: text/html
Date: Thu, 08 Oct 2020 14:09:05 GMT
Server: awselb/2.0
Via: 1.1 0b21b287f9977a9610eb12d4a4a21302.cloudfront.net (CloudFront)
X-Amz-Cf-Id: v2Qeu2QDRzbcVRLlBSGg3Ti9-fPbR5QbQHP-gH5hCIhBBC9nfpCkCg==
X-Amz-Cf-Pop: LAX3-C4
X-Cache: Error from cloudfront
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
</body>
</html>
```

Cloudfront appears to be blocking the request for some reason.

**Comment by OldSnake22** [comment]
Thanks, now we need to figure out why it is not working with httplib while it's working with curl for example.

**Comment by yhirose** [comment]
@OldSnake22, @PixlRainbow, thanks for the help. I fixed the problem and confirmed with the following code:

```cpp
#include "httplib.h"
#include <iostream>

namespace http = httplib;

int main(int argc, char const *argv[]) {
  http::SSLClient cli("www.rwcentral.com");
  auto res = cli.Get("/api/core/hello?key=f499e98d53cb48e71a107ffb514747d9");

  if (res) {
    std::cerr << "Status: " << res->status << std::endl;
    for (const auto &hdr : res->headers) {
      std::cerr << hdr.first << ": " << hdr.second << std::endl;
    }
    std::cout << res->body << std::endl;
  } else {
    std::cerr << "nope" << std::endl;
  }
  return 0;
}
```

@OldSnake22, could you test with the latest master httplib.h? Thanks!

**Comment by PixlRainbow** [comment]
it appears to be working now.

**Comment by OldSnake22** [comment]
This is fixed ! Thanks a lot to both of you 👍

**Comment by yhirose** [comment]
Thanks for checking!
