### ISSUE TITLE
upload pdf sever example

### ISSUE THREAD

**Issue by fujianhai** [yhirose/cpp-httplib#686]
请问能提供一个上传pdf文件的例子吗？

**Comment by PixlRainbow** [comment]
这软件不管上传文件的种类，对它来说，全部都是二进制数据。
你可以用["multipart/form-data"](https://github.com/yhirose/cpp-httplib#multipartform-data-post-data)，你也可以直接用 `svr.post` 和 `req.body`

**Comment by yhirose** [comment]
@fujianhai, sorry that I don't understand Chinese. Could you write it in English?

**Comment by PixlRainbow** [comment]
They're asking for example server code to handle a PDF upload

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the translation!
