### ISSUE TITLE
Can't get SSLClient to work

### ISSUE THREAD

**Issue by cristiulian** [yhirose/cpp-httplib#687]
I'm trying to use SSLClient with no luck.
I even did a test project, with simple code, taken from your example, but I always get a nullptr result and lead to the "Can't verify result" if-else branch.
I'm thinking it may be the OpenSSL version I'm using (1.1.1e-dev), but I'm not sure. I can provide the text project to take a look at.

`#define CPPHTTPLIB_OPENSSL_SUPPORT

#include <httplib.h>
#include <iostream>

#define CA_CERT_FILE "./ca-bundle.crt"

using namespace std;

int main(void) {

	httplib::SSLClient cli("https://google.com", 443);
	cli.set_ca_cert_path(CA_CERT_FILE);
	cli.enable_server_certificate_verification(false);

	auto res = cli.Get("/hi");
	if (res) {
		cout << "Res valid" << endl;
		cout << res->status << endl;
		cout << res->get_header_value("Content-Type") << endl;
		cout << res->body << endl;
	}
	else {
		cout << "Res not valid" << endl;
		auto result = cli.get_openssl_verify_result();
		if (result) {
			cout << "verify error: " << X509_verify_cert_error_string(result) << endl;
		}
		else {
			cout << "Can't verify result" << endl;
		}
	}

	return 0;
}
`

**Comment by PixlRainbow** [comment]
omit `https://` from the front of the domain.

**Comment by cristiulian** [comment]
I was sure I did that, however, indeed, it does work by removing the https:// from the url.
I even switched to the latest openssl in the meantime.
Thanks!
