### ISSUE TITLE
Http Request Middleware -Benchmark

### ISSUE THREAD

**Issue by vaggeliskls** [yhirose/cpp-httplib#69]
First of all. Contratulation on your excellent work. Iam coming from nodejs world so i found it easy to understand your vision. 

1. Does this library support some kind of middleware functions (auth or ip filter middleware etc.).

2. Secondly, is there any benchmark that compares performance with other frameworks ? (cpprestapi 
 casablanca etc.) 
Thank you.

**Comment by yhirose** [comment]
Thanks for the questions. Answer is no for both questions. This is just a small http library. I am not planning to make it like a web framework.
