### ISSUE TITLE
Multipart form data boundary

### ISSUE THREAD

**Issue by lightvector** [yhirose/cpp-httplib#691]
If I understand the current code correctly, the construction of the multipart form data boundary might a little low-entropy.

Firstly: currently the implementation `make_multipart_data_boundary` seems to do this:
```
  std::random_device seed_gen;
  std::mt19937 engine(seed_gen());
```
And then concatenates 96 random bits worth of entropy from `engine` on to `"--cpp-httplib-multipart-data-"`.

However by my [understanding](https://en.cppreference.com/w/cpp/numeric/random/random_device), `seed_gen()` only returns a single unsigned int. So there are only 2^32 = ~4 billion possible initializations of mt19937 that can be performed. Four billion is not actually that large for modern computers - I think this implies that with adversarial input, within a few tens of gigabytes of constructed data, it should be possible to have a nontrivial chance of that data conflicting with the boundary. Depending on an application, perhaps this in some cases this could become some sort of minor security risk?

Secondly: the use of std::random_device might be problematic. On some systems+toolchains it seems like the device [may actually be deterministic](https://stackoverflow.com/questions/18880654/why-do-i-get-the-same-sequence-for-every-run-with-stdrandom-device-with-mingw), which I stumbled upon from [this page](https://www.pcg-random.org/posts/cpps-random_device.html).

Any thoughts what to do here? Using more than one draw from seed_gen() in the initialization of mt_19937 would definitely help the first issue and is probably worth doing regardless? For second issue, I'm not sure what one might do, if std::random_device could on some systems in fact be extremely low-entropy.

Perhaps it could be possible to allow a user to specify their own multipart form data boundary that they know or can generate that will not conflict with the data? It also avoids semi-costly initialization of mt19937 (which is quite a big generator to initialize to only then grab 96 bits from), although maybe this initialization cost/time is small anyways compared to any network latencies and such. For my own personal use, I've tried such a hack for the client which seems to work. Replacing this:
```c++
inline Result ClientImpl::Post(const char *path, const Headers &headers,
                               const MultipartFormDataItems &items) {
    auto boundary = detail::make_multipart_data_boundary();
    ...
```

With this:
```c++
inline Result ClientImpl::Post(const char *path, const Headers &headers,
                               const MultipartFormDataItems &items) {
    return Post(path, headers, items, detail::make_multipart_data_boundary());
}
inline Result ClientImpl::Post(const char *path, const Headers &headers,
                               const MultipartFormDataItems &items,
                               const std::string& boundary) {
...
```

However I guess maybe this change alone might not be directly release-suitable, since it doesn't perform any validation that `boundary` is composed of only acceptable characters.

**Comment by yhirose** [comment]
@lightvector, thanks for the detailed feedback! I honestly didn't think of the security deeply as we did. The suggestions that you presented above sound all reasonable. Could you try those on your machine and send a pull request? Only thing that I am concerned with is that the changes can be complied with C++11 compilers. Thanks!

**Comment by yhirose** [comment]
@lightvector, thanks for the pull request. I merged it. Can this issue be closed?

**Comment by lightvector** [comment]
Okay. I guess if someone ever wants the server part later they can open an issue and/or make a new pull request, so closing this is fine. Thanks.
