### ISSUE TITLE
error cant pass verifier on windows

### ISSUE THREAD

**Issue by hotbroker** [yhirose/cpp-httplib#697]
**here is the stack when issue occurs**

00 ntdll!NtQueryObject
01 KERNELBASE!GetHandleInformation
02 WS2_32!DSOCKET::FindIFSSocket
03 WS2_32!send
04 mymodule!sock_write
05 mymodule!bwrite_conv
06 mymodule!bio_write_intern
07 mymodule!BIO_write
08 mymodule!ssl3_write_pending
09 mymodule!do_ssl3_write
0a mymodule!ssl3_dispatch_alert
0b mymodule!ssl3_send_alert
0c mymodule!ssl3_shutdown
0d mymodule!SSL_shutdown
0e mymodule!httplib::detail::ssl_delete
0f mymodule!httplib::SSLClient::close_socket
10 mymodule!httplib::ClientImpl::stop_core
11 mymodule!httplib::ClientImpl::process_request
12 mymodule!httplib::ClientImpl::handle_request
13 mymodule!<lambda_66ee1219a816680a9178e5bd970ecab4>::operator()
14 mymodule!std::invoke<<lambda_66ee1219a816680a9178e5bd970ecab4> &,httplib::Stream &>
15 mymodule!std::_Invoker_ret<bool,0>::_Call<<lambda_66ee1219a816680a9178e5bd970ecab4> &,httplib::Stream &>
16 mymodule!std::_Func_impl_no_alloc<<lambda_66ee1219a816680a9178e5bd970ecab4>,bool,httplib::Stream &>::_Do_call
17 mymodule!std::_Func_class<bool,httplib::Stream &>::operator()
18 mymodule!httplib::detail::process_client_socket_ssl<std::function<bool __cdecl(httplib::Stream &)> >
19 mymodule!httplib::SSLClient::process_socket
1a mymodule!httplib::ClientImpl::send
1b mymodule!httplib::ClientImpl::send_with_content_provider
1c mymodule!httplib::ClientImpl::Post
1d mymodule!httplib::ClientImpl::Post

I check the out,it seems like the socket was closed but the it was used again when delete ssl resource

`    inline void SSLClient::close_socket(Socket& socket, bool process_socket_ret) {
        detail::close_socket(socket.sock);
        socket_.sock = INVALID_SOCKET;
        if (socket.ssl) {
            detail::ssl_delete(ctx_mutex_, socket.ssl, process_socket_ret);
            socket_.ssl = nullptr;
        }
    }
`

**Comment by yhirose** [comment]
@hotbroker, thanks for the feedback, but it's too little information to reproduce the problem.

**Comment by hotbroker** [comment]
> @hotbroker, thanks for the feedback, but it's too little information to reproduce the problem.

1、setup “[appverfier](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/application-verifier)"

2、run a demo that invoke  httplib::Client::Post in Windbg.exe

3、then a exception may be caught

so far ,I try to fix this bug with following code(if this is a ssl socket, call ssl_delete before close_socket :

![image](https://user-images.githubusercontent.com/50006539/95893846-d2fff500-0dba-11eb-8729-5cd284c4bd3a.png)

**Comment by yhirose** [comment]
@hotbroker, could you try the latest httplib.h? Thanks!
