### ISSUE TITLE
sometimes "read time out" does't work well on windows??

### ISSUE THREAD

**Issue by hotbroker** [yhirose/cpp-httplib#698]
firstly i have to clearify this problem does not appear easily..
snippet code just like below:

		auto res1 = httplib::Client(ep.data());
		//res1.set_read_timeout(3);//
		auto res = res1.Get(path.data());

set_read_timeout just like it doest work,

here is the stack when the thread is stuck
![image](https://user-images.githubusercontent.com/50006539/95896457-d2695d80-0dbe-11eb-85d5-4c259bda1d32.png)

and so far ,to solve this problem, i cant come up with any better solution,so i have put this in a thread,which looks so dumb

**Comment by yhirose** [comment]
@hotbroker, thanks for the feedback. But the above information is not enough to investigate.

The following read timeout unit test is working on Windows on GitHub Actions workflow. (https://github.com/yhirose/cpp-httplib/runs/1239490280?check_suite_focus=true)

https://github.com/yhirose/cpp-httplib/blob/fffbf1a669b23cc192463ca1bb1d73b94d11cccd/test/test.cc#L2956-L2992

Could you first try to run the test to see what will happen?

```bash
cd test && make test && ./test --gtest_filter="*ReadTimeout*"
```

Thanks!

**Comment by hotbroker** [comment]
> @hotbroker, thanks for the feedback. But the above information is not enough to investigate.
> 
> The following read timeout unit test is working on Windows on GitHub Actions workflow. (https://github.com/yhirose/cpp-httplib/runs/1239490280?check_suite_focus=true)
> 
> https://github.com/yhirose/cpp-httplib/blob/fffbf1a669b23cc192463ca1bb1d73b94d11cccd/test/test.cc#L2956-L2992
> 
> Could you first try to run the test on your Windows machine to see what will happen?
> 
> ```shell
> cd test && make test && ./test --gtest_filter="*ReadTimeout*"
> ```
> 
> Thanks!

ok,i will try this later

**Comment by yhirose** [comment]
@hotbroker, did you try it, yet?

**Comment by hotbroker** [comment]
> @hotbroker, did you try it, yet?

F:\opensrc\cpp-httplib\test\Debug>test.exe --gtest_filter="*ReadTimeout*"
Running main() from gtest_main.cc
Note: Google Test filter = *ReadTimeout*
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from KeepAliveTest
[ RUN      ] KeepAliveTest.ReadTimeout
[       OK ] KeepAliveTest.ReadTimeout (7070 ms)
[ RUN      ] KeepAliveTest.ReadTimeoutSSL
F:\opensrc\cpp-httplib\test\test.cc(3031): error: Value of: svr.is_valid()
  Actual: false
Expected: true
[  FAILED  ] KeepAliveTest.ReadTimeoutSSL (4 ms)
[----------] 2 tests from KeepAliveTest (7079 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (7084 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] KeepAliveTest.ReadTimeoutSSL

 1 FAILED TEST

mean anything ?

**Comment by hotbroker** [comment]
plus ,when i encounter this is accessing a https url

**Comment by hotbroker** [comment]
ps: after making a self-signed cert ,test UT works
but as we can see,the timeout does no any work!!
![image](https://user-images.githubusercontent.com/50006539/97004379-962cbe80-156f-11eb-827f-98c6a10ce55d.png)

**Comment by hotbroker** [comment]
@yhirose

**Comment by yhirose** [comment]
@hotbroker, great! I'll try to reproduce it on my machine.

**Comment by yhirose** [comment]
@hotbroker, could you test with the latest httplib.h? Thanks!

**Comment by hotbroker** [comment]
> @hotbroker, could you test with the latest httplib.h? Thanks!

great, TEST PASSED!

**Comment by hotbroker** [comment]
@hotbroker
