### ISSUE TITLE
Null exception

### ISSUE THREAD

**Issue by apinprastya** [yhirose/cpp-httplib#700]
This took me many hours to figure it out, maybe I am wrong or something off on my side. So this happen when I post a multipart form data and 1 of the field is a file field. And that file is bigger then the buffer size ( > 4096 ).

The problem is from here : 

`return multipart_form_data_parser.parse(buf, n, std::move(multipart_receiver),
                                              std::move(mulitpart_header));`

If the multipart content is bigger then the 4096 which makes those function called multiple times, for the first call is fine because the `multipart_reciever` is still exist, but for the second and so on it become empty (null, not accessible anymore).

To fix it I remove the `std::move` and change the parse parameter from `T content_callback` to` const T &content_callback`. I dont know if it a solid fixed, you should be better on this fix.

I am using VS Community 2017 for the compiler btw, I didnt check with gcc or clang.

**Comment by yhirose** [comment]
@apinprastya, thanks for the report! Could you send a pull request including your fix? Thanks!

**Comment by yhirose** [comment]
@agasparovic, it seems like the recent change to use move semantics causes this bug. I guess some of them need to be reverted. Could you also take a look at it?
https://github.com/yhirose/cpp-httplib/commit/fffbf1a669b23cc192463ca1bb1d73b94d11cccd#diff-2324f73f4a4958b756eb44d0607268befc5de62db01164ccd73e154da808d8f3R321

**Comment by PixlRainbow** [comment]
might need to add a multipart test for larger files

**Comment by yhirose** [comment]
@PixlRainbow, I agree. Wee need a unit test to catch the situation. I'll try to reproduce the problem on my machine first.

@apinprastya, before making a pull request, could you try with v0.7.9? (https://github.com/yhirose/cpp-httplib/tree/v0.7.9) I would like to confirm that the version is ok. Thank you for your extra help!

**Comment by apinprastya** [comment]
@yhirose, it works on v0.7.9.
