### ISSUE TITLE
How to send data with a GET request.

### ISSUE THREAD

**Issue by lukarolak** [yhirose/cpp-httplib#704]
Hello,

I would like to create a get request with data field in it.
https://developer.paypal.com/docs/api/get-an-access-token-curl/
`curl -v https://api.sandbox.paypal.com/v1/oauth2/token \`
  ` -H "Accept: application/json" \`
   `-H "Accept-Language: en_US" \`
  ` -u "client_id:secret" \`
   `-d "grant_type=client_credentials"`

I find it hard to figure out how to send the **-d** argument in the get request.

Any help would be much appreciated.

**Comment by yhirose** [comment]
@lukarolak, thanks for the question. All the answers that you should know are described in this section. https://github.com/yhirose/cpp-httplib#client-1
Hope it helps!

**Comment by PixlRainbow** [comment]
@lukarolak  note: It likely isn't a GET request that you are performing with curl. When you provide `-d` (content data) as a parameter **it will default to a POST request**. If you still force the request to be GET by using `-X`, it will become non-standard as a GET request with a body.

**Comment by lukarolak** [comment]
@yhirose @PixlRainbow Many thanks for your help, with a bit of tinkering and listening to your advice I got it working.

For the sake of other people with a similar issue, I'll post a summary of the issue and the solution. Note: _I'm completely new to the HTTP requests, so my terminology is probably wrong_

What I needed to do was create a POST request instead of the GET request.

Post request allows sending data with it, httplib calls it body.
```
inline Result Client::Post(const char *path, const std::string &body,
                           const char *content_type)
```

Therefore above curl request
```
curl -v https://api.sandbox.paypal.com/v1/oauth2/token \
-H "Accept: application/json" \
-H "Accept-Language: en_US" \
-u "client_id:secret" \
-d "grant_type=client_credentials"
```
Can be implemented like this:

```
	httplib::Client client("https://api.paypal.com");
	
	const httplib::Headers headers = { {"Accept", "application/json"}, {"Accept-Language","en_US"} };
	client.set_default_headers(headers);
	
	const auto& clientID = "client_id";
	const auto& secretID = "secret";
	client.set_basic_auth(clientID, secretID);

	const auto& repsponse = client.Post("/v1/oauth2/token", "grant_type=client_credentials", "x-www-form-urlencoded");
```

**Comment by yhirose** [comment]
@lukarolak, you can also do like this:

```cpp
httplib::Client client("https://api.paypal.com");

client.set_basic_auth("client_id", "secret");

const auto& repsponse =
    client.Post("/v1/oauth2/token",
                {{"Accept", "application/json"}, {"Accept-Language", "en_US"}},
                {{"grant_type", "client_credentials"}});
```

https://github.com/yhirose/cpp-httplib#post-with-parameters
