### ISSUE TITLE
[oss-fuzz] issue-26453  Invalid value of Range header

### ISSUE THREAD

**Issue by omjego** [yhirose/cpp-httplib#705]
Hey @yhirose , this is reagarding the issue [26453](https://oss-fuzz.com/testcase-detail/5162724830740480),  reported by oss-fuzz.   

The program crashes when given a very large value for Range header. This happens during a call to [std::stoll()](https://github.com/yhirose/cpp-httplib/blob/a4a9637738985211321fe4b4a3add7d8ae19a338/httplib.h#L2923)  which throws std::out_of_range exception, which apparently isn't handled.  So this can be tackled wrapping it inside try...catch block, though the part of the code which calls [parse_range_header()](https://github.com/yhirose/cpp-httplib/blob/a4a9637738985211321fe4b4a3add7d8ae19a338/httplib.h#L2909) is [ignoring](https://github.com/yhirose/cpp-httplib/blob/a4a9637738985211321fe4b4a3add7d8ae19a338/httplib.h#L4582) the status returned by the range parsing function. So for such requests should we return HTTP code 416 (Requested range not satisfiable) as specified in the doc [here](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35)  or ignore it and process request anyways?. The code says its a TODO.

**Comment by yhirose** [comment]
@omjego, thank you for drilling down the issue! I agree your suggestion, and try to implement it.

**Comment by yhirose** [comment]
@omjego, I have fixed it. Do we have to tell oss-fuzz that we fixed the issue? If so, could you handle it for me? Thanks!

**Comment by omjego** [comment]
Hey @yhirose  the changes look good to me. 
The oss-fuzz will pick new changes automatically during next build within 24 hrs, (Ref)[https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproduce-using-local-source-checkout]
I'm sending out a PR which has fix for [bug 26439](https://oss-fuzz.com/testcase-detail/5390822188777472), maybe add it to the same release?

**Comment by omjego** [comment]
Fixes oss-fuzz [bug 26439](https://oss-fuzz.com/testcase-detail/5390822188777472)
https://github.com/yhirose/cpp-httplib/pull/711

**Comment by yhirose** [comment]
@omjego, thanks for the pull request, I reviewed and merged it. I'll wait 24 hours, then I'll release the fixes if oss-fuzz doesn't report the issues any more. Thanks for your help!
