### ISSUE TITLE
SSE with long message

### ISSUE THREAD

**Issue by evg82** [yhirose/cpp-httplib#708]
When i send long chunk with type text/event-stream to server, content receiver is called multiple times, first one containts "data: ....". i suppose i need to reasamble message but this function should be handled in lib, and call content receiver with a full message.

**Comment by yhirose** [comment]
@evg82, thanks for the feedback. I don't understand what "When i send long chunk with type text/event-stream to server" means. `text/event-stream` messages should be sent **from server to client** on SSE protocol. Could you explain more about the issue? Thanks!

**Comment by evg82** [comment]
Sorry for my poor description. I will try to explain better:
I have a server and a client with your lib.
Server sends for example a SSE packet with 10k payload, i see it correctly in wireshark, Client receive this correctly but gets multiple calls to content_receiver with up to CPPHTTPLIB_RECV_BUFSIZ bytes. For normal chunked encoding this is ok, but for SSE i need to receive entire message OR get message lenght to reasamble it in my code.

I dont know how to get message length of each chunk.

**Comment by yhirose** [comment]
@evg82, please see my comment in #712, and try my solution in #713.

**Comment by evg82** [comment]
Hi, its work ok to me. Thanks!

**Comment by yhirose** [comment]
@evg82, thanks for checking!
