### ISSUE TITLE
API Documentation for Cpp-httplib...?

### ISSUE THREAD

**Issue by malepurakesh** [yhirose/cpp-httplib#709]
Hi,
   Is there API documentation for cpp-httplib ? Please provide the reference link.
Thanks in advance.

**Comment by yesvivek** [comment]
I don't think there exists a dedicated API document, but samples in README and example folder were good enough for me to start with (I needed a HTTP server) and for more details I referred the code (not complex and quite verbose). But nothing beats a well-written API document.

**Comment by malepurakesh** [comment]
Thank you @yesvivek

**Comment by yhirose** [comment]
@malepurakesh, @yesvivek, thank you for the feedback. Sorry that there isn't  API documentation. I don't simply have time to make and maintain it. In addition to README, `test/test.cc` has a number of working and relative small examples. Hope it helps!
