### ISSUE TITLE
use https Get method will crash.

### ISSUE THREAD

**Issue by luwei08** [yhirose/cpp-httplib#710]
Https Get method crash. Such as: httplib::client cli(“https://****” ); cli.Get(“/*”);   But http::Get is ok.

**Comment by yhirose** [comment]
@luwei08, thanks for the report, but there is no `http:Get` API in httplib.h. Are you using the latest httplib.h?

**Comment by luwei08** [comment]
I point to Httplib::client::Get()😍
I am wrong. I forgot link openssl lib.
