### ISSUE TITLE
Issues from oss-fuzz

### ISSUE THREAD

**Issue by yhirose** [yhirose/cpp-httplib#718]
@omjego, could you take a look at the following report for me? (I tried to see the 'Detailed Report: https://oss-fuzz.com/testcase?key=6234711166550016', but it seems I don't have access right to see it...)

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26598

Thanks a lot!

**Comment by yhirose** [comment]
@omjego, we got another one. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26632. Thanks for your help!

**Comment by omjego** [comment]
@yhirose  Thank you for creating the issue, I'll take look at them. 
Although I was wondering why can't you access the oss-fuzz dashboard, are you using the email id specified [here](https://github.com/google/oss-fuzz/blob/ee423bf3d6195b38fcac59a3b68336bab6dc7001/projects/cpp-httplib/project.yaml#L3) ?

**Comment by yhirose** [comment]
@yhirose, yes. I can of course read emails from oss-fuzz, but when I click the link to the detailed page, nothing happens. So I don't get any practical information for debugging.

**Comment by yhirose** [comment]
@omjego, I now feed it's a bit too much for me to manage the results from oss-fuzz even though the server is great. If you break down results from oss-fuzz and explain the issues easier to me, it will save lots of time and I can focus on fixing the bugs. Thanks for your consideration!

**Comment by yhirose** [comment]
Fixed remaining problems at 041122908ccced5982b48ce209e5a0e1e47a1f84.
