### ISSUE TITLE
error C2888: “bool MultipartFormDataParser::parse(const char *,::size_t,const T &,const U &)”

### ISSUE THREAD

**Issue by xuhongmeng** [yhirose/cpp-httplib#719]
vs2017:
compile  error: error C2888: “bool MultipartFormDataParser::parse(const char *,::size_t,const T &,const U &)”: 不能在命名空间“detail”内定义符号。
and change to 
//template <typename T, typename U>
//bool parse(const char *buf, size_t n, const T &content_callback,
//	const U& header_callback) {
bool parse(const char *buf, size_t n, const ContentReceiver &content_callback,
	const MultipartContentHeader& header_callback) {
cpmpile ok！
I found the conflict between template function parse and parse_range_header try ...  catch....

**Comment by jiagushuai** [comment]
我也遇到了这个问题

**Comment by yhirose** [comment]
@xuhongmeng, I don't have any build problem with my Visual Studio 2017. Here is the version info.
![image](https://user-images.githubusercontent.com/357397/97233618-a0d89500-17b5-11eb-901a-816160af455c.png)

**Comment by pqdxiao** [comment]
I also encountered this problem, but after I divided it into. h and. cc, there was no such problem.
