### ISSUE TITLE
Get full URL from Request?

### ISSUE THREAD

**Issue by crtxcr** [yhirose/cpp-httplib#72]
First of all, great little library!

Is it possible to get the full URL as sent by the client from the Request struct? I know I can get the path and params, but sometimes it's useful to get the full URL. 
So, if the browser requests: http://127.0.0.1:1234/app?var1=value1&var2=value2
With **Request::path** I can get e . g. /app. With **Request::params** I can access the variables, but seems there is no way to access the full URL (besides reconstructing it yourself)?

I think something like Request::url which would return e. g. http://127.0.0.1:1234/app?var1=value1&var2=value2 or at least _app?var1=value1&var2=value2_ would be quite useful.

**Comment by yhirose** [comment]
@crtxcr, thanks for the feedback. I added 'target' property which represent 'request-target' described [here](https://tools.ietf.org/html/rfc7230#section-3.1.1) in RFC 7230.
