### ISSUE TITLE
Add move semantic for httplib::Result::res_::body

### ISSUE THREAD

**Issue by Bulb4** [yhirose/cpp-httplib#723]
Currently we need to copy body's value, because all `httplib::Result` getters are const. There is also no way to get `httplib::Result::_res` ownership because it is private and `unique_ptr`.
It would be nice to by able to use `std::move` for body, if we want to store it somewhere, and use after result destruction.

**Comment by yhirose** [comment]
@sum01, do you have any thought? I don't mind making the getters back to non-const.

**Comment by sum01** [comment]
I still think it makes sense to be const-qualified since the methods don't change anything, which is why I originally made that issue.

Does `const_cast` not solve your issue @Bulb4 ?
Either that, or maybe add a method to return the `shared_ptr<Response> res_` like `get_res_ptr` or something.

**Comment by yhirose** [comment]
@sum01, after I carefully see the current code, those methods shouldn't be changed as you mentioned. Sorry for my hasty comment.

I think your suggestion "or alternatively add duplicate getters that are all non-const, like" sounds good.
