### ISSUE TITLE
that's a good lib for http client and server using C++. But I have something want to know clear, haha.

### ISSUE THREAD

**Issue by okman334** [yhirose/cpp-httplib#726]
In MacOs, httplib::SSLClient, no need, set_ca_cert_path, also can work. But the same code in linux(ubuntu 16.04) isn't work.
       The code like that: 
         {
             httplib::Client cli("https://api.ky5215.com");
            cli.set_ca_cert_path("/etc/ssl/certs/ca-certificates.crt");
            cli.enable_server_certificate_verification(true);
         }
        if don't set_ca_cert_path, In macOs also ok.  But in linux will say: self signed certificate in certificate chain.

**Comment by yhirose** [comment]
@okman334, that's probably because the following line doesn't work on your machine. This is not a cpp-httplib problem, but the SSL configuration problem on your linux.
https://github.com/yhirose/cpp-httplib/blob/ff5677ad197947177c158fe857caff4f0e242045/httplib.h#L6045
Hope it helps!

**Comment by district10** [comment]
You can configure environment variable: `SSL_CERT_FILE`, `SSL_CERT_DIR`, instead of explicitly calling:

```
cli.set_ca_cert_path(your_cert_path, your_cert_dir);
```

See document: https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_default_verify_paths.html.
