### ISSUE TITLE
Linking libssl and libcrypto

### ISSUE THREAD

**Issue by mrzephros** [yhirose/cpp-httplib#735]
Hi, how do I link this two libraries to use the SSLClient support?

**Comment by PixlRainbow** [comment]
the exact procedure varies depending on the compiler you choose but also depends on the IDE you are using.  
For example, if using gcc/g++:
```sh
g++ main.cpp -o myprogram.exe -lssl -lcrypto
```

**Comment by yhirose** [comment]
Hope @PixlRainbow's comment helps.
