### ISSUE TITLE
Forward Declaration Header

### ISSUE THREAD

**Issue by 5cript** [yhirose/cpp-httplib#736]
(Proposal)

A header containing only forward declarations could be beneficial.
I would rather move the header to my source files without wrapping the client in a class, the implementation of which I can hide behind a pointer. I'd also rather not make my own forward declarations in "your" namespace.

**Comment by yhirose** [comment]
@5cript, thanks for the feedback, but I don't fully understand what you are proposing. Could you explain it more?

**Comment by PixlRainbow** [comment]
> A header containing only forward declarations could be beneficial.

You can generate such a header by using the `HTTPLIB_COMPILE` option in our cmake config. Alternatively you can run the split.py script directly.  
Note however that by doing so, cpp-httplib will no longer be a single-header library.

**Comment by 5cript** [comment]
I see, this fullfills my request.
