### ISSUE TITLE
Setting content in error_handler does not affect Content-Length

### ISSUE THREAD

**Issue by aldoshkind** [yhirose/cpp-httplib#738]
Setting content in error_handler does not affect Content-Length
```cpp
#include <httplib.h>

int main(void)
{
  using namespace httplib;

  Server svr;
  
	svr.set_error_handler([](const auto& req, auto& res) {
		auto fmt = "<p>Error Status: <span style='color:red;'>%d</span></p>";
		char buf[256];
		snprintf(buf, sizeof(buf), fmt, res.status);
		res.status = 200;
		res.set_content(std::string("abcdefghijklmnopqrstuvwxyz"), "text/html");      // <= Content-Length still 13
	});

  svr.Get("/hi", [](const Request& req, Response& res) {
    res.set_content("Hello World!\n", "text/plain");
    res.status = 524;
  });

  svr.listen("localhost", 1234);
}
```

**Comment by aldoshkind** [comment]
Particularly, if error_handler sets content of size less than Content-Length, client will wait for data and will close connection on timeout. For example curl says
```
* transfer closed with 11 bytes remaining to read
* stopped the pause stream!
* Closing connection 0
curl: (18) transfer closed with 11 bytes remaining to read
```

If error_handler sets content of size greater than Content-Length, client will detect excessive data. For example curl says 
```
* Excess found in a non pipelined read: excess = 13, size = 13, maxdownload = 13, bytecount = 0
```

**Comment by yhirose** [comment]
@aldoshkind, thanks for the report. It seems that this is same as #737. If so, could you move the above comments to #737?

**Comment by yhirose** [comment]
@aldoshkind, thanks for the report. Could you explain this issue more clearly? (Could you make the example code simpler, and give me the exact curl comment you issued?) Thanks!

**Comment by aldoshkind** [comment]
Oh, yes, of course :)
I've updated code in the first message. Curl line is `curl -v localhost:1234/hi`.
The problem is that if we `set_content` in url handler and than in error handler, Content-Length not getting updated at second call.
As I understand this happend due to error handler is called after Content-Length calculation: first we do `apply_ranges` at line 4029 (which sets Content-Length), and then we call `error_handler_` at line 4041.

**Comment by yhirose** [comment]
@aldoshkind, thanks! I'll take a look at it when I have time.

**Comment by yhirose** [comment]
@aldoshkind, could you try with the latest httplib.h? Thanks.

**Comment by aldoshkind** [comment]
@yhirose It works, thank you very much for rapid response!

**Comment by yhirose** [comment]
@aldoshkind, thanks for checking!
