### ISSUE TITLE
Getting parameters from the url.

### ISSUE THREAD

**Issue by dominique120** [yhirose/cpp-httplib#743]
Hi! I'm moving a small microservice application to your library and so far its been going well! This is a great library!

I have a little question though. Is it possible to get parameters from the url without having to use an identifier for them?

In my current solution I have my endpoint like this: ```/orders/{id}```. ```{id}``` can then be an id sent by the client that I can access. I access it like this: ```req.params [ "id" ]```, this will return whatever ```{id}``` is. The clients request would be something like ```/orders/uuid_of_order```.

Is such a thing possible or do I have to set an identifier to use ```get_param_value```?

Thanks!

**Comment by PixlRainbow** [comment]
`get_param_value` serves a different function. It is used for retrieving URL-encoded query parameters, when a client sends a request URL like: ![query paramters in an URL](http://images.mxpnl.com/blog/2014-10-17%2000:30:48.190268-jnurl1.png)

```cpp
svr.Get("/page.html", [&](const Request& req, Response& res) {
  if (req.has_param("parameter1")) {
    auto value1 = req.get_param_value("parameter1");
  }
});
```

If you want to retrieve identifier-set parameters, **use regex capture groups syntax** when specifying endpoint path.
```cpp
svr.Get(R"(/orders/(\d+))", [&](const Request& req, Response& res) {
  auto id = req.matches[1]; // note: this will be a string.
});
```

**Comment by yhirose** [comment]
@dominique120, in addition to the @PixlRainbow's comment, please see [here](https://github.com/yhirose/cpp-httplib#server-1) in README.

**Comment by dominique120** [comment]
Thanks @PixlRainbow for the explanation!
