### ISSUE TITLE
Make the lib independent from python

### ISSUE THREAD

**Issue by joda01** [yhirose/cpp-httplib#749]
To compile python is needed. Would it be possible to make it independent from python?

I have a suggestion and rewrote the python script in go and compiling.

**Comment by joda01** [comment]
[CMakeLists.txt](https://github.com/yhirose/cpp-httplib/files/5528917/CMakeLists.txt)

**Comment by joda01** [comment]
`package main

import (
	"io/ioutil"
	"os"
	"strings"
)

func main() {

	border := "// ----------------------------------------------------------------------------"
	content, _ := ioutil.ReadFile("httplib.h")
	lines := strings.Split(string(content), "\n")
	inImplementation := false

	os.Create("out")

	fh, _ := os.Create("out/httplib.h")
	fc, _ := os.Create("out/httplib.cc")

	fc.WriteString("#include \"httplib.h\"\n")
	fc.WriteString("namespace httplib {\n")

	for _, line := range lines {
		isBorderLine := strings.Contains(line, border)
		if isBorderLine {
			if true == inImplementation {
				inImplementation = false
			} else {
				inImplementation = true
			}
		} else {
			if inImplementation {
				toWrite := strings.ReplaceAll(line, "inline ", "")
				fc.WriteString(toWrite)
			} else {
				fh.WriteString(line)
			}
		}
	}

	fc.WriteString("} // namespace httplib\n")

}
`

**Comment by yhirose** [comment]
@joda01, thanks for the suggestion, but I am not interested in switching to Go since it requires a user to install Go environment and compile the Go code to make a binary on the user's machine architecture. I think Python is more popular and it doesn't require compile process.
