### ISSUE TITLE
get params request from client

### ISSUE THREAD

**Issue by nampqaime** [yhirose/cpp-httplib#751]
Hello,

How can I get KEY and VALUE of params dictionary from POST process of client?

About Client:
    httplib::Params params{
         { "name", "john" },
         { "note", "coder" }
    };

    auto res = cli.Post("/post", params);

About server:
    ???????
    I had tried with:      req.has_param("name")     but server got nothing.

Thanks !

**Comment by yhirose** [comment]
@nampqaime, hope the following unit test helps.
https://github.com/yhirose/cpp-httplib/blob/9c7d841b37b69cde4ffb7c6d5c1aae6d5d6e1d97/test/test.cc#L1022-L1030
https://github.com/yhirose/cpp-httplib/blob/9c7d841b37b69cde4ffb7c6d5c1aae6d5d6e1d97/test/test.cc#L1494-L1512
