### ISSUE TITLE
Stack smashing due to misuse of select (*** stack smashing detected ***: <unknown> terminated)

### ISSUE THREAD

**Issue by aldoshkind** [yhirose/cpp-httplib#754]
Hi @yhirose! 
At our project we have a problem: application crashes with message "*** stack smashing detected ***: <unknown> terminated" after some time correctly working.
OS is Ubuntu Linux.
Backtrace shows that problem is in the function `select_read`. After some investigation I found that `select` is misused. According to docs `glibc` imposes constraints on maximum value of fd to be monitored (https://man7.org/linux/man-pages/man2/select.2.html) due to `fd_set` has static array inside. `FD_SET` does not check boundaries and writes outside of array, which leads to stack corruption.

Using `CPPHTTPLIB_USE_POLL` fixes the problem

Here is code which reproduces the problem:
```cpp

// concept:
// first we exhaust 1090 fds by opening files
// then we process requests whose connection fds will be >1024 (which leads to stack damaging)
// I use 1090 beacause stack damaging is detected only after fd 1087 on my machine

#include <httplib.h>

#include <sys/time.h>
#include <sys/resource.h>

int main(void)
{
	using namespace httplib;
	
	// increase maximum fds available to expose the problem
	// on problematic machine RLIMIT_NOFILE is 1048576
	struct rlimit rl = {2048, 2048};
	setrlimit(RLIMIT_NOFILE, &rl);

	// exhaust fds up to 1090
	for(int i = 0 ; i < 1090 ; i += 1)
	{
		open("/dev/null", O_RDONLY);
	}
	
	
	// work as usual
	Server svr;
	
	svr.Get("/hi", [](const Request& req, Response& res)
	{
		res.set_content("Hello World!\n", "text/plain");
		res.status = 524;
	});

	
	svr.listen("localhost", 1234);
}

```

Request: `curl -v localhost:1234/hi`.

Also there are other issues with same symptoms, I think it is the same problem:
https://github.com/yhirose/cpp-httplib/issues/655
https://github.com/yhirose/cpp-httplib/issues/654

**Comment by yhirose** [comment]
@aldoshkind, thanks for the great finding! I checked how other products handle the FD_SETSIZE limitation.

Here is [the solution in MySQL](https://github.com/mysql/mysql-server/blob/4869291f7ee258e136ef03f5a50135fe7329ffb9/storage/ndb/include/portlib/ndb_socket_poller.h#L198-L204) for non Windows operating systems:

![image](https://user-images.githubusercontent.com/357397/99159707-1b0d8280-26ad-11eb-96b5-32e77279de16.png)

I don't think it's a good behavior to call `abort()` to terminate the server as this code does. I am thinking to return a 429 response (Too Many Requests). As you mentioned, the only and real solution on Linux and macOS should to use `poll`. There is no solution for this as long as `select` is used unfortunately.

I'll try to avoid at least the crash that you found, also encourage users to use `poll` if they expect a large number of request that might exceed FD_SETSIZE on README.

By the way, when I was reading source code in MySQL and libzmq, I found that they are applying special treatments to increase FD_SETSIZE for Winsock2. Their approaches are very different from each other though, they both support much larger amount of file/socket descriptors. But these cannot be applied to non Windows environments...

Thank you again for your valuable feedback!

**Comment by yhirose** [comment]
@aldoshkind, could you try #755 to see if it fixes the problem? It will send 429 response when the socket descriptor exceeds FD_SETSIZE. Thanks!

**Comment by aldoshkind** [comment]
Thank you for your rapid response again! :)
1. I am not deeply familiar with `select`/`poll` APIs. Please clarify: is it necessary to support `select`? Maybe there is an option to use `poll` only? As I see in discussion (https://stackoverflow.com/questions/970979/what-are-the-differences-between-poll-and-select) `poll` is considered more convinient.
Is there opportunity to use `poll` by default maybe?

2. If `select` is required, maybe we can do something like this?
```cpp
if(fd >= FD_SETSIZE)
{
    poll(fd);
}
else
{
    select(fd);
}
```

3. I am not agree with using status 429. According to RFC (https://tools.ietf.org/html/rfc7231#section-6.5): `the 4xx (Client Error) class of status code indicates that the client seems to have erred`. Particularly 429: `The 429 status code indicates that the user has sent too many requests in a given amount of time ("rate limiting")` (https://tools.ietf.org/html/rfc6585#section-4) which is not the case obviously. It seems 5xx codes are more suitable here.
But: I am not happy with option to get sudden implicit server error because of implementation's restrictions. Please consider (1) and (2) above :)

PS. If `select` is unavoidable you may put warning like this into the code to keep user informed:
```cpp
// if user uses select
#ifndef CPPHTTPLIB_USE_POLL
// if user did not explicitly stated he understand what he is doing
#ifndef I_USE_SELECT_AND_UNDERSTAND_RISKS
// warn him
#warning Using select is risky and may lead to denial of service. Please refer to docs!
#endif
#endif

```

**Comment by yhirose** [comment]
@aldoshkind, thanks for the reply!

> 1. I am not deeply familiar with select/poll APIs. Please clarify: is it necessary to support select? Maybe there is an option to use poll only? As I see in discussion (https://stackoverflow.com/questions/970979/what-are-the-differences-between-poll-and-select) poll is considered more convinient.
Is there opportunity to use poll by default maybe?

I intentionally take `select` as default. Please see 1f86e41d971a2de2f22bbfc7124b31fe5e728e75 and see the last two comments in #215.

> 2. If select is required, maybe we can do something like this?

No. It's a compile time decision and I don't want to make any confusion to use different things at the same time by mixing them together.

> 3. I am not agree with using status 429. According to RFC (https://tools.ietf.org/html/rfc7231#section-6.5): the 4xx (Client Error) class of status code indicates that the client seems to have erred. Particularly 429: The 429 status code indicates that the user has sent too many requests in a given amount of time ("rate limiting") (https://tools.ietf.org/html/rfc6585#section-4) which is not the case obviously. It seems 5xx codes are more suitable here.
But: I am not happy with option to get sudden implicit server error because of implementation's restrictions.

It makes sense. I'll consider a different status code.

Sorry for my reply that sounds a bit negative. Since a number of users are using httplib.h in different circumstances, there are situations that `poll` may not be suitable or even not runnable.  It's a totally user's responsibility to select the best one in their particular use case.

I'll find better status code and update the pull request some time this week. Thanks!

**Comment by aldoshkind** [comment]
OK, you're the boss :)
Thanks for reply and explanation!
