### ISSUE TITLE
Send data from PC to another PC

### ISSUE THREAD

**Issue by nampqaime** [yhirose/cpp-httplib#756]
Hello

I would like to send some information through HTTPS from client (PC_1) to server (PC_2) with 2 cpp file but server got nothing:

Client:
```
#define CPPHTTPLIB_OPENSSL_SUPPORT
#include "./httplib.h"
#include <iostream>
#include <string>

using namespace std;
using namespace httplib;

int main()
{
  SSLClient cli;
  cli.set_interface("https://<**ip server**>:8080");
  cli.set_ca_cert_path("./ca-bundle.crt");
  cli.enable_server_certificate_verification(true);

  string my_name = "Nam";

  httplib::Params params{
  	{ "name", my_name },
  	{ "note", "coder" }
  }; 
  
  auto res = cli.Post("/person", params); 
}
```

Server:
```
#define CPPHTTPLIB_OPENSSL_SUPPORT
#include "./httplib.h"
#include <iostream>
#include <string>

using namespace httplib;

int main(void)
{

	const std::string server_cert_file = "./**cert.pem**"; 
	const std::string server_private_key_file = "./**key.pem**"; 
	SSLServer svr(server_cert_file.c_str(), server_private_key_file.c_str());

	svr.set_read_timeout(6000, 0); 

	if (!svr.is_valid()) { 
		assert(0 == 1); 
		return -1; 
	} 

	svr.Get("/hi", [](const Request& req, Response& res) {
            res.set_content("Hello World !", "text/plain");
        });

        svr.Post("/person", [&](const Request &req, Response &res) { 
                if (req.has_param("name") && req.has_param("note")) { 
			std::cout << "--------> " << req.get_param_value("name") << std::endl;
			std::cout << "--------> " << req.get_param_value("note") << std::endl;
                } else{ 
                        res.status = 400; 
                } 
        }); 

        svr.Get("/stop", [&](const Request& req, Response& res) {
               svr.stop();
        });
	
	//svr.listen("https://localhost", 1234);
	**int port = svr.bind_to_any_port("0.0.0.0");
	svr.listen_after_bind();**
}
```
Please show me some detail for:
- "cert.pem" and "key.pem" should be generated from client pc or server pc?
- In svr.listen: what should I set param to get data from client?

I look forward to your response.
Many thanks !

**Comment by PixlRainbow** [comment]
the certificate (public key) and key (private key) can be generated anywhere, using OpenSSL or any other software or online service, as long as it is compliant with PEM format, and as long as the files are saved on the server's disk drive. Those files are only used by the server.

svr.listen is not for getting data from client. Svr listen will activate the web server and the server will run continuously after that until explicitly stopped with a call to svr.stop or by terminating the process.

You have already set up all that is needed to get data from client in your svr.Post("/person") endpoint and the cli.Post("/person") endpoint.

``` cli.set_interface("https://<**ip server**>:8080");```
You are using `set_interface` incorrectly. `set_interface` is used to configure which network interface (e.g. ethernet, Wi-Fi, 4G, etc) is used to send the request. 
You may have also constructed the client incorrectly. It has not been configured to connect to any server. You need to provide the domain name or IP address of the server directly in the constructor, as well as the port. But you provide it as two separate parameters, cpp-httplib will not parse URL strings placed into the constructor. e.g.
```cpp
SSLClient cli("<**ip server**>", 8080);
```

Note that if you have turned certificate verification on, you will need to make sure your ca-bundle.crt file contains the certificate of the signing authority that created your server's certificate. If the server's certificate is a self-signed certificate, then you can simply make sure that ca-bundle.crt contains the server's certificate.

**Comment by yhirose** [comment]
Hope @PixlRainbow's comment helps.
