### ISSUE TITLE
Not reconnect when Network change.

### ISSUE THREAD

**Issue by furkan-kara** [yhirose/cpp-httplib#758]
Hi,

I can not connect to internet over app where cpp-httplib used in when internet connectivity type change (especially from WAN to Mobile networks). Device is arm based device, device connect to internet but app not connect. After restart app, connection is successful.

Any ideas what might have caused it?

**Comment by yhirose** [comment]
@furkan-kara, thanks for the feedback, but it is out of scope of cpp-httplib, more like a question regarding general TCP/IP connection...

**Comment by PixlRainbow** [comment]
Please provide a more detailed explanation on what you mean @furkan-kara. Do you mean that after constructing a client and sending a request, the next request cannot be sent if the network is changed between the first and second request?

**Comment by furkan-kara** [comment]
Sorry for the missing information. If network is changed, ongoing request does not resume and will fail. The next requests will fail with the "Error Resolving Address" message. After restart app client can connect to server without error.

**Comment by PixlRainbow** [comment]
@yhirose is there a function to tell the client to reset the connection? Or does he have to destroy and re-construct the client object?

**Comment by furkan-kara** [comment]
yes, I tried to reset the connection and reset the client object but the error keep going.

**Comment by yhirose** [comment]
Unfortunately, there is no function to reset the current connection in client at this point. If the Client is working on non keep-alive mode (`set_keep_alive(false`), it creates a separate connection per request. So it might help.

@furkan-kara, does curl has the same problem on your environment?

**Comment by furkan-kara** [comment]
The code I used is not the last version. This problem was solved when I switched to the latest version. Thank you.
