### ISSUE TITLE
Not able to configure the library not to use SO_REUSEPORT in

### ISSUE THREAD

**Issue by milos-pesic-zattoo** [yhirose/cpp-httplib#759]
Some applications specifically want to control and forbid transparent binding multiple sockets to the same address/port and to explicitly fail in that case.
If `SO_REUSEPORT` is defined and available on the platform it will be automatically used. It would be nice to add a configuration flag to alter that behaviour when needed.

**Comment by milos-pesic-zattoo** [comment]
I tried to submit the PR - but for some reason have issue with repo access.
I am attaching a simple patch which might work:

```
--- a/httplib.h
+++ b/httplib.h
@@ -581,7 +581,7 @@ inline void default_socket_options(socket_t sock) {
   setsockopt(sock, SOL_SOCKET, SO_EXCLUSIVEADDRUSE,
              reinterpret_cast<char *>(&yes), sizeof(yes));
 #else
-#ifdef SO_REUSEPORT
+#if defined(SO_REUSEPORT) && !defined(CPPHTTPLIB_NO_SO_REUSEPORT)
   setsockopt(sock, SOL_SOCKET, SO_REUSEPORT, reinterpret_cast<void *>(&yes),
              sizeof(yes));
 #else
```

**Comment by yhirose** [comment]
@milos-pesic-zattoo, thank you for the feedback. Yes, this is the current cpp-httplib behavior.

I don't need the flexibility in my use cases though, you are very much welcome to send the pull request. When you work on that, please make sure that your PR should work on all the platform (Linux/Mac/Windows).

In fact, I was struggling the incompatibilities of `SO_REUSEADDR` and `SO_REUSEPORT` on these platforms when implementing the current behavior of cpp-httplib. So please careful not to breaking existing behavior and make sure that the new feature works on all the platforms.

You can see more information here #179, #250 and #560.

Thanks!

**Comment by milos-pesic-zattoo** [comment]
In fact - I can see that recently a new API has been added: https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L632
I could use that one to set socket options without altering the code.
Sorry - for not checking it well before opening an issue - was looking into a slightly older version which did not have that API.
I will close the issue.
