### ISSUE TITLE
The max number of threads in threadpool

### ISSUE THREAD

**Issue by kevinhwu** [yhirose/cpp-httplib#760]
Hi,

My project needs many threads for long running task，when requests become more and more, server will be blocked，so I set the ThreadPool count to 1024：`m_server.new_task_queue = [] { return new ThreadPool(1024); };`，seems better，I'm wondering if it‘s good practice, any suggestions?

Thank you!

**Comment by yhirose** [comment]
@kevinhwu, yes if you have hundreds of cores and lots of memory on your machine, but no otherwise. If your task is not a CPU-bound but a I/O bound, I recommend you to use libuv based HTTP libraries. Hope it helps!
