### ISSUE TITLE
Issue 27596 in oss-fuzz: cpp-httplib:server_fuzzer: Timeout in server_fuzzer

### ISSUE THREAD

**Issue by yhirose** [yhirose/cpp-httplib#762]
@omjego, another issue came from oss-fuzz.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27596

Could you take a quick look? I tried to reproduce it based on their report, but I can't able to do it... So I need your help again.

I also would like to learn how to read the reports from them, since I am not familiar to the oss-fuzz project. When you have time, could you explain what I should learn? Thanks!

**Comment by yhirose** [comment]
@omjego, any response?

**Comment by omjego** [comment]
Hey @yhirose , sure  let me take a look. 
Here's a doc on reproducing then bug: https://google.github.io/oss-fuzz/advanced-topics/reproducing/

Although the easiest way to do this is to use [standalone testcase](https://github.com/yhirose/cpp-httplib/blob/master/test/fuzzing/standalone_fuzz_target_runner.cpp) runner which I added for testing purposes : 
 1. Download the reproducer testcase. You'll find it in the [report page](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27596).
 2. Build the `server_fuzzer` target in Makefile.fuzz. `make -f Makefile.fuzz server_fuzzer`. (Please modify debug/sanitizer flags if needed, I've tried to keep it as simple as possible)
3. And then run `./server_fuzzer <path to test-case-file>`

The [standalone runner](https://github.com/yhirose/cpp-httplib/blob/master/test/fuzzing/standalone_fuzz_target_runner.cpp) has a main method and it just reads the input from file and [passes](https://github.com/yhirose/cpp-httplib/blob/a5c239c174f394208980100bfb7b90aa4b91dd32/test/fuzzing/server_fuzzer.cc#L86) to  server fuzzer. You can use that main method to trigger the debugger if you are using any IDE like [CLion](https://www.jetbrains.com/clion/)

**Comment by yhirose** [comment]
@omjego, thanks for the detail. I downloaded the testcase file and run `server_fuzzer` with it, but it seems it doesn't reproduce the bug... Am I missing something? Thanks for your help!

```bash
[master] ~/Projects/cpp-httplib/test$ ./server_fuzzer clusterfuzz-testcase-minimized-server_fuzzer-5672874953932800 
Reading 806965 bytes from clusterfuzz-testcase-minimized-server_fuzzer-5672874953932800
Execution successful
Execution finished
```

**Comment by yhirose** [comment]
@omjego, did you find anything about the bug?

**Comment by omjego** [comment]
@yhirose you didn't see anything cause this is a timeout error, I'm trying to debug this one.

**Comment by omjego** [comment]
Hey @yhirose , 
So I looked into this, the input generated by fuzzer is ~1MB in size and major chuck of it is HTTP body data.  The whole body consists of `\r`, `\n` and few `--m` characters/strings [Image](https://imgur.com/98vAB88). While debugging, I found that [this](https://github.com/yhirose/cpp-httplib/blob/47e5af15ea1445627c3b1ca6bba13855c60679ef/httplib.h#L3132-L3173) code was being bottleneck while parsing the body, although I didn't find anything suspicious apart from this. If you think this is expected behaviour of the code we can make autofuzz ignore this.

**Comment by yhirose** [comment]
@omjego, thanks for the information. It measured the performance with `time` comment. It takes about 11 seconds, and this slowness may cause the 60 secs timeout on the oss-fuzz server.

```
[master] ~/Projects/cpp-httplib/test$ time ./server_fuzzer clusterfuzz-testcase-minimized-server_fuzzer-5672874953932800
Reading 806965 bytes from clusterfuzz-testcase-minimized-server_fuzzer-5672874953932800
Execution successful
Execution finished

real	0m10.778s
user	0m10.111s
sys	0m0.027s
```

I'll take a look at the code if I can improve the parsing performance before ignoring this test case. I'll get back to you after that. Thank you for your fine assistence!

**Comment by yhirose** [comment]
@omjego, I have fixed this performance issue. It should be ok now on the oss-fuzz server. They will pick up this change automatically, right?

**Comment by omjego** [comment]
Nice!! Yes the changes will be picked during next run (within 24 hours)
