### ISSUE TITLE
Force TLSv1.2 version for a SSL Client

### ISSUE THREAD

**Issue by luismigb** [yhirose/cpp-httplib#764]
Hello,

I would like to know if it is possible to force the TLS version to use when creating a SSL client with the library. I am having strange behaviors, because sometimes a SSL client is using TLSv1.2 againts a web server which only supports TLSv1.2 and other times it use TLSv1 and the communication it is never established. Also, when this happens, the connection never gets timeout.

**Comment by yhirose** [comment]
@luismigb , could you test with curl on your machine if curl has the same problem? If it doesn't have the problem, I'll take a look at their source code to see how OpenSLL is used. Thanks!

**Comment by yhirose** [comment]
@luismigb, any response?

**Comment by yhirose** [comment]
I'll close it for now.

**Comment by luismigb** [comment]
@yhirose, sorry for not answering you, I finally assumed that the reason could be related with the coverage in the zone where the tests were performed, having also coverage problems in the mobile phone. I tested with the newest OpenSSL and version of your library and the behavior is the same. I was not able to test with curl (not available in the device)

**Comment by yhirose** [comment]
@luismigb, thanks for the update. I did some research and found the following pages:
https://www.openssl.org/docs/man1.1.1/man3/TLSv1_2_method.html
https://wiki.openssl.org/index.php/SSL/TLS_Client

Could you try something in the pages when you have time?
If you find a workable solution, I'll add a method to make the TLS mode configuration.
Thanks for your help!

**Comment by luismigb** [comment]
@yhirose, I have used both TLSv1_2_server_method() and TLSv1_2_client_method() in your library (and them worked as expected between the device as client and a raspberry as server, only TLS v1.2 connections are managed) but when testing outside, the problem persist. I think, for now, that it is not software related issue.

If I have news about this I will advise you.
