### ISSUE TITLE
Is there anyway to get the new url after redirection?

### ISSUE THREAD

**Issue by hwenwur** [yhirose/cpp-httplib#765]
Hello,
 
how can I get the new url after redirection(`3xx`)? 
For example, `http://a.com/` redirect to `http://b.com/`, is it have a variable to store `http://b.com/`?
The `Response` class seems not have any field can do that. 

please forgive my poor English.

**Comment by yhirose** [comment]
@hwenwur, thanks for the feedback. I added `location` member in `Response`. This may not be a URL because the information comes from HTTP Location header. But I think it's enough for you.
