### ISSUE TITLE
Get error message for server problem

### ISSUE THREAD

**Issue by iPherian** [yhirose/cpp-httplib#769]
I've been using this to run a little ssl server, and I'd like a way to get an error message when something goes wrong i.e. when I give a bad cert file:

```
httplib::SSLServer svr("nonexistent_cert.pem", "...");
svr.listen("localhost", 1234);
```

While listen will return false indicated *some* error occured, I can't find a way to get a specific error code/message.

Any way to do this?

**Comment by yhirose** [comment]
@iPherian, could run `cd test; make test` on your machine? It may give you come clues to figure out the problem.

**Comment by iPherian** [comment]
@yhirose It works fine when I give it a cert file that exists, I was just wondering if there was a way to get some kind of specific error code/message when something goes wrong with listen().

**Comment by yhirose** [comment]
@iPherian, sorry that I misunderstood your question. There is no way to get a specific error code/message, but you can check if the SSLServer is initialized successfully with `SSLServer::is_valid()` method. Is it good enough?

**Comment by iPherian** [comment]
@yhirose I can live with that.
