### ISSUE TITLE
how to get a pic?

### ISSUE THREAD

**Issue by HLhuanglang** [yhirose/cpp-httplib#772]
i've seen the source code, Client's constructor can't use a complete URL as parameterst and the  Get() must have a 'path'.
is there any easy way to use ? mabye like this:（I am a newbie in programming T_T）
```
httplib::Client cli("http://ip:prot/xxx/xxxx.jpeg")
cli.Get();
auto pic = cli->body;
```
beacuse i want to make a get request to acquirea a pic，if it doesn't work，how should i do？should i have to write like this?
```
httplib::Client cli("http://ip:prot");
cli.Get("/xxx/xxxx.jpeg");
auto pic = cli->body;
```

**Comment by yhirose** [comment]
@HLhuanglang, yes, the latter one is correct. Hope your project goes well!
