### ISSUE TITLE
question: VCPKG version out of date?

### ISSUE THREAD

**Issue by roddypratt** [yhirose/cpp-httplib#773]
When I install this package with vcpkg, I'm getting an old 7.0 version. I guess this is down to you rather than the vcpkg team?
![image](https://user-images.githubusercontent.com/1199520/100204112-5f91ed00-2efb-11eb-9412-15d92416359b.png)

**Comment by roddypratt** [comment]
I've opened an issue on vcpkg, so this can probably be closed here. https://github.com/microsoft/vcpkg/issues/14764

**Comment by yhirose** [comment]
@roddypratt, thanks for the feedback. I don't use any C++ package manager like VCPKG and Conan, and I am not planning to support them myself. I think someone probably registered this library to vcpkg repo for vcpkg users (also conan) a while ago.
Thanks for sending the issue to vcpkg!
