### ISSUE TITLE
res->body.data() or res->body.c_str() both contain hexadecimal size value in front of content

### ISSUE THREAD

**Issue by fatrolls** [yhirose/cpp-httplib#777]
res->body.data() or res->body.c_str() both contain hexadecimal size value in front of content

I didn't change any of my code it worked fine for months and when I switched from visual studio 2017 to 2019 now all my strings have hexadecimal size in front of them.. I thought it had to do with body being a struct with size indicator in front of it but I couldn't find anything about it in the code? so im confused

any way to disable the hexadecimal size in front of data in 2019 VS? is it a std::string new feature or bug? maybe the way std::string is stored now ?

Maybe it's because i'm using OpenSSL libraries for 2017 MSVC on 2019... some bug happens with OpenSSL because I do use SSL version of cpp-httplib

EDIT: Compiled my own version of OpenSSL 1.1.1i static linked it with my project and still get the hexadecimal size value in front of my data although I check the data is clearly have no hexadecimal value in any browser (Edge / IE / Chrome).

In case it's still OpenSSL.. Here is my github where I compiled the OpenSSL library today for use in MSVC 2019
https://github.com/fatrolls/OpenSSL-MSVC-2019-Precompiled

**Comment by yhirose** [comment]
@fatrolls, thanks for the report. cpp-httplib doesn't do anything special for VS 2019. I

**Comment by yhirose** [comment]
I accidentally hit the 'Close with comment' button, and reopened it again...

**Comment by yhirose** [comment]
@fatrolls, I tested the unit test with the latest Visual Studio 2019 (v16.8.2) with the static version of OpenSSL-Win64 (1.1.1h), and confirmed that all the unit test cases including lots of client request tests passed successfully.

**Comment by yhirose** [comment]
@fatrolls, could you give me more detailed information, so that I could reproduce this problem?

**Comment by fatrolls** [comment]
Tried OpenSSL compiled under 2019 that didn't solve the problem.

Here is my code
![error code](https://i.imgur.com/TmIoNRw.png)

Here is output console
![error console](https://i.imgur.com/Tn1KFgl.png)

browser output
![browser output](https://i.imgur.com/kABGHEx.png)

**Comment by yhirose** [comment]
@fatrolls, thanks for the detail. I honestly don't know what's happing on your machine... But, you may want to check some HTTP hears from the server like Content-Length and Content-Encoding to get more clues.

Here is the code to receive body content in the client where you could trace the data transfer from the server:
https://github.com/yhirose/cpp-httplib/blob/eb240ad2e5d2f7972b4c952ac2cfa2c526d7ac3d/httplib.h#L5426-L5434

You could also try with a HTTP request instead of HTTPS to see if both machines work fine.

**Comment by fatrolls** [comment]
fixed it, it was indeed old SSL revision 1.1.1 from https://github.com/openssl/openssl I used https://github.com/openssl/openssl/releases/tag/openssl-3.0.0-alpha9

problem just disappeared on all my computers.

Thanks
