### ISSUE TITLE
Where to obtain certificate for `httplib::SSLClient::set_ca_cert_path` function

### ISSUE THREAD

**Issue by cyrusbehr** [yhirose/cpp-httplib#779]
I'm following the example here:
```
#define CPPHTTPLIB_OPENSSL_SUPPORT

httplib::SSLServer svr("./cert.pem", "./key.pem");

httplib::SSLClient cli("localhost", 1234); // or `httplib::Client cli("https://localhost:1234");`
cli.set_ca_cert_path("./ca-bundle.crt");
cli.enable_server_certificate_verification(true);
```

and I'm wondering, where can I get the certificate to provided to the `set_ca_cert_path`, in the above example `ca-bundle.crt`.

**Comment by yhirose** [comment]
@cyrusbehr, you can get more information from [here](https://curl.se/docs/caextract.html). Hope it helps!

**Comment by cyrusbehr** [comment]
Awesome thank you so much! 
And thank you also for the very fast response!
