### ISSUE TITLE
std::string not supported as input for many methods?

### ISSUE THREAD

**Issue by maxnoe** [yhirose/cpp-httplib#781]
It would be nice to support directly passing `std:string` or `const std::string` to methods like `Client` or `Client::Get` and not requiring calling `c_str()`

**Comment by yhirose** [comment]
@maxnoe, thanks for asking. There is no plan to add methods taking `std::string`.

But for the next generation of this library (only support C++17), I am planning to provide the following interface which can accept both `char*` and `std::string` with one interface.

```cpp
Result Get(std::string_view path, ClientOptions options); 
```

There is the experimental method in the cpp17 branch:
https://github.com/yhirose/cpp-httplib/blob/192f298ad5d7fa75a770c49fbd34584216bc5e5d/httplib.h#L741

Hope this information answer your question.

**Comment by maxnoe** [comment]
Any reason why something like `const std::string& ` is not supported? It seems like the natural choice to me from an outside perspective.

**Comment by yhirose** [comment]
I just don't wan't to increase number of HTTP methods. For instance, there are about 50 HTTP methods in `Client`, and I am already overwhelmed with the maintenance of them. If the `const std::string&` versions are added, there will be about 100... And most of my use cases, I just specify C literal strings directly anyway, and very rare to pass std::string strings.
