### ISSUE TITLE
Getting res.error() = 4 for get request.

### ISSUE THREAD

**Issue by sumitsuthar** [yhirose/cpp-httplib#782]
I am getting error code = 4.
What is the reason behind this error code?

**Comment by yhirose** [comment]
Please see [here](https://github.com/yhirose/cpp-httplib#error-code) in README.

**Comment by sumitsuthar** [comment]
I want to know reason behind the read error. Why this error comes up.

**Comment by yhirose** [comment]
Socket reading error or reading time out.
