### ISSUE TITLE
Client can not connect with specific device "LINKZONE 4G LTE Cat4 Mobile Wi-Fi"

### ISSUE THREAD

**Issue by furkan-kara** [yhirose/cpp-httplib#786]
I have a client implementation to login to server and get information as continuously. Application works properly as expected with the mobile internet or cable. But never connected with this device "LINKZONE 4G LTE Cat4 Mobile Wi-Fi".  After I add `set_keep_alive(true);` , sometimes it connects, sometimes it does not. I could not find what caused this situation. I try this device with [cpprestsdk](https://github.com/microsoft/cpprestsdk) it work properly.

Any ideas what might have caused it?
Thank you.

**Comment by PixlRainbow** [comment]
1. Please provide a minimum code example that can reproduce the issue on your machine
2. Which client are you using? `Client` or `SSLClient`?
3. What is the error code produced when it does not connect?
4. You can check NAT type, proxy settings or firewall settings on the device.

**Comment by furkan-kara** [comment]
This is how I try to connect and I used SSLClient. The response (I think this is error code) return 0.


```
   mHttpClientRecv = std::make_unique<httplib::SSLClient>(mServerAddress.c_str(), mServerPort);
    mHttpClientRecv->set_follow_location(true);
    mHttpClientRecv->set_read_timeout(mTimeoutInSec, mTimeoutInSec);
    mHttpClientRecv->set_keep_alive(true);

    if (mProxyActive)
    {
        mHttpClientRecv->set_proxy(mProxyServerAddress.c_str(), mProxyServerPort);

        // Basic Authentication
        if (mProxyAuthentication)
            mHttpClientRecv->set_proxy_basic_auth(mProxyUsername.c_str(), mProxyPassword.c_str());
    }

    if (!mHttpClientRecv->is_valid())
    {
        return;
    }

    {
        while (!mExitRequested)
        {
            try
            {
                httplib::Headers headers = {#####};
                httplib::Result response = mHttpClientRecv->Get(serverUrl.c_str(), headers);

                if (mExitRequested)
                    break;

                auto result = mHttpClientRecv->get_openssl_verify_result();
                if (result)
                    std::cout<<"HTTP GET SSL Verify Error: ";

                if (response && response->status == 200)
                { 
                    //   
                    std::cout<< response->body;
                }
                else
                {
                    std::cout<< "Empty or Bad Response Returned";
                    std::cout<< response;
                }
            }
            catch (const std::exception &ex)
            {
                std::cout<< ex.what();
                
            }
            catch (...)
            {
                /* */
            }
        }
    }
```

**Comment by PixlRainbow** [comment]
No, the error code is not the value of `response` itself. `response` is a `httplib::Result` object. To get the error code, [you call `response.error()`](https://github.com/yhirose/cpp-httplib#client-1).  

___
This is safe to do as `response` itself will never be a `nullptr`. In fact, it is not a pointer at all. It supports the pointer-like arrow operator because it implements a custom arrow operator call, and it can evaluate to false for empty or bad response because it implements a custom boolean operator call.

**Comment by furkan-kara** [comment]
I change my code and it returns error code 8.

**Comment by PixlRainbow** [comment]
[Error code 8 is "could not establish a secure connection"](https://github.com/yhirose/cpp-httplib#error-code).  
An example would be if a TCP connection was established but the TLS handshake failed.

**Comment by furkan-kara** [comment]
Okey but only this device gives this error. what might have caused it? And I discover new thing, as I mentioned it sometimes connect and sometimes not, if it is not connect at first time, keep trying. And it successfully connect after 2.5-3 minutes.

**Comment by PixlRainbow** [comment]
try [extending the timeout](https://github.com/yhirose/cpp-httplib#timeout-1)?

**Comment by yhirose** [comment]
@furkan-kara, I don't think this is a problem caused by cpp-httplib. As @PixlRainbow implies, it seems to be a certain network problem. You could try sending the same request via curl to see more meaningful information that has better error report system. So I'll close it. Hope this information helps!

**Comment by PixlRainbow** [comment]
@yhirose they said that they had tested with the same device and network using a different library (Microsoft cpprestsdk) and the request completed successfully with no errors.

**Comment by yhirose** [comment]
@PixlRainbow, sorry that I didn't read the thread carefully... So do you think if it's a problem in cpp-httplib, or just timeout setting is too short?

**Comment by furkan-kara** [comment]
Connection timeout is set as default. Read or write timeout is set as 30 seconds. And no change when increase or decrease timeout.

**Comment by PixlRainbow** [comment]
Does the cpp httplib client work when sending request to a different server or when sending a non secured request (with normal not ssl client)?

___
It is possible that the 4G access point has some form of NAT that rewrites source/destination hostnames or IP addresses and cpp httplib might not be handling it correctly. A similar problem was seen with openssh in WSL which would cause key exchange process to fail when other https programs within the same WSL instance worked.

**Comment by yhirose** [comment]
@furkan-kara, could you answer the question above from @PixlRainbow?

**Comment by furkan-kara** [comment]
Sorry for the late reply. We determined that the problem is not caused by the library but by the device. This device gives an SSL error after running with curl for a while.
