### ISSUE TITLE
HTTP client does not support multipart

### ISSUE THREAD

**Issue by csersoft** [yhirose/cpp-httplib#790]
Hello!
The PUT method in the HTTP client does not support multipart.
Is the PUT request itself not supporting multipart?
Regards.

**Comment by yhirose** [comment]
@csersoft, thanks for the feedback. The short answer is no. (I might be supporting GET if users want.)
Please see [this stackoverflow post](https://stackoverflow.com/questions/8054165/using-put-method-in-html-form) for more information. Hope it helps!
