### ISSUE TITLE
Binary file post in http client

### ISSUE THREAD

**Issue by johnlu0907** [yhirose/cpp-httplib#791]
Hi,
I'm going to upload binary or video files to rest server.
Please provide me sample
Thanks

**Comment by PixlRainbow** [comment]
See:
https://github.com/yhirose/cpp-httplib/issues/194#issuecomment-515653093
or
https://github.com/yhirose/cpp-httplib/issues/336#issuecomment-576973884

Make sure to set the mime-type to match the file format you are uploading, and remember to make sure your input `std::string` has been configured to carry binary data correctly

**Comment by yhirose** [comment]
@PixlRainbow, thanks for answering the question.
