### ISSUE TITLE
Communication between library and website through different machines in local network

### ISSUE THREAD

**Issue by fs-c** [yhirose/cpp-httplib#792]
This question is only tangentially related to the library and I would fully understand if it were to be closed as being off-topic.

With that out of the way: I am trying to implement the following:
- User runs an application on a local machine which runs `cpp-httplib` and accepts requests. These requests control some other functionality of said application.
- User visits a website (something like `https://some.domain/configure`) on a (potentially different) machine _in the same local network_. 
- User can now control the application on local machine A from the website opened on local machine B, where A and B are not not necessarily the same machine but guaranteed to be on the same network.

The important point here is that it should be possible to use two different machines. If it were just one, the website could simply send requests to `http://localhost:<port>` and it would work fine.

One potential solution is to scan the local network for the machine on which the application is running (i.e. GET 192.168.A.B:<port>, ... and if one returns 200 we found it) but that is inelegant and very slow.

I can't imagine that this is such a rare use-case so I figured I'd ask here. Thanks in advance, but as I said I'd completely understand if you were to close this.

**Comment by PixlRainbow** [comment]
what is the problem? Can you not just host the website inside the application that is offering services to remote machines? Aka just put a function call inside the web API request handlers to activate the "other functionality" of said application, but *also* serve the web UI from the same machine.

**Comment by fs-c** [comment]
>Can you not just host the website inside the application that is offering services to remote machines?

Thanks for your quick response and yes, I could do that. But I think I failed to communicate an important point: I don't want my users to have to look up the local IP address of the machine that runs the application. If that were on the table I could simply require them to input said local IP on the website in case the connection to `http://localhost:<port>` fails.

No, what I essentially need is a way for the website to know where the application runs. One attempt was to simply scan the whole local network but that has proven to be impractical.

**Comment by PixlRainbow** [comment]
It is possible to scan the whole network quickly, but it is not something that can be implemented within the http protocol; that would have to be done at the network interface layer, by transmitting broadcast packets.
___
*If* you have to stay within http, then there must be a central "matchmaking" server hosted at a known fixed address or domain name. The service executor must submit it's address to the matchmaker on startup, and the client will then ask for the address of the service executor from the matchmaker.

Note that if the UI webpage is hosted on a different "origin" (IP address or domain name) from the API backend, then all modern web browsers require that your API backend response have a "cross origin response header" that permits access from the UI website, or the browser will block the request.

**Comment by fs-c** [comment]
>by transmitting broadcast packets.
I'm constrained to the browser (since I want users to be able to control the application from any device capable of rendering a webpage and I don't want to write "control applications" for multiple platforms) so broadcasting is not an option. Nevertheless a good point that I hadn't thought of.

>a central "matchmaking" server hosted at a known fixed address or domain name
I had previously considered this but discarded the idea since it requires the user to have a connection to the internet. The website is "offline-first" through service workers so that wouldn't otherwise be a requirement. Though, from the way you phrased it, I take that a "matchmaking server" is the _only_ feasible option in which case I don't have much of a choice anyway.

But I could swear that I've previously seen implementations which did the exact thing I'm trying to do and they _didn't_ require internet access. So I'm still somewhat fixated on finding a different way. But I have a deadline to follow so it'll be a side-project I guess.

Anyways: Thank you for your time, I really appreciate it! I'll close this for now and implement a matchmaking server.

**Comment by PixlRainbow** [comment]
If you are using a sufficiently new web browser, you actually do have other communication protocols to choose from e.g. camera QR codes, bluetooth, etc.
The "known fixed address" does not have to be on the internet; it can be local as well, as long as you tell the user to set up local network DNS first.
Note that if you are using electron to build applications, you aren't actually limited to browser features; you can also access scripts or functions outside of the browser context.

**Comment by fs-c** [comment]
Thanks a lot for the QR code idea, I'll look into implementing something like that. (I actually had a matchmaking server running already but it's not currently viable for other reasons... so I figured I'd just display the users local address and they'd be able to input it themselves. QR codes are obviously much more convenient than that for the average user.)

>The "known fixed address" does not have to be on the internet; it can be local as well, as long as you tell the user to set up local network DNS first.
Good suggestion, but I absolutely don't trust my users to be able to do that.

>Note that if you are using electron to build applications, you aren't actually limited to browser features; you can also access scripts or functions outside of the browser context.
I'd wager that's the main reason for anyone to use it. Why do you mention it though? I'm probably missing something but I don't see how it's relevant in the given context.

**Comment by PixlRainbow** [comment]
> Why do you mention it though? 

Because we have had users who paired electron for frontend with this library as a backend server, and some of them had some confusion over what features were http or browser compatible and which were features were provided out-of-band. And I was uncertain whether you were, sorry.
