### ISSUE TITLE
Execution conditions of skip_content_with_length

### ISSUE THREAD

**Issue by Lucas-Yuzc** [yhirose/cpp-httplib#793]
```
template <typename T>
bool read_content(Stream &strm, T &x, size_t payload_max_length, int &status,
                  Progress progress, ContentReceiverWithProgress receiver,
                  bool decompress) {
  return prepare_content_receiver(
      x, status, std::move(receiver), decompress,
      [&](const ContentReceiverWithProgress &out) {
        auto ret = true;
        auto exceed_payload_max_length = false;

        if (is_chunked_transfer_encoding(x.headers)) {
          ret = read_content_chunked(strm, out);
        } else if (!has_header(x.headers, "Content-Length")) {
          ret = read_content_without_length(strm, out);
        } else {
          auto len = get_header_value<uint64_t>(x.headers, "Content-Length");
          if (len > payload_max_length) {
            exceed_payload_max_length = true;
            skip_content_with_length(strm, len);
            ret = false;
          } else if (len > 0) {
            ret = read_content_with_length(strm, len, std::move(progress), out);
          }
        }

        if (!ret) { status = exceed_payload_max_length ? 413 : 400; }
        return ret;
      });
}
```

In function read_content, **if (len > payload_max_length), then skip_content_with_length**
If you are on a 32-bit system, the recv body size will be limited to 4GB, this condition makes me confused.
The above code, what are the considerations of the execution operation under this condition? thanks.

**Comment by yhirose** [comment]
@Lucas-Yuzc, thank you for the feedback. I don't fully understand what you are asking though, I'll try to answer the question. `payload_max_length` is `size_t` and set to `std::numeric_limits<size_t>::max()` as default. On a 32bit environment, `size_t` becomes same as `uint32_t`. Even if a client sends huge data exceed 4GB, the code can detect it, and skip the whole data, and will become ready for another request in the same connection on Keep-Alive mode. Does it make sense to you?

**Comment by Lucas-Yuzc** [comment]
> @Lucas-Yuzc, thank you for the feedback. I don't fully understand what you are asking though, I'll try to answer the question. `payload_max_length` is `size_t` and set to `std::numeric_limits<size_t>::max()` as default. On a 32bit environment, `size_t` becomes same as `uint32_t`. Even if a client sends huge data exceed 4GB, the code can detect it, and skip the whole data, and will become ready for another request in the same connection on Keep-Alive mode. Does it make sense to you?

I am currently using it as a client to receive data on a 32-bit system. When the data exceeds 4G, I find that it cannot accept the success, and I find that it is limited by size_t. So, I want to know that  why use std::numeric_limits<size_t>::max() to determine the payload_max_length and not uint64_t?
thanks~

**Comment by yhirose** [comment]
@Lucas-Yuzc, it's because `Request::body` is `std::string` that cannot hold data exceeds 4GB anyway. So if you expect the data is expected larger than 32 bit length, you have to move to 64 bit environment at this point.
