### ISSUE TITLE
detail function proposal to parse url

### ISSUE THREAD

**Issue by mipac** [yhirose/cpp-httplib#797]
Hi,

it could be a good idea to add a function to parse url to split domain, path, etc...
I always need it when using httplib ;)

```c++
struct parse_url_t {
  std::string protocol;
  std::string domain;
  std::string port;
  std::string path;
  std::string query;
};
static parse_url_t parse_url( const std::string &url ) {

  const std::regex ex( "(http|https)://([^/ :]+):?([^/ ]*)(/?[^ #?]*)\\x3f?([^ #]*)#?([^ ]*)" );
  parse_url_t rep;
  std::cmatch what;
  if ( regex_match( url.c_str(), what, ex ) ) {
    auto n = what.size();
    if ( n > 0 )
      rep.protocol = std::string( what[1].first, what[1].second );
    if ( n > 1 )
      rep.domain = std::string( what[2].first, what[2].second );
    if ( n > 2 )
      rep.port = std::string( what[3].first, what[3].second );
    if ( n > 3 )
      rep.path = std::string( what[4].first, what[4].second );
    if ( n > 4 )
      rep.query = std::string( what[5].first, what[5].second );
  }

  return rep;
}

```

**Comment by yhirose** [comment]
@mipac, thanks for the suggestion, but I can take the pull request unless it's well tested. Sorry about that.

Wwriting safe/efficient URL parsing code is much more difficult than we think. [Here](https://github.com/yhirose/cpp-httplib/blob/0954af2d4c7edcbf5667b4ecd22260ebf95e2ca0/httplib.h#L5145-L5146) is the current regex pattern in httplib.h to parse URL. It has been improved over the years to fix security problems...

Anyway, I would recommend you to use other open source URL parsers for this purpose. Hope it helps!

**Comment by mipac** [comment]
thanks for reply,
I understand, that's one of the reasons that make that lib a good one !
I haven't seen that parsing code , perhaps it could be factorised in detail namespace

**Comment by poor1017** [comment]
@mipac 
Your code helps for me.
Thanks
