### ISSUE TITLE
c++11 ‘auto’ in lambda parameter

### ISSUE THREAD

**Issue by DraTeots** [yhirose/cpp-httplib#8]
Hi!
It is said that cpp-httplib is C++11 library. But when I try to build example on gcc, I get an error:
```
error: use of ‘auto’ in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
```
While this relates only to examples code it... should be at least said somewhere...

**Comment by yhirose** [comment]
@DraTeots, I have just changed the example code in README not to use the C++14 generic lambda.
