### ISSUE TITLE
HTTPS client call

### ISSUE THREAD

**Issue by ruipedromachado** [yhirose/cpp-httplib#805]
Hello,

Might not be an issue at all so feel free to just disregard. More of a question really.

Found this solution searching for similar and got quite excited when I saw that supported HTTPS?

![image](https://user-images.githubusercontent.com/45498752/102670865-522cf300-4187-11eb-8479-b4ccc32fcd56.png)

So after adding the .h file to my project and making the example call:

![image](https://user-images.githubusercontent.com/45498752/102671485-7d174700-4187-11eb-875b-fffcb5dd92bb.png)

...so far so good, however changing to HTTPS:

![image](https://user-images.githubusercontent.com/45498752/102671694-8bfdf980-4187-11eb-8e1d-752cd21b696f.png)

Thanks

**Comment by yhirose** [comment]
@ruipedromachado, could you take a look at [here](https://github.com/yhirose/cpp-httplib#openssl-support) in README?

**Comment by karthik2cs** [comment]
Can we connect to other https url's like https://webhook.site ?
