### ISSUE TITLE
Why doesn't POST work when my URL has an http:// prefix?

### ISSUE THREAD

**Issue by asfarley** [yhirose/cpp-httplib#809]
I'm having trouble understanding why a POST request doesn't work. My code:

```
httplib::Client cli(URL, Port);

    httplib::Params params;
    params.emplace("user[email]", Username);
    params.emplace("user[password]", Password);

    httplib::Headers headers = {
            { "Accept", "application/json" }
    };

    auto res = cli.Post("/users/sign_in", headers, params);
```

I'm finding that `res` is empty if I use the following URL:
`http://ec2-34-222-30-114.us-west-2.compute.amazonaws.com/`

But it works if I remove the http:// prefix and the trailing /:

`ec2-34-222-30-114.us-west-2.compute.amazonaws.com`

Testing against my server, it appears to respond correctly even if there are duplicate slashes in the complete URL, i.e.:
`http://ec2-34-222-30-114.us-west-2.compute.amazonaws.com//users/sign_in`

So it seems that this library doesn't like my URL formats for some reason. My interpreation of the README looks like the http:// prefix should be fine in URLs, and my understanding of HTTP in general is that double-slashes in the route are up to the server to handle. Is it expected that I'm getting errors using the http:// prefix and the trailing slash?

**Comment by PixlRainbow** [comment]
Technically, the trailing slash IS a route. It is `/` which is web root.
It should work if you do not include the trailing slash, even if you include the protocol prefix.

**Comment by yhirose** [comment]
The `Client` constructor takes a domain name which can also take a scheme prefix with `://`. In other words, it's not `URL`. So we shouldn't put a trailing slash. Hope it heps.
