### ISSUE TITLE
Expression: c >= -1 && c <= 255

### ISSUE THREAD

**Issue by Fuatnow** [yhirose/cpp-httplib#817]
```cpp
wstring str = LR"(中国語)";
std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> convert;
string xx = convert.to_bytes(str);
httplib::Params params{
	  { "wxid", xx },
	  { "msg", xx }
};
httplib::Client cli("http://localhost:8900");
auto res = cli.Post("/receiveMsg", params);
```

I'm a chinese. When i use chinese char ， this error has appeared。

I found this mistake in `encode_query_param` function.

I have replaced `for (char const &c : value) `  to `for (unsigned char const &c : value) ` . Now，it works fun.

**Comment by yhirose** [comment]
@Fuatnow, thank you for the report.
@Yrds, it seems like this bug is introduced by #801. Could you take a look at it? Thanks!

**Comment by Yrds** [comment]
Hi @Fuatnow i did some tests, including your example code and i can't reproduce your error, i am tring to figure out what is causing this.

Which line is causing this error?

Also code already have static_cast to unsigned char(when the encode is made) in this lines:

```cpp
      escaped << '%' << std::setw(2)
              << static_cast<int>(static_cast<unsigned char>(c));
```

Tests that i made and all passed:

```cpp
TEST(EncodeQueryParamTest, TestUTF8Characters){
  string chineseCharacters = "中国語";
  string russianCharacters = "дом";
  string brazilianCharacters = "óculos";

  EXPECT_EQ(detail::encode_query_param(chineseCharacters),
      "%E4%B8%AD%E5%9B%BD%E8%AA%9E");

  EXPECT_EQ(detail::encode_query_param(russianCharacters),
      "%D0%B4%D0%BE%D0%BC");

  EXPECT_EQ(detail::encode_query_param(brazilianCharacters),
      "%C3%B3culos");
}
```

**Comment by Fuatnow** [comment]
> Hi @Fuatnow i did some tests, including your example code and i can't reproduce your error, i am tring to figure out what is causing this.
> 
> Which line is causing this error?
> 
> Also code already have static_cast to unsigned char(when the encode is made) in this lines:
> 
> ```c++
>       escaped << '%' << std::setw(2)
>               << static_cast<int>(static_cast<unsigned char>(c));
> ```
> 
> Tests that i made and all passed:
> 
> ```c++
> TEST(EncodeQueryParamTest, TestUTF8Characters){
>   string chineseCharacters = "中国語";
>   string russianCharacters = "дом";
>   string brazilianCharacters = "óculos";
> 
>   EXPECT_EQ(detail::encode_query_param(chineseCharacters),
>       "%E4%B8%AD%E5%9B%BD%E8%AA%9E");
> 
>   EXPECT_EQ(detail::encode_query_param(russianCharacters),
>       "%D0%B4%D0%BE%D0%BC");
> 
>   EXPECT_EQ(detail::encode_query_param(brazilianCharacters),
>       "%C3%B3culos");
> }
> ```

HI,I do windows development. I use wstring convert to std::string. That error must appear.
Please use this code snippet for test.
```
#include <codecvt>
wstring str = LR"(中国語)";
std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> convert;
string xx = convert.to_bytes(str);
```

**Comment by yhirose** [comment]
@Fuatnow, could you show @Yrds the actually error message that you got on your machine? It seems your information isn't enough for him to investigate. Thanks.

**Comment by Fuatnow** [comment]
> @Fuatnow, could you show @Yrds the actually error message that you got on your machine? It seems your information isn't enough for him to investigate. Thanks.

![image](https://user-images.githubusercontent.com/5172503/103416002-907ed500-4bbf-11eb-996c-5407b7eb2763.png)

**Comment by yhirose** [comment]
@Fuatnow , thanks! I am sure now that this is caused at the `std::isalnum` call.

**Comment by Fuatnow** [comment]
> @Fuatnow , thanks! I am sure now that this is caused at the `std::isalnum` call.

Ok. May be the `std::isalnum` function's param in round [-1,255].I do a breakpoint, the char value is -26.

![WechatIMG421](https://user-images.githubusercontent.com/5172503/103416760-fcaf0800-4bc2-11eb-9c9f-3b780df21343.png)
Hope that is useful to you.

**Comment by yhirose** [comment]
@Fuatnow, I just fixed it. Thanks for the report.
