### ISSUE TITLE
Multitude of Errors When Including httplib.h

### ISSUE THREAD

**Issue by Brittank88** [yhirose/cpp-httplib#819]
Hi there! I'm somewhat new to C++, so I really hope my problems are not something simplistic I've missed.

I've been reading around for the past 2-3 hours attempting to solve this on my own, however, I have come no closer to understanding why so many errors appear within `httplib.h` (as well as a single error in `std_function`, which is concerning).

I'm running on `Windows 10 Pro 64-bit (Build 19041)`, using `gcc version 9.2.0 (MinGW.org GCC Build-2)` through `VSCode 1.53.0-insider` to build.

[My code is as follows](https://pastebin.com/F3msiPBb).

Hoping for some assistance - my apologies if this falls outside of the scope of the issue tracker!

**Comment by yhirose** [comment]
@Brittank88, thanks for the feedback, but I don't have time to help someone's projects... Could you give me a smallest possible code example to reproduce it? Thank you for your consideration.

**Comment by Brittank88** [comment]
I totally understand - I'm sure you are quite busy!! I was mainly wondering if you knew of any existing gotchas/incompatibilities with VSCode, MinGW or Windows, for example, that could be causing my issues.

The set of errors will occur with literally only the line `#include "httplib.h"` present:
![image](https://user-images.githubusercontent.com/24266948/103416791-435d2c00-4bdc-11eb-94ef-0a040c4d8d08.png)

**Comment by yhirose** [comment]
@Brittank88, "`std::tread` has not been declared" tells that you are not compiling with C++11. Or, your include directory setting isn't set properly. It's not a problem of httplib.h, but just compiler setting. Hope it helps.

**Comment by Brittank88** [comment]
Yeah, it's very likely on my end rather than yours. Thanks for pointing me in the right direction though, and being patient!

Happy developing. c:
