### ISSUE TITLE
Error handler DataSink sends extra data after every <<

### ISSUE THREAD

**Issue by 00ff0000red** [yhirose/cpp-httplib#820]
I've had been using a few libraries for a server when I realized two things: the error handler is incredibly slow to start, and I'm noticing extra characters being output to the stream.

I know my code inside the error handler executes blazingly fast with little memory usage.
I know what the stream should send.

I directed my output to following:
* a file output stream
* an terminal output stream
* a non-error handler datasink.os stream
* an error handler datasink.os

All of these worked fine and were very resonsive, but the error handler seems to be corrupting the stream.

It only happens in between each call to the datasink's ostream << operator.

Reproduced on Repl.it:
https://repl.it/@xxpertHacker/bug-proof#main.cpp

**Comment by yhirose** [comment]
@00ff0000red, thanks for finding the bug! I actually didn't think of the situation where the content provider is used in an error handler...
