### ISSUE TITLE
Cannot redirect after sending content

### ISSUE THREAD

**Issue by 00ff0000red** [yhirose/cpp-httplib#821]
I'm not sure if it's part of how HTTP works, or if it's the library, but after sending some content (ex: `DataSink.os <<`), attempting to redirect via `Response.set_redirect` has no effect, is this a bug?

Example reproduction:
https://repl.it/@xxpertHacker/bug-proof

**Comment by yhirose** [comment]
@00ff0000red, thanks for the report. It seems to be a bug, and I'll look into it. (As a matter of fact, I have never tested `set_redirect` with content providers as you can see in `test/test.cc`...)

**Comment by 00ff0000red** [comment]
> ... content providers as you can see in `test/test.cc`...)

Ha, I might send a few more bug reports about how content_providers interact with everything since I'm exclusively streaming all data from the server (e.g. no .set_content).

**Comment by 00ff0000red** [comment]
Oh, just figured out the sending HTTP headers seem to not work from within chunked provider callbacks, I just moved the sending of the headers outside of the callback.

**Comment by PixlRainbow** [comment]
> sending HTTP headers seem to not work from within chunked provider callbacks

Yes, because the chunked provider callback is executed very "late" in the response processing pipeline as it's primary purpose is to write response body, while headers are written almost immediately after the request handler exits.

If you were allowed to set headers in content provider callback, we would have to guard against headers being written after a previous call to the callback had already written to body stream.

Technically, we *could* throw an exception if an attempt is made to set header from content provider, but some developers may prefer silent failure.

**Comment by PixlRainbow** [comment]
> after sending some content (ex: DataSink.os <<), attempting to redirect via Response.set_redirect has no effect

Update: `set_redirect` will set the `"Location"` header, and we cannot write headers after we have already begun sending the response body to the client.

**Comment by PixlRainbow** [comment]
Update after reading your code:
```cpp
try {
    constexpr str content = "Some content\n"sv;
    sink.os << content;
    // ...	
} catch (std::runtime_error const&) {
    sink.done();
    res.set_redirect("/error", 500);
}
```
The call to `set_redirect` will attempt to set the `Location` header, but the HTTP protocol does not permit headers to be written after the response body has already been sent to the client.

**Comment by 00ff0000red** [comment]
> The call to `set_redirect` will attempt to set the `Location` header and response code, but standard HTTP response structure does not permit headers to be written after the response body has already been sent to the client.

This was what I was thinking, that this is just how HTTP works, thank you for confirming!
