### ISSUE TITLE
Object Storage S3 Usage

### ISSUE THREAD

**Issue by ecleeEEL** [yhirose/cpp-httplib#824]
Hi i found a couple issues i had to "hack" around to get it to work for my application.  I'm working on some object storage relay.  One issue is that S3 DELETEs respond with 204, no response.  The httplib would hang until request timeout as it was waiting to process response bytes where there are no bytes to process.  I've submitted a pull request for this.

https://github.com/yhirose/cpp-httplib/pull/823

The second issue, i am still working on staging in another pull request/issue.  this involves making it handle generic binaries and not just text strings.  This is more of a hack as c++ isn't my strong suit.

Thanks for this easy to use library!

**Comment by yhirose** [comment]
@ecleeEEL, thank you for your fine contribution. The pull request looks file to me. Only thing is that I always ask contributors to provide unit tests for the changes. Could you provide a simple unit test case for this change? Thanks!

**Comment by PixlRainbow** [comment]
> The second issue, ... this involves making it handle generic binaries and not just text strings. 

What do you mean? httplib already handles binaries. Despite the name, `std::string` is not merely for human-readable strings. It is merely a wrapper around `char*` that provides extra ease of use functions.
C and C++ makes no distinction between text or binary byte data, representing both as arrays of bytes aka `char*`.

**Comment by ecleeEEL** [comment]
@yhirose Yes i will look into adding a unit test.

**Comment by vshishov** [comment]
@ecleeEEL I am working on some object store relay and am using httplib too. I posted an object from multipart form-data, but I have a problem with getobject and sending to client multipart. Please, let me some examples how to get big object from S3.

**Comment by ecleeEEL** [comment]
@vshishov Hi, our use-case only has objects <10MB, so i haven't tried using client multipart.

**Comment by PixlRainbow** [comment]
@vshishov see: [content providers and content receivers](https://github.com/yhirose/cpp-httplib#receive-content-with-a-content-receiver-1)

**Comment by yhirose** [comment]
@ecleeEEL, any update?

**Comment by ecleeEEL** [comment]
No update, i'll try to get this completed by end of week

**Comment by ecleeEEL** [comment]
Added test, one check failed on macos  but worked on my macos laptop.  I don't think it's related to the change made.

**Comment by yhirose** [comment]
@ecleeEEL, thanks for your fine contribution! The PR has been merged.
