### ISSUE TITLE
Generic Binary

### ISSUE THREAD

**Issue by ecleeEEL** [yhirose/cpp-httplib#826]
> The second issue, ... this involves making it handle generic binaries and not just text strings. 

What do you mean? httplib already handles binaries. Despite the name, `std::string` is not merely for human-readable strings. It is merely a wrapper around `char*` that provides extra ease of use functions.
C and C++ makes no distinction between text or binary byte data, representing both as arrays of bytes aka `char*`.

This is copied from issue 824.  This is a new issue to discuss why generic binary didn't seem to work.

_Originally posted by @PixlRainbow in https://github.com/yhirose/cpp-httplib/issues/824#issuecomment-755097175_

**Comment by ecleeEEL** [comment]
Attaching pull request with the hack I made to get a generic byte buffer to work through http client.  Not knowing the full scope of how the library was created, i didn't want to break pre-existing apis, so i hacked in another overloaded Put method.

Ideally as @PixlRainbow mentioned, my c background would pass in a char * and a size_t indicating buffer length, and then the PUT would handle anything whether it's text or binary data.  But since it's wrapped up in std::string AND the length of the "string" is used later down in the callstack on in the code `body.size()`, the code as currently checked in did not work as my byte buffer probably had a bunch of null characters within it.  Maybe there is a way to construct std::string with null characters within the string, but it seems like it would be safer and more portable to just use a unique_ptr<char[]> if after supporting a generic buffer.

**Comment by ecleeEEL** [comment]
i will add this. maybe there is a more elegant c++ way to do this.  My experience in c++ pre-dates c++ 11, so it's always a lot of fumbling around to figure how to do things in c++ in industry-standard ways.

**Comment by sharatk** [comment]
A std::string can be constructed with embedded null characters and will work well unless you are relying on c_str(). Perhaps there was some other reason why byte buffer failed. I have used PUT with binary data and it works fine.

**Comment by PixlRainbow** [comment]
you can just construct an `std::string` with two parameters (pointer and size) instead of one.

**Comment by ecleeEEL** [comment]
Ahh.  Thank you guys for the helpful responses.  I think the problem I encountered was on the application side with the string constructor and not using the constructor with the explicit length specified.

Still wondering what are the benefits of using std::string in place of a char array for this implementation.  It seems the main benefit is the size is stored together and an extra parameter is unnecessary?  It doesn't seem like the right explicit type to use if the concept of passing a generic byte sequence is the intention.

**Comment by yhirose** [comment]
@ecleeEEL, as @PixlRainbow said, `std::string` can be used to store binary data with no problem though, I understand benefit of `char*` interface as well. But `const std::unique_ptr<char[]> &` isn't a good idea.
So I just added the pure `const char*` and `size_t` interface at https://github.com/yhirose/cpp-httplib/commit/ddf41d29efef0e5b10ee3a43da9ec84ac8f13cb1, so that we can pass whatever data type like raw memory or `std::vector` directly to client API. Hope the change will satisfy your needs.

**Comment by PixlRainbow** [comment]
@ecleeEEL it also performs automatic copying and space allocation as well as utility features like concatenation. Also, unlike `char*`, `std::string` implements `hashable` so it can also be used directly in an `std::unordered_map` aka hash table
