### ISSUE TITLE
Adding config parameter for thread pool count 

### ISSUE THREAD

**Issue by omjego** [yhirose/cpp-httplib#828]
Currently the server uses `CPPHTTPLIB_THREAD_POOL_COUNT` macro to set number of threads which can be used to process the requests. 
Is it possible to include this count as part of server configuration. 

Something like, 
```
httplib::Server svr...;
 svr.set_thread_pool_count(1000); 
```
Is there any benefit of using macro over simple config variable?

**Comment by yhirose** [comment]
@omjego, thanks for the feedback. I have already answered the question before.
Please see https://github.com/yhirose/cpp-httplib/pull/652. Hope it helps.
