### ISSUE TITLE
Please help with cli.Post("/post", headers, params)

### ISSUE THREAD

**Issue by mmoelle1** [yhirose/cpp-httplib#829]
First of all, thank you very much for making this code available to the public.

I tried to include the library into a code that communicates with the IBMQ website via the REST API and get stuck at the authentication phase. I would like to transform the following command (issued from a Linux terminal) to httplib:
```bash
curl -X POST "https://api.quantum-computing.ibm.com/v2/users/loginWithToken" -H "Accept-Type: application/json" -H "Content-Type: application/json" -d "{\"apiToken\":\"abc...MY_PRIVATE_TOKEN\"}"
```
I tried to adapt the `client.cc` code as follows (without success):
```cpp
  httplib::SSLClient cli("https://api.quantum-computing.ibm.com/v2/users/loginWithToken", 443); // also tested without port
  cli.set_ca_cert_path(CA_CERT_FILE);
  cli.enable_server_certificate_verification(true);

  httplib::Headers headers = {
    { "Accept-Type", "json" },
    { "Content-Type", "json" }
  };
  
  httplib::Params params = {
    { "\"apiToken\"", "\"abc...MY_PRIVATE_TOKEN\"" } // also tested without \" \"
  };

  auto res = cli.Post("/post", headers, params);
  cout << "error code: " << res.error() << std::endl; // is 2
```
I always obtain the error code 2. Do you have an advice on how to debug this?

Many thanks in advanced,
Matthias

**Comment by PixlRainbow** [comment]
you have interpreted the README incorrectly. Please exclude the path from the hostname parameter and move it to the parameter of the actual post request.
Aka instead of
```cpp
httplib::SSLClient cli("https://api.quantum-computing.ibm.com/v2/users/loginWithToken");
// ......
auto res = cli.Post("/post", headers, params);
```
do
```cpp
httplib::SSLClient cli("api.quantum-computing.ibm.com");
// ......
auto res = cli.Post("/v2/users/loginWithToken", headers, params);
```
You are getting error code 2 because you have provided an entire URL as a hostname and DNS cannot resolve a domain name containing slashes, so it cannot connect.

**Comment by mmoelle1** [comment]
Thank you very much. With the suggested change and some more it now works. One thing that is still unclear is the proper use of `headers` and `params`. The following code where I explicitly pass the XML code as a string is working:
```cpp
std::string msg = "{\"apiToken\":\"abc...\"}";
auto res = cli.Post("/v2/users/loginWithToken", msg, "application/json")
```

I also tried to achieve the same using `headers` and `params` without success:
```cpp
httplib::Headers headers = {
    { "Accept-Type", "json" },   // also tested with "application/json"
    { "Content-Type", "json" }
  };
  
  httplib::Params params = {
    { "\"apiToken\"", "\"abc...\"" } // also tested without \" \"
  };

  auto res = cli.Post("/v2/users/loginWithToken", headers, params);
```
This yields the error (response from the server):
```cpp
{"error":{"statusCode":415,"name":"UnsupportedMediaTypeError","message":"Content-type json does not match [application/json].","code":"UNSUPPORTED_MEDIA_TYPE"}}
```

Isn't `headers` the data structure to pass all `curl -H` parameters and `params` the data structure to pass the `curl -d` parameters. Thanks in advanced.

**Comment by PixlRainbow** [comment]
No. `params` does not form the body into a json format. That is the responsibility of the application. We only handle the base http protocol. Use a different library like jsoncpp if you want to construct json.

`params` constructs a body following the standard http url-encoded form submit format (if using `httplib::Params`) or the multipart form submit format (if using `httplib::MultipartFormDataItems`)

**Comment by mmoelle1** [comment]
Thank you very much. All works fine now.
