### ISSUE TITLE
How to log request params if I use method with content reader?

### ISSUE THREAD

**Issue by artemshadrunov** [yhirose/cpp-httplib#830]
Hi!

I am trying to setup logging of my requests to save params of request. It's ok when i use methods Get\Post with parameters `(const char *pattern, Handler handler)`. But I noticed that Get\Post methods with parameters `(const char *pattern, HandlerWithContentReader handler)` clear `params` field in `Request` object. Other words `Request` object already has no `params` inside when it comes to request handler(I suppose content reader takes it somehow).
So my question is how can I get parameters of request when `Request` object comes to log handler after request handler with parametrs `(const char *pattern, HandlerWithContentReader handler)`?

Thanks in advance

**Comment by yhirose** [comment]
@artemshadrunov, thank you for the feedback. Could you show me a code snippet that can reproduce the problem?

**Comment by artemshadrunov** [comment]
Well, i realized that some of my requests don't send content in `params` they send it in as json with `application/json` header . My bad. 
But the question about logging still actual. I can't see any content in any field in `Request` object but reader reads content from request successfully. 
So how can I get access to content of my request inside logger handler if `set_logger` method takes handler that takes only `Request` and `Response` object?

**Comment by PixlRainbow** [comment]
The problem is that the logger runs *after* the request completes, but when a content reader is used, each chunk of data is discarded after it is successfully streamed to the remote client. This is because some users use content reader to handle extremely large data transfers, larger than can reasonably fit in memory, but it also means logger has no access to the content.

**Comment by artemshadrunov** [comment]
This is sad but i always can store my data somewhere else after reading.
Thanks for quick response!

**Comment by yhirose** [comment]
@PixlRainbow, thanks for answering the question!
