### ISSUE TITLE
When I post a request and the target server drops the line, it will throw a signal: sigabrt (aborted) error

### ISSUE THREAD

**Issue by zhongqingyang** [yhirose/cpp-httplib#834]
I use gcc version is g++-7.5.0,Which version of g++ should I use to compile the library

**Comment by yhirose** [comment]
@zhongqingyang, this library basically supports C++11 compilers. But some compilers come with broken `std::regex` that cause sigabrt. Hope it helps!

**Comment by PixlRainbow** [comment]
He is experiencing a different error. Based on his description (which he did not copy), when the server drops the connection while the bufferstream is being written, the client will crash when the buffer is being appended, possibly due to invalid pointer or operation.
