### ISSUE TITLE
Connection issues using SSL

### ISSUE THREAD

**Issue by martinpeniak** [yhirose/cpp-httplib#837]
Hi guys,

Thank you very much for developing this amazing library. I am currently using version 0.8 from Conan: https://conan.io/center/cpp-httplib

I am running a server on arm device and client locally on x86 host. Everything works great until I start using SSLServer:

ARM SERVER:

		std::cout << "Initializing HTTPS client...";
		SSLServer svr("server_cert.pem", "server_key.pem");
		svr.Get("/hi", [](const Request &req, Response &res) { res.set_content("Hello World!", "text/plain"); });
		std::cout << "OK" << std::endl;
		svr.listen("192.168.1.108", 8000);
		
X86 CLIENT:

	        httplib::SSLClient https_client("192.168.1.108", 8000);
	        https_client.set_ca_cert_path("client_cert.pem");
	        https_client.enable_server_certificate_verification(true);
	        
I have generated self-signed certificate for the server using:

openssl req -x509 -newkey rsa:4096 -keyout server_key.pem -out server_cert.pem -nodes -days 365 -subj "/CN=localhost/O=Client\ Certificate\ Demo"

Then client certificates as follows:

openssl req -newkey rsa:4096 -keyout client_key.pem -out client_csr.pem -nodes -days 365 -subj "/CN=localhost"
openssl x509 -req -in client_csr.pem -CA server_cert.pem -CAkey server_key.pem -out client_cert.pem -set_serial 01 -days 365

This was giving me the following error: 

                error code: 10
                verify error: self signed certificate
                
Instead of client_cert.pem I tried using client.pem generated as follows:

cat client_cert.pem client_key.pem server_cert.pem > client.pem

In this case I only get: 

               error code: 10

Could you please help me understand what I am doing wrong? I am new to this library.

Kind Regads

**Comment by yhirose** [comment]
@martinpeniak, in order to find the problem, could you run `cd test; make` to see if all the unit tests including SSL related tests can run successfully?

**Comment by martinpeniak** [comment]
> @martinpeniak, in order to find the problem, could you run `cd test; make` to see if all the unit tests including SSL related tests can run successfully?

Many thanks @yhirose for the quick reply, I really appreciate your time. I got it working but I am not exactly sure how...
I am using Conan but when I checked out your repo and run the test then everything is passing fine:

I got some hints when I run the server and then queried it via curl:


curl: (60) SSL: certificate subject name '192.168.1.108' does not match target host name 'localhost'

**Comment by yhirose** [comment]
@martinpeniak, glad to hear that the problem is gone now!

**Comment by fengmao31** [comment]
it is because the client donnot have the local ca for the server. and it is not in the list of public ca. at last, it will check you ip address in your certification and the real ip in the area network. this is my understanding. you can turn off the verify in the client or set the ca.crt.
