### ISSUE TITLE
Using non-null terminated strings as URLs

### ISSUE THREAD

**Issue by 00ff0000red** [yhirose/cpp-httplib#840]
A good part of the library uses `char const*` and `std::size_t` pairs to determine how far ahead to read in the char buffer, but Server::Get doesn't. Could an overload be introduced, accepting a std::size_t as a second argument, determining the length of the string being passed as the URL?

Personally, I'm using a bunch of heap allocations and memcpy calls in order to create C-style, null terminated strings from my data before using Get.

Implementing this might be problematic, since I'm not sure is std::regex supports something like this.

**Comment by PixlRainbow** [comment]
I think some of the `std::string` interfaces have automatic appending of null terminator?

**Comment by 00ff0000red** [comment]
@PixlRainbow Still causes an unecessary copy of the memory though.
