### ISSUE TITLE
Send a request to another server inside a svr.Post

### ISSUE THREAD

**Issue by DavideCoppola** [yhirose/cpp-httplib#841]
Hello everybody, I'm using the library and I've created a server on a local URL listening on a specific port. This C++ server is in contact with my web app's  front-end running on Node.js and for this it server the front-end app! Now I've created another server written in Python and running on another port on my machine, so now there are two servers as part of my Back-End application. 
I created even the Python server because in a specific request going from my Front-End application to the C++ server i need to send a  further request whit source my C++ server and destination the Python server. Especially, inside the svr.Post request inside the C++ server (located at "localhost:1234") i need to send a request to the Python server (located at "localhost:5000") and wait until the python computation and response in returned, so i can sent the response from my C++ server to the front-end application.
So, how can i send a request from C++ server to Python server inside my svr.Post method?
Thanks to all

**Comment by PixlRainbow** [comment]
just create a `Client` or `SSLClient` object within the request handler, or alternatively you may make it a global object.

**Comment by DavideCoppola** [comment]
@PixlRainbow  Thank you very much, this was so useful for me, I appreciate your response. I'll try to create a Client object inside teh request handler like you mentioned. Thank you very much
