### ISSUE TITLE
Cusom HTTP methods

### ISSUE THREAD

**Issue by aldoshkind** [yhirose/cpp-httplib#847]
Hi!
I would like to use HTTP methods other than currently supported by cpp-httplib. Particularly SUBSCRIBE is demanded.
Is there any opportunity to create some interface allowing to add handlers for custom HTTP methods?

Something like:
```
Server svr;
svr.method("SUBSCRIBE", "/hi", [](const Request &, Response &) {
    ...
});
```

**Comment by yhirose** [comment]
@aldoshkind, thanks for the feedback. I am not planning to add the routing handler support for custom HTTP methods at this point. But, you can do the same with [pre routing handle](https://github.com/yhirose/cpp-httplib#pre-routing-handler). Could you take a look at it to see if it satisfies your need?

**Comment by yhirose** [comment]
@aldoshkind, it seems like the following code needs to modified to allow such custom methods...

https://github.com/yhirose/cpp-httplib/blob/78c474c744a2582ad18cb6d936ab9273fffc6350/httplib.h#L4383-L4386

**Comment by aldoshkind** [comment]
@yhirose Thanks for rapid response! I'll check as soon as possible
