### ISSUE TITLE
SIGPIPE issue

### ISSUE THREAD

**Issue by aldoshkind** [yhirose/cpp-httplib#848]
Hi @yhirose !
Today we faced SIGPIPE issue. I found several closed issues on SIGPIPE problem.
Comments in these issues say that problem is fixed, but I still suffer from SIGPIPE. I reproduced it on 3 machines, all of them are under Ubuntu 18.04.

My attempts to put `signal(SIGPIPE, SIG_IGN);` everywhere I can imagine didnt solve the problem.
Solution was to use MSG_NOSIGNAL as argument to send. I saw proposals to use it in those closed issue and found this proposals to be reasonably rejected. But problems still exist and my proposal is: please consider extending `Server` with ability to provide user-set flags to send to allow usage of MSG_NOSIGNAL.

Here is the code to reproduce (this is variation of sse example):
```cpp
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <cpp-httplib/httplib.h>
#include <iostream>
#include <mutex>
#include <sstream>
#include <thread>

using namespace httplib;
using namespace std;

class EventDispatcher {
public:
	EventDispatcher() {
		id_ = 0;
		cid_ = -1;
	}

	void wait_event(DataSink *sink) {
		unique_lock<mutex> lk(m_);
		int id = id_;
		cv_.wait(lk, [&] { return cid_ == id; });
		if (sink->is_writable()) { sink->write(message_.data(), message_.size()); }
	}

	void send_event(const string &message) {
		lock_guard<mutex> lk(m_);
		cid_ = id_++;
		message_ = message;
		cv_.notify_all();
	}

private:
	mutex m_;
	condition_variable cv_;
	atomic_int id_;
	atomic_int cid_;
	string message_;
};

const auto html = R"(
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>SSE demo</title>
</head>
<body>
<script>
const ev1 = new EventSource("event1");
ev1.onmessage = function(e) {
  console.log('ev1', e.data);
}
</script>
</body>
</html>
)";

EventDispatcher ed;

int main(void)
{
	Server svr;

	svr.Get("/event1", [&](const Request & /*req*/, Response &res)
	{
		res.set_chunked_content_provider("text/event-stream",
										[](size_t /*offset*/, DataSink &sink)
										{
											ed.wait_event(&sink);
											return true;
										 });
	});

	thread t([&]
	{
		while (true)
		{
			this_thread::sleep_for(chrono::seconds(1));
			std::stringstream ss;
			ss << "data: " << "123" << "\n\n";
			ed.send_event(ss.str());
		}
	});

	svr.listen("localhost", 1234);
}

```

You can reproduce the problem by running
```sh
curl http://localhost:1234/event1
```
and cancelling it with Ctrl+C.

Related question: is there opportunity to detect client closed coonection while using chunked_content_provider?

Thanks!

**Comment by yhirose** [comment]
@aldoshkind, you can provide flags with the following symbol. 
https://github.com/yhirose/cpp-httplib/blob/78c474c744a2582ad18cb6d936ab9273fffc6350/httplib.h#L95

**Comment by aldoshkind** [comment]
I found that my local copy of cpp-httplib was outdated and problem was solved in 6adf130bf3c5cc6dddbd378e44e08568eb148a36 by adding CPPHTTPLIB_SEND_FLAGS. Sorry for inconvenience.

But the second question is still pending. @yhirose please advice: how `EventDispatcher` should detect if client closed connection?

**Comment by yhirose** [comment]
As you can see the above code, `is_writable` is used to detect it. It will end up calling this function:
https://github.com/yhirose/cpp-httplib/blob/78c474c744a2582ad18cb6d936ab9273fffc6350/httplib.h#L1802

This is actually kind of a general socket question. You can find much better explanation on web.

**Comment by aldoshkind** [comment]
Yes, I have tried checking `is_writable`, but on my machine it always gives `true` and hence unusable. I think the fact that socket is write ready doesnt guarantee that the connection was not closed by opposite side.
Also,  even if it would guarantee that, socket may change its state between `is_writable` and actual write. Error in `write` leads to stop of calling thread, so `is_writable` will not be called to return false. In this case return value of DataSink's `write` would be useful to detect write errors, please consider changing return type.

I found that `set_chunked_content_provider` has third argument called `resource_releaser` and it is solution to the problem of detecting closed connections.

Thanks alot!

**Comment by yhirose** [comment]
@aldoshkind, thanks for the explanation. I don't fully understand your solution with `resource_releaser`, because it's not meant for such purpose. This is to give a user a place where acquired resource can be released safely like C++ destructor. 
Could you explain how you are able to detect closed socket in this way? Thanks.

**Comment by aldoshkind** [comment]
I use SSE to notify clients on some events. Notifications should not be lost, so I have queue for each client. If client shuts down connection I have to close corresponding queue (otherwise it will grow infinitely) and release other resources.
So solution with `resource_releaser` looks appropriate for the task.
