### ISSUE TITLE
Post with ContentReceiver in Client

### ISSUE THREAD

**Issue by nextfullstorm** [yhirose/cpp-httplib#850]
Hi, is there any way to read POST response in chunks in Client? There is Client::Get with ContentReceiver, but no corresponding Client:Post, or at least I didn't find any. Sometimes it's useful to process data while reading it. My current task involves reading large POST response from another server and writing its chunks to response to Server::Get on _my_ server (REST API proxying with bells and whistles).

**Comment by yhirose** [comment]
@nextfullstorm, thanks for the feedback. I haven't implemented the method. (I have implemented only methods that are need in my projects, otherwise number of all the possible methods will be huge...)

If it's a pretty common usage and many others can benefit from it, I don't mind adding it.

**Comment by yhirose** [comment]
@nextfullstorm, I'll close it since I didn't hear from you. If you still need it, you can try the following. Hope it helps.

```cpp
Request req;
req.method = "GET";
req.path = path;
req.content_receiver = [&](const char *data, size_t data_length, uint64_t offset, uint64_t total_length) {
  ...
  return true;
};

cli.send(req);
```
