### ISSUE TITLE
sent bytes count 

### ISSUE THREAD

**Issue by sashabel** [yhirose/cpp-httplib#852]
Hello, I have a **question**, 
is there a way to get sent bytes count or to evaluate it prior sending ?

**Comment by yhirose** [comment]
@sashabel, could you give me more detail?

**Comment by sashabel** [comment]
Thanks for your fast reply.
Yes, of cause. In my application I want to set maximum bandwidth [bits per sec], (not number of commands). For that I wanted to aggregate bits count I've sent every cycle. How can I get the bytes length of the sent command from the client ? 
(I also use compression so I need the actual count that was sent)

**Comment by yhirose** [comment]
@sashabel, I guess the content receiver could work.
https://github.com/yhirose/cpp-httplib#receive-content-with-a-content-receiver

**Comment by sashabel** [comment]
@yhirose, I am interested in the sender (not the receiver), specifically the exact bytes count in the egress message (after content compression). Can you please explain how can I use suggested solution ?

**Comment by yhirose** [comment]
@sashabel, if you are talking about a client sending data via POST or PUT, you can use one of the followings.
https://github.com/yhirose/cpp-httplib#send-content-with-a-content-provider
https://github.com/yhirose/cpp-httplib#chunked-transfer-encoding-1
`offset` tells you how much data has been sent to the server so far. Hope it helps.

**Comment by sashabel** [comment]
@yhirose , thanks. But my command is built from single part, so the offset is 0. The code I used is:
```C++
std::string commandBodyStr = command.to_json().dump();
cli.set_compress(true);
auto res = cli.Post(
  "/command/raw", commandBodyStr.size() /* = 1380 */,
  [&commandBodyStr](size_t offset, size_t length, DataSink &sink) {
    sink.write(commandBodyStr.c_str() + offset, length);
    /* offset = 0 */
    return true; 
  },
  "application/json");
```

The "Content-Length: 289" in the sent message()after compression). I am interested to get the 289+Headers (after or prior sending)

**Comment by PixlRainbow** [comment]
we don't count the TCP and IP headers at all, because those are handled by the API of the host OS. We do not know what the host OS will try to do, although it may be possible for us to pull in some extra system calls to check.

**Comment by sashabel** [comment]
@PixlRainbow, thanks. Well, the size is useful for me even without these headers (They are pretty same length and I can evaluate them). 
Does it make sense to add transmitted bytes size to `httplib::Result` class ?

**Comment by PixlRainbow** [comment]
You could just rewrite your callback to write a smaller number of bytes to the sink. You do not necessarily need to use the callback's `length` parameter as-is. Afaik the sink will respect the length parameter passed to the `write` call even if it is not the same as the one passed to the callback, and the offset will be incremented accordingly.

**Comment by PixlRainbow** [comment]
@yhirose I think they mean to say that the `offset` and `length` passed reflects the uncompressed data, after httplib performs gzip compression the size is different

**Comment by yhirose** [comment]
@sashabel, it's difficult to add actual sent byte size to `Result`. But adding request headers isn't very hard, So I implemented it. You can now get Content-Length from `Result`. 

https://github.com/yhirose/cpp-httplib/blob/b7566f6961275f465638ac6e80e861e7707a5a5c/test/test.cc#L2631

**Comment by sashabel** [comment]
@yhirose , works perfect. 

**Thanks a lot!**
