### ISSUE TITLE
Compile error with ssl support on visual studio 2017

### ISSUE THREAD

**Issue by crackwei** [yhirose/cpp-httplib#853]
it's a great library. i try to use it in my project. as i test, without ssl support, it can be work good. but once i open ssl support with "CPPHTTPLIB_OPENSSL_SUPPORT", it cannot be compiled ( even the build-in demo ), shows very more error.

My Compile Env:
openssl version : "3.0.0-alpha11-dev"
windows sdk version: 10.0.17763.0
platform toolsets: Visual Studio 2017 (v141)

could you please try it?

![error](https://user-images.githubusercontent.com/10041637/106938235-b288eb80-6759-11eb-85e1-b92ea3e7c917.png)

**Comment by yhirose** [comment]
@crackwei, cpp-httplib only supports the stable version 1.1.1 as described in [README](https://github.com/yhirose/cpp-httplib#ssl-support). Hope it helps.

**Comment by crackwei** [comment]
OK, Thank you.
