### ISSUE TITLE
fatal error: openssl/err.h: No such file or directory 

### ISSUE THREAD

**Issue by ErikDz** [yhirose/cpp-httplib#855]
Hi Im on windows 10 and I get that every time I try to include httplib.
I have installed OpenSSL-Win32

![image](https://user-images.githubusercontent.com/22724935/107249364-375e5880-6a2b-11eb-8772-b13b098b69fa.png)

`source file cannot be opened (error code "openssl/err.h") (dependency of "C:\Users\erikd\Downloads\PityPiton\experimentos\C plus plus\projects\helloworld\httplib.h").`

**Comment by yhirose** [comment]
@ErikDz, I guess your compiler's include directory is not properly set. (Probably lib include directory as well?)
Hope it helps!

**Comment by ErikDz** [comment]
Hi! Thanks for answering!
I use cl.exe to compile, how would I do so with it?

**Comment by PixlRainbow** [comment]
which version of OpenSSL are you using? Some versions do not use the file `openssl/err.h`
