### ISSUE TITLE
Add second argument to httplib::Request::has_param

### ISSUE THREAD

**Issue by 00ff0000red** [yhirose/cpp-httplib#856]
Currently, httplib::Request::get_param_value accepts a char* and a length, but httplib::Request::has_param does not.
Is it possible to do the same for consistency?

**Comment by yhirose** [comment]
@00ff0000red, the 2nd parameter of `httplib::Request::get_param_value` isn't length for the key. It's index for a value for the key. 

Here is the definition of `Headers`. It's not a `map`, but `multimap`, because HTTP allows multiple entries for the same key.
```cpp
using Headers = std::multimap<std::string, std::string, detail::ci>;
```

Hope it helps.

**Comment by 00ff0000red** [comment]
Ah, should've spotted that myself, oops.
