### ISSUE TITLE
Multiple Threads, one Instance per Thread

### ISSUE THREAD

**Issue by Compaile** [yhirose/cpp-httplib#858]
Hi,

When i want to speed up my http requests (i server a lot of results to an rest api).

Currently i use n Threads with 1 httplib client per thread.

Is this recommended/safe?
And if not are there others ways to use multiple threads for client calls?

One note:
     auto n = strm_.read(&byte, 1); in line 1736 returns 0 some times for me

I dont know if this might be caused be the threads paralell access to this libary (however each thread has its own instance)
Maybe some socket race conditions might be created there?

**Comment by yhirose** [comment]
Please check https://github.com/yhirose/cpp-httplib/issues/679. Hope it helps.
