### ISSUE TITLE
Issues with specific server responses

### ISSUE THREAD

**Issue by PazerOP** [yhirose/cpp-httplib#862]
I suspend that something on Steam's end is producing an HTTP response that is invalid somehow, but every other tool seems to handle the response fine. 

Consider the endpoint `https://steamcommunity.com/inventory/76561198127224715/440/2`.

The Insomnia REST client returns the following: 

```
HTTP/1.1 403 Forbidden
Server: nginx
Content-Type: application/json; charset=utf-8
X-Frame-Options: SAMEORIGIN
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Cache-Control: no-cache
Content-Encoding: gzip
Vary: Accept-Encoding
Content-Length: 24
Date: Sun, 14 Feb 2021 15:51:33 GMT
Connection: keep-alive
Set-Cookie: sessionid=7a9968d7576ab814734b938c; Path=/; Secure; SameSite=None
Set-Cookie: steamCountry=US%7C9ec50b59a3286297e3126f4097138248; Path=/; Secure; SameSite=None

null
```

Here, I attempt to access the same page with cpp-httplib:

```cpp
#define CPPHTTPLIB_OPENSSL_SUPPORT 1

#include <iostream>

#include "httplib.h"

int main()
{
	httplib::SSLClient client("steamcommunity.com", 443);

	auto result = client.Get("/inventory/76561198127224715/440/2");
	std::cout << "error: " << result.error() << std::endl;
}
```

The result is always `error: 4` which corresponds to `Error::Read`, when the response should be HTTP error 403.

**Comment by yhirose** [comment]
@PazerOP, I guess you need ZLIB support because the Insomnia REST client result contains the following header:

```
Content-Encoding: gzip
```

Please check [here](https://github.com/yhirose/cpp-httplib#zlib-support) to enable ZLIB support.
Hope it helps.

**Comment by PazerOP** [comment]
I see. It would be helpful if there was a more specific error when an unsupported content type was encountered.
