### ISSUE TITLE
reference to 'rand' is ambiguos

### ISSUE THREAD

**Issue by GopherJ** [yhirose/cpp-httplib#863]
![image](https://user-images.githubusercontent.com/33961674/108231982-45c01900-717d-11eb-89fe-28c0fb043c2d.png)

Hi, I had an issue while compiling cpp-httplib, do you have an idea on this? I use https and the version of cpp-httplib is the latest release on github

**Comment by GopherJ** [comment]
there are other `rand` candidates it seems:

![image](https://user-images.githubusercontent.com/33961674/108232213-7e5ff280-717d-11eb-8126-a4f65b73f044.png)

**Comment by GopherJ** [comment]
I fixed it by prepend `std::`

**Comment by yhirose** [comment]
@GopherJ, thanks for the report!
