### ISSUE TITLE
invalid url will cause segmentfault

### ISSUE THREAD

**Issue by GopherJ** [yhirose/cpp-httplib#864]
Hi, I've tried to put some invalid urls, it looks like cpp-httplib will throw segement fault errors
![image](https://user-images.githubusercontent.com/33961674/108359243-bb35f300-722a-11eb-852f-f9fa73c89a42.png)

**Comment by yhirose** [comment]
@GopherJ, thanks for the feedback, but it's too little information...

**Comment by GopherJ** [comment]
@yhirose Hi I didn't put extra info because I can reproduce it using the example:

```
httplib::Client cli("https://cpp-httplib-server.yhirose.repl.co");
```

**Comment by GopherJ** [comment]
@yhirose I'm able to reproduce using the following code:

```
#include <iostream>
#define CPPHTTPLIB_OPENSSL_SUPPORT
#include "../include/httplib.h"

int main() {
  httplib::Client cli("https://cppxxhttplib-server.yhirose.repl.co");

  auto res = cli.Get("/hi");
  std::cout << res->status << std::endl;
  std::cout << res->body << std::endl;
}
```

**Comment by GopherJ** [comment]
ok my fault I should check `.error()`, while checking with gdb the segement fault error comes from my code. thanks
