### ISSUE TITLE
Ability for Graceful Shutdown

### ISSUE THREAD

**Issue by Fransferdy** [yhirose/cpp-httplib#867]
I'm currently using this server as basis for my microservices and I really like it, but I feel I might have issues in the near future with my CI/CD pipeline in production, specifically in the moment of updating the services. It would be nice if a Graceful shutdown would be added. (something like, shutdown listening the socket while still finishing the delivery of the current http requests)

**Comment by yhirose** [comment]
@Fransferdy, thank you for your feedback. cpp-httplib server does the graceful shutdown if a user uses the built-in default `ThreadPool` task queue. Please let me know if it doesn't work on your environment. Thanks!

**Comment by jwdinius** [comment]
I have a similar question and, I'm afraid, your answer is unclear to me @yhirose.  It looks as though there is a `shutdown` method defined for the `ThreadPool` class, however the `Server` member variable `new_task_queue` does not call it when `Server::stop()` is invoked.  Is this the designed behavior?

What I am looking for is a `kill` switch that I can call from a separate thread (i.e. one different than the thread of execution where `Server::listen(addr, port)` blocks).  I don't see any such functionality and assume that omission was deliberate.  Is that the case?

My use case is simple: I have built a simple, single testbench application that defines and launches an instance of `Server` in a separate thread.  On the main thread of execution, I have a `Client` that talks to that server.  I am unsure of how to shutdown the server and execute the main thread cleanly.  Currently, I join the thread where the `Server::listen(addr, port)` call is blocking and then my main thread is blocked at that point.  How can I go about exiting cleanly from this point?

**Comment by yhirose** [comment]
@jwdinius, `shutdown` method in `TreadPool` isn't for socket shutdown, but thread pool shutdown. The socket shutdown is done via `Server::stop()` method which will eventually end up calling `shutdown` system call in `shutdown_socket` function.

Anyway, you can see a number of examples in `test/test.cc` to launch a server in a separated thread and stop it from the main thread with `Server::stop()`.

Hope it helps!

**Comment by jwdinius** [comment]
@yhirose thanks much!  I was able to find what I needed.

For newcomers to this thread (pun intended), the following [example](https://github.com/yhirose/cpp-httplib/blob/d87d0672a8e0f3695f168ff1f55028f6fbe4aedf/test/test.cc#L860) from `test/test.cc` might be illustrative.  It worked for me :)
