### ISSUE TITLE
Statically serving individual files

### ISSUE THREAD

**Issue by 00ff0000red** [yhirose/cpp-httplib#869]
The library offers mounting directories to serve from, but is there a simple way to link only an individual file?

Example:
```c++
server.static_serve_individual_file("./public/index.xhtml"s, "/index"s);
```
?

**Comment by yhirose** [comment]
@00ff0000red, no. I haven't seen such a feature in http libraries like express.js or sinatra though...

**Comment by 00ff0000red** [comment]
@yhirose

sinatra: https://stackoverflow.com/questions/2437390
express.js: https://stackoverflow.com/questions/11473607

They both offer a sendfile to compensate.

Also, apparently, express.js allows this:
```js
app.use("/index", "./public/index.xhtml");
```

But, the fact that people asked those SO questions does indicate that this is a commonly encountered situation by users of HTTP libraries.

And lastly, [actix](https://actix.rs), one of the most popular Rust HTTP libraries, has something for this: <https://actix.rs/docs/static-files>.

**Comment by yhirose** [comment]
@00ff0000red, I don't think we can do `app.use("/index", "./public/index.xhtml");`. Where did you find the information? I can't find it in [the node express.js document](https://expressjs.com/en/4x/api.html#app.use)...

**Comment by 00ff0000red** [comment]
@yhirose I got that right off of the SO question that I had linked.

**Comment by 00ff0000red** [comment]
Update: I tried it myself, guess it doesn't work after all, but, this is likely a common user situation, to just want to serve a single file.

In my situation, all I wanted to do was serve a favicon for browsers, without a bunch of boilerplate code, when we realized that the library didn't have anything for such operation, so I setup a filestream and streamed through the `DataSink::os`.

**Comment by yhirose** [comment]
@00ff0000red, the 'send file' approach is one-liner and simpler though, could the following work for you for now?

```cpp
svr.Get("/favicon.ico", [](const httplib::Request &, httplib::Response &res) {
  std::string out;
  httplib::detail::read_file("./path/to/favicon.ico", out);
  res.set_content(out, "image/x-icon");
});
```

**Comment by 00ff0000red** [comment]
Well, if I wanted to serve 2 unique files, I'd need a small loop or I'd have 10 unrolled LoC, for such a simple task.

And it'd make for a simple "hello world," beginner setup:
```c++
svr.set_mount_point("/public", "./www");

svr
  .mount_file("/", "./path/to/index.xhtml")
  .mount_file("/favicon.ico", "./path/to/favicon.ico")
  .listen("0.0.0.0", 8080);
```

and you have a small static server setup.

But, personally, I use a wrapper class, so I can just implement it myself easily... so I guess I'm fine.
