### ISSUE TITLE
SSLClient not verifying domain name in the certificate

### ISSUE THREAD

**Issue by aric-driveai** [yhirose/cpp-httplib#87]
Hi,

when I connect to an https server for which the certificate does not match the domain name, everything seems to be working correctly.
When I use curl, I get an error like this one:

```
curl -vvv https://domain.com/
curl: (51) SSL: no alternative certificate subject name matches target host name 'domain.com'
```

is there any way to verify the domain name using this library?

**Comment by yhirose** [comment]
Need supporting wildcard when verifying server certificate.

**Comment by yhirose** [comment]
@aric-driveai, I finally supported this feature.

```cpp
SSLClient cli("www.youtube.com");
cli.set_ca_cert_path("./ca-bundle.crt");
cli.enable_server_certificate_verification(true);
```
