### ISSUE TITLE
A non-blocking implementation

### ISSUE THREAD

**Issue by rtrahan504** [yhirose/cpp-httplib#875]
Is there any interest in making the server-side of this library non-blocking? I have a fork which was a heavy rework of this lib. I can receive an http request and hold a reference to the request and keep it open for as long as I want. This is done by the user's httplib::Handler receiving a shared_ptr to the Request-Response pair. While the request is open, I can write from any other thread to the httplib::Response using the content provider. When the content provider is done, the request is closed automatically. For the duration of the request being open, none of the server threadpool threads are blocked. This allows me to have 10,000's of connections simultaneously open even though there may only be 8 threads servicing those requests.

**Comment by yhirose** [comment]
@rtrahan504, thanks for the feedback! I am not interested in making this library non-blocking at this point though, I am interested in how it can be done. Have you ever taken a look at [this](https://github.com/skalenetwork/skaled/issues/219)? They also made this library non-blocking with libuv in a fantastic way.

**Comment by rtrahan504** [comment]
I'll get it uploaded soon and post a link here. Essentially, I revised the call stack that originates at [Server::process_and_close_socket](https://github.com/yhirose/cpp-httplib/blob/ff813bf99d3402adafd4141b660ed2313d27f7a6/httplib.h#L5124). The resources used in that call stack are instead encapsulated in an object. That let me call the stuff like process_request, write_response, write_content, and write_content_chunked as individual tasks in the thread pool instead of one task in the thread pool. The object with the resources for these calls is held in a shared_ptr so it can be moved from thread to thread.

**Comment by rtrahan504** [comment]
The biggest update is in write_content_chunked. I changed the [while loop](https://github.com/yhirose/cpp-httplib/blob/ff813bf99d3402adafd4141b660ed2313d27f7a6/httplib.h#L3104) to just an if statement. That lets me call content_provider once, let the thread return to the pool, then call content_provider again later.

**Comment by yhirose** [comment]
@rtrahan504, great! Is it possible to send a pull request, so that we can confirm that the works on the current unit test suite. Thanks!

**Comment by prenex** [comment]
I think this would have been useful to have. Thinking about maybe using something like this not just for REST, but for general web serving and I know it is already good, but non-blocking is much leaner. I hope "heavy fork" will be available somewhere ;-)

**Comment by rtrahan504** [comment]
[Here is my update if you want to take a look.](https://github.com/rtrahan504/cpp-httplib/tree/nonblocking_server)

This is an update to the original cpp-httplib to enable non-blocking, long-standing transaction with a client. This update only includes the server code and removes all client capabilities. Additionally, the SSL support is untested in this fork. The non-blocking and scaling has worked well in my tests so far. This server is serving as the back-end of an http server for a proprietary javascript Angular front-end application.

Apologies, but the original code I had was a bit dated from your current repo, so some of your updates may not be included in this from when I forked. Also, to do my reworking I split the library into a couple more headers and cpp files, and formatting isn't consistent yet.

**Comment by yhirose** [comment]
@rtrahan504, I put a label 'information' and adjusted the title, so that others can benefit from your implementation. Thanks!

**Comment by rtrahan504** [comment]
Glad to contribute!

I thought I'd point out one main different when using this new version.

```
using Handler = std::function<void(const Request&, Response&, std::shared_ptr<Connection>)>;
using HandlerWithContentReader = std::function<void(const Request&, Response&, std::shared_ptr<Connection>, const ContentReader& content_reader)>;
```

The handlers for requests include a 3rd argument `std::shared_ptr<Connection>`. That Connection object has a method `Connection::SetUsingThreadPool(bool val);` Giving false means that when the handler function returns, the Connection will not take any more actions in the Server's thread pool. It would be up to the user's code to call `Connection::Step()` at some later point in time to continue handling the request with a content provider. You can think of every time you call Step it's a like another loop in [this while loop](https://github.com/yhirose/cpp-httplib/blob/ff813bf99d3402adafd4141b660ed2313d27f7a6/httplib.h#L3104). The result of calling step is the content provider is invoked again until the content provider indicates that the response is "done."

Eventually I'll add an example to the repo.

**Comment by blldce** [comment]
Is there any updates regarding support async for client too?
