### ISSUE TITLE
Cookies header

### ISSUE THREAD

**Issue by Planum** [yhirose/cpp-httplib#879]
Hi,
Do You plan add function for server part, with  create cookie header?
Now I have problem when I use this:
res.set_header("Set-Cookie: Basic", "1234");

In website a Get:
Set-Cookie: Basic: 1234  .. to many colon was add

**Comment by yhirose** [comment]
@Planum, sorry that I am not planning to make a method for cookie, because it's just a HTTP header.
`set_header` takes a key and a value, and `Set-Cooike: Base` isn't a correct HTTP header key. 
Hope it helps.

**Comment by Planum** [comment]
You are absolutely right! My mistake! Forgive me for taking your time!

**Comment by lionkor** [comment]
They're actually much more than that! As you probably know, they *can* be semicolon-separated key-value pairs, which means you *always* need to write a custom parser every single time.

Would this be interesting for httplib? I'd be down to write one.
