### ISSUE TITLE
Downloading binary files

### ISSUE THREAD

**Issue by hasanenalbana** [yhirose/cpp-httplib#88]
Hi,

The library interface is great and clean, but wondering to fetch binary files into the result body?

**Comment by yhirose** [comment]
@hasanenalbana, yes. you can see [the test case](https://github.com/yhirose/cpp-httplib/blob/master/test/test.cc#L121-L142).

Also the following stackoverflow post could be helpful for you.
https://stackoverflow.com/questions/12335546/when-a-web-server-returns-a-jpeg-image-mime-type-image-jpeg-how-is-that-encod

**Comment by QuantScientist** [comment]
In this example (multi part files):
```
auto size = req.files.size();
auto ret = req.has_file("name1");
const auto& file = req.get_file_value("name1");
```
How do I read an image sent by POST into an OpenCV image on the server side? 

Thanks,

**Comment by yhirose** [comment]
@hasanenalbana, thanks for the question, but I can't answer your question because I don't know anything about OpenCV... The binary data is supposed to be in `req.body` from `file.offset` through `file.offset + file.length`.
