### ISSUE TITLE
How to catch exception in ContentProvider when I try to response with chunked data?

### ISSUE THREAD

**Issue by ZacheryGuan** [yhirose/cpp-httplib#881]
My server needs to process received data when I prepare response in `ContentProvider` function. If the server receives correct parameters in the body message, it returns some results in stream. However, if the params are invalid, how can the server return error response with error message?

I tried to catch exception around `res.set_chunked_content_provider` but it does not work. 

Here is a piece of code explaining my problems.
```cpp
svr.Post("/test_chunk", [&](const Request &req, Response &res, const ContentReader &content_reader) {
  // read body content
  std::string body;
  content_reader([&](const char *data, size_t data_length) {
    body.append(data, data_length);
    return true;
  });

  // try to throw an exception in the content provider if the arguments in body are invalid.
  res.set_chunked_content_provider("text/plain",
                                   [](size_t offset, httplib::DataSink &sink) {
                                     std::string processed_result = some_process(body);
                                     if (processed_result.empty()) {
                                       throw std::invalid_argument("post body invalid.")
                                     } else {
                                       sink.write(processed_result);
                                       sink.done();
                                     }
                                   });

});
```

**Comment by PixlRainbow** [comment]
Thrown exceptions are not automatically inserted into the response stream. You must explicitly indicate that you wish to send a HTTP error response by setting res.status and res.body.
Unfortunately, the design of HTTP itself (not just our library) fundamentally does not allow changing the response status after you have already begun sending the response body. You may only send an error response right from the start of the response, or you may terminate the response stream prematurely without error.
You could call some_process in the content reader, or call some_process directly in the request handler body, then store the result and send the response as appropriate afterwards. OR you can return false in the chunked content provider to terminate the response writing.
<hr>
Another unrelated issue is that you are not really using using the streaming functions in a meaningful way. You are still processing the entire request and response body in memory in a single call, so streaming will not give you any performance benefit. I am guessing this is just example code and you intend to change it later.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the excellent comment.

@ZacheryGuan, hope the following helps.

```cpp
svr.Post("/test_chunk", [&](const Request &req, Response &res,
                            const ContentReader &content_reader) {
  std::string body;
  content_reader([&](const char *data, size_t data_length) {
    body.append(data, data_length);
    return true;
  });

  auto processed_result = some_process(body);
  if (processed_result.empty()) {
    res.status = 400;
    res.set_content("post body invalid.", "text/plain");
  } else {
    res.set_chunked_content_provider(
        "text/plain",
        [processed_result](size_t offset, httplib::DataSink &sink) {
          sink.write(processed_result);
          sink.done();
          return true;
        });
  }
});
```

**Comment by ZacheryGuan** [comment]
Get your point. Thanks for help

----
The code example does not process data in stream to provide a minimum piece.
