### ISSUE TITLE
Compile error on Android

### ISSUE THREAD

**Issue by fasiondog** [yhirose/cpp-httplib#884]
I try to add httplib to xmake repository (https://github.com/xmake-io/xmake-repo/pull/338),  but I got compilation errors on Android platform ([https://github.com/xmake-io/xmake-repo/pull/338/checks?check_run_id=2212629480](https://github.com/xmake-io/xmake-repo/pull/338/checks?check_run_id=2212629480)) , Maybe need "#include <ifaddrs.h>" on android.

erros:

checkinfo: ...amdir/core/sandbox/modules/import/core/tool/compiler.lua:84: @programdir/modules/core/tools/gcc.lua:481: /home/runner/.xmake/packages/h/httplib/0.8.5/37e2699c83df47dc9525f5d4a6aec425/include/httplib.h:2166:3: error: use of undeclared identifier 'getifaddrs'; did you mean 'ifaddrs'?
  getifaddrs(&ifap);
  ^
/home/runner/work/xmake-repo/xmake-repo/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/ifaddrs.h:45:8: note: 'ifaddrs' declared here
struct ifaddrs {
       ^
In file included from /dev/shm/.xmake1001/210328/_5F8CB1C8DBC244208A5C7BED9B0F9840.cpp:2:
/home/runner/.xmake/packages/h/httplib/0.8.5/37e2699c83df47dc9525f5d4a6aec425/include/httplib.h:2173:11: error: use of undeclared identifier 'freeifaddrs'
          freeifaddrs(ifap);
          ^
/home/runner/.xmake/packages/h/httplib/0.8.5/37e2699c83df47dc9525f5d4a6aec425/include/httplib.h:2179:3: error: use of undeclared identifier 'freeifaddrs'
  freeifaddrs(ifap);
  ^
3 errors generated.

**Comment by yhirose** [comment]
@fasiondog, thank you for the report. I have never built cpp-httplib on Android platform, and I am not planning to support it personally since I don't have the environment. Could you fix the build error and send a pull request? Thanks a lot!

**Comment by fasiondog** [comment]
I don't have android enviroment too. I'll try again later to fix it

**Comment by yhirose** [comment]
@fasiondog, please let me know when you are ready, then I'll reopen this issue. Thanks!

**Comment by PixlRainbow** [comment]
From a brief google search:

> With Android 7.0 Nougat (API 24) and above, `ifaddrs.h` is supported natively, compatible with desktop Linux
> 
> For older API level, you will need to manually copy and include google's header-only adapter from the Android OS source code.

Details: https://stackoverflow.com/a/57112520

**Comment by waruqi** [comment]
> From a brief google search:
> 
> > With Android 7.0 Nougat (API 24) and above, `ifaddrs.h` is supported natively, compatible with desktop Linux
> > For older API level, you will need to manually copy and include google's header-only adapter from the Android OS source code.
> 
> Details: https://stackoverflow.com/a/57112520
> 
> From your debug logs:
> 
> > `... -D__ANDROID_API__=21 ...`
> 
> xmake was configured to target minimum API level 21

It's right, we need send netlink udp msg to wrap it if we want to use ifaddrs below level 21. like this https://github.com/tboox/tbox/blob/master/src/tbox/platform/linux/ifaddrs2.c

But this needs to do more.

**Comment by fasiondog** [comment]
Thanks all
