### ISSUE TITLE
fileserver：how to set the header to make the Google browser popup a download file dialog?

### ISSUE THREAD

**Issue by bingzhe123** [yhirose/cpp-httplib#885]
Hi：
   I make a http server with httplib, everything is well except download file. I don't know how to set the header in server when processing download command.  I send a request with "Get" method by Google browse, **but the browser don't popup the downloading dialog**. Is anything i missed?
In the server I write as this:

`
void HttpsServer::UpLoadHandler(const Request& req, Response& res)
{
    std::cout<<"***********UpLoadHandler----UID:" << std::endl;
    auto& header = req.headers;
    auto it = header.find("UID");
    string sUID;
    if (it != header.end())
    {
        sUID = it->second;
    }
    else
    {
        res.set_content("File not exist", "text/plain");
        return;
    }
    std::cout << "***********UpLoadHandler----UID:" << sUID<< std::endl;
    auto sPath = m_spDBOperator->GetDataPath(sUID);
    std::cout << "***********UpLoadHandler----UID:" << sPath << std::endl;
    auto buffer = _getcwd(NULL, 0);
    FILE* pFile;
    fopen_s(&pFile, sPath.c_str(), "rb");
    if (pFile == nullptr)
    {
        std::cout << "Open File Failed,error code = " << errno << std::endl;
        res.status = 404;
        return;

    }
    res.headers.emplace("Content-Disposition", "attachment; filename=1502849449726.xlsx;");

    res.headers.emplace("Content-Type","application/force-download");//4

    _fseeki64(pFile, 0, SEEK_END);
    auto iFileLength = _ftelli64(pFile);
    _fseeki64(pFile, 0, SEEK_SET);
    //fread(pData, sizeof(char), iFileLength, pFile);
 
    const size_t DATA_CHUNK_SIZE = 1024;
    res.set_content_provider(iFileLength, "application/octet-stream", [pFile, DATA_CHUNK_SIZE](size_t offset, size_t length, DataSink& sink)
    {
        FILE* _pFile = (FILE * )pFile;

        const size_t DATA_CHUNK_SIZE = 1024;
        char buffer[DATA_CHUNK_SIZE];
        //char* pData = new char[DATA_CHUNK_SIZE];
        auto iSize = std::min(length, DATA_CHUNK_SIZE);
        fread(buffer, sizeof(char), iSize, pFile);

        sink.write(buffer, std::min(length, DATA_CHUNK_SIZE));
        //delete[] pData;
        return true; // return 'false' if you want to cancel the process.
    },
    [pFile] { fclose(pFile); });
}
`
**The browser respoand as :**
![image](https://user-images.githubusercontent.com/41856595/112986160-bce0c800-9193-11eb-9022-86e82d10cf48.png)

**And The file content  In Body** . My test file with contents  "test4______________sfsfasf"

![image](https://user-images.githubusercontent.com/41856595/112986458-1b0dab00-9194-11eb-8f5a-375fc5175508.png)

**Comment by yhirose** [comment]
@bingzhe123, thanks for the feedback. But it's beyond a questions of cpp-httplib, but just a HTTP general question. I am not giving any personal support for other persons' projects... Thanks for your understanding!
