### ISSUE TITLE
[httplib::Server] Is there any way to get the request IP?

### ISSUE THREAD

**Issue by osdeverr** [yhirose/cpp-httplib#886]
I'm trying to implement per-IP rate-limiting in my HTTP API server. From what I can see, there's no way to get the IP the request was sent from in request handlers. If that's even technically possible (I'm not really into HTTP and networking in general, you know), I suggest you expose the request IP to handlers. Thank you.

**Comment by yhirose** [comment]
@osdeverr, hope #443 will help you.
