### ISSUE TITLE
Get website Contents

### ISSUE THREAD

**Issue by hot202xu1** [yhirose/cpp-httplib#887]
Is there anyway this library (as a server) can get a web site and then edit it so if I go to the library port it will show the original website with my added on HTML?

a example would be with google.com and add some text under the search bar.

**Comment by yhirose** [comment]
@hot202xu1, that's not a question for cpp-httplib. I don't have enough knowledge to answer your question. Sorry about that...

**Comment by hot202xu1** [comment]
@yhirose 
Ok thanks. 
can this library copy a website and then host it on its own server?

**Comment by PixlRainbow** [comment]
yes
inside your server's request handler, create a http client to GET the original webpage

**Comment by hot202xu1** [comment]
@PixlRainbow 
Thank you does this also work if the website is using JavaScript?
Is there any examples doing this. Thanks.

**Comment by PixlRainbow** [comment]
```cpp
// ...
SSLClient cli("google.com");
cli.set_keep_alive(true);
// ...
svr.get(".*", [](const Request& req, Response& res){
    auto googleres = cli.get(req.path, req.headers);
    res.set_content(googleres->body, googleres->get_header_value("Content-Type"));
    res.status = googleres->status;
});
```
You will also need to copy the response headers (not shown here).
It may also be possible to do `res = *googleres` directly, but you may encounter memory issues.

Whether the website will continue to work if it is using JavaScript will depend entirely on how the JavaScript is written. I cannot answer that question beyond simply stating that httplib is a http protocol-level library, while JavaScript works on the browser/application-level. If you want to manipulate the JavaScript yourself or call another library to do it, it will be beyond the scope of this issue. You may encounter domain name issues, in which case you may also need to use a custom DNS server.

**Comment by hot202xu1** [comment]
@PixlRainbow 
Thanks for the reply’s
I’m getting a error
No instance of overloaded function SSLClient::Get

**Comment by PixlRainbow** [comment]
Sorry. It should be capitalized `Get`. Please read the readme.md
