### ISSUE TITLE
client reponse 302

### ISSUE THREAD

**Issue by hanyanLWD** [yhirose/cpp-httplib#888]
when i use client.post()to get response，but i get status=302
in my code
some code:
//url = "http://xxxx.com/xxxxx"

httplib::Client cli("http://xxxx.com");
string COST_SVC="/xxxxx";
cli.Post(COST_SVC.c_str(), headers, data,"application/json");

**Comment by PixlRainbow** [comment]
HTTP 302 response is normal and just means redirect. The exact reason of the response is dependent entirely on the application server.
You may either [enable automatic redirection](/yhirose/cpp-httplib#redirect) or you can follow the redirect manually by initiating a new GET request on the path in the `location` header in the first response.
