### ISSUE TITLE
undefined reference to `OPENSSL_sk_num'

### ISSUE THREAD

**Issue by juanjo75es** [yhirose/cpp-httplib#895]
I get that error when trying to link to openssl 1.1.1h. With openssl1.0 it says I need openssl1.1.1
_undefined reference to `OPENSSL_sk_num'_

I have seen an old issue asking what openssl version to install and the answer was 1.0 but seems that answer is outdated, so what version should I install?

**Comment by yhirose** [comment]
Please see the information [here](https://github.com/yhirose/cpp-httplib#ssl-support) in README.
