### ISSUE TITLE
How to add more than 1 header

### ISSUE THREAD

**Issue by oofsamy** [yhirose/cpp-httplib#896]
Sorry if this issue was a waste, but I've been having a go at every http and/or websocket lib I could find, this is the one I have best luck with, how can I send multiple things in headers, as in your post example, you only mention 1 thing in headers and it's a string, I need to have Authorization and Content-type in mine. (I'm pretty new to C++)

**Comment by yhirose** [comment]
@oofsamy, here is an example.

```cpp
httplib::Headers headers = {
  { "Accept-Encoding", "gzip, deflate" },
  { "Another-Header1", "value" },
  { "Another-Header2", "value" },
};
auto res = cli.Get("/hi", headers);
```

Hope it helps!
