### ISSUE TITLE
Please help me, i'm newbie in c++

### ISSUE THREAD

**Issue by pathawee1993** [yhirose/cpp-httplib#898]
Hello everyone,
i have ubuntu-server and try to use httplib with vscode, but the problem is that vscode can't find following library:
#include <arpa/inet.h>
#include <cstring>
#include <ifaddrs.h>
#include <netdb.h>
#include <netinet/in.h>
#ifdef __linux__
#include <resolv.h>
#endif
#include <netinet/tcp.h>
#ifdef CPPHTTPLIB_USE_POLL
#include <poll.h>
#endif
#include <csignal>
#include <pthread.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <unistd.h>

using socket_t = int;
#define INVALID_SOCKET (-1)
#endif //_WIN32

#include <algorithm>
#include <array>
#include <atomic>
#include <cassert>
#include <cctype>
#include <climits>
#include <condition_variable>
#include <errno.h>
#include <fcntl.h>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <list>
#include <map>
#include <memory>
#include <mutex>
#include <random>
#include <regex>
#include <sstream>
#include <string>
#include <sys/stat.h>
#include <thread>
#include <set>

how could i fix this issue :D  thank you so much

**Comment by yhirose** [comment]
@pathawee1993, this issue has nothing to do with cpp-httplib itself, but how to include header files. Please check your compiler option such as `-I`. Hope it helps.

**Comment by PixlRainbow** [comment]
I don't think you have actually installed a compiler yet @pathawee1993
