### ISSUE TITLE
Does space matter? using udl::operator""_;

### ISSUE THREAD

**Issue by MugiwaraJAK** [yhirose/cpp-httplib#899]
Is this correct having definition with a space and directive without? 

I don't know if this is a problem with syntax or just an issue with eclipse. 

```
namespace udl {

inline constexpr unsigned int operator"" _(const char *s, size_t l) {
  return str2tag_core(s, l, 0);
}

} // namespace udl
```
`
  using udl::operator""_;
`

**Comment by yhirose** [comment]
@MugiwaraJAK, please see #865. clangformat doesn't put a spece between `""` and `_`. It's totally legal according to C++ spec, but some older compilers incorrectly report it as an error. Hope it helps.
