### ISSUE TITLE
SIGPIPE (signal SIGPIPE) after some time working

### ISSUE THREAD

**Issue by DraTeots** [yhirose/cpp-httplib#9]
Having a pretty simple server, which is set up very close to the examples. 

After some time of fine running,  it just starts failing with SIGPIPE here:

```
inline int SocketStream::write(const char* ptr, size_t size) // ptr = "Connection: close\r\n"
    {
        return send(sock_, ptr, size, 0);
    }
```

```
Linux 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
```
Update:
Sometimes it runs really long without it. So one can say, that sometimes it is not happening.

**Comment by yhirose** [comment]
@DraTeots, I added the code to ignore SIGPIPE at e4ef0828b097eb52afc20d3accd675e5a0ab650a.
Could you check if the commit fixes the problem on your machine?

https://stackoverflow.com/questions/108183/how-to-prevent-sigpipes-or-handle-them-properly#answer-108192

**Comment by DraTeots** [comment]
I actually found the same stackoverflow QA yesterday and set the same `signal(SIGPIPE, SIG_IGN);` but in my code. It worked fine since then. So I think the issue is fixed. 

But now , as cpp-httplib is updated, and will let it work for the weekends. And see what will happend.

**Comment by yhirose** [comment]
@DraTeots, thanks for your contribution!
