### ISSUE TITLE
How to set timeout for sink.write() in chunked response?

### ISSUE THREAD

**Issue by ZacheryGuan** [yhirose/cpp-httplib#900]
I found sometimes doing `sink.write()` in` set_chunked_content_provider` will block the program. I guess it may caused by some network issues like unstable connection. How to set a timeout or catch an exception to avoid this kind of block?
I've tried set_write_timeout. But it does not work.

**Comment by yhirose** [comment]
@ZacheryGuan, `set_write_timeout` is the one to set timeout sec/usec. Since `sink.write()` will end up calling `select_write()`, could you take a look at the code in the function to get more information? If `select` system call doesn't work on the OS that you are working on, you may want to try `poll` with CPPHTTPLIB_USE_POLL.

https://github.com/yhirose/cpp-httplib/blob/faa5f1d8023746a3da9f275c51867ded2a672ee9/httplib.h#L1849-L1875

Hope it helps.

**Comment by ZacheryGuan** [comment]
I've tried CPPHTTPLIB_USE_POLL and it will also block. By debugging the program, I found the program stucks here:
https://github.com/yhirose/cpp-httplib/blob/faa5f1d8023746a3da9f275c51867ded2a672ee9/httplib.h#L4139-L4140

**Comment by yhirose** [comment]
@ZacheryGuan, thanks for the information. Do think that it/s it easy to reproduce the condition on someone's machine like my machine? Otherwise, it's too hard for me to debug it. Or could you try to fix it on your machine and send a pull request? Thanks!

**Comment by ZacheryGuan** [comment]
Sorry for the inconvenience. To reproduce this, it may require additional network components, a load balancer in my case. 

Generally, I need to transfer a lot data (like 1M) to the client. The client is not reading but its receive buffer is full. In the meantime, the server's send buffer is also full. The socket `send` will block under such circumstance.

I found [a helpful post discussing about this](https://www.softlab.ntua.gr/facilities/documentation/unix/unix-socket-faq/unix-socket-faq-2.html). You can locate related discussion by searching `The sender blocks when the socket send buffer is full, so buffers will be full at both ends.` in the browser.

**Comment by yhirose** [comment]
@ZacheryGuan, sorry that the helpful post that you mentioned is reported as "Your connection is not fully secure" on my Chrome... I feel like it's a general socket issue which can happen in whatever HTTP libraries. Could you try with other HTTP client like curl to verify it on your machine? Thanks!

**Comment by ZacheryGuan** [comment]
Thanks for your opinion! Though I have not tried other http server lib, I also feel like this may be a general socket issue. 
I have managed to reproduce it using following code. The server writes big chunk(like 100K) of data and the client is not reading socket buffer. 
https://github.com/ZacheryGuan/cpp-httplib-900/tree/main

After running the server and the client, the server only outputs 4 lines on my machine, while the server should print 1024*1024 lines:
```
write 0 th
write 1 th
write 2 th
write 3 th
write 4 th
```
----

BTW, an unrelated question: what will happen when many clients send requests simultaneously to a server using only 1 thread (by `svr.new_task_queue = [] { return new httplib::ThreadPool(1); };`)? It seems that the server only responses the first request and ignores the others. The server will recover to listen until the first response finishes.

**Comment by yhirose** [comment]
@ZacheryGuan, thanks for the sample code. I am able to reproduce the problem on my macOS. I'll take a look at it when I have time. Thank you!

**Comment by yhirose** [comment]
@ZacheryGuan , I made some experimental change [here](https://github.com/yhirose/cpp-httplib/pull/907/files). Could you try the version when you have time to see if the change fixes the problem on your environment? Thanks a lot!

**Comment by ZacheryGuan** [comment]
@yhirose, I will try it next Monday. Thanks for your effort!

**Comment by ZacheryGuan** [comment]
It fixes the problem in my case. Thanks!
Can I get a status from `sink.write()` to know if I have written to the socket successfully? Now I temporarily use `sink.is_writable()` after `sink.write()` to check that status.

**Comment by yhirose** [comment]
@ZacheryGuan, I changed it to return a boolean value from `write_data`. The return value is not the same as from `is_writable`, but I think that's what you really need.

**Comment by ZacheryGuan** [comment]
@yhirose, thank you! IMHO, the readme could also mention the new feature, the return value of `wirte_data`.
