### ISSUE TITLE
Very long connection, when the server binds to "0.0.0.0" and the client connects to "localhost".

### ISSUE THREAD

**Issue by vlad-mal** [yhirose/cpp-httplib#902]
OS: Win10x64 Pro, MSVS-2019 (CE).
We are talking specifically about the long time operation of the network connection, that is, in fact, about the first GET request (subsequent requests are completed faster, especially when keep alive is ON)

Server:
```
#include <httplib.h>
namespace htl = httplib;
int main()
{
	htl::Server srv;
	srv.Get(R"(/id=(\d+))", [](const htl::Request& req, htl::Response& res) {
		auto result = "Echo " + req.matches[1].str();
		res.set_content(result, "text/plain");
	});
	srv.listen("0.0.0.0", 8080);
}
```
Client:
```
#include <httplib.h>
#include <chrono>
namespace htl = httplib;

int main()
{
	htl::Client cli("localhost", 8080);
	auto start = std::chrono::steady_clock::now();
	cli.Get("/id=1");
	auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - start).count();
	printf("\nMs: %d\n", ms);
}
```
Output:
`Ms: 2052`
...
When the client connects to "127.0.0.1" (and not to  "localhost"), then the connection time is reduced to 5 ... 30 milliseconds.
Also, the time reduced when the server binds to "::" and not to "0.0.0.0".
Perhaps the file "hosts." resolves "localhost" to two addresses - IPv6 and IPv4, but your library, being smart enough to use IPv6, but not smart enough to connect to all received addresses at once...

**Comment by yhirose** [comment]
@vlad-mal, I just compiled the server and client codes on my Windows 10 with the latest Microsoft Visual Studio 2019. My result with '0.0.0.0' is ''Ms 7', 'Ms8' or 'Ms9'.

Anyway, I don't think it's a bug in cpp-httplib, but a network problem. You can see more detailed information which socket will be used from the `getaddrinfo` system call [here](https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L2076-L2135)

Hope it helps.

**Comment by PixlRainbow** [comment]
It is a known issue with Windows' OS network stack. It always takes a long time to resolve the name "localhost" to the loopback address and the problem is worsened if antivirus or firewall (e.g. Windows Defender) is running.

If Windows is configured to use a proxy, you may need to configure Windows to [skip proxy for local addresses](https://stackoverflow.com/a/25763832). This is configured through Internet Explorer, but affects system-wide.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the helpful info!

**Comment by vlad-mal** [comment]
> Это известная проблема сетевого стека ОС Windows. Преобразование имени localhost в адрес обратной связи всегда занимает много времени, и проблема усугубляется, если запущен антивирус или брандмауэр (например, Защитник Windows). Microsoft не исправила это, хотя это была проблема со времен Windows Vista.
> 
> Если Windows настроена на использование прокси, вам может потребоваться настроить Windows, чтобы [пропускать прокси для локальных адресов](https://stackoverflow.com/a/25763832) . Это настраивается через Internet Explorer, но влияет на всю систему. Однако это _не_ гарантирует решения вашей проблемы.

Thanks for the tip, but the "do not use proxy for local addresses" option did not work as expected.

**Comment by vlad-mal** [comment]
> [](https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L2076-L2135)
> 
> Hope it helps.

Thank, yhirose.
Apologies in advance for my poor english.
Tracing your code showed that the server, when creating a server socket (binding to "0.0.0.0"), always immediately creates a socket with the IpV4 protocol.
And when creating a client socket (connecting to "localhost") the getaddrinfo () function at https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L2076 returns a list of sorted addrinfo structures, so the structures with the IpV6 protocol come first, and then the IpV4 addresses. So, first, an attempt is made to connect using the IpV6 protocol, which causes a failure with an annoying timeout of about 2 seconds, then the next addrinfo (with the IpV4 protocol) is taken from the list and a successful (AND FAST!) connection. At as result, connection is made using the IpV4 protocol.
It's all about the getaddrinfo () function. In Win10, the IpV6 protocol takes precedence over the IpV4 protocol, so addrinfo with the IpV6 protocol comes first in the list. Of course, you can completely disable support for the IpV6 protocol, but this is strongly discouraged for Vista (and newer) operating systems.
You can change the priority of the protocols by prioritizing IpV4 over IpV6. To do this, just create (or change) the DisabledComponents variable in the registry branch.
HKEY_LOCAL_MACHINE \ SYSTEM \ CurrentControlSet \ Services \ Tcpip6 \ Parameters
setting its value to 20 (hexadecimal).
Details: https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/configure-ipv6-in-windows.

Regarding your library, dear yhirose, it would be convenient to do some additional setting in the line https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L2069, namely the value of ai_family: instead of
`hints.ai_family = AF_UNSPEC;
`set parameterized value
`hints.ai_family = <parameterized value>;
`
This will avoid annoying delays when connecting to older servers that do not support IpV6.

Regards.

**Comment by yhirose** [comment]
@vlad-mal, I just added `set_address_family` method. Please let me know if it works on your environment.

**Comment by vlad-mal** [comment]
> @vlad-mal, I just added `set_address_family` method. Please let me know if it works on your environment.

`#include <httplib.h>
#include <chrono>
namespace htl = httplib;

int main()
{
	htl::Client cli("localhost", 8080);
	cli.set_address_family(AF_INET); //********************************! :)
	auto start = std::chrono::steady_clock::now();
	cli.Get("/id=1");
	auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - start).count();
	printf("\nMs: %d\n", ms);
}
`

Thank you very much!
Now everything works without a pause.
