### ISSUE TITLE
Error::Read meaning and what could cause that

### ISSUE THREAD

**Issue by gtnardy** [yhirose/cpp-httplib#903]
Hey there!
Since I've updated from 0.7.x to the latest version (can't say exactly which one I was), I started to receive randomly the error code 4 (Error::Read) when downloading files. This is so random that if I just try again with the same URL after having the error, the error doesn't happen anymore.

What reasons could cause that? I've tried debugging or reading the code but couldn't find a reasonable explanation!

Thanks in advance!

**Comment by yhirose** [comment]
@gtnardy, thanks for the report. I used the test suite to validate my changes when releasing new versions, and it didn't detect the error... Is is possible for you walk back from the current release to a release that works (or the other way around)? I think it will tell us why the problem sneaked in. Thanks!

**Comment by PixlRainbow** [comment]
Hi gtnardy

Error::Read is supposed to mean malformed HTTP response, disconnect or incomplete response, is what I guess from reading the code.

**Comment by gtnardy** [comment]
Thank you @yhirose and @PixlRainbow! Fortunately I've found the problem and it was my fault 😄!

I was reusing an Client instance to download multiple files and it seems the read or keep-alive timeout was expiring after downloading a big file. Increasing the timeout value seems to have fixed it! Everything's good now!

**Comment by chuanxinwong** [comment]
`c++
void postGLTFBin(const std::string& orginPath,  std::string& outbin)
{
    httplib::Client cli(orginPath);
    // cli.set_keep_alive(true);        // Increase this 
    
    httplib::MultipartFormDataItems items = {
         { "gltf.bin", outbin, "filename", "application/octet-stream"},
    };
    auto res = cli.Post(fullPath, items);
    auto err = res.error();
}

postGLTFBin("path1", "xxxx1");   // Most likely successful
postGLTFBin("path1", "xxxx2");   // Most likely successful
postGLTFBin("path1", "xxxx3");   // Most likely to fail
postGLTFBin("path1", "xxxx4");   // Most likely to fail
`
I succeeded after increasing cli.set_keep_alive(true)。
