### ISSUE TITLE
How to return a JSON format or other format

### ISSUE THREAD

**Issue by AKmoex** [yhirose/cpp-httplib#905]
First of all, thank you for this project. 
I found that only one string can be returned in the server-side examples. 
How can I return a JSON or other format content

**Comment by PixlRainbow** [comment]
1. [strings in C/C++ are not just for human-readable text](https://github.com/yhirose/cpp-httplib/issues/824#issuecomment-755097175)
2. You will need to construct the JSON data either by yourself or using a [third party library](https://github.com/nlohmann/json#tofrom-strings). This library only handles the base HTTP protocol and communications.  
After you have constructed the JSON data and stored it into an `std::string`, [set the content type](https://github.com/yhirose/cpp-httplib#server) to be `application/json`. e.g.  
```cpp
// .. some handler code
res.set_content(myJsonData, "application/json");
// .. some handler code
```

**Comment by yhirose** [comment]
@PixlRainbow, thanks for your help as always!

**Comment by AKmoex** [comment]
@PixlRainbow Thank you.
