### ISSUE TITLE
The constructor of std::regex under the qnx platform is wrong

### ISSUE THREAD

**Issue by lujuntuan** [yhirose/cpp-httplib#908]
Platform: qnx700 aarch64 C++11 support

I try to modify:
Before
```
    post_handlers_.push_back(
        std::make_pair(std::regex(pattern, pattern_len), std::move(handler)));
    return *this;
```

After
```
    post_handlers_.push_back(
        std::make_pair(std::regex(pattern, pattern_len, std::regex::ECMAScript), std::move(handler)));
    return *this;
```

And it is ok.

**Comment by yhirose** [comment]
@lujuntuan, thanks for the report. It seems like it's a bug in your compiler. Please see the following reference. According to the constructor declarations, the `flag_type f` is optional. Could you submit a bug report to them?
https://en.cppreference.com/w/cpp/regex/basic_regex/basic_regex

**Comment by lujuntuan** [comment]
@yhirose , It is true that the constructor lacks default values. 
The new compiler version seems to have changed.
I personally think that adding a default value to this place will not have any effect, haha.
