### ISSUE TITLE
OpenSSL version less than 1.1.1

### ISSUE THREAD

**Issue by lujuntuan** [yhirose/cpp-httplib#909]
Sorry,

I want to know what features will not be supported if the version is less than 1.1.1?
It looks okay after I ignore #error? 
(It looks like you have done a version less than 1.1.1 )

```
#if OPENSSL_VERSION_NUMBER < 0x1010100fL
//#error Sorry, OpenSSL versions prior to 1.1.1 are not supported
#endif
```

My OpenSSL version is 1.0.2 under qnx platform, I only need https server and client to transfer files.

**Comment by yhirose** [comment]
@lujuntuan, thanks for the feedback. Since I don't want to take any risks with versions that are no longer officially supported, I intentionally dropped the support for such older versions. Thanks for your understanding!
https://www.openssl.org/policies/releasestrat.html

**Comment by lujuntuan** [comment]
emm.. 
Ok i got it. Thanks~
