### ISSUE TITLE
Openssl on macos crash

### ISSUE THREAD

**Issue by RolandasV** [yhirose/cpp-httplib#910]
Trying to use the library with open ssl support on both windows and macos. Managed to get it working on windows, however having trouble with openssl support on macos. Not sure if it is a bug or I'm doing something wrong.

Build openssl from source and linked with my project, also tried getting openssl from brew and then linking the libraries. The project builds fine, however getting a run time crash.

<img width="1018" alt="Screenshot 2021-04-22 at 11 00 34" src="https://user-images.githubusercontent.com/17047859/115678574-5433d800-a35a-11eb-8db8-62aa27203a1a.png">

The crash happens in httplib.h file. Not sure if this is httplib problem or an issue the with the linked openssl libraries.

All I'm doing is a simple https post.

Any help would be appreciated.

**Comment by yhirose** [comment]
@RolandasV, could you try `cd test; make` on your machine please?

**Comment by RolandasV** [comment]
@yhirose 1test failed.

[----------] Global test environment tear-down
[==========] 213 tests from 56 test cases ran. (233077 ms total)
[  PASSED  ] 212 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SSLClientTest.WildcardHostNameMatch


[ RUN      ] SSLClientTest.WildcardHostNameMatch
test.cc:3880: Failure
Value of: res->status
  Actual: 302
Expected: 200
[  FAILED  ] SSLClientTest.WildcardHostNameMatch (241 ms)

**Comment by yhirose** [comment]
@RolandasV, I just updated the test/test.cc. Could you try it again with the latest code? Thanks.

**Comment by RolandasV** [comment]
@yhirose with the changes all tests pass.

**Comment by yhirose** [comment]
@RolandasV, good! That means all you need to know are written in [test/Makefile](https://github.com/yhirose/cpp-httplib/blob/master/test/Makefile). Hope it helps!

**Comment by RolandasV** [comment]
@yhirose after some more debugging now I'm getting a BindIPAddress error when posting. Could you give some more info what the error is about? And maybe some possible solutions? Thanks.

`httplib::Client cli(host.c_str());cli.enable_server_certificate_verification(false);
auto res = cli.Post(url.c_str(), postData, dataTransfer.c_str());`
