### ISSUE TITLE
IP 127.0.0.1 does not work

### ISSUE THREAD

**Issue by Spixmaster** [yhirose/cpp-httplib#914]
The following code does not work. It results in error 2 which is "Connection".
```
httplib::Client client("127.0.0.1", 5285);
httplib::Result result = client.Get("/hi");
std::cout << static_cast<int>(result.error()) << std::endl;
```

Is there a reason for it? As a side note. The server on localhost was setup with the host "localhost".

**Comment by yhirose** [comment]
@Spixmaster, since it's a general problem of socket, you could try with `curl http://127.0.0.1:5285/hi -v' to get more information to diagnose your network problem. Hope it helps.

**Comment by corentin35000** [comment]
Bind host for : 0.0.0.0

**Comment by Spixmaster** [comment]
> Bind server host via : 0.0.0.0

That might work, I use `localhost` which works. I do not know why `127.0.0.1` did not work. I have not tested it recently. I just wanted to let the public know.
