### ISSUE TITLE
Getting non-existent values should throw an exception

### ISSUE THREAD

**Issue by Spixmaster** [yhirose/cpp-httplib#915]
In all three cases, no exception is thrown.
```
httplib::Server server;

server.Post("/test", [](const httplib::Request &req, httplib::Response &res)
{
    req.get_header_value("does_not_exist");
    req.get_param_value("does_not_exist");
    req.get_file_value("does_not_exist");
}
```

Instead, a default value is returned as this code snippet shows:
```
inline MultipartFormData Request::get_file_value(const char *key) const {
  auto it = files.find(key);
  if (it != files.end()) { return it->second; }
  return MultipartFormData();
}
```

I think this should throw an exception each time as otherwise there would be no difference between `req.get_file_value("does_not_exist").content == ""` for a key which does exists and simply has no content and a key that does not exist. Another argument is that in the current situation the "has-function" like `req.has_file("")` are not needed.

**Comment by yhirose** [comment]
@Spixmaster, thank you for the suggestions, but the intentions for them are not as you think. Please check README and test/test.cc. Hope it helps!

**Comment by Spixmaster** [comment]
@yhirose I checked the Readme and test/test.cc. Nevertheless, I do not understand what you mean with "the intentions for them are not as you think".

I looked at the line and the following ones: https://github.com/yhirose/cpp-httplib/blob/master/test/test.cc#L1405

**Comment by yhirose** [comment]
@Spixmaster, `bool has_???(const char *key) const` method should be used to check the key exists, then use the corresponding `get` method.

**Comment by Spixmaster** [comment]
@yhirose Yes, this is how I thought it should be. My question is, why `bool get_???(const char *key) const` does not throw an exception if `bool has_???(const char *key) const` is false and the key does not exist.

**Comment by yhirose** [comment]
@yhirose, basically, I try to make this library 'exception free' code. That's why I made `has_` methods instead of throwing exceptions from `get_`. (Right now, there is only one place to throw an exception in cpp-httplib.) As you pointed in `test/test.cc`, there is `get_file_vaule` which throws an exception, but it's just a utility method for testing. Hope it satisfies your question.
