### ISSUE TITLE
'httplib::Server::Post: ambiguous call to overloaded function' compilation error

### ISSUE THREAD

**Issue by tsilia** [yhirose/cpp-httplib#916]
Hello. Thanks for your neat library!

I'm trying to use `std::bind` with `Server::Post`, like this:
```cpp
#include <functional>
//...
svr.Post("/post", std::bind(&Server::ProcessPostRequest, this, std::placeholders::_1, std::placeholders::_2));
```
and getting the aforementioned compile error. While this approach works well with other methods (`Server::set_logger` and the likes) it wouldn't work with this particular method, probaly because of how its overloads are defined:
```cpp
Server &Post(const char *pattern, Handler handler);
Server &Post(const char *pattern, HandlerWithContentReader handler);
```
Looks like the two alternatives *are* ambiguous because both `Handler` and `HandlerWithContentReader` are defined as
```cpp
using Handler = std::function<void(const Request &, Response &)>;
using HandlerWithContentReader = std::function<void(
      const Request &, Response &, const ContentReader &content_reader)>;
```
, i.e. an `std::function` essentially.
I have looked through the `test.cc` and found no examples of using functional binding with the `Server::Post` method. I know I could get away with lambdas:
```cpp
svr.Post("/post", [&](const auto& req, auto& res)
{
    return ProcessPostRequest(req, res);
});
```
but would like to keep the code a bit more readable and less redundant. Besides, it could be useful if you need to refer to other object's methods.

Please, is there any way to use `std::bind` with `Server::Post`?

PS. Looks like there's a typo in the content-type parameter in `test.cc` which isn't worth making a PR:
https://github.com/yhirose/cpp-httplib/blob/c58b00580ee66a248c2ef20334bb84319ccde310/test/test.cc#L1316

**Comment by yhirose** [comment]
@tsilia, thanks for the feedback. Could you explain what is `ProcessPostRequest`? There is no such method on `Server` though...

**Comment by tsilia** [comment]
Hey @yhirose, thank you for your reply.
Sorry I wasn't clear enough and my message was also a bit misleading.

`ProcessPostRequest` is just a placeholder for a method that processes post requests. It is a member of my class, `::Server`, which I somehow named exactly as your class located in the `httplib` namespace. After renaming it to make things more clear and giving some more details, I have this:
```cpp
#include <cpphttplib/httplib.h>
// I simplified the code for brevity
class HttpServer
{
private:
    void ProcessPostRequest(const httplib::Request& req, httplib::Response& res)
    {
        res.status = 501;
        res.set_content("not implemented", "plain/text");
    }

    void ThreadFunc()
    {
        auto pServer = std::make_unique<httplib::Server>();
        pServer->Post("/post", std::bind(&HttpServer::ProcessPostRequest, this, std::placeholders::_1, std::placeholders::_2));
        pServer->listen("localhost", 12345);
    }
}
```
I'm trying to use functional binding with `httplib::Server::Post` method instead of lambdas but can't because of compiler error which tells there's an ambiguity between the two overloads of the `httplib::Server::Post` method:
```
Error	C2668	'httplib::Server::Post': ambiguous call to overloaded function	my_project\httpserver.cpp

libs\cpphttplib\httplib.h(4238): note: could be 'httplib::Server &httplib::Server::Post(const char *,httplib::Server::HandlerWithContentReader)'
libs\cpphttplib\httplib.h(4227): note: or       'httplib::Server &httplib::Server::Post(const char *,httplib::Server::Handler)'
my_project\httpserver.cpp(76): note: while trying to match the argument list '(const char [13], std::_Binder<std::_Unforced,void (__thiscall HttpServer::* )(const httplib::Request &,httplib::Response &),HttpServer *const ,const std::_Ph<1> &,const std::_Ph<2> &>)'
```
So, I was wondering if there's any way to resolve the issue other than using lambdas which I'm already doing for now :)

**Comment by yhirose** [comment]
@tsilia, I now got it.

`std::bind` is a much weaker solution than the lambda function anyway, and I think there is no elegant solution. Only thing that I can come up with is as below:

```cpp
class HttpServer
{
private:
    void ProcessPostRequest(const httplib::Request& req, httplib::Response& res)
    {
        res.status = 501;
        res.set_content("not implemented", "plain/text");
    }

    void ThreadFunc()
    {
        auto pServer = std::make_unique<httplib::Server>();
        pServer->Post("/post", httplib::Server::Handler(std::bind(&HttpServer::ProcessPostRequest, this, std::placeholders::_1, std::placeholders::_2)));
        pServer->listen("localhost", 12345);
    }
}
```

Is it good enough for you?

**Comment by tsilia** [comment]
Yeah, thanks, that compiles ok. Couldn't think of putting it this way. Now that you suggested it, I'm thinking of making a wrapper function, smth like RegisterHandler which will return `httplib::Server::Handler(std::bind(callable, args))`.
Thank you.

**Comment by wongdu** [comment]
got the same problem

**Comment by eurake** [comment]
Same problem, need solution
