### ISSUE TITLE
compile with no exceptions?

### ISSUE THREAD

**Issue by bftjoe** [yhirose/cpp-httplib#919]
Is there a chance the library could do without exception support? I tried to combine this with another c++ project with exceptions disabled for performance, but this requires exceptions.

**Comment by yhirose** [comment]
@bftjoe, thank you for the feedback. There is only one place where cpp-httplib throws an exception.

https://github.com/yhirose/cpp-httplib/blob/c58b00580ee66a248c2ef20334bb84319ccde310/httplib.h#L7189-L7197

You can fork this library and comment out the block to make it exception free code. Hope it helps.

**Comment by bftjoe** [comment]
Did you mean to link to a specific line? In any case, -fno-exceptions disables all try catch, not just throwing exception. I will probably look into a different library.

**Comment by yhirose** [comment]
@bftjoe, sorry that this library doesn't satisfy your needs... Hope you will find a library that fits in with your requirement. :)

**Comment by bftjoe** [comment]
Looks like there is now support for no exceptions.
