### ISSUE TITLE
How can I download a file with cpp-httplib

### ISSUE THREAD

**Issue by geometry2019** [yhirose/cpp-httplib#923]
I have tried using cpp-httplib's Get() to download an image , but it failed and the error code was Read . As you can imagine , the image is not text , but it uses string to store it , which makes it not 
 worked . So how can I use this library to download files ?

**Comment by yhirose** [comment]
@geometry2019, hope this helps.
https://github.com/yhirose/cpp-httplib/blob/2a70c45697822621c4c50b5e26834d42ed41df01/test/test.cc#L357-L378
