### ISSUE TITLE
Split.py does not work if you want to enable openssl support

### ISSUE THREAD

**Issue by braindigitalis** [yhirose/cpp-httplib#928]
If you want to enable openssl support using `#define CPPHTTPLIB_OPENSSL_SUPPORT`, you cannot also use split.py without additional changes to the .cc file.

The .cc file needs the following additional definitions above the `#include`:

    #include <openssl/ssl.h>
    #include <openssl/err.h>
    #include <openssl/md5.h>
    #define CPPHTTPLIB_OPENSSL_SUPPORT

Of course, if you are not using openssl these are not required. Can split.py be modified to have a command line parameter asking if you intend to use openssl? I would do this myself and submit a PR, but i don't really know any python.

Thanks for considering!

**Comment by yhirose** [comment]
@braindigitalis, the split `httplib.cc` has the following lines. So what you have to do is to pass `CPPHTTPLIB_OPENSSL_SUPPORT` to your compiler.

![image](https://user-images.githubusercontent.com/357397/117538761-a3723d80-afd5-11eb-9841-71e01273def6.png)

Hope it helps!
