### ISSUE TITLE
Server: get notified if transfer is aborted ?

### ISSUE THREAD

**Issue by ottigeda** [yhirose/cpp-httplib#930]
In some code using a httplib::Server() I would like to learn when a client aborts the transfer,
or if the file was successfully and completely delivered to the client.
I did think Server::set_error_handler would do the job, but for me the error handler never gets called.
Is this a bug, or did I not fully understand what is the purpose of the error handler ?

In my test I use wget to download a bigger file from a httplib::Server(),
which serves the contents using a content provider.
When I abort the wget I expected that the error handler gets called,
but it does not do that for me.

**Comment by yhirose** [comment]
@ottigeda, `Server:: set_error_handler` isn't for that purpose. It is called when the path doesn't match any of registered request handlers. You can see some examples in `test/test.cc`. There is no way to detect such an abort event on client for now.

**Comment by PixlRainbow** [comment]
> In my test I use wget to download a bigger file from a httplib::Server(),
which serves the contents using a content provider.

You can write your content provider to set a global flag to indicate that a transfer is complete if the last batch of data has been written to sink. There is still a possibility that an abort will not be caught if a client aborts halfway through the transfer of the last batch, but at least you will be catching aborts between any other batch.
