### ISSUE TITLE
SSLClient - any docs how to use it for client certificate authentication?

### ISSUE THREAD

**Issue by samthesuperhero** [yhirose/cpp-httplib#932]
Dear contributors,

any idea where I can find detailed guide of API documentation to use SSLClient for client X.509 certificate authenticating? Or at least, turn on some "debug logging" or so, to understand what happens?

Running on Fedora 34,
``` cpp
#include <cstdio>
#include <iostream>
#include "httplib.h"

int main() {

    #ifndef CPPHTTPLIB_OPENSSL_SUPPORT
        httplib::Client cli("http://134.122.94.197:9080");
    #else
        httplib::SSLClient cli("dev-IoTHub-FHCS-weeu-cloudgateway-cgw.azure-devices.net",
                               443,
                               ".azure.x.509.certs/Simulate_HTTP-public.pem",
                               ".azure.x.509.certs/Simulate_HTTP-private.pem");
    #endif

    auto r = cli.Post("", "CCCC", "application/octet-stream");

    std::cout << r->status << std::endl;

    return 0;
}
```
Output:
``` shell
Segmentation fault (core dumped)
```
(exit code 139 by signal 11: SIGSEGV)

If I comment stdout,
``` cpp
    // std::cout << r->status << std::endl;
```
just nothing happens, Wireshark as well shows nothing, no traffic obviously generated by this code.

**Comment by yhirose** [comment]
@samthesuperhero, you can see a number of examples calling the constructor of `SSLClient` with a cert file and a private key file`. The segmentation fault sounds that your build doesn't link necessary libraries properly. (If you run `cd test; make` works on your machine?)
Hope it helps!
