### ISSUE TITLE
Cannot graceful stop

### ISSUE THREAD

**Issue by guoxiangzhou** [yhirose/cpp-httplib#937]
class Server {
public:
    void start(const std::string &ip, int port);
    void stop();

protected:
    void registerHandler();

private:
    httplib::Server m_server;
    std::unique_ptr<std::thread> m_work;
};

void Server::start(const std::string &ip, int port) {
    registerHandler();

    m_work = std::make_unique<std::thread>([&](){
        m_server.listen(ip.c_str(), port);
    });
}

void Server::stop() {
    m_server.stop();
    m_work->join();
}

void Server::registerHandler() {
    m_server.Get("/collection/create", [](const httplib::Request &http_req, httplib::Response &http_res) {
        LOG_I("/collection/create");
        http_res.set_content("create table success", "text/plain");
    });
}

int main() {
   Server s;
   s.start("127.0.0.1", 80);
   s.stop();   
   return 1;
}

can not exit;
On macos, I found block in the stack of call s.stop()

**Comment by yhirose** [comment]
@guoxiangzhou, hope [this](https://github.com/yhirose/cpp-httplib/blob/75fdb06696d4e27b590135c1e4a226b4e13e9bd7/test/test.cc#L3778-L3802) helps!

**Comment by guoxiangzhou** [comment]
I don't think the problem has been solved. _t.join() will be blocked, because _t thread wait the return of accept function.

**Comment by guoxiangzhou** [comment]
I don't think the problem has been solved.

I debugged the test code: The reason why it can exit normally is that Before the t_ thread enters the listen function, the main thread executes the teardown function.

In general, The t_ thread is waiting for the accpet function to return, and t_. join() will block

**Comment by yhirose** [comment]
@guoxiangzhou, I closed #943, because I would not like to scatter the same thing in different issues. Also I'll keep it as 'closed' until I confirm it's a really problem. Thank you for your understanding!

Anyway, could you add the following after you start the thread?
https://github.com/yhirose/cpp-httplib/blob/75fdb06696d4e27b590135c1e4a226b4e13e9bd7/test/test.cc#L3789-L3791
