### ISSUE TITLE
Error in section SSL Support

### ISSUE THREAD

**Issue by aramperez** [yhirose/cpp-httplib#939]
The code in this section has the following code:
`
#define CPPHTTPLIB_OPENSSL_SUPPORT
#include "path/to/httplib.h"

// Server
httplib::SSLServer svr("./cert.pem", "./key.pem");

// Client
httplib::Client cli("https://localhost:1234");

// Use your CA bundle
cli.set_ca_cert_path("./ca-bundle.crt");

// Disable cert verification
cli.enable_server_certificate_verification(false);
`

However, the `httplib::Client` class does NOT have a `set_ca_cert_path` method. That method is only available in the `httplib::SSLClient`.

**Comment by yhirose** [comment]
@aramperez, hope the following info helps you!
https://github.com/yhirose/cpp-httplib/blob/75fdb06696d4e27b590135c1e4a226b4e13e9bd7/httplib.h#L1347-L1349

**Comment by aramperez** [comment]
I guess I was not clear enough: you have an error in your README.md file. Take a look at your example in the **SSL Support** section. It states `httplib::Client cli("https://localhost:1234");` followed by `cli.set_ca_cert_path("./ca-bundle.crt");`. The first statement should have been `httplib::SSLClient cli("https://localhost:1234");`.
