### ISSUE TITLE
SSL read timeout errors on Windows

### ISSUE THREAD

**Issue by oviano** [yhirose/cpp-httplib#944]
Firstly, thanks for making the library! It's nice to have a simpler modern alternative to libCURL.

So I'm finding on Windows that I get an unexpected amount of error code 4 returned when calling Get when accessing a remote https endpoint to receive JSON data.

I do not get the same timeouts when retrieving the same amounts of data, from the same LAN, using the Mac platform, therefore I think there is something different/wrong with the Windows implementation.

Often retrying immediately afterwards produces the same error. It comes and goes. It can be mitigated to some extent (but not completely) by increasing the read timeout to a huge number, but this seems odd because this already defaults to 5s and the error occurs well before 5s have passed from the initial Get call.

Anyway, I traced it through and I found that inside SSLSocketStream::read, if I hack in the following lines at the top of the while loop...

      while (err == SSL_ERROR_WANT_READ || (err == SSL_ERROR_SYSCALL && WSAGetLastError() == 10060)) {
        if (err == SSL_ERROR_SYSCALL && WSAGetLastError() == 10060) {
          std::cout << "timeout error, retrying" << std::endl;
        }

...then I can make the problem go away. I see it come up occasionally in the trace, but it now completes the Get request, rather than fail completely, repeatedly.

Thread here in the openssl project, which might give some clues about this behaviour:

https://github.com/openssl/openssl/issues/12416

**Comment by yhirose** [comment]
@oviano, thank you for the fine report and look fine to me. Could you test with the following change on you machine?

```cpp
#ifdef _WIN32
      while (err == SSL_ERROR_WANT_READ ||
             err == SSL_ERROR_SYSCALL && WSAGetLastError() == WSAETIMEDOUT) {
#else
      while (err == SSL_ERROR_WANT_READ) {
#endif
```

Thank you for your help!

**Comment by oviano** [comment]
Yes, this works correctly.

**Comment by yhirose** [comment]
@oviano, I have merged it. Thanks for your fine contribution!

**Comment by qt1** [comment]
Also works for me.
I actually did the same patch and discovered that the upstream was already fixed :)
