### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by just6chill** [yhirose/cpp-httplib#945]
```c++
#include <iostream>

#include "UrlHandler.h"
#include "httplib.h"

int requestSend() {

    std::cout << "sending request";

    httplib::Client cli("https://api.telegram.org");
    

    cli.set_compress(true);
    auto res = cli.Post("/botMYTOKEN/sendMessage", "chat_id=1025711021&text=test%20from%20Framework", "application/x-www-form-urlencoded");

    return 0;
}
```

i have this code but somehow it always abort, i am on windows using the msvc compiler. help would be great, dunno what i did wrong.

if i do a curl request like this:
```
curl -X POST "https://api.telegram.org/botMYTOKEN/sendMessage?chat_id=1025711021&text=test%20from%20Framework"
```
it works completly fine

i appreciate every help.

**Comment by yhirose** [comment]
@just6chill, I am not sure. Your code looks good to me. Probabry `CPPHTTPLIB_OPENSSL_SUPPORT` is not enabled when compiling?

**Comment by just6chill** [comment]
@yhirose sorry for the late reply, you where right I neither include ssl nor installed the libs, not it's working, Thanks!
