### ISSUE TITLE
error: missing space between '""' and suffix identifier

### ISSUE THREAD

**Issue by kktao** [yhirose/cpp-httplib#953]
hello, when I compile it with my project, I had following problem.
### my environment:
-- CMake version: 3.5.1
-- CMAKE_CXX_COMPILER '/usr/bin/c++' 'GNU' '4.8.4'
### error info
`cpp-httplib-v0.8.5/httplib.h:2286:14: error: missing space between '""' and suffix identifier
   using udl::operator""_;`
### my solution
To solve the problem you only need to add a space in this line
`using udl::operator"" _;`
And that is it, hope it helps someone else.

**Comment by yhirose** [comment]
Hope #812 and #865 help you.
