### ISSUE TITLE
how to upload big file to server

### ISSUE THREAD

**Issue by Airyzf** [yhirose/cpp-httplib#954]
How to upload a big file , i dont know how to write frame data in post callback function

    std::ifstream fs;
    fs.open(filename.c_str(), std::ifstream::in | std::ifstream::binary);
    if (!fs) 
    {
        printf("open %s failed\n", filename.c_str());
    } 
    std::streampos pos = fs.tellg();
    fs.seekg(0, std::ios::end);
    size_t filesize = fs.tellg();
    std::cout << "size = "<<filesize<<std::endl;

    auto res = cli->Post(
        _url.c_str(),
        filesize,
        [](size_t offset,size_t length, httplib::DataSink &sink) {
            std::cout << "length = "<<length<<",offset = "<<offset<<std::endl;
            // how to write data frame here
            return true; // return 'false' if you want to cancel the request.
        },
        "application/octet-stream");

**Comment by yhirose** [comment]
@Airyzf, I probably don't understand what you meant with 'frame', but you can send whatever data via `sink.write`. You can see a number of examples in `test.test.cc`. Hope it helps!

**Comment by Airyzf** [comment]
> @Airyzf, I probably don't understand what you meant with 'frame', but you can send whatever data via `sink.write`. You can see a number of examples in `test.test.cc`. Hope it helps!

How to send data to server when I read a big file one by one chunked?

**Comment by yhirose** [comment]
https://github.com/yhirose/cpp-httplib/blob/master/README.md#receive-content-with-a-content-receiver

**Comment by yhirose** [comment]
It might help you:
https://github.com/yhirose/cpp-httplib/issues/922
