### ISSUE TITLE
Disable Content-Type in Post requests

### ISSUE THREAD

**Issue by mahsa-kh-21** [yhirose/cpp-httplib#959]
I want to interact with Dropbox API in one of my C++ projects. I need to upload two json strings to a text file that is already in my Dropbox. I'm using [this API](https://www.dropbox.com/developers/documentation/http/documentation#files-upload) to upload strings. This is my code:
```
        httplib::SSLClient cli("content.dropboxapi.com");
	httplib::Headers headers = {
		{ "Authorization",
		" Bearer " + accessToken
		},
		{ "Dropbox-API-Arg",
		"{\"path\": \"" + uploadPath + "\",\"mode\": \"overwrite\",\"mute\": false,\"strict_conflict\": false}"
		},
		{ "Content-Type","application/octet-stream" }
	};
        httplib::Params content{
				{ "hardware",  obj.hardware },
				{ "client",  obj.client }
			};
	auto res = cli.Post("/2/files/upload", headers, content);
```
As you can see I've only set `{ "Content-Type", "application/octet-stream" }` but when I execute my code I get the following error from API:
`400
Error in call to API function "files/upload": Bad HTTP "Content-Type" header: "application/octet-stream,application/x-www-form-urlencoded".  Expecting one of "application/octet-stream", "text/plain; charset=dropbox-cors-hack".`
Looks like `application/x-www-form-urlencoded` is being added automatically and since the API is very strict with `Content-Type`, I'm looking forward to disabling it.
Oh and one more detail, if I send somethin like this I wont get any errors:
```
cli.Post("/2/files/upload", headers, "hello world", "application/octet-stream");
```
Unfortunately merging jsons into one is very a expensive operation and I cant use the latter approach so I thought Id ask if I can disable it.
Thanks for this amazing library.

**Comment by yhirose** [comment]
@mahsa-kh-21, thanks for the feedback. The Post API taking `Params` can be used only for `application/x-www-form-urlencoded`, not for any other content types like JSON. Please see the following example based on [the MDN](
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST#example).

```cpp
httplib::Headers headers {
  ...
};

httplib::Params params {
  {"field1", "value1"},
  {"field2", "value2"},
};

auto res = cli.Post("/test", headers, params);
```

```
POST /test HTTP/1.1
Host: foo.example
Content-Type: application/x-www-form-urlencoded
Content-Length: 27

field1=value1&field2=value2
```

This API sends `field1=value1&field2=value2` as body content, and not `{{"field1","value1"},{"field2","value2"}}`.

If you want to send JSON data, you have to use either of the followings:

```cpp
Result Post(const char *path, const Headers &headers, const char *body,
            size_t content_length, const char *content_type);

Result Post(const char *path, const Headers &headers, size_t content_length,
            ContentProvider content_provider, const char *content_type);
```

You can see more examples in `test/test.cc`.
Hope it helps!
