### ISSUE TITLE
what does the condition "s[i] < 0" mean?

### ISSUE THREAD

**Issue by meloncolie** [yhirose/cpp-httplib#96]
`inline std::string encode_url(const std::string& s)
{
    std::string result;

    for (auto i = 0; s[i]; i++) {
        switch (s[i]) {
        case ' ':  result += "+"; break;
        case '\'': result += "%27"; break;
        case ',':  result += "%2C"; break;
        case ':':  result += "%3A"; break;
        case ';':  result += "%3B"; break;
        default:
            if (s[i] < 0) {
                result += '%';
                char hex[4];
                size_t len = snprintf(hex, sizeof(hex) - 1, "%02X", (unsigned char)s[i]);
                assert(len == 2);
                result.append(hex, len);
            } else {
                result += s[i];
            }
            break;
        }
   }

    return result;
}`

in this section, 's' is a string and "if (s[i] < 0)" should be always false. I am wondering, what does this condition mean and how to correct it? thx

**Comment by yhirose** [comment]
@meloncolie, thanks for the question. This is not a bug. When we encode a UTF string, `s[i]` could actually contain negative values, since the `value_type` of `std::string` is `char` (which can take -127 to 127). '-127 to -1' means '0x80 to 0xff'.

Here is an example for the UTF8 copyright mark:

```cpp
#include <iostream>

int main(void) {
  std::string s = u8"©"; // copyright mark (U+00A9, '0xC2 0xA9 (c2a9)' in UTF8)

  // C2:-62
  // A9:-87
  for (int i = 0; i < s.size(); i++) {
    printf("%X:%d\n", (unsigned char)s[i], s[i]);
  }
}

```

Does it make sense to you?

**Comment by meloncolie** [comment]
@yhirose i got it, thx a lot~

**Comment by yhirose** [comment]
@meloncolie, thanks for the additional information. I now understand your concern. [This stackoverflow post](https://stackoverflow.com/questions/757482/comparison-is-always-true-due-to-limited-range-of-data-type-warning-in-c) explains it well.

I just updated the code. Thanks for your contribution!
