### ISSUE TITLE
the "/" problem

### ISSUE THREAD

**Issue by qbgit** [yhirose/cpp-httplib#960]
the client http url like 
  1==>   httplib::Client cli0("http://127.0.0.1:8088")
or
  2 ==>  httplib::Client cli0("http://127.0.0.1:8088/")

 we porcess the "/" ,but cpp-httplib will be make an error ,it occurs ,if we have the "/" ,just like 2 method

**Comment by PixlRainbow** [comment]
the constructor of the httplib::Client object takes a string that contains IP or hostname, and optionally port number or protocol. It does not accept specifying path in the constructor. By adding a `/` you are indicating a path (root directory of web server).

**Comment by yhirose** [comment]
Hope @PixlRainbow's comment helps.
