### ISSUE TITLE
SSLServerVerification error when using SSLClient on Mac

### ISSUE THREAD

**Issue by zgerrard** [yhirose/cpp-httplib#967]
Hi, thanks for the great library. I tried testing it and I am getting error 10 (SSLServerVerification) when using SSLClient. I also tried different hosts (e.g. google.com), and getting the same error. Below is the code:
```
httplib::SSLClient scli("www.httpwatch.com", 443);
scli.set_connection_timeout(2);
auto res = scli.Get("/httpgallery/chunked/chunkedimage.aspx?0.4153841143030137"));
```

Any ideas on what might be going on? I am using OpenSSL version 1.1.1i, and running everything on Mac with M1.

**Comment by yhirose** [comment]
Does #673 help you?
