### ISSUE TITLE
post big data

### ISSUE THREAD

**Issue by chentiannan** [yhirose/cpp-httplib#968]
In the case of post large JSON data, it always fails to send. After verification, an error is reported_ write ssl_ error_ Syscall, get on Windows system_ last_ The code of error is 10060. I use it when I use client
```
cli.set_ connection_ timeout(30000);
cli.set_ write_ timeout(10000);
cli.set_ read_ timeout(10000);
cli.set_ keep_ alive(true);
```
Solve the problem temporarily.

**Comment by yhirose** [comment]
@chentiannan, sorry but I think it's not related to httplib.h itself, but more like your network condition...

**Comment by chentiannan** [comment]
But I am in the same network conditions, using postman is OK, I confirm that when the data is greater than 64K, the error is SSL_ Write, this function is successfully sent when it is called for the first time, and returns - 1 for the second time, which causes the httplib error code to be unknown.
The relevant codes are as follows:
```
inline ssize_t SSLSocketStream::write(const char *ptr, size_t size) 
   return SSL_write(ssl_, ptr, static_cast<int>(size));
```
