### ISSUE TITLE
Getting Segmentation Fault : 11 with https requests

### ISSUE THREAD

**Issue by vectar31** [yhirose/cpp-httplib#969]
Here's what I am running this on macOS: 

```
#define CPPHTTPLIB_OPENSSL_SUPPORT
#include "httplib.h"

httplib::Client cli("https://cpp-httplib-server.yhirose.repl.co");
	cli.enable_server_certificate_verification(false);
  
 auto res = cli.Get("/hi");

 if (res) {
    std::cout << res->status << std::endl;
    std::cout << res->body << std::endl;
  }
```

The segmentation fault : 11 is thrown while executing line ` auto res = cli.Get("/hi");` 

Any idea why that may be happening?

**Comment by yhirose** [comment]
@vectar31, did you follow the following instruction in README?

> SSL support is available with CPPHTTPLIB_OPENSSL_SUPPORT. libssl and libcrypto should be linked.
