### ISSUE TITLE
void Client::write_request should buffer request before writing to socket/stream

### ISSUE THREAD

**Issue by DJm00n** [yhirose/cpp-httplib#97]
At least some devices do not understand HTTP requests with header and json in separate TCP packets. This is caused by multiple SocketStream::write calls on same socket stream.
To fix this in my case I just implemented BufferStream and just using it in Client::write_request instead of provded Stream& strm:

```
inline void Client::write_request(Stream& strm, Request& req)
{
    auto path = detail::encode_url(req.path);

    BufferStream buffer;
    // Request line
    buffer.write_format("%s %s HTTP/1.1\r\n",
        req.method.c_str(),
        path.c_str());
.....
    use buffer instead of strm (socket stream)
.....
    auto& data = buffer.get_buffer();
    strm.write(data.data(), data.size());
}
```

```
class BufferStream : public Stream {
public:
    BufferStream() {}
    virtual ~BufferStream() {}

    virtual int read(char* ptr, size_t size);
    virtual int write(const char* ptr, size_t size);
    virtual int write(const char* ptr);
    virtual std::string get_remote_addr();

    std::string& get_buffer();

private:
    std::string buffer;
};

//Buffer stream implementation
inline int BufferStream::read(char* ptr, size_t size)
{
#ifdef _WIN32
    return static_cast<int>(buffer._Copy_s(ptr, size, size));
#else
    return static_cast<int>(buffer.copy(ptr, size));
#endif
}

inline int BufferStream::write(const char* ptr, size_t size)
{
    buffer.append(ptr, size);
    return static_cast<int>(size);
}

inline int BufferStream::write(const char* ptr)
{
    size_t size = strlen(ptr);
    buffer.append(ptr, size);
    return static_cast<int>(size);
}

inline std::string BufferStream::get_remote_addr() {
    return "";
}

inline std::string& BufferStream::get_buffer() {
    return buffer;
}
```

**Comment by yhirose** [comment]
@DJm00n, thanks for your feedback! I have two questions.

1. Could you give me specific examples of 'At least some devices'?
2. How did you implement `write_format` method on your BufferStream class? (I am just curious because it's not easy to implement it in an efficient way.)

Thanks!

**Comment by DJm00n** [comment]
@yhirose 
1. I working with [Nanoleaf Light Panel](https://nanoleaf.me/en/consumer-led-lighting/products/smarter-series/nanoleaf-light-panels-smarter-kit/) via their [HTTP/JSON API (REST)](https://forum.nanoleaf.me/forum/aurora-open-api/aurora-open-api-documentation) (needs free registration to view documentation) and their devices responds with "`422 Unprocessable Entity`" if request is consists from multiple TCP packet. Maybe this is a bug is their devices firmware but my first cURL client implementation worked fine with its simple `curl_easy_*()` API.
2. I did't implement it in `BufferStream` at all so implementation is from parent class `Stream`. Not sure about efficiency in this case.

**Comment by yhirose** [comment]
@DJm00n, thanks for the answers. I probably understand what you mean now. The device requires that HTTP header and HTTP body should be sent at a time, but HTTP request line can be send separately, right?
I'll take care of it when I have time.

**Comment by yhirose** [comment]
@DJm00n, I finally got time to work on it. I basically took your suggestion as it is. Thanks for your great contribution!

**Comment by DJm00n** [comment]
@yhirose, thank you!
