### ISSUE TITLE
The server's throughput and performance details?

### ISSUE THREAD

**Issue by alphamarket** [yhirose/cpp-httplib#970]
I cannot find any documentation on the number of workers and stats, on how many threads do you process requests? is there no limit or is there any configuration that we can configure the limit?

Regarding the performance, do you process the headers on-demand or all the time when a request comes in?

**Comment by yhirose** [comment]
As for the default ThreadPool, you can see the information [here](https://github.com/yhirose/cpp-httplib#default-thread-pool-support) in README. What it does is [here](https://github.com/yhirose/cpp-httplib/blob/9648f950f5a8a41d18833cf4a85f5821b1bcac54/httplib.h#L509-L577). Hope these answer your performance questions.

Honestly, if you need better task management, I don't recommend to use the default thread pool implementation which uses portable C++ standard thread library. Rather, you can implement `TaskQueue` with your own special algorithm or OS provided library like Microsoft TPL, and use it with cpp-httplib server to gain full performance on your environment.

Hope it helps!

**Comment by alphamarket** [comment]
Thanks, that information did help!
What about processing the headers on demand, for sure that will help to increase the throughput, for instance, the library can only process the first line to pick up the HTTP version and the requested path and when for the first time the client program asks for any headers it processes the headers. I wrote an HTTP server that does it and it really helped me gain performance back then.

**Comment by yhirose** [comment]
I think I don't do on-demand header processing. (Sorry that I don't fully understand what it mean actually...) The server code to read and parse the request line and headers is [here](https://github.com/yhirose/cpp-httplib/blob/9648f950f5a8a41d18833cf4a85f5821b1bcac54/httplib.h#L5175-L5180).

After reading and parsing headers, the information goes into `Request`. After that, the server take a look at some header values, and eventually pass the request object to the router.

**Comment by alphamarket** [comment]
@yhirose `On-demand processing headers` means you don't process the headers until someone in the callback asks for any heads via `has_header` & `get_header_value` methods. so many times the callback doesn't want to do something with the headers, why we process it beforehand?
