### ISSUE TITLE
"unresolved external symbol" when linking openssl on VS 2019

### ISSUE THREAD

**Issue by SJS830** [yhirose/cpp-httplib#973]
I am linking libcrypto.lib and libssl.lib from openssl 1.1.1 to my project, This is my stacktrace:

`
Error	LNK2019	unresolved external symbol _ASN1_STRING_get0_data referenced in function "private: bool __thiscall httplib::SSLClient::verify_host_with_subject_alt_name(struct x509_st *)const " (?verify_host_with_subject_alt_name@SSLClient@httplib@@ABE_NPAUx509_st@@@Z)		
Error	LNK2019	unresolved external symbol _ASN1_STRING_length referenced in function "private: bool __thiscall httplib::SSLClient::verify_host_with_subject_alt_name(struct x509_st *)const " (?verify_host_with_subject_alt_name@SSLClient@httplib@@ABE_NPAUx509_st@@@Z)		
Error	LNK2019	unresolved external symbol _BIO_ctrl referenced in function "struct ssl_st * __cdecl httplib::detail::ssl_new<class <lambda_eafd05591aa132e2b1f377c2149d4a77>,class <lambda_dc75220d722fb4da5da29f12c20ad857> >(unsigned int,struct ssl_ctx_st *,class std::mutex &,class <lambda_eafd05591aa132e2b1f377c2149d4a77>,class <lambda_dc75220d722fb4da5da29f12c20ad857>)" (??$ssl_new@V<lambda_eafd05591aa132e2b1f377c2149d4a77>@@V<lambda_dc75220d722fb4da5da29f12c20ad857>@@@detail@httplib@@YAPAUssl_st@@IPAUssl_ctx_st@@AAVmutex@std@@V<lambda_eafd05591aa132e2b1f377c2149d4a77>@@V<lambda_dc75220d722fb4da5da29f12c20ad857>@@@Z)		
Error	LNK2019	unresolved external symbol _BIO_new_socket referenced in function "struct ssl_st * __cdecl httplib::detail::ssl_new<class <lambda_eafd05591aa132e2b1f377c2149d4a77>,class <lambda_dc75220d722fb4da5da29f12c20ad857> >(unsigned int,struct ssl_ctx_st *,class std::mutex &,class <lambda_eafd05591aa132e2b1f377c2149d4a77>,class <lambda_dc75220d722fb4da5da29f12c20ad857>)" (??$ssl_new@V<lambda_eafd05591aa132e2b1f377c2149d4a77>@@V<lambda_dc75220d722fb4da5da29f12c20ad857>@@@detail@httplib@@YAPAUssl_st@@IPAUssl_ctx_st@@AAVmutex@std@@V<lambda_eafd05591aa132e2b1f377c2149d4a77>@@V<lambda_dc75220d722fb4da5da29f12c20ad857>@@@Z)		
Error	LNK2019	unresolved external symbol _d2i_X509 referenced in function "bool __cdecl httplib::detail::load_system_certs_on_windows(struct x509_store_st *)" (?load_system_certs_on_windows@detail@httplib@@YA_NPAUx509_store_st@@@Z)		
Error	LNK2019	unresolved external symbol _GENERAL_NAMES_free referenced in function "private: bool __thiscall httplib::SSLClient::verify_host_with_subject_alt_name(struct x509_st *)const " (?verify_host_with_subject_alt_name@SSLClient@httplib@@ABE_NPAUx509_st@@@Z)		
Error	LNK2019	unresolved external symbol _MD5_Final referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl httplib::detail::MD5(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?MD5@detail@httplib@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV34@@Z)		
Error	LNK2019	unresolved external symbol _MD5_Init referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl httplib::detail::MD5(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?MD5@detail@httplib@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV34@@Z)		
Error	LNK2019	unresolved external symbol _MD5_Update referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl httplib::detail::MD5(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?MD5@detail@httplib@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV34@@Z)		
Error	LNK2019	unresolved external symbol _OPENSSL_init_ssl referenced in function "public: __thiscall httplib::detail::SSLInit::SSLInit(void)" (??0SSLInit@detail@httplib@@QAE@XZ)		
Error	LNK2019	unresolved external symbol _OPENSSL_sk_num referenced in function _sk_GENERAL_NAME_num		
Error	LNK2019	unresolved external symbol _OPENSSL_sk_value referenced in function _sk_GENERAL_NAME_value		
Error	LNK2019	unresolved external symbol _SHA256_Final referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl httplib::detail::SHA_256(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SHA_256@detail@httplib@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV34@@Z)		
Error	LNK2019	unresolved external symbol _SHA256_Init referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl httplib::detail::SHA_256(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SHA_256@detail@httplib@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV34@@Z)		
Error	LNK2019	unresolved external symbol _SHA256_Update referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl httplib::detail::SHA_256(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SHA_256@detail@httplib@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV34@@Z)		
Error	LNK2019	unresolved external symbol _SHA512_Final referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl httplib::detail::SHA_512(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SHA_512@detail@httplib@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV34@@Z)		
Error	LNK2019	unresolved external symbol _SHA512_Init referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl httplib::detail::SHA_512(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SHA_512@detail@httplib@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV34@@Z)		
Error	LNK2019	unresolved external symbol _SHA512_Update referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl httplib::detail::SHA_512(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SHA_512@detail@httplib@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV34@@Z)		
Error	LNK2019	unresolved external symbol _SSL_connect referenced in function "public: bool __thiscall <lambda_eafd05591aa132e2b1f377c2149d4a77>::operator()(struct ssl_st *)const " (??R<lambda_eafd05591aa132e2b1f377c2149d4a77>@@QBE_NPAUssl_st@@@Z)		
Error	LNK2019	unresolved external symbol _SSL_ctrl referenced in function "public: __thiscall httplib::detail::SSLSocketStream::SSLSocketStream(unsigned int,struct ssl_st *,__int64,__int64,__int64,__int64)" (??0SSLSocketStream@detail@httplib@@QAE@IPAUssl_st@@_J111@Z)		
Error	LNK2019	unresolved external symbol _SSL_CTX_free referenced in function "public: __thiscall httplib::SSLClient::SSLClient(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0SSLClient@httplib@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H00@Z)		
Error	LNK2019	unresolved external symbol _SSL_CTX_get_cert_store referenced in function "public: void __thiscall <lambda_e9b8453515739d8dce6e1e15798c14e3>::operator()(void)const " (??R<lambda_e9b8453515739d8dce6e1e15798c14e3>@@QBEXXZ)		
Error	LNK2019	unresolved external symbol _SSL_CTX_load_verify_locations referenced in function "public: void __thiscall <lambda_e9b8453515739d8dce6e1e15798c14e3>::operator()(void)const " (??R<lambda_e9b8453515739d8dce6e1e15798c14e3>@@QBEXXZ)		
Error	LNK2019	unresolved external symbol _SSL_CTX_new referenced in function "public: __thiscall httplib::SSLClient::SSLClient(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0SSLClient@httplib@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H00@Z)		
Error	LNK2019	unresolved external symbol _SSL_CTX_use_certificate_file referenced in function "public: __thiscall httplib::SSLClient::SSLClient(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0SSLClient@httplib@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H00@Z)		
Error	LNK2019	unresolved external symbol _SSL_CTX_use_PrivateKey_file referenced in function "public: __thiscall httplib::SSLClient::SSLClient(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0SSLClient@httplib@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H00@Z)		
Error	LNK2019	unresolved external symbol _SSL_free referenced in function "struct ssl_st * __cdecl httplib::detail::ssl_new<class <lambda_eafd05591aa132e2b1f377c2149d4a77>,class <lambda_dc75220d722fb4da5da29f12c20ad857> >(unsigned int,struct ssl_ctx_st *,class std::mutex &,class <lambda_eafd05591aa132e2b1f377c2149d4a77>,class <lambda_dc75220d722fb4da5da29f12c20ad857>)" (??$ssl_new@V<lambda_eafd05591aa132e2b1f377c2149d4a77>@@V<lambda_dc75220d722fb4da5da29f12c20ad857>@@@detail@httplib@@YAPAUssl_st@@IPAUssl_ctx_st@@AAVmutex@std@@V<lambda_eafd05591aa132e2b1f377c2149d4a77>@@V<lambda_dc75220d722fb4da5da29f12c20ad857>@@@Z)		
Error	LNK2019	unresolved external symbol _SSL_get_error referenced in function "bool __cdecl httplib::detail::ssl_connect_or_accept_nonblocking<int (__cdecl*)(struct ssl_st *)>(unsigned int,struct ssl_st *,int (__cdecl*)(struct ssl_st *),__int64,__int64)" (??$ssl_connect_or_accept_nonblocking@P6AHPAUssl_st@@@Z@detail@httplib@@YA_NIPAUssl_st@@P6AH0@Z_J2@Z)		
Error	LNK2019	unresolved external symbol _SSL_get_peer_certificate referenced in function "public: bool __thiscall <lambda_eafd05591aa132e2b1f377c2149d4a77>::operator()(struct ssl_st *)const " (??R<lambda_eafd05591aa132e2b1f377c2149d4a77>@@QBE_NPAUssl_st@@@Z)		
Error	LNK2019	unresolved external symbol _SSL_get_verify_result referenced in function "public: bool __thiscall <lambda_eafd05591aa132e2b1f377c2149d4a77>::operator()(struct ssl_st *)const " (??R<lambda_eafd05591aa132e2b1f377c2149d4a77>@@QBE_NPAUssl_st@@@Z)		
Error	LNK2019	unresolved external symbol _SSL_new referenced in function "struct ssl_st * __cdecl httplib::detail::ssl_new<class <lambda_eafd05591aa132e2b1f377c2149d4a77>,class <lambda_dc75220d722fb4da5da29f12c20ad857> >(unsigned int,struct ssl_ctx_st *,class std::mutex &,class <lambda_eafd05591aa132e2b1f377c2149d4a77>,class <lambda_dc75220d722fb4da5da29f12c20ad857>)" (??$ssl_new@V<lambda_eafd05591aa132e2b1f377c2149d4a77>@@V<lambda_dc75220d722fb4da5da29f12c20ad857>@@@detail@httplib@@YAPAUssl_st@@IPAUssl_ctx_st@@AAVmutex@std@@V<lambda_eafd05591aa132e2b1f377c2149d4a77>@@V<lambda_dc75220d722fb4da5da29f12c20ad857>@@@Z)		
Error	LNK2019	unresolved external symbol _SSL_pending referenced in function "public: virtual int __thiscall httplib::detail::SSLSocketStream::read(char *,unsigned int)" (?read@SSLSocketStream@detail@httplib@@UAEHPADI@Z)		
Error	LNK2019	unresolved external symbol _SSL_read referenced in function "public: virtual int __thiscall httplib::detail::SSLSocketStream::read(char *,unsigned int)" (?read@SSLSocketStream@detail@httplib@@UAEHPADI@Z)		
Error	LNK2019	unresolved external symbol _SSL_set_bio referenced in function "struct ssl_st * __cdecl httplib::detail::ssl_new<class <lambda_eafd05591aa132e2b1f377c2149d4a77>,class <lambda_dc75220d722fb4da5da29f12c20ad857> >(unsigned int,struct ssl_ctx_st *,class std::mutex &,class <lambda_eafd05591aa132e2b1f377c2149d4a77>,class <lambda_dc75220d722fb4da5da29f12c20ad857>)" (??$ssl_new@V<lambda_eafd05591aa132e2b1f377c2149d4a77>@@V<lambda_dc75220d722fb4da5da29f12c20ad857>@@@detail@httplib@@YAPAUssl_st@@IPAUssl_ctx_st@@AAVmutex@std@@V<lambda_eafd05591aa132e2b1f377c2149d4a77>@@V<lambda_dc75220d722fb4da5da29f12c20ad857>@@@Z)		
Error	LNK2019	unresolved external symbol _SSL_set_verify referenced in function "public: bool __thiscall <lambda_eafd05591aa132e2b1f377c2149d4a77>::operator()(struct ssl_st *)const " (??R<lambda_eafd05591aa132e2b1f377c2149d4a77>@@QBE_NPAUssl_st@@@Z)		
Error	LNK2019	unresolved external symbol _SSL_shutdown referenced in function "struct ssl_st * __cdecl httplib::detail::ssl_new<class <lambda_eafd05591aa132e2b1f377c2149d4a77>,class <lambda_dc75220d722fb4da5da29f12c20ad857> >(unsigned int,struct ssl_ctx_st *,class std::mutex &,class <lambda_eafd05591aa132e2b1f377c2149d4a77>,class <lambda_dc75220d722fb4da5da29f12c20ad857>)" (??$ssl_new@V<lambda_eafd05591aa132e2b1f377c2149d4a77>@@V<lambda_dc75220d722fb4da5da29f12c20ad857>@@@detail@httplib@@YAPAUssl_st@@IPAUssl_ctx_st@@AAVmutex@std@@V<lambda_eafd05591aa132e2b1f377c2149d4a77>@@V<lambda_dc75220d722fb4da5da29f12c20ad857>@@@Z)		
Error	LNK2019	unresolved external symbol _SSL_write referenced in function "public: virtual int __thiscall httplib::detail::SSLSocketStream::write(char const *,unsigned int)" (?write@SSLSocketStream@detail@httplib@@UAEHPBDI@Z)		
Error	LNK2019	unresolved external symbol _TLS_client_method referenced in function "public: __thiscall httplib::SSLClient::SSLClient(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0SSLClient@httplib@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H00@Z)		
Error	LNK2019	unresolved external symbol _X509_free referenced in function "public: bool __thiscall <lambda_eafd05591aa132e2b1f377c2149d4a77>::operator()(struct ssl_st *)const " (??R<lambda_eafd05591aa132e2b1f377c2149d4a77>@@QBE_NPAUssl_st@@@Z)		
Error	LNK2019	unresolved external symbol _X509_get_ext_d2i referenced in function "private: bool __thiscall httplib::SSLClient::verify_host_with_subject_alt_name(struct x509_st *)const " (?verify_host_with_subject_alt_name@SSLClient@httplib@@ABE_NPAUx509_st@@@Z)		
Error	LNK2019	unresolved external symbol _X509_get_subject_name referenced in function "private: bool __thiscall httplib::SSLClient::verify_host_with_common_name(struct x509_st *)const " (?verify_host_with_common_name@SSLClient@httplib@@ABE_NPAUx509_st@@@Z)		
Error	LNK2019	unresolved external symbol _X509_NAME_get_text_by_NID referenced in function "private: bool __thiscall httplib::SSLClient::verify_host_with_common_name(struct x509_st *)const " (?verify_host_with_common_name@SSLClient@httplib@@ABE_NPAUx509_st@@@Z)		
Error	LNK2019	unresolved external symbol _X509_STORE_add_cert referenced in function "bool __cdecl httplib::detail::load_system_certs_on_windows(struct x509_store_st *)" (?load_system_certs_on_windows@detail@httplib@@YA_NPAUx509_store_st@@@Z)		
`

What else do I have to do to link openssl to my project?

**Comment by yhirose** [comment]
Hope [this](https://github.com/yhirose/cpp-httplib#ssl-support) in README helps.

**Comment by SJS830** [comment]
Including winsock2.h **before** windows.h fixed it for me.
