### ISSUE TITLE
Posting JSON Array

### ISSUE THREAD

**Issue by lordbendtner1337** [yhirose/cpp-httplib#975]
Not an issue per say, however I am having troubles figuring out how to post an array of objects.

For example, you can easily post a single object like;
httplib::Params params;
params.emplace( "uniqueid", pPlayer->strUniqueId );
params.emplace( "ip", pPlayer->strIP );

auto res = cli.Post( ( RequestURL + "/player" ).c_str( ), params );

However, how would I go about adding multiple "player" objects as a parameter?

Are there currently a way that I could post like this;
httplib::Params params[ 100 ];

**Comment by yhirose** [comment]
@lordbendtner1337, sorry that there is not way to pass an array of `httplib::Params`. This is for 'application/x-www-form-urlencoded' content type.
