### ISSUE TITLE
Cannot get (a list of) all cookies

### ISSUE THREAD

**Issue by sp22214** [yhirose/cpp-httplib#976]
Hi, 

I've recently switched from libcurl to cpp-httplib and I can't find get any header named "Set-Cookie" or "Cookie" from the client-side. 
Using libcurl I was able to get a list of all cookies using the below calls:
       curl_easy_setopt(curlInstance, CURLOPT_COOKIEFILE, "");
       curl_easy_getinfo(curlInstace, CURLINFO_COOKIELIST, &curl_jar);

What's the correct way of getting all cookies (both Client and SSLClient)?

Thanks

**Comment by yhirose** [comment]
@sp22214, since 'Set-Cookie' is just HTTP header value, you can read it with `get_header_value` and `get_header_value_count`. Hope it helps.

**Comment by sp22214** [comment]
thanks, that's what I understood. If I just call:
res = cli.Get(path);
The "res" will have a bunch of headers, but none is "Set-Cookie". This is a Jupyter Hub server I'm trying to communicate with, but if I just use a test host like "www.ikea.com" it provides "Set-Cookie" in the list of headers. The issue is that using libcurl after the call to "curl_easy_setopt(curlInstance, CURLOPT_COOKIEFILE, "");" I was able to get a bunch of "Set-Cookie" headers using Jupyter hub (and the server can be even irrelevant to this problem). 

I understand that curl has a different set of calls and a one-to-one conversion is either not possible or not needed. I'm looking for a missing call or calls that are needed to get similar cookies (that normally are not given). I could not find such a call in the example files from cpp-httplib.
