### ISSUE TITLE
Public Key Pinning

### ISSUE THREAD

**Issue by liob** [yhirose/cpp-httplib#977]
Hi, does cpp-httplib support public key pinning? I found no obvious way by reading the header file. Thanks.

**Comment by yhirose** [comment]
@liob, no, sorry about that.

**Comment by valden** [comment]
was the issue closed due to this feature was implemented?

**Comment by realkarmakun** [comment]
Will it be supported? SSL pinning sounds like an important feature of https stack

**Comment by yhirose** [comment]
No, I am not planning to support it.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning

**Comment by valden** [comment]
Are Certificate Transparency and Expect-CT supported by cpp-httplib?
Note: Public Key Pinning mechanism was deprecated in favor of [Certificate Transparency](https://developer.mozilla.org/en-US/docs/Web/Security/Certificate_Transparency) and [Expect-CT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT) header.

**Comment by realkarmakun** [comment]
Certificate Transparency and Expect-CT are made for browsers. I'd like to enforce connection with specific SSL cert only

**Comment by chausner** [comment]
I'm new to OpenSSL but what seems to work is using `Client::ssl_context()` to obtain an instance of `SSL_CTX` which can be passed to [SSL_CTX_set_verify](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_verify.html) for registering a custom validation callback function. In the callback, one can then retrieve the public key of the certificate and check if it matches the expected key.

Here's some sample code:
```c++
#include "httplib/httplib.h"
#include "openssl/crypto.h"
#include "openssl/ssl.h"
#include "openssl/x509.h"
#include "openssl/x509_vfy.h"
#include <algorithm>
#include <vector>

extern "C" int verify_callback(int preverify_ok, X509_STORE_CTX *x509_ctx) {
    // early exit if certificate validation failed
    if (!preverify_ok) {
        return false;
    }

    X509 *current_cert = X509_STORE_CTX_get_current_cert(x509_ctx);
    X509 *cert = X509_STORE_CTX_get0_cert(x509_ctx);

    // verify_callback is called for every certificate in the chain
    // but we are only interested in the end-entity certificate
    if (current_cert != cert) {
        return true;
    }

    // get public key in DER format
    EVP_PKEY *pkey = X509_get_pubkey(cert);
    if (pkey == nullptr) {
        return false;
    }
    unsigned char *der_pkey = nullptr;
    int der_pkey_length = i2d_PUBKEY(pkey, &der_pkey);

    // expected public key, can be obtained from a certificate file via:
    //     openssl x509 -in my-certificate.crt -pubkey -noout | openssl pkey -pubin -outform der | xxd
    // or from a host via:
    //     openssl s_client -servername example.com -connect example.com:443 < /dev/null | openssl x509 -pubkey -noout | openssl rsa -pubin -outform der | xxd
    static const std::vector<unsigned char> expected_pkey { /* ... */  };

    // compare for equality
    bool match = der_pkey_length == expected_pkey.size() && std::equal(der_pkey, der_pkey + der_pkey_length, expected_pkey.data());

    OPENSSL_free(der_pkey);

    return match;
}

int main() {
    httplib::Client cli("https://example.com");

    SSL_CTX_set_verify(cli.ssl_context(), SSL_VERIFY_PEER, verify_callback);

    auto res = cli.Get("/");
    if (res != nullptr) {
        std::cout << "Request succeeded. Status: " << res->status << std::endl;
        return 0;
    } else {
        std::cerr << "Request failed." << std::endl;
        return 1;
    }
}
```
