### ISSUE TITLE
I want to transfer binary files with a size of 256KB per piece, how do I increase the RECV BUFF?

### ISSUE THREAD

**Issue by zerolslong** [yhirose/cpp-httplib#982]
I want to transfer binary files with a size of 256KB per piece, how do I increase the RECV BUFF?

**Comment by yhirose** [comment]
You can modify `CPPHTTPLIB_RECV_BUFSIZ`.

**Comment by zerolslong** [comment]
I tried to increase the size of the buff, but received a size < 10*1024

**Comment by zerolslong** [comment]
#ifndef CPPHTTPLIB_RECV_BUFSIZ
#define CPPHTTPLIB_RECV_BUFSIZ size_t(266240u)
#endif

**Comment by yhirose** [comment]
The actual read size is out of our control because the OS system call or WinSock2 API `recv` dictate it. Sorry...

**Comment by zerolslong** [comment]
Thanks for the answer, I think it's a problem on our side, I've probably found the problem, thanks again
