### ISSUE TITLE
Is it possible for httplib::Server to receive file data from a command (ie curl)

### ISSUE THREAD

**Issue by jeffopolis** [yhirose/cpp-httplib#983]
I'm looking through the documentation and I'm not seeing anything that's helping me, but perhaps I'm just overlooking it...

Say I'm using a curl command like:

    curl --request POST --form "file='path/to/file.txt'" http://localhost/upload

How can I receive the file data from the client trying to send the data?

**Comment by yhirose** [comment]
Unfortunately, there is no convenient way like curl's `--form` option. But here is the information that might help you in README.

```
httplib::MultipartFormDataItems items = {
  { "text1", "text default", "", "" },
  { "text2", "aωb", "", "" },
  { "file1", "h\ne\n\nl\nl\no\n", "hello.txt", "text/plain" },
  { "file2", "{\n  \"world\", true\n}\n", "world.json", "application/json" },
  { "file3", "", "", "application/octet-stream" },
};

auto res = cli.Post("/multipart", items);
```

So, as for your 'multiple/form-data' example , you have to open `path/to/file.txt` and prepare `httplib::MultipartFormDataItems` by yourself, and simply pass it to `Post` method.

Hope it helps!

**Comment by jeffopolis** [comment]
@yhirose Thanks for the quick  response, however I was referring to the httplib _receiving_ such a command. For example, say I have a server with the following:

    httplib::Server server;
    server.Post( "/upload", [ & ]( const httplib::Request& req, httplib::Response& res ) {
            // How to receive the file here?
    } );

And I issue the curl command via command line, trying to upload the file to my server:

    curl --request POST --form "file='path/to/file.txt'" http://localhost/upload
