### ISSUE TITLE
Download something by just providing the complete URL?

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [yhirose/cpp-httplib#984]
I'm new to this library, so I'm not sure whether what I'm trying to do is possible, but after playing with the library a little bit, it seems very weird how it works...

Why do I have to enter the domain/host in the constructor of `httplib::Client`, and then separately provide the complete path to the file I need to reach? ... As a developer who just wants to retrieve a file, why should I care and not just hand the full URL to the library and expect it to do the download for me?! This is a very weird design decision and makes moving from cURL to this library an order of magnitude harder because it cannot be used as a drop-in replacement, which I was planning to do.

Nevertheless, thanks for the nice library. C++ needed something like this for a very long time... I'm abandoning cURL because of its complexity.

**Comment by yhirose** [comment]
@TheQuantumPhysicist, sorry that this doesn't meet your requirement. This design enables us to issue multiple HTTP requests via a same TCP connection with HTTP KeepAlive.

Microsoft cpprestsdk also takes the same approach.
https://github.com/Microsoft/cpprestsdk/wiki/Getting-Started-Tutorial

Hope it helps!

**Comment by TheQuantumPhysicist** [comment]
Maybe this feature can be added? Please consider it. It's very useful.

**Comment by PixlRainbow** [comment]
@yhirose I can't remember why it was done, but was `Client2` removed?

**Comment by yhirose** [comment]
@PixlRainbow, `Client2` wasn't taking a while URL, but the exactly same as the `host_and_port` interface on `Client`.

**Comment by PixlRainbow** [comment]
I thought I remember there used to be a simple client or simple get or something

**Comment by poor1017** [comment]
@yhirose Hi, does this feature supported now? Or maybe I need use `curl_easy_perform` in my httplib code.
