### ISSUE TITLE
DLL gets locked when linked against OpenSSL 1.1.1j

### ISSUE THREAD

**Issue by hbeni** [yhirose/cpp-httplib#986]
Hi there,
I really could use some help with the following issue.

I have a plugin for mumble in the works, which faciliates an updater. Mumble can load and unload the plugins. They are just DLLs exporting a bunch of functions. Mumble also has an updater, that calls a plugin function to get the latest download URL. It then fetches the new plugin, **unloads the current one if loaded**, and then :warning: **_deletes the old plugin dll_** to overwrite it with the downloaded version.

This is the point where I get problems:
As soon as I compile against OpenSSL (1.1.1j is in effect here) the DLL gets locked and thus cannot be deleted by mumble.

- We already tracked this down to be specifically related to cpp-httplib and/or OpenSSL
- We ruled out it'ts a mumble or generic plugin issue
- I think the Problem is something in OpenSSL or maybe the way cpp-httplib instanciates/uses it
- Just linking OpenSSL does not trigger the issue, it is only there if `#define CPPHTTPLIB_OPENSSL_SUPPORT 1`

I hoped you could see if there is a problem in the cpp-httplib regarding usage of OpenSSL.

----
Details:

- Code is specifically here: https://github.com/hbeni/fgcom-mumble/blob/master/client/mumble-plugin/lib/updater.cpp
- We track it here, for further information: https://github.com/hbeni/fgcom-mumble/issues/131

**Comment by yhirose** [comment]
@hbeni, thanks for the feedback, but I probably cannot give you any meaningful help since I don't fully understand your environment. The only thing I can tell at this point is that you may want to look into the constructor and destructor of `SSLServer` and `SSLClient` where all the OpenSSL activities start. Hope it help!

**Comment by hbeni** [comment]
Thank you, will do!
But maybe you could skim trough my updater code if you see something I do wrong wit the httplib?

https://github.com/hbeni/fgcom-mumble/blob/5d2125f1c296bc7cd64537a14eab2f828d766486/client/mumble-plugin/lib/updater.cpp#L143-L260

**Comment by hbeni** [comment]
Just as an idea: wolfSSL is not supported, I guess?

**Comment by yhirose** [comment]
No, also I am not planning to support it. You may want to check the following as well.

https://github.com/yhirose/cpp-httplib/blob/80be649de7cd821652aa1be4d0c9cf5930f18225/httplib.h#L6738

**Comment by hbeni** [comment]
Looking at it again; I have a question.

In my code, inside a function, I do:
```c++
void fgcom_getLatestReleaseFromGithub_Web() {
  ...
  httplib::SSLClient cli(host.c_str());
...
}
``` 
I assumed that after the function is complete, everything is cleaned up.
Is that maybe not the case, and I have to unload/destroy/free something regarding `cli` manually?

**Comment by yhirose** [comment]
Yes or no. Everything in `httplib::SSLClient` is cleaned up, but the global variable `static SSLInit sslinit_;` stays. You probably have to change the global variable to be unloadable manually.

**Comment by hbeni** [comment]
OK, I found out something by accident.
I wondered if it might have to do with the OpenSSL version, and indeed it has.

Versions `1.1.1a` and `1.1.1b` are working fine, but any 1.1.1 after that has the issue.
So it is surely something in OpenSSL's codebase.
