### ISSUE TITLE
IPv6 addresses in host header not escaped

### ISSUE THREAD

**Issue by gjasny** [yhirose/cpp-httplib#998]
Hello,

thanks for taking care of #979. Unfortunately the `Host` header still looks wrong:

```
GET /cache/8e193hu1ntu7bvd6ohhsrncr94hibhn8s HTTP/1.1
Accept: */*
Host: ::1:8080
User-Agent: ccache/master.b7e6280e
```

Maybe you could use a dedicated URL class for parsing like: [CxxUrl](https://github.com/chmike/CxxUrl)?

Thanks,
Gregor

_Originally posted by @gjasny in https://github.com/yhirose/cpp-httplib/issues/979#issuecomment-880440594_

**Comment by gjasny** [comment]
For your convenience I added a test case.

**Comment by yhirose** [comment]
@gjasny, should it look like `[::1]:8080`? Can you find the RFC or other reliable source to describe what format I should be? Thanks for your help.

> Maybe you could use a dedicated URL class for parsing like: CxxUrl?
The selling point of this library is that it doesn't depend on any other third party library except OpenSSL, compression libraries.

**Comment by gjasny** [comment]
The closest I could find is: https://bugzilla.mozilla.org/show_bug.cgi?id=45891

**Comment by yhirose** [comment]
Thanks for the valuable information!
